"use client";
// 👪 حزمة العائلة المتقدمة — ElternPaket (Modul V) في جناح التعليم
// ثلاثة أدوات مساندة للأسرة (لا أدوات شاردة):
//   🌍 Family Report بالإنجليزية — لأهل لا يتكلمون العربية ولا الألمانية
//   🎧 دليل Diktat منزلي — تسميع بورقة واحدة بلا أي ألمانية من الوالدين
//   📅 اجتماع الأحد — طقس أسبوعي بخمس خطوات يجمع العائلة حول التقدّم
import { useState } from "react";
import type { Progress } from "@/lib/types";
import { TOTAL_DAYS } from "@/lib/types";
import { sentences } from "@/lib/content";
import { levelOf, pickN, rng } from "@/lib/plan";
import { kompetenzWerte, b2Score, pruefungsBereitschaft, bereitBand, KOMPETENZEN } from "@/lib/kompetenz";
import { resistenteFehler, fehlerFamilien } from "@/lib/fehler";
import { empfehlungen } from "./berichte";
import { useProgress } from "@/lib/store";
import { checkAbzeichen } from "@/lib/spiel";
import { De } from "./De";

const EN_SKILL: Record<string, string> = {
  Lesen: "Reading", Hoeren: "Listening", Schreiben: "Writing", Sprechen: "Speaking", Grammatik: "Grammar", Wortschatz: "Vocabulary",
};
const EN_BAND = (v: number) =>
  v >= 80 ? "Ready for the exam" : v >= 65 ? "Nearly ready" : v >= 40 ? "On the way" : "Early stage — building foundations";

const NAMES: Record<string, string> = { Lesen: "reading", Hoeren: "listening", Schreiben: "writing", Sprechen: "speaking", Grammatik: "grammar", Wortschatz: "vocabulary" };

function druckeHtml(html: string, titel: string) {
  const fenster = window.open("", "_blank");
  if (!fenster) return;
  fenster.document.write(html);
  fenster.document.close();
  fenster.focus();
  setTimeout(() => fenster.print(), 350);
}

function familienBerichtHtml(p: Progress, name: string): string {
  const w = kompetenzWerte(p);
  const bereit = pruefungsBereitschaft(p);
  const fehler = Object.values(p.fehler ?? {});
  const resis = resistenteFehler(p);
  const tage = Object.values(p.plan.days ?? {}).filter((d) => d.closed).length;
  const schwach = [...KOMPETENZEN].sort((a, b) => w[a].wert - w[b].wert || a.localeCompare(b))[0];
  const rows = KOMPETENZEN.map((h) => `<tr><td>${EN_SKILL[h]}</td><td class="n">${w[h].wert}</td></tr>`).join("");
  const heute = new Date().toISOString().slice(0, 10);
  return `<!doctype html><html dir="ltr"><head><meta charset="utf-8"><title>Family Report — ${name}</title>
<style>
body{font-family:Georgia,serif;color:#2c2a25;background:#fff;margin:2rem;max-width:44rem}
h1{color:#355E3B;font-size:1.45rem;margin:0 0 .15rem}h2{color:#B03A2E;font-size:1.05rem;margin:1.1rem 0 .35rem}
.kopf{border-bottom:3px solid #355E3B;padding-bottom:.5rem;margin-bottom:.7rem}
.kacheln{display:flex;gap:.7rem;flex-wrap:wrap;margin:.5rem 0}
.kachel{border:1px solid #ddd;border-radius:.5rem;padding:.45rem .85rem;text-align:center}
.kachel b{display:block;font-size:1.35rem;color:#355E3B}
table{border-collapse:collapse;width:100%;max-width:26rem;font-size:.9rem}td,th{border:1px solid #ddd;padding:.28rem .55rem;text-align:left}
.n{text-align:center;font-weight:700}ol,ul{line-height:1.85}.fuss{margin-top:1.2rem;font-size:.75rem;color:#777;border-top:1px solid #ddd;padding-top:.45rem}
</style></head><body>
<div class="kopf">
<h1>🏠 Family Progress Report</h1>
<div><b>Way to B2</b> — Student: <b>${name}</b> · Day <b>${p.plan.day}</b>/${TOTAL_DAYS} · Issued: ${heute}</div>
</div>
<div class="kacheln">
<div class="kachel"><b>${bereit.gesamt}%</b>Exam readiness<br><small>${EN_BAND(bereit.gesamt)}</small></div>
<div class="kachel"><b>${b2Score(p)}</b>B2-Score</div>
<div class="kachel"><b>${tage}</b>Study days completed</div>
<div class="kachel"><b>${p.xp ?? 0}</b>XP earned</div>
<div class="kachel"><b>${fehler.length}</b>Mistakes tracked (${resis.length} stubborn)</div>
</div>
<h2>📊 Skill overview (0–100)</h2>
<table><tr><th>Skill</th><th class="n">Score</th></tr>${rows}</table>
<h2>🔎 This week's main focus</h2>
<p><b>${EN_SKILL[schwach]}</b> is the current bottleneck. At school we train it daily; at home, please reinforce it gently (see tips).</p>
<h2>💚 How to help at home — no German required</h2>
<ol>
<li><b>Dinner teaching:</b> ask your child to teach you 3 German words each evening. Teaching is the deepest form of learning.</li>
<li><b>5-minute dictation:</b> twice a week use our printed "Diktat at Home" sheet — play the sound, your child writes, check with the answer key.</li>
<li><b>Praise consistency, not perfection:</b> 15 calm minutes every day beat weekend marathons. Never correct mid-sentence; celebrate afterwards.</li>
</ol>
<h2>🧭 What we will do next week</h2>
<ul>${empfehlungen(p).map((e) => `<li>${e.text}</li>`).join("")}</ul>
<div class="fuss">Automated, deterministic report generated by the learning app from real study data. No accounts, no servers — your data stays on this device.</div>
</body></html>`;
}

function diktatGuideHtml(p: Progress, name: string): string {
  const lvl = levelOf(p.plan.day);
  const pool = sentences;
  const half = Math.floor(pool.length / 2);
  const seed = p.plan.day * 101 + 7;
  const items = [...pickN(pool.slice(0, half), 4, rng(seed)), ...pickN(pool.slice(half), 4, rng(seed + 9))];
  const zeilen = items
    .map(
      (s, i) => `<tr><td class="n">${i + 1}</td><td class="ar">${s.ar}</td><td class="linie">&nbsp;</td></tr>`
    )
    .join("");
  const schluessel = items.map((s, i) => `<tr><td class="n">${i + 1}</td><td>${s.de}</td></tr>`).join("");
  const heute = new Date().toISOString().slice(0, 10);
  return `<!doctype html><html><head><meta charset="utf-8"><title>Diktat zu Hause — ${name}</title>
<style>
body{font-family:Georgia,serif;color:#2c2a25;background:#fff;margin:1.6rem;max-width:44rem}
h1{color:#355E3B;font-size:1.35rem;margin:0 0 .2rem}h2{color:#B03A2E;font-size:1.05rem;margin:1rem 0 .3rem}
.ar{text-align:right;direction:rtl}.n{text-align:center;font-weight:700;width:2rem}
table{border-collapse:collapse;width:100%;font-size:.95rem}td,th{border:1px solid #ccc;padding:.4rem .55rem}
.linie{background:repeating-linear-gradient(transparent, transparent 1.55rem, #999 1.55rem, #999 1.6rem);height:1.9rem}
ol{line-height:1.9}.rtl{direction:rtl;text-align:right;line-height:1.9}
.fuss{margin-top:1rem;font-size:.75rem;color:#777;border-top:1px solid #ddd;padding-top:.4rem}
.bruch{border-top:2px dashed #B03A2E;margin:1.2rem 0 .6rem;position:relative}
.bruch span{position:absolute;top:-0.8rem;right:1rem;background:#fff;color:#B03A2E;font-size:.75rem;padding:0 .4rem}
</style></head><body>
<h1>🎧 Diktat zu Hause — التسميع المنزلي</h1>
<div class="rtl">ورقة أسبوعية للطالب <b>${name}</b> (المستوى ${lvl}) · ${heute} — يديرها وليّ الأمر <b>بلا أي ألمانية</b>.</div>
<h2 class="rtl">المنهجية الخمس (5 دقائق × مرتان أسبوعياً)</h2>
<ol class="rtl">
<li><b>شغّل الصوت</b> من التطبيق (زر 🔊) أو اقرأ الجملة الألمانية من عمود «المفتاح» أسفل الورقة بعد طيّها.</li>
<li><b>يكتب الطفل</b> ما يسمعه بالألمانية في السطر المخصّص — لا تُصحّح أثناء الكتابة.</li>
<li><b>قارنا معاً</b> مع المفتاح: ضع ✓ للصحيح، واحِط الخاطئ بدائرة.</li>
<li><b>الجملة الخاطئة</b> تُكتب ثلاث مرات بخط اليد.</li>
<li><b>امدح المحاولة لا النتيجة</b> — «أعجبني تركيزك» تصنع أكثر من «أخطأت».</li>
</ol>
<h2 class="rtl">قائمة هذا الأسبوع (8 جُمل — المعنى بالعربية يميناً)</h2>
<table><tr><th class="n">#</th><th class="ar">المعنى</th><th class="ar">اكتب الجملة الألمانية هنا</th></tr>${zeilen}</table>
<div class="bruch"><span>✂️ اطوِ هنا — المفتاح تحت! لا تطلّع عليه الطالب</span></div>
<h2>Muster &amp; Schlüssel — المفتاح</h2>
<table><tr><th class="n">#</th><th>Satz</th></tr>${schluessel}</table>
<div class="fuss">Way to B2 · Diktat-Bootcamp family sheet · generated deterministically for day ${p.plan.day}</div>
</body></html>`;
}

const MEETING_PROMPTS = [
  { emoji: "🎉", titel: "احتفال — ماذا أنجزتَ هذا الأسبوع؟", hint: "اذكر 3 أشياء تعلّمتها: كلمة جديدة · قاعدة · جملة نطقها صديقك الألماني وفهمها!" },
  { emoji: "📊", titel: "الأرقام — اقرؤها معاً من الشاشة", hint: "الجاهزية · B2-Score · الأيام المُغلقة · الأخطاء المتبقية (في مركز التقارير)." },
  { emoji: "💬", titel: "حديث الصعوبة — ما الأصعب عليك؟", hint: "اشرح لعائلتك بلغتك الأم: أين تتعثّر؟ الاستماع؟ الأدوات؟ ثم اختروا معاً حلاً واحداً." },
  { emoji: "🎯", titel: "أهداف الأسبوع القادم — ثلاثة فقط", hint: "قلّل الأهداف كي تُنجز: هدف لغوي · هدف عادة · هدف ممتع." },
  { emoji: "🎁", titel: "المكافأة — اتفاق العائلة", hint: "استمرار أسبوع كامل؟ اختاروا مكافأة صغيرة: نزهة · طبق مفضّل · ساعة لعب إضافية." },
];

export function ElternPaket({ progress, name = "المتعلّم" }: { progress: Progress; name?: string }) {
  const { update } = useProgress();
  const [open, setOpen] = useState(false);
  const [tab, setTab] = useState<"report" | "diktat" | "meeting">("report");
  const [haken, setHaken] = useState<Record<number, boolean>>({});
  const [geschlossen, setGeschlossen] = useState(false);
  const bereit = pruefungsBereitschaft(progress);

  return (
    <div className="card fadein" style={{ padding: "1.1rem 1.3rem", borderInlineStart: "5px solid var(--color-gold)" }}>
      <button style={{ background: "none", border: 0, cursor: "pointer", display: "flex", justifyContent: "space-between", width: "100%", alignItems: "center", minHeight: "44px", font: "inherit", color: "inherit", textAlign: "start" }} onClick={() => setOpen((o) => !o)}>
        <span style={{ fontWeight: 900, fontSize: "1.05rem", color: "var(--color-cola)" }}>
          👪 حزمة العائلة المتقدمة — ElternPaket <span style={{ fontSize: "0.75rem", color: "var(--color-ink2)" }}>(Modul V)</span>
        </span>
        <span className="chip">{open ? "إخفاء ▲" : "إظهار ▼"}</span>
      </button>
      <div style={{ fontSize: "0.8rem", color: "var(--color-ink2)", margin: "0.2rem 0 0.6rem" }}>
        ثلاث أدوات للأهل: تقرير بالإنجليزية لغير الناطقين · ورقة تسميع منزلية بلا ألمانية · طقس اجتماع الأحد — العائلة شريك لا متفرّج.
      </div>
      {open && (
        <>
          <div style={{ display: "flex", gap: "0.35rem", flexWrap: "wrap", marginBottom: "0.6rem" }}>
            {([
              { id: "report", n: "🌍 Family Report (EN)" },
              { id: "diktat", n: "🎧 Diktat zu Hause" },
              { id: "meeting", n: "📅 اجتماع الأحد" },
            ] as const).map((t) => (
              <button key={t.id} className="chip" style={{ cursor: "pointer", background: tab === t.id ? "var(--color-cola)" : "white", color: tab === t.id ? "white" : undefined }} onClick={() => setTab(t.id)}>
                {t.n}
              </button>
            ))}
          </div>

          {tab === "report" && (
            <div className="card" style={{ padding: "0.85rem 1.1rem", background: "var(--color-paper)" }}>
              <div style={{ fontWeight: 800 }}>🌍 Family Progress Report — بالإنجليزية</div>
              <div style={{ fontSize: "0.85rem", color: "var(--color-ink2)", margin: "0.35rem 0", lineHeight: 1.8 }}>
                صفحة مطبوعة واحدة للأهل الذين لا يتكلمون العربية ولا الألمانية: الأرقام الحقيقية · خريطة المهارات الست ·
                ثلاث نصائح منزلية (لا ألمانية مطلوبة) · تركيز الأسبوع القادم. يُطبع أو يُحفظ PDF.
              </div>
              <button className="btn btn-gold" onClick={() => druckeHtml(familienBerichtHtml(progress, name), "Family Report")}>
                🖨️ اطبع Family Report
              </button>
            </div>
          )}

          {tab === "diktat" && (
            <div className="card" style={{ padding: "0.85rem 1.1rem", background: "var(--color-paper)" }}>
              <div style={{ fontWeight: 800 }}>🎧 دليل التسميع المنزلي — Diktat zu Hause</div>
              <div style={{ fontSize: "0.85rem", color: "var(--color-ink2)", margin: "0.35rem 0", lineHeight: 1.8 }}>
                ورقة أسبوعية (8 جُمل من موسوعة مستواك): المعنى بالعربية + سطر للكتابة + <strong>مفتاح تصحيح بعد خطّ طيّ</strong> —
                يديرها وليّ الأمر بخمس خطوات مكتوبة بلا أي ألمانية. مرتان أسبوعياً × 5 دقائق = عجائب.
              </div>
              <button className="btn btn-gold" onClick={() => druckeHtml(diktatGuideHtml(progress, name), "Diktat zu Hause")}>
                🖨️ اطبع ورقة التسميع
              </button>
            </div>
          )}

          {tab === "meeting" && (
            <div style={{ display: "grid", gap: "0.5rem" }}>
              <div className="card" style={{ padding: "0.6rem 0.9rem", background: "var(--color-paper)", fontSize: "0.85rem" }}>
                📅 <strong>اجتماع الأحد (20 دقيقة)</strong> — نفس الجدول كل أسبوع: احتفال ← أرقام ← صعوبة ← أهداف ← مكافأة.
                الجاهزية الحالية: <span className="rtl-num" style={{ fontWeight: 800 }}>{bereit.gesamt}%</span> · أيام مُغلقة: <span className="rtl-num">{Object.values(progress.plan.days ?? {}).filter((d) => d.closed).length}</span> · مقاوم: <span className="rtl-num">{resistenteFehler(progress).length}</span>
              </div>
              {MEETING_PROMPTS.map((m, i) => (
                <button
                  key={i}
                  className="card"
                  style={{ display: "flex", gap: "0.5rem", width: "100%", textAlign: "start", padding: "0.55rem 0.85rem", cursor: "pointer", background: haken[i] ? "rgba(53,94,59,.08)" : "white", border: "1px solid var(--color-line)" }}
                  onClick={() => setHaken((x) => ({ ...x, [i]: !x[i] }))}
                >
                  <span>{haken[i] ? "✅" : m.emoji}</span>
                  <span>
                    <strong>{m.titel}</strong>
                    <div style={{ fontSize: "0.8rem", color: "var(--color-ink2)", lineHeight: 1.7 }}>{m.hint}</div>
                  </span>
                </button>
              ))}
              {geschlossen ? (
                <div className="card" style={{ padding: "0.7rem 0.9rem", fontWeight: 700, background: "var(--color-gold-soft)" }}>
                  🎉 اجتماع مغلق بنجاح — سُجّلت مشاركتك. نلتقي الأحد القادم بالأهداف نفسها حتى تتحقق.
                </div>
              ) : (
                <button
                  className="btn btn-gold"
                  disabled={Object.values(haken).filter(Boolean).length < 3}
                  onClick={() => {
                    setGeschlossen(true);
                    update((p) => checkAbzeichen({ ...p, xp: (p.xp ?? 0) + 5 }));
                  }}
                >
                  أغلق الاجتماع (≥3 خطوات) ✓
                </button>
              )}
            </div>
          )}
        </>
      )}
    </div>
  );
}
