# -*- coding: utf-8 -*-
"""Dialog-A1/A2: Fallen-Distraktoren (gehörte Anker, Anfängerniveau: Zahl/Ort/Person aus dem Dialog in falscher Rolle)."""
P = {
"d-a1-01-q1": dict(o=["aus Berlin","aus Tunesien","aus Deutschland, seit drei Monaten"], a="aus Tunesien",
  e="الدليل: «Ja, ich komme aus Tunesien. Ich wohne jetzt in Berlin». الفخّ 1: برلين مكان السكن الآن لا الأصل. الفخّ 2: «drei Monate» مدّة تعلّم الألمانية."),
"d-a1-02-q1": dict(o=["Kaffee mit Zucker","Kaffee mit ein bisschen Milch","Kaffee mit Milch und Zucker"], a="Kaffee mit ein bisschen Milch",
  e="الدليل: «Ein bisschen Milch, keinen Zucker». الفخّ: «Zucker» سُمع في سؤال النادل لكنّ سامي رفضه («keinen»)."),
"d-a1-03-q1": dict(o=["am Dienstag um zehn Uhr","am Donnerstag um zehn Uhr","am Dienstag um zwölf Uhr"], a="am Dienstag um zehn Uhr",
  e="الدليل: «Am Dienstag um zehn Uhr? — Am Dienstag bin ich frei». الفخّ 1: Dienstag/Donnerstag تشابه صوتي. الفخّ 2: zehn/zwölf تشابه صوتي."),
"d-a1-04-q2": dict(o=["drei Eier","sechs Eier","ein Kilo Eier"], a="sechs Eier",
  e="الدليل: «ein Brot und sechs Eier». الفخّ 1: ثلاثة هو سعر الطماطم باليورو. الفخّ 2: الكيلو للطماطم."),
"d-a1-05-q1": dict(o=["Er spielt Fußball mit Freunden.","Er besucht seine Tante.","Er lernt Deutsch zu Hause."], a="Er spielt Fußball mit Freunden.",
  e="الدليل: «Am Samstag spiele ich Fußball mit Freunden». الفخّ 1: العمّة يوم الأحد. الفخّ 2: تعلّم الألمانية برنامج لينا."),
"d-a2-01-q2": dict(o=["neben dem Reisebüro","im Zentrum, gegenüber vom Bahnhof","in München am Stadtrand"], a="im Zentrum, gegenüber vom Bahnhof",
  e="الدليل: «Ein Doppelzimmer im Zentrum, gegenüber vom Bahnhof». الفخّ 1: مكتب السفر مكان الحوار. الفخّ 2: ميونيخ صحيحة لكن «Stadtrand» يناقض «Zentrum»."),
"d-a2-02-q1": dict(o=["seinen Geburtstag","eine Party am Samstag um acht","den Geburtstag von Selma"], a="seinen Geburtstag",
  e="الدليل: «Am Samstag feiere ich meinen Geburtstag». الفخّ 1: الحفلة في «achtzehn Uhr» لا الثامنة. الفخّ 2: عيد ميلاد مهدي لا سلمى."),
"d-a2-03-q2": dict(o=["dreimal am Tag","zweimal am Tag","drei Tage lang einmal"], a="dreimal am Tag",
  e="الدليل: «Nehmen Sie die Medizin dreimal am Tag». الفخّ 1: «zwei» هو أيام البقاء في البيت. الفخّ 2: «drei Tage» مدّة ألم الحلق."),
"d-a2-04-q1": dict(o=["in Köln","in Frankfurt","nach vier Stunden"], a="in Frankfurt",
  e="الدليل: «in Frankfurt müssen Sie umsteigen». الفخّ 1: كولن الوجهة. الفخّ 2: أربع ساعات مدّة الرحلة."),
"d-a2-05-q1": dict(o=["Sie war krank.","Sie hat vergessen, zum Termin zu kommen.","Sie kann morgen nicht kommen."], a="Sie hat vergessen, zum Termin zu kommen.",
  e="الدليل: «Gestern habe ich vergessen, zum Termin zu kommen». الفخّ 1: المرض سأل عنه حسن ونفته سارة. الفخّ 2: الغد اقتراح حسن للقاء."),
"d-a1-06-q1": dict(o=["Ja, der Bus fährt zum Zentrum.","Nein, das ist die falsche Linie.","Ja, es ist die Nummer zwölf."], a="Nein, das ist die falsche Linie.",
  e="الدليل: «Das ist die falsche Linie. Sie müssen hier aussteigen». الفخّ: رقم 12 هو الحافلة الصحيحة «gegenüber»، لا هذه."),
"d-a1-07-q1": dict(o=["nur waschen","schneiden, nicht zu kurz","sehr kurz schneiden"], a="schneiden, nicht zu kurz",
  e="الدليل: «Nur schneiden, bitte. Nicht zu kurz!». الفخّ 1: الغسل اقتراح الحلّاق وافقت عليه لاحقاً كإضافة. الفخّ 2: «kurz» سُمع مع «nicht zu»."),
"d-a2-06-q2": dict(o=["den Kassenzettel","den Pullover in Größe M","die kleinere Größe zurück"], a="den Kassenzettel",
  e="الدليل: «Haben Sie den Kassenzettel dabei?». الفخّ 1: المقاس M هو ما تحصل عليه الزبونة. الفخّ 2: البلوفر الصغير تعيده هي، لكن البائع طلب الإيصال."),
"d-a2-07-q1": dict(o=["Frau Klein","Herr Yilmaz","der Bote gegen neun Uhr"], a="Herr Yilmaz",
  e="الدليل: «Ich habe Ihr Paket angenommen» — يقولها السيد يلماز. الفخّ 1: فراو كلاين صاحبة الطرد. الفخّ 2: الساعي سلّمه لا استلمه."),
"d-a1-08-q1": dict(o=["einen Kaffee mit Milch und einen Apfel","einen Kaffee mit Milch und ein Stück Kuchen","nur einen Apfel","einen Kaffee ohne Milch"], a="einen Kaffee mit Milch und einen Apfel",
  e="الدليل: «Einen Kaffee mit Milch, bitte» ثم «Nein, danke. Nur einen Apfel». الفخّ 1: الكعك رفضته. الفخّ 2: «nur» تخصّ الإضافة لا الطلب كلّه. الفخّ 3: مع حليب."),
"d-a1-08-q2": dict(o=["drei Euro fünfzig","fünf Euro fünfzig","drei Euro","fünfzig Cent"], a="drei Euro fünfzig",
  e="الدليل: «Das macht drei Euro fünfzig». الفخّان: «drei» و«fünfzig» يظهران منفصلين في الخيارات الخاطئة."),
"d-a1-09-q1": dict(o=["Herr Weber aus dem Büro","Frau Ibrahim","Sara","der Chef von Sara"], a="Herr Weber aus dem Büro",
  e="الدليل: «Hier ist Herr Weber aus dem Büro». الفخّ: سارة إبراهيم هي من ردّت («am Apparat»)، لا من اتّصل."),
"d-a1-09-q2": dict(o=["morgen um neun Uhr","heute um neun Uhr","morgen um neun Uhr im Büro von Sara","morgen um acht Uhr"], a="morgen um neun Uhr",
  e="الدليل: «Ist morgen um neun Uhr ein Termin möglich? — Ja, um neun Uhr passt gut». الفخّ 1: اليوم ≠ غداً. الفخّ 2: المكتب مكتب السيد فيبر لا مكان الموعد المذكور. الفخّ 3: acht/neun."),
"d-a2-08-q1": dict(o=["Halsschmerzen seit gestern Abend","Kopfschmerzen seit gestern","Halsschmerzen seit drei Tagen","Fieber und Husten"], a="Halsschmerzen seit gestern Abend",
  e="الدليل: «Ich habe Halsschmerzen» و«Seit gestern Abend». الفخّ 1: الرأس لم يُذكر. الفخّ 2: «drei Tage» ليست في هذا الحوار. الفخّ 3: لا حمّى ولا سعال هنا."),
"d-a2-08-q2": dict(o=["Lutschtabletten und einen Tee","nur Wasser","Tabletten zum Schlucken","einen Tee und Wasser zum Kaufen"], a="Lutschtabletten und einen Tee",
  e="الدليل: «Ich gebe Ihnen Lutschtabletten und einen Tee». الفخّ 1: الماء نصيحة للشرب لا دواء. الفخّ 2: «schlucken» ذُكر كألم. الفخّ 3: الماء لا يُباع هنا."),
"d-a2-09-q1": dict(o=["um vierzehn Uhr dreißig","um fünfzehn Uhr dreißig","um vierzehn Uhr von Gleis drei","um dreizehn Uhr dreißig"], a="um vierzehn Uhr dreißig",
  e="الدليل: «Um vierzehn Uhr dreißig, Gleis fünf». الفخّ 1: vierzehn/fünfzehn. الفخّ 2: الرصيف خمسة لا ثلاثة، و«dreißig» دقائق. الفخّ 3: dreizehn/dreißig."),
"d-a2-09-q2": dict(o=["eine Fahrkarte zweiter Klasse","eine Rückfahrkarte für neunundzwanzig Euro","eine Fahrkarte erster Klasse","fünf Fahrkarten"], a="eine Fahrkarte zweiter Klasse",
  e="الدليل: «Eine Fahrkarte zweiter Klasse, bitte». الفخّ 1: عن تذكرة العودة سأل فقط ولم يطلبها. الفخّ 2: erster/zweiter. الفخّ 3: «fünf» رقم الرصيف."),
"d-a1-31-q1": dict(o=["um neun Uhr bei Frau Bauer","um neun Uhr bei Herrn Haddad","um zehn Uhr bei Frau Bauer"], a="um neun Uhr bei Frau Bauer",
  e="الدليل: «Ja, um neun Uhr bei Frau Bauer». الفخّ 1: حدّاد هو المريض رامي. الفخّ 2: neun/zehn."),
"d-a1-32-q1": dict(o=["neben der Bank","an der Ampel","fünf Minuten geradeaus, dann links"], a="neben der Bank",
  e="الدليل: «Die Post ist neben der Bank». الفخّ 1: الإشارة نقطة الانعطاف. الفخّ 2: «rechts» لا «links»."),
"d-a2-31-q1": dict(o=["einen neuen Wasserkocher","ihr Geld zurück","eine Reparatur innerhalb von vierzehn Tagen"], a="ihr Geld zurück",
  e="الدليل: «Ich hätte gern mein Geld zurück». الفخّ 1: لم تطلب استبدالاً. الفخّ 2: 14 يوماً مهلة الاسترجاع، لا إصلاح."),
"d-a2-32-q1": dict(o=["einen Tag","drei Tage","bis heute Abend"], a="drei Tage",
  e="الدليل: «Der Arzt hat mich für drei Tage krankgeschrieben». الفخّ: «heute noch» موعد إرسال الشهادة بالبريد."),
}
