# -*- coding: utf-8 -*-
"""Dialog-B1: Fallen-Distraktoren (gehörte Anker). Siehe b2_dialog_fallen.py."""
P = {
"d-b1-01-q1": dict(o=["Man spart Zeit.","Man verliert den Kontakt.","Die Flexibilität überwiegt."], a="Man verliert den Kontakt.",
  e="الدليل: «Zwar spart man Zeit, aber man verliert den Kontakt». الفخّ 1: توفير الوقت هو الجزء المُسلَّم به «zwar» لا الاعتراض. الفخّ 2: «Flexibilität überwiegt» رأي مارا."),
"d-b1-02-q2": dict(o=["Er übernimmt mehr Verantwortung.","Die Firma meldet sich.","Er arbeitet drei Jahre als Techniker."], a="Die Firma meldet sich.",
  e="الدليل: «Wir melden uns nächste Woche bei Ihnen». الفخّ 1: المسؤولية هدفه المستقبلي العامّ لا الأسبوع القادم. الفخّ 2: السنوات الثلاث ماضٍ."),
"d-b1-03-q1": dict(o=["Die Verhandlungen haben begonnen.","Es gibt einen Streik.","Lea fährt jeden Tag mit dem Rad."], a="Es gibt einen Streik.",
  e="الدليل: «Der Streik geht weiter» و«die Züge fahren heute wieder nicht». الفخّ 1: المفاوضات بداية الحلّ لا المشكلة. الفخّ 2: الدرّاجة احتمال «sonst» لا واقع."),
"d-b1-04-q1": dict(o=["die Kartons im Flur","die Bücher","die enge Tür"], a="die Bücher",
  e="الدليل: «Die Bücher sind am schwersten». الفخّ 1: الكراتين مكانها في الممرّ، لا وزنها. الفخّ 2: الباب «eng» ضيّق لا ثقيل."),
"d-b1-05-q1": dict(o=["nach der Prüfung in Köln studieren","ein Praktikum in einer Klinik machen","sich bei Ali bewerben"], a="ein Praktikum in einer Klinik machen",
  e="الدليل: «Ich würde gern ein Praktikum in einer Klinik machen». الفخّ 1: كولن مكان محتمل للتقديم لا دراسة. الفخّ 2: علي هو السائل."),
"d-b1-06-q2": dict(o=["Donnerstag um 11:30 Uhr","Dienstag um 11:30 Uhr","Donnerstag um 13:30 Uhr"], a="Donnerstag um 11:30 Uhr",
  e="الدليل: «Könnte der Termin am Donnerstag sein? — Ja, um 11:30 Uhr». الفخّ 1: Dienstag/Donnerstag تشابه صوتي. الفخّ 2: 13:30 تبديل رقم."),
"d-b1-07-q1": dict(o=["etwas Schlimmes am Bildschirm","nichts Schlimmes","dass die Schmerzen zurückkommen"], a="nichts Schlimmes",
  e="الدليل: «Die Untersuchung zeigt: Es ist nichts Schlimmes». الفخّ 1: الشاشة سبب يجب تقليله لا نتيجة الفحص. الفخّ 2: عودة الألم احتمال «wenn»."),
"d-b1-08-q1": dict(o=["einen Putzplan","eine Einkaufsliste","zusammen einkaufen","die Küche zu wechseln"], a="einen Putzplan",
  e="الدليل: «Ich schlage einen Putzplan vor». الفخّ 1: القائمة تكتبها نينا. الفخّ 2: الشراء المشترك سؤال من باول لا اقتراح مؤكَّد منه — نينا وافقت. الفخّ 3: المطبخ موضوع الحديث."),
"d-b1-08-q2": dict(o=["Das spart Geld.","Weil die Küche unordentlich ist.","Weil Nina eine Liste schreibt.","Weil jeder einmal pro Woche sauber macht."], a="Das spart Geld.",
  e="الدليل: «Ja, das spart Geld». الفخّ 1: الفوضى سبب خطّة التنظيف. الفخّ 2: القائمة نتيجة القرار لا سببه. الفخّ 3: التنظيف موضوع آخر."),
"d-b1-09-q1": dict(o=["Die Heizung funktioniert nicht.","Zimmer 205 ist zu kalt.","Der Techniker kommt nicht.","Das Zimmer ist nicht frei."], a="Die Heizung funktioniert nicht.",
  e="الدليل: «Die Heizung funktioniert nicht, und es ist sehr kalt». الفخّ 1: 205 هو الحلّ «frei und warm». الفخّ 2: الفنّي يُرسَل فوراً. الفخّ 3: الغرفة 205 «frei»."),
"d-b1-09-q2": dict(o=["ein anderes Zimmer, Nummer 205","ein Techniker repariert sofort die Heizung","eine neue Heizung","ein wärmeres Bett"], a="ein anderes Zimmer, Nummer 205",
  e="الدليل: «Natürlich. Zimmer 205 ist frei und warm». الفخّ 1: الفنّي يُرسَل، لكنّ الحلّ النهائي المتّفق عليه هو تبديل الغرفة. الفخّ 2 و3: لم يُذكرا."),
"d-b1-10-q1": dict(o=["ein Einstufungstest","ein Nachweis über den Aufenthalt","die Prüfung"], a="ein Einstufungstest",
  e="الدليل: «Haben Sie den Einstufungstest schon gemacht? … Ja, sonst passt die Gruppe nicht». الفخّ 1: إثبات الإقامة غير مطلوب («Nur Pass und Meldebescheinigung»). الفخّ 2: الامتحان في نهاية الدورة وهو «inklusive»."),
"d-b1-10-q2": dict(p="Wie viel kostet der Kurs pro Monat?", o=["38 Euro","83 Euro","83 Euro plus Prüfungsgebühr"], a="83 Euro",
  e="الدليل: «Dreiundachtzig Euro — die Prüfung ist inklusive». الفخّ 1: 38/83 قلب الرقم (dreiundachtzig ≠ achtunddreißig). الفخّ 2: الامتحان مشمول."),
"d-b1-10-q3": dict(p="Was muss Frau Weber mitbringen?", o=["Pass und Aufenthaltsnachweis","Pass und Meldebescheinigung","nur die Meldebescheinigung"], a="Pass und Meldebescheinigung",
  e="الدليل: «Nur Pass und Meldebescheinigung». الفخّ 1: الـAufenthaltsnachweis سألت عنه ولم يُطلب. الفخّ 2: «nur» تخصّ الاثنين معاً."),
"d-b1-11-q1": dict(o=["nur der Herd","Herd, Spüle und Schränke","die Möbel der Wohnung"], a="Herd, Spüle und Schränke",
  e="الدليل: «Die Küche ist möbliert: Herd, Spüle und Schränke bleiben». الفخّ 1: الموقد جزء فقط. الفخّ 2: «möbliert» قيلت عن المطبخ لا الشقّة."),
"d-b1-11-q2": dict(o=["die Nebenkosten","die Kaution","Wasser und Heizung sind enthalten"], a="die Nebenkosten",
  e="الدليل: «Kaltmiete vierhundertfünfzig, Nebenkosten kommen dazu». الفخّ 1: الضمان يُدفع مرّة لا شهرياً. الفخّ 2: «Nein» — غير مشمولة."),
"d-b1-11-q3": dict(o=["450 Euro","zwei Monatsmieten","eine Monatsmiete zum Ersten"], a="zwei Monatsmieten",
  e="الدليل: «Zwei Monatsmieten, wie immer». الفخّ 1: 450 هي الإيجار البارد. الفخّ 2: «zum Ersten» موعد الإخلاء."),
"d-b1-12-q1": dict(o=["Fieber, weil er Ungewohntes gegessen hat","Fieber und einen Ausschlag","Husten seit zwei Tagen"], a="Fieber und einen Ausschlag",
  e="الدليل: «Mein Sohn hat seit gestern Fieber und einen Ausschlag». الفخّ 1: الأكل الغريب نفاه الأب. الفخّ 2: «zwei Tage» مدّة الابتعاد عن الحضانة."),
"d-b1-12-q2": dict(o=["ja, es ist nicht ansteckend","nein, erst zwei Tage nach dem letzten Fieber","nein, erst nach dem Antibiotikum"], a="nein, erst zwei Tage nach dem letzten Fieber",
  e="الدليل: «Ja — bis zwei Tage nach dem letzten Fieber darf er nicht hin». الفخّ 1: «ansteckend» أُجيب بنعم. الفخّ 2: لا مضادّ حيوي."),
"d-b1-12-q3": dict(o=["weil er noch Fieber hat","weil es bei Viren nicht wirkt","weil er viel trinken soll"], a="weil es bei Viren nicht wirkt",
  e="الدليل: «Nein, bei Viren wirkt es nicht». الفخّ 1: الحمّى موجودة لكنّها ليست السبب. الفخّ 2: الشرب توصية إضافية."),
"d-b1-13-q1": dict(p="Warum verschiebt Frau Krause den Termin?", o=["Die Kinder müssen in die Kita.","Ihr Chef gab ihr einen dringenden Auftrag.","Sami plant den Tag umsonst."], a="Ihr Chef gab ihr einen dringenden Auftrag.",
  e="الدليل: «Mein Chef gab mir unerwartet einen dringenden Auftrag». الفخّ 1: الحضانة سبب «nicht vor neun» لا سبب التأجيل. الفخّ 2: هذا اعتراض سامي."),
"d-b1-13-q2": dict(o=["Donnerstag","Montag um neun","Dienstag um neun"], a="Montag um neun",
  e="الدليل: «Montag, aber nicht vor neun» ← «Neun Uhr passt». الفخّ 1: الخميس عرض لم يُختَر. الفخّ 2: الثلاثاء الموعد القديم."),
"d-b1-13-q3": dict(p="Was braucht Sami für die Arbeit?", o=["den Schlüssel von Frau Krause persönlich","Zugang zum Keller","Zugang zur Kita"], a="Zugang zum Keller",
  e="الدليل: «Ich brauche Zugang zum Keller». الفخّ 1: المفتاح عند الاستقبال لا عندها. الفخّ 2: الحضانة تخصّ الأطفال."),
"d-b1-14-q1": dict(o=["Chef Linke selbst","Tarek","Rania, um elf"], a="Tarek",
  e="الدليل: «Tarek übernimmt». الفخّ 1: الرئيس سأل فقط. الفخّ 2: رانيا مريضة، «elf» موعد الاجتماع."),
"d-b1-14-q2": dict(o=["Rania sendet sie vor zehn.","Sie liegen seit gestern im gemeinsamen Ordner.","Sie sind für Montag noch nicht fertig."], a="Sie liegen seit gestern im gemeinsamen Ordner.",
  e="الدليل: «Längst im gemeinsamen Ordner, seit gestern Abend». الفخّ 1: «vor zehn» يخصّ الشرائح لتارك. الفخّ 2: «Montag» موعد الحاجة إليها وهي جاهزة."),
"d-b1-14-q3": dict(o=["die Frist am Montag","die Gesundheit vor der Frist","das Meeting um elf"], a="die Gesundheit vor der Frist",
  e="الدليل: «die Gesundheit geht vor der Frist». الفخّان: المهلة والاجتماع ذُكرا لكنّ الرئيس قدّم الصحّة عليهما."),
"d-b1-15-q1": dict(o=["Die neue Karte wird bestellt.","Die Karte wird gesperrt.","Der Automat am Hauptbahnhof wird geprüft."], a="Die Karte wird gesperrt.",
  e="الدليل: «bitte sofort sperren! — Die Karte ist gesperrt». الفخّ 1: البطاقة الجديدة بعد 14 يوماً. الفخّ 2: الصرّاف مكان آخر استعمال، لا إجراء."),
"d-b1-15-q2": dict(o=["sechs Euro","zwanzig Euro","vierzehn Euro"], a="sechs Euro",
  e="الدليل: «Zwanzig Euro bei Diebstahl, sechs bei Verlust» و«Leider Verlust». الفخّ 1: 20 للسرقة. الفخّ 2: 14 عدد الأيام."),
"d-b1-15-q3": dict(o=["in vierzehn Tagen","gestern Vormittag","in sechs Tagen"], a="in vierzehn Tagen",
  e="الدليل: «Die neue Karte kommt in vierzehn Tagen». الفخّ 1: أمس صباحاً آخر استعمال. الفخّ 2: ستّة هي الرسوم."),
"d-b1-16-q1": dict(o=["fünfzehn Prozent des Preises","fünfzig Prozent des Preises","der nächste Zug ohne Aufpreis"], a="fünfzehn Prozent des Preises",
  e="الدليل: «Bei fünfzig Minuten stehen Ihnen fünfzehn Prozent des Preises zu». الفخّ 1: fünfzig دقائق التأخير لا النسبة. الفخّ 2: القطار التالي يخصّ الرحلة الملغاة."),
"d-b1-16-q2": dict(o=["das Original der Fahrkarte","das Onlineformular und eine Kopie der Fahrkarte","Bargeld am Schalter"], a="das Onlineformular und eine Kopie der Fahrkarte",
  e="الدليل: «Das Formular „Geld zurück“ online ausfüllen» و«Eine Kopie genügt — bewahren Sie das Original auf». الفخّ 1: الأصل يحتفظ به. الفخّ 2: «Bar» سأل عنه والجواب: على الحساب."),
"d-b1-16-q3": dict(o=["der nächste Zug ohne Aufpreis","fünfzehn Prozent zusätzlich","kein Anspruch, weil der Zug ausfiel"], a="der nächste Zug ohne Aufpreis",
  e="الدليل: «Dann gilt der nächste Zug ohne Aufpreis». الفخّ 1: 15٪ للتأخير لا للإلغاء. الفخّ 2: الإلغاء يمنح حقّاً لا يلغيه."),
"d-b1-17-q1": dict(o=["eine Leseecke","ein Sponsor","Eltern zum Vorlesen"], a="ein Sponsor",
  e="الدليل: «für die Bibliothek fehlt ein Sponsor». الفخّ 1: ركن القراءة «fertig». الفخّ 2: القراءة بصوت عالٍ اقتراح المعلّمة لمساعدة أخرى."),
"d-b1-17-q2": dict(o=["einmal monatlich, samstags vor zehn","freitags nach siebzehn Uhr","täglich vor dem Dienst"], a="einmal monatlich, samstags vor zehn",
  e="الدليل: «einmal monatlich, samstags vor zehn». الفخّ 1: الجمعة بعد 17 موعد مجموعة العمل. الفخّ 2: «Dienst» ذُكر كعائق."),
"d-b1-17-q3": dict(o=["die Leseecke","die Abschlussfeier","die Einladung der Partnerschule"], a="die Abschlussfeier",
  e="الدليل: «Die Abschlussfeier planen wir als Arbeitsgruppe am Freitag». الفخّ 1: الركن جاهز. الفخّ 2: الدعوة يرسلها سليم لا المجموعة."),
"d-b1-18-q1": dict(o=["die Musik durch die Wand","die laut verstärkte Übertragung des Bruders","die Gäste von Frau Dittrich"], a="die laut verstärkte Übertragung des Bruders",
  e="الدليل: «Das war die Übertragung meines Bruders, laut verstärkt». الفخّ 1: الموسيقى احتمال مستقبلي «Dringt … Musik». الفخّ 2: ضيوف السيّدة ديتريش موضوع الإعلام المسبق."),
"d-b1-18-q2": dict(o=["um zweiundzwanzig Uhr","nach Mitternacht","zwanzig Minuten vorher"], a="um zweiundzwanzig Uhr",
  e="الدليل: «Nachtruhe ab zweiundzwanzig». الفخّ 1: بعد منتصف الليل وقت الضجيج أمس. الفخّ 2: 20 دقيقة مهلة الإعلام عن الضيوف."),
"d-b1-18-q3": dict(o=["Er sagt bei Gästen zwanzig Minuten vorher Bescheid.","Die Übertragung bleibt künftig aus.","Er klopft einmal an die Wand."], a="Die Übertragung bleibt künftig aus.",
  e="الدليل: «Die Übertragung bleibt künftig aus». الفخّ 1: الإعلام المسبق وعد السيّدة ديتريش. الفخّ 2: الطرق ما يطلبه منها هي."),
"d-b1-19-q1": dict(o=["mündlich mit Prüfungsanmeldung","nur schriftlich mit Nachweis des Grundes","nur am Freitag"], a="nur schriftlich mit Nachweis des Grundes",
  e="الدليل: «Verschiebungen nur schriftlich; den Grund bitte nachweisen». الفخّ 1: شفهياً منفيّ بـ«nur schriftlich». الفخّ 2: الجمعة الموعد القديم."),
"d-b1-19-q2": dict(o=["nur der Brief mit dem neuen Termin","alle Unterlagen wie beim ersten Mal","nur die Prüfungsanmeldung"], a="alle Unterlagen wie beim ersten Mal",
  e="الدليل: «Pass, Aufenthaltstitel, Mietvertrag, Versicherungsnachweis — wie beim ersten Mal». الفخّ 1: الرسالة شرط الدخول إضافةً لا بديلاً. الفخّ 2: التسجيل كان إثبات السبب."),
"d-b1-19-q3": dict(o=["ein neuer Termin einen Monat später","Ablehnung und eine neue Gebühr","eine schriftliche Warnung"], a="Ablehnung und eine neue Gebühr",
  e="الدليل: «Bei zweitem Versäumnis: Ablehnung, neue Gebühr». الفخّ 1: «ein Monat später» طلب أميرة الأوّل. الفخّ 2: لا تحذير مذكوراً."),
"d-b1-20-q1": dict(o=["bis acht Uhr früh","bis Mitternacht","bis zwanzig Uhr"], a="bis acht Uhr früh",
  e="الدليل: «Ja — bis acht Uhr früh». الفخّ: «zwanzig» تشابه مع acht (20 Uhr = 8 مساءً) — انتبه لـ«früh»."),
"d-b1-20-q2": dict(o=["so viele wie nötig","nur ein Mittel zur Zeit","Fiebermittel und Hustenmittel zusammen"], a="nur ein Mittel zur Zeit",
  e="الدليل: «Nicht kombinieren bei Kindern: nur ein Mittel zur Zeit». الفخّ: الجمع بين الدواءين هو ما سألت عنه ورُفض."),
"d-b1-20-q3": dict(p="Kann Frau Seidl das Rezept morgen bringen?", o=["Ja, Rezepte gelten bundesweit.","Nein, nur heute Nacht bis acht Uhr.","Nein, das Fiebermittel ist rezeptpflichtig."], a="Ja, Rezepte gelten bundesweit.",
  e="الدليل: «Rezepte gelten bundesweit». الفخّ 1: «bis acht Uhr» مدّة المناوبة لا صلاحية الوصفة. الفخّ 2: خافض الحرارة «rezeptfrei»."),
"d-b1-21-q1": dict(o=["ein Telefonat zwei Wochen vorher","Schriftform mit sechs Wochen Frist","Kündigung zum Monatsende"], a="Schriftform mit sechs Wochen Frist",
  e="الدليل: «Die Frist beträgt sechs Wochen, schriftlich — siehe Vertrag». الفخّ 1: «Telefon allein genügt nicht». الفخّ 2: نهاية الشهر رغبة رياض."),
"d-b1-21-q2": dict(o=["Sie verfällt mit Fristablauf.","Sie wird erstattet.","Sie wird mit der Schlüsselkaution verrechnet."], a="Sie wird erstattet.",
  e="الدليل: «zu viel Gezahltes wird erstattet». الفخّ 1: «Fristablauf» موعد إيقاف السحب لا سقوط الحقّ. الفخّ 2: ضمان المفتاح يُردّ منفصلاً."),
"d-b1-21-q3": dict(o=["fünfzehn Euro","sechs Euro","vierzehn Euro"], a="fünfzehn Euro",
  e="الدليل: «Fünfzehn Euro zurück, binnen vierzehn Tagen». الفخّ 1: ستّة أسابيع هي المهلة (وحدة مختلفة). الفخّ 2: 14 هي أيام الردّ."),
"d-b1-22-q1": dict(o=["das Dessert","das Mineralwasser","die Hauptspeise"], a="das Mineralwasser",
  e="الدليل: «Auf der Rechnung steht Mineralwasser — wir haben nichts bestellt». الفخّ 1: الحلوى هديّة. الفخّ 2: الطبق الرئيسي كان بارداً لا محسوباً خطأً."),
"d-b1-22-q2": dict(o=["mit zwölf Euro Nachlass","mit einem Dessert aufs Haus","mit einer Meldung an den Nebentisch"], a="mit einem Dessert aufs Haus",
  e="الدليل: «Das Dessert geht aufs Haus — Küche ist intern gemeldet». الفخّ 1: 12 يورو تصحيح الماء. الفخّ 2: الطاولة المجاورة صاحبة الماء."),
"d-b1-22-q3": dict(o=["achtunddreißig Euro","sechsundzwanzig Euro","zwölf Euro"], a="sechsundzwanzig Euro",
  e="الدليل: «sechsundzwanzig statt achtunddreißig». الفخّ 1: 38 المبلغ الخاطئ. الفخّ 2: 12 الفرق."),
"d-b1-23-q1": dict(o=["Kurs B und die Aufzeichnung","die Vorlesung und das Praktikum","das Praktikum und die Fabrik"], a="die Vorlesung und das Praktikum",
  e="الدليل: «Vorlesung gegen Praktikum». الفخّ 1: Kurs B والتسجيل هما الحلّ. الفخّ 2: المصنع مكان التدريب."),
"d-b1-23-q2": dict(o=["acht bis zwölf Uhr","dreißig Wochenstunden","zwölf Wochenstunden"], a="dreißig Wochenstunden",
  e="الدليل: «maximal dreißig Wochenstunden». الفخّ 1: 8–12 وقت التدريب اليومي. الفخّ 2: 12 ساعة نهاية الدوام."),
"d-b1-23-q3": dict(o=["eine Bestätigung mit Zeiten","eine formlose E-Mail der Chefin","ein Gespräch mit der Beraterin"], a="eine formlose E-Mail der Chefin",
  e="الدليل: «Eine E-Mail der Chefin — formlos, aber schriftlich — genügt». الفخّ 1: التأكيد بالأوقات هو الأصل المفقود. الفخّ 2: يجب أن يكون «schriftlich»."),
"d-b1-24-q1": dict(o=["Diebstahl im Bus","Verlust im Bus","Fund an der Endhaltestelle"], a="Verlust im Bus",
  e="الدليل: «verlor ich im Bus die Laptoptasche». الفخّ 1: لا سرقة ذُكرت. الفخّ 2: الـFund هو العثور لا ما حدث لواسيم."),
"d-b1-24-q2": dict(o=["nur den Ausweis","Ausweis und Eigentumsnachweis","nur Fotos des Geräts"], a="Ausweis und Eigentumsnachweis",
  e="الدليل: «Ausweis und Eigentumsnachweis: Rechnung oder Fotos». الفخّ 1: الهويّة وحدها لا تكفي. الفخّ 2: الصور أحد شكلي الإثبات، ويُضاف إليها الهويّة."),
"d-b1-24-q3": dict(o=["bis neun Uhr","vierzehn Tage","bis zwanzig Uhr zwanzig"], a="vierzehn Tage",
  e="الدليل: «Vierzehn Tage Aufbewahrung, dann Versteigerungslager». الفخّ 1: التاسعة بداية الاستلام. الفخّ 2: 20:20 وقت الإبلاغ عن العثور."),
"d-b1-25-q1": dict(o=["innerhalb von zwei Wochen","sobald der Vermieter zurück ist","innerhalb von sechs Tagen"], a="innerhalb von zwei Wochen",
  e="الدليل: «Genau zwei Wochen Frist — rechtzeitig». الفخّ 1: غياب المؤجّر لا يمدّد المهلة. الفخّ 2: ستّة هي يوروهات الـeID."),
"d-b1-25-q2": dict(o=["Toufik als Mieter","der Vermieter","Amtsfrau Berg"], a="der Vermieter",
  e="الدليل: «Ein Blatt mit der Unterschrift des Vermieters über den Einzug». الفخّ 1: المستأجر يقدّمها لا يوقّعها. الفخّ 2: الموظّفة تصدر الوثيقة المؤقّتة."),
"d-b1-25-q3": dict(o=["eine Anmeldung für sechs Euro","eine vorläufige Bescheinigung","die eID-Funktion gratis"], a="eine vorläufige Bescheinigung",
  e="الدليل: «Ohne sie keine Anmeldung — ich gebe Ihnen vorläufig eine Bescheinigung». الفخّ 1: التسجيل مجّاني لكنّه غير ممكن بدونها. الفخّ 2: الـeID تكلّف ستّة يورو."),
"d-b1-26-q1": dict(o=["Fatma selbst zum Monatsersten","der neue Anbieter","die Grundversorgung"], a="der neue Anbieter",
  e="الدليل: «wir übernehmen alles». الفخّ 1: فاطمة قالت «Ich kündige» لكنّ المزوّد يتولّى الإجراء. الفخّ 2: الـGrundversorgung تضمن الاستمرار."),
"d-b1-26-q2": dict(o=["per Foto im Onlineformular bis 22 Uhr","per Anruf bei der Hotline","der Zähler meldet automatisch"], a="per Foto im Onlineformular bis 22 Uhr",
  e="الدليل: «Foto per Onlineformular, spätestens zweiundzwanzig Uhr». الفخّ 1: الخطّ الساخن محاورها الآن لا وسيلة الإبلاغ. الفخّ 2: لا إبلاغ آلي."),
"d-b1-26-q3": dict(o=["an zwölf Monaten Preisbindung","an der Grundversorgung","am Zählerstand am Umschalttag"], a="an zwölf Monaten Preisbindung",
  e="الدليل: «Bonus nur bei zwölf Monaten Bindung; Preisgarantie braucht Preisbindung». الفخّ 1: التزويد الأساسي يخصّ الانقطاع. الفخّ 2: قراءة العدّاد للفوترة."),
"d-b1-27-q1": dict(o=["vierzig Übungsstunden","die Erste-Hilfe-Bescheinigung","das Ausbildungsprotokoll"], a="die Erste-Hilfe-Bescheinigung",
  e="الدليل: «Erste-Hilfe-Kurs vorher nötig». الفخّ 1: الأربعون ساعة ذكرتها سُندس، لا شرط المدرّب. الفخّ 2: البروتوكول ضمن أوراق يوم الامتحان."),
"d-b1-27-q2": dict(p="Wie lange ist die Erste-Hilfe-Bescheinigung gültig?", o=["zwei Wochen","sie läuft nie ab","vierzehn Tage nach der Prüfung"], a="sie läuft nie ab",
  e="الدليل: «Einmal im Leben: sie läuft nie ab». الفخّ 1: أسبوعان أقرب موعد للامتحان. الفخّ 2: 14 يوماً مدّة الحظر."),
"d-b1-27-q3": dict(o=["Neuanmeldung mit neuer Gebühr","vierzehn Tage Sperre, Gebühr bleibt gültig","Sperre auf Lebenszeit"], a="vierzehn Tage Sperre, Gebühr bleibt gültig",
  e="الدليل: «Vierzehn Tage Sperre — die Gebühr bleibt gültig, keine Neuanmeldung». الفخّ 1: «keine Neuanmeldung» منفيّ. الفخّ 2: «im Leben» قيلت عن الإسعاف."),
"d-b1-31-q1": dict(o=["Sie lehnt sie ab, weil er unter Zeitdruck war.","Sie versteht sie, kritisiert aber trotzdem.","Sie hält die Absprache selbst nicht ein."], a="Sie versteht sie, kritisiert aber trotzdem.",
  e="الدليل: «Das kann ich nachvollziehen. Trotzdem hätte ein kurzer Anruf gereicht». الفخّ 1: ضغط الوقت عذر يوناس، وهي تفهمه. الفخّ 2: يوناس هو من أخلّ."),
"d-b1-32-q1": dict(o=["dass er zu Hause weniger erzählt","dass er täglich fünfzehn Minuten laut liest","dass er sich in der Klasse seltener meldet"], a="dass er täglich fünfzehn Minuten laut liest",
  e="الدليل: «Wichtig wäre, dass er öfter laut liest» و«Fünfzehn Minuten reichen». الفخّ 1: الحديث في البيت ملاحظة الأب. الفخّ 2: «meldet sich selten» هي المشكلة لا التوصية."),
}
