# -*- coding: utf-8 -*-
"""Dialog-B2: Fallen-Distraktoren. Jeder Distraktor ist ein Wort/Inhalt aus dem Dialog in falscher Rolle
(Gegenposition, verneinte Option, verwechselte Zahl/Person). explanationAr nennt den Beleg und warum jede Falle falsch ist."""
P = {
"d-b2-01-q1": dict(o=["die Richtung der Maßnahmen","die unzureichenden Maßnahmen","den Optimismus der Moderatorin"], a="die unzureichenden Maßnahmen",
  e="الدليل: «reichen aber bei Weitem nicht aus». الفخّ 1: الاتجاه تصفه بأنه «richtig» لا تنتقده. الفخّ 2: التفاؤل الذي تنتقده هو تفاؤل «الحكومة» لا المقدِّمة."),
"d-b2-02-q2": dict(o=["dass die Kommunen zuerst die Infrastruktur bauen","dass die Schulungen begleitend stattfinden","dass der Zeitplan eingehalten wird"], a="dass die Schulungen begleitend stattfinden",
  e="الدليل: «Entscheidend ist, dass die … Schulungen begleitend stattfinden». الفخّ 1: البنية التحتية ذُكرت كشرط ناقص لا كالأمر الحاسم. الفخّ 2: الجدول الزمني ذكره قائد المشروع في الختام فقط."),
"d-b2-03-q1": dict(o=["seriös, aber ohne Zahlen","nicht besonders seriös","seriös, die Zahlen sind aber geschönt"], a="nicht besonders seriös",
  e="الدليل: «Sie ist nicht besonders seriös». الفخّ: «geschönt» قالها يوناس عن الشركة (الادّعاء)، لا دينا عن المصدر."),
"d-b2-04-q2": dict(o=["mehr Verantwortung ab nächstem Jahr","eine schriftliche Zusage für nächstes Jahr","eine sofortige Erhöhung trotz begrenzter Spielräume"], a="eine schriftliche Zusage für nächstes Jahr",
  e="الدليل: «Unter der Bedingung einer schriftlichen Zusage für nächstes Jahr». الفخّ 1: المسؤولية الإضافية حجّته الماضية لا شرطه. الفخّ 2: «Spielräume dieses Jahr begrenzt» كلام الرئيسة، وهو يقبل التأجيل."),
"d-b2-05-q1": dict(o=["die Sprache","die Figurenentwicklung","den vorhersehbaren Plot"], a="den vorhersehbaren Plot",
  e="الدليل: «wenngleich der Plot etwas vorhersehbar wirkt». الفخّ 1: اللغة وصفها «brillant». الفخّ 2: تطوّر الشخصيات أُعجبت به هيلينا، وكريم أقرّ بأن البطلة «vielschichtig»."),
"d-b2-06-q1": dict(o=["KI als Werkzeug zu begreifen","den Lehrer durch KI zu ersetzen","Urteilskraft als Lernziel"], a="den Lehrer durch KI zu ersetzen",
  e="الدليل: «Einen Lehrer zu ersetzen, wäre ein Kategorienfehler». الفخّ 1: «Werkzeug» شرط د. صالح للموافقة. الفخّ 2: «Urteilskraft» هو ما يطالب به فيبر لا ما ينتقده."),
"d-b2-07-q2": dict(o=["eine kürzere Lieferfrist","eine längere Vertragslaufzeit","5 Prozent mehr"], a="eine längere Vertragslaufzeit",
  e="الدليل: «unter der Bedingung einer längeren Vertragslaufzeit». الفخّ 1: تقصير مدّة التسليم شرط المشتري. الفخّ 2: الـ5٪ عرض المشتري مقابل ذلك الشرط."),
"d-b2-08-q1": dict(o=["die Methode der Studie","die zu kleine Stichprobe","die Verallgemeinerung durch die Dozentin","den fehlenden Abschnitt im Paper"], a="die zu kleine Stichprobe",
  e="الدليل: «Methodisch stark, aber die Stichprobe ist zu klein». الفخّ 1: المنهج مدحته. الفخّ 2: التعميم مشكلةٌ في الدراسة لا فعل الأستاذة. الفخّ 3: القسم الناقص هو ما ستضيفه هي."),
"d-b2-08-q2": dict(o=["einen Abschnitt über die Grenzen der Forschung","eine größere Stichprobe","eine Kritik an der Methode","eine Bewertung der Dozentin"], a="einen Abschnitt über die Grenzen der Forschung",
  e="الدليل: «ich ergänze einen Abschnitt über die Grenzen der Forschung». الفخّ 1: العيّنة الصغيرة هي ما انتقدت لا ما ستضيف. الفخّ 2: المنهج قوي في رأيها. الفخّ 3: الأستاذة هي من تسأل عن التقييم."),
"d-b2-09-q1": dict(o=["wegen der Einarbeitung in den ersten Wochen","wegen der nachhaltigen Projekte","weil er unter Druck ruhig bleibt","wegen der Personalchefin"], a="wegen der nachhaltigen Projekte",
  e="الدليل: «Ihre Firma arbeitet an nachhaltigen Projekten – genau das interessiert mich». الفخّ 1: الـEinarbeitung سؤاله في النهاية. الفخّ 2: الهدوء تحت الضغط جواب سؤال آخر (نقطة قوّته)."),
"d-b2-09-q2": dict(o=["Interesse an Nachhaltigkeit","strukturiertes Arbeiten und Ruhe unter Druck","schnelle Einarbeitung","dass er viele Fragen stellt"], a="strukturiertes Arbeiten und Ruhe unter Druck",
  e="الدليل: «Ich arbeite strukturiert und bleibe auch unter Druck ruhig». الفخّ 1: الاستدامة سبب تقدّمه لا قوّته. الفخّ 2: الـEinarbeitung شيء يسأل عنه."),
"d-b2-10-q1": dict(o=["48.000 Euro, wie Youssef gefordert hat","45.500 Euro mit Homeoffice und Weiterbildungsbudget","45.000 Euro plus variabler Anteil"], a="45.500 Euro mit Homeoffice und Weiterbildungsbudget",
  e="الدليل: «Dann 45.500, zwei Tage Homeoffice und 400 Euro Weiterbildungsbudget» ثم «Abgemacht». الفخّ 1: 48.000 مطلبه الأوّل الذي لم يُصرّ عليه. الفخّ 2: 45.000 + variabel العرض الأوّل قبل التحسين."),
"d-b2-10-q2": dict(o=["eine Probezeit von höchstens drei Monaten","zwei Tage Homeoffice","dass die Weiterbildungszeit bezahlt wird"], a="eine Probezeit von höchstens drei Monaten",
  e="الدليل: «Sofern der Vertrag die Probezeit auf drei Monate begrenzt». الفخّ 1: الهوم أوفيس عرض من الرئيسة لا شرط منه. الفخّ 2: وقت التكوين يريده أن يُحتسب «als Leistung» لا أن يُدفع."),
"d-b2-10-q3": dict(o=["nur die Gehaltshöhe","die Zusage über den gesamten Kompromiss","der variable Anteil"], a="die Zusage über den gesamten Kompromiss",
  e="الدليل: «die Zusage bekommen Sie schriftlich morgen Vormittag» بعد الاتفاق على الكلّ. الفخّ: الجزء المتغيّر كان في العرض الأوّل الذي استُبدل."),
"d-b2-11-q1": dict(o=["auf die Wirtschaftlichkeitsberechnung der Verwaltung","auf den Mietspiegel und die Kappungsgrenze","auf die Nebenkostenabrechnung"], a="auf den Mietspiegel und die Kappungsgrenze",
  e="الدليل: «Genau der Mietspiegel besagt: Kappungsgrenze bei elf Prozent». الفخّ 1: الـWirtschaftlichkeitsberechnung دليل الإدارة. الفخّ 2: الـNebenkosten طلبٌ إضافي (محضر) لا حجّة."),
"d-b2-11-q2": dict(o=["eine Erhöhung um 15 Prozent","eine korrigierte Forderung von 9,8 Prozent plus Protokoll","eine Erhöhung um elf Prozent"], a="eine korrigierte Forderung von 9,8 Prozent plus Protokoll",
  e="الدليل: «wir korrigieren auf 9,8 Prozent» و«Das Protokoll folgt binnen vierzehn Tagen». الفخّ 1: 15٪ الطلب الأصلي المرفوض. الفخّ 2: 11٪ هو سقف الـKappungsgrenze لا المبلغ الجديد."),
"d-b2-11-q3": dict(o=["sofort nach dem Gespräch","wenn Protokoll und Belege eingetroffen sind","nach vierzehn Tagen, ohne Bedingung"], a="wenn Protokoll und Belege eingetroffen sind",
  e="الدليل: «Sofern alles eintrifft, akzeptiere ich den neuen Betrag zum Ersten». الفخّ: «vierzehn Tage» مهلة المحضر لا موعد القبول؛ القبول مشروط بـ«sofern»."),
"d-b2-12-q1": dict(o=["nur das Diplom und ein Foto","beglaubigte Übersetzung, Fächerübersicht und Praxisnachweis","eine Berufserlaubnis aus Tunesien"], a="beglaubigte Übersetzung, Fächerübersicht und Praxisnachweis",
  e="الدليل: «Beglaubigte Übersetzung, Fächerübersicht, Nachweis praktischer Tätigkeiten». الفخّ: الـBerufserlaubnis يحصل عليها هنا أثناء الانتظار، لا وثيقة يقدّمها."),
"d-b2-12-q2": dict(o=["unbegrenzt, sobald der Antrag gestellt ist","eingeschränkt, mit Berufserlaubnis","erst nach dem Anpassungslehrgang"], a="eingeschränkt, mit Berufserlaubnis",
  e="الدليل: «mit Ihrer Berufserlaubnis im Warteverfahren — ja, eingeschränkt». الفخّ: الـAnpassungslehrgang يأتي فقط إذا رُفضت المعادلة جزئياً."),
"d-b2-12-q3": dict(o=["drei Monate","16 Monate","400 Monate"], a="16 Monate",
  e="الدليل: «Anpassungslehrgang … höchstens 16 Monate Praxis». الفخّ 1: ثلاثة أشهر مدّة فحص الطلب. الفخّ 2: 400 هو مبلغ الرسوم باليورو."),
"d-b2-13-q1": dict(o=["zwölf Monate","drei Monate","vier Monate"], a="drei Monate",
  e="الدليل: «rückwirkend nur für drei». الفخّ 1: 12 شهراً هي فترة حساب الدخل. الفخّ 2: 4 أشهر هي فترة الحصول المتزامن مع الشريك."),
"d-b2-13-q2": dict(o=["67 Prozent","zwölf Prozent","zwei Prozent"], a="67 Prozent",
  e="الدليل: «bis 67 Prozent». الفخّان: 12 و2 أرقام وردت لأشهر (الدخل الأخير، الـBonus) لا لنِسَب."),
"d-b2-13-q3": dict(o=["ein PDF für alle Monate zusammen","je Monat ein PDF, mit Stempel","Scans ohne Stempel im Portal"], a="je Monat ein PDF, mit Stempel",
  e="الدليل: «als PDF, je Monat ein Dokument — Scans ohne Stempel akzeptieren wir nicht». الفخّ 1: ملف واحد للكلّ يخالف «je Monat». الفخّ 2: «ohne Stempel» هو المرفوض صراحةً."),
"d-b2-14-q1": dict(o=["durch einen Anruf bei der Hotline","automatisch, wenn ein Steuerberater beauftragt ist","durch eine geänderte Einkommensprognose"], a="automatisch, wenn ein Steuerberater beauftragt ist",
  e="الدليل: «Mit Beratung verlängert sich die Frist automatisch». الفخّ 1: الاتصال بالخطّ الساخن هو ما يفعله طارق الآن لا وسيلة التمديد. الفخّ 2: الـEinkommensprognose شرط الاعتراض على الدفعة المسبقة."),
"d-b2-14-q2": dict(o=["ein Monat","bis April nächsten Jahres","es gibt keine Frist, nur die Prognose"], a="ein Monat",
  e="الدليل: «Innerhalb eines Monats, aber nur mit geänderter Einkommensprognose». الفخّ 1: أبريل هو مهلة التصريح الممدّدة. الفخّ 2: التوقّع شرط إضافي لا بديل عن المهلة."),
"d-b2-14-q3": dict(o=["eine Bestätigung des Steuerberaters","die Sendebestätigung von ELSTER","der Grundriss des Arbeitszimmers"], a="die Sendebestätigung von ELSTER",
  e="الدليل: «die Sendebestätigung aufheben — sie ist das einzige Quittungsdokument». الفخّ: الـGrundriss دليل على غرفة العمل لا على الاستلام."),
"d-b2-15-q1": dict(o=["die Hausratversicherung","der Vermieter","der Handwerker-Notdienst"], a="die Hausratversicherung",
  e="الدليل: «Hausrat zahlt Trocknung und Hotel bis zur Wiederbewohnbarkeit». الفخّ 1: المؤجّر مسؤول عن الـMietminderung، والرجوع عليه لاحق. الفخّ 2: خدمة الطوارئ تُصلح لا تدفع."),
"d-b2-15-q2": dict(o=["die Endrechnung","die Rechnung über die Sofortmaßnahme","das Gutachten"], a="die Rechnung über die Sofortmaßnahme",
  e="الدليل: «die Rechnung über die Sofortmaßnahme reicht ein, nicht die Endrechnung». الفخّ 1: الفاتورة النهائية منفيّة صراحة. الفخّ 2: الـGutachten مرحلة التسوية لا الإسعاف."),
"d-b2-15-q3": dict(o=["sofort nach der Meldung mit Nummer 7714","binnen zwei Wochen nach dem Gutachtertermin","erst nach der Endrechnung"], a="binnen zwei Wochen nach dem Gutachtertermin",
  e="الدليل: «Wir regulieren nach dem Gutachtertermin, binnen zwei Wochen». الفخّ 1: رقم البلاغ لا يعني تسوية فورية. الفخّ 2: الفاتورة النهائية لم تُذكر شرطاً للتسوية."),
"d-b2-16-q1": dict(o=["15 Euro","nichts, weil Nadia bei der Warteliste hilft","15 Euro, dafür entfällt die Anwesenheitspflicht"], a="nichts, weil Nadia bei der Warteliste hilft",
  e="الدليل: «dann Tausch ohne Gebühr, aber die Anwesenheitspflicht bleibt heilig». الفخّ 1: 15 يورو العرض الأوّل الذي أُسقط. الفخّ 2: واجب الحضور لا يسقط أبداً."),
"d-b2-16-q2": dict(o=["80 Prozent","ab 18 Uhr jeden Donnerstag","15 Sitzungen"], a="80 Prozent",
  e="الدليل: «Das Zertifikat setzt 80 Prozent Teilnahme voraus». الفخّ 1: 18 هو وقت بداية كتلة الخميس. الفخّ 2: 15 هو مبلغ رسم التحويل."),
"d-b2-16-q3": dict(o=["bis Montag","am Monatsersten","in der Prüfungswoche"], a="bis Montag",
  e="الدليل: «Ärztliches Attest bis Montag, dann Nachtermin am Monatsersten». الفخّ 1: أوّل الشهر موعد الامتحان البديل لا الشهادة. الفخّ 2: أسبوع الامتحان وقت المرض."),
"d-b2-17-q1": dict(o=["eine Prämie für Branchennähe","eine Rückzahlung laut Klausel","zwei freie Tage pro Monat"], a="eine Rückzahlung laut Klausel",
  e="الدليل: «Rückzahlungsklausel bei Wechsel unter 24 Monaten». الفخّ 1: الـBranchennähe شرط التمويل لا مكافأة. الفخّ 2: اليومان مقابل الالتزام لا نتيجة المغادرة."),
"d-b2-17-q2": dict(o=["die Kosten werden um die Pause erhöht","der Anspruch ruht und die Bindung wird um die Pause verlängert","die Bindung endet mit der Elternzeit"], a="der Anspruch ruht und die Bindung wird um die Pause verlängert",
  e="الدليل: «Der Anspruch ruht; wir verlängern die Bindung um die Pause, nicht die Kosten». الفخّ 1: «nicht die Kosten» منفيّ صراحةً. الفخّ 2: الالتزام يُمدَّد لا ينتهي."),
"d-b2-17-q3": dict(o=["zwei Tage pro Monat","24 Tage im Jahr","zwei Tage pro Woche"], a="zwei Tage pro Monat",
  e="الدليل: «Zwei Tage pro Monat frei gegen Bindung an ein Jahr». الفخّ 1: 24 هو عدد أشهر بند الاسترداد. الفخّ 2: «Woche» تبديل الوحدة."),
"d-b2-18-q1": dict(o=["Sami kündigt selbst zum Quartalsende per Brief","die neue Kasse reicht die Kündigung digital ein","über die elektronische Verordnung"], a="die neue Kasse reicht die Kündigung digital ein",
  e="الدليل: «die neue Kasse reicht die Kündigung digital ein». الفخّ 1: سامي يريد الإنهاء، لكنّ الصندوق الجديد هو من يقدّمه. الفخّ 2: الوصفة الإلكترونية تخصّ الأدوية."),
"d-b2-18-q2": dict(o=["ja, bis zur Sammelbescheinigung","nein, der Schutz bleibt bis zum letzten Tag bestehen","nur für Dauermedikamente"], a="nein, der Schutz bleibt bis zum letzten Tag bestehen",
  e="الدليل: «der Versicherungsschutz bleibt bis zum letzten Tag bestehen». الفخّ 1: الـSammelbescheinigung تخصّ حصص الاشتراك. الفخّ 2: الأدوية تستمرّ «nahtlos» إضافةً لا حصراً."),
"d-b2-18-q3": dict(o=["Sami mit der Sammelbescheinigung","die Buchhaltungen beider Kassen unter sich","der Arbeitgeber"], a="die Buchhaltungen beider Kassen unter sich",
  e="الدليل: «Die Buchhaltung beider Kassen tut das unter sich». الفخّ 1: سامي يتلقّى الشهادة فقط. الفخّ 2: صاحب العمل يدفع حصّته لكنّه لا يُجري المحاسبة بين الصندوقين."),
"d-b2-19-q1": dict(o=["im Chat, um schnell zu sein","per Mail mit datierten Protokollen","mündlich im Flur"], a="per Mail mit datierten Protokollen",
  e="الدليل: «die Protokolle datiert … per Mail, nicht im Chat». الفخّ 1: الشات منفيّ صراحةً. الفخّ 2: «Zurufen im Flur» هو ما تريد إنهاءه."),
"d-b2-19-q2": dict(o=["jede Seite nennt drei Bedürfnisse","die Einkaufsabteilung erhält eine Rückmeldung","es wird über die Lieferfristen abgestimmt"], a="jede Seite nennt drei Bedürfnisse",
  e="الدليل: «runden Tisch: jede Seite nennt drei Bedürfnisse». الفخّ 1: غياب الـRückmeldung هو الشكوى. الفخّ 2: المواعيد تُثبَّت في محضر لا بتصويت."),
"d-b2-19-q3": dict(o=["durch die Zahlen bis Mittwoch","durch ein gegengezeichnetes Protokoll mit Fristen und Wiedervorlage","durch Rückmeldung an die Einkaufsabteilung"], a="durch ein gegengezeichnetes Protokoll mit Fristen und Wiedervorlage",
  e="الدليل: «ein Protokoll mit Fristen, das beide gegenzeichnen» و«Wiedervorlage nach sechs Wochen — damit es nicht verpufft». الفخّ: الأرقام يوم الأربعاء للمقارنة لا للضغط."),
"d-b2-20-q1": dict(o=["die Diagnose Schlaganfall","die Selbstständigkeit im Alltag","die Wegstrecke zur Praxis"], a="die Selbstständigkeit im Alltag",
  e="الدليل: «Wir bewerten Selbstständigkeit, nicht die Diagnose allein». الفخّ 1: التشخيص منفيّ كمعيار وحيد. الفخّ 2: الـWegstrecke المقصودة داخل الشقّة لا إلى العيادة."),
"d-b2-20-q2": dict(o=["die Aufsicht am Mittag","das zweiwöchige Tagebuch mit Uhrzeiten","der Widerspruch"], a="das zweiwöchige Tagebuch mit Uhrzeiten",
  e="الدليل: «Die zweiwöchige Liste ist vorbereitet, mit Uhrzeiten». الفخّ 1: الإشراف حالة الأب لا تحضير. الفخّ 2: الاعتراض خطوة لاحقة إن كان التقييم ضعيفاً."),
"d-b2-20-q3": dict(o=["vier Wochen","25 Arbeitstage","zwei Wochen"], a="25 Arbeitstage",
  e="الدليل: «Schriftlich binnen 25 Arbeitstagen». الفخّ 1: أربعة أسابيع مضت منذ الجلطة. الفخّ 2: أسبوعان مدّة اليوميات."),
"d-b2-21-q1": dict(o=["auf der Bürgschaft","auf der Gehaltsüberweisung über die Bank","auf der Karenzzeit"], a="auf der Gehaltsüberweisung über die Bank",
  e="الدليل: «abhängig vom Zinsnachlass bei Gehaltsüberweisung». الفخّ 1: الكفالة شرط القرض البنكي لا سبب الخصم. الفخّ 2: فترة السماح تؤجّل السداد ولا تخفّض الفائدة."),
"d-b2-21-q2": dict(o=["die Zinsen laufen weiter und werden gestundet","Zinsen und Tilgung ruhen vollständig","die Tilgungsrate von 120 Euro beginnt"], a="die Zinsen laufen weiter und werden gestundet",
  e="الدليل: «die Zinsen laufen weiter, werden gestundet». الفخّ 1: „ruhen vollständig“ يناقض „laufen weiter“. الفخّ 2: 120 يورو أقلّ قسط بعد السماح لا خلاله."),
"d-b2-21-q3": dict(o=["durch die Bürgschaft","durch die zwei Sonderzahlungen im Jahr","durch das Einstiegsgehalt"], a="durch die zwei Sonderzahlungen im Jahr",
  e="الدليل: «Sonderzahlung zweimal jährlich — damit wäre eine jährliche Sondertilgung vereinbart». الفخّ 1: الكفالة ضمان لا مصدر دفع. الفخّ 2: راتب البداية يحدّد القسط العادي."),
"d-b2-22-q1": dict(o=["eine Zweitüberweisung ans andere Krankenhaus","der Dringlichkeitscode C auf dem Schein","die Nachrückliste"], a="der Dringlichkeitscode C auf dem Schein",
  e="الدليل: «Dringlichkeitscode C auf dem Schein verkürzt die Wartezeit». الفخّ 1: التحويل الثاني «parallel» ممكن لكنّه ليس ما يقصّر الانتظار حسب الطبيبة. الفخّ 2: قائمة الانتظار البديلة تخصّ الإلغاء."),
"d-b2-22-q2": dict(o=["das Einverständnis der Patientin zum Aktenaustausch","eine Bestätigung des Radiologen","dass die Schmerzen akut sind"], a="das Einverständnis der Patientin zum Aktenaustausch",
  e="الدليل: «die Akten müssen austauschbar sein — mit Ihrem Einverständnis». الفخّ 1: الراديولوجي لم يُطلب منه شيء. الفخّ 2: الحدّة سبب الكود C لا شرط التحويل الموازي."),
"d-b2-22-q3": dict(o=["im DICOM-Format ohne Komprimierung","komprimiert, damit sie schneller ankommen","als Laborwerte der Woche"], a="im DICOM-Format ohne Komprimierung",
  e="الدليل: «Voraufnahmen im DICOM-Format, keine Komprimierung». الفخّ 1: الضغط منفيّ صراحةً. الفخّ 2: قيم المختبر وثيقة أخرى لا صور."),
"d-b2-23-q1": dict(o=["zu Überstunden mit Zuschlag","zum monatlichen Ausgleich des Arbeitszeitkontos","zum Abbau vor Ostern"], a="zum monatlichen Ausgleich des Arbeitszeitkontos",
  e="الدليل: «Das Arbeitszeitkonto muss monatlich ausgeglichen werden — wir haben die Betriebsvereinbarung». الفخّ 1: الزيادة حسب الـTarif لا الاتفاقية. الفخّ 2: «vor Ostern» مطلب أمير لا نصّ الاتفاقية."),
"d-b2-23-q2": dict(o=["die Liste mit dem Schichtleiter","die Einigungsstelle","der Tarifvertrag"], a="die Einigungsstelle",
  e="الدليل: «Dann Einigungsstelle; der Spruch ersetzt die Weigerung des Arbeitgebers». الفخّ 1: القائمة مع رئيس الوردية هي الخطوة العادية يوم الاثنين. الفخّ 2: الـTarif يحدّد الزيادة لا يفرض التنفيذ."),
"d-b2-23-q3": dict(o=["eine Auszahlung statt Freizeit","den Abbau des Überstundenkontingents","einen neuen Schichtplan"], a="den Abbau des Überstundenkontingents",
  e="الدليل: «wir brauchen das Kontingent vor Ostern abgebaut». الفخّ 1: أمير سأل عن «Zeitschiene statt Auszahlung». الفخّ 2: جدول الورديات عائق ذكره لا مطلب."),
"d-b2-24-q1": dict(o=["einen Nachweis der Wiederholung","das Zertifikat nach vier Wochen per Post","eine halbierte Gebühr"], a="das Zertifikat nach vier Wochen per Post",
  e="الدليل: «Bestanden ist bestanden — das Zertifikat kommt nach vier Wochen per Post». الفخّ 1: الإعادة لا تلزم عند النجاح. الفخّ 2: تخفيض الرسوم يخصّ المحاولة المكرَّرة."),
"d-b2-24-q2": dict(o=["einmal","höchstens zweimal","zweimal jährlich"], a="höchstens zweimal",
  e="الدليل: «Wiederholungen nur bei Nichtbestehen, maximal zweimal». الفخّ: „zweimal jährlich“ يضيف تكراراً سنوياً لم يُذكر؛ الحدّ إجماليّ."),
"d-b2-24-q3": dict(p="Wo meldet sich Firas für die B2-Prüfung an?", o=["über die Volkshochschule","direkt über das Sprachenzentrum","über den Kursträger, der die Gebühren halbiert"], a="direkt über das Sprachenzentrum",
  e="الدليل: «Direkt über das Sprachenzentrum, Termin im Frühjahr». الفخّ 1: الـVHS اقتراح فراس المصحَّح. الفخّ 2: الـKursträger يخفّض الرسوم ولا يسجّل."),
"d-b2-25-q1": dict(o=["der Warenwert, weil das Kühlpaket offen war","die Versandgebühr plus ein 10-Euro-Gutschein","nur der Gutschein"], a="die Versandgebühr plus ein 10-Euro-Gutschein",
  e="الدليل: «ich verlange die Versandgebühr zurück» ← «Rückerstattung plus 10-Euro-Gutschein». الفخّ 1: البضاعة «einwandfrei» فلا تعويض عنها. الفخّ 2: القسيمة إضافة لا بديل."),
"d-b2-25-q2": dict(o=["binnen 72 Stunden","binnen drei Tagen nach der Schulung des Kuriers","nach drei Tagen Verspätung"], a="binnen 72 Stunden",
  e="الدليل: «gutgeschrieben binnen 72 Stunden». الفخّ 1: تدريب الساعي إجراء داخلي منفصل. الفخّ 2: الأيام الثلاثة مدّة تأخّر الطرد."),
"d-b2-25-q3": dict(o=["eine Beschwerde auf Englisch","Fotos, Packzettel und Zeitstempel der Tür","das Protokoll der Charge"], a="Fotos, Packzettel und Zeitstempel der Tür",
  e="الدليل: «Belegfotos, Packzettel und Zeitstempel der Tür — dann öffnen wir das Verfahren». الفخّ 1: الإنجليزية غير مطلوبة («Auf Deutsch reicht»). الفخّ 2: الـCharge يوثّقها المركز لا العميل."),
"d-b2-26-q1": dict(o=["das Kolloquium","die Bestellung einer neuen Erstprüferin","die zwei externen Gutachten"], a="die Bestellung einer neuen Erstprüferin",
  e="الدليل: «Wir brauchen eine neue Erstprüferin … binnen sechs Wochen». الفخّ 1: الـKolloquium يبقى في موعده. الفخّ 2: التقارير الخارجية «bis Monatsende»."),
"d-b2-26-q2": dict(o=["die Dissertationsrichtung kann frei geändert werden","die alten Gutachten werden übertragen","der Kolloquiumstermin wird verschoben"], a="die alten Gutachten werden übertragen",
  e="الدليل: «die alten Gutachten werden übertragen». الفخّ 1: فايلر اشترط بقاء الاتجاه. الفخّ 2: الموعد لا يتغيّر إلا بطلب تأجيل."),
"d-b2-26-q3": dict(o=["eine Unterschrift von Dr. Weiler","zwei externe Gutachten","einen Antrag auf Aufschub"], a="zwei externe Gutachten",
  e="الدليل: «Zwei externe Gutachten — die Verwaltung holt sie bis Monatsende ein». الفخّ 1: توقيع فايلر جزء من التبديل لا شرطاً إضافياً في اللائحة. الفخّ 2: التأجيل اختياري."),
"d-b2-27-q1": dict(o=["eine Mahnung mit Frist","ein Schlichtungsversuch","ein Zwangsgeld"], a="ein Schlichtungsversuch",
  e="الدليل: «Vor der Klage gehört der Schlichtungsversuch zur Pflicht». الفخّ 1: الإنذار أرسلته يارا ولم ينفع، وليس شرطاً قانونياً هنا. الفخّ 2: الغرامة تأتي بعد المخالفة."),
"d-b2-27-q2": dict(o=["ein Zwangsgeld bis 250.000 Euro","das Scheitern wird protokolliert und die Klage wird zulässig","Yara verzichtet auf Schadensersatz"], a="das Scheitern wird protokolliert und die Klage wird zulässig",
  e="الدليل: «Dann wird das Scheitern protokolliert — und die Klage wird zulässig». الفخّ 1: الغرامة عند مخالفة مهلة مصادَق عليها. الفخّ 2: التنازل مشروط بقبول الحدّ."),
"d-b2-27-q3": dict(o=["die Frist zum Rückschnitt","der Verzicht auf Schadensersatz","die Grenze von 40 Zentimetern"], a="die Frist zum Rückschnitt",
  e="الدليل: «Vergleich mit Frist zum Rückschnitt … bei Verstoß droht ein Zwangsgeld». الفخّ 1: التنازل وعد يارا. الفخّ 2: الـ40 سم مقدار التجاوز لا موضوع الغرامة."),
"d-b2-31-q1": dict(o=["Er weicht auf den Fachkurs aus","Er bestätigt sie und zeigt den beruflichen Nutzen","Er bestreitet, dass es eine Lücke gab"], a="Er bestätigt sie und zeigt den beruflichen Nutzen",
  e="الدليل: «Das ist richtig … Ich habe gelernt, unter Belastung zu priorisieren». الفخّ 1: الدورة ذُكرت «nebenbei» لا هرباً. الفخّ 2: «Das ist richtig» يناقض الإنكار."),
"d-b2-32-q1": dict(o=["dass die Einsparung größer ausfällt","dass gleichzeitig in Schienen investiert wird","dass das Limit nichts kostet"], a="dass gleichzeitig in Schienen investiert wird",
  e="الدليل: «Einverstanden, sofern man gleichzeitig in Schienen investiert». الفخّ 1: صِغر التوفير اعتراضه لا شرطه. الفخّ 2: «kostet nichts» حجّة يارا."),
}
