# -*- coding: utf-8 -*-
"""exampleDe/exampleAr Batch 2: Rest B1 (231)."""
B = {
"v312": ("Die Entwicklung der Mieten in Leipzig macht vielen Sorgen.", "تطوّر الإيجارات في لايبزغ يقلق كثيرين."),
"v316": ("Der Wandel in der Arbeitswelt kommt schneller als erwartet.", "التحوّل في عالم العمل يأتي أسرع من المتوقع."),
"v317": ("Soziale Medien haben großen Einfluss auf junge Leute.", "الشبكات الاجتماعية لها تأثير كبير على الشباب."),
"v321": ("Die Miete ist um 9,8 Prozent gestiegen, nicht um 15.", "الأجرة ارتفعت 9.8٪ لا 15٪."),
"v327": ("Mein Nachbar wohnt erst seit einem Monat hier.", "جاري يسكن هنا منذ شهر فقط."),
"v331": ("Ende März ziehe ich aus der alten Wohnung aus.", "في نهاية مارس أخرج من الشقة القديمة."),
"v332": ("Am Ersten ziehen wir in die neue Wohnung ein.", "في الأول من الشهر ندخل الشقة الجديدة."),
"v333": ("Die Gegend ist ruhig, mit vielen Bäumen und einem Park.", "المنطقة هادئة، فيها أشجار كثيرة وحديقة."),
"v336": ("Im Dorf fährt der Bus nur dreimal am Tag.", "في القرية تمرّ الحافلة ثلاث مرات فقط يومياً."),
"v342": ("Für das letzte Studienjahr braucht sie einen Kredit.", "لسنة الدراسة الأخيرة تحتاج قرضاً."),
"v356": ("Nicht jeder ist für das Leben in einer WG gemacht.", "ليس كل شخص مناسباً للعيش في سكن مشترك."),
"v359": ("Im Sommer frühstücken wir auf dem Balkon.", "في الصيف نفطر على الشرفة."),
"v368": ("Nach zehn Uhr abends brauche ich Ruhe zum Schlafen.", "بعد العاشرة مساءً أحتاج السكينة للنوم."),
"v372": ("Wir chatten jeden Abend eine halbe Stunde auf Deutsch.", "ندردش كل مساء نصف ساعة بالألمانية."),
"v373": ("Mit dieser App lerne ich täglich zwanzig neue Wörter.", "بهذا التطبيق أتعلّم يومياً عشرين كلمة جديدة."),
"v374": ("Das Gerät ist alt, aber es funktioniert noch gut.", "الجهاز قديم لكنه ما زال يعمل جيداً."),
"v375": ("Ich sitze zu lange vor dem Bildschirm, deshalb tun die Augen weh.", "أجلس طويلاً أمام الشاشة، لذلك تؤلمني عيناي."),
"v377": ("Gib das Wort in die Suchmaschine ein und lies die ersten Ergebnisse.", "أدخل الكلمة في محرك البحث واقرأ النتائج الأولى."),
"v378": ("Am Wochenende streamen wir eine deutsche Serie mit Untertiteln.", "في نهاية الأسبوع نشاهد مسلسلاً ألمانياً تدفّقياً مع ترجمة."),
"v381": ("Für den Kurs müssen Sie sich online anmelden.", "للدورة يجب أن تسجّل عبر الإنترنت."),
"v382": ("Die Anmeldung beim Amt ist innerhalb von zwei Wochen Pflicht.", "التسجيل في الدائرة واجب خلال أسبوعين."),
"v383": ("Vergiss nicht, den Text zu speichern, bevor du das Programm schließt.", "لا تنسَ حفظ النص قبل إغلاق البرنامج."),
"v388": ("In der Fabrik arbeitet ein Roboter neben den Menschen.", "في المصنع يعمل روبوت بجانب البشر."),
"v392": ("In den sozialen Medien verbreiten sich Gerüchte schnell.", "في الشبكات الاجتماعية تنتشر الشائعات بسرعة."),
"v393": ("Ein gutes Netzwerk hilft bei der Jobsuche.", "شبكة علاقات جيدة تساعد في البحث عن عمل."),
"v394": ("Die Werbung verspricht viel, aber das Produkt hält wenig.", "الإعلان يعد بالكثير، لكن المنتج لا يفي إلا بالقليل."),
"v396": ("Die Lieferung kam drei Tage zu spät, und das Paket war offen.", "التوصيل تأخّر ثلاثة أيام، والطرد كان مفتوحاً."),
"v403": ("Ich muss mein Handy aufladen, der Akku ist fast leer.", "يجب أن أشحن هاتفي، فالبطارية شبه فارغة."),
"v405": ("Jeder Nutzer braucht ein eigenes Passwort.", "كل مستخدم يحتاج كلمة سر خاصة به."),
"v411": ("Die Kündigung reicht die neue Kasse digital ein.", "الصندوق الجديد يقدّم الإلغاء رقمياً."),
"v412": ("Auf der deutschen Tastatur sind Y und Z vertauscht.", "على لوحة المفاتيح الألمانية Y وZ متبادلان."),
"v416": ("Die Studie ist methodisch stark, aber die Stichprobe ist klein.", "الدراسة قوية منهجياً لكن العيّنة صغيرة."),
"v417": ("Der Arzt untersucht zuerst den Hals und dann die Ohren.", "الطبيب يفحص الحلق أولاً ثم الأذنين."),
"v418": ("Die Untersuchung zeigt: Es ist nichts Schlimmes.", "الفحص يُظهر أنه لا شيء خطير."),
"v419": ("Das Ergebnis der Prüfung kommt in vier Wochen.", "نتيجة الامتحان تصل خلال أربعة أسابيع."),
"v420": ("Das Experiment wurde dreimal wiederholt, mit gleichem Ergebnis.", "التجربة أُعيدت ثلاث مرات بنفس النتيجة."),
"v421": ("In der Theorie klingt der Plan gut, in der Praxis ist er schwer.", "نظرياً تبدو الخطة جيدة، عملياً هي صعبة."),
"v424": ("Der Forscher arbeitet seit Jahren an diesem Thema.", "الباحث يعمل على هذا الموضوع منذ سنوات."),
"v426": ("Welche Methode hilft dir beim Wörterlernen am meisten?", "أي منهج يساعدك أكثر في حفظ الكلمات؟"),
"v428": ("Die Statistik zeigt weniger Unfälle seit dem Tempolimit.", "الإحصاء يُظهر حوادث أقل منذ تحديد السرعة."),
"v434": ("Das Zitat stammt aus einem Roman, nicht aus einer Rede.", "الاقتباس من رواية لا من خطاب."),
"v438": ("Ohne Daten kann man diese Behauptung nicht beweisen.", "بلا بيانات لا يمكن البرهنة على هذا الادّعاء."),
"v439": ("Die Sendebestätigung ist der einzige Beweis für den Eingang.", "تأكيد الإرسال هو البرهان الوحيد على الاستلام."),
"v440": ("Nach der Ausbildung kann sie immer noch ein Studium beginnen.", "بعد التكوين المهني يمكنها دائماً بدء دراسة جامعية."),
"v441": ("Sara studiert Informatik an der Universität Leipzig.", "سارة تدرس الإعلامية في جامعة لايبزغ."),
"v442": ("Im Seminar diskutieren wir jede Woche einen Text.", "في الحلقة النقاشية نناقش كل أسبوع نصاً."),
"v444": ("Die Frist für den Widerspruch beträgt einen Monat.", "مهلة الاعتراض شهر واحد."),
"v448": ("Die Stadt fördert Sprachkurse für Neuankömmlinge.", "المدينة تدعم دورات لغة للقادمين الجدد."),
"v457": ("Das Aussehen ist beim Vorstellungsgespräch nicht alles.", "المظهر ليس كل شيء في مقابلة العمل."),
"v458": ("Die Landschaft an der Ostsee ist im Herbst besonders schön.", "المشهد الطبيعي على بحر البلطيق جميل جداً في الخريف."),
"v460": ("Das neue Gebäude finden viele hässlich, ich mag es.", "المبنى الجديد يراه كثيرون قبيحاً، أنا أحبه."),
"v463": ("Schönheit ist Geschmackssache, sagt meine Großmutter.", "الجمال مسألة ذوق، تقول جدتي."),
"v464": ("Im Winter muss man die Haut besonders pflegen.", "في الشتاء يجب العناية بالبشرة خاصة."),
"v465": ("Die Pflege des Vaters übernimmt Hedi am Morgen.", "العناية بالأب يتولّاها هادي صباحاً."),
"v466": ("Diese Creme hilft gegen trockene Hände im Winter.", "هذا الكريم يساعد ضد جفاف اليدين شتاءً."),
"v467": ("Sie schminkt sich nur für besondere Anlässe.", "هي تتزيّن فقط للمناسبات الخاصة."),
"v469": ("Mit fünfzig hat man eben die eine oder andere Falte.", "في الخمسين يكون للمرء بعض التجاعيد بطبيعة الحال."),
"v470": ("Im Alter braucht man mehr Zeit für den Alltag.", "في الكِبَر يحتاج المرء وقتاً أطول لشؤونه اليومية."),
"v471": ("Mit siebzig sieht er noch erstaunlich jugendlich aus.", "في السبعين ما زال يبدو فتيّاً بشكل مدهش."),
"v473": ("In meiner Jugend gab es noch kein Internet.", "في شبابي لم يكن هناك إنترنت بعد."),
"v474": ("Die Mode ändert sich jedes Jahr, guter Stil bleibt.", "الموضة تتغيّر كل سنة، والأسلوب الجيد يبقى."),
"v477": ("Für das Vorstellungsgespräch wähle ich schlichte Kleidung.", "لمقابلة العمل أختار ملابس بسيطة."),
"v478": ("Zieh dich warm an, es sind nur acht Grad!", "ارتدِ ملابس دافئة، الحرارة ثماني درجات فقط!"),
"v486": ("Sie trug ein elegantes, dunkelblaues Kleid.", "كانت ترتدي فستاناً أنيقاً أزرق داكناً."),
"v488": ("Ihr Auftreten wirkt natürlich, nicht gespielt.", "حضورها يبدو طبيعياً لا مصطنعاً."),
"v495": ("Ihr ruhiges Auftreten hat die Personalchefin beeindruckt.", "حضورها الهادئ أبهر مديرة الموارد البشرية."),
"v496": ("Der erste Eindruck entsteht in wenigen Sekunden.", "الانطباع الأول يتكوّن في ثوانٍ قليلة."),
"v502": ("Kunst im öffentlichen Raum macht die Stadt lebendiger.", "الفن في الفضاء العام يجعل المدينة أكثر حيوية."),
"v503": ("Der Künstler malt vor allem Straßen bei Nacht.", "الفنان يرسم خصوصاً الشوارع ليلاً."),
"v504": ("Die Künstlerin stellt ihre Bilder im Rathaus aus.", "الفنانة تعرض لوحاتها في البلدية."),
"v505": ("Am Sonntag ist der Eintritt ins Museum frei.", "يوم الأحد الدخول إلى المتحف مجاني."),
"v506": ("Die Ausstellung läuft noch bis Ende Oktober.", "المعرض مستمر حتى نهاية أكتوبر."),
"v508": ("Am Wochenende male ich, um den Kopf frei zu bekommen.", "في نهاية الأسبوع أرسم لأصفّي ذهني."),
"v509": ("An der Wand hängt ein Bild von meiner Familie.", "على الجدار تُعلَّق صورة لعائلتي."),
"v512": ("Wir haben Karten fürs Theater am Samstagabend.", "لدينا تذاكر للمسرح مساء السبت."),
"v514": ("Das Konzert im Park war kostenlos und sehr voll.", "الحفل الموسيقي في الحديقة كان مجانياً ومزدحماً."),
"v515": ("In der Oper habe ich zum ersten Mal Mozart gehört.", "في الأوبرا سمعت موتسارت لأول مرة."),
"v516": ("Das Orchester probt jeden Dienstag in der Stadthalle.", "الأوركسترا تتدرّب كل ثلاثاء في قاعة المدينة."),
"v517": ("Welches Instrument spielst du? – Gitarre, seit drei Jahren.", "أي آلة تعزف؟ – الغيتار، منذ ثلاث سنوات."),
"v518": ("Im Bus höre ich deutsche Musik, das hilft beim Lernen.", "في الحافلة أسمع موسيقى ألمانية، وهذا يساعد على التعلّم."),
"v519": ("Nadia wählt den Film aus, meistens eine Komödie.", "نادية تختار الفيلم، غالباً كوميديا."),
"v520": ("Der Regisseur hat den Film in nur drei Wochen gedreht.", "المخرج صوّر الفيلم في ثلاثة أسابيع فقط."),
"v525": ("Die Hauptfigur spielt eine schwierige Rolle zwischen zwei Familien.", "الشخصية الرئيسية تلعب دوراً صعباً بين عائلتين."),
"v529": ("Die Kritik lobt die Sprache, findet den Plot aber vorhersehbar.", "النقد يمدح اللغة لكنه يجد الحبكة متوقعة."),
"v530": ("Sie kritisiert den Plan sachlich, ohne laut zu werden.", "هي تنتقد الخطة بموضوعية دون رفع صوتها."),
"v533": ("Der Roman spielt in Tunis in den achtziger Jahren.", "تدور أحداث الرواية في تونس في الثمانينات."),
"v534": ("Wir lernen im Kurs ein kurzes Gedicht auswendig.", "نحفظ في الدورة قصيدة قصيرة عن ظهر قلب."),
"v536": ("Deutsche Literatur lese ich zuerst in einfacher Sprache.", "أقرأ الأدب الألماني أولاً بلغة مبسّطة."),
"v537": ("Es lohnt sich, das Buch zweimal zu lesen.", "يستحق الكتاب أن يُقرأ مرتين."),
"v540": ("Das dritte Kapitel ist das längste und das spannendste.", "الفصل الثالث هو الأطول والأكثر تشويقاً."),
"v541": ("Die Handlung ist einfach, aber die Figuren sind stark.", "الحبكة بسيطة لكن الشخصيات قوية."),
"v543": ("Essen ist ein wichtiger Teil jeder Kultur.", "الأكل جزء مهم من كل ثقافة."),
"v544": ("Beim Festival im Juli spielen dreißig Bands aus zehn Ländern.", "في مهرجان يوليو تعزف ثلاثون فرقة من عشرة بلدان."),
"v545": ("Am Freitag zusammen zu essen ist Tradition in unserer Familie.", "الأكل معاً يوم الجمعة تقليد في عائلتنا."),
"v550": ("Die Firma zahlt einen Teil der Weiterbildung, mit Rückzahlungsklausel.", "الشركة تدفع جزءاً من التكوين المستمر، مع بند استرداد."),
"v551": ("Mira möchte ein Praktikum in einer Klinik in Köln machen.", "ميرا تريد تدريباً عملياً في مستشفى في كولن."),
"v552": ("Als Arbeitnehmer haben Sie Anspruch auf bezahlten Urlaub.", "كأجير لك الحق في إجازة مدفوعة."),
"v553": ("Das Gehalt liegt bei 45.500 Euro plus Weiterbildungsbudget.", "الراتب 45500 يورو زائد ميزانية تكوين."),
"v554": ("Der Lohn wird am Monatsende überwiesen.", "يُحوَّل الأجر في نهاية الشهر."),
"v562": ("Die Probezeit ist auf drei Monate begrenzt.", "فترة التجربة محدّدة بثلاثة أشهر."),
"v563": ("Ich arbeite in der Abteilung für Kundenservice.", "أعمل في قسم خدمة الزبائن."),
"v564": ("Die Besprechung um elf übernimmt heute Tarek.", "اجتماع الحادية عشرة يتولّاه طارق اليوم."),
"v570": ("Mein Arbeitsplatz ist ein kleines Büro in der Stadtmitte.", "مكان عملي مكتب صغير في وسط المدينة."),
"v572": ("Die Beraterin war kompetent und hat alles ruhig erklärt.", "المستشارة كانت كفؤة وشرحت كل شيء بهدوء."),
"v578": ("Ich bewerbe mich um die Stelle als Techniker.", "أتقدّم لوظيفة فنّي."),
"v579": ("Sein Verdienst reicht für die Miete und ein bisschen mehr.", "ما يكسبه يكفي للإيجار وقليلاً فوق ذلك."),
"v580": ("Das Elterngeld hängt vom Einkommen der letzten zwölf Monate ab.", "منحة الوالدين تتوقف على دخل الأشهر الاثني عشر الأخيرة."),
"v581": ("Die Steuer wird automatisch vom Gehalt abgezogen.", "الضريبة تُخصم تلقائياً من الراتب."),
"v587": ("Zur Bewerbung gehören Lebenslauf und das letzte Zeugnis.", "من ملف التوظيف السيرة الذاتية وآخر شهادة."),
"v593": ("Die Arbeitslosigkeit in der Region ist gesunken.", "البطالة في المنطقة انخفضت."),
"v597": ("Das Klima in Tunis ist im Sommer heiß und trocken.", "المناخ في تونس حار وجاف صيفاً."),
"v600": ("Der Fluss war früher stark verschmutzt, heute kann man baden.", "النهر كان ملوّثاً بشدة سابقاً، واليوم يمكن السباحة فيه."),
"v601": ("Bitte den Abfall trennen: Papier, Glas und Restmüll.", "من فضلك افصل النفايات: ورق وزجاج وبقايا."),
"v606": ("Die Verpackung ist größer als das Produkt selbst.", "التغليف أكبر من المنتج نفسه."),
"v608": ("Unser Verbrauch an Strom ist im Winter doppelt so hoch.", "استهلاكنا للكهرباء في الشتاء ضعف ذلك."),
"v609": ("Alte Geräte verbrauchen viel mehr Strom als neue.", "الأجهزة القديمة تستهلك كهرباء أكثر بكثير من الجديدة."),
"v610": ("Wer sparsam heizt, spart im Jahr mehrere hundert Euro.", "من يدفّئ باقتصاد يوفّر مئات اليورو سنوياً."),
"v611": ("Der Strom wird ohne eine Sekunde Pause weitergeliefert.", "التيار الكهربائي يستمر توصيله دون انقطاع ثانية."),
"v618": ("Kohle war lange die wichtigste Energiequelle der Region.", "الفحم كان طويلاً أهم مصدر طاقة في المنطقة."),
"v619": ("Der Preis für Erdöl ist wieder gestiegen.", "سعر النفط ارتفع مجدداً."),
"v620": ("Viele Wohnungen werden noch mit Erdgas geheizt.", "شقق كثيرة ما زالت تُدفّأ بالغاز الطبيعي."),
"v627": ("Zu viel Lärm ist schädlich für die Gesundheit.", "الضجيج الزائد ضار بالصحة."),
"v632": ("Grüne Dächer schützen die Stadt ein wenig vor der Hitze.", "الأسطح الخضراء تحمي المدينة قليلاً من الحر."),
"v639": ("Nach dem Sturm gab es eine Überschwemmung im Keller.", "بعد العاصفة حدث غمر مياه في القبو."),
"v655": ("Im Zug war alles neu: die Ansagen, die Menschen, die Landschaft.", "في القطار كان كل شيء جديداً: الإعلانات والناس والمشهد الطبيعي."),
"v657": ("Die Anwohner protestieren gegen die neue Straße.", "السكان يحتجّون على الشارع الجديد."),
"v661": ("Den Betrag bekommen Sie bar, nach der Unterschrift.", "تحصل على المبلغ نقداً بعد التوقيع."),
"v663": ("Mit der Karte gibt es zehn Prozent Rabatt.", "بالبطاقة يوجد خصم عشرة بالمائة."),
"v667": ("Ich möchte ein Konto eröffnen, welche Unterlagen brauchen Sie?", "أريد فتح حساب، أي وثائق تحتاجون؟"),
"v669": ("Bei der Sparkasse gibt es den Kredit mit Bürgschaft.", "في مصرف التوفير يوجد القرض بكفالة."),
"v670": ("Ich hebe am Automaten hundert Euro ab.", "أسحب من الصرّاف مائة يورو."),
"v671": ("Jeden Monat zahle ich fünfzig Euro auf das Sparkonto ein.", "كل شهر أودع خمسين يورو في حساب التوفير."),
"v675": ("Nach dem Studium hatte er zehntausend Euro Schulden.", "بعد الدراسة كان عليه عشرة آلاف يورو ديون."),
"v678": ("Der Käufer hat vierzehn Tage Zeit für die Rückgabe.", "للمشتري أربعة عشر يوماً للإرجاع."),
"v680": ("Der Kunde verlangt die Versandgebühr zurück.", "الزبون يطلب استرداد رسوم الشحن."),
"v687": ("Das alte Foto ist für mich wertvoll, für andere nur Papier.", "الصورة القديمة ثمينة لي، ولغيري مجرد ورق."),
"v690": ("Viele Firmen werben mit kostenloser Lieferung.", "شركات كثيرة تروّج بالتوصيل المجاني."),
"v694": ("Unser Budget für den Urlaub sind achthundert Euro.", "ميزانيتنا للعطلة ثمانمائة يورو."),
"v700": ("Auf den Wasserkocher gibt es zwei Jahre Garantie.", "على الغلاية ضمان سنتين."),
"v705": ("Den Pullover kann ich mit Kassenzettel zurückgeben.", "يمكنني إعادة البلوفر مع الإيصال."),
"v706": ("Wir konsumieren mehr, als wir wirklich brauchen.", "نستهلك أكثر مما نحتاج فعلاً."),
"v708": ("Kann ich hier mit Kreditkarte bezahlen?", "هل يمكنني الدفع هنا بالبطاقة الائتمانية؟"),
"v709": ("Der Betrag wird bar ausgezahlt, ich habe kein Bargeld dabei.", "المبلغ يُدفع نقداً، وليس معي نقد سائل."),
"v716": ("Das Fahrrad ist in der Stadt das schnellste Verkehrsmittel.", "الدراجة أسرع وسيلة تنقّل في المدينة."),
"v717": ("Morgens ist der Verkehr in der Innenstadt sehr dicht.", "صباحاً حركة المرور في وسط المدينة كثيفة جداً."),
"v719": ("Jedes Fahrzeug muss alle zwei Jahre zur Prüfung.", "كل مركبة يجب أن تخضع للفحص كل سنتين."),
"v723": ("Die Haltestelle ist direkt vor dem Krankenhaus.", "موقف الحافلة أمام المستشفى مباشرة."),
"v727": ("Laut Fahrplan kommt der Bus um 14:30 Uhr.", "حسب جدول المواعيد تصل الحافلة في 14:30."),
"v733": ("Die Straße ist wegen der Baustelle bis Freitag gesperrt.", "الشارع مغلق بسبب الورشة حتى الجمعة."),
"v734": ("Wegen des Staus kam ich zwanzig Minuten zu spät.", "بسبب الازدحام تأخّرت عشرين دقيقة."),
"v736": ("Als Fußgänger hat man am Zebrastreifen Vorrang.", "المارّ على قدميه له الأولوية على ممر المشاة."),
"v737": ("Am Zebrastreifen müssen Autos für Fußgänger anhalten.", "عند ممر المشاة يجب أن تتوقف السيارات للمشاة."),
"v738": ("Der neue Radweg führt vom Bahnhof bis zum Park.", "مسار الدراجات الجديد يمتد من المحطة إلى الحديقة."),
"v745": ("Mobilität ohne eigenes Auto ist in der Stadt kein Problem.", "التنقّل بلا سيارة خاصة ليس مشكلة في المدينة."),
"v752": ("Nach dem Unfall war die Straße zwei Stunden gesperrt.", "بعد الحادث أُغلق الشارع ساعتين."),
"v753": ("Alle müssen sich an die Verkehrsregeln halten, auch Radfahrer.", "على الجميع الالتزام بقواعد المرور، حتى راكبي الدراجات."),
"v766": ("Sie können online einchecken und das Gepäck am Schalter abgeben.", "يمكنك تسجيل الوصول عبر الإنترنت وتسليم الأمتعة عند الشباك."),
"v771": ("Das neue Gesetz gilt ab Januar für alle Mieter.", "القانون الجديد يسري من يناير على كل المستأجرين."),
"v780": ("Die Behörde antwortet innerhalb von vier Wochen schriftlich.", "الإدارة الرسمية تردّ كتابياً خلال أربعة أسابيع."),
"v783": ("Den Antrag auf Elterngeld stellt man im Portal.", "طلب منحة الوالدين يُقدَّم عبر البوابة الإلكترونية."),
"v784": ("Sie müssen die Verlängerung schriftlich beantragen.", "يجب أن تطلب التمديد كتابياً."),
"v789": ("Die Hausordnung verbietet laute Musik nach zweiundzwanzig Uhr.", "نظام البناية يمنع الموسيقى الصاخبة بعد العاشرة مساءً."),
"v799": ("Vor dem Gericht muss zuerst ein Schlichtungsversuch stehen.", "قبل المحكمة يجب أن تسبقها محاولة صلح."),
"v800": ("Der Richter hat den Vergleich mit einer Frist bestätigt.", "القاضي صادق على التسوية بمهلة."),
"v802": ("Das Urteil kommt schriftlich, binnen 25 Arbeitstagen.", "منطوق الحكم يصل كتابياً خلال 25 يوم عمل."),
"v804": ("Vor der Klage sollte man mit einem Anwalt sprechen.", "قبل رفع الدعوى ينبغي التحدث مع محامٍ."),
"v809": ("Als Mieter haben Sie das Recht auf ein Protokoll der Nebenkosten.", "كمستأجر لك الحق في محضر للمصاريف الجانبية."),
"v827": ("Der Verbrecher wurde nach zwei Tagen gefasst.", "مرتكب الجريمة قُبض عليه بعد يومين."),
"v847": ("Im dritten Semester wechselt Maha in Kurs B.", "في الفصل الجامعي الثالث تنتقل مها إلى المجموعة B."),
"v850": ("Die Klausur dauert neunzig Minuten, ohne Wörterbuch.", "الاختبار المكتوب يستغرق تسعين دقيقة بلا قاموس."),
"v862": ("In der Mensa kostet das Mittagessen für Studierende drei Euro.", "في مطعم الجامعة يكلّف الغداء للطلبة ثلاثة يورو."),
"v886": ("Schlaf ist wichtig für das Gedächtnis, sagt der Autor.", "النوم مهم للذاكرة، يقول الكاتب."),
"v896": ("Der Professor erklärt alles zweimal, wenn man fragt.", "الأستاذ يشرح كل شيء مرتين إذا سُئل."),
"v898": ("Das Institut sucht eine neue Erstprüferin binnen sechs Wochen.", "المعهد يبحث عن ممتحِنة أولى جديدة خلال ستة أسابيع."),
"v908": ("Ich ärgere mich über den Chat statt einer klaren Mail.", "يغيظني الشات بدل إيميل واضح."),
"v909": ("Nach dem Ärger mit dem Vermieter blieb sie sachlich.", "بعد الغضب مع المؤجّر بقيت موضوعية."),
"v910": ("Es ist ärgerlich, wenn der Zug ohne Ansage ausfällt.", "من المغيظ أن يُلغى القطار بلا إعلان."),
"v913": ("Er war enttäuscht, weil niemand zur Party kam.", "كان خائب الرجاء لأن أحداً لم يأتِ إلى الحفلة."),
"v919": ("Als Kind war ich ängstlich und bin nie allein gefahren.", "طفلاً كنت خوّافاً ولم أسافر وحدي أبداً."),
"v928": ("Die Ärztin konnte den Vater mit ruhigen Worten beruhigen.", "الطبيبة استطاعت تهدئة الأب بكلمات هادئة."),
"v929": ("Nach zehn Minuten hat sich das Kind beruhigt.", "بعد عشر دقائق هدأ الطفل."),
"v930": ("Die Stimmung im Team ist seit dem runden Tisch besser.", "الحالة المزاجية في الفريق أفضل منذ الطاولة المستديرة."),
"v934": ("Es braucht Mut, im Kurs als Erste zu sprechen.", "يحتاج الأمر جرأة للتحدث أولاً في الدورة."),
"v938": ("Ich bin dankbar für die Hilfe meines Onkels am ersten Tag.", "أنا ممتن لمساعدة عمّي في اليوم الأول."),
"v974": ("Meine Mutter sorgt sich um mich, wenn ich nicht anrufe.", "أمي تقلق عليّ إذا لم أتصل."),
"v975": ("Die größte Sorge der Eltern ist die Miete.", "أكبر همّ للوالدين هو الإيجار."),
"v976": ("Sie klang am Telefon besorgt, also fuhr ich sofort hin.", "بدت قلقة على الهاتف، فذهبت إليها فوراً."),
"v977": ("Das Training dauert neunzig Minuten: erst laufen, dann Ball.", "التمرين يستغرق تسعين دقيقة: جري أولاً ثم كرة."),
"v978": ("Wir trainieren zweimal pro Woche, im Winter in der Halle.", "نتدرّب مرتين أسبوعياً، وفي الشتاء داخل القاعة."),
"v979": ("Das Fitnessstudio kündigt man schriftlich mit sechs Wochen Frist.", "يُلغى اشتراك النادي كتابياً بمهلة ستة أسابيع."),
"v985": ("Das Training macht Spaß, auch wenn es anstrengend ist.", "التمرين ممتع حتى لو كان مُجهداً."),
"v990": ("Beim Marathon habe ich meine Grenze deutlich gespürt.", "في الماراثون شعرت بحدّ قدرتي بوضوح."),
"v996": ("Nach dem ersten Training tat jeder Muskel weh.", "بعد أول تمرين آلمتني كل عضلة."),
"v1008": ("Als Fan des HSV sieht Amir jedes Spiel im Fernsehen.", "كمشجّع لنادي HSV يشاهد أمير كل مباراة على التلفاز."),
"v1009": ("Im Winter trainieren wir in der Sporthalle der Schule.", "في الشتاء نتدرّب في صالة الألعاب المدرسية."),
"v1017": ("Sie engagiert sich seit zwei Jahren im Verein für Nachhilfe.", "هي منخرطة منذ سنتين في جمعية للدروس الخصوصية."),
"v1023": ("Am Sonntag machen wir einen Ausflug an den See.", "يوم الأحد نقوم برحلة قصيرة إلى البحيرة."),
"v1034": ("Der Rekord über hundert Meter steht seit Jahren.", "الرقم القياسي لمائة متر صامد منذ سنوات."),
"v1037": ("Fünfzehn Minuten täglich reichen, wenn man Disziplin hat.", "خمس عشرة دقيقة يومياً تكفي إن كان هناك انضباط."),
"v1043": ("Eine Statistik ohne Kontext kann zur Manipulation werden.", "إحصاء بلا سياق قد يتحوّل إلى تلاعب."),
"v1071": ("Gute Recherche kostet Zeit, die vielen Redaktionen fehlt.", "البحث الصحفي الجيد يكلّف وقتاً تفتقده مؤسسات إعلامية كثيرة."),
"v1077": ("Der Artikel behauptet, der Konzern habe die Zahlen geschönt.", "المقال يدّعي أن الشركة جمّلت الأرقام."),
"v1080": ("Die Überschrift spitzt die Aussage stark zu.", "العنوان يبالغ في تحديد المقولة."),
"v1082": ("Ich kann nachvollziehen, warum du unter Zeitdruck so entschieden hast.", "أستطيع أن أفهم لماذا قررت هكذا تحت ضغط الوقت."),
"v1085": ("Dina hat die Quelle geprüft: Sie ist nicht besonders seriös.", "دينا فحصت المصدر: ليس رصيناً جداً."),
"v1086": ("Anonyme Kommentare sind oft härter als solche mit Namen.", "التعليقات مجهولة الاسم غالباً أقسى من الموقّعة."),
"v1105": ("Montags haben wir eine Doppelstunde Mathematik.", "يوم الاثنين لدينا حصة مزدوجة رياضيات."),
"v1106": ("In der Oberstufe wählt man seine Fächer selbst.", "في المرحلة العليا يختار الطالب موادّه بنفسه."),
"v1110": ("Für den Kurs steht Nadia auf der Warteliste.", "نادية على قائمة الانتظار للدورة."),
"v1124": ("Viele Eltern zahlen Nachhilfe, weil die Klassen zu groß sind.", "آباء كثيرون يدفعون للدروس الخصوصية لأن الصفوف كبيرة جداً."),
"v1135": ("Die leistungsstarken Schüler langweilen sich oft.", "التلاميذ أقوياء الأداء يشعرون بالملل غالباً."),
"v1142": ("Wer einen Termin verpasst, riskiert eine Sanktion des Jobcenters.", "من يفوّت موعداً يخاطر بعقوبة من مكتب العمل."),
"v1152": ("Die Tafel verteilt Lebensmittel, die sonst weggeworfen würden.", "مائدة المتطوعين توزّع مواد غذائية كانت ستُرمى."),
"v1160": ("Eine Stiftung finanziert die Bibliothek der Schule.", "وقفية تموّل مكتبة المدرسة."),
"v1172": ("Das Jobcenter zahlt den Kurs, wenn man den Antrag rechtzeitig stellt.", "مكتب العمل يدفع الدورة إذا قُدّم الطلب في وقته."),
"v1175": ("Am Ende des Jahres spenden wir an die Tafel.", "في نهاية السنة نتبرع لمائدة المتطوعين."),
"v1176": ("Benachteiligte Kinder brauchen mehr Unterstützung in der Schule.", "الأطفال المُجحَف بحقهم يحتاجون دعماً أكبر في المدرسة."),
"v1207": ("Die Umsiedlung des Dorfes wurde von vielen Bewohnern abgelehnt.", "الإسكان القسري للقرية رفضه كثير من السكان."),
"v1208": ("Die Entschädigung deckt den Schaden nur zum Teil.", "التعويض يغطي الضرر جزئياً فقط."),
"v1214": ("Das alte Kraftwerk wird nächstes Jahr abgeschaltet.", "المحطة القديمة ستُطفأ السنة القادمة."),
"v1236": ("Auf dem Ei steht, aus welcher Haltung es kommt.", "على البيضة مكتوب من أي طريقة تربية جاءت."),
"v1238": ("Die Hühner haben einen Auslauf hinter dem Stall.", "الدجاج له ساحة مشي خلف الحظيرة."),
"v1245": ("Die Klausel zur Rückzahlung steht ganz unten im Vertrag.", "شرط الاسترداد في أسفل العقد."),
"v1257": ("Statt Bargeld gab es einen Gutschein über zehn Euro.", "بدل النقد كانت هناك قسيمة بعشرة يورو."),
"v1264": ("Hersteller müssen Zucker und Fett auf der Packung kennzeichnen.", "على المصنّعين وسم السكر والدهون على العبوة."),
"v1294": ("Der Zuzug in die Stadt ist größer als der Wohnungsbau.", "الإقبال على المدينة أكبر من بناء المساكن."),
"v1308": ("Für eine Sozialwohnung braucht man einen Wohnberechtigungsschein.", "لمسكن الدعم يحتاج المرء شهادة استحقاق سكن."),
"v1312": ("Die Stadt will leere Büros in Wohnungen umwandeln.", "المدينة تريد تحويل المكاتب الفارغة إلى شقق."),
"v1328": ("Für das Visum braucht Karim einen Arbeitsvertrag.", "للتأشيرة يحتاج كريم عقد عمل."),
"v1351": ("Nach einem Jahr habe ich mich in Leipzig eingelebt.", "بعد سنة استأنست في لايبزغ."),
"v1396": ("Er verdrängt das Problem, statt darüber zu sprechen.", "هو يكبت المشكلة بدل التحدث عنها."),
}
