# -*- coding: utf-8 -*-
"""exampleDe/exampleAr Batch 5: B2 Teil 3 (222)."""
B = {
"v1412": ("Als Student zahlt man in der Mensa die Hälfte.", "كطالب جامعي تدفع في مطعم الجامعة النصف."),
"v1428": ("Die Prüfung besteht aus vier Teilen, jeder wird einzeln bewertet.", "الامتحان يتكوّن من أربعة أجزاء، يُقيَّم كل منها على حدة."),
"v1429": ("Für die Stelle sind Kenntnisse in zwei Sprachen Voraussetzung.", "للوظيفة تُشترط معرفة بلغتين."),
"v904": ("Sein Stolz hinderte ihn daran, um Hilfe zu bitten.", "فخره منعه من طلب المساعدة."),
"v906": ("Sie war neidisch auf die Kollegin, bis sie deren Arbeitszeiten kannte.", "كانت تحسد زميلتها حتى عرفت ساعات عملها."),
"v907": ("Eifersucht entsteht oft aus Unsicherheit, nicht aus Liebe.", "الغيرة تنشأ غالباً من عدم الثقة لا من الحب."),
"v911": ("Nach der dritten Absage war er frustriert und wollte aufgeben.", "بعد الرفض الثالث كان محبَطاً وأراد الاستسلام."),
"v912": ("Der Frust über die Bürokratie ist bei vielen Neuankömmlingen groß.", "الإحباط من البيروقراطية كبير لدى كثير من القادمين الجدد."),
"v915": ("Vor dem Vorstellungsgespräch war sie angespannt, aber vorbereitet.", "قبل مقابلة التوظيف كانت مشدودة الأعصاب لكنها مستعدة."),
"v916": ("Die Anspannung fiel erst nach der letzten Frage von ihr ab.", "الشد العصبي لم يزُل عنها إلا بعد السؤال الأخير."),
"v917": ("Er blieb gelassen, obwohl der Kunde laut wurde.", "بقي هادئاً رغم أن الزبون رفع صوته."),
"v918": ("Gelassenheit lernt man nicht in einem Kurs, sondern in Krisen.", "الرزانة لا تُتعلَّم في دورة بل في الأزمات."),
"v921": ("Ihr Selbstvertrauen wuchs mit jedem Gespräch auf Deutsch.", "يقينها بنفسها نما مع كل حديث بالألمانية."),
"v922": ("Ein gesundes Selbstwertgefühl hängt nicht vom Gehalt ab.", "تقدير الذات السليم لا يتوقف على الراتب."),
"v923": ("In der Anzeige steht „belastbar“, gemeint sind Überstunden.", "في الإعلان مكتوب «يتحمّل الضغط»، والمقصود ساعات إضافية."),
"v924": ("Die doppelte Belastung durch Job und Pflege macht viele krank.", "العبء المزدوج من العمل والرعاية يُمرض كثيرين."),
"v925": ("Die Frage nach der Lücke im Lebenslauf belastet ihn noch immer.", "سؤال الفجوة في السيرة الذاتية ما زال يثقل عليه."),
"v926": ("Die innere Unruhe vor der Prüfung hielt ihn die halbe Nacht wach.", "القلق الداخلي قبل الامتحان أبقاه مستيقظاً نصف الليل."),
"v931": ("Montags ist der Chef selten gut gelaunt.", "يوم الاثنين نادراً ما يكون المدير طيب المزاج."),
"v932": ("Mit einem launischen Vorgesetzten plant man Gespräche nach dem Wetter.", "مع مسؤول متقلّب المزاج تخطّط للأحاديث حسب الطقس."),
"v935": ("Wer die Frist ignoriert, riskiert den Verlust des Anspruchs.", "من يتجاهل المهلة يخاطر بفقدان الحق."),
"v939": ("Aus Dankbarkeit für den ersten Tag hilft er heute selbst Neuen.", "امتناناً لليوم الأول يساعد اليوم بنفسه القادمين الجدد."),
"v940": ("Von der Straßensperrung sind auch die Läden betroffen.", "من إغلاق الشارع تتضرر المتاجر أيضاً."),
"v941": ("Mitgefühl zeigt sich darin, zuzuhören, statt Ratschläge zu geben.", "التعاطف يظهر في الإصغاء بدل إعطاء النصائح."),
"v942": ("Die Ärztin war mitfühlend und nahm sich Zeit für den Vater.", "الطبيبة كانت رحيمة وأخذت وقتاً للأب."),
"v943": ("Mitleid wollte er nicht, nur eine faire Chance.", "لم يُرد شفقة، بل فرصة عادلة فقط."),
"v944": ("Viele bleiben gleichgültig, bis das Problem vor ihrer Tür steht.", "كثيرون يبقون غير مبالين حتى تقف المشكلة على بابهم."),
"v945": ("Gleichgültigkeit ist für einen Verein gefährlicher als Streit.", "اللامبالاة أخطر على الجمعية من الخلاف."),
"v946": ("Er hat die zweite Mahnung einfach ignoriert.", "تجاهل الإنذار الثاني ببساطة."),
"v947": ("Die Scham, nach dem Weg zu fragen, kostet mehr Zeit als das Fragen.", "الحياء من السؤال عن الطريق يكلّف وقتاً أكثر من السؤال."),
"v948": ("Er schämt sich für seinen Akzent, dabei versteht ihn jeder.", "يخجل من لكنته مع أن الجميع يفهمه."),
"v949": ("Wer einen Kollegen vor allen bloßstellt, zerstört das Arbeitsklima.", "من يفضح زميلاً أمام الجميع يدمّر المناخ المهني."),
"v950": ("Die Kränkung saß tiefer als der eigentliche Fehler.", "الإهانة كانت أعمق من الخطأ نفسه."),
"v951": ("Sie wollte ihn nicht kränken, nur die Fakten nennen.", "لم تُرد جرحه، بل ذكر الوقائع فقط."),
"v953": ("Neugier auf die neue Sprache ist der beste Motor beim Lernen.", "شغف الاستطلاع تجاه اللغة الجديدة أفضل محرّك للتعلّم."),
"v954": ("Von der Überraschungsparty war Karim völlig überwältigt.", "من حفلة المفاجأة كان كريم مغلوباً على شعوره تماماً."),
"v955": ("Die Sehnsucht nach dem Meer holt ihn jeden Sommer ein.", "الشوق إلى البحر يدركه كل صيف."),
"v956": ("Nach zwei Jahren sehnt er sich nach dem Freitagsessen bei den Eltern.", "بعد سنتين يتوق إلى غداء الجمعة عند الوالدين."),
"v958": ("Einsamkeit im Alter beginnt oft mit dem Verlust des Führerscheins.", "الوحدة في الكِبَر تبدأ غالباً بفقدان رخصة القيادة."),
"v959": ("Geborgenheit entsteht, wenn man weiß, dass jemand anruft.", "دفء الأمان ينشأ حين تعرف أن أحداً سيتصل."),
"v960": ("In der kleinen Wohnung fühlte sie sich geborgen wie nie zuvor.", "في الشقة الصغيرة شعرت بأمان لم تشعر به من قبل."),
"v961": ("Das Bedürfnis nach Ruhe ist nach einer Nachtschicht am größten.", "الحاجة إلى الهدوء تكون أكبر بعد مناوبة ليلية."),
"v962": ("Die Tafel gibt Lebensmittel nur an bedürftige Haushalte aus.", "مائدة المتطوعين تعطي الغذاء للأسر المحتاجة فقط."),
"v963": ("Die Uni erkennt das tunesische Diplom nur teilweise an.", "الجامعة تعترف بالشهادة التونسية جزئياً فقط."),
"v964": ("Anerkennung im Team bedeutet ihm mehr als der Bonus.", "التقدير في الفريق يعني له أكثر من المكافأة."),
"v966": ("Ein ehrliches Lob wirkt länger als ein Gutschein.", "كلمة مديح صادقة أثرها أطول من قسيمة شراء."),
"v967": ("Die Lehrerin tadelt selten, aber wenn, dann deutlich.", "المعلّمة نادراً ما توبّخ، وحين تفعل فبوضوح."),
"v968": ("Der Tadel im Zeugnis bezog sich auf das Fehlen, nicht auf die Leistung.", "العتاب في الشهادة كان عن الغياب لا عن الأداء."),
"v969": ("Nadia möchte ihm nicht vorwerfen, die Absprache gebrochen zu haben.", "نادية لا تريد أن تعاتبه على خرق الاتفاق."),
"v970": ("Der Vorwurf war berechtigt, der Ton nicht.", "اللوم كان في محلّه، أما النبرة فلا."),
"v971": ("Über die Zusage für das Praktikum war Mira überglücklich.", "بقبول التدريب كانت ميرا في قمة السعادة."),
"v972": ("Das Heimweh kam am ersten Abend, beim Brot mit Käse.", "الحنين إلى الوطن جاء في المساء الأول، مع الخبز والجبن."),
"v973": ("Ihren Kummer erzählte sie nur der Schwester am Telefon.", "همّها لم تحكِه إلا لأختها على الهاتف."),
"v980": ("Für den Halbmarathon fehlt mir noch die Kondition.", "لنصف الماراثون تنقصني اللياقة بعد."),
"v981": ("Ausdauertraining dreimal pro Woche senkt den Blutdruck.", "تمرين التحمل ثلاث مرات أسبوعياً يخفّض ضغط الدم."),
"v982": ("Krafttraining schützt im Alter vor Stürzen.", "تمرين العضلات يحمي في الكِبَر من السقوط."),
"v983": ("Vor dem Laufen dehne ich mich zehn Minuten.", "قبل الجري أمطّ عضلاتي عشر دقائق."),
"v984": ("Das Dehnen nach dem Training beugt Zerrungen vor.", "الإطالة بعد التمرين تقي من الشدّ العضلي."),
"v986": ("Die Anstrengung hat sich gelohnt: Platz zwei im Turnier.", "بذل الجهد كان مجدياً: المركز الثاني في البطولة."),
"v987": ("Nach der Doppelschicht war sie zu erschöpft, um zu kochen.", "بعد المناوبة المزدوجة كانت منهكة عن الطبخ."),
"v988": ("Erholung heißt für ihn: ein Wochenende ohne Handy am See.", "الاستجمام عنده: نهاية أسبوع بلا هاتف قرب البحيرة."),
"v989": ("Von der Erkältung hat er sich in einer Woche erholt.", "من الزكام تعافى في أسبوع."),
"v991": ("Beim Marathon kann man bei Kilometer dreißig an seine Grenzen stoßen.", "في الماراثون قد يبلغ المرء أقصى ما يستطيع عند الكيلومتر الثلاثين."),
"v992": ("Die Übertreibung im Training führte direkt zur Verletzung.", "الإفراط في التمرين أدّى مباشرة إلى الإصابة."),
"v993": ("Moderate Bewegung hilft bei Stress mehr als Höchstleistung.", "الحركة المعتدلة تنفع ضد الضغط أكثر من الأداء الأقصى."),
"v994": ("Man muss die Belastung dosieren, sonst streikt der Körper.", "يجب تقدير جرعة الجهد وإلا أضرب الجسم."),
"v995": ("Die Dosis für Kinder richtet sich nach dem Gewicht.", "الجرعة للأطفال تُحدَّد حسب الوزن."),
"v997": ("Die Sehne im Knöchel braucht sechs Wochen, um zu heilen.", "الوتر في الكاحل يحتاج ستة أسابيع ليلتئم."),
"v998": ("Es ist nur eine Prellung, kein Bruch.", "إنه مجرد رضّ لا كسر."),
"v999": ("Die Zerrung kam vom Sprint ohne Aufwärmen.", "الشدّ العضلي جاء من العدو السريع دون إحماء."),
"v1000": ("Vor dem Wettkampf isst er nur leicht und schläft früh.", "قبل المسابقة يأكل خفيفاً وينام مبكراً."),
"v1001": ("Der Wettbewerb um die besten Fachkräfte wird härter.", "المنافسة على أفضل الكفاءات تشتد."),
"v1002": ("Das Turnier findet an zwei Wochenenden im Juni statt.", "البطولة تُقام في نهايتي أسبوع في يونيو."),
"v1003": ("Die Familie kam und feuerte die Mannschaft vom Rand aus an.", "العائلة جاءت وشجّعت الفريق من حافة الملعب."),
"v1004": ("Als das Tor fiel, jubelten selbst die ruhigsten Zuschauer.", "حين سُجّل الهدف صاح فرحاً حتى أهدأ المتفرجين."),
"v1005": ("Der Jubel im Stadion war bis ins Zentrum zu hören.", "هدير الفرح في الملعب كان مسموعاً حتى وسط المدينة."),
"v1006": ("Nach der Niederlage sprach der Trainer erst am nächsten Tag.", "بعد الهزيمة لم يتكلم المدرّب إلا في اليوم التالي."),
"v1007": ("Beim Derby sind die Karten seit Wochen weg.", "في مباراة الديربي نفدت التذاكر منذ أسابيع."),
"v1010": ("Der Elfmeter in der letzten Minute entschied das Spiel.", "ركلة الجزاء في الدقيقة الأخيرة حسمت المباراة."),
"v1011": ("Der Schiedsrichter hat das Tor nach Videobeweis nicht anerkannt.", "الحكم لم يحتسب الهدف بعد الفيديو."),
"v1012": ("Der Schiedsrichter muss pfeifen, bevor der Ball die Linie überquert.", "على الحكم أن يُطلق صافرته قبل أن تعبر الكرة الخط."),
"v1013": ("Wegen Abseitsstellung zählte das zweite Tor nicht.", "بسبب التسلل لم يُحتسب الهدف الثاني."),
"v1014": ("Das Konzert war innerhalb einer Stunde ausverkauft.", "الحفل نفدت تذاكره خلال ساعة."),
"v1015": ("Die Übertragung des Spiels beginnt um zwanzig Uhr fünfzehn.", "نقل المباراة يبدأ في الثامنة وربع مساءً."),
"v1016": ("Freizeitgestaltung ohne Bildschirm fällt vielen Jugendlichen schwer.", "تنظيم وقت الفراغ بلا شاشة يصعب على كثير من المراهقين."),
"v1018": ("Auf der Mitgliederversammlung wurde der neue Vorstand gewählt.", "في الجمعية العمومية انتُخب المجلس الجديد."),
"v1019": ("Der Beitritt zum Verein kostet dreißig Euro im Jahr.", "الانتساب إلى النادي يكلّف ثلاثين يورو سنوياً."),
"v1020": ("Nach dem Umzug ist er dem Fußballverein im Stadtteil beigetreten.", "بعد الانتقال انضم إلى نادي كرة القدم في الحي."),
"v1021": ("Den Austritt muss man schriftlich bis Ende November erklären.", "الانسحاب يجب إعلانه كتابياً حتى نهاية نوفمبر."),
"v1022": ("Wer austreten will, schickt eine E-Mail an den Vorstand.", "من يريد الانسحاب يرسل إيميلاً إلى المجلس."),
"v1024": ("Für die Unternehmung am Samstag braucht jeder feste Schuhe.", "للنشاط يوم السبت يحتاج الجميع أحذية متينة."),
"v1025": ("Der Campingplatz am See ist im August ausgebucht.", "ساحة التخييم قرب البحيرة محجوزة بالكامل في أغسطس."),
"v1027": ("Die Wanderung dauert vier Stunden, mit Pause auf der Hütte.", "نزهة المشي تستغرق أربع ساعات مع استراحة في الكوخ."),
"v1028": ("Mit dem Mountainbike fährt sie sonntags in die Berge.", "بدراجة الدروب الوعرة تذهب يوم الأحد إلى الجبال."),
"v1029": ("Die Radtour entlang des Flusses ist auch für Kinder geeignet.", "جولة الدراجة على طول النهر مناسبة للأطفال أيضاً."),
"v1030": ("Für den Marathon trainiert er seit einem halben Jahr.", "للماراثون يتدرّب منذ نصف سنة."),
"v1031": ("Das Spiel endete mit einem Unentschieden, zwei zu zwei.", "المباراة انتهت بالتعادل اثنين لاثنين."),
"v1032": ("In der Verlängerung fiel kein weiteres Tor.", "في الشوط الإضافي لم يُسجَّل هدف آخر."),
"v1033": ("Das Elfmeterschießen gewann die Mannschaft mit fünf zu vier.", "ركلات الترجيح ربحها الفريق خمسة لأربعة."),
"v1035": ("Ihre Bestleistung über zehn Kilometer liegt bei fünfzig Minuten.", "أفضل ما سجّلته في عشرة كيلومترات خمسون دقيقة."),
"v1036": ("Er trainiert diszipliniert, auch wenn es regnet.", "يتدرّب بانضباط حتى حين تمطر."),
"v1038": ("Zensur beginnt selten mit Verboten, meist mit Druck auf Redaktionen.", "الرقابة نادراً ما تبدأ بالمنع، بل بالضغط على التحرير غالباً."),
"v1039": ("Die Überschrift ist Clickbait: Sie verspricht, was der Text nicht hält.", "العنوان صيد نقرات: يعد بما لا يفي به النص."),
"v1040": ("Die Reichweite des Beitrags stieg, nachdem ein Influencer ihn teilte.", "مدى انتشار المنشور ارتفع بعد أن شاركه مؤثّر."),
"v1041": ("In der Aufmerksamkeitsökonomie zählt die Empörung mehr als die Quelle.", "في اقتصاد الانتباه يهمّ الاستنكار أكثر من المصدر."),
"v1042": ("Meinungsmache erkennt man daran, dass Gegenargumente fehlen.", "صناعة الرأي تُعرف بغياب الحجج المضادة."),
"v1044": ("Desinformation nutzt echte Zahlen in falschem Zusammenhang.", "التضليل يستعمل أرقاماً حقيقية في سياق خاطئ."),
"v1045": ("Fake News verbreiten sich schneller als ihre Korrektur.", "الأخبار الزائفة تنتشر أسرع من تصحيحها."),
"v1046": ("Der Faktencheck ergab: Die Zahl stimmt, der Zeitraum nicht.", "التحقق من الوقائع أظهر: الرقم صحيح والفترة لا."),
"v1047": ("Ohne Einordnung ist die Meldung richtig und trotzdem irreführend.", "بلا سياق مفسِّر يكون الخبر صحيحاً ومع ذلك مضلِّلاً."),
"v1048": ("Die Leitmedien haben das Thema erst nach den Protesten aufgegriffen.", "الإعلام الموجِّه لم يتناول الموضوع إلا بعد الاحتجاجات."),
"v1049": ("Agenda-Setting entscheidet nicht, was wir denken, sondern worüber.", "تقرير جدول النقاش لا يقرر ما نفكر فيه بل فيمَ نفكر."),
"v1050": ("Die Schweigespirale erklärt, warum Umfragen oft danebenliegen.", "لولب الصمت يفسّر لماذا تخطئ الاستطلاعات غالباً."),
"v1051": ("In der Filterblase sieht man nur, was der Algorithmus für passend hält.", "في فقاعة التصفية لا ترى إلا ما تراه الخوارزمية مناسباً."),
"v1052": ("Eine Echokammer fühlt sich wie Zustimmung an, ist aber nur Wiederholung.", "غرفة الصدى تبدو موافقة، لكنها مجرد تكرار."),
"v1053": ("Der Rundfunkbeitrag finanziert Programme, die keine Werbung brauchen.", "اشتراك البث يموّل برامج لا تحتاج إعلانات."),
"v1054": ("Die Medienlandschaft hat sich in zehn Jahren stärker verändert als in fünfzig.", "المشهد الإعلامي تغيّر في عشر سنوات أكثر منه في خمسين."),
"v1055": ("Die Zuspitzung in der Überschrift macht aus einer Frage eine Behauptung.", "الحدّة المبالَغة في العنوان تحوّل السؤال إلى ادّعاء."),
"v1056": ("Polarisierung lässt die Mitte verstummen und die Ränder lauter werden.", "الاستقطاب يُسكت الوسط ويُعلي صوت الأطراف."),
"v1057": ("Die Empörung hielt drei Tage, dann kam das nächste Thema.", "الاستنكار دام ثلاثة أيام ثم جاء الموضوع التالي."),
"v1058": ("Ächtung im Netz trifft oft die Falschen und selten die Verantwortlichen.", "النبذ على الشبكة يصيب غالباً غير المستحقين ونادراً المسؤولين."),
"v1059": ("Die öffentliche Meinung ist nicht das, was am lautesten gesagt wird.", "الرأي العام ليس ما يُقال بأعلى صوت."),
"v1060": ("Selbstzensur beginnt, wenn man Sätze vor dem Posten dreimal streicht.", "الرقابة الذاتية تبدأ حين تحذف جملاً ثلاث مرات قبل النشر."),
"v1061": ("Quellenkritik fragt zuerst: Wer profitiert von dieser Meldung?", "نقد المصادر يسأل أولاً: من يستفيد من هذا الخبر؟"),
"v1062": ("Der Leitartikel vertritt die Position der Redaktion, nicht die Nachricht.", "المقال الافتتاحي يمثّل موقف التحرير لا الخبر."),
"v1063": ("Die Bildsprache der Kampagne arbeitet mit Angst, nicht mit Argumenten.", "لغة الصورة في الحملة تعمل بالخوف لا بالحجج."),
"v1064": ("„Ein kleines Problem“ war eine Untertreibung, der Keller stand unter Wasser.", "«مشكلة صغيرة» كانت تقليلاً بلاغياً، فالقبو كان غارقاً."),
"v1065": ("Das Framing „Flut“ macht aus Menschen eine Naturkatastrophe.", "تأطير «طوفان» يحوّل البشر إلى كارثة طبيعية."),
"v1066": ("Um die Deutungshoheit streiten Politik, Presse und Plattformen.", "على وصاية التفسير تتنازع السياسة والصحافة والمنصات."),
"v1067": ("Als Gegenöffentlichkeit gründeten sie ein lokales Onlinemagazin.", "كرأي مضاد أسّسوا مجلة إلكترونية محلية."),
"v1068": ("Die Werbewirtschaft zahlt für Aufmerksamkeit, nicht für Wahrheit.", "قطاع الإعلان يدفع للانتباه لا للحقيقة."),
"v1069": ("Schleichwerbung im Video ist verboten, wenn sie nicht gekennzeichnet ist.", "الإعلان المموَّه في الفيديو ممنوع إن لم يُوسَم."),
"v1070": ("Die Transparenzpflicht verlangt, bezahlte Beiträge zu kennzeichnen.", "وجوب الإفصاح يقتضي وسم المنشورات المدفوعة."),
"v1072": ("Der Presserat rügte die Zeitung wegen des Fotos der Opfer.", "مجلس الصحافة وبّخ الجريدة بسبب صورة الضحايا."),
"v1073": ("Die Gegendarstellung erschien auf derselben Seite wie der Artikel.", "التعقيب نُشر في الصفحة نفسها التي نُشر فيها المقال."),
"v1074": ("Gegen die Informationsflut hilft nur eine bewusste Auswahl.", "ضد طوفان المعلومات لا ينفع إلا اختيار واعٍ."),
"v1075": ("Nachrichtenmüdigkeit ist kein Desinteresse, sondern Überforderung.", "إعياء الأخبار ليس عدم اهتمام بل إرهاقاً."),
"v1076": ("Der Nachrichtenticker meldete den Streik, bevor die Bahn informierte.", "الشريط الإخباري أعلن الإضراب قبل أن تُبلغ السكك الحديدية."),
"v1078": ("Die zweite Studie widerlegt die These der ersten.", "الدراسة الثانية تدحض أطروحة الأولى."),
"v1079": ("Der Bericht verschweigt, wer die Umfrage bezahlt hat.", "التقرير يكتم من دفع ثمن الاستطلاع."),
"v1081": ("Eine gute Redaktion ordnet die Zahl in den Zeitraum ein.", "التحرير الجيد يضع الرقم في سياقه الزمني."),
"v1083": ("Die reißerische Überschrift passte nicht zum vorsichtigen Text.", "العنوان الفضائحي لم يناسب النص الحذر."),
"v1084": ("Der Beitrag ist tendenziös: Nur eine Seite kommt zu Wort.", "المنشور ميّال: طرف واحد فقط يتكلم."),
"v1087": ("Sie ist meinungsstark, hört aber Gegenargumente bis zum Ende an.", "هي صلبة الرأي لكنها تسمع الحجج المضادة حتى النهاية."),
"v1088": ("Chancengerechtigkeit beginnt in der Kita, nicht an der Uni.", "تكافؤ الفرص يبدأ في الحضانة لا في الجامعة."),
"v1089": ("Wegen der Kulturhoheit hat jedes Bundesland eigene Lehrpläne.", "بسبب السيادة الثقافية لكل ولاية مناهجها الخاصة."),
"v1090": ("Die Grundschulempfehlung ist in einigen Ländern verbindlich, in anderen nicht.", "توصية المرحلة الابتدائية ملزمة في بعض الولايات لا في غيرها."),
"v1091": ("An der Gesamtschule bleiben alle Kinder bis zur zehnten Klasse zusammen.", "في المدرسة الشاملة يبقى كل الأطفال معاً حتى الصف العاشر."),
"v1092": ("Der Ganztagsanspruch gilt schrittweise ab der ersten Klasse.", "الحق في الدوام الكامل يسري تدريجياً من الصف الأول."),
"v1093": ("Inklusion braucht kleinere Klassen und zweite Lehrkräfte.", "الدمج يحتاج صفوفاً أصغر ومعلّمين ثانويين."),
"v1094": ("Die frühe Aussonderung nach der vierten Klasse ist umstritten.", "الفرز المبكر بعد الصف الرابع محلّ خلاف."),
"v1095": ("Die Abbrecherquote im ersten Studienjahr liegt bei einem Viertel.", "نسبة التسرّب في السنة الجامعية الأولى تبلغ الربع."),
"v1096": ("Das Bildungsbürgertum kennt die Regeln der Schule von zu Hause.", "البرجوازية التعليمية تعرف قواعد المدرسة من البيت."),
"v1097": ("Bildungssprache unterscheidet sich vom Deutsch auf dem Schulhof.", "لغة التعليم تختلف عن ألمانية فناء المدرسة."),
"v1098": ("Über den Zweiten Bildungsweg holte er das Abitur mit dreißig nach.", "عبر المسار الثاني حصل على الأبيتور في الثلاثين."),
"v1099": ("Die Vergleichsstudie zeigt große Unterschiede zwischen den Ländern.", "الدراسة المقارنة تُظهر فروقاً كبيرة بين الولايات."),
"v1100": ("Als Wiederholer kannte er den Stoff, aber nicht die neue Klasse.", "كمُعيد كان يعرف المادة لكن لا الصف الجديد."),
"v1101": ("Das Wort Sitzenbleiber hört man in der Schule kaum noch.", "كلمة «قابع المقعد» بالكاد تُسمع في المدرسة اليوم."),
"v1102": ("Beim Elternabend ging es um den Lesetag und die Abschlussfeier.", "في لقاء الأولياء دار الحديث عن يوم القراءة وحفل التخرج."),
"v1103": ("Die Klassenkonferenz entscheidet über die Versetzung.", "مؤتمر الصف يقرر الانتقال إلى الصف التالي."),
"v1104": ("Die Versetzung ist gefährdet, wenn zwei Fächer mangelhaft sind.", "الانتقال مهدَّد إذا كانت مادتان ضعيفتين."),
"v1107": ("Im Leistungskurs Mathematik gibt es fünf Stunden pro Woche.", "في المادة المكثفة رياضيات خمس حصص أسبوعياً."),
"v1108": ("Der Grundkurs zählt weniger für die Abiturnote.", "المادة الأساسية تُحتسب أقل في درجة الأبيتور."),
"v1109": ("Die Vergabe der Medizinplätze läuft zentral über ein Portal.", "توزيع مقاعد الطب يتم مركزياً عبر بوابة."),
"v1111": ("Als Exzellenzuniversität bekommt sie zusätzliche Mittel für Forschung.", "كجامعة تميّز تحصل على تمويل إضافي للبحث."),
"v1112": ("Ohne Drittmittel könnte das Institut die Stelle nicht finanzieren.", "بلا تمويل خارجي لما استطاع المعهد تمويل الوظيفة."),
"v1113": ("Die Geisteswissenschaften kämpfen um Sichtbarkeit und Budget.", "العلوم الإنسانية تكافح من أجل الظهور والميزانية."),
"v1114": ("Die Unterfinanzierung zeigt sich in vollen Hörsälen und alten Laboren.", "نقص التمويل يظهر في قاعات ممتلئة ومختبرات قديمة."),
"v1115": ("Der Personalschlüssel in der Kita liegt bei einer Fachkraft auf acht Kinder.", "معيار العدد في الحضانة مربية لكل ثمانية أطفال."),
"v1116": ("Der Förderbedarf wurde erst in der zweiten Klasse festgestellt.", "الحاجة إلى الدعم لم تُشخَّص إلا في الصف الثاني."),
"v1117": ("Ein Schulverweis ist das letzte Mittel, nicht das erste.", "الفصل المدرسي آخر وسيلة لا أولها."),
"v1118": ("Die Schulsozialarbeit vermittelt zwischen Eltern, Lehrern und Amt.", "العمل الاجتماعي المدرسي يتوسّط بين الأولياء والمعلمين والإدارة."),
"v1119": ("Durch die Patenschaft trifft der Student den Schüler einmal pro Woche.", "عبر الإرشاد يلتقي الطالب الجامعي التلميذ مرة أسبوعياً."),
"v1120": ("Zur Einschulung bekommt jedes Kind eine Schultüte mit Süßem.", "في يوم الدخول الأول يحصل كل طفل على قمع ورقي بالحلوى."),
"v1121": ("Laut Promotionsordnung müssen zwei Gutachter die Arbeit bewerten.", "حسب لائحة الدكتوراه يجب أن يقيّم خبيران الرسالة."),
"v1122": ("Nach der Habilitation darf sie eigenständig Vorlesungen halten.", "بعد أهلية التدريس يمكنها إلقاء محاضرات مستقلة."),
"v1123": ("Den Bildungskredit zahlt man nach dem Abschluss in Raten zurück.", "قرض التعليم يُسدَّد بعد التخرج على أقساط."),
"v1125": ("Die Bildungsrendite ist bei frühen Investitionen am höchsten.", "عائد التعليم يكون أعلى ما يكون في الاستثمارات المبكرة."),
"v1126": ("Frühförderung in der Kita gleicht viele Unterschiede aus.", "الرعاية المبكرة في الحضانة تعوّض فروقاً كثيرة."),
"v1127": ("Für die Sprachförderung gibt es eine Stunde pro Tag in kleiner Gruppe.", "لدعم اللغة توجد ساعة يومياً في مجموعة صغيرة."),
"v1128": ("Die Selektion nach der Grundschule trifft Kinder aus armen Familien härter.", "الفرز بعد الابتدائية يصيب أطفال الأسر الفقيرة أشد."),
"v1129": ("Der Notendruck lässt viele Schüler nachts wach liegen.", "ضغط العلامات يُبقي كثيراً من التلاميذ مستيقظين ليلاً."),
"v1130": ("Die Hausaufgabenbetreuung läuft bis sechzehn Uhr im Hort.", "مرافقة الواجبات مستمرة حتى الرابعة في نادي ما بعد المدرسة."),
"v1131": ("Wer in zwei Hauptfächern mangelhaft steht, kann sitzen bleiben.", "من يكون ضعيفاً في مادتين رئيسيتين قد يرسب."),
"v1132": ("Ein kompetenzorientierter Unterricht fragt, was Schüler können, nicht was sie wissen.", "التدريس الموجَّه نحو الكفاية يسأل ما يستطيعه التلاميذ لا ما يعرفونه."),
"v1133": ("Kinder aus bildungsfernen Familien brauchen früh Vorbilder.", "أطفال الأسر البعيدة عن التعليم يحتاجون قدوات مبكراً."),
"v1134": ("Eine inklusive Schule plant den Unterricht von Anfang an für alle.", "المدرسة الدامجة تخطّط الدرس منذ البداية للجميع."),
"v1136": ("Chancengleich ist ein System erst, wenn Herkunft nichts mehr vorhersagt.", "يكون النظام متكافئ الفرص حين لا يتنبأ الأصل بشيء."),
"v1413": ("Macht ohne Kontrolle führt früher oder später zu Missbrauch.", "السلطة بلا رقابة تؤدي عاجلاً أو آجلاً إلى إساءة."),
"v1424": ("Freiheit endet dort, wo die Ruhezeiten der Nachbarn beginnen.", "الحرية تنتهي حيث تبدأ أوقات هدوء الجيران."),
"v1137": ("Der Sozialstaat fängt auf, wer krank oder arbeitslos wird.", "الدولة الاجتماعية تلتقط من يمرض أو يفقد عمله."),
"v1138": ("Umverteilung über Steuern ist das Prinzip hinter dem Kindergeld.", "إعادة التوزيع عبر الضرائب هي المبدأ وراء إعانة الطفل."),
"v1139": ("Den Solidaritätszuschlag zahlen heute nur noch hohe Einkommen.", "ملحق التضامن لا تدفعه اليوم إلا الدخول العالية."),
"v1140": ("Die Grundsicherung deckt Miete, Heizung und den Regelsatz.", "الضمان الأساسي يغطي الإيجار والتدفئة والمعدل المعياري."),
"v1141": ("Das Bürgergeld wird vom Jobcenter monatlich überwiesen.", "بدل المواطن يحوّله مكتب العمل شهرياً."),
"v1143": ("Der Regelsatz für Alleinstehende wird jährlich angepasst.", "المعدل المعياري للعزّاب يُعدَّل سنوياً."),
"v1144": ("Zur Bedarfsgemeinschaft zählen Partner und Kinder im Haushalt.", "الوحدة المستحقة تشمل الشريك والأطفال في البيت."),
"v1145": ("Die Riester-Rente lohnt sich vor allem mit Kindern und Zulagen.", "معاش ريستر يستحق خصوصاً مع الأطفال والعلاوات."),
"v1146": ("Altersarmut trifft besonders Frauen mit langen Erziehungszeiten.", "فقر الشيخوخة يصيب خصوصاً النساء ذوات فترات التربية الطويلة."),
"v1147": ("Die Mütterrente rechnet Erziehungsjahre als Beitragszeiten an.", "معاش الأمهات يحتسب سنوات التربية كفترات اشتراك."),
"v1148": ("Die Erwerbsminderungsrente gibt es nur nach ärztlichem Gutachten.", "معاش العجز عن الكسب لا يُمنح إلا بعد تقرير طبي."),
"v1149": ("Wohngeld beantragt man bei der Stadt, nicht beim Jobcenter.", "بدل السكن يُطلب من المدينة لا من مكتب العمل."),
"v1150": ("Die Armutsgefährdungsquote liegt bei Alleinerziehenden am höchsten.", "مؤشر خطر الفقر أعلى ما يكون لدى الوالدين المنفردين."),
"v1151": ("Teilhabe bedeutet, sich das Vereinsleben leisten zu können.", "المشاركة في المجتمع تعني القدرة على تكلفة حياة النادي."),
"v1153": ("Ohne Ehrenamtliche würde die Tafel am Samstag geschlossen bleiben.", "بلا متطوعين لبقيت مائدة المتطوعين مغلقة يوم السبت."),
"v1154": ("Nach der Schule machte sie ein Jahr Freiwilligendienst im Altenheim.", "بعد المدرسة قضت سنة خدمة طوعية في دار المسنين."),
"v1155": ("Die Aufwandsentschädigung deckt Fahrtkosten, nicht die Arbeitszeit.", "تعويض النفقات يغطي تكاليف التنقل لا وقت العمل."),
"v1156": ("Die Übungsleiterpauschale bleibt bis zu einer Grenze steuerfrei.", "بدل قائد الفرق يبقى معفى من الضريبة حتى حدّ معيّن."),
"v1157": ("Bis zum Freibetrag zahlt man auf Nebeneinkünfte keine Steuer.", "حتى مبلغ الإعفاء لا تُدفع ضريبة على الدخل الجانبي."),
"v1158": ("Ohne Spendenquittung erkennt das Finanzamt die Spende nicht an.", "بلا إشعار تبرع لا تعترف مصلحة الضرائب بالتبرع."),
"v1159": ("Als Sachspende nimmt die Tafel nur haltbare Lebensmittel an.", "كتبرع عيني لا تقبل مائدة المتطوعين إلا الأغذية القابلة للحفظ."),
"v1161": ("Die Gemeinnützigkeit muss der Verein alle drei Jahre nachweisen.", "صفة النفع العام يجب أن تثبتها الجمعية كل ثلاث سنوات."),
"v1162": ("Der Wohlfahrtsverband betreibt Kitas, Pflegeheime und Beratungsstellen.", "المؤسسة الخيرية الكبرى تدير حضانات ودور رعاية ومراكز استشارة."),
"v1163": ("Die Ehrenamtsagentur vermittelt Freiwillige an Vereine im Stadtteil.", "مكتب التطوع يوجّه المتطوعين إلى جمعيات الحي."),
"v1164": ("Ihre Einsatzstelle im Freiwilligendienst war eine Bibliothek.", "موضع تكليفها في الخدمة الطوعية كان مكتبة."),
"v1165": ("In der Solidargemeinschaft zahlen Gesunde heute für Kranke von morgen.", "في جماعة التضامن يدفع الأصحاء اليوم لمرضى الغد."),
"v1166": ("Für die Pflegezeit kann man sich bis zu sechs Monate freistellen lassen.", "لإجازة الرعاية يمكن التفرّغ حتى ستة أشهر."),
"v1167": ("Das Kindergeld wird bis zum Ende der Ausbildung gezahlt.", "إعانة الطفل تُدفع حتى نهاية التكوين المهني."),
"v1168": ("Den Kinderzuschlag gibt es für Familien mit kleinem Einkommen.", "ملحق الطفل يُمنح للأسر ذات الدخل المحدود."),
"v1169": ("Mitbestimmung heißt, dass der Betriebsrat vor Kündigungen gehört wird.", "المشاركة في القرار تعني الاستماع لمجلس العمال قبل التسريح."),
"v1170": ("Die Versicherungspflicht gilt für alle Arbeitnehmer ab dem ersten Tag.", "إلزامية التأمين تسري على كل الأجراء من اليوم الأول."),
"v1171": ("Über der Beitragsbemessungsgrenze steigen die Beiträge nicht weiter.", "فوق سقف الاشتراك لا تزداد الاشتراكات."),
}
