# -*- coding: utf-8 -*-
"""exampleDe/exampleAr Batch 4: B2 Teil 2 (240)."""
B = {
"v573": ("Mit zwei Abschlüssen gilt sie für die Stelle als überqualifiziert.", "بشهادتين تُعتبر زائدة عن حاجة المنصب."),
"v574": ("Pflegekräfte sind unterbezahlt, darüber sind sich fast alle einig.", "العاملون في التمريض أجرهم أقل من العادل، وعلى ذلك يتفق الجميع تقريباً."),
"v575": ("Das Burnout kam nicht plötzlich, sondern nach Monaten ohne Pause.", "الاحتراق الوظيفي لم يأتِ فجأة بل بعد أشهر بلا استراحة."),
"v576": ("Die Vereinbarkeit von Familie und Beruf scheitert oft an den Kita-Zeiten.", "التوفيق بين العائلة والعمل يفشل غالباً بسبب أوقات الحضانة."),
"v577": ("Von Work-Life-Balance spricht die Firma viel, die Überstunden bleiben.", "الشركة تتكلم كثيراً عن التوازن بين العمل والحياة، والساعات الإضافية باقية."),
"v584": ("Die Gewerkschaft fordert acht Prozent mehr Lohn und kürzere Schichten.", "النقابة تطالب بزيادة ثمانية بالمائة في الأجر ومناوبات أقصر."),
"v585": ("Die Lokführer streiken seit Montag, die Züge fahren nicht.", "سائقو القطارات مضربون منذ الاثنين، والقطارات لا تسير."),
"v586": ("Der Streik wurde nach einer Woche ausgesetzt, weil verhandelt wird.", "الإضراب عُلّق بعد أسبوع لأن المفاوضات جارية."),
"v588": ("Eine Bewerbung nur nach dem Foto zu beurteilen, ist unfair.", "تقييم طلب توظيف بحسب الصورة وحدها أمر غير عادل."),
"v589": ("Drei Jahre Berufserfahrung wiegen hier mehr als der Notendurchschnitt.", "ثلاث سنوات خبرة مهنية تزن هنا أكثر من معدل الدرجات."),
"v590": ("Als Quereinsteiger aus der Gastronomie kam er in die Pflege.", "كداخل من تخصص آخر جاء من المطاعم إلى التمريض."),
"v591": ("Die Umschulung zum Fachinformatiker dauert zwei Jahre.", "إعادة التأهيل المهني كأخصائي معلوماتية تستغرق سنتين."),
"v594": ("Die Rente reicht knapp für Miete und Nebenkosten.", "معاش التقاعد يكفي بالكاد للإيجار والمصاريف."),
"v595": ("Im Ruhestand engagiert er sich ehrenamtlich in der Bibliothek.", "في التقاعد يتطوّع في المكتبة."),
"v596": ("Mein Vater geht nächstes Jahr in den Ruhestand, nach vierzig Jahren.", "أبي يتقاعد السنة القادمة بعد أربعين سنة."),
"v598": ("Die Luftqualität in der Innenstadt hat sich seit der Umweltzone verbessert.", "نقاء الهواء في وسط المدينة تحسّن منذ منطقة الانبعاث المقيّدة."),
"v599": ("Die Fabrik hat den Fluss jahrzehntelang verschmutzt.", "المصنع لوّث النهر عقوداً."),
"v603": ("Wiederverwendung ist besser als Recycling, weil Energie gespart wird.", "إعادة الاستعمال أفضل من التدوير لأنها توفّر الطاقة."),
"v604": ("Ein Einwegprodukt ist billig im Kauf und teuer für die Umwelt.", "المنتج أحادي الاستعمال رخيص في الشراء وغالٍ على البيئة."),
"v605": ("Der Plastikmüll im Meer stammt zum großen Teil vom Land.", "النفايات البلاستيكية في البحر مصدرها الأكبر اليابسة."),
"v612": ("Das Kraftwerk am Fluss liefert Strom für die halbe Region.", "محطة الطاقة على النهر توفّر الكهرباء لنصف المنطقة."),
"v613": ("Erneuerbare Energien decken inzwischen einen großen Teil des Bedarfs.", "الطاقات المتجددة تغطي الآن جزءاً كبيراً من الاحتياج."),
"v614": ("Auf dem Dach der Schule liefert Solarenergie den Strom für die Küche.", "على سطح المدرسة توفّر طاقة الشمس الكهرباء للمطبخ."),
"v615": ("Das Windrad am Ortsrand ist nachts kaum zu hören.", "عنفة الرياح على حافة القرية لا تكاد تُسمع ليلاً."),
"v616": ("Gegen den neuen Windpark protestieren einige Anwohner.", "ضد مزرعة الرياح الجديدة يحتج بعض السكان."),
"v617": ("Fossile Energie ist kurzfristig billig und langfristig teuer.", "الطاقة الأحفورية رخيصة قصير المدى وغالية طويل المدى."),
"v621": ("Der Ausstoß der Fabrik wird jedes Quartal gemessen.", "كمية انبعاثات المصنع تُقاس كل ربع سنة."),
"v622": ("Ältere Busse stoßen deutlich mehr Feinstaub aus.", "الحافلات القديمة تُصدر جسيمات دقيقة أكثر بكثير."),
"v623": ("Die Emission pro Kopf ist in der Stadt niedriger als auf dem Land.", "الانبعاث للفرد في المدينة أقل منه في الريف."),
"v624": ("Feinstaub entsteht nicht nur im Auspuff, sondern auch durch Bremsen.", "الجسيمات الدقيقة لا تنشأ من العادم فقط بل من الفرامل أيضاً."),
"v625": ("Umweltbewusstsein zeigt sich beim Einkauf, nicht in Umfragen.", "الوعي البيئي يظهر عند الشراء لا في الاستطلاعات."),
"v626": ("Der Zug ist die umweltschonendste Art, nach München zu reisen.", "القطار أكثر وسيلة مجانبة للضرر البيئي للسفر إلى ميونيخ."),
"v628": ("Zu viel Salz auf den Straßen schädigt die Bäume am Rand.", "الملح الزائد على الطرق يُلحق ضرراً بالأشجار على الحافة."),
"v629": ("Der Bau der Straße würde das Biotop am See gefährden.", "بناء الشارع سيُعرّض الموطن البيئي قرب البحيرة للخطر."),
"v630": ("Naturschutz und Windkraft geraten hier in Konflikt.", "حماية الطبيعة وطاقة الرياح تتصادمان هنا."),
"v631": ("Im Schutzgebiet dürfen keine neuen Häuser gebaut werden.", "في المنطقة المحمية لا يجوز بناء منازل جديدة."),
"v633": ("Ohne Schutz würde diese Vogelart in der Region aussterben.", "بلا حماية سينقرض هذا النوع من الطيور في المنطقة."),
"v634": ("Das Aussterben einer Art fällt oft erst auf, wenn es zu spät ist.", "انقراض نوع ما لا يُلاحَظ غالباً إلا بعد فوات الأوان."),
"v635": ("Die Biodiversität im Garten steigt, wenn man weniger mäht.", "التنوع الحيوي في الحديقة يزداد حين يقلّ القصّ."),
"v636": ("Das Biotop am Bahndamm wurde von Freiwilligen angelegt.", "الموطن البيئي على جانب السكة أنشأه متطوعون."),
"v637": ("Das Grundwasser ist in trockenen Sommern deutlich gesunken.", "المياه الجوفية انخفضت بوضوح في الصيوف الجافة."),
"v638": ("Beim Hochwasser stand das Wasser einen Meter hoch im Keller.", "في الفيضان بلغ الماء متراً في القبو."),
"v640": ("Die Dürre hat die Ernte der Bauern halbiert.", "الجفاف قلّص محصول المزارعين إلى النصف."),
"v641": ("Während der Hitzewelle öffnete die Stadt kühle Räume für Ältere.", "أثناء موجة الحر فتحت المدينة غرفاً باردة للمسنّين."),
"v642": ("Steigt der Meeresspiegel weiter, sind Küstenstädte zuerst betroffen.", "إذا استمر ارتفاع منسوب البحر فالمدن الساحلية أول المتضررين."),
"v643": ("Der Gletscher hat in zwanzig Jahren die Hälfte seiner Länge verloren.", "النهر الجليدي فقد نصف طوله في عشرين سنة."),
"v644": ("Das Gletscherschmelzen verändert die Flüsse im Tal.", "ذوبان الأنهار الجليدية يغيّر أنهار الوادي."),
"v645": ("Der Regenwald speichert Kohlenstoff, solange er steht.", "الغابة المطيرة تخزّن الكربون ما دامت قائمة."),
"v646": ("Für die Plantage wurden hunderte Hektar Wald abgeholzt.", "من أجل المزرعة اجتُثّت مئات الهكتارات من الغابة."),
"v647": ("Die Abholzung lässt sich aus dem Satellitenbild ablesen.", "القطع الجائر للغابات يمكن قراءته من صورة القمر الصناعي."),
"v648": ("Methan ist ein Treibhausgas, das stärker wirkt als CO₂.", "الميثان غاز دفيئة أقوى أثراً من ثاني أكسيد الكربون."),
"v649": ("Der Treibhauseffekt an sich ist natürlich, das Problem ist seine Verstärkung.", "ظاهرة الاحتباس الحراري طبيعية بحد ذاتها، والمشكلة في تعزيزها."),
"v650": ("Das Klimaziel für 2030 ist ohne weniger Verkehr kaum zu erreichen.", "هدف المناخ لعام 2030 يصعب تحقيقه بلا تقليل حركة المرور."),
"v651": ("Das Abkommen wurde unterschrieben, die Umsetzung fehlt noch.", "الاتفاق وُقّع، والتنفيذ ما زال ناقصاً."),
"v652": ("Auf die Flasche gibt es 25 Cent Pfand, die man zurückbekommt.", "على الزجاجة 25 سنتاً عربوناً يُسترد."),
"v653": ("Ein Mehrwegsystem spart Verpackung, braucht aber Rückgabestellen.", "نظام إعادة استعمال العبوات يوفّر التغليف لكنه يحتاج نقاط إرجاع."),
"v654": ("Die Mülltrennung funktioniert nur, wenn alle im Haus mitmachen.", "فرز النفايات لا ينجح إلا بمشاركة كل سكان البناية."),
"v656": ("Die Klimabewegung hat das Thema in die Nachrichten gebracht.", "الحركة الشعبية للمناخ أدخلت الموضوع إلى الأخبار."),
"v658": ("Die Zahlung erfolgt bar, sobald Sie unten unterschrieben haben.", "الدفع يتم نقداً بمجرد توقيعك في الأسفل."),
"v659": ("Bitte überweisen Sie die Kaution auf das Sonderkonto.", "من فضلك حوّل الضمانة إلى الحساب الخاص."),
"v660": ("Die Überweisung dauert innerhalb Europas einen Werktag.", "التحويل البنكي داخل أوروبا يستغرق يوم عمل."),
"v664": ("Studierende bekommen eine Ermäßigung von fünfzig Prozent.", "الطلبة يحصلون على تخفيض خمسين بالمائة."),
"v665": ("Auch Einnahmen aus Nebenjobs muss man versteuern.", "حتى دخل الأعمال الجانبية يخضع للضريبة."),
"v666": ("Die Mehrwertsteuer auf Lebensmittel ist niedriger als auf Kleidung.", "ضريبة القيمة المضافة على الغذاء أقل منها على الملابس."),
"v672": ("Das Guthaben auf der Karte reicht noch für drei Fahrten.", "الرصيد على البطاقة يكفي لثلاث رحلات."),
"v673": ("Den Kontostand prüfe ich jeden Freitag in der App.", "رصيد الحساب أتحقق منه كل جمعة في التطبيق."),
"v674": ("Am Monatsende rutscht das Konto oft ins Minus.", "في نهاية الشهر يُسحب من الحساب أكثر مما فيه غالباً."),
"v676": ("Nach dem Studium war er mit zehntausend Euro verschuldet.", "بعد الدراسة كان مثقلاً بديون عشرة آلاف يورو."),
"v677": ("Die Verschuldung junger Haushalte hat zugenommen.", "مديونية الأسر الشابة ازدادت."),
"v681": ("Die Kundschaft des Ladens ist älter geworden, das Sortiment auch.", "زبائن المتجر تقدّموا في السن، والتشكيلة أيضاً."),
"v684": ("Der Mantel war ein Schnäppchen: siebzig Prozent reduziert.", "المعطف كان صفقة رابحة: مخفّض سبعين بالمائة."),
"v686": ("Bei Kleidung zählt für mich Qualität mehr als Quantität.", "في الملابس تهمّني الجودة أكثر من الكمية."),
"v688": ("Die Ware war minderwertig, die Nähte lösten sich nach einer Woche.", "البضاعة كانت رديئة الصنع، وانفكّت الخياطة بعد أسبوع."),
"v689": ("Ein hochwertiger Rucksack hält zehn Jahre, ein billiger zwei.", "حقيبة الظهر عالية الجودة تدوم عشر سنوات، والرخيصة سنتين."),
"v691": ("Das Plakat für das Konzert hängt an jeder Haltestelle.", "ملصق الحفل معلّق في كل موقف."),
"v692": ("Die Anschaffung einer Waschmaschine lohnt sich nach zwei Jahren.", "اقتناء غسالة يصبح مجدياً بعد سنتين."),
"v693": ("Eine Wohnung im Zentrum können wir uns nicht mehr leisten.", "شقة في المركز لم نعد نقدر على تكلفتها."),
"v695": ("Im Haushaltsplan stehen Miete, Strom und zweihundert Euro Reserve.", "في ميزانية البيت: الإيجار والكهرباء ومئتا يورو احتياط."),
"v696": ("Ohne Kassenbon ist ein Umtausch nur aus Kulanz möglich.", "بلا وصل الصندوق لا يكون الاستبدال ممكناً إلا تفضّلاً."),
"v697": ("Für die Steuer brauche ich eine Quittung mit Firmenstempel.", "للضريبة أحتاج إيصالاً مختوماً بختم الشركة."),
"v698": ("Der Umtausch ist innerhalb von vierzehn Tagen möglich.", "الاستبدال ممكن خلال أربعة عشر يوماً."),
"v699": ("Kann ich den Pullover gegen Größe M umtauschen?", "هل يمكنني استبدال البلوفر بمقاس M؟"),
"v701": ("Die Gewährleistung gilt zwei Jahre, unabhängig von der Garantie.", "الضمان القانوني يسري سنتين بغض النظر عن ضمان البائع."),
"v702": ("Den defekten Wasserkocher habe ich sofort reklamiert.", "الغلاية المعطوبة قدّمت شكوى بها فوراً."),
"v703": ("Die Reklamation wurde anerkannt, das Geld kam nach einer Woche.", "الشكوى قُبلت، والمال وصل بعد أسبوع."),
"v704": ("Das Rückgaberecht bei Onlinekäufen beträgt vierzehn Tage.", "حق الإرجاع في المشتريات الإلكترونية أربعة عشر يوماً."),
"v707": ("Im Schlussverkauf sind die Größen schnell weg.", "في التخفيضات الأخيرة تنفد المقاسات بسرعة."),
"v710": ("Am Geldautomaten am Hauptbahnhof habe ich die Karte zuletzt benutzt.", "في الصرّاف الآلي بالمحطة الرئيسية استعملت البطاقة آخر مرة."),
"v711": ("Die Rate für das Auto beträgt zweihundert Euro im Monat.", "قسط السيارة مئتا يورو شهرياً."),
"v712": ("Bei hoher Inflation verliert das Sparbuch jedes Jahr an Wert.", "مع التضخم المرتفع يفقد دفتر التوفير قيمته كل سنة."),
"v713": ("Die Teuerung trifft vor allem Haushalte mit kleinem Einkommen.", "الغلاء يصيب خصوصاً الأسر ذات الدخل المحدود."),
"v714": ("Die Firma war zahlungsunfähig, die Löhne kamen zu spät.", "الشركة كانت معسرة عن السداد، والأجور تأخّرت."),
"v715": ("Nach der Insolvenz wurden dreißig Mitarbeiter entlassen.", "بعد الإفلاس سُرّح ثلاثون موظفاً."),
"v718": ("In der Stadt bewege ich mich fast nur mit dem Rad fort.", "في المدينة أتنقّل بالدراجة تقريباً فقط."),
"v720": ("Das Elektroauto lädt über Nacht an der Wallbox in der Garage.", "السيارة الكهربائية تُشحن ليلاً على الشاحن الجداري في المرآب."),
"v721": ("Elektromobilität braucht mehr Ladestationen als Werbung.", "التنقل الكهربائي يحتاج محطات شحن أكثر من الإعلانات."),
"v722": ("Die nächste Ladestation ist am Parkhaus, zehn Minuten entfernt.", "أقرب محطة شحن عند موقف السيارات البرجي، على بعد عشر دقائق."),
"v724": ("Bei fünfzig Minuten Verspätung hat der Fahrgast Anspruch auf Erstattung.", "عند تأخير خمسين دقيقة يحق للراكب استرداد جزء من الثمن."),
"v726": ("Vergiss nicht, das Ticket vor der Fahrt zu entwerten.", "لا تنسَ ختم التذكرة قبل الرحلة."),
"v729": ("Der Anschluss in Frankfurt fiel aus, der nächste Zug galt ohne Aufpreis.", "رحلة الربط في فرانكفورت أُلغيت، والقطار التالي صار سارياً بلا زيادة."),
"v730": ("Der Zug nach Köln fährt heute von Gleis fünf, nicht von Gleis drei.", "قطار كولن ينطلق اليوم من الرصيف خمسة لا ثلاثة."),
"v732": ("Wegen der Straßensperrung fährt der Bus eine Umleitung.", "بسبب إغلاق الشارع تسلك الحافلة تحويلة."),
"v739": ("Mit dem Lastenrad bringt sie beide Kinder zur Kita.", "بدراجة الحمل توصل طفليها إلى الحضانة."),
"v740": ("Über die App fand ich eine Mitfahrgelegenheit nach Hamburg für fünfzehn Euro.", "عبر التطبيق وجدت فرصة مشاركة رحلة إلى هامبورغ بخمسة عشر يورو."),
"v741": ("Die Fahrgemeinschaft spart jedem von uns hundert Euro im Monat.", "مجموعة تقاسم السيارة توفّر لكل واحد منا مائة يورو شهرياً."),
"v742": ("Als Pendlerin verbringt sie täglich zwei Stunden im Zug.", "كمتنقّلة يومياً تقضي ساعتين في القطار كل يوم."),
"v743": ("Seit dem Umzug pendelt er vierzig Kilometer zur Arbeit.", "منذ الانتقال يتنقّل يومياً أربعين كيلومتراً إلى العمل."),
"v744": ("Das Pendeln kostet Zeit, die abends in der Familie fehlt.", "التنقل اليومي يكلّف وقتاً ينقص العائلة مساءً."),
"v746": ("Die Mobilitätswende beginnt beim Fahrplan, nicht beim Autokauf.", "التحول في أنماط التنقل يبدأ من جدول المواعيد لا من شراء السيارة."),
"v747": ("Ohne bessere Busse auf dem Land bleibt die Verkehrswende ein Stadtprojekt.", "بلا حافلات أفضل في الريف يبقى تحوّل النقل مشروعاً حضرياً."),
"v748": ("In der Umweltzone dürfen nur Autos mit grüner Plakette fahren.", "في منطقة الانبعاث المقيّدة لا تسير إلا السيارات ذات الملصق الأخضر."),
"v749": ("Die Geschwindigkeitsbegrenzung vor der Schule gilt nur tagsüber.", "تحديد السرعة أمام المدرسة يسري نهاراً فقط."),
"v750": ("Das Tempolimit hat die Unfälle auf dem Ring um ein Drittel gesenkt.", "حد السرعة خفّض الحوادث على الطريق الدائري بمقدار الثلث."),
"v751": ("Die Höchstgeschwindigkeit auf dieser Strecke beträgt achtzig.", "أقصى سرعة مسموحة على هذا المقطع ثمانون."),
"v754": ("An der Kreuzung hat der Bus Vorfahrt, nicht das Auto.", "عند التقاطع الأولوية للحافلة لا للسيارة."),
"v755": ("Das Parkhaus am Bahnhof kostet zwei Euro pro Stunde.", "موقف السيارات البرجي عند المحطة بيورهين للساعة."),
"v756": ("Vor der Einfahrt gilt absolutes Parkverbot.", "أمام المدخل يُمنع الوقوف منعاً مطلقاً."),
"v757": ("Der Strafzettel lag unter dem Scheibenwischer: zwanzig Euro.", "ورقة المخالفة كانت تحت المسّاحة: عشرون يورو."),
"v758": ("Wer bei Rot fährt, zahlt ein Bußgeld und bekommt einen Punkt.", "من يقطع الإشارة الحمراء يدفع غرامة ويحصل على نقطة."),
"v759": ("Nach dem zweiten Verstoß drohte ihm ein Fahrverbot von einem Monat.", "بعد المخالفة الثانية هدّده سحب الرخصة شهراً."),
"v761": ("Die Fahrschule verlangt den Erste-Hilfe-Kurs vor der Theorieprüfung.", "مدرسة السياقة تشترط دورة الإسعاف قبل امتحان النظري."),
"v762": ("Der Fernbus ist langsamer als der Zug, aber halb so teuer.", "حافلة المسافات الطويلة أبطأ من القطار لكنها بنصف الثمن."),
"v763": ("Mit dem Nachtzug kommt man morgens ausgeschlafen an.", "بقطار النوم الليلي تصل صباحاً وقد نمت جيداً."),
"v765": ("Die Fluggesellschaft muss bei Annullierung den Preis erstatten.", "شركة الطيران ملزمة برد الثمن عند الإلغاء."),
"v767": ("Ins Handgepäck passen nur Flüssigkeiten bis hundert Milliliter.", "في أمتعة الكابينة لا تدخل إلا سوائل حتى مائة مليلتر."),
"v768": ("Die Anreise erfolgt am besten mit dem Zug bis zum Hauptbahnhof.", "الوصول يكون أفضل بالقطار حتى المحطة الرئيسية."),
"v769": ("Am Tag der Abreise muss das Zimmer bis elf Uhr frei sein.", "يوم المغادرة يجب إخلاء الغرفة حتى الحادية عشرة."),
"v770": ("Nach der Rückkehr aus Tunis brauchte ich zwei Tage, um anzukommen.", "بعد العودة من تونس احتجت يومين لأستعيد إيقاعي."),
"v772": ("Die Kündigungsfrist ist gesetzlich geregelt, nicht verhandelbar.", "مهلة الفسخ منصوص عليها قانوناً وليست قابلة للتفاوض."),
"v773": ("Die Rechtslage ist eindeutig: Der Vermieter muss die Kaution verzinsen.", "الوضع القانوني واضح: على المؤجّر دفع فوائد على الضمانة."),
"v774": ("Die Verfassung garantiert die Freiheit der Meinung und der Presse.", "الدستور يضمن حرية الرأي والصحافة."),
"v775": ("Artikel eins des Grundgesetzes schützt die Würde des Menschen.", "المادة الأولى من القانون الأساسي تحمي كرامة الإنسان."),
"v776": ("Gleichheit vor dem Gesetz ist ein Grundwert, kein Detail.", "المساواة أمام القانون قيمة تأسيسية لا تفصيل."),
"v777": ("Der Paragraph regelt, wann der Vermieter die Wohnung betreten darf.", "المادة تنظّم متى يجوز للمؤجّر دخول الشقة."),
"v778": ("Laut Vorschrift muss der Rauchmelder jährlich geprüft werden.", "حسب النص الملزم يجب فحص كاشف الدخان سنوياً."),
"v779": ("Das Gesetz schreibt vor, dass die Nebenkosten jährlich abgerechnet werden.", "القانون يُملي أن تُحاسَب المصاريف الجانبية سنوياً."),
"v782": ("Die Verwaltung arbeitet noch mit Papier, deshalb dauert alles länger.", "جهاز الإدارة ما زال يعمل بالورق، لذلك يطول كل شيء."),
"v785": ("Der Antrag auf Wohngeld wurde nach sechs Wochen bewilligt.", "طلب إعانة السكن ووفق عليه بعد ستة أسابيع."),
"v786": ("Ohne Bewilligung darf der Kurs nicht beginnen.", "بلا موافقة رسمية لا يجوز أن تبدأ الدورة."),
"v787": ("Für den Balkonanbau braucht man eine Genehmigung der Stadt.", "لبناء الشرفة يحتاج المرء ترخيصاً من المدينة."),
"v788": ("Die Stadt hat den Umbau genehmigt, mit Auflagen zum Lärmschutz.", "المدينة رخّصت التجديد بشروط للحماية من الضجيج."),
"v790": ("Das Verbot gilt nur für Musik nach zweiundzwanzig Uhr.", "المنع يسري فقط على الموسيقى بعد العاشرة مساءً."),
"v791": ("Ohne schriftliche Erlaubnis darf man keine Haustiere halten.", "بلا إذن كتابي لا يجوز اقتناء حيوانات أليفة."),
"v792": ("Die Behörde kann den Antrag ablehnen, muss es aber begründen.", "يمكن للإدارة رفض الطلب لكن عليها التعليل."),
"v793": ("Gegen die Ablehnung kann man innerhalb eines Monats Widerspruch einlegen.", "ضد الرفض يمكن تقديم اعتراض خلال شهر."),
"v794": ("Der Bescheid kam per Post, mit Datum und Rechtsbehelfsbelehrung.", "الإشعار الرسمي وصل بالبريد، بالتاريخ وبيان طرق الطعن."),
"v795": ("Der Widerspruch muss schriftlich und fristgerecht eingehen.", "الاعتراض يجب أن يصل كتابياً وفي المهلة."),
"v796": ("Sie will dem Bescheid widersprechen und Belege beilegen.", "تريد الاعتراض على الإشعار وإرفاق الوثائق."),
"v797": ("Vor der Klage muss ein Schlichtungsversuch stehen.", "قبل الدعوى يجب أن تسبق محاولة صلح."),
"v798": ("Wer klagen will, sollte vorher die Kosten kennen.", "من يريد رفع دعوى عليه معرفة التكاليف مسبقاً."),
"v801": ("Die Richterin schlug einen Vergleich mit Frist vor.", "القاضية اقترحت تسوية بمهلة."),
"v803": ("Das Verfahren dauerte acht Monate und endete mit einem Vergleich.", "سير المحاكمة استغرق ثمانية أشهر وانتهى بتسوية."),
"v805": ("Die Anwältin riet, zuerst schriftlich Widerspruch einzulegen.", "المحامية نصحت بتقديم اعتراض كتابي أولاً."),
"v806": ("Eine erste Rechtsberatung beim Mieterverein kostet nur den Jahresbeitrag.", "أول استشارة قانونية في جمعية المستأجرين تكلّف اشتراك السنة فقط."),
"v807": ("Bei zweitem Versäumnis fällt eine neue Gebühr an.", "عند التخلّف الثاني تُفرض رسوم جديدة."),
"v808": ("Die Justiz braucht mehr Personal, sonst dauern Verfahren Jahre.", "القضاء يحتاج موظفين أكثر وإلا استغرقت القضايا سنوات."),
"v810": ("Pressefreiheit heißt auch, unbequeme Fragen stellen zu dürfen.", "حرية الصحافة تعني أيضاً الحق في طرح أسئلة محرجة."),
"v811": ("Das Wahlrecht ab sechzehn wird in einigen Ländern diskutiert.", "حق الاقتراع من سن السادسة عشرة يُناقش في بعض الولايات."),
"v812": ("Der Bundestag hat das Gesetz in zweiter Lesung beraten.", "مجلس النواب ناقش القانون في القراءة الثانية."),
"v813": ("Der Bundesrat muss zustimmen, wenn die Länder betroffen sind.", "مجلس الولايات يجب أن يوافق إذا كانت الولايات معنية."),
"v814": ("Bildung ist föderal geregelt, jedes Land hat eigene Lehrpläne.", "التعليم منظّم اتحادياً، ولكل ولاية مناهجها."),
"v815": ("Für die Staatsbürgerschaft braucht man B1 und einen Einbürgerungstest.", "للجنسية يحتاج المرء B1 واختبار تجنيس."),
"v816": ("Die Einbürgerung dauerte bei ihr fast zwei Jahre.", "منح الجنسية استغرق عندها سنتين تقريباً."),
"v817": ("Letztes Jahr wurden in der Stadt achthundert Menschen eingebürgert.", "السنة الماضية جُنّس في المدينة ثمانمائة شخص."),
"v818": ("Der Aufenthalt wurde um zwei Jahre verlängert.", "الإقامة مُدّدت سنتين."),
"v819": ("Niemanden darf man abschieben, ohne dass ein Gericht entscheidet.", "لا يجوز إبعاد أحد دون أن تقرر محكمة."),
"v820": ("Die Abschiebung wurde vom Gericht vorläufig gestoppt.", "قرار الإبعاد أوقفته المحكمة مؤقتاً."),
"v821": ("Der Antrag auf Asyl wird in einem persönlichen Gespräch geprüft.", "طلب اللجوء يُفحص في مقابلة شخصية."),
"v823": ("Die Haft dauerte zwei Wochen, dann kam er auf Kaution frei.", "الاحتجاز دام أسبوعين ثم أُفرج عنه بكفالة."),
"v824": ("Der Verdächtige ist seit gestern inhaftiert.", "المشتبه به محتجز منذ أمس."),
"v825": ("Schon der Versuch ist eine Straftat.", "مجرد المحاولة فعل مؤثَّم."),
"v826": ("Das Verbrechen wurde nach zwei Tagen aufgeklärt.", "الجريمة كُشفت بعد يومين."),
"v828": ("Ohne Vorstrafe fällt die Strafe milder aus.", "بلا سوابق تكون العقوبة أخف."),
"v829": ("Statt Haft gab es eine Geldstrafe von sechzig Tagessätzen.", "بدل السجن كانت هناك غرامة بستين يوماً من الدخل."),
"v830": ("Korruption beginnt oft mit kleinen Gefälligkeiten.", "الفساد يبدأ غالباً بخدمات صغيرة."),
"v831": ("Er versuchte, den Prüfer mit Geld zu bestechen.", "حاول رشوة المفتّش بالمال."),
"v832": ("Bestechung im Amt wird mit Haft bestraft.", "الرشوة في المنصب يُعاقب عليها بالسجن."),
"v833": ("Die Fälschung des Zeugnisses flog beim Vergleich mit dem Original auf.", "تزوير الشهادة انكشف عند المقارنة بالأصل."),
"v834": ("Wer Unterlagen fälscht, verliert den Anspruch sofort.", "من يزوّر الوثائق يفقد الحق فوراً."),
"v835": ("Die Bescheinigung der Uni reicht als Nachweis für den Termin.", "شهادة الجامعة تكفي كإثبات للموعد."),
"v836": ("Der Arzt bescheinigt die Arbeitsunfähigkeit für drei Tage.", "الطبيب يشهد بعدم القدرة على العمل ثلاثة أيام."),
"v837": ("Als Nachweis genügt eine Kopie der Fahrkarte.", "كدليل إثبات تكفي نسخة من التذكرة."),
"v838": ("Sie muss nachweisen, dass sie zwölf Monate Praxis hat.", "عليها إثبات أن لديها اثني عشر شهراً من الممارسة."),
"v839": ("Kopien von Zeugnissen muss man beglaubigen lassen.", "نسخ الشهادات يجب تصديقها رسمياً."),
"v840": ("Die Beglaubigung kostet fünf Euro pro Seite im Rathaus.", "التصديق يكلّف خمسة يورو للصفحة في البلدية."),
"v841": ("Das Verfassungsgericht hat das Gesetz teilweise gekippt.", "المحكمة الدستورية أبطلت القانون جزئياً."),
"v1409": ("Der Staat finanziert die Sprachkurse zum großen Teil.", "الدولة تموّل دورات اللغة في معظمها."),
"v1410": ("Das Militär half nach dem Hochwasser beim Aufräumen.", "الجيش ساعد في التنظيف بعد الفيضان."),
"v842": ("Der Studiengang kombiniert Informatik mit Wirtschaft.", "التخصص الجامعي يجمع الإعلامية مع الاقتصاد."),
"v843": ("Ein Studienplatz in Medizin ist zehnmal so begehrt wie einer in Chemie.", "مقعد القبول في الطب مطلوب عشرة أضعاف مقعد الكيمياء."),
"v844": ("Die Zulassung kam per Post, zwei Wochen vor Semesterbeginn.", "قرار القبول وصل بالبريد قبل بدء الفصل بأسبوعين."),
"v845": ("Die Uni will nur Bewerber mit B2-Zertifikat zulassen.", "الجامعة لا تريد قبول إلا المتقدمين بشهادة B2."),
"v846": ("Wegen des Numerus clausus wartet sie ein Jahr auf den Platz.", "بسبب حد القبول تنتظر سنة على المقعد."),
"v848": ("Der Hörsaal war so voll, dass Studierende auf den Stufen saßen.", "قاعة المحاضرات كانت ممتلئة حتى جلس الطلبة على الدرج."),
"v851": ("Die Hausarbeit hat fünfzehn Seiten und ist bis März abzugeben.", "البحث المكتوب خمس عشرة صفحة ويُسلَّم حتى مارس."),
"v852": ("Ohne den Schein aus dem Seminar kann man sich nicht zur Prüfung anmelden.", "بلا شهادة اجتياز الحلقة لا يمكن التسجيل للامتحان."),
"v853": ("Der Leistungsnachweis besteht aus Referat und Klausur.", "دليل الإنجاز يتكوّن من عرض واختبار."),
"v854": ("Die Dozentin benotet die Arbeit nach Struktur, Quellen und Sprache.", "المحاضِرة تمنح العلامة حسب البنية والمصادر واللغة."),
"v856": ("Wer durchfallen sollte, darf die Prüfung noch zweimal wiederholen.", "من قد يرسب يمكنه إعادة الامتحان مرتين أخريين."),
"v857": ("Von der Prüfung kann man mit Attest bis zum Vortag zurücktreten.", "يمكن الانسحاب من الامتحان بشهادة طبية حتى اليوم السابق."),
"v858": ("Die Rückmeldung fürs nächste Semester läuft bis Ende Juli.", "تجديد التسجيل للفصل القادم مستمر حتى نهاية يوليو."),
"v859": ("Die Einschreibung ist nur persönlich mit Pass möglich.", "القيد في السجل ممكن شخصياً فقط مع جواز السفر."),
"v860": ("Sie schreibt sich für Informatik ein, im Wintersemester.", "تسجّل في الإعلامية في الفصل الشتوي."),
"v861": ("Die Studienberatung half beim Umbau des Stundenplans.", "الإرشاد الأكاديمي ساعد في إعادة ترتيب الجدول."),
"v864": ("Man darf bis zu zehn Bücher gleichzeitig ausleihen.", "يمكن استعارة حتى عشرة كتب في الوقت نفسه."),
"v865": ("Die Leihfrist lässt sich online zweimal verlängern.", "مدة الإعارة يمكن تمديدها مرتين عبر الإنترنت."),
"v866": ("Nach der zweiten Mahnung kostet jeder Tag fünfzig Cent.", "بعد الإنذار الثاني يكلّف كل يوم خمسين سنتاً."),
"v867": ("Gutes Zeitmanagement heißt: zuerst das Schwierige, dann die Mails.", "ضبط الوقت الجيد يعني: الصعب أولاً ثم الإيميلات."),
"v868": ("Der Lernplan sieht täglich zwanzig Minuten Wortschatz vor.", "خطة المراجعة تنص على عشرين دقيقة مفردات يومياً."),
"v869": ("Meine beste Lernmethode ist, die Wörter laut zu lesen.", "أفضل أسلوب تحصيل عندي هو قراءة الكلمات بصوت عالٍ."),
"v870": ("Ohne Wiederholung nach drei Tagen ist das meiste wieder weg.", "بلا إعادة بعد ثلاثة أيام يضيع معظم ما حُفظ."),
"v871": ("Eine Eselsbrücke für „der, die, das“: Männer, Frauen, Kinder.", "حيلة ذهنية لـ«der, die, das»: رجال، نساء، أطفال."),
"v872": ("Im Karteikasten wandern gewusste Karten ein Fach weiter.", "في صندوق البطاقات تنتقل البطاقات المحفوظة خانة إلى الأمام."),
"v873": ("Auf jeder Karteikarte steht vorn das Wort und hinten ein Beispiel.", "على كل بطاقة الكلمة في الأمام ومثال في الخلف."),
"v874": ("Nach vierzig Minuten lässt die Konzentration deutlich nach.", "بعد أربعين دقيقة يتراجع حضور الذهن بوضوح."),
"v875": ("Das Handy auf dem Tisch lenkt ab, auch wenn es stumm ist.", "الهاتف على الطاولة يشتّت حتى وهو صامت."),
"v876": ("Die größte Ablenkung beim Lernen ist der Blick auf Nachrichten.", "أكبر مشتِّت أثناء الدراسة هو النظر إلى الأخبار."),
"v877": ("Jede Unterbrechung kostet zehn Minuten, bis man wieder drin ist.", "كل قطع يكلّف عشر دقائق حتى تعود إلى التركيز."),
"v878": ("Bitte unterbrechen Sie mich nicht, ich bin gleich fertig.", "من فضلك لا تقاطعني، سأنتهي حالاً."),
"v879": ("Die Störung im Netz dauerte den ganzen Vormittag.", "العطل في الشبكة دام طوال الصباح."),
"v880": ("Kurze Einheiten sind effizienter als ein langer Abend.", "الوحدات القصيرة أجدى من مساء طويل."),
"v881": ("Die Effizienz steigt, wenn man Ähnliches zusammen erledigt.", "الجدوى تزداد حين تُنجز الأعمال المتشابهة معاً."),
"v882": ("Der Lernerfolg zeigt sich erst im Gespräch, nicht im Test.", "ثمرة التعلّم تظهر في الحديث لا في الاختبار."),
"v883": ("Im Lerntagebuch notiere ich, was ich noch nicht kann.", "في دفتر المتابعة أدوّن ما لا أتقنه بعد."),
"v884": ("Der Selbsttest vor der Prüfung zeigt die letzten Lücken.", "امتحان النفس قبل الامتحان يكشف الثغرات الأخيرة."),
"v885": ("Ich überprüfe mich jeden Sonntag mit den Karten der Woche.", "أختبر نفسي كل أحد ببطاقات الأسبوع."),
"v888": ("Die Betonung liegt bei „Kaffee“ auf der zweiten Silbe.", "التوكيد في «Kaffee» على المقطع الثاني."),
"v889": ("Man betont „umfahren“ je nach Bedeutung anders.", "يُوكَّد «umfahren» بشكل مختلف حسب المعنى."),
"v890": ("Die Rechtschreibung von „dass“ und „das“ verwechseln viele.", "إملاء «dass» و«das» يخلط بينهما كثيرون."),
"v891": ("Ich habe mich vertippt, es sollte „Frist“ heißen.", "أخطأت على لوحة المفاتيح، كان المقصود «Frist»."),
"v892": ("Ein Tippfehler in der E-Mail-Adresse, und die Bestätigung kam nie an.", "خطأ مطبعي في عنوان الإيميل، ولم يصل التأكيد أبداً."),
"v893": ("Das war ein Flüchtigkeitsfehler, die Regel kenne ich.", "كان خطأ سهو، فأنا أعرف القاعدة."),
"v894": ("Der Dozent stellt die Folien vor der Vorlesung online.", "المحاضر ينشر الشرائح على الإنترنت قبل المحاضرة."),
"v895": ("Die Dozentin erwartet die Hausarbeit bis Ende März.", "المحاضِرة تنتظر البحث المكتوب حتى نهاية مارس."),
"v897": ("Die Fakultät für Informatik ist in einem neuen Gebäude.", "كلية الإعلامية في مبنى جديد."),
"v899": ("Die Exkursion führt ins Labor eines Windparks.", "الرحلة الدراسية تذهب إلى مختبر مزرعة رياح."),
"v900": ("Für die Abschlussarbeit hat sie sechs Monate Zeit.", "لرسالة التخرج لديها ستة أشهر."),
"v901": ("Der Professor betreut nur fünf Arbeiten pro Semester.", "الأستاذ يشرف على خمس رسائل فقط في الفصل."),
"v902": ("Mein Betreuer antwortet auf Mails meist innerhalb eines Tages.", "مشرفي يجيب على الإيميلات خلال يوم غالباً."),
"v903": ("Die Sprechstunde ist dienstags von zehn bis zwölf.", "موعد المكتب يوم الثلاثاء من العاشرة إلى الثانية عشرة."),
}
