# -*- coding: utf-8 -*-
"""exampleDe/exampleAr Batch 3: B2 Teil 1 (235)."""
B = {
"v121": ("Der Kommentar auf Seite zwei vertritt eine klare Meinung, der Bericht daneben nicht.", "التعليق في الصفحة الثانية يتبنّى رأياً واضحاً، بخلاف الخبر المجاور."),
"v122": ("Die Schlagzeile verspricht einen Skandal, den der Text nicht belegt.", "العنوان الرئيسي يعد بفضيحة لا يُثبتها النص."),
"v123": ("Ohne eine zweite Quelle darf die Redaktion die Zahl nicht drucken.", "بلا مصدر ثانٍ لا يجوز للتحرير نشر الرقم."),
"v124": ("Der Konzern hat die Zahlen angeblich geschönt, bewiesen ist nichts.", "الشركة زعموا أنها جمّلت الأرقام، ولم يثبت شيء."),
"v125": ("Dina hat zwei Tage recherchiert, bevor sie den Artikel veröffentlichte.", "دينا بحثت يومين قبل أن تنشر المقال."),
"v126": ("Laut einer Umfrage mit tausend Befragten sind die meisten dagegen.", "حسب استطلاع شمل ألف شخص فإن الأغلبية معارضة."),
"v127": ("Nachhaltig bauen heißt, an die Kosten in dreißig Jahren zu denken.", "البناء المستدام يعني التفكير في تكاليف ثلاثين سنة قادمة."),
"v128": ("Der Fortschritt in der Medizin hat seinen Preis, auch ethisch.", "التقدّم في الطب له ثمنه، أخلاقياً أيضاً."),
"v129": ("Die Forschung braucht Zeit, während die Politik schnelle Antworten will.", "البحث العلمي يحتاج وقتاً بينما تريد السياسة إجابات سريعة."),
"v130": ("Welche Auswirkung hat das Tempolimit tatsächlich auf die Unfallzahlen?", "ما الأثر الفعلي لتحديد السرعة على أعداد الحوادث؟"),
"v132": ("Die Anforderung an das Deutschniveau ist B2, nicht C1.", "المتطلب في مستوى الألمانية هو B2 لا C1."),
"v133": ("Die größte Herausforderung war nicht die Sprache, sondern die Bürokratie.", "التحدّي الأكبر لم يكن اللغة بل البيروقراطية."),
"v134": ("Zwischen Schlaf und Gedächtnis besteht ein enger Zusammenhang.", "بين النوم والذاكرة صلة وثيقة."),
"v135": ("Die Jury bewertet nicht die Idee allein, sondern auch die Umsetzung.", "لجنة التحكيم لا تقيّم الفكرة وحدها بل تنفيذها أيضاً."),
"v136": ("Man sollte an Anfänger nicht denselben Maßstab anlegen wie an Profis.", "لا ينبغي تطبيق المعيار نفسه على المبتدئين والمحترفين."),
"v138": ("Die Fähigkeit, ruhig zu widersprechen, lernt man nicht aus Büchern.", "القدرة على الاعتراض بهدوء لا تُتعلَّم من الكتب."),
"v139": ("Der Kurs setzt voraus, dass Sie B1 sicher beherrschen.", "الدورة تستلزم إتقانك لمستوى B1."),
"v140": ("Ein Nachweis über zwölf Monate Praxis ist Voraussetzung für die Anerkennung.", "إثبات اثني عشر شهراً من الممارسة شرط مسبق للاعتراف."),
"v141": ("Aus der kleinen Stichprobe lässt sich keine allgemeine Schlussfolgerung ziehen.", "من العيّنة الصغيرة لا يمكن استخلاص استنتاج عام."),
"v175": ("Bei steigenden Mieten ist der Wegzug vieler Familien unvermeidlich.", "مع ارتفاع الإيجارات يصبح رحيل عائلات كثيرة أمراً لا مفرّ منه."),
"v176": ("Angesichts der Zahlen hat der Rat den Beschluss vertagt.", "في ضوء الأرقام أجّل المجلس القرار."),
"v177": ("Prävention ist billiger als jede spätere Behandlung.", "الوقاية أرخص من أي علاج لاحق."),
"v178": ("Wer im Homeoffice arbeitet, muss beim Thema Pausen umdenken.", "من يعمل من البيت عليه إعادة التفكير في موضوع الاستراحات."),
"v180": ("Gute Urteilskraft zeigt sich, wenn zwei Quellen einander widersprechen.", "القدرة على الحكم تظهر حين يتناقض مصدران."),
"v185": ("Eine Partnerschaft auf Augenhöhe verteilt auch die unsichtbare Arbeit.", "الشراكة المتكافئة توزّع العمل غير المرئي أيضاً."),
"v186": ("Das Verhältnis zwischen Mieter und Vermieter war nie schlecht, nur distanziert.", "العلاقة بين المستأجر والمؤجّر لم تكن سيئة قط، بل متحفّظة فحسب."),
"v189": ("Nach dem Gespräch am runden Tisch haben sich die beiden versöhnt.", "بعد حديث الطاولة المستديرة تصالح الاثنان."),
"v191": ("Tarek gilt im Team als zuverlässig, weil er Fristen still einhält.", "طارق يُعتبر في الفريق جديراً بالثقة لأنه يلتزم بالمهل بصمت."),
"v194": ("Die Trennung war für die Kinder schwerer als für die Eltern.", "الانفصال كان على الأطفال أصعب منه على الوالدين."),
"v195": ("Nach der Scheidung teilen sie sich weiterhin die Betreuung.", "بعد الطلاق ما زالا يتقاسمان رعاية الأطفال."),
"v200": ("Das Missverständnis entstand, weil die Mail keinen Betreff hatte.", "سوء الفهم نشأ لأن الإيميل كان بلا موضوع."),
"v202": ("Zu viel Nähe kann in einer WG genauso stören wie zu wenig.", "القرب الزائد في السكن المشترك قد يزعج كالقرب القليل."),
"v205": ("Seine Zuneigung zeigt er nicht in Worten, sondern in Taten.", "مودّته لا يُظهرها بالكلام بل بالأفعال."),
"v209": ("Wer beim Zählerstand betrügt, riskiert die Kündigung des Vertrags.", "من يخدع في قراءة العدّاد يخاطر بفسخ العقد."),
"v210": ("Für ihn war die Weitergabe des Geheimnisses ein Verrat.", "بالنسبة له كان إفشاء السرّ خيانة."),
"v212": ("Ich will dich nicht enttäuschen, aber der Termin ist unrealistisch.", "لا أريد تخييب أملك، لكن الموعد غير واقعي."),
"v213": ("Die Enttäuschung über die Absage hielt nur einen Tag.", "خيبة الأمل من الرفض لم تدم سوى يوم."),
"v215": ("Neid entsteht oft dort, wo man nur die Fassade des anderen sieht.", "الحسد ينشأ غالباً حيث لا يرى المرء إلا واجهة الآخر."),
"v216": ("Ich gönne ihr die Beförderung, sie hat jahrelang dafür gearbeitet.", "أتمنّى لها الترقية من قلبي، فقد عملت لها سنوات."),
"v217": ("Meine Großmutter ist mein Vorbild, weil sie mit sechzig noch Lesen lernte.", "جدتي قدوتي لأنها تعلّمت القراءة في الستين."),
"v220": ("Der Vermieter wollte nicht nachgeben, akzeptierte aber die Ratenzahlung.", "المؤجّر لم يُرد التراجع، لكنه قبل الدفع بالتقسيط."),
"v221": ("Die beiden Seiten haben sich auf eine Frist von zwei Wochen geeinigt.", "اتّفق الطرفان على مهلة أسبوعين."),
"v236": ("Bei einer Erkältung hilft Ruhe mehr als jedes Antibiotikum.", "في الزكام تنفع الراحة أكثر من أي مضاد حيوي."),
"v237": ("Fieber ist ein Symptom, nicht die Krankheit selbst.", "الحمّى عَرَض لا المرض نفسه."),
"v238": ("Die Diagnose kam erst nach der zweiten Untersuchung.", "التشخيص لم يأتِ إلا بعد الفحص الثاني."),
"v241": ("Das Knie muss operiert werden, sonst bleibt der Schmerz.", "الركبة يجب أن تُجرى لها عملية وإلا بقي الألم."),
"v243": ("Der Patient ist langsamer gesundet, als die Ärzte erwartet hatten.", "المريض تماثل للشفاء أبطأ مما توقّع الأطباء."),
"v244": ("Während der Genesung sollte man auf Sport verzichten.", "أثناء التعافي ينبغي الامتناع عن الرياضة."),
"v245": ("Die Krankschreibung gilt für drei Tage und wurde per Post geschickt.", "شهادة المرض صالحة لثلاثة أيام وأُرسلت بالبريد."),
"v249": ("Für die Prüfungsverschiebung verlangt die Uni ein ärztliches Attest.", "لتأجيل الامتحان تطلب الجامعة شهادة طبية."),
"v250": ("Nach dem Schlaganfall folgen drei Wochen Reha, dann ambulante Therapie.", "بعد الجلطة ثلاثة أسابيع تأهيل، ثم علاج خارجي."),
"v253": ("Die Erschöpfung nach der Doppelschicht war körperlich und seelisch.", "الإعياء بعد المناوبة المزدوجة كان جسدياً ونفسياً."),
"v254": ("Die Sucht nach dem Handy beginnt oft mit dem ersten Blick am Morgen.", "إدمان الهاتف يبدأ غالباً بأول نظرة صباحاً."),
"v255": ("Er merkte erst spät, wie süchtig er nach Anerkennung war.", "لم يدرك إلا متأخراً كم كان مدمناً على التقدير."),
"v256": ("Mobbing am Arbeitsplatz muss man dokumentieren, mit Datum und Uhrzeit.", "التنمّر في مكان العمل يجب توثيقه بالتاريخ والساعة."),
"v257": ("Wer Kollegen mobbt, riskiert eine Abmahnung.", "من ينمّر على زملائه يخاطر بإنذار."),
"v258": ("Mein Vorgesetzter hat das Gespräch sachlich geführt.", "مسؤولي المباشر أدار الحديث بموضوعية."),
"v259": ("Ein gutes Arbeitsklima ist wichtiger als der Obstkorb.", "المناخ المهني الجيد أهم من سلة الفاكهة."),
"v262": ("Bei Bildschirmarbeit sollte man alle zwei Stunden aufstehen.", "في عمل الشاشات ينبغي النهوض كل ساعتين."),
"v263": ("Die Kasse übernimmt die Vorsorge ab dem fünfunddreißigsten Lebensjahr.", "التأمين يتحمّل الفحص الوقائي من سن الخامسة والثلاثين."),
"v264": ("Die Schlafstörung begann mit den Nachtschichten.", "اضطراب النوم بدأ مع المناوبات الليلية."),
"v1408": ("Der Arzt hört das Herz ab und schaut in den Hals.", "الطبيب يستمع إلى القلب وينظر في الحلق."),
"v269": ("Ohne ein stabiles Umfeld ist jede Therapie schwerer.", "بلا محيط اجتماعي مستقر يكون كل علاج أصعب."),
"v270": ("Der Zusammenhalt im Dorf zeigte sich nach der Überschwemmung.", "التماسك في القرية ظهر بعد الفيضان."),
"v271": ("Solidarität heißt hier konkret: einmal pro Woche vorlesen.", "التضامن هنا يعني عملياً: القراءة للأطفال مرة أسبوعياً."),
"v272": ("Die Ungleichheit beginnt oft schon vor der Einschulung.", "اللاتكافؤ يبدأ غالباً قبل دخول المدرسة."),
"v274": ("Im Winter öffnet die Stadt Notunterkünfte für Obdachlose.", "في الشتاء تفتح المدينة مآوي طوارئ لمن بلا مأوى."),
"v275": ("Ein Viertel der Schüler hat einen Migrationshintergrund.", "ربع التلاميذ لهم جذر هجرة عائلي."),
"v276": ("Als Migrant lernt man die Behörden schneller kennen als die Nachbarn.", "كمهاجر تتعرّف على الدوائر الرسمية أسرع من الجيران."),
"v277": ("Ohne Zuwanderung fehlten der Region tausende Fachkräfte.", "بلا هجرة وافدة لنقص المنطقة آلاف الكفاءات."),
"v278": ("Sich zu integrieren heißt nicht, die eigene Sprache aufzugeben.", "الاندماج لا يعني التخلّي عن اللغة الأم."),
"v280": ("Ausgrenzung beginnt oft mit einem Witz, über den nur einer lacht.", "الإقصاء يبدأ غالباً بنكتة لا يضحك عليها إلا شخص واحد."),
"v281": ("Wer Bewerber wegen des Namens aussortiert, diskriminiert.", "من يستبعد المتقدّمين بسبب الاسم يمارس التمييز."),
"v282": ("Gegen Diskriminierung bei der Wohnungssuche kann man sich beschweren.", "ضد التمييز في البحث عن سكن يمكن تقديم شكوى."),
"v287": ("Sie arbeitet ehrenamtlich bei der Tafel, jeden zweiten Samstag.", "تعمل تطوّعياً في مائدة المتطوعين كل سبتين."),
"v289": ("Ihr Engagement im Verein hat ihr später den Job gebracht.", "التزامها المدني في الجمعية جلب لها العمل لاحقاً."),
"v290": ("Die Demonstration verlief friedlich, mit rund zweitausend Teilnehmern.", "المظاهرة جرت سلمياً بنحو ألفي مشارك."),
"v292": ("Zur Kundgebung vor dem Rathaus kamen mehr Menschen als angemeldet.", "إلى التجمّع أمام البلدية جاء ناس أكثر مما سُجّل."),
"v293": ("Die Petition gegen die Umsiedlung hat zehntausend Unterschriften.", "العريضة ضد الإسكان القسري جمعت عشرة آلاف توقيع."),
"v294": ("Lesen Sie den Vertrag, bevor Sie unterschreiben, besonders die Klausel unten.", "اقرأ العقد قبل أن توقّع، خاصة البند في الأسفل."),
"v301": ("Im Rechtsstaat gilt auch für die Behörde eine Frist.", "في دولة القانون تسري المهلة على الإدارة أيضاً."),
"v302": ("Die Grundrechte gelten für alle, nicht nur für Staatsbürger.", "الحقوق الأساسية للجميع لا للمواطنين فقط."),
"v305": ("Unser Konsum an Kleidung hat sich in zwanzig Jahren verdoppelt.", "استهلاكنا للملابس تضاعف في عشرين سنة."),
"v307": ("In der Konsumgesellschaft wird Reparieren zur Ausnahme.", "في مجتمع الاستهلاك يصبح الإصلاح استثناءً."),
"v308": ("Er hat ein schlechtes Gewissen, weil er den Termin vergessen hat.", "يؤنّبه ضميره لأنه نسي الموعد."),
"v309": ("Meinungsfreiheit schützt auch Aussagen, die einem nicht gefallen.", "حرية الرأي تحمي أيضاً أقوالاً لا تعجبك."),
"v310": ("Die Debatte über das Tempolimit wird seit Jahren geführt.", "الجدل حول تحديد السرعة يدور منذ سنوات."),
"v315": ("Die Doppelbelastung lässt sich nur mit einem klaren Plan bewältigen.", "العبء المزدوج لا يُجابَه إلا بخطة واضحة."),
"v318": ("Die Vielfalt im Team bringt bessere Lösungen, aber längere Diskussionen.", "التنوّع في الفريق يجلب حلولاً أفضل ونقاشات أطول."),
"v322": ("Sie vermietet das kleine Zimmer an eine Studentin.", "هي تؤجّر الغرفة الصغيرة لطالبة."),
"v323": ("Der Vermieter muss den Mangel innerhalb einer angemessenen Frist beheben.", "على المؤجّر إصلاح العيب خلال مهلة معقولة."),
"v324": ("Als Mieter darf man die Miete bei Schimmel mindern.", "كمستأجر يحقّ لك تخفيض الإيجار عند وجود عفن."),
"v325": ("Die Kaution beträgt zwei Monatsmieten und liegt auf einem Sonderkonto.", "الضمانة شهران من الإيجار وتُودَع في حساب خاص."),
"v326": ("Im Mietvertrag steht, wer für kleine Reparaturen zahlt.", "في عقد الإيجار مكتوب من يدفع الإصلاحات الصغيرة."),
"v328": ("In unserer Nachbarschaft gibt es eine Gruppe, in der man Werkzeug teilt.", "في جيرتنا مجموعة تتشارك الأدوات."),
"v329": ("Der Umzug kostete mehr Nerven als Geld.", "النقلة السكنية كلّفت أعصاباً أكثر من المال."),
"v330": ("Wir ziehen im März um, zwei Straßen weiter.", "ننتقل في مارس، على بعد شارعين."),
"v334": ("Der Stadtteil im Norden ist günstiger, aber schlechter angebunden.", "ضاحية الشمال أرخص لكنها أسوأ ربطاً بالمواصلات."),
"v335": ("In ländlichen Gegenden fährt der Bus nur dreimal täglich.", "في المناطق الريفية تمرّ الحافلة ثلاث مرات يومياً فقط."),
"v337": ("In der Innenstadt sind die Mieten zuletzt am stärksten gestiegen.", "في مركز المدينة ارتفعت الإيجارات مؤخراً أكثر ما يكون."),
"v338": ("Das Grundstück ist klein, aber der Garten geht nach Süden.", "قطعة الأرض صغيرة لكن الحديقة تتجه جنوباً."),
"v339": ("Ein Eigenheim bindet einen an einen Ort, für Jahrzehnte.", "المنزل المملوك يربطك بمكان لعقود."),
"v340": ("Die Hypothek läuft noch zwanzig Jahre.", "الرهن العقاري ما زال يستمر عشرين سنة."),
"v341": ("Wie wollen Sie den Umbau finanzieren, mit Eigenkapital oder Kredit?", "كيف ستموّل التجديد، برأس مال ذاتي أم بقرض؟"),
"v343": ("Der Vermieter will das Bad renovieren, während wir im Urlaub sind.", "المؤجّر يريد تجديد الحمّام بينما نحن في العطلة."),
"v344": ("Nach dem Modernisieren darf die Miete nur begrenzt steigen.", "بعد التحديث لا يجوز أن يرتفع الإيجار إلا بحدود."),
"v345": ("Der Makler verlangt zwei Kaltmieten Provision vom Vermieter.", "الوسيط العقاري يطلب عمولة شهرين إيجار بارد من المؤجّر."),
"v346": ("Bei der Besichtigung waren zwanzig andere Interessenten da.", "في المعاينة كان هناك عشرون مهتماً آخر."),
"v347": ("Wir haben die Wohnung zweimal besichtigt, einmal bei Tageslicht.", "عايّنا الشقة مرتين، مرة في ضوء النهار."),
"v348": ("Die Provision zahlt seit 2015 derjenige, der den Makler beauftragt.", "العمولة يدفعها منذ 2015 من يكلّف الوسيط."),
"v349": ("Der Vertrag ist auf zwei Jahre befristet, mit Option auf Verlängerung.", "العقد محدّد بسنتين مع خيار التمديد."),
"v350": ("Nach der Probezeit wurde die Stelle unbefristet.", "بعد فترة التجربة صار المنصب غير محدود المدة."),
"v351": ("Man kann den Vertrag nur schriftlich kündigen, mit sechs Wochen Frist.", "لا يمكن فسخ العقد إلا كتابياً بمهلة ستة أسابيع."),
"v352": ("Die Kündigung muss dem Vermieter bis zum dritten Werktag vorliegen.", "الفسخ يجب أن يصل المؤجّر حتى ثالث يوم عمل."),
"v353": ("Auf Elterngeld besteht ein Anspruch, wenn der Antrag rechtzeitig kommt.", "يوجد حق في منحة الوالدين إذا وصل الطلب في موعده."),
"v354": ("Die Wohnungsnot trifft zuerst Studierende und Alleinerziehende.", "أزمة السكن تصيب أولاً الطلبة والوالدين المنفردين."),
"v355": ("Leere Büros könnten neuen Wohnraum schaffen, wenn der Plan es erlaubt.", "المكاتب الفارغة قد توفّر حيّز سكن جديداً إن سمح المخطط."),
"v357": ("Zusammenleben in einer WG funktioniert nur mit klaren Regeln.", "العيش معاً في سكن مشترك لا ينجح إلا بقواعد واضحة."),
"v358": ("Die Nebenkosten kommen zur Kaltmiete hinzu, etwa zweihundert Euro.", "التكاليف الجانبية تُضاف إلى الإيجار البارد، نحو مائتي يورو."),
"v360": ("Die Möblierung bleibt: Herd, Spüle und Schränke.", "التأثيث يبقى: موقد وحوض وخزائن."),
"v361": ("Die Firma stattet jeden Arbeitsplatz mit zwei Bildschirmen aus.", "الشركة تجهّز كل مكان عمل بشاشتين."),
"v362": ("Die Ausstattung der Wohnung ist einfach, aber vollständig.", "تجهيز الشقة بسيط لكنه كامل."),
"v363": ("Laut Grundriss liegt das Schlafzimmer zur ruhigen Hofseite.", "حسب مخطط الشقة تقع غرفة النوم على جهة الفناء الهادئة."),
"v364": ("Musik nach Mitternacht gilt als Belästigung laut Hausordnung.", "الموسيقى بعد منتصف الليل تُعتبر إيذاءً حسب نظام العمارة."),
"v365": ("Ich möchte mich über den Lärm der Baustelle beschweren.", "أريد أن أشتكي من ضجيج الورشة."),
"v366": ("Die Beschwerde muss schriftlich mit Datum und Uhrzeit eingereicht werden.", "الشكوى يجب أن تُقدَّم كتابياً بالتاريخ والساعة."),
"v367": ("Die Hausordnung kennt Ruhezeiten ab zweiundzwanzig Uhr.", "نظام العمارة يحدّد أوقات هدوء من العاشرة مساءً."),
"v370": ("Die Plattform vermittelt Zimmer, haftet aber nicht für Schäden.", "المنصّة تتوسّط في الغرف لكنها لا تتحمّل الأضرار."),
"v371": ("Der Chatbot beantwortet Standardfragen, alles andere geht an Menschen.", "روبوت المحادثة يجيب عن الأسئلة النمطية، والباقي يذهب للبشر."),
"v376": ("Die Kinderärztin empfiehlt höchstens eine Stunde Bildschirmzeit pro Tag.", "طبيبة الأطفال توصي بساعة واحدة كحد أقصى من زمن الشاشة يومياً."),
"v379": ("Ein sicheres Passwort hat zwölf Zeichen und steht in keinem Wörterbuch.", "كلمة المرور الآمنة من اثني عشر رمزاً وليست في أي قاموس."),
"v380": ("Ohne Nutzerkonto kann man die Kündigung nicht digital einreichen.", "بلا حساب مستخدم لا يمكن تقديم الإلغاء رقمياً."),
"v384": ("Der Datenschutz verbietet es, die Liste per Mail zu verschicken.", "حماية البيانات تمنع إرسال القائمة بالإيميل."),
"v385": ("Laut DSGVO darf man die Löschung seiner Daten verlangen.", "حسب لائحة حماية البيانات الأوروبية يحق للمرء طلب حذف بياناته."),
"v386": ("Der Algorithmus zeigt dir, was du schon glaubst.", "الخوارزمية تعرض لك ما تؤمن به مسبقاً."),
"v387": ("Künstliche Intelligenz kann Röntgenbilder vorsortieren, nicht entscheiden.", "الذكاء الاصطناعي يستطيع فرز صور الأشعة مسبقاً لا اتخاذ القرار."),
"v389": ("Die Automatisierung hat im Lager zwanzig Stellen verändert, nicht gestrichen.", "الأتمتة غيّرت عشرين وظيفة في المستودع ولم تلغِها."),
"v390": ("Die digitale Kluft verläuft heute weniger nach Alter als nach Einkommen.", "الفجوة الرقمية تسير اليوم حسب الدخل أكثر من العمر."),
"v391": ("Der Influencer erwähnt die Bezahlung erst am Ende des Videos.", "المؤثّر لا يذكر الأجر إلا في نهاية الفيديو."),
"v395": ("Der Online-Handel muss die Versandkosten bei Widerruf erstatten.", "التجارة الإلكترونية ملزمة بردّ تكاليف الشحن عند التراجع."),
"v397": ("Das Konto wurde gehackt, weil das Passwort auch für Spiele galt.", "الحساب اختُرق لأن كلمة المرور كانت نفسها للألعاب."),
"v398": ("Cyberkriminalität trifft kleine Firmen härter als Konzerne.", "الجرائم السيبرانية تصيب الشركات الصغيرة أشدّ من الكبرى."),
"v399": ("Die Datenspeicherung ist auf sechs Monate begrenzt.", "تخزين البيانات محدود بستة أشهر."),
"v400": ("Die Fotos liegen in der Cloud, nicht mehr auf dem Handy.", "الصور في السحابة، ولم تعد على الهاتف."),
"v401": ("Ein Backup jede Woche hätte den Verlust der Arbeit verhindert.", "نسخة احتياطية أسبوعية كانت ستمنع ضياع العمل."),
"v402": ("Der Akku hält nach zwei Jahren nur noch einen halben Tag.", "البطارية بعد سنتين لا تصمد إلا نصف يوم."),
"v404": ("Der Speicher ist voll, deshalb lädt das Update nicht.", "مساحة التخزين ممتلئة، لذلك لا يُحمَّل التحديث."),
"v406": ("Kaum jemand liest die Nutzungsbedingungen, bevor er zustimmt.", "قلّما يقرأ أحد شروط الاستخدام قبل الموافقة."),
"v407": ("Bitte aktualisieren Sie die App, sonst funktioniert die Anmeldung nicht.", "من فضلك حدّث التطبيق وإلا لن يعمل تسجيل الدخول."),
"v408": ("Die Bestätigung lag im Spam, nicht im Posteingang.", "التأكيد كان في البريد المزعج لا في الوارد."),
"v409": ("Das Abonnement verlängert sich automatisch, wenn man nicht kündigt.", "الاشتراك يتجدّد تلقائياً إن لم يُلغَ."),
"v410": ("Die Influencerin kennzeichnet bezahlte Beiträge mit „Werbung“.", "المؤثِّرة تسم المنشورات المدفوعة بكلمة «إعلان»."),
"v413": ("Nach dem Update war die Tastatur plötzlich englisch.", "بعد التحديث صارت لوحة المفاتيح إنجليزية فجأة."),
"v415": ("Sie forscht seit Jahren zu Schlaf und Gedächtnis.", "هي تبحث منذ سنوات في النوم والذاكرة."),
"v422": ("Die Hypothese wurde durch das zweite Experiment widerlegt.", "الفرضية دُحضت بالتجربة الثانية."),
"v423": ("Die wichtigste Erkenntnis: Kleine Pausen wirken besser als eine lange.", "أهم معرفة مستخلَصة: الاستراحات القصيرة أنفع من واحدة طويلة."),
"v425": ("Im Labor werden die Proben bei minus achtzig Grad gelagert.", "في المختبر تُخزَّن العيّنات عند ثمانين درجة تحت الصفر."),
"v427": ("Der Datensatz umfasst dreitausend Befragte aus zwei Regionen.", "مجموعة البيانات تشمل ثلاثة آلاف مستجوَب من منطقتين."),
"v429": ("Wir werten die Fragebögen erst nach der letzten Befragung aus.", "نحلّل الاستبيانات بعد آخر استجواب فقط."),
"v430": ("Die Auswertung dauert länger als die Befragung selbst.", "التحليل يستغرق أطول من الاستطلاع نفسه."),
"v432": ("Die Studie hat tausend Haushalte telefonisch befragt.", "الدراسة استطلعت ألف أسرة هاتفياً."),
"v433": ("Die Stichprobe ist zu klein, um die Region zu vertreten.", "العيّنة أصغر من أن تمثّل المنطقة."),
"v435": ("Wer zitiert, muss die Quelle mit Seitenzahl angeben.", "من يقتبس عليه ذكر المصدر مع رقم الصفحة."),
"v437": ("Die Behauptung ist nicht belegt, es fehlt jede Quelle.", "الادّعاء غير مثبت، ولا يوجد أي مصدر."),
"v443": ("Die Vorlesung gibt es als Aufzeichnung, das Seminar nicht.", "المحاضرة متوفرة كتسجيل، أما الحلقة النقاشية فلا."),
"v445": ("Wer die Frist nicht einhalten kann, zahlt eine neue Gebühr.", "من لا يستطيع الالتزام بالمهلة يدفع رسوماً جديدة."),
"v446": ("Das Gutachten des Instituts kommt zu einem anderen Ergebnis.", "التقرير الخبير للمعهد يصل إلى نتيجة مختلفة."),
"v447": ("Die Förderung läuft drei Jahre und deckt zwei Stellen.", "التمويل يستمر ثلاث سنوات ويغطّي وظيفتين."),
"v449": ("Das Forschungsprojekt untersucht Lärm in Schulen.", "المشروع البحثي يدرس الضجيج في المدارس."),
"v450": ("Nachhaltigkeit steht im Bericht, aber nicht im Budget.", "الاستدامة موجودة في التقرير لا في الميزانية."),
"v451": ("Nach dem Master will sie promovieren, am liebsten im Ausland.", "بعد الماستر تريد نيل الدكتوراه، ويفضَّل في الخارج."),
"v452": ("Die Promotion dauerte fünf Jahre, neben einer halben Stelle.", "الدكتوراه استغرقت خمس سنوات إلى جانب وظيفة نصف دوام."),
"v453": ("Das Team publiziert die Ergebnisse frei zugänglich.", "الفريق ينشر النتائج بشكل مفتوح."),
"v454": ("Die Veröffentlichung wurde von zwei Gutachtern geprüft.", "النشر العلمي راجعه خبيران."),
"v455": ("Die Glaubwürdigkeit der Quelle hängt von ihrer Unabhängigkeit ab.", "مصداقية المصدر تتوقف على استقلاليته."),
"v456": ("Ein glaubwürdiger Zeuge widerspricht sich nicht bei den Details.", "الشاهد الموثوق لا يناقض نفسه في التفاصيل."),
"v1430": ("Wissen veraltet schnell, die Fähigkeit zu lernen nicht.", "المعرفة تشيخ بسرعة، أما القدرة على التعلّم فلا."),
"v459": ("Die Stelle ist attraktiv, obwohl das Gehalt nur Durchschnitt ist.", "الوظيفة جذابة رغم أن الراتب متوسط فقط."),
"v461": ("Das Ideal der ständigen Erreichbarkeit macht viele krank.", "المثال الأعلى في التواجد الدائم يُمرض كثيرين."),
"v462": ("Das Schönheitsideal ändert sich, der Druck bleibt.", "مثال الجمال السائد يتغيّر، والضغط يبقى."),
"v468": ("Auf dem Foto war das Make-up so retuschiert, dass sie sich kaum erkannte.", "في الصورة كان المكياج منمَّقاً حتى بالكاد عرفت نفسها."),
"v472": ("Wir altern alle, die Frage ist nur, wie gesund.", "كلنا نشيخ، والسؤال فقط: بأي صحة."),
"v475": ("Der Mantel ist modisch, aber für den Winter zu dünn.", "المعطف على الموضة لكنه رقيق جداً للشتاء."),
"v476": ("Für das Vorstellungsgespräch wählte sie ein schlichtes Outfit.", "لمقابلة التوظيف اختارت زيّاً بسيطاً."),
"v479": ("Das Label steht für faire Produktion, sagt zumindest die Werbung.", "العلامة التجارية ترمز لإنتاج عادل، على الأقل حسب الإعلان."),
"v480": ("Die Marke ist teuer, die Qualität nicht unbedingt besser.", "البراند غالٍ، والجودة ليست بالضرورة أفضل."),
"v481": ("Der neue Look passt zu ihr, weil er nicht verkleidet wirkt.", "الإطلالة الجديدة تناسبها لأنها لا تبدو تنكّراً."),
"v482": ("Beim Styling für das Foto ging es mehr um Licht als um Kleidung.", "في التنسيق للصورة كان الأمر عن الضوء أكثر من الملابس."),
"v483": ("Der Trend zu Secondhand hat auch mit dem Preis zu tun.", "الرواج نحو الملابس المستعملة له علاقة بالسعر أيضاً."),
"v484": ("Ihr Stil ist schlicht: dunkle Farben, keine Logos.", "أسلوبها بسيط: ألوان داكنة وبلا شعارات."),
"v485": ("Das Café ist stilvoll eingerichtet, ohne teuer zu wirken.", "المقهى مؤثَّث بأناقة دون أن يبدو غالياً."),
"v487": ("Die Wohnung ist schlicht, aber hell und gut geschnitten.", "الشقة بسيطة لكنها مضيئة وحسنة التقسيم."),
"v489": ("Das Lächeln auf dem Werbefoto wirkt künstlich.", "الابتسامة في صورة الإعلان تبدو مصطنعة."),
"v490": ("Viele Magazine retuschieren Haut und Figur, ohne es zu kennzeichnen.", "مجلات كثيرة تنمّق البشرة والقوام دون وسم ذلك."),
"v491": ("Ohne Retusche sähe das Titelbild ganz normal aus.", "بلا تنميق لبدت صورة الغلاف عادية تماماً."),
"v492": ("Für ein Selfie vor dem Denkmal standen zwanzig Leute Schlange.", "لصورة ذاتية أمام النصب اصطفّ عشرون شخصاً."),
"v493": ("Der erste Eindruck zählt, lässt sich aber korrigieren.", "الانطباع الأول مهم، لكنه قابل للتصحيح."),
"v494": ("Ruhige Stimmen wirken auf Kunden überzeugender als laute.", "الأصوات الهادئة تؤثّر في الزبائن أكثر إقناعاً من الصاخبة."),
"v497": ("Sie tritt selbstbewusst auf, ohne arrogant zu wirken.", "تتصرّف بثقة بالنفس دون أن تبدو متكبّرة."),
"v498": ("Selbstbewusstsein wächst mit jeder Prüfung, die man besteht.", "الثقة بالنفس تنمو مع كل امتحان يُجتاز."),
"v499": ("Die Warnung war übertrieben, es regnete nur eine Stunde.", "التحذير كان مبالَغاً فيه، فقد أمطرت ساعة فقط."),
"v500": ("Die Überschrift übertreibt, der Text selbst ist vorsichtig.", "العنوان يبالغ، والنص نفسه حذر."),
"v501": ("Eitelkeit lässt Menschen Fotos zehnmal wiederholen.", "الغرور يجعل الناس يعيدون الصور عشر مرات."),
"v507": ("Das Gemälde zeigt eine Straße bei Nacht, ohne Menschen.", "اللوحة تصوّر شارعاً ليلاً بلا ناس."),
"v510": ("Die Skulptur vor dem Bahnhof ist aus altem Stahl.", "المنحوتة أمام المحطة من فولاذ قديم."),
"v511": ("Das Denkmal erinnert an die Opfer der Überschwemmung.", "النصب التذكاري يخلّد ضحايا الفيضان."),
"v513": ("Auf der Bühne wirkte sie viel größer als im Café.", "على الخشبة بدت أكبر بكثير مما في المقهى."),
"v521": ("Die Regie setzt auf lange Szenen ohne Musik.", "الإخراج يعتمد على مشاهد طويلة بلا موسيقى."),
"v522": ("Der Regisseur drehte den Film in nur drei Wochen.", "المخرج صوّر الفيلم في ثلاثة أسابيع فقط."),
"v523": ("Das Drehbuch wurde zehnmal umgeschrieben.", "السيناريو أُعيدت كتابته عشر مرات."),
"v524": ("Der Darsteller spricht im Film Deutsch mit tunesischem Akzent.", "الممثل يتكلم في الفيلم ألمانية بلكنة تونسية."),
"v526": ("Die letzte Szene wurde ohne Dialog gedreht.", "المشهد الأخير صُوّر بلا حوار."),
"v527": ("Die Vorstellung beginnt um acht, Einlass ab halb acht.", "العرض يبدأ في الثامنة، والدخول من السابعة والنصف."),
"v528": ("Die Schüler führen im Juni ein eigenes Stück auf.", "التلاميذ يعرضون في يونيو مسرحية من تأليفهم."),
"v531": ("Wer ein Buch rezensiert, sollte es ganz gelesen haben.", "من يكتب نقداً لكتاب ينبغي أن يكون قد قرأه كاملاً."),
"v532": ("Die Rezension lobt die Sprache und kritisiert den Schluss.", "المقالة النقدية تمدح اللغة وتنتقد الخاتمة."),
"v535": ("Lyrik lese ich laut, sonst verstehe ich den Rhythmus nicht.", "الشعر الغنائي أقرؤه بصوت عالٍ وإلا لا أفهم الإيقاع."),
"v538": ("Der Schriftsteller lebt seit zwanzig Jahren in Hamburg.", "الأديب يعيش في هامبورغ منذ عشرين سنة."),
"v539": ("Ihr bekanntestes Werk ist ein Roman über zwei Familien.", "أشهر أعمالها رواية عن عائلتين."),
"v542": ("Das Motiv des Heimwehs zieht sich durch alle Kapitel.", "فكرة الحنين إلى الوطن تخترق كل الفصول."),
"v546": ("Das kulturelle Erbe der Region sind ihre Märkte, nicht ihre Museen.", "الإرث الثقافي للمنطقة هو أسواقها لا متاحفها."),
"v547": ("Die Altstadt gehört seit Jahren zum Weltkulturerbe.", "المدينة القديمة مدرجة منذ سنوات في التراث العالمي."),
"v548": ("Die bekannteste Sehenswürdigkeit ist eigentlich der Markt am Samstag.", "أشهر معلم جدير بالزيارة هو في الحقيقة سوق السبت."),
"v549": ("Im Vorstellungsgespräch fragte man nach der Lücke im Lebenslauf.", "في مقابلة التوظيف سألوا عن الفجوة في السيرة الذاتية."),
"v555": ("Die Vergütung für Überstunden steht im Tarifvertrag.", "المكافأة عن الساعات الإضافية مذكورة في الاتفاقية الجماعية."),
"v556": ("Jede Überstunde wird mit Zuschlag bezahlt oder abgefeiert.", "كل ساعة إضافية تُدفع بعلاوة أو تُعوَّض إجازة."),
"v557": ("Die Schicht beginnt um sechs und endet um vierzehn Uhr.", "المناوبة تبدأ في السادسة وتنتهي في الثانية ظهراً."),
"v558": ("Schichtarbeit stört den Schlaf mehr als lange Arbeitstage.", "العمل بالمناوبات يخلّ بالنوم أكثر من أيام العمل الطويلة."),
"v559": ("Nach der Elternzeit arbeitet sie in Teilzeit, dreißig Stunden.", "بعد إجازة الأمومة تعمل بدوام جزئي، ثلاثين ساعة."),
"v560": ("In Vollzeit wären es vierzig Stunden pro Woche.", "بالدوام الكامل ستكون أربعين ساعة أسبوعياً."),
"v561": ("Im Arbeitsvertrag steht eine Probezeit von sechs Monaten.", "في عقد العمل فترة تجربة ستة أشهر."),
"v565": ("Auf der Konferenz hielt sie einen Vortrag über Lärmschutz.", "في المؤتمر ألقت محاضرة عن الحماية من الضجيج."),
"v567": ("Eine gute Führungskraft erklärt Entscheidungen, statt sie nur anzukündigen.", "القيادي الجيد يشرح القرارات بدل مجرد إعلانها."),
"v568": ("Der Aufstieg zur Teamleitung kam nach fünf Jahren.", "الترقي إلى قيادة الفريق جاء بعد خمس سنوات."),
"v569": ("Wer aufsteigen will, muss auch unbequeme Aufgaben übernehmen.", "من يريد الترقي عليه تولّي مهام غير مريحة أيضاً."),
}
