# -*- coding: utf-8 -*-
"""exampleDe/exampleAr Batch 6 (letzte): Rest B2 (212)."""
B = {
"v1173": ("Aus der Fürsorgepflicht folgt, dass der Arbeitgeber Überlastung ernst nehmen muss.", "من واجب الرعاية يترتب أن على صاحب العمل أخذ الإرهاق بجدّية."),
"v1174": ("Eine Sozialleistung muss man beantragen, sie kommt nicht von allein.", "الخدمة الاجتماعية يجب طلبها، فهي لا تأتي وحدها."),
"v1177": ("Wer kein Konto hat, ist von vielen Angeboten ausgeschlossen.", "من لا يملك حساباً مستبعَد من عروض كثيرة."),
"v1178": ("Die Laufzeitverlängerung des Kraftwerks wurde heftig diskutiert.", "تمديد عمر المحطة نوقش بحدّة."),
"v1179": ("Ein Endlager muss für Jahrtausende sicher sein.", "موقع الدفن النهائي يجب أن يكون آمناً لآلاف السنين."),
"v1180": ("Der Atommüll lagert vorerst in Zwischenlagern neben den Werken.", "النفايات الإشعاعية تُخزَّن مؤقتاً في مستودعات وسيطة قرب المحطات."),
"v1181": ("Beim Bürgerwindpark gehört jedes Windrad zum Teil den Anwohnern.", "في مزرعة الرياح الأهلية تعود كل عنفة جزئياً للسكان."),
"v1182": ("Der Mindestabstand zum nächsten Haus beträgt hier tausend Meter.", "المسافة الدنيا إلى أقرب منزل هنا ألف متر."),
"v1183": ("Der Schattenwurf der Rotoren stört morgens im Wohnzimmer.", "إلقاء ظل الشفرات يزعج صباحاً في غرفة الجلوس."),
"v1184": ("Ob Infraschall krank macht, ist wissenschaftlich umstritten.", "هل يُمرض ما تحت السمع؟ الأمر محلّ خلاف علمي."),
"v1185": ("Das Netzentgelt macht ein Viertel des Strompreises aus.", "تعرفة الشبكة تشكّل ربع سعر الكهرباء."),
"v1186": ("Ohne Netzausbau kommt der Windstrom nicht in den Süden.", "بلا توسيع الشبكة لا تصل كهرباء الرياح إلى الجنوب."),
"v1187": ("Gegen die neue Stromtrasse klagen mehrere Gemeinden.", "ضد ممر الكهرباء الجديد ترفع بلديات عدة دعاوى."),
"v1188": ("Die Gleichstromleitung verliert auf langer Strecke weniger Energie.", "خط التيار المستمر يفقد طاقة أقل على المسافات الطويلة."),
"v1189": ("Wenn der Anbieter pleitegeht, springt der Grundversorger ein.", "إذا أفلس المورّد يتدخل المورّد الأساسي."),
"v1190": ("Der Anbieterwechsel dauert vier Wochen und unterbricht die Versorgung nicht.", "تبديل المورّد يستغرق أربعة أسابيع ولا يقطع التزويد."),
"v1191": ("Die Stromkennzeichnung auf der Rechnung zeigt den Anteil aus Kohle.", "بطاقة منشأ الكهرباء على الفاتورة تُظهر حصة الفحم."),
"v1192": ("Ökostrom kostet bei diesem Tarif nur zwei Cent mehr.", "الكهرباء الخضراء تكلّف في هذه التعرفة سنتين إضافيين فقط."),
"v1193": ("Das Erneuerbare-Energien-Gesetz garantierte jahrelang feste Preise.", "قانون الطاقات المتجددة ضمن أسعاراً ثابتة لسنوات."),
"v1194": ("Die Einspeisevergütung sinkt für neue Anlagen jedes Jahr.", "تعرفة التغذية تنخفض للمنشآت الجديدة كل سنة."),
"v1195": ("Beim Eigenverbrauch spart man den vollen Strompreis.", "في الاستهلاك الذاتي توفّر سعر الكهرباء كاملاً."),
"v1196": ("Ein Stromspeicher im Keller macht die Solaranlage auch abends nützlich.", "مخزن كهرباء في القبو يجعل المنظومة الشمسية مفيدة مساءً أيضاً."),
"v1197": ("Das Pumpspeicherkraftwerk pumpt nachts Wasser nach oben und lässt es tags ab.", "محطة الضخ التخزينية تضخ الماء ليلاً إلى الأعلى وتُنزله نهاراً."),
"v1198": ("Sektorenkopplung heißt: Strom heizt Häuser und fährt Autos.", "اقتران القطاعات يعني: الكهرباء تدفّئ البيوت وتحرّك السيارات."),
"v1199": ("Die Wärmewende scheitert oft an alten Heizkellern.", "تحوّل التدفئة يفشل غالباً بسبب أقبية التدفئة القديمة."),
"v1200": ("Mit Fernwärme braucht das Haus keinen eigenen Kessel.", "بالتدفئة البعيدة لا يحتاج المنزل مرجلاً خاصاً."),
"v1201": ("Die Umlage wird auf alle Stromkunden verteilt.", "الرسوم المضافة تُوزَّع على كل زبائن الكهرباء."),
"v1202": ("Der CO2-Preis verteuert Benzin und Heizöl schrittweise.", "سعر الكربون يرفع ثمن البنزين وزيت التدفئة تدريجياً."),
"v1203": ("Im Emissionshandel kaufen Firmen das Recht, CO2 auszustoßen.", "في تجارة الانبعاثات تشتري الشركات حق إصدار ثاني أكسيد الكربون."),
"v1204": ("Die Wasserstoffstrategie setzt auf Import aus sonnenreichen Ländern.", "استراتيجية الهيدروجين تراهن على الاستيراد من بلدان مشمسة."),
"v1205": ("Bei der Elektrolyse wird Wasser mit Strom in Wasserstoff und Sauerstoff getrennt.", "في التحليل الكهربائي يُفصل الماء بالكهرباء إلى هيدروجين وأكسجين."),
"v1206": ("Für den Braunkohletagebau wurden ganze Dörfer umgesiedelt.", "من أجل منجم الفحم المفتوح أُعيد إسكان قرى كاملة."),
"v1209": ("Die Akzeptanz für Windräder steigt, wenn die Gemeinde mitverdient.", "القبول الاجتماعي لعنفات الرياح يرتفع حين تكسب البلدية معها."),
"v1210": ("Beim Blackout fielen auch Ampeln und Geldautomaten aus.", "في الانقطاع الشامل تعطّلت إشارات المرور والصرّافات أيضاً."),
"v1211": ("Die Netzreserve springt nur an, wenn Wind und Sonne fehlen.", "احتياطي الشبكة لا يعمل إلا حين تغيب الرياح والشمس."),
"v1212": ("Der Flächenverbrauch durch neue Gewerbegebiete ist enorm.", "التهام الأرض بالمناطق الصناعية الجديدة هائل."),
"v1213": ("Überschüssigen Solarstrom kann man ins Netz einspeisen.", "الكهرباء الشمسية الفائضة يمكن ضخّها في الشبكة."),
"v1215": ("Nach der Wartung muss man das Kraftwerk langsam wieder hochfahren.", "بعد الصيانة يجب إعادة المحطة إلى العمل تدريجياً."),
"v1216": ("Bei zu viel Wind muss der Betreiber die Anlagen abregeln.", "عند الرياح الزائدة يجب على المشغّل كبح المنشآت."),
"v1217": ("Energieintensive Betriebe zahlen niedrigere Netzentgelte.", "المنشآت كثيفة الطاقة تدفع تعرفات شبكة أقل."),
"v1218": ("Wind und Sonne sind volatil, deshalb braucht man Speicher.", "الرياح والشمس متقلبتان، لذلك نحتاج مخازن."),
"v1219": ("Wasserkraft gilt als grundlastfähig, Solar nicht.", "الطاقة المائية تُعتبر قادرة على الحمل القاعدي، أما الشمسية فلا."),
"v1220": ("Große Batterien machen das Netz netzstabil, wenn die Frequenz schwankt.", "البطاريات الكبيرة تُثبّت الشبكة حين يتذبذب التردد."),
"v1221": ("Von Stromknappheit sprach man im Winter zum ersten Mal seit Jahrzehnten.", "عن ندرة الكهرباء تحدّث الناس في الشتاء لأول مرة منذ عقود."),
"v1222": ("Energiesouveränität heißt, nicht von einem einzigen Lieferanten abzuhängen.", "السيادة الطاقية تعني عدم الاعتماد على مورّد واحد."),
"v1223": ("Die Gasspeicher waren im November zu neunzig Prozent gefüllt.", "خزانات الغاز كانت في نوفمبر ممتلئة بنسبة تسعين بالمائة."),
"v1224": ("Jede fossile Subvention verzögert den Umbau um Jahre.", "كل دعم للوقود الأحفوري يؤخّر التحوّل سنوات."),
"v1225": ("Das Mindesthaltbarkeitsdatum ist kein Wegwerfdatum.", "تاريخ «يُفضَّل قبل» ليس تاريخ رمي."),
"v1226": ("Ein Drittel der Lebensmittelverschwendung passiert zu Hause.", "ثلث إسراف المأكولات يحدث في البيت."),
"v1227": ("Die Lebensmittelrettung holt abends Brot ab, das sonst weggeworfen würde.", "إنقاذ الطعام يجمع مساءً خبزاً كان سيُرمى."),
"v1228": ("Die Nährwerttabelle steht klein auf der Rückseite der Packung.", "جدول القيمة الغذائية مكتوب صغيراً على ظهر العبوة."),
"v1229": ("Der Nutri-Score zeigt mit fünf Farben, wie ausgewogen ein Produkt ist.", "المقياس اللوني يُظهر بخمسة ألوان مدى توازن المنتج."),
"v1230": ("Ein Geschmacksverstärker lässt billige Suppen intensiver schmecken.", "معزّز النكهة يجعل الحساء الرخيص أقوى طعماً."),
"v1231": ("Jeder Zusatzstoff muss auf der Zutatenliste stehen.", "كل مُضاف صناعي يجب أن يُذكر في قائمة المكونات."),
"v1232": ("Hinter jeder E-Nummer steckt ein geprüfter Zusatzstoff.", "وراء كل رقم E مُضاف مفحوص."),
"v1233": ("Der Süßstoff liefert Süße fast ohne Kalorien.", "المحلّي الصناعي يعطي حلاوة بلا سعرات تقريباً."),
"v1234": ("Palmöl steckt in Schokolade, Seife und Fertigpizza.", "زيت النخيل موجود في الشوكولاتة والصابون والبيتزا الجاهزة."),
"v1235": ("Eine Tierwohlabgabe würde Fleisch um wenige Cent teurer machen.", "ضريبة رفاهية الحيوان سترفع سعر اللحم بسنتات قليلة."),
"v1237": ("Eier aus Käfighaltung sind im Supermarkt kaum noch zu finden.", "بيض التربية في الأقفاص بالكاد يوجد في السوبرماركت الآن."),
"v1239": ("Das Biosiegel garantiert Mindeststandards, nicht Perfektion.", "الختم العضوي يضمن معايير دنيا لا الكمال."),
"v1240": ("Die Herkunftsangabe fehlt oft bei verarbeiteten Produkten.", "بيان المنشأ يغيب غالباً في المنتجات المصنّعة."),
"v1241": ("Die Siegelflut verwirrt mehr, als sie informiert.", "طوفان الأختام يربك أكثر مما يُعلم."),
"v1242": ("Ein Bauernhof auf der Packung ist Irreführung, wenn das Fleisch aus der Fabrik kommt.", "مزرعة على العبوة تضليل إذا كان اللحم من المصنع."),
"v1243": ("Die Abmahnung kam vom Anwalt eines Konkurrenten.", "الإنذار القانوني جاء من محامي منافس."),
"v1244": ("Aus Kulanz nahm der Laden den Pullover ohne Bon zurück.", "من باب الكرم استرجع المتجر البلوفر بلا إيصال."),
"v1246": ("Im Kleingedruckten steht die automatische Verlängerung.", "في الخط الصغير مكتوب التمديد التلقائي."),
"v1247": ("Die Abo-Falle beginnt mit einem kostenlosen Probemonat.", "فخ الاشتراك يبدأ بشهر تجريبي مجاني."),
"v1248": ("Der Fernseher war ein Lockvogel, im Laden gab es nur drei Stück.", "التلفاز كان طُعماً، في المتجر ثلاث قطع فقط."),
"v1249": ("Die Preistreiberei nach dem Sturm hat die Behörde geprüft.", "التسعير الجشع بعد العاصفة فحصته الإدارة."),
"v1250": ("Das Bundeskartellamt prüft, ob die Fusion den Wettbewerb schadet.", "مكتب مكافحة الكارتل يفحص إن كان الاندماج يضر بالمنافسة."),
"v1251": ("Die Lebensmittelinflation trifft Familien mit Kindern zuerst.", "تضخم أسعار الغذاء يصيب العائلات ذات الأطفال أولاً."),
"v1252": ("Die Kennzeichnungspflicht gilt auch für Allergene in Restaurants.", "إلزامية الوسم تسري أيضاً على مسببات الحساسية في المطاعم."),
"v1253": ("Nach der Rückrufaktion bekamen Kunden den Kaufpreis erstattet.", "بعد سحب المنتج استردّ الزبائن ثمن الشراء."),
"v1254": ("Der Rückruf betrifft nur Packungen mit diesem Datum.", "الاستدعاء يخص فقط العبوات بهذا التاريخ."),
"v1255": ("Mit der Musterfeststellungsklage klagen tausende Kunden gemeinsam.", "بالدعوى النموذجية يقاضي آلاف الزبائن معاً."),
"v1256": ("Beim Testkauf verkaufte der Laden Alkohol an eine Sechzehnjährige.", "في الشراء الاختباري باع المتجر كحولاً لفتاة في السادسة عشرة."),
"v1258": ("Die Haltbarkeit verlängert sich im Kühlschrank um mehrere Tage.", "مدة الصلاحية تطول في الثلاجة أياماً عدة."),
"v1259": ("Die Eigenmarke kommt oft aus derselben Fabrik wie das Markenprodukt.", "علامة المتجر تأتي غالباً من المصنع نفسه كمنتج الماركة."),
"v1260": ("Die Portionsgröße auf der Packung ist kleiner, als man wirklich isst.", "حجم الحصة على العبوة أصغر مما يأكله المرء فعلاً."),
"v1261": ("Der Zuckergehalt im Fruchtjoghurt überrascht viele Eltern.", "نسبة السكر في زبادي الفاكهة تفاجئ آباء كثيرين."),
"v1262": ("Die Verlockung an der Kasse sind Süßigkeiten in Kinderhöhe.", "الإغراء عند الصندوق حلويات على ارتفاع الأطفال."),
"v1263": ("Eine Mogelpackung ist halb leer und kostet wie eine volle.", "العبوة المخاتلة نصف فارغة وتكلّف كالممتلئة."),
"v1265": ("Verbraucherzentralen können Firmen wegen falscher Werbung abmahnen.", "مراكز حماية المستهلك يمكنها إنذار الشركات قانونياً بسبب إعلان كاذب."),
"v1266": ("Der Hersteller musste die Charge wegen Glassplittern zurückrufen.", "المصنّع اضطر لاستدعاء الدفعة بسبب شظايا زجاج."),
"v1267": ("Verderbliche Ware wie Fisch verkauft die Tafel noch am selben Tag.", "البضاعة القابلة للتلف كالسمك توزّعها مائدة المتطوعين في اليوم نفسه."),
"v1268": ("Gentechnisch veränderte Zutaten müssen gekennzeichnet werden.", "المكونات المعدّلة وراثياً يجب وسمها."),
"v1269": ("Linsen sind nährstoffreich und billiger als Fleisch.", "العدس غني بالعناصر وأرخص من اللحم."),
"v1270": ("Die geschönten Zahlen fielen erst dem Wirtschaftsprüfer auf.", "الأرقام المجمَّلة لم يلاحظها إلا مراجع الحسابات."),
"v1271": ("Verbraucherfeindliche Klauseln sind vor Gericht oft unwirksam.", "البنود المعادية للمستهلك غالباً باطلة أمام المحكمة."),
"v1411": ("Für Kinder ist schon eine kleine Menge dieses Mittels Gift.", "للأطفال حتى كمية صغيرة من هذه المادة سمّ."),
"v1272": ("Gute Stadtplanung denkt an Schatten, bevor die Hitze kommt.", "التخطيط الحضري الجيد يفكّر في الظل قبل أن يأتي الحر."),
"v1273": ("Der Bebauungsplan erlaubt hier höchstens vier Stockwerke.", "مخطط البناء يسمح هنا بأربعة طوابق كحد أقصى."),
"v1274": ("Im Flächennutzungsplan ist das Gelände als Gewerbe eingetragen.", "في مخطط استعمال الأرض تُسجَّل القطعة كمنطقة تجارية."),
"v1275": ("Gentrifizierung beginnt mit Cafés und endet mit Kündigungen.", "التطوير الطارد يبدأ بالمقاهي وينتهي بالإخلاءات."),
"v1276": ("Die Aufwertung des Viertels hat die Mieten verdoppelt.", "الارتقاء العمراني للحي ضاعف الإيجارات."),
"v1277": ("Die Milieuschutzsatzung verbietet Luxussanierungen im Viertel.", "لائحة حماية الوسط تمنع الترميمات الفاخرة في الحي."),
"v1278": ("Die Zweckentfremdung von Wohnungen als Ferienunterkunft ist genehmigungspflichtig.", "تحوير الشقق إلى مساكن سياحية يخضع للترخيص."),
"v1279": ("Der Mietspiegel zeigt, was in dieser Straße üblich ist.", "مرآة الإيجارات تُظهر ما هو معتاد في هذا الشارع."),
"v1280": ("Die Kappungsgrenze erlaubt maximal fünfzehn Prozent in drei Jahren.", "سقف الزيادة يسمح بخمسة عشر بالمائة كحد أقصى في ثلاث سنوات."),
"v1281": ("Die Wohnraumförderung bindet die Miete für zwanzig Jahre.", "تمويل الإسكان المشروط يقيّد الإيجار عشرين سنة."),
"v1282": ("Geschosswohnungsbau spart Fläche im Vergleich zum Einfamilienhaus.", "البناء الطابقي يوفّر الأرض مقارنة بمنزل العائلة الواحدة."),
"v1283": ("Bei der Nachverdichtung verschwindet oft der Spielplatz im Hof.", "في الحشو العمراني يختفي غالباً ملعب الفناء."),
"v1284": ("Die Skyline der Stadt besteht aus Kirchtürmen und drei Hochhäusern.", "خط أفق المدينة يتكوّن من أبراج كنائس وثلاثة أبراج سكنية."),
"v1285": ("Wegen des Denkmalschutzes dürfen die alten Fenster nicht ersetzt werden.", "بسبب حماية الأثر لا يجوز استبدال النوافذ."),
"v1286": ("Beim Bürgerentscheid stimmten sechzig Prozent gegen den Tunnel.", "في الاستفتاء المحلي صوّت ستون بالمائة ضد النفق."),
"v1287": ("Die Planfeststellung für die Trasse dauerte sieben Jahre.", "التحقيق التخطيطي للممر استغرق سبع سنوات."),
"v1288": ("Bürgerbeteiligung heißt mehr als ein Abend mit Folien im Rathaus.", "إشراك المواطنين يعني أكثر من أمسية بشرائح في البلدية."),
"v1289": ("Die Versiegelung des Bodens lässt Regen nicht mehr versickern.", "تعبيد التربة لا يترك المطر يتسرّب."),
"v1290": ("Die Frischluftschneise darf nicht bebaut werden.", "ممر الهواء النقي لا يجوز البناء فيه."),
"v1291": ("Der Hitzeaktionsplan sieht kühle Räume und Trinkbrunnen vor.", "مخطط الطوارئ الحرارية ينص على غرف باردة ونوافير شرب."),
"v1292": ("Stadtbegrünung kostet wenig und senkt die Temperatur um mehrere Grad.", "تخضير المدينة يكلّف قليلاً ويخفّض الحرارة درجات عدة."),
"v1293": ("Die Schwammstadt speichert Regen, statt ihn in den Kanal zu leiten.", "المدينة الإسفنجية تخزّن المطر بدل تصريفه في القناة."),
"v1295": ("Die Abwanderung junger Leute lässt das Dorf altern.", "نزوح الشباب يجعل القرية تشيخ."),
"v1296": ("In der Kleinstadt kennt der Bäcker noch jeden Kunden beim Namen.", "في المدينة الصغيرة ما زال الخباز يعرف كل زبون باسمه."),
"v1297": ("Das Stadt-Land-Gefälle zeigt sich beim Internet und beim Busfahrplan.", "هوّة المدينة والريف تظهر في الإنترنت وجدول الحافلات."),
"v1298": ("Nach der Verkehrsberuhigung spielen wieder Kinder auf der Straße.", "بعد تهدئة المرور عاد الأطفال يلعبون في الشارع."),
"v1299": ("Parkraumbewirtschaftung heißt: Parken kostet, auch für Anwohner.", "إدارة أرصفة الوقوف تعني: الوقوف يكلّف حتى السكان."),
"v1300": ("In der autofreien Zone liefern Händler morgens vor zehn.", "في المنطقة الخالية من السيارات يوصّل التجار صباحاً قبل العاشرة."),
"v1301": ("Das Quartiersmanagement organisiert das Straßenfest im Juni.", "إدارة الحي تنظّم مهرجان الشارع في يونيو."),
"v1302": ("Der Leerstand im Zentrum ärgert die Nachbarn seit Jahren.", "المباني الفارغة في المركز تزعج الجيران منذ سنوات."),
"v1303": ("Die Hausbesetzung endete nach zwei Wochen mit einem Mietvertrag.", "احتلال المبنى انتهى بعد أسبوعين بعقد إيجار."),
"v1304": ("Mit dem Vorkaufsrecht kann die Stadt Häuser vor Spekulanten kaufen.", "بحق الشراء الأول تستطيع المدينة شراء المباني قبل المضاربين."),
"v1305": ("Verdrängung passiert leise: Der Kiosk schließt, die Miete steigt.", "الإزاحة تحدث بصمت: الكشك يغلق والإيجار يرتفع."),
"v1306": ("Die Mietpreisbremse gilt nur bei Neuvermietung, nicht bei Neubau.", "كبح الإيجار يسري فقط عند التأجير الجديد لا في البناء الجديد."),
"v1307": ("Über die Modernisierungsumlage zahlt der Mieter die neue Heizung mit.", "عبر تحميل الترميم يشارك المستأجر في دفع التدفئة الجديدة."),
"v1309": ("Die Belegungsbindung endet nach fünfzehn Jahren, dann steigt die Miete.", "قيد التخصيص ينتهي بعد خمس عشرة سنة ثم يرتفع الإيجار."),
"v1310": ("Die Stadt will das Viertel verdichten, ohne Grünflächen zu opfern.", "المدينة تريد حشو الحي بالبناء دون التضحية بالمساحات الخضراء."),
"v1311": ("Das Haus wurde energetisch saniert, die Miete stieg um zwölf Prozent.", "المبنى رُمّم طاقياً وارتفع الإيجار اثني عشر بالمائة."),
"v1313": ("Wer ein Viertel aufwertet, muss an die alten Mieter denken.", "من يرتقي بحي عليه التفكير في المستأجرين القدامى."),
"v1314": ("Das Viertel ist dicht bebaut, dafür ist alles zu Fuß erreichbar.", "الحي متلاصق البنيان، وبالمقابل كل شيء في متناول المشي."),
"v1315": ("Reihenhäuser sind flächensparender als freistehende Häuser.", "البيوت المتلاصقة أوفر للأرض من المنازل المنفصلة."),
"v1316": ("In der Neubausiedlung fehlt noch die Bushaltestelle.", "في الضاحية الحديثة ما زال موقف الحافلة ناقصاً."),
"v1317": ("Das Fachkräfteeinwanderungsgesetz erleichtert die Anerkennung von Abschlüssen.", "قانون استقدام الكوادر يسهّل الاعتراف بالشهادات."),
"v1318": ("Mit der Blauen Karte darf Karim als Ingenieur in Deutschland arbeiten.", "بالبطاقة الزرقاء يمكن لكريم العمل مهندساً في ألمانيا."),
"v1319": ("Im Punktesystem zählen Alter, Sprache und Berufserfahrung.", "في نظام النقاط يُحتسب العمر واللغة والخبرة المهنية."),
"v1320": ("Die Gleichwertigkeitsprüfung des Diploms dauerte drei Monate.", "فحص معادلة الشهادة استغرق ثلاثة أشهر."),
"v1321": ("Nach der Nachqualifizierung von zwölf Monaten gilt der Abschluss voll.", "بعد التأهيل اللاحق اثني عشر شهراً تُعتمد الشهادة كاملة."),
"v1322": ("Der Integrationskurs umfasst Sprache und einen Orientierungsteil.", "دورة الاندماج تشمل اللغة وجزءاً توجيهياً."),
"v1323": ("Im Wertekurs geht es um Grundgesetz, Alltag und Behörden.", "في دورة القيم يدور الحديث عن القانون الأساسي والحياة اليومية والإدارات."),
"v1324": ("Die Optionspflicht zwang junge Leute früher, sich für einen Pass zu entscheiden.", "خيار الجنسية أجبر الشباب سابقاً على اختيار جواز واحد."),
"v1325": ("Mit einer Duldung darf man bleiben, aber kaum planen.", "بالتحمّل المؤقت يمكنك البقاء لكن بالكاد التخطيط."),
"v1326": ("Die Niederlassungserlaubnis bekommt man nach fünf Jahren und B1.", "إذن الإقامة الدائم يُمنح بعد خمس سنوات ومستوى B1."),
"v1327": ("Der Familiennachzug setzt ausreichend Wohnraum voraus.", "لحاق الأسرة يشترط مسكناً كافياً."),
"v1329": ("Krieg ist die häufigste Fluchtursache, Dürre wird die zweite.", "الحرب أكثر أسباب اللجوء شيوعاً، والجفاف يصبح الثاني."),
"v1330": ("In der Asylunterkunft teilen sich vier Menschen ein Zimmer.", "في مأوى اللجوء يتقاسم أربعة أشخاص غرفة."),
"v1331": ("Die dezentrale Unterbringung in Wohnungen erleichtert das Ankommen.", "التوزيع اللامركزي في شقق يسهّل الاستقرار."),
"v1332": ("Wegen der Residenzpflicht darf er den Landkreis nicht verlassen.", "بسبب قيد الإقامة الجغرافي لا يجوز له مغادرة المقاطعة."),
"v1333": ("Ohne Arbeitserlaubnis darf der Betrieb ihn nicht einstellen.", "بلا رخصة عمل لا يجوز للمنشأة توظيفه."),
"v1334": ("Der Zweitspracherwerb gelingt Kindern schneller als Erwachsenen.", "اكتساب اللغة الثانية ينجح لدى الأطفال أسرع من البالغين."),
"v1335": ("Bei der Sprachmittlung im Amt half eine ehrenamtliche Übersetzerin.", "في الترجمة الوسيطة بالدائرة ساعدت مترجمة متطوعة."),
"v1336": ("Die Sensibilisierung der Lehrkräfte begann mit einem Workshop.", "إيقاظ حساسية المعلّمين بدأ بورشة عمل."),
"v1337": ("Willkommenskultur zeigt sich am Bahnhof und im Jobcenter gleichermaßen.", "ثقافة الترحيب تظهر في المحطة ومكتب العمل بالقدر نفسه."),
"v1338": ("Über den Begriff Leitkultur wird seit Jahren gestritten.", "حول مصطلح الثقافة الموجِّهة يدور خلاف منذ سنوات."),
"v1339": ("Das Wort Parallelgesellschaft sagt mehr über die Angst als über das Viertel.", "كلمة مجتمع الموازاة تقول عن الخوف أكثر مما تقول عن الحي."),
"v1340": ("Eine Quotelung soll verhindern, dass eine Schule alle Neuankömmlinge aufnimmt.", "توزيع الحصص يهدف لمنع أن تستقبل مدرسة واحدة كل القادمين الجدد."),
"v1341": ("Der Migrationsbeirat berät den Stadtrat, entscheidet aber nicht.", "مجلس شؤون المهاجرين ينصح مجلس المدينة لكنه لا يقرر."),
"v1342": ("Das Herkunftsland steht in jedem Formular, der Beruf selten.", "البلد الأصلي مذكور في كل استمارة، والمهنة نادراً."),
"v1343": ("Ihre Migrationsgeschichte reicht bis zu den Großeltern zurück.", "سيرة هجرتها تمتد إلى الأجداد."),
"v1344": ("Mit guter Bleibeperspektive darf man früher am Sprachkurs teilnehmen.", "مع أفق بقاء جيد يمكن المشاركة في دورة اللغة مبكراً."),
"v1345": ("Die Ausbildungsduldung schützt Azubis vor Abschiebung während der Lehre.", "تحمّل التدريب يحمي المتدربين من الإبعاد أثناء التكوين."),
"v1346": ("Die Vorrangprüfung wurde für viele Berufe abgeschafft.", "فحص الأولوية أُلغي لمهن كثيرة."),
"v1347": ("Bei der Einbürgerungsfeier bekam jeder eine Urkunde und ein Grundgesetz.", "في حفل التجنيس حصل كل واحد على شهادة ونسخة من القانون الأساسي."),
"v1348": ("Assimilation verlangt Aufgabe, Integration verlangt Teilnahme.", "الاستذواب يطلب التخلّي، والاندماج يطلب المشاركة."),
"v1349": ("Die Mehrheitsgesellschaft merkt selten, dass sie Regeln setzt.", "مجتمع الأكثرية نادراً ما يلاحظ أنه يضع القواعد."),
"v1350": ("Die Zuwanderungsstatistik zählt Zuzüge, nicht Menschen, die bleiben.", "إحصاء الهجرة يعدّ الوافدين لا من يبقون."),
"v1352": ("Sie hat sich schnell in das Team eingefügt, ohne sich zu verbiegen.", "اندمجت بسرعة في الفريق دون أن تتنازل عن نفسها."),
"v1353": ("Ein Verein integriert schneller als jeder Kurs.", "الجمعية تدمج أسرع من أي دورة."),
"v1354": ("Ein Viertel der Belegschaft ist zugewandert, meist aus drei Ländern.", "ربع الطاقم مهاجرون، من ثلاثة بلدان غالباً."),
"v1355": ("Nach dem Krieg waren viele Familien jahrelang heimatlos.", "بعد الحرب كانت عائلات كثيرة بلا وطن لسنوات."),
"v1356": ("Ihre Bildungskarriere begann mit einer Patenschaft in der dritten Klasse.", "مسارها التعليمي بدأ بإرشاد في الصف الثالث."),
"v1357": ("Zweitsprachigkeit ist ein Vorteil, den Schulen noch zu selten nutzen.", "ثنائية اللغة ميزة ما زالت المدارس نادراً ما تستغلها."),
"v1358": ("Der Bolzplatz ist die wichtigste Begegnungszone im Viertel.", "ملعب الحي هو أهم منطقة لقاء فيه."),
"v1359": ("Erinnerungskultur zeigt sich in Schulbüchern, Straßennamen und Feiertagen.", "ثقافة التذكّر تظهر في الكتب المدرسية وأسماء الشوارع والأعياد."),
"v1360": ("Das Gedenken an die Opfer findet jedes Jahr am selben Ort statt.", "إحياء ذكرى الضحايا يُقام كل سنة في المكان نفسه."),
"v1361": ("Am Volkstrauertag bleiben viele Geschäfte geschlossen.", "في يوم الحداد الوطني تبقى متاجر كثيرة مغلقة."),
"v1362": ("Ein Stolperstein vor dem Haus nennt Namen, Geburtsjahr und Schicksal.", "حجر العثرة أمام المنزل يذكر الاسم وسنة الميلاد والمصير."),
"v1363": ("Das Mahnmal im Zentrum soll nicht schön sein, sondern erinnern.", "النصب التحذيري في المركز ليس مقصوداً أن يكون جميلاً بل مذكِّراً."),
"v1364": ("Die Gedenkstätte bietet Führungen für Schulklassen an.", "موقع التذكير يقدّم جولات للصفوف المدرسية."),
"v1365": ("Wiedergutmachung kann Verlust nicht ersetzen, nur anerkennen.", "جبر الضرر لا يعوّض الفقد بل يعترف به فقط."),
"v1366": ("Die Reparationen wurden über Jahrzehnte in Raten gezahlt.", "التعويضات الحربية دُفعت على أقساط عبر عقود."),
"v1367": ("Die Entnazifizierung stützte sich auf Fragebögen und Zeugen.", "نزع النازية اعتمد على استبيانات وشهود."),
"v1368": ("Als Mitläufer galt, wer mitmachte, ohne selbst zu entscheiden.", "المنساق هو من شارك دون أن يقرر بنفسه."),
"v1369": ("Die Frage der Täterschaft wurde in vielen Familien nie gestellt.", "سؤال فاعلية الجناة لم يُطرح في عائلات كثيرة قط."),
"v1370": ("Die Schuldfrage trennt zwischen Verantwortung und Erbe.", "سؤال الذنب يفصل بين المسؤولية والإرث."),
"v1371": ("Das Konzept der Kollektivschuld lehnen die meisten Historiker ab.", "مفهوم الذنب الجماعي يرفضه معظم المؤرخين."),
"v1372": ("Der Zeitzeuge sprach zwei Stunden, ohne einmal auf die Uhr zu sehen.", "شاهد العصر تحدّث ساعتين دون أن ينظر إلى الساعة مرة."),
"v1373": ("Das Zeitzeugeninterview wurde für das Archiv aufgezeichnet.", "مقابلة الشاهد سُجّلت للأرشيف."),
"v1374": ("Nach der Gedenkminute las eine Schülerin die Namen vor.", "بعد دقيقة الصمت قرأت تلميذة الأسماء."),
"v1375": ("Verharmlosung beginnt bei der Wortwahl, nicht bei der Leugnung.", "التصغير المتعمد يبدأ باختيار الكلمات لا بالإنكار."),
"v1376": ("Relativierung klingt wie Vergleich, wirkt aber wie Entschuldigung.", "المقارنة المُغسِلة تبدو مقارنة لكنها تعمل كتبرير."),
"v1377": ("Den Schlussstrich fordern vor allem jene, die nichts erlebt haben.", "خط النهاية يطالب به خصوصاً من لم يعيشوا شيئاً."),
"v1378": ("Erinnerungsarbeit an Schulen braucht Zeit im Lehrplan, nicht nur Projekttage.", "عمل التذكّر في المدارس يحتاج وقتاً في المنهج لا أيام مشاريع فقط."),
"v1379": ("Das Gedenkritual mit Kranz und Rede wirkt auf Jugendliche oft fern.", "طقس الإحياء بالإكليل والخطاب يبدو للشباب بعيداً غالباً."),
"v1380": ("Die Friedliche Revolution begann mit Kerzen und Gebeten.", "الثورة السلمية بدأت بالشموع والصلوات."),
"v1381": ("Die Montagsdemonstration wuchs von Woche zu Woche.", "مسيرة الاثنين كبرت أسبوعاً بعد أسبوع."),
"v1382": ("Die Stasi-Unterlagen kann man auf Antrag einsehen.", "ملفات الشرطة السرية يمكن الاطلاع عليها بطلب."),
"v1383": ("Vergangenheitsbewältigung ist Arbeit, kein Datum im Kalender.", "معالجة الماضي عمل لا تاريخ في التقويم."),
"v1384": ("Geschichtspolitik entscheidet, welche Gedenkstätte Geld bekommt.", "سياسة التاريخ تقرر أي موقع تذكير يحصل على المال."),
"v1385": ("Die Restitution des Gemäldes an die Erben dauerte zehn Jahre.", "إرجاع اللوحة إلى الورثة استغرق عشر سنوات."),
"v1386": ("Raubkunst hängt bis heute in manchen Museen.", "فن السلب ما زال معلّقاً حتى اليوم في بعض المتاحف."),
"v1387": ("Die Provenienzforschung prüft, wem ein Bild vor dem Krieg gehörte.", "بحث المنشأ يفحص لمن كانت اللوحة قبل الحرب."),
"v1388": ("Die Umbenennung der Straße kostete auch die Anwohner Geld.", "إعادة تسمية الشارع كلّفت السكان مالاً أيضاً."),
"v1389": ("Die Namensdebatte um die Kaserne dauert seit zwei Jahren.", "سجال الأسماء حول الثكنة مستمر منذ سنتين."),
"v1390": ("Die Kolonialgeschichte kommt im Schulbuch oft nur auf einer Seite vor.", "التاريخ الاستعماري لا يظهر في الكتاب المدرسي غالباً إلا في صفحة."),
"v1391": ("Die Opferperspektive fehlt in vielen älteren Dokumentationen.", "منظور الضحية يغيب في كثير من الوثائقيات القديمة."),
"v1392": ("Die Täterforschung fragt, wie normale Menschen mitmachten.", "علم الجناة يسأل كيف شارك أناس عاديون."),
"v1393": ("Mein Großvater kam als Vertriebener mit einem Koffer in die Stadt.", "جدي جاء إلى المدينة مُهجَّراً بحقيبة واحدة."),
"v1394": ("Die Nachwirkungsdebatte zeigt: Die Grenze ist im Kopf noch nicht weg.", "جدل ما بعد الانقسام يُظهر: الحدود لم تزُل من الأذهان بعد."),
"v1395": ("Am Sonntag gedenkt die Stadt der Opfer des Hochwassers.", "يوم الأحد تستذكر المدينة ضحايا الفيضان."),
"v1397": ("Der Verein will seine eigene Geschichte aufarbeiten, mit Historikern.", "الجمعية تريد استقصاء تاريخها الخاص مع مؤرخين."),
"v1398": ("Wer Verbrechen relativieren will, beginnt oft mit „aber“.", "من يريد المقارنة لغسل الجرائم يبدأ غالباً بـ«لكن»."),
"v1399": ("Die Entscheidung über den Straßennamen ist erinnerungspolitisch heikel.", "قرار اسم الشارع حساس من زاوية سياسة الذاكرة."),
}
