# -*- coding: utf-8 -*-
"""exampleDe/exampleAr Batch 1: A1 (44) + A2 (87) + B1 (90). Regel: Wort (oder flektierte Form) kommt wörtlich vor, 5–14 Wörter, Niveau der Karte."""
B = {
# ---- A1 ----
"v013": ("Meine Tochter geht jeden Morgen um acht Uhr in die Schule.", "ابنتي تذهب إلى المدرسة كل صباح في الثامنة."),
"v016": ("Die Stadt ist klein, aber alles ist nah.", "المدينة صغيرة لكن كل شيء قريب."),
"v018": ("Wie ist Ihre Adresse? – Parkstraße 12, in Berlin.", "ما هو عنوانك؟ – شارع بارك 12، في برلين."),
"v019": ("Kannst du mir bitte deine Telefonnummer geben?", "هل يمكنك إعطائي رقم هاتفك من فضلك؟"),
"v020": ("Ich möchte nur eins, bitte: ein Brötchen.", "أريد واحداً فقط، من فضلك: خبزة صغيرة."),
"v021": ("Das Brot kostet fünf Euro? Das ist teuer!", "الخبز بخمسة يورو؟ هذا غالٍ!"),
"v022": ("Wir treffen uns um zehn Uhr vor dem Bahnhof.", "نلتقي في العاشرة أمام المحطة."),
"v023": ("Die Fahrt dauert zwanzig Minuten mit dem Bus.", "الرحلة تستغرق عشرين دقيقة بالحافلة."),
"v024": ("Der Kurs kostet hundert Euro pro Monat.", "الدورة تكلّف مائة يورو في الشهر."),
"v145": ("Danke für das Gespräch, auf Wiedersehen, Frau Müller!", "شكراً على الحديث، إلى اللقاء سيدة مولر!"),
"v146": ("Entschuldigung, wo ist hier die Toilette?", "عفواً، أين الحمّام هنا؟"),
"v147": ("Mein Name ist Youssef. Und wie heißen Sie?", "اسمي يوسف. وما اسمك حضرتك؟"),
"v148": ("Ich habe eine Frage: Wann beginnt der Kurs?", "عندي سؤال: متى تبدأ الدورة؟"),
"v150": ("Kann ich mit Karte bezahlen oder nur bar?", "هل يمكنني الدفع بالبطاقة أم نقداً فقط؟"),
"v025": ("Am Freitag isst meine Familie immer zusammen.", "يوم الجمعة تأكل عائلتي معاً دائماً."),
"v026": ("Meine Mutter kocht sehr gut, besonders Couscous.", "أمي تطبخ جيداً جداً، خاصة الكسكسي."),
"v027": ("Mein Vater ist Lehrer und arbeitet in Sfax.", "أبي معلّم ويعمل في صفاقس."),
"v028": ("Mein Bruder wohnt noch bei meinen Eltern.", "أخي ما زال يسكن عند والديّ."),
"v029": ("Meine Schwester ist siebzehn und geht in die Schule.", "أختي في السابعة عشرة وتذهب إلى المدرسة."),
"v030": ("Hast du Geschwister? – Ja, einen Bruder und zwei Schwestern.", "هل لديك إخوة؟ – نعم، أخ وأختان."),
"v031": ("Karim ist mein bester Freund aus der Schulzeit.", "كريم أعزّ صديق لي من أيام المدرسة."),
"v032": ("Das Haus hat einen kleinen Garten hinter der Küche.", "المنزل له حديقة صغيرة خلف المطبخ."),
"v033": ("Die Wohnung hat zwei Zimmer und ist im dritten Stock.", "الشقة فيها غرفتان وهي في الطابق الثالث."),
"v034": ("Mein Zimmer ist klein, aber sehr ruhig.", "غرفتي صغيرة لكنها هادئة جداً."),
"v035": ("In der Küche steht ein großer Tisch.", "في المطبخ طاولة كبيرة."),
"v039": ("Zum Frühstück trinke ich immer einen Tee mit Milch.", "على الفطور أشرب دائماً شاياً بالحليب."),
"v040": ("Mein Alltag ist einfach: Arbeit, Deutschkurs, schlafen.", "يومياتي بسيطة: عمل، دورة ألمانية، نوم."),
"v041": ("Entschuldigung, haben Sie die Uhrzeit? – Es ist halb drei.", "عفواً، هل تعرف كم الساعة؟ – الثانية والنصف."),
"v042": ("Heute ist Samstag, und ich habe frei.", "اليوم السبت وعندي عطلة."),
"v043": ("Morgen fahre ich mit dem Zug nach Hamburg.", "غداً أسافر بالقطار إلى هامبورغ."),
"v044": ("Gestern war ich beim Arzt, heute geht es mir besser.", "أمس كنت عند الطبيب، واليوم أنا أفضل."),
"v045": ("Das Frühstück im Hotel ist von sieben bis zehn Uhr.", "الفطور في الفندق من السابعة إلى العاشرة."),
"v046": ("Zum Mittagessen gibt es heute Reis mit Gemüse.", "على الغداء اليوم أرز مع خضار."),
"v047": ("Ein Kaffee kostet hier zwei Euro fünfzig.", "القهوة هنا بيورهين ونصف."),
"v048": ("Möchtest du Tee oder Kaffee? – Tee, bitte, ohne Zucker.", "أتريد شاياً أم قهوة؟ – شاي من فضلك، بلا سكر."),
"v151": ("Das Abendessen ist um sieben Uhr fertig.", "العشاء يكون جاهزاً في السابعة."),
"v152": ("Unser Hund heißt Max und ist drei Jahre alt.", "كلبنا اسمه ماكس وعمره ثلاث سنوات."),
"v153": ("Die Katze schläft den ganzen Tag auf dem Sofa.", "القطة تنام طوال اليوم على الأريكة."),
"v154": ("Das Kind spielt im Garten mit dem Ball.", "الطفل يلعب في الحديقة بالكرة."),
"v155": ("Amir steht sehr früh auf, schon um fünf Uhr.", "أمير يستيقظ باكراً جداً، في الخامسة."),
"v156": ("Am Wochenende gehe ich auf den Markt und in den Park.", "في عطلة نهاية الأسبوع أذهب إلى السوق والحديقة."),
"v683": ("Der Einkauf für die Woche kostet etwa fünfzig Euro.", "تسوّق الأسبوع يكلّف حوالي خمسين يورو."),
"v936": ("Ich bin froh, dass du gekommen bist!", "أنا مسرور أنك جئت!"),
"v937": ("Die Kinder springen vor Freude, denn morgen sind Ferien.", "الأطفال يقفزون من الفرح لأن العطلة غداً."),
# ---- A2 ----
"v049": ("Der Arzt sagt, ich soll zwei Tage zu Hause bleiben.", "الطبيب يقول إنه عليّ البقاء في البيت يومين."),
"v051": ("Seit gestern tut mir der Kopf weh.", "منذ أمس يؤلمني رأسي."),
"v052": ("Nach dem Essen hatte er starke Schmerzen im Bauch.", "بعد الأكل شعر بألم شديد في بطنه."),
"v053": ("Nehmen Sie die Medizin dreimal am Tag nach dem Essen.", "تناول الدواء ثلاث مرات يومياً بعد الأكل."),
"v054": ("Die Reise nach München dauert ungefähr vier Stunden.", "الرحلة إلى ميونيخ تستغرق حوالي أربع ساعات."),
"v055": ("Der Bahnhof ist gegenüber vom Hotel, fünf Minuten zu Fuß.", "المحطة مقابل الفندق، خمس دقائق مشياً."),
"v056": ("Eine Fahrkarte zweiter Klasse nach Köln, bitte.", "تذكرة درجة ثانية إلى كولن من فضلك."),
"v057": ("In Frankfurt müssen Sie umsteigen, Gleis fünf.", "في فرانكفورت عليك تبديل القطار، الرصيف خمسة."),
"v058": ("Ich möchte einen Tisch für vier Personen reservieren.", "أريد حجز طاولة لأربعة أشخاص."),
"v059": ("Das Hotel liegt im Zentrum, direkt am Bahnhof.", "الفندق في المركز، قرب المحطة مباشرة."),
"v060": ("Haben Sie eine Reservierung? – Ja, auf den Namen Haddad.", "هل لديك حجز؟ – نعم، باسم حدّاد."),
"v061": ("Wir sparen jeden Monat hundert Euro für den Urlaub.", "ندّخر كل شهر مائة يورو للعطلة."),
"v062": ("Mit dem Fahrrad zur Arbeit fahren ist gut für die Umwelt.", "الذهاب إلى العمل بالدراجة جيد للبيئة."),
"v063": ("Das Wetter ist heute schlecht: Regen und nur acht Grad.", "الطقس اليوم سيّئ: مطر وثماني درجات فقط."),
"v064": ("Nimm einen Schirm mit, es soll am Abend regnen.", "خذ مظلة معك، يُتوقّع أن تمطر مساءً."),
"v065": ("Im Frühling blühen die Bäume im Park.", "في الربيع تُزهر الأشجار في الحديقة."),
"v066": ("Im Sommer fahren wir zwei Wochen an die Ostsee.", "في الصيف نسافر أسبوعين إلى بحر البلطيق."),
"v067": ("Im Herbst wird es früh dunkel und oft windig.", "في الخريف يحلّ الظلام باكراً وغالباً ما يكون الجو عاصفاً."),
"v068": ("Im Winter trainieren wir in der Halle, draußen ist es zu kalt.", "في الشتاء نتدرّب في القاعة، فالخارج بارد جداً."),
"v069": ("Am Samstag putzen wir zusammen die Küche und das Bad.", "يوم السبت ننظّف معاً المطبخ والحمّام."),
"v070": ("Ich kaufe immer samstags auf dem Markt ein.", "أتسوّق دائماً يوم السبت في السوق."),
"v071": ("Das Geschäft öffnet um neun und schließt um zwanzig Uhr.", "المتجر يفتح في التاسعة ويغلق في الثامنة مساءً."),
"v072": ("Heute gibt es ein Angebot: Äpfel für ein Euro das Kilo.", "اليوم يوجد عرض: التفاح بيورو للكيلو."),
"v157": ("Ich habe morgen um zehn einen Termin beim Zahnarzt.", "لديّ غداً في العاشرة موعد عند طبيب الأسنان."),
"v158": ("Auf der Rechnung steht ein Mineralwasser, das wir nicht bestellt haben.", "في الفاتورة مياه معدنية لم نطلبها."),
"v159": ("Der Zug hatte fünfzig Minuten Verspätung.", "القطار تأخّر خمسين دقيقة."),
"v160": ("Sie können das Gepäck an der Rezeption lassen.", "يمكنك ترك الأمتعة عند الاستقبال."),
"v162": ("In der Nacht war es sehr laut, ich habe kaum geschlafen.", "في الليل كان الضجيج شديداً، بالكاد نمت."),
"v073": ("Meiner Meinung nach ist Homeoffice eine gute Lösung.", "في رأيي العمل من البيت حلّ جيد."),
"v074": ("Ich habe das Gefühl, dass der Kurs zu schnell ist.", "عندي شعور بأن الدورة سريعة جداً."),
"v077": ("Ich ärgere mich über den Lärm der Nachbarn.", "أنزعج من ضجيج الجيران."),
"v078": ("Vor der Prüfung hatte ich große Angst.", "قبل الامتحان كان عندي خوف كبير."),
"v079": ("Nach dem Streit haben sie zwei Tage nicht gesprochen.", "بعد الشجار لم يتكلّما يومين."),
"v081": ("Danke für die Einladung zu deinem Geburtstag!", "شكراً على الدعوة إلى عيد ميلادك!"),
"v083": ("Am Samstag feiert Mehdi seinen dreißigsten Geburtstag.", "يوم السبت يحتفل مهدي بعيد ميلاده الثلاثين."),
"v084": ("Ich habe zwei Jahre Erfahrung als Techniker.", "لديّ خبرة سنتين كفنّي."),
"v085": ("Die Zeitung berichtet über den Streik bei der Bahn.", "الجريدة تُبلّغ عن إضراب السكك الحديدية."),
"v086": ("Erzähl mir von deinem ersten Tag in Deutschland!", "احكِ لي عن يومك الأول في ألمانيا!"),
"v087": ("Können Sie den Mann bitte genau beschreiben?", "هل يمكنك وصف الرجل بدقّة من فضلك؟"),
"v088": ("Das war keine Absicht, entschuldige bitte!", "لم يكن ذلك بقصد، اعذرني من فضلك!"),
"v089": ("Mein Plan für Sonntag: lange schlafen und lesen.", "خطتي ليوم الأحد: نوم طويل وقراءة."),
"v090": ("Ich hoffe, dass der Zug pünktlich kommt.", "آمل أن يصل القطار في موعده."),
"v091": ("Die Entscheidung war nicht leicht, aber jetzt bin ich sicher.", "القرار لم يكن سهلاً، لكنني الآن متأكّد."),
"v092": ("Ich empfehle dir das Café am Bahnhof, der Kuchen ist super.", "أنصحك بالمقهى قرب المحطة، الكعك ممتاز."),
"v093": ("Hast du die Nachricht gelesen? Der Kurs fällt heute aus.", "هل قرأت الخبر؟ الدورة ملغاة اليوم."),
"v094": ("Mein Vater liest jeden Morgen die Zeitung beim Frühstück.", "أبي يقرأ الجريدة كل صباح على الفطور."),
"v095": ("Ohne Internet kann ich meine Hausaufgaben nicht schicken.", "بلا إنترنت لا أستطيع إرسال واجباتي."),
"v096": ("Was sind Sie von Beruf? – Ich bin Ingenieurin.", "ما مهنتك؟ – أنا مهندسة."),
"v163": ("Ich habe einen Vorschlag: Treffen wir uns am Samstag?", "عندي اقتراح: نلتقي يوم السبت؟"),
"v164": ("Die Regel in unserer WG: Jeder putzt einmal pro Woche.", "القاعدة في سكننا المشترك: كل واحد ينظّف مرة أسبوعياً."),
"v165": ("Das ist eine gute Chance für einen neuen Job.", "هذه فرصة جيدة لعمل جديد."),
"v166": ("Ich erwarte morgen ein Paket, bitte nehmen Sie es an.", "أنتظر طرداً غداً، من فضلك استلمه."),
"v167": ("Ich habe noch keine Antwort auf meine E-Mail bekommen.", "لم أتلقَّ بعد إجابة على إيميلي."),
"v168": ("Die Strecke von Tunis nach Sousse dauert zwei Stunden.", "المسافة من تونس إلى سوسة تستغرق ساعتين."),
"v566": ("Meine Kollegin hilft mir oft bei schwierigen E-Mails.", "زميلتي تساعدني كثيراً في الإيميلات الصعبة."),
"v571": ("Sie ist sehr fleißig und lernt jeden Abend zwei Stunden.", "هي مجتهدة جداً وتدرس كل مساء ساعتين."),
"v582": ("Netto bleiben mir etwa 1.800 Euro im Monat.", "الصافي الذي يبقى لي حوالي 1800 يورو شهرياً."),
"v583": ("Das Gehalt ist 2.500 Euro brutto, also vor den Abzügen.", "الراتب 2500 يورو إجمالي، أي قبل الخصومات."),
"v592": ("Er war ein halbes Jahr arbeitslos, jetzt hat er eine Stelle.", "كان عاطلاً عن العمل نصف سنة، والآن لديه وظيفة."),
"v602": ("In Deutschland recyceln wir Papier, Glas und Plastik getrennt.", "في ألمانيا نعيد تدوير الورق والزجاج والبلاستيك بشكل منفصل."),
"v607": ("Können Sie das Geschenk bitte schön verpacken?", "هل يمكنك تغليف الهدية بشكل جميل من فضلك؟"),
"v662": ("Das Zimmer war günstig: nur vierzig Euro pro Nacht.", "الغرفة كانت مناسبة الثمن: أربعون يورو فقط لليلة."),
"v668": ("Ich möchte ein Konto bei Ihrer Bank eröffnen.", "أريد فتح حساب في بنككم."),
"v679": ("Die Verkäuferin zeigt mir eine größere Größe.", "البائعة تُريني مقاساً أكبر."),
"v682": ("Auf der Einkaufsliste stehen Brot, Milch, Eier und Käse.", "في قائمة التسوق خبز وحليب وبيض وجبن."),
"v685": ("Das Brot aus der Bäckerei hat eine bessere Qualität.", "خبز المخبز جودته أفضل."),
"v725": ("Ich habe das Ticket online gekauft, es ist auf dem Handy.", "اشتريت التذكرة عبر الإنترنت، وهي على الهاتف."),
"v728": ("Entschuldigung, ich habe mich verspätet, der Bus kam nicht.", "عذراً، تأخّرت، فالحافلة لم تأتِ."),
"v731": ("Wegen der Baustelle ist die Straße bis Freitag gesperrt.", "بسبب ورشة الطريق الشارع مغلق حتى الجمعة."),
"v735": ("Gehen Sie geradeaus bis zur Ampel, dann rechts.", "امشِ مستقيماً حتى إشارة المرور ثم يميناً."),
"v760": ("Ich mache gerade den Führerschein, nächste Woche ist die Prüfung.", "أنا أحضّر رخصة السياقة حالياً، والامتحان الأسبوع القادم."),
"v764": ("Mein Onkel hat mich am Flughafen in Frankfurt abgeholt.", "عمّي أخذني من مطار فرانكفورت."),
"v781": ("Für die Anmeldung müssen Sie zum Amt gehen.", "للتسجيل يجب أن تذهب إلى الدائرة الحكومية."),
"v822": ("Nach dem Urteil kam der Mann für zwei Jahre ins Gefängnis.", "بعد الحكم دخل الرجل السجن لسنتين."),
"v849": ("Nach der Vorlesung gibt es eine Übung mit Aufgaben.", "بعد المحاضرة توجد حصة تطبيقية بمسائل."),
"v855": ("In Deutschland ist die Note eins die beste.", "في ألمانيا الدرجة واحد هي الأفضل."),
"v863": ("In der Bibliothek kann man Bücher für vier Wochen ausleihen.", "في المكتبة يمكن استعارة الكتب لأربعة أسابيع."),
"v887": ("Meine Aussprache wird besser, wenn ich laut lese.", "نطقي يتحسّن عندما أقرأ بصوت عالٍ."),
"v905": ("Ich bin stolz auf meine Tochter, sie hat die Prüfung bestanden.", "أنا فخور بابنتي، فقد نجحت في الامتحان."),
"v914": ("Wir wollen Karim zum Geburtstag überraschen.", "نريد مفاجأة كريم في عيد ميلاده."),
"v920": ("Am Anfang war ich unsicher, ob mein Deutsch reicht.", "في البداية كنت متردداً هل تكفي ألمانيتي."),
"v927": ("Vor dem Gespräch war er unruhig und konnte nicht sitzen.", "قبل المقابلة كان قلقاً ولم يستطع الجلوس."),
"v933": ("Es war mutig, im Kurs als Erste zu sprechen.", "كان من الشجاعة أن تتكلّم أولاً في الدورة."),
"v952": ("Kinder sind neugierig und fragen den ganzen Tag „Warum?“.", "الأطفال فضوليون ويسألون طوال اليوم «لماذا؟»."),
"v957": ("In den ersten Wochen in Berlin fühlte ich mich einsam.", "في الأسابيع الأولى في برلين شعرت بالوحدة."),
"v965": ("Der Lehrer lobt Sara, weil sie viel Fortschritte gemacht hat.", "المعلّم يمدح سارة لأنها تقدّمت كثيراً."),
"v1026": ("Am Sonntag wandern wir drei Stunden in den Bergen.", "يوم الأحد نتنزّه مشياً ثلاث ساعات في الجبال."),
# ---- B1 ----
"v097": ("Unsere Gesellschaft wird älter, und das verändert den Arbeitsmarkt.", "مجتمعنا يشيخ، وهذا يغيّر سوق العمل."),
"v098": ("Nach dem Vortrag gab es eine lebhafte Diskussion.", "بعد المحاضرة دار نقاش حيوي."),
"v100": ("Der größte Vorteil von Homeoffice ist die Flexibilität.", "أكبر ميزة للعمل من البيت هي المرونة."),
"v101": ("Ein Nachteil der WG ist, dass man wenig Ruhe hat.", "من عيوب السكن المشترك قلّة الهدوء."),
"v102": ("Seit einem Jahr trage ich mehr Verantwortung im Projekt.", "منذ سنة أتحمّل مسؤولية أكبر في المشروع."),
"v103": ("Lena macht eine Ausbildung zur Krankenpflegerin.", "لينا تتابع تكويناً مهنياً في التمريض."),
"v104": ("Ich habe meine Bewerbung gestern per E-Mail geschickt.", "أرسلت طلب توظيفي أمس عبر الإيميل."),
"v105": ("Die Stelle ist ab dem ersten März frei.", "المنصب شاغر ابتداءً من أول مارس."),
"v106": ("Im Lebenslauf fällt eine Lücke von acht Monaten auf.", "في السيرة الذاتية تلفت الانتباه فجوة ثمانية أشهر."),
"v107": ("Mein Arbeitgeber bezahlt einen Teil der Weiterbildung.", "صاحب عملي يدفع جزءاً من التكوين المستمر."),
"v108": ("Die Umweltverschmutzung in den Städten nimmt weiter zu.", "تلوّث البيئة في المدن يتزايد."),
"v109": ("Die Stadt plant eine neue Maßnahme gegen den Lärm.", "المدينة تخطّط لإجراء جديد ضد الضجيج."),
"v110": ("Der Klimawandel ist auch in Tunesien deutlich spürbar.", "التغيّر المناخي محسوس بوضوح في تونس أيضاً."),
"v111": ("Die Regierung hält die Zahlen für ausreichend.", "الحكومة تعتبر الأرقام كافية."),
"v112": ("Die Wirtschaft wächst langsamer als im letzten Jahr.", "الاقتصاد ينمو أبطأ من السنة الماضية."),
"v113": ("Die Krankenkasse übernimmt die Kosten für die Behandlung.", "صندوق التأمين الصحي يتحمّل تكاليف العلاج."),
"v114": ("Die Behandlung dauert sechs Wochen, dreimal pro Woche.", "العلاج يستغرق ستة أسابيع، ثلاث مرات أسبوعياً."),
"v115": ("Mit guten Argumenten kannst du sie sicher überzeugen.", "بحجج جيدة يمكنك إقناعها بالتأكيد."),
"v116": ("Eine Mischung aus Büro und Homeoffice wäre die beste Lösung.", "مزيج بين المكتب والعمل من البيت سيكون أفضل حل."),
"v118": ("Die neue Regelung gilt ab Januar für alle Mitarbeiter.", "التنظيم الجديد يسري من يناير على كل الموظفين."),
"v119": ("Die Firma bildet jedes Jahr zehn junge Leute aus.", "الشركة تكوّن مهنياً كل سنة عشرة شبّان."),
"v120": ("Seine These ist, dass Handys im Unterricht nur stören.", "أطروحته أن الهواتف في الدرس تشوّش فقط."),
"v169": ("Lesen Sie den Vertrag genau, bevor Sie unterschreiben.", "اقرأ العقد بدقّة قبل أن توقّع."),
"v170": ("Nach der Ausbildung kann sie immer noch an die Hochschule gehen.", "بعد التكوين المهني يمكنها دائماً الالتحاق بالجامعة."),
"v171": ("Ihr Vortrag war kurz, aber sehr überzeugend.", "محاضرتها كانت قصيرة لكن مقنعة جداً."),
"v173": ("Nach einem Jahr zieht sie eine positive Bilanz.", "بعد سنة تخلص إلى حصيلة إيجابية."),
"v174": ("Das Prüfungsergebnis kommt in vier Wochen per Post.", "نتيجة الامتحان تصل خلال أربعة أسابيع بالبريد."),
"v131": ("Wer die Frist verpasst, muss mit der Konsequenz leben: neue Gebühr.", "من يفوّت المهلة يتحمّل النتيجة: رسوم جديدة."),
"v181": ("Eine gute Beziehung braucht Zeit und Vertrauen.", "العلاقة الجيدة تحتاج وقتاً وثقة."),
"v182": ("Ich habe noch Kontakt zu meinen alten Kollegen.", "ما زلت على تواصل مع زملائي القدامى."),
"v183": ("Unsere Freundschaft hält seit der Schulzeit in Sfax.", "صداقتنا مستمرة منذ أيام المدرسة في صفاقس."),
"v184": ("Mein Partner und ich teilen uns die Hausarbeit.", "أنا وشريكي نتقاسم أعمال البيت."),
"v188": ("Die Nachbarn streiten sich oft wegen der Musik.", "الجيران يتشاجرون كثيراً بسبب الموسيقى."),
"v190": ("Ohne Vertrauen funktioniert keine Zusammenarbeit.", "بلا ثقة لا ينجح أي تعاون."),
"v192": ("Sei ehrlich: Hast du die Hausaufgaben wirklich gemacht?", "كن صادقاً: هل أنجزت الواجبات فعلاً؟"),
"v193": ("Nach fünf Jahren haben sie sich getrennt.", "بعد خمس سنوات انفصلا."),
"v196": ("Er ist verliebt und redet nur noch von ihr.", "هو واقع في الحب ولا يتحدث إلا عنها."),
"v197": ("Sie hat heute Abend ein Date im Café am Fluss.", "لديها هذا المساء موعد عاطفي في المقهى قرب النهر."),
"v198": ("Wir haben uns für Samstag um zehn verabredet.", "حدّدنا موعداً يوم السبت في العاشرة."),
"v199": ("Tut mir leid, ich habe die Verabredung vergessen.", "آسفة، نسيت اللقاء المتّفق عليه."),
"v201": ("Im Team kommunizieren wir hauptsächlich per E-Mail.", "في الفريق نتواصل أساساً عبر الإيميل."),
"v203": ("Seit dem Streit gibt es eine gewisse Distanz zwischen ihnen.", "منذ الشجار هناك مسافة ما بينهما."),
"v204": ("Hedi kümmert sich um seinen Vater nach dem Schlaganfall.", "هادي يرعى والده بعد الجلطة."),
"v206": ("Der Konflikt im Team wurde am runden Tisch gelöst.", "الصراع في الفريق حُلّ على طاولة مستديرة."),
"v207": ("Nach dem Gespräch mit der Chefin war ich erleichtert.", "بعد الحوار مع المديرة شعرت بالارتياح."),
"v208": ("Wir haben uns lange über den Film unterhalten.", "تحدثنا طويلاً عن الفيلم."),
"v211": ("Das bleibt unser Geheimnis, sag es niemandem!", "هذا يبقى سرّنا، لا تخبر أحداً!"),
"v214": ("Ich freue mich schon auf den Urlaub an der Ostsee.", "أترقّب بفرح العطلة على بحر البلطيق."),
"v218": ("In der WG ist es Gewohnheit, sonntags zusammen zu kochen.", "في السكن المشترك من العادة الطبخ معاً يوم الأحد."),
"v219": ("Am Ende fanden beide Seiten einen Kompromiss.", "في النهاية وجد الطرفان تسوية."),
"v223": ("Die Gesundheit geht vor der Frist, sagt mein Chef.", "الصحة قبل المهلة، يقول رئيسي."),
"v224": ("Rania ist krank und kommt heute nicht ins Büro.", "رانيا مريضة ولن تأتي إلى المكتب اليوم."),
"v225": ("Die Krankheit ist nicht ansteckend, sagt die Ärztin.", "المرض غير معدٍ، تقول الطبيبة."),
"v227": ("Die Ärztin hat mich für drei Tage krankgeschrieben.", "الطبيبة منحتني إجازة مرضية ثلاثة أيام."),
"v228": ("Die Praxis öffnet um acht, ich war um zehn nach acht da.", "العيادة تفتح في الثامنة، وكنت هناك في الثامنة وعشر دقائق."),
"v229": ("Die Post ist gegenüber vom Krankenhaus.", "البريد مقابل المستشفى."),
"v230": ("In der Apotheke neben der Praxis kaufe ich die Tabletten.", "أشتري الأقراص من الصيدلية المجاورة للعيادة."),
"v231": ("Der Arzt schreibt ein Rezept für ein Fiebermittel.", "الطبيب يكتب وصفة لخافض حرارة."),
"v232": ("Nehmen Sie eine Tablette morgens und eine abends.", "تناول قرصاً صباحاً وقرصاً مساءً."),
"v233": ("Der Schmerz im Knie ist nach dem Laufen schlimmer.", "ألم الركبة يشتدّ بعد الجري."),
"v234": ("Bei Fieber ist Sport gefährlich, warten Sie, bis Sie gesund sind.", "مع الحمّى الرياضة خطيرة، انتظر حتى تتعافى."),
"v235": ("Wie fühlen Sie sich heute? – Viel besser, danke.", "كيف تشعر اليوم؟ – أفضل بكثير، شكراً."),
"v239": ("Diese Ärztin behandelt vor allem Kinder.", "هذه الطبيبة تعالج الأطفال بشكل أساسي."),
"v242": ("Die Operation dauerte zwei Stunden und verlief gut.", "العملية الجراحية استغرقت ساعتين وسارت جيداً."),
"v246": ("Ich muss mich heute krankmelden, ich habe starke Kopfschmerzen.", "يجب أن أبلّغ بمرضي اليوم، عندي صداع شديد."),
"v248": ("Welche Versicherung zahlt den Wasserschaden, Hausrat oder Vermieter?", "أي تأمين يدفع أضرار الماء، تأمين المنزل أم المؤجّر؟"),
"v251": ("Vor der Prüfung hatte ich viel Stress und wenig Schlaf.", "قبل الامتحان كان عندي ضغط كبير ونوم قليل."),
"v252": ("Nach zehn Stunden Arbeit ist sie völlig gestresst.", "بعد عشر ساعات عمل هي مرهقة تماماً."),
"v260": ("Meine Arbeitszeit ist von acht bis siebzehn Uhr.", "ساعات عملي من الثامنة إلى الخامسة."),
"v261": ("Machen Sie alle zwei Stunden eine kurze Pause vom Bildschirm.", "خذ استراحة قصيرة من الشاشة كل ساعتين."),
"v265": ("Ich halte mich mit Schwimmen und Radfahren fit.", "أحافظ على لياقتي بالسباحة وركوب الدراجة."),
"v266": ("Wer sich gesund ernährt, braucht weniger Tabletten.", "من يتغذّى بشكل صحي يحتاج أقراصاً أقل."),
"v267": ("Bewegung an der frischen Luft hilft gegen Stress.", "الحركة في الهواء الطلق تساعد ضد الضغط."),
"v273": ("Armut ist auch in reichen Ländern ein Problem.", "الفقر مشكلة حتى في البلدان الغنية."),
"v279": ("Sprache ist der Schlüssel zur Integration.", "اللغة هي مفتاح الاندماج."),
"v283": ("Ein Vorurteil verschwindet, wenn man die Menschen kennenlernt.", "القالب المسبق يزول عندما تتعرّف على الناس."),
"v284": ("Meine Nachbarn sind tolerant und sehr hilfsbereit.", "جيراني متسامحون ومستعدون للمساعدة."),
"v285": ("Ich akzeptiere deine Entscheidung, auch wenn ich anders denke.", "أقبل قرارك حتى لو كنت أفكّر بشكل مختلف."),
"v286": ("Für ein Ehrenamt braucht man nur Zeit und Bereitschaft.", "للعمل التطوعي تحتاج فقط وقتاً واستعداداً."),
"v288": ("Ich spiele seit drei Jahren Fußball im Verein.", "ألعب كرة القدم في النادي منذ ثلاث سنوات."),
"v291": ("Tausende demonstrieren heute für besseren Klimaschutz.", "الآلاف يتظاهرون اليوم من أجل حماية أفضل للمناخ."),
"v295": ("Die nächste Wahl findet im September statt.", "الانتخابات القادمة ستُجرى في سبتمبر."),
"v296": ("Ab achtzehn darf man in Deutschland wählen.", "من سن الثامنة عشرة يمكن التصويت في ألمانيا."),
"v297": ("Jeder Wähler bekommt die Unterlagen per Post.", "كل ناخب يتلقى الوثائق بالبريد."),
"v298": ("Das Parlament diskutiert heute über das neue Gesetz.", "البرلمان يناقش اليوم القانون الجديد."),
"v300": ("In einer Demokratie darf man seine Meinung frei sagen.", "في الديمقراطية يمكنك قول رأيك بحرية."),
"v303": ("Die Anmeldung beim Amt ist Pflicht, innerhalb von zwei Wochen.", "التسجيل في الدائرة واجب، خلال أسبوعين."),
"v304": ("Der Kurs ist freiwillig, aber ich empfehle ihn.", "الدورة طوعية، لكنني أنصح بها."),
"v306": ("Alte Batterien darf man nicht einfach wegwerfen.", "البطاريات القديمة لا يجوز رميها ببساطة."),
"v311": ("Das stärkste Argument gegen das Auto ist der Preis.", "أقوى حجة ضد السيارة هي السعر."),
}
