# -*- coding: utf-8 -*-
"""9 neue A1-Dialoge (d-a1-19..27) aus verwaisten A1-Karten — schliesst A1 auf 29 Dialoge."""
D = [
{"id":"d-a1-19","titleDe":"Frühstück in der Familie","titleAr":"فطور في العائلة",
 "waisen":["die Butter","das Salz","die Banane","die Orange","der Löffel","das Messer","das Mittagessen","das Abendessen","die Katze","backen"],
 "lines":[
  ["Mutter","Guten Morgen! Das Frühstück ist fertig. Brot, Butter und Käse.","صباح الخير! الفطور جاهز. خبز وزبدة وجبن."],
  ["Tochter","Gibt es auch Obst? Ich möchte eine Banane.","هل يوجد فاكهة أيضاً؟ أريد موزة."],
  ["Mutter","Ja, und eine Orange. Hier ist ein Messer für das Brot.","نعم، وبرتقالة. هذا سكين للخبز."],
  ["Tochter","Danke. Wo ist der Löffel für das Ei? Und das Salz?","شكراً. أين ملعقة البيض؟ والملح؟"],
  ["Mutter","Auf dem Tisch, neben der Katze. Sie schläft schon wieder.","على الطاولة، بجانب القطة. تنام مرة أخرى."],
  ["Tochter","Was gibt es zum Mittagessen?","ماذا يوجد على الغداء؟"],
  ["Mutter","Reis mit Gemüse. Und heute Abend backen wir einen Kuchen für Oma.","أرز مع خضار. ومساء اليوم نخبز كعكة للجدة."],
  ["Tochter","Super! Dann esse ich zum Abendessen nur Kuchen.","رائع! إذن آكل على العشاء كعكاً فقط."]],
 "questions":[
  {"type":"mc","promptDe":"Was gibt es zum Mittagessen?","options":["Reis mit Gemüse","Brot, Butter und Käse","Kuchen"],"answer":"Reis mit Gemüse","explanationAr":"الدليل: «Was gibt es zum Mittagessen?» … «Reis mit Gemüse». الفخّ 1: الخبز والزبدة للفطور. الفخّ 2: الكعك مساءً للجدة."},
  {"type":"mc","promptDe":"Wo ist das Salz?","options":["auf dem Tisch, neben der Katze","neben dem Ei","neben dem Kuchen"],"answer":"auf dem Tisch, neben der Katze","explanationAr":"الدليل: «Auf dem Tisch, neben der Katze». الفخّ 1: الملعقة للبيض. الفخّ 2: الكعكة تُخبز مساءً."},
  {"type":"truefalse","promptDe":"Die Familie backt heute Abend einen Kuchen.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «heute Abend backen wir einen Kuchen für Oma»."}],
 "dictation":["Das Frühstück ist fertig.","Was gibt es zum Mittagessen?"]},
{"id":"d-a1-20","titleDe":"Ein Termin im Kalender","titleAr":"موعد في التقويم",
 "waisen":["das Datum","der Donnerstag","der März","der April","übermorgen","vorgestern","bald","die Uhrzeit","zuletzt","Punkt zwölf"],
 "lines":[
  ["Chef","Frau Amri, wann ist der Termin mit der Firma Berger?","سيدة عمري، متى الموعد مع شركة بيرغر؟"],
  ["Frau Amri","Am Donnerstag. Das Datum ist der 28. März.","يوم الخميس. التاريخ 28 مارس."],
  ["Chef","Also übermorgen. Und die Uhrzeit?","إذن بعد غد. والساعة؟"],
  ["Frau Amri","Punkt zwölf, im großen Raum.","الثانية عشرة تماماً، في القاعة الكبيرة."],
  ["Chef","Gut. Wann hatten wir zuletzt einen Termin mit ihnen?","حسناً. متى كان آخر موعد معهم؟"],
  ["Frau Amri","Vorgestern, am Montag. Das war kurz, nur eine Stunde.","أول أمس، يوم الاثنين. كان قصيراً، ساعة واحدة فقط."],
  ["Chef","Und im April kommt der zweite Termin?","وفي أبريل يأتي الموعد الثاني؟"],
  ["Frau Amri","Ja, bald, am 5. April. Ich schreibe es in den Kalender.","نعم، قريباً، في 5 أبريل. أكتبه في التقويم."]],
 "questions":[
  {"type":"mc","promptDe":"Wann ist der Termin mit der Firma Berger?","options":["am Donnerstag um Punkt zwölf","am Montag um zwölf","am 5. April"],"answer":"am Donnerstag um Punkt zwölf","explanationAr":"الدليل: «Am Donnerstag» و«Punkt zwölf». الفخّ 1: الاثنين كان الموعد الأخير. الفخّ 2: 5 أبريل الموعد الثاني."},
  {"type":"mc","promptDe":"Wie lange war der letzte Termin?","options":["nur eine Stunde","zwei Stunden","den ganzen Montag"],"answer":"nur eine Stunde","explanationAr":"الدليل: «Das war kurz, nur eine Stunde». الفخّ: الاثنين هو اليوم لا المدة."},
  {"type":"fill","promptDe":"Das Datum ist der 28. ___.","answer":["März"],"explanationAr":"الدليل: «Das Datum ist der 28. März»."}],
 "dictation":["Also übermorgen. Und die Uhrzeit?","Ja, bald, am 5. April."]},
{"id":"d-a1-21","titleDe":"In der Schule","titleAr":"في المدرسة",
 "waisen":["der Schüler","die Klasse","das Heft","der Stift","das Papier","der Satz","das Diktat","auswendig lernen","antworten","die Pause machen"],
 "lines":[
  ["Lehrerin","Guten Morgen, Klasse! Heute schreiben wir ein Diktat.","صباح الخير أيها الصف! اليوم نكتب إملاءً."],
  ["Schüler","Brauchen wir das Heft oder ein Papier?","هل نحتاج الدفتر أم ورقة؟"],
  ["Lehrerin","Das Heft, bitte. Und einen blauen Stift, keinen Bleistift.","الدفتر من فضلكم. وقلماً أزرق، لا قلم رصاص."],
  ["Schüler","Wie viele Sätze sind es?","كم جملة؟"],
  ["Lehrerin","Sechs Sätze. Ich lese jeden Satz zweimal. Dann antwortet ihr auf zwei Fragen.","ست جمل. أقرأ كل جملة مرتين. ثم تجيبون عن سؤالين."],
  ["Schüler","Und danach machen wir eine Pause?","وبعدها نأخذ استراحة؟"],
  ["Lehrerin","Ja, zehn Minuten. Nach der Pause lernen wir das Gedicht auswendig.","نعم، عشر دقائق. بعد الاستراحة نحفظ القصيدة عن ظهر قلب."],
  ["Schüler","Das Gedicht ist lang! Können wir nur die Hälfte lernen?","القصيدة طويلة! هل يمكن أن نحفظ النصف فقط؟"]],
 "questions":[
  {"type":"mc","promptDe":"Womit schreiben die Schüler das Diktat?","options":["mit einem blauen Stift ins Heft","mit einem Bleistift auf Papier","mit einem blauen Stift auf Papier"],"answer":"mit einem blauen Stift ins Heft","explanationAr":"الدليل: «Das Heft, bitte. Und einen blauen Stift, keinen Bleistift». الفخّ 1: قلم الرصاص منفيّ. الفخّ 2: الورقة لا الدفتر."},
  {"type":"mc","promptDe":"Wie oft liest die Lehrerin jeden Satz?","options":["zweimal","sechs Mal","zehn Mal"],"answer":"zweimal","explanationAr":"الدليل: «Ich lese jeden Satz zweimal». الفخّ 1: ستة عدد الجمل. الفخّ 2: عشرة دقائق الاستراحة."},
  {"type":"truefalse","promptDe":"Die Pause dauert zehn Minuten.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Ja, zehn Minuten»."}],
 "dictation":["Heute schreiben wir ein Diktat.","Ich lese jeden Satz zweimal."]},
{"id":"d-a1-22","titleDe":"Die Großeltern kommen","titleAr":"الجدّان يأتيان",
 "waisen":["die Großmutter","der Großvater","der Ehemann","die Geschwister","das Mädchen","das Baby","mitbringen","fliegen","ankommen"],
 "lines":[
  ["Salma","Meine Großmutter und mein Großvater kommen am Samstag aus Tunis.","جدتي وجدي يأتيان يوم السبت من تونس."],
  ["Nina","Fliegen sie? Wann sollen sie ankommen?","هل يطيران؟ متى يُفترض أن يصلا؟"],
  ["Salma","Ja, das Flugzeug kommt um 14 Uhr an. Mein Ehemann holt sie ab.","نعم، الطائرة تصل في الثانية. زوجي يأخذهما."],
  ["Nina","Wohnen sie bei euch?","هل يسكنان عندكم؟"],
  ["Salma","Ja, zwei Wochen. Meine Geschwister kommen dann auch zu Besuch.","نعم، أسبوعين. إخوتي يأتون للزيارة أيضاً."],
  ["Nina","Wie viele Geschwister hast du?","كم أخاً وأختاً لديك؟"],
  ["Salma","Zwei: einen Bruder und eine Schwester. Meine Schwester möchte ihr Baby mitbringen, ein Mädchen.","اثنان: أخ وأخت. أختي تريد إحضار طفلتها، بنت."],
  ["Nina","Wie schön! Dann ist das Haus voll. Deine Großmutter freut sich sicher auf das Baby.","ما أجمل! إذن البيت ممتلئ. جدتك تفرح بالرضيعة بالتأكيد."]],
 "questions":[
  {"type":"mc","promptDe":"Wer holt die Großeltern ab?","options":["der Ehemann von Salma","die Schwester von Salma","die Großmutter selbst"],"answer":"der Ehemann von Salma","explanationAr":"الدليل: «Mein Ehemann holt sie ab». الفخّ 1: الأخت تحضر الرضيعة. الفخّ 2: الجدة هي القادمة."},
  {"type":"mc","promptDe":"Wie lange bleiben die Großeltern?","options":["zwei Wochen","zwei Tage","zwei Stunden"],"answer":"zwei Wochen","explanationAr":"الدليل: «Ja, zwei Wochen». الفخّ 1: الرقم صحيح والوحدة خاطئة. الفخّ 2: ساعتان لم تُذكرا، 14 Uhr موعد الوصول."},
  {"type":"fill","promptDe":"Das Flugzeug kommt um 14 Uhr ___.","answer":["an"],"explanationAr":"الدليل: «das Flugzeug kommt um 14 Uhr an» — ankommen فعل منفصل."}],
 "dictation":["Fliegen sie? Wann sollen sie ankommen?","Meine Schwester möchte ihr Baby mitbringen, ein Mädchen."]},
{"id":"d-a1-23","titleDe":"Notruf: Feuer in der Küche","titleAr":"اتصال طوارئ: حريق في المطبخ",
 "waisen":["der Notruf","die Feuerwehr","der Eingang","der Ausgang","die Treppe","drinnen","niemand","jemand","die Richtung","schnell"],
 "lines":[
  ["Frau Weber","Hallo, hier Weber, Gartenstraße 8. In der Küche ist Feuer!","مرحباً، معك فيبر، شارع غارتن 8. في المطبخ حريق!"],
  ["Notruf","Bleiben Sie ruhig. Ist noch jemand drinnen?","ابقي هادئة. هل ما زال أحد في الداخل؟"],
  ["Frau Weber","Nein, niemand. Wir sind alle draußen, vor dem Eingang.","لا، لا أحد. كلنا في الخارج أمام المدخل."],
  ["Notruf","Gut. Die Feuerwehr ist schon unterwegs, fünf Minuten.","حسناً. الإطفاء في الطريق، خمس دقائق."],
  ["Frau Weber","Der Ausgang zum Garten ist offen, die Treppe ist frei.","المخرج إلى الحديقة مفتوح، والدرج خالٍ."],
  ["Notruf","Sehr gut. Gehen Sie nicht zurück ins Haus.","ممتاز. لا تعودي إلى البيت."],
  ["Frau Weber","In welche Richtung sollen wir gehen?","في أي اتجاه نذهب؟"],
  ["Notruf","Auf die andere Straßenseite. Warten Sie dort auf die Feuerwehr.","إلى الجهة الأخرى من الشارع. انتظروا هناك الإطفاء."]],
 "questions":[
  {"type":"mc","promptDe":"Ist noch jemand im Haus?","options":["Nein, alle sind draußen vor dem Eingang.","Ja, jemand ist in der Küche.","Ja, jemand ist auf der Treppe."],"answer":"Nein, alle sind draußen vor dem Eingang.","explanationAr":"الدليل: «Nein, niemand. Wir sind alle draußen, vor dem Eingang». الفخّ 1: المطبخ مكان النار. الفخّ 2: الدرج «frei»."},
  {"type":"mc","promptDe":"Wann kommt die Feuerwehr?","options":["in fünf Minuten","in acht Minuten","sie ist schon da"],"answer":"in fünf Minuten","explanationAr":"الدليل: «Die Feuerwehr ist schon unterwegs, fünf Minuten». الفخّ 1: 8 رقم البيت. الفخّ 2: «unterwegs» في الطريق لا وصلت."},
  {"type":"truefalse","promptDe":"Frau Weber soll ins Haus zurückgehen.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Gehen Sie nicht zurück ins Haus»."}],
 "dictation":["Ist noch jemand drinnen?","Gehen Sie nicht zurück ins Haus."]},
{"id":"d-a1-24","titleDe":"Was machst du in der Freizeit?","titleAr":"ماذا تفعل في وقت الفراغ؟",
 "waisen":["die Freizeit","der Sport","schwimmen","tanzen","das Lied","das Foto","spazieren gehen","zufrieden","mögen","täglich"],
 "lines":[
  ["Tom","Was machst du in der Freizeit, Leila?","ماذا تفعلين في وقت فراغك يا ليلى؟"],
  ["Leila","Ich mache viel Sport. Ich schwimme täglich, morgens um sieben.","أمارس رياضة كثيرة. أسبح يومياً في السابعة صباحاً."],
  ["Tom","Jeden Tag? Ich gehe lieber spazieren, im Park.","كل يوم؟ أنا أفضّل التنزّه مشياً في الحديقة."],
  ["Leila","Das mag ich auch. Und am Samstag tanze ich mit Freundinnen.","أحب ذلك أيضاً. ويوم السبت أرقص مع صديقاتي."],
  ["Tom","Ich singe gern. Kennst du das Lied „Die Gedanken sind frei“?","أحب الغناء. هل تعرفين أغنية «Die Gedanken sind frei»؟"],
  ["Leila","Nein. Singst du es mir vor?","لا. هل تغنّيها لي؟"],
  ["Tom","Später. Schau, hier ist ein Foto vom Chor.","لاحقاً. انظري، هذه صورة الجوقة."],
  ["Leila","Schön! Du siehst sehr zufrieden aus.","جميل! تبدو راضياً جداً."]],
 "questions":[
  {"type":"mc","promptDe":"Wann schwimmt Leila?","options":["täglich, morgens um sieben","am Samstag mit Freundinnen","später im Park"],"answer":"täglich, morgens um sieben","explanationAr":"الدليل: «Ich schwimme täglich, morgens um sieben». الفخّ 1: السبت للرقص. الفخّ 2: الحديقة للتنزّه."},
  {"type":"mc","promptDe":"Was zeigt Tom?","options":["ein Foto vom Chor","ein Lied im Buch","den Park"],"answer":"ein Foto vom Chor","explanationAr":"الدليل: «hier ist ein Foto vom Chor». الفخّ 1: الأغنية يغنّيها لاحقاً. الفخّ 2: الحديقة مكان تنزّهه."},
  {"type":"truefalse","promptDe":"Leila kennt das Lied.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Nein. Singst du es mir vor?»."}],
 "dictation":["Ich mache viel Sport.","Du siehst sehr zufrieden aus."]},
{"id":"d-a1-25","titleDe":"Am Geldautomaten","titleAr":"عند الصرّاف الآلي",
 "waisen":["die Bankkarte","die Geheimzahl","wechseln","funktionieren","kaputtgehen","klicken","die Hälfte","wahrscheinlich","unmöglich","leider"],
 "lines":[
  ["Karim","Entschuldigung, der Automat funktioniert nicht. Ist er kaputt?","عفواً، الجهاز لا يعمل. هل هو معطّل؟"],
  ["Bankangestellte","Leider ja, er ist heute Morgen kaputtgegangen. Nehmen Sie den zweiten Automaten.","للأسف نعم، تعطّل هذا الصباح. استعمل الجهاز الثاني."],
  ["Karim","Danke. Ich stecke die Bankkarte hinein und gebe die Geheimzahl ein.","شكراً. أدخل البطاقة البنكية وأكتب الرقم السري."],
  ["Bankangestellte","Dann klicken Sie auf „Geld abheben“.","ثم اضغط على «سحب نقود»."],
  ["Karim","Ich möchte 200 Euro. Kann ich die Hälfte in kleinen Scheinen haben?","أريد 200 يورو. هل أستطيع أخذ النصف بأوراق صغيرة؟"],
  ["Bankangestellte","Das ist hier unmöglich, der Automat gibt nur Fünfziger. Aber Sie können am Schalter wechseln.","هذا مستحيل هنا، الجهاز يعطي أوراق خمسين فقط. لكن يمكنك التبديل عند الشباك."],
  ["Karim","Gut. Ist der Schalter noch offen?","حسناً. هل الشباك ما زال مفتوحاً؟"],
  ["Bankangestellte","Wahrscheinlich ja, bis 16 Uhr.","على الأرجح نعم، حتى الرابعة."]],
 "questions":[
  {"type":"mc","promptDe":"Warum funktioniert der erste Automat nicht?","options":["Er ist heute Morgen kaputtgegangen.","Karim hat die falsche Geheimzahl.","Er gibt nur Fünfziger."],"answer":"Er ist heute Morgen kaputtgegangen.","explanationAr":"الدليل: «er ist heute Morgen kaputtgegangen». الفخّ 1: الرقم السري لم يُذكر كخطأ. الفخّ 2: أوراق الخمسين تخصّ الجهاز الثاني."},
  {"type":"mc","promptDe":"Wo kann Karim Geld wechseln?","options":["am Schalter","am zweiten Automaten","nirgendwo, das ist unmöglich"],"answer":"am Schalter","explanationAr":"الدليل: «Aber Sie können am Schalter wechseln». الفخّ 1: الجهاز يعطي خمسينات فقط. الفخّ 2: «unmöglich» تخصّ الجهاز لا الشباك."},
  {"type":"fill","promptDe":"Ich stecke die Bankkarte hinein und gebe die ___ ein.","answer":["Geheimzahl"],"explanationAr":"الدليل: «gebe die Geheimzahl ein»."}],
 "dictation":["Entschuldigung, der Automat funktioniert nicht.","Wahrscheinlich ja, bis 16 Uhr."]},
{"id":"d-a1-26","titleDe":"Regen im Herbst","titleAr":"مطر في الخريف",
 "waisen":["der Regenschirm","die Jahreszeit","nass","trocken","der Oktober","der November","der Dezember","wohin","zurückfahren","hoffentlich"],
 "lines":[
  ["Mia","Es regnet schon wieder! Meine Jacke ist ganz nass.","تمطر مرة أخرى! سترتي مبتلّة تماماً."],
  ["Omar","Hast du keinen Regenschirm?","أليس معك مظلة؟"],
  ["Mia","Nein, zu Hause. Welche Jahreszeit ist das? Der Oktober ist doch schön!","لا، في البيت. أي فصل هذا؟ أكتوبر جميل عادة!"],
  ["Omar","In Deutschland ist der Oktober oft nass. Im November wird es noch kälter.","في ألمانيا أكتوبر ممطر غالباً. وفي نوفمبر يزداد البرد."],
  ["Mia","Und im Dezember? Hoffentlich schneit es dann.","وفي ديسمبر؟ آمل أن تثلج حينها."],
  ["Omar","Vielleicht. Wohin gehst du jetzt?","ربما. إلى أين تذهبين الآن؟"],
  ["Mia","Ich fahre zurück nach Hause und ziehe trockene Sachen an.","أعود إلى البيت وأرتدي ملابس جافة."],
  ["Omar","Gut. Nimm meinen Schirm, ich habe zwei.","حسناً. خذي مظلتي، عندي اثنتان."]],
 "questions":[
  {"type":"mc","promptDe":"Wo ist Mias Regenschirm?","options":["zu Hause","in Omars Tasche, er hat zwei","in der Jacke"],"answer":"zu Hause","explanationAr":"الدليل: «Hast du keinen Regenschirm?» … «Nein, zu Hause». الفخّ 1: عمر يعطيها مظلته لكن مظلتها في البيت. الفخّ 2: السترة مبتلّة."},
  {"type":"mc","promptDe":"Was macht Mia jetzt?","options":["Sie fährt nach Hause und zieht trockene Sachen an.","Sie kauft einen Regenschirm.","Sie wartet auf den Schnee im Dezember."],"answer":"Sie fährt nach Hause und zieht trockene Sachen an.","explanationAr":"الدليل: «Ich fahre zurück nach Hause und ziehe trockene Sachen an». الفخّ 1: تأخذ مظلة عمر. الفخّ 2: الثلج أمل لديسمبر."},
  {"type":"truefalse","promptDe":"Im November wird es kälter.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Im November wird es noch kälter»."}],
 "dictation":["Meine Jacke ist ganz nass.","Nimm meinen Schirm, ich habe zwei."]},
{"id":"d-a1-27","titleDe":"In der Werkstatt","titleAr":"في الورشة",
 "waisen":["die Werkstatt","der Techniker","anfangen","aufhören","wissen","denken","die Idee","das Ziel","leicht","letzte"],
 "lines":[
  ["Chef","Herr Diallo, Sie sind der neue Techniker? Willkommen in der Werkstatt.","سيد ديالو، أنت الفنّي الجديد؟ أهلاً بك في الورشة."],
  ["Diallo","Danke. Wann fange ich an?","شكراً. متى أبدأ؟"],
  ["Chef","Heute um acht. Wir hören um vier auf, Freitag schon um zwei.","اليوم في الثامنة. ننتهي في الرابعة، والجمعة في الثانية."],
  ["Diallo","Gut. Wissen Sie schon, was ich heute mache?","حسناً. هل تعرف ماذا أفعل اليوم؟"],
  ["Chef","Ja, die letzte Maschine dort. Das ist leicht, nur eine Kontrolle.","نعم، الآلة الأخيرة هناك. هذا سهل، مجرد فحص."],
  ["Diallo","Ich denke, das schaffe ich bis zum Mittag.","أظن أنني أنجزه حتى الظهر."],
  ["Chef","Sehr gut. Unser Ziel: alle Maschinen bis Freitag fertig.","ممتاز. هدفنا: كل الآلات جاهزة حتى الجمعة."],
  ["Diallo","Ich habe eine Idee: Wir machen zuerst die großen Maschinen.","عندي فكرة: نبدأ بالآلات الكبيرة أولاً."]],
 "questions":[
  {"type":"mc","promptDe":"Wann hört die Arbeit am Freitag auf?","options":["um zwei","um vier","um acht"],"answer":"um zwei","explanationAr":"الدليل: «Wir hören um vier auf, Freitag schon um zwei». الفخّ 1: الرابعة في الأيام العادية. الفخّ 2: الثامنة موعد البدء."},
  {"type":"mc","promptDe":"Was macht Herr Diallo heute?","options":["eine Kontrolle an der letzten Maschine","alle großen Maschinen","alle Maschinen bis Freitag"],"answer":"eine Kontrolle an der letzten Maschine","explanationAr":"الدليل: «die letzte Maschine dort. Das ist leicht, nur eine Kontrolle». الفخّ 1: الكبيرة فكرته. الفخّ 2: كل الآلات هدف الأسبوع."},
  {"type":"truefalse","promptDe":"Die Arbeit fängt heute um acht an.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Wann fange ich an?» … «Heute um acht»."}],
 "dictation":["Wann fange ich an?","Das ist leicht, nur eine Kontrolle."]},
]
