# -*- coding: utf-8 -*-
"""9 neue A2-Dialoge (d-a2-10..18), gebaut aus verwaisten A2-Karten (>=8 pro Dialog). Fragen: Fallen-Distraktoren, Belege woertlich."""
D = [
{"id":"d-a2-10","titleDe":"Schimmel im Bad","titleAr":"عفن في الحمّام",
 "waisen":["der Hausmeister","lüften","der Schimmel","die Feuchtigkeit","der Mangel","die Mietminderung","sich beschweren","die Hausverwaltung"],
 "lines":[
  ["Mieterin","Guten Tag, Herr Kaya. Im Bad ist Schimmel an der Wand, oben in der Ecke.","طاب يومك سيد كايا. في الحمّام عفن على الجدار، في الزاوية العليا."],
  ["Hausmeister","Lüften Sie regelmäßig? Nach dem Duschen muss das Fenster zehn Minuten offen sein.","هل تهوّين بانتظام؟ بعد الاستحمام يجب أن تبقى النافذة مفتوحة عشر دقائق."],
  ["Mieterin","Ja, jeden Tag. Aber die Feuchtigkeit bleibt, das Fenster ist sehr klein.","نعم، كل يوم. لكن الرطوبة تبقى، فالنافذة صغيرة جداً."],
  ["Hausmeister","Dann ist es ein Mangel an der Wohnung, nicht Ihr Fehler. Ich schreibe das der Hausverwaltung.","إذن هو عيب في الشقة لا خطؤك. سأكتب ذلك لإدارة العقار."],
  ["Mieterin","Muss ich mich auch selbst beschweren, oder reicht es, wenn der Hausmeister das meldet?","هل يجب أن أشتكي بنفسي أيضاً، أم يكفي أن يبلّغ الحارس؟"],
  ["Hausmeister","Ja, bitte schriftlich, mit Foto und Datum. Dann kann die Verwaltung eine Mietminderung prüfen.","نعم، كتابياً من فضلك، مع صورة وتاريخ. عندها تستطيع الإدارة النظر في تخفيض الإيجار."],
  ["Mieterin","Und wann kommt jemand?","ومتى يأتي أحد؟"],
  ["Hausmeister","Der Handwerker kommt nächste Woche, am Dienstag um neun.","الحرفيّ يأتي الأسبوع القادم، الثلاثاء في التاسعة."]],
 "questions":[
  {"type":"mc","promptDe":"Warum ist der Schimmel laut Hausmeister nicht der Fehler der Mieterin?","options":["Weil sie nicht lüftet.","Weil das Fenster sehr klein ist und die Feuchtigkeit bleibt.","Weil der Handwerker zu spät kommt."],"answer":"Weil das Fenster sehr klein ist und die Feuchtigkeit bleibt.","explanationAr":"الدليل: «die Feuchtigkeit bleibt, das Fenster ist sehr klein» ثم «Dann ist es ein Mangel an der Wohnung, nicht Ihr Fehler». الفخّ 1: التهوية سأل عنها وهي تهوّي يومياً. الفخّ 2: الحرفيّ موعد لا سبب."},
  {"type":"mc","promptDe":"Wie soll sich die Mieterin beschweren?","options":["telefonisch beim Hausmeister","schriftlich, mit Foto und Datum","persönlich beim Handwerker"],"answer":"schriftlich, mit Foto und Datum","explanationAr":"الدليل: «Ja, bitte schriftlich, mit Foto und Datum». الفخّ 1: الحارس هو من تكلّمه الآن. الفخّ 2: الحرفيّ يأتي للإصلاح."},
  {"type":"truefalse","promptDe":"Der Handwerker kommt am Dienstag um neun.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Der Handwerker kommt nächste Woche, am Dienstag um neun»."}],
 "dictation":["Im Bad ist Schimmel an der Wand, oben in der Ecke.","Dann kann die Verwaltung eine Mietminderung prüfen."]},
{"id":"d-a2-11","titleDe":"Anruf im Büro","titleAr":"مكالمة في المكتب",
 "waisen":["der Anruf","besetzt","weiterleiten","die Sprachnachricht","die Ansage","nachfragen","erreichen","die Bestätigung"],
 "lines":[
  ["Sekretärin","Firma Neumann, guten Tag. Was kann ich für Sie tun?","شركة نويمان، طاب يومك. بمَ أخدمك؟"],
  ["Karim","Guten Tag, hier Karim Saidi. Ich möchte Frau Lang erreichen.","طاب يومك، معك كريم السعيدي. أريد الوصول إلى السيدة لانغ."],
  ["Sekretärin","Frau Lang ist gerade besetzt. Soll ich den Anruf an ihren Kollegen weiterleiten?","السيدة لانغ مشغولة الآن. هل أحوّل المكالمة إلى زميلها؟"],
  ["Karim","Nein danke. Ich wollte nur nachfragen: Ist meine Bestätigung angekommen?","لا شكراً. أردت فقط الاستفسار: هل وصل تأكيدي؟"],
  ["Sekretärin","Ich sehe hier eine E-Mail von gestern. Ja, die Bestätigung ist da.","أرى هنا إيميلاً من أمس. نعم، التأكيد موجود."],
  ["Karim","Sehr gut. Kann ich Frau Lang eine Sprachnachricht hinterlassen?","ممتاز. هل يمكنني ترك رسالة صوتية للسيدة لانغ؟"],
  ["Sekretärin","Ja. Nach der Ansage sprechen Sie bitte Ihren Namen und Ihre Nummer.","نعم. بعد الإعلان قل اسمك ورقمك من فضلك."],
  ["Karim","Danke. Und sie ruft heute noch zurück?","شكراً. وهل تعاود الاتصال اليوم؟"]],
 "questions":[
  {"type":"mc","promptDe":"Warum kann Karim Frau Lang nicht sprechen?","options":["Sie ist gerade besetzt.","Sie ist bei ihrem Kollegen.","Ihre E-Mail ist nicht angekommen."],"answer":"Sie ist gerade besetzt.","explanationAr":"الدليل: «Frau Lang ist gerade besetzt». الفخّ 1: الزميل هو من عُرض تحويل المكالمة إليه. الفخّ 2: الإيميل وصل («die Bestätigung ist da»)."},
  {"type":"mc","promptDe":"Was soll Karim nach der Ansage tun?","options":["die Nummer der Sekretärin aufschreiben","seinen Namen und seine Nummer sprechen","eine E-Mail an den Kollegen schicken"],"answer":"seinen Namen und seine Nummer sprechen","explanationAr":"الدليل: «Nach der Ansage sprechen Sie bitte Ihren Namen und Ihre Nummer». الفخّ 1: رقمه هو لا رقم السكرتيرة. الفخّ 2: الإيميل كان أمس ووصل."},
  {"type":"fill","promptDe":"Soll ich den Anruf an ihren Kollegen ___?","answer":["weiterleiten"],"explanationAr":"الدليل: «Soll ich den Anruf an ihren Kollegen weiterleiten?» — فعل منفصل في المصدر بعد soll."}],
 "dictation":["Frau Lang ist gerade besetzt.","Ist meine Bestätigung angekommen?"]},
{"id":"d-a2-12","titleDe":"Der Wetterbericht im Radio","titleAr":"نشرة الطقس في الراديو",
 "waisen":["das Gewitter","die Wolke","der Wind","die Temperatur","die Vorhersage","der Frost","die Hitze","bewölkt","neblig"],
 "lines":[
  ["Moderator","Und jetzt die Vorhersage für morgen. Am Morgen ist es neblig, besonders an den Flüssen.","والآن التوقعات ليوم غد. صباحاً ضباب، خصوصاً قرب الأنهار."],
  ["Meteorologin","Richtig. Bis zehn Uhr bleibt es bewölkt, dann kommt die Sonne.","صحيح. حتى العاشرة يبقى الجو غائماً ثم تظهر الشمس."],
  ["Moderator","Wie warm wird es?","كم ستكون الحرارة؟"],
  ["Meteorologin","Die Temperatur steigt auf 27 Grad. Das ist keine Hitze, aber sehr warm für April.","تصل الحرارة إلى 27 درجة. ليس حرّاً شديداً لكنه دافئ جداً لشهر أبريل."],
  ["Moderator","Und am Abend?","وفي المساء؟"],
  ["Meteorologin","Am Abend kommt starker Wind aus dem Westen, und in den Bergen gibt es ein Gewitter.","في المساء تأتي رياح قوية من الغرب، وفي الجبال عاصفة رعدية."],
  ["Moderator","Also kein Frost mehr in der Nacht?","إذن لا صقيع بعد الآن في الليل؟"],
  ["Meteorologin","Nein, kein Frost. Aber nehmen Sie eine Jacke mit, der Wind ist kalt.","لا، لا صقيع. لكن خذوا سترة معكم، فالرياح باردة."]],
 "questions":[
  {"type":"mc","promptDe":"Wie ist das Wetter morgen früh?","options":["neblig, besonders an den Flüssen","sonnig ab dem Morgen","ein Gewitter in den Bergen"],"answer":"neblig, besonders an den Flüssen","explanationAr":"الدليل: «Am Morgen ist es neblig, besonders an den Flüssen». الفخّ 1: الشمس بعد العاشرة. الفخّ 2: العاصفة في المساء."},
  {"type":"mc","promptDe":"Wo gibt es am Abend ein Gewitter?","options":["an den Flüssen","in den Bergen","im Westen"],"answer":"in den Bergen","explanationAr":"الدليل: «in den Bergen gibt es ein Gewitter». الفخّ 1: الأنهار مكان الضباب. الفخّ 2: الغرب مصدر الرياح."},
  {"type":"truefalse","promptDe":"In der Nacht gibt es Frost.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Nein, kein Frost»."}],
 "dictation":["Bis zehn Uhr bleibt es bewölkt, dann kommt die Sonne.","Am Abend kommt starker Wind aus dem Westen, und in den Bergen gibt es ein Gewitter."]},
{"id":"d-a2-13","titleDe":"Der erste Arbeitstag","titleAr":"أول يوم عمل",
 "waisen":["die Einarbeitung","die Fortbildung","die Teamarbeit","die Kenntnisse","sich vorstellen","der Zeitdruck","die Firma","pünktlich"],
 "lines":[
  ["Chefin","Willkommen in der Firma, Frau Mansour! Darf ich Sie dem Team vorstellen?","أهلاً بك في الشركة سيدة منصور! هل أقدّمك للفريق؟"],
  ["Frau Mansour","Sehr gern. Ich bin etwas nervös, aber ich freue mich.","بكل سرور. أنا متوترة قليلاً لكنني سعيدة."],
  ["Chefin","Die Einarbeitung dauert vier Wochen. In dieser Zeit gibt es keinen Zeitdruck.","فترة التأهيل تدوم أربعة أسابيع. في هذه الفترة لا ضغط وقت."],
  ["Frau Mansour","Das ist gut. Und wer erklärt mir das Programm am Computer, Sie als Chefin?","هذا جيد. ومن يشرح لي البرنامج على الحاسوب، أنتِ كمديرة؟"],
  ["Chefin","Ihr Kollege Tom. Er hat gute Kenntnisse und viel Geduld. Teamarbeit ist bei uns wichtig.","زميلك توم. لديه معرفة جيدة وصبر كبير. العمل الجماعي مهم عندنا."],
  ["Frau Mansour","Gibt es auch eine Fortbildung?","هل يوجد تكوين مستمر أيضاً؟"],
  ["Chefin","Ja, im Herbst, zwei Tage in Köln. Die Firma bezahlt alles.","نعم، في الخريف، يومان في كولن. الشركة تدفع كل شيء."],
  ["Frau Mansour","Danke! Ich bin morgen pünktlich um acht da.","شكراً! سأكون هنا غداً في الثامنة بالضبط."]],
 "questions":[
  {"type":"mc","promptDe":"Wie lange dauert die Einarbeitung?","options":["vier Wochen","zwei Tage","bis zum Herbst"],"answer":"vier Wochen","explanationAr":"الدليل: «Die Einarbeitung dauert vier Wochen». الفخّ 1: يومان هي مدة التكوين في كولن. الفخّ 2: الخريف موعد التكوين."},
  {"type":"mc","promptDe":"Wer erklärt Frau Mansour das Programm?","options":["die Chefin","ihr Kollege Tom","ein Trainer in Köln"],"answer":"ihr Kollege Tom","explanationAr":"الدليل: «Ihr Kollege Tom. Er hat gute Kenntnisse und viel Geduld». الفخّ 1: المديرة تقدّمها للفريق فقط. الفخّ 2: كولن مكان التكوين."},
  {"type":"fill","promptDe":"In dieser Zeit gibt es keinen ___.","answer":["Zeitdruck"],"explanationAr":"الدليل: «In dieser Zeit gibt es keinen Zeitdruck»."}],
 "dictation":["Die Einarbeitung dauert vier Wochen.","Teamarbeit ist bei uns wichtig."]},
{"id":"d-a2-14","titleDe":"Ankunft im Hotel","titleAr":"الوصول إلى الفندق",
 "waisen":["die Landung","die Rezeption","das Einzelzimmer","die Übernachtung","der Reiseführer","die Aussicht","sich verlaufen","der Notausgang","das Trinkgeld","das Gepäck"],
 "lines":[
  ["Gast","Guten Abend. Ich habe ein Einzelzimmer reserviert, auf den Namen Trabelsi.","مساء الخير. حجزت غرفة مفردة باسم الطرابلسي."],
  ["Rezeption","Willkommen! Wie war der Flug?","أهلاً! كيف كانت الرحلة؟"],
  ["Gast","Lang, aber die Landung war pünktlich. Ich habe nur ein kleines Gepäck.","طويلة، لكن الهبوط كان في موعده. معي أمتعة صغيرة فقط."],
  ["Rezeption","Zimmer 312, dritter Stock, mit Aussicht auf den Fluss. Drei Übernachtungen, richtig?","الغرفة 312، الطابق الثالث، بإطلالة على النهر. ثلاث ليالٍ، صحيح؟"],
  ["Gast","Ja. Haben Sie einen Reiseführer für die Stadt? Ich verlaufe mich schnell.","نعم. هل لديكم دليل سياحي للمدينة؟ أضيع بسرعة."],
  ["Rezeption","Hier, kostenlos. Der Notausgang ist am Ende des Flurs, links.","تفضّل، مجاناً. مخرج الطوارئ في نهاية الممر، يساراً."],
  ["Gast","Danke. Gibt man hier Trinkgeld?","شكراً. هل يُعطى بقشيش هنا؟"],
  ["Rezeption","Das ist freiwillig, ein bis zwei Euro sind üblich.","هذا اختياري، يورو أو اثنان هو المعتاد."]],
 "questions":[
  {"type":"mc","promptDe":"Was für ein Zimmer hat der Gast?","options":["ein Einzelzimmer mit Aussicht auf den Fluss","ein Doppelzimmer im dritten Stock","ein Zimmer am Ende des Flurs, links"],"answer":"ein Einzelzimmer mit Aussicht auf den Fluss","explanationAr":"الدليل: «Ich habe ein Einzelzimmer reserviert» و«mit Aussicht auf den Fluss». الفخّ 1: الطابق الثالث صحيح لكن الغرفة مفردة لا مزدوجة. الفخّ 2: نهاية الممر يساراً هو مخرج الطوارئ."},
  {"type":"mc","promptDe":"Wie viele Übernachtungen bleibt er?","options":["drei","zwei","eine Übernachtung"],"answer":"drei","explanationAr":"الدليل: «Drei Übernachtungen, richtig?» … «Ja». الفخّ: «ein bis zwei Euro» هو البقشيش."},
  {"type":"truefalse","promptDe":"Der Reiseführer kostet zwei Euro.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Hier, kostenlos». اليورو أو الاثنان هما البقشيش المعتاد."}],
 "dictation":["Lang, aber die Landung war pünktlich.","Der Notausgang ist am Ende des Flurs, links."]},
{"id":"d-a2-15","titleDe":"Zusammen kochen","titleAr":"نطبخ معاً",
 "waisen":["die Zutat","das Mehl","braten","die Soße","der Pfeffer","der Backofen","vorheizen","die Schüssel","umrühren","einfrieren","auftauen"],
 "lines":[
  ["Lina","Hast du alle Zutaten? Mehl, Eier, Milch und Zwiebeln?","هل لديك كل المكونات؟ طحين وبيض وحليب وبصل؟"],
  ["Yusuf","Ja. Das Fleisch habe ich gestern aus dem Gefrierfach genommen, es ist aufgetaut.","نعم. اللحم أخرجته أمس من الفريزر، وقد ذاب."],
  ["Lina","Gut. Zuerst den Backofen vorheizen, 180 Grad.","جيد. أولاً نسخّن الفرن مسبقاً، 180 درجة."],
  ["Yusuf","Und ich brate die Zwiebeln in der Pfanne?","وأنا أقلي البصل في المقلاة؟"],
  ["Lina","Ja, langsam. Dann Mehl und Milch in die Schüssel und gut umrühren, sonst gibt es Klumpen.","نعم، ببطء. ثم الطحين والحليب في الوعاء ونحرّك جيداً وإلا تكوّنت كتل."],
  ["Yusuf","Kommt Pfeffer in die Soße?","هل يُضاف الفلفل إلى الصلصة؟"],
  ["Lina","Nur ein bisschen, am Ende. Salz haben wir schon.","قليلاً فقط، في النهاية. الملح وضعناه."],
  ["Yusuf","Und den Rest frieren wir ein? Das reicht für zwei Tage.","والباقي نجمّده؟ يكفي ليومين."]],
 "questions":[
  {"type":"mc","promptDe":"Was hat Yusuf gestern gemacht?","options":["das Fleisch aus dem Gefrierfach genommen","die Zwiebeln gebraten","den Backofen vorgeheizt"],"answer":"das Fleisch aus dem Gefrierfach genommen","explanationAr":"الدليل: «Das Fleisch habe ich gestern aus dem Gefrierfach genommen». الفخّ 1: القلي الآن. الفخّ 2: التسخين هو أول خطوة اليوم."},
  {"type":"mc","promptDe":"Warum soll man gut umrühren?","options":["damit die Soße scharf wird","weil es sonst Klumpen gibt","damit das Fleisch auftaut"],"answer":"weil es sonst Klumpen gibt","explanationAr":"الدليل: «gut umrühren, sonst gibt es Klumpen». الفخّ 1: الفلفل هو ما يخصّ الحرارة. الفخّ 2: اللحم ذاب أمس."},
  {"type":"fill","promptDe":"Zuerst den Backofen ___, 180 Grad.","answer":["vorheizen"],"explanationAr":"الدليل: «Zuerst den Backofen vorheizen, 180 Grad»."}],
 "dictation":["Zuerst den Backofen vorheizen, 180 Grad.","Kommt Pfeffer in die Soße?"]},
{"id":"d-a2-16","titleDe":"Sicherheit in der Werkstatt","titleAr":"السلامة في الورشة",
 "waisen":["die Schutzkleidung","der Helm","die Warnung","die Unterweisung","die Anweisung","befolgen","der Arbeitsunfall","der Erste-Hilfe-Kasten","die Arbeitssicherheit"],
 "lines":[
  ["Meister","Bevor Sie anfangen, gibt es eine Unterweisung zur Arbeitssicherheit. Das dauert eine halbe Stunde.","قبل أن تبدأ، هناك تعليم في السلامة المهنية. يستغرق نصف ساعة."],
  ["Azubi","Muss ich immer den Helm tragen?","هل يجب أن أرتدي الخوذة دائماً؟"],
  ["Meister","In der Halle ja, und die Schutzkleidung auch: Schuhe, Brille, Handschuhe.","في القاعة نعم، وملابس الوقاية أيضاً: الحذاء والنظارة والقفازات."],
  ["Azubi","Und wenn ich eine Anweisung nicht verstehe?","وإذا لم أفهم تعليمة؟"],
  ["Meister","Dann fragen Sie sofort. Jede Anweisung muss man befolgen, aber erst, wenn man sie verstanden hat.","اسأل فوراً. كل تعليمة يجب اتباعها، لكن بعد فهمها أولاً."],
  ["Azubi","Was passiert bei einem Arbeitsunfall?","ماذا يحدث عند حادث عمل؟"],
  ["Meister","Erste Hilfe, dann Meldung an mich als Meister. Der Erste-Hilfe-Kasten hängt neben der Tür, rot.","إسعاف أولي، ثم إبلاغي أنا المعلّم. صندوق الإسعاف معلّق قرب الباب، أحمر."],
  ["Azubi","Verstanden. Und das gelbe Schild dort ist eine Warnung?","مفهوم. واللافتة الصفراء هناك تحذير؟"]],
 "questions":[
  {"type":"mc","promptDe":"Wann muss man eine Anweisung befolgen?","options":["sofort, auch ohne sie zu verstehen","erst, wenn man sie verstanden hat","nur bei einem Arbeitsunfall"],"answer":"erst, wenn man sie verstanden hat","explanationAr":"الدليل: «Jede Anweisung muss man befolgen, aber erst, wenn man sie verstanden hat». الفخّ 1: «sofort» تخصّ السؤال. الفخّ 2: الحادث موضوع آخر."},
  {"type":"mc","promptDe":"Wo ist der Erste-Hilfe-Kasten?","options":["neben der Tür","in der Halle beim gelben Schild","beim Meister"],"answer":"neben der Tür","explanationAr":"الدليل: «Der Erste-Hilfe-Kasten hängt neben der Tür, rot». الفخّ 1: اللافتة الصفراء تحذير. الفخّ 2: المعلّم يُبلَّغ بعد الإسعاف."},
  {"type":"truefalse","promptDe":"Die Unterweisung dauert eine Stunde.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Das dauert eine halbe Stunde»."}],
 "dictation":["In der Halle ja, und die Schutzkleidung auch: Schuhe, Brille, Handschuhe.","Der Erste-Hilfe-Kasten hängt neben der Tür, rot."]},
{"id":"d-a2-17","titleDe":"In der Sprachschule","titleAr":"في مدرسة اللغة",
 "waisen":["der Einstufungstest","die Zwischenprüfung","nachholen","der Lernpartner","die Motivation","dranbleiben","der Akzent","der Wortschatz","die Grammatikregel","die Sprachschule"],
 "lines":[
  ["Lehrerin","Herr Ben Ali, Sie waren letzte Woche krank. Die Zwischenprüfung können Sie am Freitag nachholen.","سيد بن علي، كنت مريضاً الأسبوع الماضي. يمكنك تعويض الامتحان النصفي يوم الجمعة."],
  ["Ben Ali","Danke. Ich habe Angst vor dem Grammatikteil.","شكراً. أخاف من جزء القواعد."],
  ["Lehrerin","Die Grammatikregeln kennen Sie. Ihr Problem ist der Wortschatz: zu wenige Wörter.","القواعد تعرفها. مشكلتك هي المفردات: كلمات قليلة جداً."],
  ["Ben Ali","Wie viele Wörter pro Tag sind gut?","كم كلمة في اليوم أمر جيد؟"],
  ["Lehrerin","Zehn, aber jeden Tag. Suchen Sie sich einen Lernpartner, das hilft bei der Motivation.","عشر، لكن كل يوم. ابحث عن شريك تعلّم، هذا يساعد على التحفيز."],
  ["Ben Ali","Und mein Akzent? Die Leute verstehen mich nicht immer.","ولكنتي؟ الناس لا يفهمونني دائماً."],
  ["Lehrerin","Der Akzent ist kein Problem, wenn Sie langsam sprechen. Wichtig ist: dranbleiben.","اللكنة ليست مشكلة إذا تكلمت ببطء. المهم: الاستمرار."],
  ["Ben Ali","Gut. Beim Einstufungstest im September war ich noch bei A1.","حسناً. في اختبار تحديد المستوى في سبتمبر كنت ما زلت في A1."]],
 "questions":[
  {"type":"mc","promptDe":"Was ist laut Lehrerin das Problem von Herrn Ben Ali?","options":["die Grammatikregeln","der Wortschatz","der Akzent"],"answer":"der Wortschatz","explanationAr":"الدليل: «Ihr Problem ist der Wortschatz: zu wenige Wörter». الفخّ 1: القواعد «kennen Sie». الفخّ 2: اللكنة «kein Problem»."},
  {"type":"mc","promptDe":"Wann kann er die Zwischenprüfung nachholen?","options":["am Freitag","im September","nächste Woche"],"answer":"am Freitag","explanationAr":"الدليل: «können Sie am Freitag nachholen». الفخّ 1: سبتمبر موعد اختبار المستوى. الفخّ 2: الأسبوع الماضي كان مريضاً."},
  {"type":"fill","promptDe":"Suchen Sie sich einen ___, das hilft bei der Motivation.","answer":["Lernpartner"],"explanationAr":"الدليل: «Suchen Sie sich einen Lernpartner, das hilft bei der Motivation»."}],
 "dictation":["Ihr Problem ist der Wortschatz: zu wenige Wörter.","Wichtig ist: dranbleiben."]},
{"id":"d-a2-18","titleDe":"Wohnungsübergabe","titleAr":"تسليم الشقة",
 "waisen":["die Übergabe","das Protokoll","streichen","die Wohnfläche","der Quadratmeter","die Warmmiete","der Stellplatz","die Hausverwaltung","die Nachmieter suchen"],
 "lines":[
  ["Vermieter","So, die Übergabe. Ich schreibe alles ins Protokoll: Zählerstand, Schlüssel, Schäden.","إذن، التسليم. أكتب كل شيء في المحضر: قراءة العدّاد، المفاتيح، الأضرار."],
  ["Mieter","Die Wände habe ich letzte Woche weiß gestrichen.","الجدران دهنتها بالأبيض الأسبوع الماضي."],
  ["Vermieter","Sehr gut, das sehe ich. Die Wohnfläche sind 54 Quadratmeter, alles sauber.","ممتاز، أرى ذلك. مساحة السكن 54 متراً مربعاً، كل شيء نظيف."],
  ["Mieter","Bekomme ich die Kaution bald zurück?","هل أسترد الضمانة قريباً؟"],
  ["Vermieter","Ja, in vier Wochen, nach der letzten Abrechnung der Warmmiete.","نعم، خلال أربعة أسابيع، بعد آخر تسوية للإيجار الشامل."],
  ["Mieter","Und der Stellplatz für das Auto? Den Schlüssel dafür habe ich hier.","وموقف السيارة؟ مفتاحه معي هنا."],
  ["Vermieter","Danke. Haben Sie eigentlich den Nachmieter gefunden?","شكراً. بالمناسبة، هل وجدت المستأجر التالي؟"],
  ["Mieter","Nein, die Hausverwaltung hat ihn gefunden. Er zieht am Ersten ein.","لا، إدارة العقار وجدته. يدخل في الأول من الشهر."]],
 "questions":[
  {"type":"mc","promptDe":"Was hat der Mieter letzte Woche gemacht?","options":["die Wände weiß gestrichen","den Nachmieter gefunden","den Zählerstand ins Protokoll geschrieben"],"answer":"die Wände weiß gestrichen","explanationAr":"الدليل: «Die Wände habe ich letzte Woche weiß gestrichen». الفخّ 1: المستأجر التالي وجدته الإدارة. الفخّ 2: المحضر يكتبه المؤجّر."},
  {"type":"mc","promptDe":"Wann bekommt der Mieter die Kaution zurück?","options":["in vier Wochen, nach der Abrechnung","am Ersten, wenn der Nachmieter einzieht","sofort bei der Übergabe"],"answer":"in vier Wochen, nach der Abrechnung","explanationAr":"الدليل: «in vier Wochen, nach der letzten Abrechnung der Warmmiete». الفخّ 1: الأول من الشهر موعد دخول المستأجر التالي. الفخّ 2: التسليم الآن."},
  {"type":"truefalse","promptDe":"Die Wohnfläche sind 54 Quadratmeter.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Die Wohnfläche sind 54 Quadratmeter, alles sauber»."}],
 "dictation":["Ich schreibe alles ins Protokoll: Zählerstand, Schlüssel, Schäden.","Er zieht am Ersten ein."]},
]
