# -*- coding: utf-8 -*-
"""9 neue A1-Dialoge (d-a1-10..18) aus verwaisten A1-Karten. Sprache: Praesens, kurze Saetze, A1-Wortschatz."""
D = [
{"id":"d-a1-10","titleDe":"Im Restaurant bestellen","titleAr":"الطلب في المطعم",
 "waisen":["die Speisekarte","das Hähnchen","der Fisch","der Salat","das Glas","die Tasse","der Durst","satt","hungrig","süß"],
 "lines":[
  ["Kellnerin","Guten Abend! Hier ist die Speisekarte.","مساء الخير! هذه قائمة الطعام."],
  ["Amir","Danke. Ich bin sehr hungrig. Was ist gut?","شكراً. أنا جائع جداً. ما الجيد عندكم؟"],
  ["Kellnerin","Das Hähnchen mit Reis oder der Fisch mit Kartoffeln.","الدجاج مع الأرز أو السمك مع البطاطا."],
  ["Amir","Ich nehme den Fisch und einen kleinen Salat.","آخذ السمك وسلطة صغيرة."],
  ["Kellnerin","Und zu trinken? Ein Glas Wasser?","وللشرب؟ كأس ماء؟"],
  ["Amir","Ja, ich habe großen Durst. Und danach eine Tasse Tee.","نعم، عندي عطش شديد. وبعدها فنجان شاي."],
  ["Kellnerin","Möchten Sie auch etwas Süßes? Der Kuchen ist heute frisch.","هل تريد شيئاً حلواً أيضاً؟ الكعك طازج اليوم."],
  ["Amir","Nein danke, nach dem Fisch bin ich satt.","لا شكراً، بعد السمك سأشبع."]],
 "questions":[
  {"type":"mc","promptDe":"Was isst Amir?","options":["den Fisch und einen Salat","das Hähnchen mit Reis","den Kuchen"],"answer":"den Fisch und einen Salat","explanationAr":"الدليل: «Ich nehme den Fisch und einen kleinen Salat». الفخّ 1: الدجاج اقتراح النادلة. الفخّ 2: الكعك رفضه."},
  {"type":"mc","promptDe":"Was trinkt Amir zuerst?","options":["ein Glas Wasser","eine Tasse Tee","ein Stück Kuchen"],"answer":"ein Glas Wasser","explanationAr":"الدليل: «Ein Glas Wasser?» … «Ja» ثم «danach eine Tasse Tee». الفخّ: الشاي بعد الأكل."},
  {"type":"truefalse","promptDe":"Amir möchte den Kuchen.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Nein danke, nach dem Fisch bin ich satt»."}],
 "dictation":["Ich bin sehr hungrig.","Ja, ich habe großen Durst."]},
{"id":"d-a1-11","titleDe":"Beim Arzt: Was tut weh?","titleAr":"عند الطبيب: ما الذي يؤلم؟",
 "waisen":["der Körper","das Ohr","die Nase","der Zahn","die Hand","das Bein","der Rücken","der Husten","gesund","sich ausruhen"],
 "lines":[
  ["Ärztin","Guten Tag, Frau Nasri. Was tut weh?","طاب يومك سيدة نصري. ما الذي يؤلمك؟"],
  ["Frau Nasri","Der Rücken tut weh, und ich habe Husten.","الظهر يؤلمني، وعندي سعال."],
  ["Ärztin","Tut auch das Ohr oder die Nase weh?","هل تؤلمك الأذن أو الأنف أيضاً؟"],
  ["Frau Nasri","Die Nase ein bisschen. Das Ohr nicht.","الأنف قليلاً. الأذن لا."],
  ["Ärztin","Und der Zahn? Sie halten die Hand am Mund.","والسنّ؟ تضعين يدك على الفم."],
  ["Frau Nasri","Nein, der Zahn ist gut. Nur der Rücken und der Husten.","لا، السنّ بخير. فقط الظهر والسعال."],
  ["Ärztin","Der Körper braucht Ruhe. Ruhen Sie sich drei Tage aus, bleiben Sie zu Hause.","الجسم يحتاج راحة. استريحي ثلاثة أيام وابقي في البيت."],
  ["Frau Nasri","Und dann bin ich wieder gesund? Mein Bein tut nämlich nicht weh, ich kann laufen.","وبعدها أعود صحيحة؟ ساقي لا تؤلمني، أستطيع المشي."]],
 "questions":[
  {"type":"mc","promptDe":"Was tut Frau Nasri weh?","options":["der Rücken","das Ohr ein bisschen","der Zahn"],"answer":"der Rücken","explanationAr":"الدليل: «Der Rücken tut weh, und ich habe Husten». الفخّ 1: «Das Ohr nicht». الفخّ 2: «der Zahn ist gut»."},
  {"type":"mc","promptDe":"Wie lange soll sie sich ausruhen?","options":["drei Tage","drei Wochen","bis der Husten weg ist"],"answer":"drei Tage","explanationAr":"الدليل: «Ruhen Sie sich drei Tage aus». الفخّ 1: الرقم صحيح والوحدة خاطئة. الفخّ 2: السعال ذُكر كعَرَض لا كشرط."},
  {"type":"truefalse","promptDe":"Die Nase tut ein bisschen weh.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Die Nase ein bisschen»."}],
 "dictation":["Der Rücken tut weh, und ich habe Husten.","Der Körper braucht Ruhe."]},
{"id":"d-a1-12","titleDe":"Kleidung für den Winter","titleAr":"ملابس للشتاء",
 "waisen":["der Mantel","die Mütze","die Socke","das Hemd","die Größe","die Farbe","blau","schwarz","anziehen","das Geld"],
 "lines":[
  ["Verkäufer","Guten Tag! Suchen Sie etwas?","طاب يومك! هل تبحث عن شيء؟"],
  ["Rami","Ja, einen Mantel für den Winter. Größe L.","نعم، معطفاً للشتاء. مقاس L."],
  ["Verkäufer","Welche Farbe? Wir haben blau, schwarz und grau.","أي لون؟ عندنا أزرق وأسود ورمادي."],
  ["Rami","Schwarz, bitte. Kann ich ihn anziehen?","أسود من فضلك. هل أستطيع ارتداءه؟"],
  ["Verkäufer","Natürlich, dort hinten. Brauchen Sie auch eine Mütze?","بالطبع، هناك في الخلف. هل تحتاج قبعة أيضاً؟"],
  ["Rami","Ja, eine blaue Mütze. Und warme Socken.","نعم، قبعة زرقاء. وجوارب دافئة."],
  ["Verkäufer","Der Mantel kostet 89 Euro, die Mütze 12, die Socken 6.","المعطف بـ89 يورو، القبعة 12، الجوارب 6."],
  ["Rami","Gut. Das Hemd nehme ich nicht, ich habe nicht so viel Geld dabei.","حسناً. القميص لا آخذه، ليس معي مال كثير."]],
 "questions":[
  {"type":"mc","promptDe":"Welche Farbe hat der Mantel?","options":["schwarz","blau","grau"],"answer":"schwarz","explanationAr":"الدليل: «Schwarz, bitte». الفخّ 1: القبعة زرقاء. الفخّ 2: الرمادي عرض البائع."},
  {"type":"mc","promptDe":"Was kauft Rami nicht?","options":["das Hemd","die Mütze","die Socken"],"answer":"das Hemd","explanationAr":"الدليل: «Das Hemd nehme ich nicht». الفخّ: القبعة والجوارب يأخذهما."},
  {"type":"fill","promptDe":"Der Mantel kostet ___ Euro.","answer":["89","neunundachtzig"],"explanationAr":"الدليل: «Der Mantel kostet 89 Euro»."}],
 "dictation":["Ja, einen Mantel für den Winter.","Welche Farbe? Wir haben blau, schwarz und grau."]},
{"id":"d-a1-13","titleDe":"Am Bahnhof: Der Zug nach Köln","titleAr":"في المحطة: القطار إلى كولن",
 "waisen":["ankommen","abfahren","die Abfahrt","die Ankunft","der Sitzplatz","das Gepäckstück","Viertel vor","Viertel nach","pünktlich sein"],
 "lines":[
  ["Sami","Entschuldigung, wann fährt der Zug nach Köln ab?","عفواً، متى ينطلق القطار إلى كولن؟"],
  ["Mitarbeiterin","Abfahrt um Viertel nach neun, Gleis 4.","الانطلاق في التاسعة والربع، الرصيف 4."],
  ["Sami","Und wann kommt er in Köln an?","ومتى يصل إلى كولن؟"],
  ["Mitarbeiterin","Ankunft um Viertel vor zwölf. Der Zug ist meistens pünktlich.","الوصول في الثانية عشرة إلا ربعاً. القطار في موعده غالباً."],
  ["Sami","Brauche ich einen Sitzplatz?","هل أحتاج مقعداً محجوزاً؟"],
  ["Mitarbeiterin","Heute ja, der Zug ist voll. Ein Sitzplatz kostet vier Euro.","اليوم نعم، القطار ممتلئ. المقعد بأربعة يورو."],
  ["Sami","Gut. Ich habe zwei Gepäckstücke, einen Koffer und eine Tasche.","حسناً. معي قطعتا أمتعة، حقيبة سفر وحقيبة يد."],
  ["Mitarbeiterin","Kein Problem. Seien Sie bitte pünktlich am Gleis.","لا مشكلة. كن في الرصيف في الوقت من فضلك."]],
 "questions":[
  {"type":"mc","promptDe":"Wann fährt der Zug ab?","options":["um Viertel nach neun","um Viertel vor zwölf","um vier Uhr"],"answer":"um Viertel nach neun","explanationAr":"الدليل: «Abfahrt um Viertel nach neun». الفخّ 1: الثانية عشرة إلا ربعاً هي الوصول. الفخّ 2: أربعة يورو ثمن المقعد."},
  {"type":"mc","promptDe":"Warum braucht Sami heute einen Sitzplatz?","options":["Der Zug ist voll.","Er hat zwei Gepäckstücke.","Der Zug ist nicht pünktlich."],"answer":"Der Zug ist voll.","explanationAr":"الدليل: «Heute ja, der Zug ist voll». الفخّ 1: الأمتعة سبب آخر لم يُربط بالمقعد. الفخّ 2: القطار «meistens pünktlich»."},
  {"type":"truefalse","promptDe":"Der Zug fährt von Gleis 4.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Abfahrt um Viertel nach neun, Gleis 4»."}],
 "dictation":["Und wann kommt er in Köln an?","Heute ja, der Zug ist voll."]},
{"id":"d-a1-14","titleDe":"Auf der Post","titleAr":"في مكتب البريد",
 "waisen":["das Paket","die Briefmarke","der Umschlag","die Postleitzahl","abholen","Österreich","das Ausland","schließen","geöffnet"],
 "lines":[
  ["Kundin","Guten Tag. Ich möchte ein Paket nach Österreich schicken.","طاب يومك. أريد إرسال طرد إلى النمسا."],
  ["Mitarbeiter","Ins Ausland, gut. Ist die Adresse mit Postleitzahl auf dem Paket?","إلى الخارج، حسناً. هل العنوان مع الرمز البريدي على الطرد؟"],
  ["Kundin","Ja, hier: 1010 Wien. Was kostet das?","نعم، هنا: 1010 فيينا. كم يكلّف؟"],
  ["Mitarbeiter","Neun Euro. Und für den Brief brauchen Sie eine Briefmarke für 85 Cent.","تسعة يورو. وللرسالة تحتاجين طابعاً بـ85 سنتاً."],
  ["Kundin","Danke. Haben Sie auch einen Umschlag?","شكراً. هل لديكم ظرف أيضاً؟"],
  ["Mitarbeiter","Ja, zwanzig Cent. Noch etwas?","نعم، عشرون سنتاً. شيء آخر؟"],
  ["Kundin","Mein Mann möchte morgen ein Paket abholen. Wann ist geöffnet?","زوجي يريد استلام طرد غداً. متى تفتحون؟"],
  ["Mitarbeiter","Von acht bis achtzehn Uhr. Am Samstag schließen wir um zwölf.","من الثامنة إلى السادسة مساءً. يوم السبت نغلق في الثانية عشرة."]],
 "questions":[
  {"type":"mc","promptDe":"Wohin schickt die Kundin das Paket?","options":["nach Österreich","ins Ausland zu ihrem Mann","nach Wien zum Abholen"],"answer":"nach Österreich","explanationAr":"الدليل: «ein Paket nach Österreich schicken». الفخّ 1: الزوج يستلم طرداً هنا غداً لا في الخارج. الفخّ 2: فيينا وجهة الطرد لا مكان الاستلام."},
  {"type":"mc","promptDe":"Was kostet die Briefmarke?","options":["85 Cent","20 Cent","neun Euro"],"answer":"85 Cent","explanationAr":"الدليل: «eine Briefmarke für 85 Cent». الفخّ 1: 20 سنتاً الظرف. الفخّ 2: تسعة يورو الطرد."},
  {"type":"truefalse","promptDe":"Am Samstag ist die Post bis achtzehn Uhr geöffnet.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Am Samstag schließen wir um zwölf»."}],
 "dictation":["Ich möchte ein Paket nach Österreich schicken.","Am Samstag schließen wir um zwölf."]},
{"id":"d-a1-15","titleDe":"Die neue Wohnung","titleAr":"الشقة الجديدة",
 "waisen":["das Badezimmer","die Toilette","der Flur","der Stuhl","das Sofa","der Boden","der Schlüssel","möbliert","sauber","schmutzig"],
 "lines":[
  ["Vermieterin","Hier ist der Schlüssel. Die Wohnung ist möbliert.","هذا هو المفتاح. الشقة مفروشة."],
  ["Lina","Schön! Ein Sofa, ein Tisch und vier Stühle.","جميل! أريكة وطاولة وأربعة كراسٍ."],
  ["Vermieterin","Der Flur ist klein, aber das Badezimmer ist groß.","الممر صغير لكن الحمّام كبير."],
  ["Lina","Ist die Toilette im Badezimmer?","هل المرحاض داخل الحمّام؟"],
  ["Vermieterin","Nein, die Toilette ist extra, neben der Küche.","لا، المرحاض منفصل، بجانب المطبخ."],
  ["Lina","Der Boden im Wohnzimmer ist ein bisschen schmutzig.","أرضية الصالة متّسخة قليلاً."],
  ["Vermieterin","Ja, morgen kommt die Putzfrau. Dann ist alles sauber.","نعم، غداً تأتي عاملة التنظيف. عندها يكون كل شيء نظيفاً."],
  ["Lina","Gut. Dann komme ich am Samstag mit meinen Sachen.","حسناً. إذن آتي يوم السبت بأغراضي."]],
 "questions":[
  {"type":"mc","promptDe":"Wo ist die Toilette?","options":["neben der Küche","im Badezimmer","im Flur"],"answer":"neben der Küche","explanationAr":"الدليل: «die Toilette ist extra, neben der Küche». الفخّ 1: «Nein» على سؤال الحمّام. الفخّ 2: الممر صغير فقط."},
  {"type":"mc","promptDe":"Was ist schmutzig?","options":["der Boden im Wohnzimmer","das Badezimmer","das Sofa"],"answer":"der Boden im Wohnzimmer","explanationAr":"الدليل: «Der Boden im Wohnzimmer ist ein bisschen schmutzig». الفخّ 1: الحمّام كبير. الفخّ 2: الأريكة من الأثاث."},
  {"type":"fill","promptDe":"Die Wohnung ist ___.","answer":["möbliert"],"explanationAr":"الدليل: «Die Wohnung ist möbliert»."}],
 "dictation":["Hier ist der Schlüssel.","Der Flur ist klein, aber das Badezimmer ist groß."]},
{"id":"d-a1-16","titleDe":"Ein Spaziergang in der Natur","titleAr":"نزهة في الطبيعة",
 "waisen":["die Natur","der Baum","der Fluss","der Wald","der Himmel","die Luft","das Tier","der Vogel","das Pferd","die Kuh","der Mond"],
 "lines":[
  ["Vater","Komm, wir gehen in den Wald. Die Luft ist heute gut.","تعال، نذهب إلى الغابة. الهواء اليوم جيد."],
  ["Kind","Schau, ein Vogel auf dem Baum! Er singt.","انظر، عصفور على الشجرة! يغرّد."],
  ["Vater","Ja. Und dort am Fluss stehen zwei Pferde.","نعم. وهناك عند النهر يقف حصانان."],
  ["Kind","Ich sehe auch eine Kuh. Ist die Kuh ein Tier aus dem Wald?","أرى بقرة أيضاً. هل البقرة حيوان من الغابة؟"],
  ["Vater","Nein, die Kuh kommt vom Bauernhof. Im Wald leben andere Tiere.","لا، البقرة من المزرعة. في الغابة تعيش حيوانات أخرى."],
  ["Kind","Der Himmel ist so blau. Ich liebe die Natur.","السماء زرقاء جداً. أحب الطبيعة."],
  ["Vater","Ich auch. Am Abend sehen wir dann den Mond.","وأنا أيضاً. في المساء نرى القمر."],
  ["Kind","Können wir morgen wieder kommen?","هل نأتي مجدداً غداً؟"]],
 "questions":[
  {"type":"mc","promptDe":"Wo stehen die Pferde?","options":["am Fluss","auf dem Baum","im Wald"],"answer":"am Fluss","explanationAr":"الدليل: «dort am Fluss stehen zwei Pferde». الفخّ 1: العصفور على الشجرة. الفخّ 2: الغابة هدف النزهة."},
  {"type":"mc","promptDe":"Woher kommt die Kuh?","options":["vom Bauernhof","aus dem Wald","vom Fluss"],"answer":"vom Bauernhof","explanationAr":"الدليل: «die Kuh kommt vom Bauernhof». الفخّ 1: «Nein» على سؤال الغابة."},
  {"type":"truefalse","promptDe":"Der Vogel singt auf dem Baum.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «ein Vogel auf dem Baum! Er singt»."}],
 "dictation":["Die Luft ist heute gut.","Der Himmel ist so blau."]},
{"id":"d-a1-17","titleDe":"Hausarbeit am Samstag","titleAr":"أعمال البيت يوم السبت",
 "waisen":["die Wäsche","bügeln","kehren","die Seife","das Handtuch","der Herd","der Topf","die Pfanne","voll","leer","der Schmutz"],
 "lines":[
  ["Mutter","Heute ist Samstag. Wir machen zusammen die Hausarbeit.","اليوم السبت. نقوم بأعمال البيت معاً."],
  ["Sohn","Okay. Was mache ich?","حسناً. ماذا أفعل؟"],
  ["Mutter","Du kehrst die Küche. Da ist viel Schmutz auf dem Boden.","تكنس المطبخ. هناك وسخ كثير على الأرض."],
  ["Sohn","Und der Herd? Der Topf und die Pfanne sind noch schmutzig.","والموقد؟ القدر والمقلاة ما زالا متّسخين."],
  ["Mutter","Die wasche ich mit Seife. Der Mülleimer ist voll, bring ihn bitte raus.","أغسلهما بالصابون. سلة القمامة ممتلئة، أخرجها من فضلك."],
  ["Sohn","Gut. Und die Wäsche? Der Korb ist auch voll.","حسناً. والغسيل؟ السلة ممتلئة أيضاً."],
  ["Mutter","Die Wäsche wasche ich, du bügelst danach die Hemden.","الغسيل أغسله أنا، وأنت تكوي القمصان بعده."],
  ["Sohn","Und die Handtücher? Der Schrank ist leer.","والمناشف؟ الخزانة فارغة."]],
 "questions":[
  {"type":"mc","promptDe":"Was macht der Sohn zuerst?","options":["Er kehrt die Küche.","Er wäscht den Topf.","Er bügelt die Hemden."],"answer":"Er kehrt die Küche.","explanationAr":"الدليل: «Du kehrst die Küche». الفخّ 1: القدر تغسله الأم. الفخّ 2: الكيّ «danach»."},
  {"type":"mc","promptDe":"Was ist leer?","options":["der Schrank","der Mülleimer","der Korb mit der Wäsche"],"answer":"der Schrank","explanationAr":"الدليل: «Der Schrank ist leer». الفخّ: سلة القمامة وسلة الغسيل «voll»."},
  {"type":"fill","promptDe":"Die wasche ich mit ___.","answer":["Seife"],"explanationAr":"الدليل: «Die wasche ich mit Seife»."}],
 "dictation":["Da ist viel Schmutz auf dem Boden.","Der Mülleimer ist voll, bring ihn bitte raus."]},
{"id":"d-a1-18","titleDe":"Woher kommst du?","titleAr":"من أين أنت؟",
 "waisen":["die Heimat","der Ausländer","die Nationalität","die Muttersprache","das Wörterbuch","übersetzen","die Sprache","der Nachname","ledig","verheiratet"],
 "lines":[
  ["Lehrer","Herr Haddad, welche Nationalität haben Sie?","سيد حدّاد، ما جنسيتك؟"],
  ["Haddad","Ich bin Tunesier. Meine Heimat ist Sfax.","أنا تونسي. وطني صفاقس."],
  ["Lehrer","Und Ihre Muttersprache ist Arabisch?","ولغتك الأم العربية؟"],
  ["Haddad","Ja. Ich spreche auch Französisch. Deutsch ist meine dritte Sprache.","نعم. أتكلم الفرنسية أيضاً. الألمانية لغتي الثالثة."],
  ["Lehrer","Sehr gut. Wie schreibt man Ihren Nachnamen?","ممتاز. كيف يُكتب اسم عائلتك؟"],
  ["Haddad","H-A-D-D-A-D. Darf ich im Kurs ein Wörterbuch benutzen?","H-A-D-D-A-D. هل يمكنني استعمال قاموس في الدورة؟"],
  ["Lehrer","Ja, aber übersetzen Sie nicht jedes Wort. Sind Sie verheiratet?","نعم، لكن لا تترجم كل كلمة. هل أنت متزوج؟"],
  ["Haddad","Nein, ich bin ledig. Viele Ausländer im Kurs sind auch ledig.","لا، أنا أعزب. كثير من الأجانب في الدورة عزّاب أيضاً."]],
 "questions":[
  {"type":"mc","promptDe":"Welche Sprache ist die dritte Sprache von Herrn Haddad?","options":["Deutsch","Französisch","Arabisch"],"answer":"Deutsch","explanationAr":"الدليل: «Deutsch ist meine dritte Sprache». الفخّ 1: الفرنسية الثانية. الفخّ 2: العربية الأم."},
  {"type":"mc","promptDe":"Ist Herr Haddad verheiratet?","options":["Nein, er ist ledig.","Ja, seine Frau ist in Sfax.","Ja, er ist verheiratet."],"answer":"Nein, er ist ledig.","explanationAr":"الدليل: «Nein, ich bin ledig». الفخّ: صفاقس هي الوطن لا مكان الزوجة."},
  {"type":"truefalse","promptDe":"Er darf im Kurs ein Wörterbuch benutzen.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Ja, aber übersetzen Sie nicht jedes Wort»."}],
 "dictation":["Meine Heimat ist Sfax.","Deutsch ist meine dritte Sprache."]},
]
