# -*- coding: utf-8 -*-
"""9 neue A2-Dialoge (d-a2-19..27) aus verwaisten A2-Karten — schliesst A2 auf 29 Dialoge."""
D = [
{"id":"d-a2-19","titleDe":"Im Bürgeramt: Ausweis verlängern","titleAr":"في مكتب المواطنين: تمديد البطاقة",
 "waisen":["der Personalausweis","verlängern","die Bearbeitungszeit","vollständig","unvollständig","die Unterschrift","die Vollmacht","der Ansprechpartner","die Auskunft"],
 "lines":[
  ["Sachbearbeiterin","Guten Tag. Sie möchten den Personalausweis verlängern?","طاب يومك. تريد تمديد بطاقة الهوية؟"],
  ["Amir","Ja, er läuft nächsten Monat ab. Sind meine Unterlagen vollständig?","نعم، تنتهي صلاحيتها الشهر القادم. هل أوراقي كاملة؟"],
  ["Sachbearbeiterin","Fast. Das Foto ist da, aber die Unterschrift auf dem Formular fehlt. So ist der Antrag unvollständig.","تقريباً. الصورة موجودة لكن التوقيع على الاستمارة ناقص. هكذا الطلب غير مكتمل."],
  ["Amir","Oh, Entschuldigung. Hier, bitte. Wie lange ist die Bearbeitungszeit?","عذراً. تفضّلي. كم مدة المعالجة؟"],
  ["Sachbearbeiterin","Etwa drei Wochen. Sie bekommen dann einen Brief.","حوالي ثلاثة أسابيع. ستصلك رسالة بعدها."],
  ["Amir","Kann meine Frau den Ausweis abholen? Ich arbeite tagsüber.","هل تستطيع زوجتي استلام البطاقة؟ أنا أعمل نهاراً."],
  ["Sachbearbeiterin","Ja, mit einer Vollmacht von Ihnen und ihrem eigenen Ausweis.","نعم، بتوكيل منك وبطاقتها الشخصية."],
  ["Amir","Und wer ist mein Ansprechpartner, wenn ich eine Auskunft brauche?","ومن هو الشخص المسؤول إذا احتجت معلومة؟"]],
 "questions":[
  {"type":"mc","promptDe":"Warum ist der Antrag zuerst unvollständig?","options":["Das Foto fehlt.","Die Unterschrift auf dem Formular fehlt.","Die Vollmacht fehlt."],"answer":"Die Unterschrift auf dem Formular fehlt.","explanationAr":"الدليل: «Das Foto ist da, aber die Unterschrift auf dem Formular fehlt». الفخّ 1: الصورة موجودة. الفخّ 2: التوكيل يخصّ استلام الزوجة."},
  {"type":"mc","promptDe":"Was braucht die Frau von Amir zum Abholen?","options":["eine Vollmacht und ihren eigenen Ausweis","nur den Brief vom Amt","das Foto und das Formular"],"answer":"eine Vollmacht und ihren eigenen Ausweis","explanationAr":"الدليل: «mit einer Vollmacht von Ihnen und ihrem eigenen Ausweis». الفخّ 1: الرسالة تُعلم بالجاهزية فقط. الفخّ 2: الصورة والاستمارة للطلب."},
  {"type":"truefalse","promptDe":"Die Bearbeitungszeit beträgt etwa drei Tage.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Etwa drei Wochen. Sie bekommen dann einen Brief» — أسابيع لا أيام."}],
 "dictation":["Sie möchten den Personalausweis verlängern?","Etwa drei Wochen. Sie bekommen dann einen Brief."]},
{"id":"d-a2-20","titleDe":"Streit in der WG","titleAr":"خلاف في السكن المشترك",
 "waisen":["die Wohngemeinschaft","aufräumen","die Spülmaschine","abwaschen","die Essensreste","die Rücksicht","die Absprache","ordentlich","chaotisch","zuhören"],
 "lines":[
  ["Nadia","Jonas, wir müssen reden. Die Küche ist seit drei Tagen chaotisch.","يوناس، يجب أن نتكلم. المطبخ فوضوي منذ ثلاثة أيام."],
  ["Jonas","Ich weiß, tut mir leid. Ich hatte diese Woche viel Stress.","أعرف، آسف. كان عندي ضغط كبير هذا الأسبوع."],
  ["Nadia","Die Essensreste stehen auf dem Herd, und die Spülmaschine ist voll, aber niemand macht sie an.","بقايا الطعام على الموقد، وغسّالة الصحون ممتلئة ولا أحد يشغّلها."],
  ["Jonas","Okay. Ich wasche heute Abend alles ab und räume auf.","حسناً. سأغسل كل شيء الليلة وأرتّب."],
  ["Nadia","Danke. In einer Wohngemeinschaft braucht man Rücksicht, sonst funktioniert es nicht.","شكراً. في السكن المشترك نحتاج مراعاة وإلا لا ينجح الأمر."],
  ["Jonas","Du hast recht. Machen wir eine feste Absprache: Ich bin ordentlich in der Küche, du kümmerst dich ums Bad?","معك حق. لنتّفق اتفاقاً ثابتاً: أنا مرتّب في المطبخ، وأنتِ تهتمّين بالحمّام؟"],
  ["Nadia","Einverstanden. Und beim nächsten Problem: erst zuhören, dann streiten.","موافقة. وعند المشكلة القادمة: نستمع أولاً ثم نتخاصم."],
  ["Jonas","Lieber gar nicht streiten.","بل الأفضل ألا نتخاصم أصلاً."]],
 "questions":[
  {"type":"mc","promptDe":"Was ist das Problem mit der Spülmaschine?","options":["Sie steht voll mit Essensresten auf dem Herd.","Sie ist voll, aber niemand macht sie an.","Jonas hat sie heute Abend angemacht."],"answer":"Sie ist voll, aber niemand macht sie an.","explanationAr":"الدليل: «die Spülmaschine ist voll, aber niemand macht sie an». الفخّ 1: بقايا الطعام على الموقد لا في الغسّالة. الفخّ 2: «heute Abend» وعد يوناس بالغسل باليد."},
  {"type":"mc","promptDe":"Welche Absprache schlägt Jonas vor?","options":["Er macht die Küche, Nadia das Bad.","Beide räumen die Küche zusammen auf.","Nadia macht die Küche, er das Bad."],"answer":"Er macht die Küche, Nadia das Bad.","explanationAr":"الدليل: «Ich bin ordentlich in der Küche, du kümmerst dich ums Bad?». الفخّ: قلب الأدوار."},
  {"type":"fill","promptDe":"In einer Wohngemeinschaft braucht man ___, sonst funktioniert es nicht.","answer":["Rücksicht"],"explanationAr":"الدليل: «In einer Wohngemeinschaft braucht man Rücksicht, sonst funktioniert es nicht»."}],
 "dictation":["Die Küche ist seit drei Tagen chaotisch.","Ich wasche heute Abend alles ab und räume auf."]},
{"id":"d-a2-21","titleDe":"Nach dem Fußballspiel","titleAr":"بعد مباراة كرة القدم",
 "waisen":["die Mannschaft","gewinnen","verlieren","die Verletzung","sich verletzen","der Facharzt","die Beschwerden","trösten","hilfsbereit"],
 "lines":[
  ["Trainer","Kopf hoch, Leute. Wir haben verloren, aber die Mannschaft hat gut gespielt.","ارفعوا رؤوسكم يا شباب. خسرنا لكن الفريق لعب جيداً."],
  ["Selim","Zwei zu drei. Ohne die Verletzung von Ali hätten wir gewonnen.","اثنان لثلاثة. لولا إصابة علي لكنّا فزنا."],
  ["Trainer","Wie geht es ihm? Hat er sich schlimm verletzt?","كيف حاله؟ هل أُصيب بشدة؟"],
  ["Selim","Das Knie tut weh. Er hat starke Beschwerden beim Gehen.","الركبة تؤلمه. عنده آلام شديدة عند المشي."],
  ["Trainer","Dann muss er morgen zum Facharzt, nicht nur zum Hausarzt.","إذن عليه غداً الذهاب إلى الطبيب المختص لا طبيب العائلة فقط."],
  ["Selim","Ich fahre ihn hin. Und heute Abend gehen wir alle zu ihm, um ihn zu trösten.","سأوصله. والليلة نذهب جميعاً إليه لنواسيه."],
  ["Trainer","Das ist hilfsbereit von euch. So gewinnt man auch nach einer Niederlage.","هذا تعاون طيب منكم. هكذا يفوز المرء حتى بعد الخسارة."],
  ["Selim","Nächste Woche gewinnen wir dann richtig.","الأسبوع القادم نفوز فعلاً."]],
 "questions":[
  {"type":"mc","promptDe":"Wie ist das Spiel ausgegangen?","options":["Die Mannschaft hat zwei zu drei verloren.","Die Mannschaft hat drei zu zwei gewonnen.","Das Spiel wurde wegen der Verletzung abgebrochen."],"answer":"Die Mannschaft hat zwei zu drei verloren.","explanationAr":"الدليل: «Wir haben verloren» و«Zwei zu drei». الفخّ 1: قلب النتيجة. الفخّ 2: الإصابة لم توقف المباراة."},
  {"type":"mc","promptDe":"Wohin soll Ali morgen gehen?","options":["zum Facharzt","nur zum Hausarzt","zu Ali nach Hause"],"answer":"zum Facharzt","explanationAr":"الدليل: «Dann muss er morgen zum Facharzt, nicht nur zum Hausarzt». الفخّ 1: «nicht nur zum Hausarzt» منفيّ صراحة. الفخّ 2: بيت علي يزوره الأصدقاء مساءً."},
  {"type":"truefalse","promptDe":"Die Freunde besuchen Ali heute Abend.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «heute Abend gehen wir alle zu ihm, um ihn zu trösten»."}],
 "dictation":["Wir haben verloren, aber die Mannschaft hat gut gespielt.","Er hat starke Beschwerden beim Gehen."]},
{"id":"d-a2-22","titleDe":"Die Stromrechnung","titleAr":"فاتورة الكهرباء",
 "waisen":["der Stromanbieter","die Nebenkostenabrechnung","nachzahlen","die Rückzahlung","die Energiekosten","sparsam heizen","vergleichen","der Preisvergleich","die Ausgaben"],
 "lines":[
  ["Fatma","Schau, die Nebenkostenabrechnung ist gekommen. Wir müssen 240 Euro nachzahlen.","انظر، وصلت تسوية المصاريف الجانبية. علينا دفع 240 يورو إضافية."],
  ["Omar","So viel? Letztes Jahr gab es eine Rückzahlung von 80 Euro.","كل هذا؟ السنة الماضية كان هناك استرداد 80 يورو."],
  ["Fatma","Die Energiekosten sind gestiegen. Und wir haben im Winter zu viel geheizt.","ارتفعت تكاليف الطاقة. ونحن دفّأنا كثيراً في الشتاء."],
  ["Omar","Dann heizen wir nächsten Winter sparsam: 20 Grad im Wohnzimmer, nicht 23.","إذن ندفّئ الشتاء القادم باقتصاد: 20 درجة في الصالة لا 23."],
  ["Fatma","Und ich mache einen Preisvergleich. Vielleicht ist ein anderer Stromanbieter billiger.","وأنا أعمل مقارنة أسعار. ربما مزوّد كهرباء آخر أرخص."],
  ["Omar","Gute Idee. Wir sollten alle Ausgaben einmal vergleichen: Strom, Internet, Versicherung.","فكرة جيدة. ينبغي أن نقارن كل المصاريف مرة: الكهرباء والإنترنت والتأمين."],
  ["Fatma","Machen wir am Sonntag. Ich drucke alle Rechnungen aus.","نفعل ذلك يوم الأحد. سأطبع كل الفواتير."],
  ["Omar","Und die 240 Euro? Können wir in Raten zahlen?","والـ240 يورو؟ هل نستطيع الدفع بالتقسيط؟"]],
 "questions":[
  {"type":"mc","promptDe":"Was war letztes Jahr anders?","options":["Es gab eine Rückzahlung von 80 Euro.","Sie mussten 80 Euro nachzahlen.","Der Stromanbieter war billiger."],"answer":"Es gab eine Rückzahlung von 80 Euro.","explanationAr":"الدليل: «Letztes Jahr gab es eine Rückzahlung von 80 Euro». الفخّ 1: قلب الاتجاه. الفخّ 2: تغيير المزوّد فكرة للمستقبل."},
  {"type":"mc","promptDe":"Was will Fatma machen?","options":["einen Preisvergleich der Stromanbieter","alle Rechnungen in Raten zahlen","im Winter 23 Grad heizen"],"answer":"einen Preisvergleich der Stromanbieter","explanationAr":"الدليل: «ich mache einen Preisvergleich. Vielleicht ist ein anderer Stromanbieter billiger». الفخّ 1: التقسيط سؤال عمر. الفخّ 2: 23 درجة هو ما يريدون تركه."},
  {"type":"truefalse","promptDe":"Sie müssen 240 Euro nachzahlen.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Wir müssen 240 Euro nachzahlen»."}],
 "dictation":["Die Energiekosten sind gestiegen.","Vielleicht ist ein anderer Stromanbieter billiger."]},
{"id":"d-a2-23","titleDe":"Einladung zum Fest","titleAr":"دعوة إلى العيد",
 "waisen":["das Fest","der Gast","die Einladung","gratulieren","die Dekoration","die Vorbereitung","vorbereiten","die Speise","probieren","die Gastfreundschaft","das Ramadanfest"],
 "lines":[
  ["Lena","Danke für die Einladung zum Ramadanfest, Salma! Was soll ich mitbringen?","شكراً على دعوة عيد الفطر يا سلمى! ماذا أحضر معي؟"],
  ["Salma","Nur dich selbst. Die Vorbereitung machen wir in der Familie, das ist Tradition.","فقط نفسك. التحضير نقوم به في العائلة، هذا تقليد."],
  ["Lena","Wie viele Gäste kommen?","كم ضيفاً سيأتي؟"],
  ["Salma","Ungefähr zwanzig. Meine Mutter bereitet seit gestern die Speisen vor.","حوالي عشرين. أمي تحضّر الأطباق منذ أمس."],
  ["Lena","Und die Dekoration? Die Lichter am Fenster sind wunderschön.","والزينة؟ الأضواء على النافذة رائعة."],
  ["Salma","Das machen die Kinder. Du musst unbedingt die süßen Speisen probieren.","هذا يصنعه الأطفال. يجب أن تجرّبي الحلويات حتماً."],
  ["Lena","Gern! Wie gratuliert man richtig?","بكل سرور! كيف أهنّئ بشكل صحيح؟"],
  ["Salma","Sag einfach „Frohes Fest“. Gastfreundschaft ist bei uns das Wichtigste.","قولي ببساطة «عيد سعيد». الضيافة عندنا هي الأهم."]],
 "questions":[
  {"type":"mc","promptDe":"Wer macht die Dekoration?","options":["die Kinder","Salmas Mutter","die Gäste"],"answer":"die Kinder","explanationAr":"الدليل: «Und die Dekoration? … Das machen die Kinder». الفخّ 1: الأم تحضّر الأطباق. الفخّ 2: الضيوف يأتون فقط."},
  {"type":"mc","promptDe":"Was soll Lena mitbringen?","options":["nichts, nur sich selbst","süße Speisen","Lichter für das Fenster"],"answer":"nichts, nur sich selbst","explanationAr":"الدليل: «Nur dich selbst». الفخّ 1: الحلويات تجرّبها. الفخّ 2: الأضواء زينة العائلة."},
  {"type":"fill","promptDe":"Ungefähr zwanzig ___ kommen.","answer":["Gäste"],"explanationAr":"الدليل: «Wie viele Gäste kommen?» … «Ungefähr zwanzig»."}],
 "dictation":["Die Vorbereitung machen wir in der Familie, das ist Tradition.","Gastfreundschaft ist bei uns das Wichtigste."]},
{"id":"d-a2-24","titleDe":"Bewerbung für das Stipendium","titleAr":"طلب المنحة الدراسية",
 "waisen":["das Stipendium","der Abschluss","das Gymnasium","die Klassenarbeit","die Note","fleißig","selbstständig","die Bewerbungsunterlagen","die Unterstützung","sich vorbereiten auf"],
 "lines":[
  ["Beraterin","Sie möchten sich für das Stipendium bewerben? Erzählen Sie kurz von sich.","تريد التقدّم للمنحة؟ حدّثني عن نفسك باختصار."],
  ["Youssef","Ich habe letztes Jahr den Abschluss am Gymnasium gemacht, mit guten Noten.","أنهيت الثانوية العامة السنة الماضية بدرجات جيدة."],
  ["Beraterin","Welche Note in Mathematik?","أي درجة في الرياضيات؟"],
  ["Youssef","Eine Zwei. In der letzten Klassenarbeit sogar eine Eins.","اثنان. وفي آخر اختبار حتى واحد."],
  ["Beraterin","Gut. Das Stipendium ist für Studierende, die fleißig und selbstständig arbeiten. Warum brauchen Sie die Unterstützung?","جيد. المنحة للطلبة المجتهدين والمستقلين. لماذا تحتاج الدعم؟"],
  ["Youssef","Meine Eltern können das Studium nicht bezahlen. Ich arbeite nebenbei im Supermarkt.","والداي لا يستطيعان دفع تكاليف الدراسة. أعمل بجانب ذلك في السوبرماركت."],
  ["Beraterin","Verstehe. Schicken Sie die Bewerbungsunterlagen bis zum 15. März: Zeugnis, Lebenslauf und ein kurzes Motivationsschreiben.","فهمت. أرسل وثائق الطلب حتى 15 مارس: الشهادة والسيرة الذاتية ورسالة دوافع قصيرة."],
  ["Youssef","Und wie bereite ich mich auf das Gespräch vor?","وكيف أستعدّ للمقابلة؟"]],
 "questions":[
  {"type":"mc","promptDe":"Welche Note hatte Youssef in der letzten Klassenarbeit?","options":["eine Eins","eine Zwei","eine Zwei in Mathematik und eine Drei in der Klassenarbeit"],"answer":"eine Eins","explanationAr":"الدليل: «In der letzten Klassenarbeit sogar eine Eins». الفخّ 1: «Eine Zwei» هي درجة الرياضيات العامة. الفخّ 2: قلب الدرجتين."},
  {"type":"mc","promptDe":"Warum braucht Youssef das Stipendium?","options":["Seine Eltern können das Studium nicht bezahlen.","Er will nicht mehr im Supermarkt arbeiten.","Er hat schlechte Noten."],"answer":"Seine Eltern können das Studium nicht bezahlen.","explanationAr":"الدليل: «Meine Eltern können das Studium nicht bezahlen». الفخّ 1: العمل في السوبرماركت واقع لا سبب. الفخّ 2: الدرجات جيدة."},
  {"type":"truefalse","promptDe":"Die Bewerbungsunterlagen müssen bis zum 15. April da sein.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل: «Schicken Sie die Bewerbungsunterlagen bis zum 15. März» — مارس لا أبريل."}],
 "dictation":["Welche Note in Mathematik?","Meine Eltern können das Studium nicht bezahlen."]},
{"id":"d-a2-25","titleDe":"Im Zug ohne Ticket","titleAr":"في القطار بلا تذكرة",
 "waisen":["die Fahrkartenkontrolle","schwarzfahren","die Monatskarte","gültig","das Ticket","die Umleitung","die Verbindung","die Auskunft","höflich"],
 "lines":[
  ["Kontrolleur","Fahrkartenkontrolle, bitte. Ihr Ticket?","تفتيش التذاكر من فضلك. تذكرتك؟"],
  ["Rania","Hier ist meine Monatskarte.","هذه بطاقتي الشهرية."],
  ["Kontrolleur","Die ist seit gestern nicht mehr gültig. Der Monat ist zu Ende.","لم تعد صالحة منذ أمس. انتهى الشهر."],
  ["Rania","Oh nein! Das habe ich vergessen. Ich wollte nicht schwarzfahren.","لا! نسيت ذلك. لم أقصد الركوب بلا تذكرة."],
  ["Kontrolleur","Das glaube ich Ihnen. Aber die Regel ist die Regel: 60 Euro.","أصدّقك. لكن القاعدة قاعدة: 60 يورو."],
  ["Rania","Kann ich die neue Monatskarte nachher zeigen? Dann zahle ich weniger, oder?","هل يمكنني إظهار البطاقة الشهرية الجديدة لاحقاً؟ عندها أدفع أقل، صحيح؟"],
  ["Kontrolleur","Ja, innerhalb von einer Woche im Kundenzentrum. Dann sind es nur sieben Euro.","نعم، خلال أسبوع في مركز الزبائن. عندها سبعة يورو فقط."],
  ["Rania","Danke, dass Sie so höflich sind. Noch eine Auskunft bitte: Wegen der Umleitung heute, erreiche ich meine Verbindung am Hauptbahnhof?","شكراً لأنك مهذب. معلومة أخرى من فضلك: بسبب التحويلة اليوم، هل ألحق بقطار الربط في المحطة الرئيسية؟"]],
 "questions":[
  {"type":"mc","promptDe":"Warum ist die Monatskarte nicht gültig?","options":["Der Monat ist zu Ende.","Rania hat die falsche Karte gekauft.","Der Zug fährt eine Umleitung."],"answer":"Der Monat ist zu Ende.","explanationAr":"الدليل: «Die ist seit gestern nicht mehr gültig. Der Monat ist zu Ende». الفخّ 1: لم يُذكر خطأ في الشراء. الفخّ 2: التحويلة موضوع آخر."},
  {"type":"mc","promptDe":"Wie viel zahlt Rania, wenn sie die neue Monatskarte innerhalb einer Woche zeigt?","options":["sieben Euro","60 Euro","sechs Euro"],"answer":"sieben Euro","explanationAr":"الدليل: «innerhalb von einer Woche im Kundenzentrum. Dann sind es nur sieben Euro». الفخّ 1: 60 يورو بلا إثبات. الفخّ 2: sechs/sieben تشابه صوتي."},
  {"type":"fill","promptDe":"Ich wollte nicht ___.","answer":["schwarzfahren"],"explanationAr":"الدليل: «Ich wollte nicht schwarzfahren» — فعل منفصل في المصدر بعد wollte."}],
 "dictation":["Die ist seit gestern nicht mehr gültig.","Aber die Regel ist die Regel: 60 Euro."]},
{"id":"d-a2-26","titleDe":"Klamotten kaufen","titleAr":"شراء ملابس",
 "waisen":["anprobieren","die Umkleidekabine","die Hose","preiswert","das Sonderangebot","die Rückgabe","die Quittung aufheben","bequem sitzen","der Schmuck","altmodisch"],
 "lines":[
  ["Verkäuferin","Kann ich Ihnen helfen?","هل أستطيع مساعدتك؟"],
  ["Mira","Ja, ich suche eine Hose für die Arbeit. Nicht zu teuer.","نعم، أبحث عن بنطال للعمل. ليس غالياً جداً."],
  ["Verkäuferin","Diese hier ist im Sonderangebot: 29 statt 49 Euro. Sehr preiswert.","هذا في عرض خاص: 29 بدل 49 يورو. رخيص جداً."],
  ["Mira","Die Farbe ist ein bisschen altmodisch. Haben Sie sie auch in Dunkelblau?","اللون قديم الطراز قليلاً. هل لديكم منه بالأزرق الداكن؟"],
  ["Verkäuferin","Ja, Größe 38. Die Umkleidekabine ist hinten links. Probieren Sie sie an.","نعم، مقاس 38. غرفة القياس في الخلف يساراً. جرّبيه."],
  ["Mira","Sie sitzt bequem. Ich nehme sie. Und wie ist die Rückgabe, falls sie doch nicht passt?","مريح. سآخذه. وكيف الإرجاع إن لم يناسب في النهاية؟"],
  ["Verkäuferin","Vierzehn Tage, aber nur mit Quittung. Heben Sie die Quittung also gut auf.","أربعة عشر يوماً، لكن بالإيصال فقط. احتفظي بالإيصال جيداً."],
  ["Mira","Mache ich. Den Schmuck dort schaue ich mir auch noch an.","سأفعل. سألقي نظرة أيضاً على المجوهرات هناك."]],
 "questions":[
  {"type":"mc","promptDe":"Was kostet die Hose im Sonderangebot?","options":["29 Euro","49 Euro","38 Euro"],"answer":"29 Euro","explanationAr":"الدليل: «29 statt 49 Euro». الفخّ 1: 49 السعر القديم. الفخّ 2: 38 هو المقاس."},
  {"type":"mc","promptDe":"Was ist für die Rückgabe wichtig?","options":["die Quittung","die Umkleidekabine","die Farbe Dunkelblau"],"answer":"die Quittung","explanationAr":"الدليل: «Vierzehn Tage, aber nur mit Quittung». الفخّ 1: غرفة القياس للتجربة. الفخّ 2: اللون رغبة ميرا."},
  {"type":"truefalse","promptDe":"Mira findet die erste Farbe altmodisch.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل: «Die Farbe ist ein bisschen altmodisch»."}],
 "dictation":["Die Umkleidekabine ist hinten links.","Heben Sie die Quittung also gut auf."]},
{"id":"d-a2-27","titleDe":"Erinnerungen an die Kindheit","titleAr":"ذكريات الطفولة",
 "waisen":["die Kindheit","damals","neulich","inzwischen","das Erlebnis","sich verändern","der Höhepunkt","die Vergangenheit","erzählen","sich gewöhnen an"],
 "lines":[
  ["Enkelin","Oma, erzähl mir von deiner Kindheit in Sousse.","جدتي، احكي لي عن طفولتك في سوسة."],
  ["Oma","Damals gab es kein Internet und nur ein Telefon im ganzen Haus. Wir haben draußen gespielt, bis es dunkel war.","آنذاك لم يكن هناك إنترنت وهاتف واحد فقط في البيت كله. كنا نلعب في الخارج حتى يحلّ الظلام."],
  ["Enkelin","Was war das schönste Erlebnis?","ما أجمل تجربة؟"],
  ["Oma","Der Höhepunkt war jeden Sommer die Reise ans Meer mit der ganzen Familie.","الذروة كانت كل صيف رحلة البحر مع العائلة كلها."],
  ["Enkelin","Und hat sich die Stadt inzwischen sehr verändert?","وهل تغيّرت المدينة كثيراً منذ ذلك الحين؟"],
  ["Oma","Sehr. Neulich war ich dort: neue Straßen, hohe Gebäude. Nur das Meer ist gleich geblieben.","كثيراً. مؤخراً كنت هناك: شوارع جديدة ومبانٍ عالية. البحر وحده بقي كما هو."],
  ["Enkelin","Vermisst du die Vergangenheit?","هل تشتاقين إلى الماضي؟"],
  ["Oma","Manchmal. Aber man gewöhnt sich an alles, auch an Handys.","أحياناً. لكن المرء يعتاد على كل شيء، حتى الهواتف."]],
 "questions":[
  {"type":"mc","promptDe":"Was war laut Oma der Höhepunkt jedes Sommers?","options":["die Reise ans Meer mit der Familie","das Spielen draußen bis zum Dunkelwerden","das einzige Telefon im Haus"],"answer":"die Reise ans Meer mit der Familie","explanationAr":"الدليل: «Der Höhepunkt war jeden Sommer die Reise ans Meer mit der ganzen Familie». الفخّ 1: اللعب في الخارج يومي لا ذروة الصيف. الفخّ 2: الهاتف تفصيل عن الماضي."},
  {"type":"mc","promptDe":"Was ist in Sousse gleich geblieben?","options":["das Meer","die Straßen","die Gebäude"],"answer":"das Meer","explanationAr":"الدليل: «Nur das Meer ist gleich geblieben». الفخّ: الشوارع والمباني «neue»/«hohe»."},
  {"type":"fill","promptDe":"Aber man gewöhnt sich ___ alles, auch an Handys.","answer":["an"],"explanationAr":"الدليل: «Aber man gewöhnt sich an alles» — sich gewöhnen an + Akkusativ."}],
 "dictation":["Damals gab es kein Internet und nur ein Telefon im ganzen Haus.","Nur das Meer ist gleich geblieben."]},
]
