# -*- coding: utf-8 -*-
"""Kollokationen Batch 7 (B1 Rest, Teil 2 — alle verbleibenden Einzelwörter): je 2 Verbindungen.
Präpositionen/Konnektoren/Reihenadverbien → AUSNAHMEN (Wortart)."""
AUSNAHMEN = {
"vo-b1v-019": "Präposition (aufgrund)", "vo-b1v-020": "Präposition (infolge)", "vo-b1v-021": "Präposition (anlässlich)",
"vo-b1v-022": "Präposition (mangels)", "vo-b1v-023": "Präposition (zwecks)", "vo-b1v-025": "Präposition (gemäß)",
"vo-b1v-026": "Präposition (entgegen)", "vo-b1v-027": "Präposition (dank)", "vo-b1v-028": "Präposition (statt)",
"vo-b1v-029": "Präposition (außerhalb)", "vo-b1v-031": "Präposition (bezüglich)", "vo-b1v-033": "Präposition (unweit)",
"vo-b1v-034": "Präposition (binnen)",
"vs-b1r-014": "Textadverb (zunächst)", "vs-b1r-015": "Textadverb (anschließend)", "vs-b1r-016": "Textadverb (abschließend)",
"vs-b1r-017": "Textadverb (einleitend)", "vs-b1r-018": "Textadverb (hierbei)", "vs-b1r-019": "Textadverb (dabei)",
"vs-b1r-022": "Reihenadverb (erstens)", "vs-b1r-023": "Reihenadverb (zweitens)", "vs-b1r-024": "Textadverb (letztlich)",
}
K = {
"vl-b1y-015": ["eine Preiserhöhung ankündigen","die Preiserhöhung gilt ab"],
"vl-b1y-016": ["die Kaufkraft sinkt","die Kaufkraft stärken"],
"vl-b1y-018": ["einen Kostenvoranschlag einholen","der Kostenvoranschlag ist kostenlos"],
"vl-b1y-020": ["die Investition rentiert sich","sich nach zwei Jahren rentieren"],
"vl-b1y-025": ["ein angemessener Preis","angemessen reagieren"],
"vl-b1y-027": ["eine nachvollziehbare Entscheidung","nachvollziehbar begründen"],
"vl-b1y-028": ["eine fragwürdige Methode","fragwürdig erscheinen"],
"vl-b1y-030": ["ein umstrittenes Thema","umstritten bleiben"],
"vl-b1y-031": ["eine eindeutige Antwort","eindeutig geregelt"],
"vl-b1y-032": ["ein voreiliger Schluss","voreilig entscheiden"],
"vl-b1y-033": ["ein vertretbarer Aufwand","vertretbar sein"],
"vl-b1y-034": ["eine bedenkliche Entwicklung","bedenklich finden"],
"vl-b1y-035": ["ein erheblicher Unterschied","erheblich steigen"],
"vl-b1y-036": ["ein geringfügiger Fehler","geringfügig beschäftigt"],
"vl-b1y-037": ["eine vorläufige Bescheinigung","vorläufig stoppen"],
"vl-b1y-038": ["die endgültige Entscheidung","endgültig absagen"],
"vl-b1y-039": ["eine zwangsläufige Folge","zwangsläufig führen zu"],
"vl-b1y-040": ["eine beabsichtigte Wirkung","nicht beabsichtigt sein"],
"vm-b1z-005": ["eine Vermutung äußern","die Vermutung bestätigt sich"],
"vm-b1z-007": ["die Ursache finden","die Ursache des Problems"],
"vm-b1z-013": ["die Bedienungsanleitung lesen","die Bedienungsanleitung verstehen"],
"vm-b1z-019": ["eine Aufgabe aufschieben","auf morgen aufschieben"],
"vm-b1z-026": ["einen Rückschlag erleben","nach dem Rückschlag weitermachen"],
"vm-b1z-900": ["die Datenauswertung dauert","eine sorgfältige Datenauswertung"],
"vm-b1z-901": ["eine repräsentative Umfrage","repräsentativ sein"],
"vn-b1w-000": ["eine Vorspeise bestellen","als Vorspeise nehmen"],
"vn-b1w-001": ["die Hauptspeise kommt kalt","eine vegetarische Hauptspeise"],
"vn-b1w-002": ["eine Nachspeise wählen","die Nachspeise geht aufs Haus"],
"vn-b1w-003": ["eine Beilage wählen","Reis als Beilage"],
"vn-b1w-004": ["die Zutatenliste lesen","auf der Zutatenliste stehen"],
"vn-b1w-005": ["eine Unverträglichkeit haben","die Unverträglichkeit angeben"],
"vn-b1w-014": ["an einer Führung teilnehmen","eine Führung durch das Museum"],
"vn-b1w-019": ["die Hauptrolle spielen","die Hauptrolle besetzen"],
"vn-b1w-021": ["eine neue Epoche","die Epoche der Romantik"],
"vo-b1v-002": ["eine Vorerkrankung haben","Vorerkrankungen angeben"],
"vo-b1v-004": ["eine Wechselwirkung zwischen Medikamenten","Wechselwirkungen prüfen"],
"vo-b1v-005": ["der Befund ist unauffällig","den Befund besprechen"],
"vo-b1v-007": ["Schonung brauchen","zur Schonung raten"],
"vo-b1v-010": ["eine gute Hausgemeinschaft","in der Hausgemeinschaft wohnen"],
"vo-b1v-011": ["den Gemeinschaftsraum nutzen","im Gemeinschaftsraum feiern"],
"vo-b1v-012": ["die Reinigungspflicht erfüllen","die Reinigungspflicht im Treppenhaus"],
"vo-b1v-015": ["den Schlüsseldienst rufen","der Schlüsseldienst kommt"],
"vo-b1v-018": ["ein Nachbarschaftsfest organisieren","zum Nachbarschaftsfest einladen"],
"vo-b1v-900": ["die Tagesdosis überschreiten","die empfohlene Tagesdosis"],
"vp-b1u-000": ["eine Stellenanzeige lesen","auf die Stellenanzeige antworten"],
"vp-b1u-001": ["dem Anforderungsprofil entsprechen","das Anforderungsprofil erfüllen"],
"vp-b1u-003": ["ein Arbeitsverhältnis beginnen","das Arbeitsverhältnis beenden"],
"vp-b1u-005": ["die Gehaltsvorstellung nennen","eine realistische Gehaltsvorstellung"],
"vp-b1u-006": ["die Einarbeitungszeit dauert","während der Einarbeitungszeit"],
"vp-b1u-008": ["die Arbeitszeiterfassung einführen","die Arbeitszeiterfassung ist Pflicht"],
"vp-b1u-009": ["den Gleitzeitrahmen nutzen","der Gleitzeitrahmen beginnt um sieben"],
"vp-b1u-010": ["eine Urlaubssperre gilt","die Urlaubssperre im Dezember"],
"vp-b1u-012": ["einen Betriebsausflug machen","der Betriebsausflug findet statt"],
"vp-b1u-013": ["die Führerscheinprüfung bestehen","zur Führerscheinprüfung anmelden"],
"vp-b1u-014": ["eine Fahrstunde nehmen","die Fahrstunde kostet"],
"vp-b1u-015": ["eine Verkehrsregel beachten","gegen eine Verkehrsregel verstoßen"],
"vp-b1u-019": ["zur Hauptuntersuchung fahren","die Hauptuntersuchung bestehen"],
"vp-b1u-022": ["eine Panne haben","bei einer Panne helfen"],
"vp-b1u-023": ["den Abschleppdienst rufen","der Abschleppdienst kommt"],
"vp-b1u-026": ["ein Medikament verschreiben","Tabletten verschreiben"],
"vp-b1u-027": ["die Nummer aufschreiben","alles aufschreiben"],
"vp-b1u-029": ["jemandem die Schuld zuschreiben","einen Erfolg zuschreiben"],
"vp-b1u-031": ["Kosten entstehen","ein Missverständnis entsteht"],
"vp-b1u-033": ["einen Fehler gestehen","die Tat gestehen"],
"vp-b1u-034": ["der Versuchung widerstehen","dem Druck widerstehen"],
"vp-b1u-900": ["zur Probearbeit eingeladen","einen Tag Probearbeit"],
"vp-b1u-901": ["ein Zwischenzeugnis verlangen","ein Zwischenzeugnis ausstellen"],
"vp-b1u-902": ["die Bewerbungsfrist endet","die Bewerbungsfrist einhalten"],
"vp-b1u-903": ["eine Parklücke finden","in die Parklücke fahren"],
"vp-b1u-904": ["einen Parkschein ziehen","den Parkschein hinter die Scheibe legen"],
"vp-b1u-905": ["eine Umweltplakette brauchen","ohne Umweltplakette fahren"],
"vq-b1t-000": ["eine Haftpflichtversicherung abschließen","die Haftpflichtversicherung zahlt"],
"vq-b1t-003": ["die Police prüfen","in der Police stehen"],
"vq-b1t-004": ["der Beitragssatz steigt","den Beitragssatz senken"],
"vq-b1t-005": ["eine Beitragsrückerstattung bekommen","Anspruch auf Beitragsrückerstattung"],
"vq-b1t-006": ["für die Altersvorsorge sparen","die private Altersvorsorge"],
"vq-b1t-007": ["ein Sparziel setzen","das Sparziel erreichen"],
"vq-b1t-009": ["per Lastschrift zahlen","eine Lastschrift zurückbuchen"],
"vq-b1t-011": ["die Kontoführungsgebühr zahlen","die Kontoführungsgebühr erhöhen"],
"vq-b1t-012": ["Freiwilligenarbeit leisten","sich für Freiwilligenarbeit melden"],
"vq-b1t-015": ["in den Vorstand wählen","der Vorstand entscheidet"],
"vq-b1t-017": ["eine Spende überweisen","um eine Spende bitten"],
"vq-b1t-019": ["Hilfsbereitschaft zeigen","große Hilfsbereitschaft"],
"vq-b1t-020": ["ein Anliegen haben","das Anliegen vortragen"],
"vq-b1t-025": ["fest überzeugt sein","überzeugt von der Idee"],
"vq-b1t-026": ["ein enttäuschendes Ergebnis","enttäuschend verlaufen"],
"vq-b1t-027": ["eine beeindruckende Leistung","beeindruckend ruhig"],
"vq-b1t-029": ["ein erholsames Wochenende","erholsam schlafen"],
"vq-b1t-030": ["ein aufregender Tag","aufregend finden"],
"vq-b1t-031": ["eine beruhigende Stimme","beruhigend sprechen"],
"vq-b1t-032": ["der entscheidende Punkt","entscheidend sein"],
"vq-b1t-033": ["ausreichend Zeit haben","ausreichend trinken"],
"vq-b1t-034": ["eine zutreffende Beschreibung","zutreffend beantworten"],
"vq-b1t-900": ["zur Jahreshauptversammlung einladen","die Jahreshauptversammlung wählt"],
"vq-b1t-950": ["die Ehrenamtspauschale nutzen","die Ehrenamtspauschale bleibt steuerfrei"],
"vr-b1s-001": ["die Online-Banking-App öffnen","sich in der Online-Banking-App anmelden"],
"vr-b1s-002": ["die Zwei-Faktor-Authentifizierung aktivieren","per Zwei-Faktor-Authentifizierung schützen"],
"vr-b1s-004": ["einen Betrugsversuch melden","einen Betrugsversuch erkennen"],
"vr-b1s-005": ["eine Phishing-Mail erkennen","auf eine Phishing-Mail hereinfallen"],
"vr-b1s-006": ["die Datenschutzerklärung lesen","die Datenschutzerklärung akzeptieren"],
"vr-b1s-007": ["die Einwilligung geben","die Einwilligung widerrufen"],
"vr-b1s-011": ["eine Videosprechstunde buchen","per Videosprechstunde beraten"],
"vr-b1s-013": ["einen Testbericht lesen","der Testbericht empfiehlt"],
"vr-b1s-015": ["die Lieferzeit beträgt","eine lange Lieferzeit"],
"vr-b1s-017": ["eine Retoure anmelden","die Retoure ist kostenlos"],
"vr-b1s-018": ["das Etikett lesen","ein Etikett aufkleben"],
"vr-b1s-020": ["ein beschädigtes Paket","beschädigt ankommen"],
"vr-b1s-021": ["ein Ersatzteil bestellen","das Ersatzteil einbauen"],
"vr-b1s-025": ["die Durchführung planen","für die Durchführung verantwortlich"],
"vr-b1s-026": ["eine Verbesserung vorschlagen","eine deutliche Verbesserung"],
"vr-b1s-027": ["eine Erhöhung der Miete","die Erhöhung ankündigen"],
"vr-b1s-028": ["eine Senkung der Steuern","die Senkung beschließen"],
"vr-b1s-029": ["eine Verzögerung entschuldigen","ohne Verzögerung liefern"],
"vr-b1s-030": ["eine Erweiterung planen","die Erweiterung des Angebots"],
"vr-b1s-031": ["eine Kürzung der Leistungen","die Kürzung zurücknehmen"],
"vr-b1s-032": ["die Umstellung auf Ökostrom","die Umstellung dauert"],
"vr-b1s-033": ["eine Abstimmung durchführen","die Abstimmung gewinnen"],
"vr-b1s-034": ["die Fortsetzung folgt","eine Fortsetzung drehen"],
"vs-b1r-000": ["die Prüfungsanmeldung abgeben","die Prüfungsanmeldung läuft bis"],
"vs-b1r-001": ["jeder Prüfungsteil zählt","den Prüfungsteil bestehen"],
"vs-b1r-003": ["die Aufgabenstellung lesen","die Aufgabenstellung verstehen"],
"vs-b1r-004": ["mit der Musterlösung vergleichen","eine Musterlösung anbieten"],
"vs-b1r-005": ["die Bewertungskriterien kennen","nach festen Bewertungskriterien"],
"vs-b1r-008": ["ein Zertifikat erhalten","das Zertifikat vorlegen"],
"vs-b1r-009": ["unter Prüfungsstress leiden","den Prüfungsstress abbauen"],
"vs-b1r-010": ["eine Lernstrategie entwickeln","die passende Lernstrategie"],
"vs-b1r-012": ["eine ehrliche Selbsteinschätzung","die Selbsteinschätzung abgeben"],
"vt-b1q-000": ["Maßnahmen zur Klimaanpassung","in Klimaanpassung investieren"],
"vt-b1q-003": ["Starkregen erwarten","bei Starkregen überschwemmt"],
"vt-b1q-004": ["unter Trockenheit leiden","die Trockenheit hält an"],
"vt-b1q-005": ["der Wasserstand steigt","den Wasserstand messen"],
"vt-b1q-006": ["die Artenvielfalt schützen","der Verlust der Artenvielfalt"],
"vt-b1q-008": ["den Lebensraum zerstören","der Lebensraum der Tiere"],
"vt-b1q-009": ["die Aufforstung fördern","mit der Aufforstung beginnen"],
"vt-b1q-010": ["dem Umweltschutzverband beitreten","der Umweltschutzverband klagt"],
"vt-b1q-013": ["Muskelkater haben","Muskelkater nach dem Training"],
"vt-b1q-014": ["eine Dehnübung machen","mit einer Dehnübung beginnen"],
"vt-b1q-015": ["Krankheiten vorbeugen","Verletzungen vorbeugen"],
"vt-b1q-016": ["Zeit zur Regeneration","die Regeneration fördern"],
"vt-b1q-017": ["den Schlafrhythmus stören","einen festen Schlafrhythmus"],
"vt-b1q-019": ["eine Entspannungstechnik lernen","eine Entspannungstechnik anwenden"],
"vt-b1q-021": ["ein Stigma tragen","das Stigma abbauen"],
"vt-b1q-022": ["eine Selbsthilfegruppe besuchen","eine Selbsthilfegruppe gründen"],
"vt-b1q-023": ["umweltfreundlich reisen","ein umweltfreundliches Produkt"],
"vt-b1q-024": ["kostenbewusst einkaufen","kostenbewusst planen"],
"vt-b1q-025": ["ein zeitaufwendiges Projekt","zeitaufwendig sein"],
"vt-b1q-026": ["eine pflegeleichte Pflanze","pflegeleichte Kleidung"],
"vt-b1q-027": ["eine benutzerfreundliche App","benutzerfreundlich gestalten"],
"vt-b1q-028": ["eine kinderfreundliche Stadt","ein kinderfreundliches Restaurant"],
"vt-b1q-029": ["verkehrsgünstig liegen","eine verkehrsgünstige Lage"],
"vt-b1q-030": ["einkommensschwache Familien","einkommensschwache Haushalte unterstützen"],
"vt-b1q-031": ["arbeitsintensive Pflege","arbeitsintensiv sein"],
"vt-b1q-032": ["ein krisenfester Beruf","krisenfest bleiben"],
"vt-b1q-033": ["lernbereit sein","lernbereite Mitarbeiter"],
"vt-b1q-034": ["teamfähig sein","als teamfähig gelten"],
"vt-b1q-900": ["eine lange Dürreperiode","die Dürreperiode überstehen"],
"vt-b1q-901": ["in Hochwasserschutz investieren","Maßnahmen zum Hochwasserschutz"],
"vt-b1q-902": ["eine Achtsamkeitsübung machen","mit einer Achtsamkeitsübung beginnen"],
"vt-b1q-903": ["stressresistent sein","stressresistent bleiben"],
"vu-b1p-000": ["die Berichterstattung verfolgen","eine ausgewogene Berichterstattung"],
"vu-b1p-001": ["einseitig berichten","eine einseitige Darstellung"],
"vu-b1p-002": ["ausgewogen berichten","ein ausgewogenes Urteil"],
"vu-b1p-005": ["eine Leserzuschrift schreiben","Leserzuschriften veröffentlichen"],
"vu-b1p-007": ["die Gegenposition vertreten","eine Gegenposition einnehmen"],
"vu-b1p-011": ["eine Verallgemeinerung vermeiden","zur Verallgemeinerung neigen"],
"vu-b1p-012": ["ein Einzelfall bleiben","vom Einzelfall auf alle schließen"],
"vu-b1p-013": ["eine Reiserücktrittsversicherung abschließen","die Reiserücktrittsversicherung zahlt"],
"vu-b1p-020": ["eine Auslandskrankenversicherung brauchen","die Auslandskrankenversicherung übernimmt"],
"vu-b1p-021": ["einen Notfallkontakt angeben","den Notfallkontakt anrufen"],
"vu-b1p-030": ["eine Entscheidung hinauszögern","den Termin hinauszögern"],
"vu-b1p-900": ["eine Richtigstellung veröffentlichen","eine Richtigstellung verlangen"],
"vu-b1p-901": ["einen Reiseabbruch melden","Kosten bei Reiseabbruch"],
"vv-verwal-001": ["der Sachbearbeiter prüft","beim Sachbearbeiter nachfragen"],
"vv-verwal-002": ["Akteneinsicht beantragen","Akteneinsicht gewähren"],
"vv-verwal-005": ["einen Rechtsanspruch haben","der Rechtsanspruch auf einen Kitaplatz"],
"vv-verwal-008": ["die Rechtsmittelbelehrung lesen","ohne Rechtsmittelbelehrung ungültig"],
"vv-verwal-009": ["der Gemeinderat beschließt","in den Gemeinderat gewählt"],
"vv-verwal-010": ["die Bürgersprechstunde besuchen","in der Bürgersprechstunde fragen"],
"vv-verwal-011": ["eine Beschlussvorlage einbringen","über die Beschlussvorlage abstimmen"],
"vv-verwal-015": ["eine Auflage erfüllen","mit Auflagen genehmigen"],
"vv-verwal-017": ["eine Einsprache erheben","die Einsprache prüfen"],
"vv-handwe-000": ["einen Handwerksbetrieb führen","im Handwerksbetrieb arbeiten"],
"vv-handwe-001": ["einen Lehrling ausbilden","als Lehrling anfangen"],
"vv-handwe-002": ["die Meisterprüfung ablegen","die Meisterprüfung bestehen"],
"vv-handwe-003": ["das Werkzeug mitbringen","Werkzeug teilen"],
"vv-handwe-004": ["die Bohrmaschine ausleihen","mit der Bohrmaschine arbeiten"],
"vv-handwe-005": ["auf die Leiter steigen","die Leiter halten"],
"vv-handwe-012": ["die Materialkosten berechnen","Materialkosten sparen"],
"vv-handwe-013": ["die Abnahme durchführen","bei der Abnahme prüfen"],
"vv-handwe-014": ["die Gewährleistungsfrist beträgt","innerhalb der Gewährleistungsfrist"],
"vv-handwe-016": ["eine Schutzbrille tragen","die Schutzbrille aufsetzen"],
"vv-handwe-017": ["Staub wischen","viel Staub machen"],
"vv-handwe-018": ["die Entsorgung übernehmen","die Entsorgung kostet"],
"vv-handwe-019": ["termingerecht liefern","termingerecht fertig werden"],
"vv-gefueh-000": ["Zuversicht ausstrahlen","voller Zuversicht"],
"vv-gefueh-001": ["Erleichterung spüren","mit Erleichterung reagieren"],
"vv-gefueh-002": ["Verunsicherung auslösen","große Verunsicherung"],
"vv-gefueh-003": ["Überforderung spüren","vor Überforderung schützen"],
"vv-gefueh-007": ["vor Ungeduld zittern","Ungeduld zeigen"],
"vv-gefueh-008": ["die Rücksichtslosigkeit der Fahrer","Rücksichtslosigkeit kritisieren"],
"vv-gefueh-009": ["einen Groll hegen","der Groll bleibt"],
"vv-gefueh-010": ["Genugtuung empfinden","mit Genugtuung feststellen"],
"vv-gefueh-011": ["einen Zusammenhang vermuten","stark vermuten"],
"vv-gefueh-012": ["die Zahlen bezweifeln","die Aussage bezweifeln"],
"vv-gefueh-016": ["einen Fehler zugeben","offen zugeben"],
"vv-gefueh-017": ["den Vorwurf bestreiten","energisch bestreiten"],
"vv-gefueh-018": ["einen Verdacht nahelegen","eine Lösung nahelegen"],
"vv-gefueh-019": ["die Frage offenlassen","das Ergebnis offenlassen"],
"vw-b1n-004": ["eine Teilqualifikation erwerben","die Teilqualifikation anerkennen"],
"vw-b1n-005": ["einen Bildungsgutschein bekommen","den Bildungsgutschein einlösen"],
"vw-b1n-006": ["einen Praktikumsplatz suchen","einen Praktikumsplatz anbieten"],
"vw-b1n-007": ["die Bewerbungsmappe abgeben","eine vollständige Bewerbungsmappe"],
"vw-b1n-008": ["mit dem Berufsberater sprechen","der Berufsberater empfiehlt"],
"vw-b1n-009": ["sich bei der Arbeitsagentur melden","die Arbeitsagentur zahlt"],
"vw-b1n-011": ["eine Eingliederungsvereinbarung unterschreiben","die Eingliederungsvereinbarung einhalten"],
"vw-b1n-012": ["der Meldepflicht nachkommen","die Meldepflicht gilt"],
"vw-b1n-015": ["eine Nebentätigkeit anmelden","die Nebentätigkeit genehmigen"],
"vw-b1n-017": ["die Lohnsteuerklasse wechseln","in Lohnsteuerklasse eins"],
"vw-b1n-018": ["die Lohnabrechnung prüfen","die Lohnabrechnung erhalten"],
"vw-b1n-019": ["der Nettolohn bleibt","den Nettolohn berechnen"],
"vw-b1n-020": ["Sozialabgaben zahlen","die Sozialabgaben abziehen"],
"vw-b1n-021": ["in die Rentenversicherung einzahlen","die Rentenversicherung informiert"],
"vw-b1n-022": ["die Pflegeversicherung zahlt","Beiträge zur Pflegeversicherung"],
"vw-b1n-024": ["Elterngeld erhalten","das Elterngeld berechnen"],
"vw-b1n-025": ["einen Betreuungsplatz finden","auf einen Betreuungsplatz warten"],
"vw-b1n-027": ["der Schulweg ist sicher","den Schulweg üben"],
"vw-b1n-028": ["das Ganztagsangebot nutzen","ein Ganztagsangebot einrichten"],
"vw-b1n-029": ["auf Klassenfahrt fahren","die Klassenfahrt bezahlen"],
"vw-b1n-030": ["Förderunterricht bekommen","Förderunterricht in Deutsch"],
"vw-b1n-032": ["eine Mitschrift machen","die Mitschrift teilen"],
"vw-b1n-033": ["einen Wohnberechtigungsschein beantragen","der Wohnberechtigungsschein gilt"],
"vw-b1n-035": ["die Rundfunkgebühr zahlen","von der Rundfunkgebühr befreit"],
"vw-b1n-036": ["die Verbraucherzentrale berät","zur Verbraucherzentrale gehen"],
"vw-b1n-038": ["eine Kündigungsbestätigung erhalten","auf die Kündigungsbestätigung warten"],
"vw-b1n-040": ["in Zahlungsverzug geraten","der Zahlungsverzug kostet"],
"vw-b1n-041": ["die Schuldnerberatung aufsuchen","die Schuldnerberatung hilft kostenlos"],
"vw-b1n-043": ["die Fixkosten senken","hohe Fixkosten"],
"vw-b1n-047": ["die Preisbindung gilt","eine Preisbindung vereinbaren"],
"vw-b1n-048": ["einen Tarifwechsel beantragen","der Tarifwechsel spart Geld"],
"vw-b1n-049": ["eine Abschlagszahlung leisten","die Abschlagszahlung erhöhen"],
"vw-b1n-901": ["einen Aufhebungsvertrag unterschreiben","der Aufhebungsvertrag beendet das Arbeitsverhältnis"],
"vw-b1n-902": ["eine Sperrzeit bekommen","die Sperrzeit dauert zwölf Wochen"],
"vw-b1n-904": ["die Erstausstattung beantragen","Geld für die Erstausstattung"],
"vw-b1n-905": ["einen Mehrbedarf anerkennen","den Mehrbedarf beantragen"],
"vw-b1n-906": ["die Widerspruchsfrist einhalten","die Widerspruchsfrist beträgt einen Monat"],
"vw-b1n-907": ["die Auszahlung erfolgt","auf die Auszahlung warten"],
"vw-b1n-908": ["eine Nachzahlung leisten","die Nachzahlung fordern"],
"vw-b1n-909": ["den Bewilligungsbescheid erhalten","der Bewilligungsbescheid kommt per Post"],
}
