# -*- coding: utf-8 -*-
"""Kollokationen Batch 10 (A1 Kernverben/-nomen): je 2 sehr einfache Verbindungen — nur A1-Wortschatz.
Pädagogischer Rahmen: A1 bekommt nur Alltagsverben + hochfrequente Nomen; Funktionswörter/Zahlen/Farben nicht."""
K = {
"v006": ["Wie heißen Sie?","Ich heiße Sara."],
"v007": ["aus Tunesien kommen","nach Hause kommen"],
"v008": ["in Berlin wohnen","bei den Eltern wohnen"],
"v009": ["Deutsch sprechen","langsam sprechen"],
"v010": ["alles verstehen","das Wort nicht verstehen"],
"v011": ["Deutsch lernen","jeden Abend lernen"],
"v012": ["viel arbeiten","als Ingenieur arbeiten"],
"v014": ["zur Arbeit fahren","die Arbeit beginnt um acht"],
"v015": ["eine Sprache lernen","die deutsche Sprache"],
"v017": ["auf dem Land wohnen","in ein anderes Land fahren"],
"v149": ["mit Karte bezahlen","bar bezahlen"],
"v036": ["um sieben Uhr aufstehen","früh aufstehen"],
"v037": ["lange schlafen","acht Stunden schlafen"],
"v038": ["zu Mittag essen","Brot essen"],
"v039": ["Kaffee trinken","ein Glas Wasser trinken"],
"v045": ["Frühstück machen","das Frühstück ist fertig"],
"v046": ["das Mittagessen kochen","zum Mittagessen gehen"],
"v047": ["einen Kaffee bestellen","der Kaffee kostet zwei Euro"],
"v151": ["das Abendessen essen","zum Abendessen kommen"],
"v152": ["mit dem Hund gehen","der Hund heißt Max"],
"v153": ["die Katze schläft","eine Katze haben"],
"v154": ["das Kind spielt","ein Kind haben"],
"v156": ["am Wochenende frei haben","schönes Wochenende"],
"v1402": ["in den Kühlschrank legen","der Kühlschrank ist leer"],
"v1415": ["einen Kuchen backen","ein Stück Kuchen"],
"v1416": ["Zucker in den Tee","ohne Zucker trinken"],
"v1418": ["Milch trinken","Kaffee mit Milch"],
"v1419": ["am Tisch sitzen","den Tisch decken"],
"v1422": ["Wasser trinken","ein Glas Wasser"],
"vw-a1ess-000": ["Brot kaufen","frisches Brot"],
"vw-a1ess-013": ["ein Ei kochen","sechs Eier kaufen"],
"vw-a1ess-014": ["Brot mit Käse","Käse kaufen"],
"vw-a1ess-016": ["einen Apfel essen","ein roter Apfel"],
"vw-a1ess-023": ["Gemüse kaufen","Gemüse kochen"],
"vw-a1ess-024": ["Obst essen","frisches Obst"],
"vw-a1ess-025": ["einen Salat machen","Salat mit Tomaten"],
"vw-a1ess-026": ["eine Suppe kochen","warme Suppe"],
"vw-a1ess-032": ["Hunger haben","großen Hunger haben"],
"vw-a1ess-033": ["Durst haben","großen Durst haben"],
"vw-a1ess-036": ["Reis kochen","gern kochen"],
"vw-a1ess-037": ["Brot backen","Pizza backen"],
"vw-a1ess-038": ["süß schmecken","es schmeckt lecker"],
"vw-a1ess-039": ["eine Pizza bestellen","im Restaurant bestellen"],
"vw-a1ess-042": ["ins Restaurant gehen","im Restaurant essen"],
"vw-a1ess-043": ["die Speisekarte lesen","die Speisekarte bitte"],
"vw-a1ess-044": ["der Kellner kommt","den Kellner rufen"],
"vw-a1ess-046": ["ein Glas Saft","das Glas ist leer"],
"vw-a1ess-047": ["eine Tasse Kaffee","eine Tasse Tee"],
"vw-a1ess-051": ["eine Flasche Wasser","die Flasche öffnen"],
"vw-a1ess-052": ["im Supermarkt arbeiten","zum Supermarkt gehen"],
"vw-a1ess-053": ["in der Bäckerei kaufen","zur Bäckerei gehen"],
"vw-a1ess-059": ["ein Kilo Tomaten","zwei Kilo Kartoffeln"],
"vw-a1koe-008": ["die Hand geben","die Hand heben"],
"vw-a1koe-021": ["ein Hemd tragen","ein weißes Hemd"],
"vw-a1koe-025": ["eine Jacke anziehen","eine warme Jacke"],
"vw-a1koe-027": ["Schuhe kaufen","neue Schuhe"],
"vw-a1koe-031": ["eine schwere Tasche","die Tasche öffnen"],
"vw-a1koe-032": ["eine Brille tragen","einen Mantel tragen"],
"vw-a1koe-033": ["die Jacke anziehen","den Pullover anziehen"],
"vw-a1koe-035": ["die Hose passt","der Termin passt gut"],
"vw-a1koe-036": ["zwei Euro kosten","Was kostet das?"],
"vw-a1koe-039": ["Größe M haben","die richtige Größe"],
"vw-a1koe-040": ["Welche Farbe?","eine schöne Farbe"],
"vw-a1koe-049": ["das Auto waschen","die Haare waschen"],
"vw-a1sta-003": ["einen Platz suchen","der Platz ist frei"],
"vw-a1sta-009": ["zur Post gehen","die Post ist gegenüber"],
"vw-a1sta-010": ["zur Bank gehen","Geld von der Bank"],
"vw-a1sta-014": ["mit dem Bus fahren","der Bus kommt"],
"vw-a1sta-015": ["mit dem Zug fahren","der Zug kommt um zehn"],
"vw-a1sta-016": ["mit dem Auto fahren","ein Auto haben"],
"vw-a1sta-017": ["mit dem Fahrrad fahren","ein Fahrrad kaufen"],
"vw-a1sta-018": ["ein Taxi nehmen","mit dem Taxi fahren"],
"vw-a1sta-019": ["nach Hamburg fahren","langsam fahren"],
"vw-a1sta-020": ["zu Fuß laufen","schnell laufen"],
"vw-a1sta-021": ["nach Tunis fliegen","der Vogel fliegt"],
"vw-a1sta-022": ["um zehn Uhr ankommen","in Berlin ankommen"],
"vw-a1sta-023": ["um acht Uhr abfahren","pünktlich abfahren"],
"vw-a1sta-034": ["den Weg zeigen","nach dem Weg fragen"],
"vw-a1sta-035": ["den Kellner fragen","noch einmal fragen"],
"vw-a1sta-036": ["das Zimmer zeigen","den Pass zeigen"],
"vw-a1sta-037": ["eine Wohnung suchen","den Schlüssel suchen"],
"vw-a1sta-038": ["den Weg finden","eine Wohnung finden"],
"vw-a1sta-040": ["auf den Markt gehen","auf dem Markt kaufen"],
"vw-a1sta-041": ["Obst kaufen","im Supermarkt kaufen"],
"vw-a1sta-042": ["das Auto verkaufen","Obst verkaufen"],
"vw-a1sta-043": ["Geld haben","Geld wechseln"],
"vw-a1sta-045": ["an der Kasse bezahlen","an die Kasse gehen"],
"vw-a1sta-046": ["ins Kino gehen","im Kino sein"],
"vw-a1sta-047": ["ein Café am Bahnhof","das Café ist warm"],
"vw-a1sta-048": ["in den Park gehen","im Park spielen"],
"vw-a1sta-052": ["im Zentrum wohnen","ins Zentrum fahren"],
"vx-zeit--000": ["Zeit haben","keine Zeit haben"],
"vx-zeit--001": ["eine Stunde warten","zwei Stunden lernen"],
"vx-zeit--002": ["fünf Minuten zu Fuß","zehn Minuten warten"],
"vx-zeit--003": ["jeden Tag","einen schönen Tag"],
"vx-zeit--004": ["nächste Woche","zweimal pro Woche"],
"vx-zeit--007": ["jeden Morgen","am Morgen Kaffee trinken"],
"vx-zeit--011": ["jeden Abend","am Abend kochen"],
"vx-zeit--032": ["Wie viel Uhr ist es?","um acht Uhr"],
"vx-haus--004": ["die Tür öffnen","die Tür ist eng"],
"vx-haus--005": ["das Fenster öffnen","am Fenster sitzen"],
"vx-haus--006": ["ins Bett gehen","das Bett steht an der Wand"],
"vx-haus--014": ["den Schlüssel geben","der Schlüssel liegt an der Rezeption"],
"vx-haus--021": ["Hausaufgaben machen","die Hausaufgabe vergessen"],
"vx-haus--024": ["ein neues Wort","das Wort verstehen"],
"vx-haus--025": ["einen Satz schreiben","der Satz ist lang"],
"vx-haus--026": ["einen Text lesen","den Text verstehen"],
"vx-haus--028": ["langsam lesen","ein Buch im Park lesen"],
"vx-haus--029": ["eine E-Mail schreiben","einen Brief schreiben"],
"vx-haus--030": ["Radio hören","Musik im Bus hören"],
"vx-haus--031": ["das Hotel sehen","einen Film im Kino sehen"],
"vx-haus--032": ["nach Hause gehen","zu Fuß gehen"],
"vx-haus--033": ["Sport machen","Fehler machen"],
"vx-haus--034": ["dem Kind Milch geben","Geld geben"],
"vx-haus--035": ["den Bus nehmen","einen Kaffee nehmen"],
"vx-haus--036": ["Danke sagen","die Wahrheit sagen"],
"vx-haus--037": ["Blumen bringen","zum Bahnhof bringen"],
"vx-haus--038": ["der Mutter helfen","gern helfen"],
"vx-haus--039": ["Hilfe brauchen","Zeit brauchen"],
"vx-haus--040": ["die Antwort wissen","den Weg wissen"],
"vx-haus--041": ["die Stadt kennen","einen Freund kennen"],
"vx-haus--043": ["zu Hause bleiben","im Bett bleiben"],
"vx-haus--044": ["den Laptop öffnen","um acht Uhr öffnen"],
"vx-haus--045": ["die Tür schließen","das Fenster schließen"],
"vx-haus--046": ["mit der Arbeit anfangen","um acht Uhr anfangen"],
"vx-haus--047": ["mit dem Rauchen aufhören","um fünf Uhr aufhören"],
"vx-haus--048": ["den Termin vergessen","die Eier vergessen"],
"vx-haus--050": ["auf den Bus warten","fünf Minuten warten"],
"vx-haus--051": ["Fußball spielen","mit den Kindern spielen"],
"vx-haus--062": ["mein Sohn ist fünf","einen Sohn haben"],
"vx-haus--063": ["meine Tochter geht zur Schule","eine Tochter haben"],
"vx-haus--066": ["die Großmutter besuchen","meine Großmutter kocht"],
"vx-haus--068": ["mein Onkel wohnt in Berlin","den Onkel abholen"],
"vx-haus--069": ["die Tante besuchen","meine Tante kommt"],
"vy-natur-005": ["ans Meer fahren","im Meer schwimmen"],
"vy-natur-006": ["am Strand liegen","an den Strand gehen"],
"vy-natur-013": ["frische Luft","an die frische Luft gehen"],
"vy-natur-022": ["viel Sport treiben","Sport ist gesund"],
"vy-natur-023": ["Fußball im Fernsehen sehen","Fußball ist mein Hobby"],
"vy-natur-024": ["im See schwimmen","schwimmen gehen"],
"vy-natur-025": ["tanzen gehen","gern tanzen"],
"vy-natur-026": ["ein Lied singen","im Chor singen"],
"vy-natur-029": ["ein Hobby haben","mein Hobby ist Fußball"],
"vy-natur-032": ["ein Foto machen","ein Foto von der Familie"],
"vy-natur-033": ["nach Tunesien reisen","viel reisen"],
"vy-natur-034": ["Freunde besuchen","die Großeltern besuchen"],
"vy-natur-035": ["Freunde treffen","sich am Samstag treffen"],
"vy-natur-037": ["viel Freizeit haben","in der Freizeit lesen"],
"vy-natur-044": ["über den Witz lachen","viel lachen"],
"vy-natur-047": ["Kaffee mögen","Kinder mögen Schokolade"],
"vy-natur-053": ["morgens duschen","zehn Minuten duschen"],
"vy-natur-055": ["Wäsche waschen","die Wäsche aufhängen"],
"vy-natur-060": ["Brot schneiden","das Gemüse schneiden"],
"vz-welt-b-013": ["im Wörterbuch suchen","ein Wörterbuch kaufen"],
"vz-welt-b-014": ["ins Deutsche übersetzen","einen Satz übersetzen"],
"vz-welt-b-015": ["den Namen buchstabieren","bitte buchstabieren"],
"vz-welt-b-027": ["im Büro arbeiten","ins Büro gehen"],
"vz-welt-b-043": ["die Kinder holen","Brot holen"],
"vz-welt-b-079": ["um Hilfe bitten","Hilfe bekommen"],
"va-modort-053": ["eine E-Mail bekommen","eine E-Mail an die Schwester"],
"va-modort-069": ["einen Brief bekommen","einen Brief zur Post bringen"],
"va-modort-070": ["ein Paket bekommen","ein Paket abholen"],
"va-modort-073": ["das Paket abholen","die Kinder abholen"],
"va-modort-084": ["ein Buch leihen","Geld leihen"],
"va-modort-088": ["Kuchen mitbringen","einen Freund mitbringen"],
"va-modort-091": ["das Licht anmachen","das Licht ausmachen"],
"va-modort-094": ["ein Problem haben","kein Problem"],
"vb-abschl-006": ["auf die Frage antworten","schnell antworten"],
"vb-abschl-014": ["eine gute Idee","eine Idee haben"],
"vb-abschl-033": ["den Regenschirm mitnehmen","einen Regenschirm brauchen"],
}
