# -*- coding: utf-8 -*-
"""Kollokationen Batch 1 (B2): je Karte 3 feste Wortverbindungen, die das Kartenwort enthalten."""
K = {
"v121": ["einen Kommentar schreiben","einen Kommentar veröffentlichen","ein kritischer Kommentar"],
"v122": ["eine reißerische Schlagzeile","Schlagzeilen machen","die Schlagzeile des Tages"],
"v123": ["eine zuverlässige Quelle","die Quelle angeben","aus sicherer Quelle"],
"v125": ["gründlich recherchieren","zu einem Thema recherchieren","im Archiv recherchieren"],
"v126": ["eine Umfrage durchführen","laut einer aktuellen Umfrage","an einer Umfrage teilnehmen"],
"v128": ["Fortschritte machen","der technische Fortschritt","ein deutlicher Fortschritt"],
"v129": ["Forschung betreiben","die aktuelle Forschung","Forschung und Entwicklung"],
"v130": ["Auswirkungen haben auf","negative Auswirkungen","die Auswirkungen abschätzen"],
"v132": ["hohe Anforderungen stellen","den Anforderungen entsprechen","die Anforderungen erfüllen"],
"v133": ["eine Herausforderung annehmen","vor einer Herausforderung stehen","eine große Herausforderung"],
"v134": ["in engem Zusammenhang stehen","der Zusammenhang zwischen","aus dem Zusammenhang reißen"],
"v135": ["eine Leistung bewerten","positiv bewerten","kritisch bewerten"],
"v136": ["einen Maßstab anlegen","nach strengen Maßstäben","Maßstäbe setzen"],
"v138": ["die Fähigkeit besitzen","seine Fähigkeiten einsetzen","die Fähigkeit entwickeln"],
"v140": ["die Voraussetzung erfüllen","unter der Voraussetzung, dass","eine wichtige Voraussetzung"],
"v141": ["eine Schlussfolgerung ziehen","zu der Schlussfolgerung kommen","eine voreilige Schlussfolgerung"],
"v177": ["Prävention betreiben","in die Prävention investieren","Maßnahmen zur Prävention"],
"v180": ["die Urteilskraft schulen","über Urteilskraft verfügen","politische Urteilskraft"],
"v185": ["eine Partnerschaft eingehen","in einer festen Partnerschaft leben","die Partnerschaft beenden"],
"v186": ["ein gutes Verhältnis haben","das Verhältnis verbessern","im Verhältnis zu"],
"v189": ["sich mit jemandem versöhnen","sich nach dem Streit versöhnen","sich wieder versöhnen"],
"v194": ["die Trennung verarbeiten","eine Trennung verkraften","eine schmerzhafte Trennung"],
"v195": ["die Scheidung einreichen","die Scheidung beantragen","eine Scheidung durchmachen"],
"v200": ["ein Missverständnis aufklären","zu Missverständnissen führen","ein Missverständnis vermeiden"],
"v202": ["die Nähe suchen","körperliche Nähe","in der Nähe sein"],
"v205": ["Zuneigung zeigen","Zuneigung empfinden","große Zuneigung"],
"v209": ["den Partner betrügen","Kunden betrügen","beim Spiel betrügen"],
"v210": ["Verrat begehen","als Verrat empfinden","Verrat an Freunden"],
"v212": ["jemanden bitter enttäuschen","die Erwartungen enttäuschen","jemanden nicht enttäuschen wollen"],
"v213": ["eine große Enttäuschung","die Enttäuschung verbergen","eine Enttäuschung erleben"],
"v215": ["vor Neid platzen","Neid erregen","blass vor Neid"],
"v217": ["ein Vorbild sein","sich ein Vorbild nehmen","als Vorbild dienen"],
"v220": ["dem Druck nachgeben","nicht nachgeben wollen","am Ende nachgeben"],
"v221": ["sich auf einen Kompromiss einigen","sich auf einen Termin einigen","sich schnell einigen"],
"v236": ["eine Erkältung bekommen","sich eine Erkältung einfangen","eine Erkältung auskurieren"],
"v237": ["ein typisches Symptom","Symptome zeigen","die Symptome lindern"],
"v238": ["eine Diagnose stellen","die Diagnose bestätigen","eine falsche Diagnose"],
"v241": ["am Knie operieren","sofort operieren","erfolgreich operieren"],
"v244": ["eine schnelle Genesung","gute Genesung wünschen","auf dem Weg der Genesung"],
"v245": ["eine Krankschreibung vorlegen","die Krankschreibung verlängern","die Krankschreibung einreichen"],
"v249": ["ein ärztliches Attest","ein Attest vorlegen","ein Attest ausstellen"],
"v250": ["in die Reha gehen","eine Reha beantragen","die Reha abschließen"],
"v253": ["völlige Erschöpfung","vor Erschöpfung einschlafen","Anzeichen von Erschöpfung"],
"v254": ["eine Sucht entwickeln","die Sucht bekämpfen","in eine Sucht geraten"],
"v256": ["Mobbing am Arbeitsplatz","Opfer von Mobbing werden","gegen Mobbing vorgehen"],
"v258": ["der direkte Vorgesetzte","mit dem Vorgesetzten sprechen","den Vorgesetzten informieren"],
"v259": ["ein gutes Arbeitsklima","das Arbeitsklima verbessern","ein angespanntes Arbeitsklima"],
"v263": ["zur Vorsorge gehen","Vorsorge treffen","die Vorsorge übernehmen"],
"v264": ["unter Schlafstörungen leiden","Schlafstörungen behandeln","chronische Schlafstörungen"],
"v269": ["das soziale Umfeld","im familiären Umfeld","ein stabiles Umfeld"],
"v270": ["den Zusammenhalt stärken","gesellschaftlicher Zusammenhalt","der Zusammenhalt im Team"],
"v271": ["Solidarität zeigen","Solidarität üben","Solidarität mit den Betroffenen"],
"v272": ["soziale Ungleichheit","die Ungleichheit verringern","wachsende Ungleichheit"],
"v277": ["die Zuwanderung steuern","Zuwanderung von Fachkräften","die Zuwanderung begrenzen"],
"v278": ["sich in die Gesellschaft integrieren","sich schnell integrieren","sich am Arbeitsplatz integrieren"],
"v280": ["soziale Ausgrenzung","Ausgrenzung erfahren","gegen Ausgrenzung kämpfen"],
"v281": ["jemanden wegen seiner Herkunft diskriminieren","systematisch diskriminieren","niemanden diskriminieren"],
"v282": ["Diskriminierung erfahren","sich gegen Diskriminierung wehren","Diskriminierung am Arbeitsplatz"],
"v289": ["ehrenamtliches Engagement","Engagement zeigen","großes Engagement"],
"v290": ["an einer Demonstration teilnehmen","eine Demonstration anmelden","eine friedliche Demonstration"],
"v293": ["eine Petition unterschreiben","eine Petition starten","eine Petition einreichen"],
"v294": ["den Vertrag unterschreiben","mit vollem Namen unterschreiben","unten rechts unterschreiben"],
"v302": ["die Grundrechte achten","Grundrechte einschränken","die Grundrechte garantieren"],
"v305": ["den Konsum einschränken","nachhaltiger Konsum","der private Konsum"],
"v308": ["ein schlechtes Gewissen haben","das Gewissen beruhigen","gegen sein Gewissen handeln"],
"v310": ["eine Debatte führen","eine hitzige Debatte","eine Debatte auslösen"],
"v315": ["eine Krise bewältigen","den Alltag bewältigen","Probleme bewältigen"],
"v318": ["kulturelle Vielfalt","die Vielfalt fördern","eine große Vielfalt an"],
"v322": ["eine Wohnung vermieten","möbliert vermieten","an Studenten vermieten"],
"v323": ["den Vermieter informieren","mit dem Vermieter sprechen","der Vermieter kündigt"],
"v324": ["als Mieter Rechte haben","der Mieter zahlt","dem Mieter kündigen"],
"v325": ["eine Kaution hinterlegen","die Kaution zurückbekommen","zwei Monatsmieten Kaution"],
"v326": ["den Mietvertrag unterschreiben","einen befristeten Mietvertrag","der Mietvertrag läuft aus"],
"v329": ["einen Umzug planen","beim Umzug helfen","der Umzug in eine andere Stadt"],
"v338": ["ein Grundstück kaufen","ein Grundstück bebauen","das Grundstück liegt am Waldrand"],
"v340": ["eine Hypothek aufnehmen","die Hypothek abbezahlen","eine Hypothek auf das Haus"],
"v341": ["ein Projekt finanzieren","das Studium finanzieren","über Kredit finanzieren"],
"v343": ["die Wohnung renovieren","das Bad renovieren","komplett renovieren"],
"v345": ["einen Makler beauftragen","über einen Makler suchen","der Makler verlangt Provision"],
"v346": ["einen Besichtigungstermin vereinbaren","zur Besichtigung kommen","eine Besichtigung der Wohnung"],
"v348": ["Provision zahlen","eine Provision verlangen","zwei Monatsmieten Provision"],
"v351": ["den Vertrag kündigen","fristgerecht kündigen","schriftlich kündigen"],
"v352": ["eine Kündigung erhalten","die Kündigung einreichen","eine fristlose Kündigung"],
"v353": ["Anspruch haben auf","einen Anspruch geltend machen","den Anspruch verlieren"],
"v354": ["die Wohnungsnot bekämpfen","unter Wohnungsnot leiden","die Wohnungsnot in den Städten"],
"v355": ["Wohnraum schaffen","bezahlbarer Wohnraum","knapper Wohnraum"],
"v358": ["die Nebenkosten abrechnen","die Nebenkosten steigen","Miete inklusive Nebenkosten"],
"v362": ["eine moderne Ausstattung","die Ausstattung der Küche","eine einfache Ausstattung"],
"v364": ["sexuelle Belästigung","Belästigung durch Lärm","eine Belästigung melden"],
"v365": ["sich über den Lärm beschweren","sich beim Vermieter beschweren","sich schriftlich beschweren"],
"v366": ["eine Beschwerde einreichen","Beschwerde einlegen","eine Beschwerde prüfen"],
"v367": ["die Hausordnung einhalten","gegen die Hausordnung verstoßen","laut Hausordnung"],
"v379": ["ein sicheres Passwort","das Passwort ändern","das Passwort vergessen"],
"v384": ["den Datenschutz beachten","gegen den Datenschutz verstoßen","aus Gründen des Datenschutzes"],
"v386": ["der Algorithmus entscheidet","einen Algorithmus entwickeln","der Algorithmus bevorzugt"],
"v389": ["die Automatisierung vorantreiben","durch Automatisierung ersetzen","die Automatisierung der Produktion"],
"v397": ["ein Konto hacken","gehackt werden","Systeme hacken"],
"v401": ["ein Backup machen","ein Backup erstellen","das Backup wiederherstellen"],
"v402": ["den Akku aufladen","der Akku ist leer","der Akku hält lange"],
"v407": ("die App aktualisieren","die Software aktualisieren","regelmäßig aktualisieren"),
"v409": ["ein Abonnement abschließen","das Abonnement kündigen","ein Abonnement verlängern"],
"v415": ["zu einem Thema forschen","an der Universität forschen","seit Jahren forschen"],
"v422": ["eine Hypothese aufstellen","die Hypothese bestätigen","eine Hypothese widerlegen"],
"v423": ["eine neue Erkenntnis","zu der Erkenntnis kommen","wissenschaftliche Erkenntnisse"],
"v429": ["Daten auswerten","die Ergebnisse auswerten","statistisch auswerten"],
"v432": ["Passanten befragen","tausend Personen befragen","zu ihrer Meinung befragen"],
"v433": ["eine repräsentative Stichprobe","eine kleine Stichprobe","die Stichprobe umfasst"],
"v435": ["eine Quelle zitieren","wörtlich zitieren","aus einem Buch zitieren"],
"v437": ["mit Zahlen belegen","eine Behauptung belegen","durch Quellen belegen"],
"v445": ["die Frist einhalten","Regeln einhalten","einen Termin einhalten"],
"v446": ["ein Gutachten erstellen","ein Gutachten in Auftrag geben","laut Gutachten"],
"v447": ["Förderung beantragen","finanzielle Förderung","staatliche Förderung"],
"v453": ["Ergebnisse publizieren","in einer Fachzeitschrift publizieren","regelmäßig publizieren"],
"v455": ["an Glaubwürdigkeit verlieren","die Glaubwürdigkeit einer Quelle","Glaubwürdigkeit gewinnen"],
"v461": ["einem Ideal folgen","das Ideal der Schönheit","hohe Ideale haben"],
"v472": ["in Würde altern","gesund altern","die Gesellschaft altert"],
"v483": ["einem Trend folgen","im Trend liegen","ein neuer Trend"],
"v484": ["einen eigenen Stil haben","im Stil der achtziger Jahre","der Stil des Autors"],
"v490": ["ein Foto retuschieren","stark retuschieren","die Haut retuschieren"],
"v494": ["überzeugend wirken auf","beruhigend wirken","auf Kunden wirken"],
"v496": ["einen guten Eindruck machen","den Eindruck erwecken","einen bleibenden Eindruck hinterlassen"],
"v498": ["Selbstbewusstsein stärken","mehr Selbstbewusstsein gewinnen","mangelndes Selbstbewusstsein"],
"v500": ["maßlos übertreiben","beim Training übertreiben","kräftig übertreiben"],
"v513": ["auf der Bühne stehen","die Bühne betreten","auf die Bühne gehen"],
"v521": ["Regie führen","unter der Regie von","die Regie übernehmen"],
"v523": ["ein Drehbuch schreiben","das Drehbuch umschreiben","nach einem Drehbuch"],
"v526": ["eine Szene drehen","die Szene spielt in","eine dramatische Szene"],
"v527": ["die Vorstellung beginnt","eine Vorstellung besuchen","die Vorstellung ist ausverkauft"],
"v528": ["ein Stück aufführen","ein Konzert aufführen","zum ersten Mal aufführen"],
"v532": ["eine Rezension schreiben","eine positive Rezension","in der Rezension heißt es"],
"v539": ["ein bekanntes Werk","das Werk eines Künstlers","ein Werk veröffentlichen"],
"v546": ["das kulturelle Erbe","ein Erbe antreten","das Erbe bewahren"],
"v549": ["zum Vorstellungsgespräch einladen","ein Vorstellungsgespräch führen","sich auf das Vorstellungsgespräch vorbereiten"],
"v555": ["eine angemessene Vergütung","die Vergütung von Überstunden","die Vergütung erhöhen"],
"v556": ["Überstunden machen","Überstunden abbauen","bezahlte Überstunden"],
"v557": ["in Schichten arbeiten","die Schicht beginnt","eine Schicht übernehmen"],
"v559": ["in Teilzeit arbeiten","eine Stelle in Teilzeit","von Vollzeit auf Teilzeit wechseln"],
"v561": ["den Arbeitsvertrag unterschreiben","ein befristeter Arbeitsvertrag","laut Arbeitsvertrag"],
"v565": ["an einer Konferenz teilnehmen","eine Konferenz organisieren","auf einer Konferenz sprechen"],
"v567": ["als Führungskraft arbeiten","eine erfahrene Führungskraft","eine Führungskraft schulen"],
"v568": ["der berufliche Aufstieg","den Aufstieg schaffen","Aufstieg und Fall"],
"v584": ["in die Gewerkschaft eintreten","die Gewerkschaft fordert","Mitglied der Gewerkschaft"],
"v585": ["für höhere Löhne streiken","tagelang streiken","das Recht zu streiken"],
"v586": ["zum Streik aufrufen","der Streik dauert an","den Streik beenden"],
"v588": ["die Lage beurteilen","fair beurteilen","nach der Leistung beurteilen"],
"v589": ["Berufserfahrung sammeln","langjährige Berufserfahrung","Berufserfahrung mitbringen"],
"v591": ["eine Umschulung machen","eine Umschulung beginnen","die Umschulung finanzieren"],
"v594": ["in Rente gehen","die Rente reicht nicht","eine kleine Rente beziehen"],
"v601": ["Abfall trennen","Abfall vermeiden","Abfall entsorgen"],
"v606": ["die Verpackung recyceln","auf Verpackung verzichten","umweltfreundliche Verpackung"],
"v609": ["Strom verbrauchen","viel Energie verbrauchen","weniger Wasser verbrauchen"],
"v611": ["Strom sparen","Strom erzeugen","der Strom fällt aus"],
"v623": ["Emissionen reduzieren","Emissionen verursachen","die Emissionen senken"],
"v628": ["die Gesundheit schädigen","die Umwelt schädigen","nachhaltig schädigen"],
"v629": ["die Sicherheit gefährden","Menschen gefährden","den Erfolg gefährden"],
"v633": ["vom Aussterben bedroht","langsam aussterben","Arten sterben aus"],
"v640": ["eine lange Dürre","unter der Dürre leiden","die Dürre bedroht die Ernte"],
"v651": ["ein Abkommen schließen","ein Abkommen unterzeichnen","gegen das Abkommen verstoßen"],
"v652": ["Pfand zahlen","das Pfand zurückbekommen","Flaschen mit Pfand"],
"v659": ["Geld überweisen","auf ein Konto überweisen","die Miete überweisen"],
"v660": ["eine Überweisung tätigen","die Überweisung dauert","per Überweisung zahlen"],
"v664": ["eine Ermäßigung bekommen","Ermäßigung für Studierende","um Ermäßigung bitten"],
"v667": ["ein Konto eröffnen","das Konto überziehen","Geld vom Konto abheben"],
"v670": ["Geld abheben","am Automaten abheben","hundert Euro abheben"],
"v675": ["Schulden machen","Schulden abbauen","in Schulden geraten"],
"v692": ["eine größere Anschaffung","die Anschaffung lohnt sich","eine Anschaffung planen"],
"v698": ["ein Umtausch ist möglich","den Umtausch verlangen","Umtausch nur mit Kassenbon"],
"v700": ["zwei Jahre Garantie","die Garantie läuft ab","Garantie geben auf"],
"v703": ["eine Reklamation einreichen","die Reklamation anerkennen","eine berechtigte Reklamation"],
"v711": ["in Raten zahlen","die Rate beträgt","monatliche Raten"],
"v712": ["die Inflation steigt","hohe Inflation","die Inflation bekämpfen"],
"v717": ["dichter Verkehr","den Verkehr umleiten","der Verkehr steht still"],
"v729": ["den Anschluss verpassen","den Anschluss erreichen","der Anschluss nach Köln"],
"v734": ["im Stau stehen","in einen Stau geraten","ein kilometerlanger Stau"],
"v752": ["einen Unfall verursachen","einen Unfall haben","bei einem Unfall verletzt"],
"v754": ["Vorfahrt haben","die Vorfahrt beachten","die Vorfahrt nehmen"],
"v758": ["ein Bußgeld zahlen","ein Bußgeld verhängen","ein hohes Bußgeld"],
"v771": ["ein Gesetz verabschieden","gegen das Gesetz verstoßen","laut Gesetz"],
"v783": ["einen Antrag stellen","den Antrag ablehnen","einen Antrag bewilligen"],
"v787": ["eine Genehmigung beantragen","die Genehmigung erteilen","ohne Genehmigung"],
"v792": ["einen Antrag ablehnen","ein Angebot ablehnen","höflich ablehnen"],
"v794": ["einen Bescheid erhalten","der Bescheid kommt per Post","gegen den Bescheid vorgehen"],
"v795": ["Widerspruch einlegen","der Widerspruch wurde abgelehnt","fristgerecht Widerspruch einlegen"],
"v797": ["Klage einreichen","eine Klage abweisen","Klage erheben gegen"],
"v802": ["ein Urteil fällen","das Urteil verkünden","gegen das Urteil Berufung einlegen"],
"v807": ["eine Gebühr erheben","die Gebühr bezahlen","eine Gebühr fällt an"],
"v837": ["einen Nachweis erbringen","als Nachweis dienen","den Nachweis vorlegen"],
"v838": ["seine Unschuld nachweisen","Kenntnisse nachweisen","die Herkunft nachweisen"],
"v844": ["die Zulassung erhalten","die Zulassung beantragen","die Zulassung zum Studium"],
"v850": ["eine Klausur schreiben","die Klausur bestehen","durch die Klausur fallen"],
"v851": ["eine Hausarbeit schreiben","die Hausarbeit abgeben","eine Hausarbeit korrigieren"],
"v866": ["eine Mahnung erhalten","eine Mahnung schicken","die zweite Mahnung"],
"v874": ["die Konzentration lässt nach","hohe Konzentration erfordern","die Konzentration stören"],
"v875": ["vom Lernen ablenken","sich leicht ablenken lassen","die Aufmerksamkeit ablenken"],
"v878": ["die Arbeit unterbrechen","das Gespräch unterbrechen","kurz unterbrechen"],
"v900": ["die Abschlussarbeit schreiben","die Abschlussarbeit abgeben","die Abschlussarbeit betreuen"],
"v901": ["eine Arbeit betreuen","Kinder betreuen","Patienten betreuen"],
"v903": ["in die Sprechstunde gehen","eine Sprechstunde anbieten","die Sprechstunde findet statt"],
}
