# -*- coding: utf-8 -*-
"""Kollokationen Batch 9 (A2 Alltagsverben und Kernnomen): je 2 einfache Verbindungen (A2-Wortschatz)."""
K = {
"v049": ["zum Arzt gehen","der Arzt untersucht"],
"v051": ["der Kopf tut weh","den Kopf waschen"],
"v052": ["der Bauch tut weh","auf dem Bauch liegen"],
"v053": ["Medizin nehmen","die Medizin hilft"],
"v054": ["eine Reise machen","die Reise dauert"],
"v055": ["zum Bahnhof fahren","am Bahnhof warten"],
"v056": ["eine Fahrkarte kaufen","die Fahrkarte zeigen"],
"v057": ["in Frankfurt umsteigen","in den Bus umsteigen"],
"v058": ["einen Tisch reservieren","ein Zimmer reservieren"],
"v059": ["im Hotel übernachten","ein Hotel buchen"],
"v060": ["eine Reservierung haben","die Reservierung bestätigen"],
"v061": ["Geld sparen","für den Urlaub sparen"],
"v062": ["die Umwelt schonen","an die Umwelt denken"],
"v063": ["das Wetter ist schön","schlechtes Wetter"],
"v064": ["es regnet den ganzen Tag","es regnet stark"],
"v065": ["im Frühling blühen","der Frühling kommt"],
"v066": ["im Sommer baden","ein heißer Sommer"],
"v067": ["im Herbst wird es kalt","ein goldener Herbst"],
"v068": ["im Winter schneit es","ein kalter Winter"],
"v069": ["die Küche putzen","das Fenster putzen"],
"v070": ["im Supermarkt einkaufen","fürs Wochenende einkaufen"],
"v071": ["ein Geschäft eröffnen","das Geschäft schließt um acht"],
"v072": ["ein gutes Angebot","das Angebot gilt bis Samstag"],
"v157": ["zum Zahnarzt gehen","ein Termin beim Zahnarzt"],
"v158": ["die Rechnung bezahlen","die Rechnung stimmt nicht"],
"v159": ["Verspätung haben","zwanzig Minuten Verspätung"],
"v160": ["das Gepäck abgeben","viel Gepäck haben"],
"v161": ["sich beeilen müssen","sich am Morgen beeilen"],
"v162": ["in der Nacht schlafen","eine ruhige Nacht"],
"v1403": ["Handschuhe anziehen","warme Handschuhe"],
"v1404": ["mit dem Flugzeug fliegen","das Flugzeug landet"],
"v1414": ["eine Hose anprobieren","die Hose ist zu eng"],
"v1421": ["die Straße überqueren","in der Straße wohnen"],
"v1423": ["ein Feuer machen","das Feuer löschen"],
"v1425": ["im Schlafzimmer schlafen","das Schlafzimmer lüften"],
"v1426": ["der Lehrer erklärt","den Lehrer fragen"],
"v1427": ["Urlaub machen","im Urlaub sein"],
"v073": ["seine Meinung sagen","meiner Meinung nach"],
"v074": ["ein gutes Gefühl haben","das Gefühl haben, dass"],
"v075": ["an die Zukunft glauben","an Gott glauben"],
"v076": ["sich über das Geschenk freuen","sich auf den Besuch freuen"],
"v077": ["sich über den Bus ärgern","sich schnell ärgern"],
"v078": ["Angst haben vor","keine Angst haben"],
"v079": ["Streit haben","einen Streit beenden"],
"v080": ["sich für den Fehler entschuldigen","sich höflich entschuldigen"],
"v081": ["eine Einladung bekommen","die Einladung annehmen"],
"v082": ["zum Geburtstag gratulieren","herzlich gratulieren"],
"v083": ["Geburtstag haben","den Geburtstag feiern"],
"v084": ["Erfahrung haben","Erfahrungen sammeln"],
"v085": ["über den Streik berichten","kurz berichten"],
"v086": ["einen Witz erzählen","von der Reise erzählen"],
"v087": ["den Weg beschreiben","genau beschreiben"],
"v088": ["die Absicht haben","keine Absicht sein"],
"v089": ["einen Plan machen","den Plan ändern"],
"v090": ["auf gutes Wetter hoffen","auf eine Antwort hoffen"],
"v091": ["eine Entscheidung treffen","eine schwere Entscheidung"],
"v092": ["ein Restaurant empfehlen","einen Film empfehlen"],
"v093": ["eine Nachricht schreiben","eine gute Nachricht"],
"v094": ["die Zeitung lesen","in der Zeitung stehen"],
"v095": ["im Internet suchen","ohne Internet arbeiten"],
"v096": ["einen Beruf lernen","von Beruf sein"],
"v163": ["einen Vorschlag machen","den Vorschlag annehmen"],
"v164": ["eine Regel einhalten","die Regeln erklären"],
"v165": ["eine Chance haben","die Chance nutzen"],
"v166": ["ein Paket erwarten","Gäste erwarten"],
"v167": ["eine Antwort bekommen","auf die Antwort warten"],
"v168": ["eine lange Strecke","die Strecke fahren"],
"v1405": ["ein hohes Gebäude","das Gebäude ist alt"],
"v566": ["meine Kollegin hilft","mit der Kollegin sprechen"],
"v571": ["fleißig lernen","eine fleißige Schülerin"],
"v592": ["arbeitslos sein","arbeitslos werden"],
"v602": ["Papier recyceln","Glas recyceln"],
"v607": ["das Geschenk verpacken","schön verpacken"],
"v662": ["ein günstiges Zimmer","günstig einkaufen"],
"v668": ["ein Restaurant eröffnen","eine Ausstellung eröffnen"],
"v679": ["die Verkäuferin fragen","die Verkäuferin zeigt"],
"v682": ["eine Einkaufsliste schreiben","auf der Einkaufsliste stehen"],
"v685": ["gute Qualität","auf Qualität achten"],
"v725": ["ein Ticket kaufen","das Ticket zeigen"],
"v728": ["sich um zehn Minuten verspäten","der Zug verspätet sich"],
"v731": ["an der Baustelle warten","wegen der Baustelle langsam fahren"],
"v735": ["an der Ampel warten","bis zur Ampel gehen"],
"v760": ["den Führerschein machen","den Führerschein zeigen"],
"v764": ["zum Flughafen fahren","am Flughafen abholen"],
"v781": ["zum Amt gehen","einen Termin beim Amt"],
"v849": ["eine Übung machen","die Übung ist leicht"],
"v855": ["eine gute Note bekommen","die Note eins"],
"v863": ["in die Bibliothek gehen","in der Bibliothek lernen"],
"v887": ["die Aussprache üben","eine gute Aussprache"],
"v914": ["Freunde überraschen","zum Geburtstag überraschen"],
"v920": ["unsicher sein","sich unsicher fühlen"],
"v927": ["unruhig schlafen","unruhig werden"],
"v933": ["mutig sein","eine mutige Entscheidung"],
"v952": ["neugierig sein","neugierig fragen"],
"v957": ["sich einsam fühlen","einsam sein"],
"v965": ["das Kind loben","den Schüler loben"],
"v1026": ["in den Bergen wandern","am Sonntag wandern"],
"vw-a2arb-006": ["ein netter Kollege","mit dem Kollegen essen"],
"vw-a2arb-018": ["sich bei der Firma bewerben","sich als Techniker bewerben"],
"vw-a2arb-019": ["tausend Euro verdienen","Geld verdienen"],
"vw-a2arb-022": ["einen Termin machen","den Termin verschieben"],
"vw-a2arb-023": ["den Termin absagen","das Treffen absagen"],
"vw-a2arb-024": ["den Termin auf Montag verschieben","um eine Woche verschieben"],
"vw-a2arb-025": ["die Unterlagen mitbringen","alle Unterlagen haben"],
"vw-a2arb-027": ["ein Formular ausfüllen","das Formular abgeben"],
"vw-a2arb-028": ["das Formular ausfüllen","alles ausfüllen"],
"vw-a2arb-038": ["die Prüfung bestehen","den Test bestehen"],
"vw-a2arb-040": ["die Wörter wiederholen","den Kurs wiederholen"],
"vw-a2arb-041": ["einen Kurs besuchen","der Kurs beginnt"],
"vw-a2arb-043": ["eine Aufgabe lösen","die Aufgabe ist schwer"],
"vw-a2arb-044": ["die Regel erklären","genau erklären"],
"vw-a2arb-046": ["Deutsch üben","jeden Tag üben"],
"vw-a2arb-049": ["pünktlich kommen","pünktlich sein"],
"vw-a2arb-050": ["selbstständig arbeiten","selbstständig sein"],
"vw-a2arb-054": ["mit dem Chef sprechen","der Chef sagt"],
"vw-a2arb-055": ["in einer Firma arbeiten","die Firma baut"],
"vw-a2arb-056": ["ein neuer Mitarbeiter","die Mitarbeiter informieren"],
"vw-a2arb-057": ["die Sicherheit prüfen","für Sicherheit sorgen"],
"vw-a2arb-058": ["einen Fehler machen","Fehler sind normal"],
"vw-a2arb-064": ["eine Anfrage schicken","auf die Anfrage antworten"],
"vw-a2arb-065": ["eine Bestätigung bekommen","die Bestätigung per Mail"],
"vw-a2arb-068": ["am Schalter fragen","der Schalter ist geschlossen"],
"vw-a2arb-069": ["in der Warteschlange stehen","eine lange Warteschlange"],
"vw-a2arb-076": ["die Einarbeitung dauert","während der Einarbeitung"],
"vw-a2arb-077": ["eine Fortbildung machen","zur Fortbildung gehen"],
"vw-a2arb-079": ["gute Teamarbeit","Teamarbeit ist wichtig"],
"vw-a2arb-080": ["gute Kenntnisse haben","Kenntnisse in Deutsch"],
"vw-a2arb-081": ["sich kurz vorstellen","sich den Kollegen vorstellen"],
"vw-a2arb-082": ["beim Arzt nachfragen","noch einmal nachfragen"],
"vw-a2arb-083": ["sich krank melden","sich per Mail melden"],
"vw-a2arb-085": ["Unterstützung bekommen","Unterstützung brauchen"],
"vw-a2arb-087": ["unter Zeitdruck arbeiten","Zeitdruck haben"],
"vw-a2arb-088": ["die Bewerbungsunterlagen schicken","vollständige Bewerbungsunterlagen"],
"vw-a2all-004": ["die Heizung funktioniert nicht","die Heizung anmachen"],
"vw-a2all-006": ["die Reparatur kostet","eine Reparatur bezahlen"],
"vw-a2all-007": ["kaputt sein","kaputt gehen"],
"vw-a2all-008": ["das Fahrrad reparieren","die Heizung reparieren"],
"vw-a2all-011": ["den Müll trennen","den Müll rausbringen"],
"vw-a2all-012": ["Papier und Glas trennen","den Müll richtig trennen"],
"vw-a2all-013": ["das Zimmer aufräumen","die Küche aufräumen"],
"vw-a2all-014": ["Ordnung machen","Ordnung halten"],
"vw-a2all-015": ["das Handy ausschalten","am Handy spielen"],
"vw-a2all-016": ["die Mutter anrufen","kurz anrufen"],
"vw-a2all-019": ["eine E-Mail schicken","ein Paket schicken"],
"vw-a2all-020": ["den Chef erreichen","telefonisch erreichen"],
"vw-a2all-023": ["einen Termin absprechen","sich mit dem Team absprechen"],
"vw-a2all-025": ["Freunde einladen","zum Essen einladen"],
"vw-a2all-028": ["sich für die Verspätung entschuldigen","sich bei der Nachbarin entschuldigen"],
"vw-a2all-030": ["ein Geschenk kaufen","ein Geschenk bekommen"],
"vw-a2all-033": ["ein Fest feiern","zum Fest gehen"],
"vw-a2all-034": ["Geburtstag feiern","bis Mitternacht feiern"],
"vw-a2all-035": ["ein Gast kommt","der Gast bleibt lange"],
"vw-a2all-037": ["im Regen stehen","der Regen hört auf"],
"vw-a2all-038": ["der Schnee fällt","im Schnee spielen"],
"vw-a2all-039": ["der Wind ist stark","bei Wind und Regen"],
"vw-a2all-040": ["eine dunkle Wolke","die Wolken kommen"],
"vw-a2all-041": ["die Sonne scheint","in der Sonne sitzen"],
"vw-a2all-042": ["ein Gewitter kommt","bei Gewitter drinnen bleiben"],
"vw-a2all-043": ["die Temperatur steigt","die Temperatur messen"],
"vw-a2all-044": ["ein sonniger Tag","morgen wird es sonnig"],
"vw-a2all-045": ["bewölkt sein","ein bewölkter Himmel"],
"vw-a2all-046": ["am Morgen neblig","ein nebliger Tag"],
"vw-a2all-049": ["einen Flug buchen","online buchen"],
"vw-a2all-051": ["den Koffer packen","der Koffer ist schwer"],
"vw-a2all-052": ["die Tasche packen","alles packen"],
"vw-a2all-053": ["den Ausweis zeigen","den Ausweis mitbringen"],
"vw-a2all-054": ["den Pass verlängern","der Pass ist gültig"],
"vw-a2all-058": ["das Ticket ist gültig","gültig bis Dezember"],
"vw-a2all-062": ["den Hausmeister anrufen","der Hausmeister repariert"],
"vw-a2all-063": ["den Aufzug nehmen","der Aufzug ist kaputt"],
"vw-a2all-064": ["im Keller stehen","in den Keller gehen"],
"vw-a2all-066": ["das Zimmer lüften","morgens lüften"],
"vw-a2all-067": ["der Lärm stört","Lärm machen"],
"vw-a2all-068": ["sich über das Essen beschweren","sich beim Hausmeister beschweren"],
"vw-a2all-069": ["eine Sprachnachricht schicken","die Sprachnachricht anhören"],
"vw-a2all-070": ["einen Anruf bekommen","auf den Anruf warten"],
"vw-a2all-071": ["die Leitung ist besetzt","der Platz ist besetzt"],
"vw-a2all-072": ["die Ansage hören","eine Ansage im Zug"],
"vw-a2all-073": ["die Mail weiterleiten","den Anruf weiterleiten"],
"vw-a2all-074": ["eine nette Unterhaltung","die Unterhaltung beginnen"],
"vw-a2all-076": ["höflich fragen","höflich sein"],
"vw-a2all-078": ["einen Termin vorschlagen","ein Restaurant vorschlagen"],
"vw-a2all-079": ["für Samstag zusagen","schnell zusagen"],
"vw-a2all-080": ["sich für die Hilfe bedanken","sich herzlich bedanken"],
"vw-a2all-081": ["Rücksicht nehmen","Rücksicht auf die Nachbarn"],
"vw-a2all-083": ["Frost in der Nacht","bei Frost vorsichtig fahren"],
"vw-a2all-084": ["große Hitze","bei Hitze viel trinken"],
"vw-a2all-085": ["die Vorhersage sagt","die Vorhersage für morgen"],
"vw-a2all-086": ["eine Unterkunft suchen","eine günstige Unterkunft"],
"vy-leben-003": ["der Grund für die Verspätung","einen guten Grund haben"],
"vy-leben-005": ["ein großer Unterschied","den Unterschied erklären"],
"vy-leben-006": ["eine Möglichkeit haben","die beste Möglichkeit"],
"vy-leben-008": ["sich für den Kurs entscheiden","sich schnell entscheiden"],
"vy-leben-010": ["die Preise vergleichen","zwei Angebote vergleichen"],
"vy-leben-011": ["das Wort bedeutet","viel bedeuten"],
"vy-leben-012": ["den Kindern erlauben","nicht erlaubt sein"],
"vy-leben-018": ["auf die Kinder aufpassen","im Unterricht aufpassen"],
"vy-leben-019": ["etwas fest versprechen","viel versprechen"],
"vy-leben-021": ["eine Gelegenheit nutzen","bei Gelegenheit"],
"vy-leben-022": ["eine Bedingung stellen","die Bedingung erfüllen"],
"vy-leben-023": ["zu welchem Zweck","der Zweck der Reise"],
"vy-leben-024": ["eine große Wirkung","die Wirkung der Medizin"],
"vy-leben-025": ["eine wichtige Erfindung","die Erfindung des Telefons"],
"vy-leben-029": ["die Nachricht löschen","ein Foto löschen"],
"vy-leben-030": ["ein Programm herunterladen","die Datei herunterladen"],
"vy-leben-031": ["die Verbindung ist schlecht","eine schnelle Verbindung"],
"vy-leben-041": ["Beschwerden haben","die Beschwerden werden schlimmer"],
"vy-leben-044": ["gesunde Ernährung","auf die Ernährung achten"],
"vy-leben-045": ["fünf Kilo abnehmen","schnell abnehmen"],
"vy-leben-046": ["im Winter zunehmen","drei Kilo zunehmen"],
"vy-leben-047": ["im Notfall anrufen","ein medizinischer Notfall"],
"vy-leben-050": ["die Geschwindigkeit messen","mit hoher Geschwindigkeit"],
"vy-leben-054": ["eine Strafe bekommen","eine Strafe zahlen"],
"vy-leben-057": ["zuständig sein","der zuständige Mitarbeiter"],
"vy-leben-058": ["eine Auskunft bekommen","um Auskunft bitten"],
"vy-leben-059": ["im Erdgeschoss wohnen","der Laden im Erdgeschoss"],
"vy-leben-901": ["eine Beratung bekommen","zur Beratung gehen"],
"vy-leben-902": ["als Anlage schicken","die Anlage öffnen"],
"vy-leben-903": ["die Nutzung der App","kostenlose Nutzung"],
"vz-schrei-001": ["ein besonderer Anlass","aus diesem Anlass"],
"vz-schrei-002": ["die richtige Anrede","die Anrede im Brief"],
"vz-schrei-003": ["den Betreff schreiben","ohne Betreff schicken"],
"vz-schrei-004": ["mit freundlichen Grüßen als Grußformel","die Grußformel am Ende"],
"vz-schrei-006": ["eine Bitte haben","um etwas bitten"],
"vz-schrei-009": ["dem Vorschlag zustimmen","dem Plan zustimmen"],
"vz-schrei-011": ["den Standpunkt erklären","einen klaren Standpunkt"],
"vz-schrei-012": ["ein Beispiel geben","ein gutes Beispiel"],
"vz-schrei-019": ["einen Zuschuss bekommen","der Zuschuss vom Amt"],
"vz-schrei-020": ["die Kündigungsfrist beachten","eine Kündigungsfrist von drei Monaten"],
"vz-schrei-022": ["ein Feiertag ist frei","am Feiertag geschlossen"],
"vz-schrei-023": ["die Kinderbetreuung organisieren","Kinderbetreuung suchen"],
"vz-schrei-024": ["Nachbarschaftshilfe anbieten","die Nachbarschaftshilfe im Viertel"],
"vz-schrei-025": ["sich über den Kurs informieren","sich im Internet informieren"],
"vz-schrei-026": ["am Kurs teilnehmen","an der Prüfung teilnehmen"],
"vz-schrei-027": ["die Teilnahme ist kostenlos","die Teilnahme bestätigen"],
"vz-schrei-029": ["eine Verpflichtung haben","keine Verpflichtung sein"],
"vz-schrei-030": ["die Bedienung ist freundlich","die Bedienung rufen"],
"vz-schrei-036": ["eine große Auswahl","die Auswahl treffen"],
"vz-schr-900": ["die Rückgabe ist möglich","bei der Rückgabe"],
"vz-schr-901": ["eine Anzahlung leisten","die Anzahlung beträgt"],
"vz-schr-902": ["zur Beratungsstelle gehen","die Beratungsstelle hilft"],
"vz-schr-903": ["einen Sprachnachweis brauchen","den Sprachnachweis vorlegen"],
"vz-schr-904": ["die Unterschrift fehlt","eine Unterschrift leisten"],
"vz-schr-905": ["eine Vollmacht geben","mit Vollmacht abholen"],
"vz-schr-906": ["ein Anschreiben verfassen","das Anschreiben ist kurz"],
}
