# -*- coding: utf-8 -*-
"""Kollokationen Batch 3 (B2 Fachwortschatz, Teil 1): je 2 Verbindungen. AUSNAHMEN: Wörter ohne feste Kollokation (Präpositionen, Phrasen)."""
AUSNAHMEN = {
"v176": "Präposition (angesichts) — keine Nomen-Verb-Verbindung",
"v596": "ist selbst eine Wendung (in den Ruhestand gehen)",
"v674": "ist selbst eine Wendung (ins Minus rutschen)",
"v693": "ist selbst eine Wendung (sich leisten können)",
"v949": "ist selbst eine Wendung (jdn bloßstellen)",
"v969": "ist selbst eine Wendung (jdm etwas vorwerfen)",
"v991": "ist selbst eine Wendung (an seine Grenzen stoßen)",
"v1131": "ist selbst eine Wendung (sitzen bleiben)",
}
K = {
"v124": ["angeblich geschönte Zahlen","angeblich krank sein"],
"v127": ["nachhaltig wirtschaften","nachhaltig bauen"],
"v175": ["unvermeidliche Folgen","ein unvermeidlicher Konflikt"],
"v191": ["ein zuverlässiger Partner","zuverlässig arbeiten"],
"v243": ["langsam gesunden","vollständig gesunden"],
"v255": ["nach Anerkennung süchtig","süchtig nach dem Handy"],
"v262": ["Pausen bei Bildschirmarbeit","die Bildschirmarbeit belastet die Augen"],
"v1408": ["das Herz abhören","das Herz schlägt schneller"],
"v287": ["ehrenamtlich tätig sein","ehrenamtlich arbeiten"],
"v307": ["in der Konsumgesellschaft leben","Kritik an der Konsumgesellschaft"],
"v335": ["ländliche Gegenden","der ländliche Raum"],
"v349": ["ein befristeter Vertrag","befristet einstellen"],
"v350": ["eine unbefristete Stelle","unbefristet übernehmen"],
"v360": ["die Möblierung bleibt","eine einfache Möblierung"],
"v371": ["einen Chatbot einsetzen","der Chatbot antwortet"],
"v385": ["die DSGVO einhalten","gegen die DSGVO verstoßen"],
"v387": ["künstliche Intelligenz einsetzen","die Grenzen künstlicher Intelligenz"],
"v391": ["als Influencer arbeiten","der Influencer wirbt für"],
"v395": ["im Online-Handel bestellen","der Online-Handel wächst"],
"v398": ["Cyberkriminalität bekämpfen","Opfer von Cyberkriminalität"],
"v400": ["in der Cloud speichern","aus der Cloud laden"],
"v408": ["im Spam landen","Spam filtern"],
"v410": ["eine bekannte Influencerin","die Influencerin kennzeichnet Werbung"],
"v456": ["eine glaubwürdige Quelle","glaubwürdig wirken"],
"v459": ["eine attraktive Stelle","attraktiv gestalten"],
"v468": ["Make-up auftragen","dezentes Make-up"],
"v475": ["modisch gekleidet","ein modischer Mantel"],
"v476": ["ein schlichtes Outfit","das Outfit wählen"],
"v479": ["ein bekanntes Label","das Label steht für"],
"v481": ["ein neuer Look","der Look passt zu ihr"],
"v482": ["das Styling für das Foto","professionelles Styling"],
"v485": ["stilvoll eingerichtet","stilvoll gekleidet"],
"v487": ["eine schlichte Wohnung","schlicht und funktional"],
"v489": ["künstlich wirken","künstliches Licht"],
"v492": ["ein Selfie machen","ein Selfie posten"],
"v497": ["selbstbewusst auftreten","selbstbewusst antworten"],
"v499": ["eine übertriebene Warnung","übertriebene Erwartungen"],
"v535": ["Lyrik lesen","moderne Lyrik"],
"v547": ["zum Weltkulturerbe gehören","als Weltkulturerbe anerkennen"],
"v573": ["als überqualifiziert gelten","überqualifiziert für die Stelle"],
"v574": ["chronisch unterbezahlt","unterbezahlte Pflegekräfte"],
"v577": ["auf Work-Life-Balance achten","eine gesunde Work-Life-Balance"],
"v604": ["auf Einwegprodukte verzichten","ein billiges Einwegprodukt"],
"v613": ["erneuerbare Energien","aus erneuerbaren Quellen"],
"v615": ["ein Windrad aufstellen","das Windrad dreht sich"],
"v616": ["einen Windpark bauen","gegen den Windpark protestieren"],
"v617": ["fossile Energie","fossile Brennstoffe"],
"v626": ["umweltschonend reisen","umweltschonend produzieren"],
"v634": ["das Aussterben einer Art","vom Aussterben bedroht sein"],
"v635": ["die Biodiversität schützen","der Verlust an Biodiversität"],
"v636": ["ein Biotop anlegen","das Biotop gefährden"],
"v644": ["das Gletscherschmelzen beschleunigt sich","die Folgen des Gletscherschmelzens"],
"v645": ["den Regenwald schützen","der Regenwald schrumpft"],
"v649": ["den Treibhauseffekt verstärken","der natürliche Treibhauseffekt"],
"v653": ["ein Mehrwegsystem einführen","auf ein Mehrwegsystem umstellen"],
"v656": ["die Klimabewegung wächst","sich der Klimabewegung anschließen"],
"v676": ["verschuldete Haushalte","verschuldet sein"],
"v686": ["Quantität statt Qualität","auf Quantität setzen"],
"v688": ["minderwertige Ware","minderwertiges Material"],
"v689": ["hochwertige Materialien","ein hochwertiges Produkt"],
"v707": ["im Schlussverkauf kaufen","der Schlussverkauf beginnt"],
"v713": ["die Teuerung bremsen","unter der Teuerung leiden"],
"v714": ["zahlungsunfähig werden","für zahlungsunfähig erklären"],
"v718": ["sich mit dem Rad fortbewegen","sich zu Fuß fortbewegen"],
"v721": ["die Elektromobilität fördern","der Ausbau der Elektromobilität"],
"v732": ["eine Straßensperrung umfahren","eine Straßensperrung ankündigen"],
"v739": ["mit dem Lastenrad transportieren","ein Lastenrad leihen"],
"v740": ["eine Mitfahrgelegenheit suchen","eine Mitfahrgelegenheit anbieten"],
"v741": ["eine Fahrgemeinschaft bilden","in einer Fahrgemeinschaft fahren"],
"v742": ["als Pendlerin unterwegs","die Pendlerin steigt um"],
"v744": ["das tägliche Pendeln","das Pendeln kostet Zeit"],
"v746": ["die Mobilitätswende vorantreiben","Ziele der Mobilitätswende"],
"v747": ["die Verkehrswende gestalten","für die Verkehrswende werben"],
"v748": ["in die Umweltzone einfahren","die Umweltzone einrichten"],
"v749": ["eine Geschwindigkeitsbegrenzung einführen","die Geschwindigkeitsbegrenzung beachten"],
"v750": ["ein Tempolimit einführen","gegen das Tempolimit sein"],
"v751": ["die Höchstgeschwindigkeit überschreiten","die zulässige Höchstgeschwindigkeit"],
"v755": ["im Parkhaus parken","das Parkhaus verlassen"],
"v756": ["Parkverbot beachten","im Parkverbot stehen"],
"v761": ["die Fahrschule besuchen","in der Fahrschule lernen"],
"v762": ["mit dem Fernbus reisen","der Fernbus hält am Bahnhof"],
"v763": ["den Nachtzug nehmen","im Nachtzug schlafen"],
"v765": ["die Fluggesellschaft erstattet","bei der Fluggesellschaft buchen"],
"v772": ["gesetzlich geregelt","die gesetzliche Frist"],
"v776": ["ein Grundwert der Demokratie","Grundwerte vermitteln"],
"v801": ["die Richterin entscheidet","vor der Richterin aussagen"],
"v805": ["die Anwältin rät","eine Anwältin beauftragen"],
"v808": ["die Justiz reformieren","die unabhängige Justiz"],
"v812": ["in den Bundestag einziehen","der Bundestag beschließt"],
"v813": ["der Bundesrat stimmt zu","im Bundesrat vertreten"],
"v814": ["föderal organisiert","der föderale Staat"],
"v819": ["jemanden abschieben","in das Herkunftsland abschieben"],
"v824": ["inhaftiert werden","seit gestern inhaftiert"],
"v828": ["eine Vorstrafe haben","eine Vorstrafe eintragen"],
"v832": ["Bestechung im Amt","wegen Bestechung verurteilt"],
"v840": ["eine Beglaubigung vornehmen","die Beglaubigung kostet"],
"v841": ["vor dem Verfassungsgericht klagen","das Verfassungsgericht entscheidet"],
"v1409": ["der Staat finanziert","Aufgaben des Staates"],
"v1410": ["das Militär einsetzen","beim Militär dienen"],
"v846": ["der Numerus clausus liegt bei","wegen des Numerus clausus warten"],
"v848": ["im Hörsaal sitzen","den Hörsaal verlassen"],
"v872": ["mit dem Karteikasten lernen","Karten in den Karteikasten sortieren"],
"v873": ["eine Karteikarte schreiben","die Karteikarte umdrehen"],
"v880": ["effizient arbeiten","eine effiziente Methode"],
"v883": ["ein Lerntagebuch führen","im Lerntagebuch notieren"],
"v884": ["einen Selbsttest machen","der Selbsttest zeigt Lücken"],
"v885": ["sich regelmäßig überprüfen","sich mit Karten überprüfen"],
"v891": ["sich beim Namen vertippen","sich schnell vertippen"],
"v893": ["ein Flüchtigkeitsfehler passiert","Flüchtigkeitsfehler vermeiden"],
"v895": ["die Dozentin erwartet","bei der Dozentin nachfragen"],
"v1412": ["als Student arbeiten","der Student zahlt weniger"],
"v906": ["neidisch sein auf","neidisch werden"],
"v911": ["frustriert aufgeben","frustriert reagieren"],
"v915": ["angespannt wirken","die angespannte Lage"],
"v917": ["gelassen bleiben","gelassen reagieren"],
"v922": ["das Selbstwertgefühl stärken","ein gesundes Selbstwertgefühl"],
"v923": ["belastbar sein","psychisch belastbar"],
"v926": ["innere Unruhe spüren","die innere Unruhe wächst"],
"v931": ["gut gelaunt sein","gut gelaunt ankommen"],
"v932": ["ein launischer Chef","launisch reagieren"],
"v939": ["Dankbarkeit zeigen","aus Dankbarkeit helfen"],
"v940": ["von der Sperrung betroffen","betroffen reagieren"],
"v942": ["mitfühlend zuhören","eine mitfühlende Ärztin"],
"v944": ["gleichgültig bleiben","gleichgültig reagieren"],
"v945": ["Gleichgültigkeit zeigen","die Gleichgültigkeit der Mehrheit"],
"v947": ["vor Scham rot werden","Scham empfinden"],
"v948": ["sich für den Akzent schämen","sich vor anderen schämen"],
"v951": ["jemanden tief kränken","jemanden nicht kränken wollen"],
"v954": ["vor Freude überwältigt","völlig überwältigt sein"],
"v956": ["sich nach Hause sehnen","sich nach dem Meer sehnen"],
"v959": ["Geborgenheit spüren","Geborgenheit geben"],
"v960": ["sich geborgen fühlen","geborgen aufwachsen"],
"v962": ["bedürftige Haushalte","bedürftig sein"],
"v967": ["einen Schüler tadeln","scharf tadeln"],
"v968": ["einen Tadel bekommen","ein Tadel im Zeugnis"],
"v971": ["überglücklich sein","überglücklich reagieren"],
"v973": ["Kummer haben","vor Kummer nicht schlafen"],
"v981": ["Ausdauertraining machen","regelmäßiges Ausdauertraining"],
"v982": ["Krafttraining machen","Krafttraining schützt vor Stürzen"],
"v983": ["sich vor dem Laufen dehnen","sich gründlich dehnen"],
"v984": ["das Dehnen nach dem Training","das Dehnen nicht vergessen"],
"v987": ["völlig erschöpft","erschöpft nach Hause kommen"],
"v992": ["eine maßlose Übertreibung","die Übertreibung im Training"],
"v993": ["moderate Bewegung","moderat trainieren"],
"v994": ["die Belastung dosieren","sparsam dosieren"],
"v997": ["die Sehne reißt","eine Sehne verletzen"],
"v998": ["eine Prellung am Knie","eine Prellung kühlen"],
"v999": ["eine Zerrung haben","Zerrungen vorbeugen"],
"v1003": ["die Mannschaft anfeuern","vom Rand aus anfeuern"],
"v1004": ["über das Tor jubeln","gemeinsam jubeln"],
"v1005": ["großer Jubel","der Jubel im Stadion"],
"v1007": ["das Derby gewinnen","Karten fürs Derby"],
"v1010": ["einen Elfmeter schießen","den Elfmeter verwandeln"],
"v1012": ["das Spiel abpfeifen","der Schiedsrichter muss pfeifen"],
"v1013": ["eine Abseitsstellung erkennen","wegen Abseitsstellung nicht zählen"],
"v1014": ["restlos ausverkauft","schnell ausverkauft sein"],
"v1016": ["Freizeitgestaltung ohne Bildschirm","Angebote zur Freizeitgestaltung"],
"v1018": ["zur Mitgliederversammlung einladen","auf der Mitgliederversammlung wählen"],
"v1022": ["aus dem Verein austreten","aus der Kirche austreten"],
"v1024": ["eine Unternehmung planen","eine gemeinsame Unternehmung"],
"v1025": ["auf dem Campingplatz übernachten","der Campingplatz ist ausgebucht"],
"v1028": ["mit dem Mountainbike fahren","ein Mountainbike leihen"],
"v1029": ["eine Radtour machen","eine Radtour entlang des Flusses"],
"v1031": ["mit einem Unentschieden enden","ein gerechtes Unentschieden"],
"v1033": ["im Elfmeterschießen gewinnen","das Elfmeterschießen entscheidet"],
"v1036": ["diszipliniert trainieren","diszipliniert arbeiten"],
"v1038": ["Zensur ausüben","der Zensur unterliegen"],
"v1039": ["auf Clickbait hereinfallen","reiner Clickbait"],
"v1040": ["die Reichweite erhöhen","eine große Reichweite"],
"v1041": ["in der Aufmerksamkeitsökonomie zählen","die Logik der Aufmerksamkeitsökonomie"],
"v1042": ["Meinungsmache betreiben","gezielte Meinungsmache"],
"v1044": ["Desinformation verbreiten","gegen Desinformation vorgehen"],
"v1045": ["Fake News verbreiten","Fake News erkennen"],
"v1046": ["einen Faktencheck machen","der Faktencheck ergibt"],
"v1047": ["die Einordnung fehlt","eine sachliche Einordnung"],
"v1048": ["die Leitmedien berichten","Kritik an den Leitmedien"],
"v1049": ["Agenda-Setting betreiben","Agenda-Setting durch Medien"],
"v1050": ["die Schweigespirale erklärt","in die Schweigespirale geraten"],
"v1051": ["in der Filterblase leben","die Filterblase verlassen"],
"v1052": ["in der Echokammer bleiben","eine digitale Echokammer"],
"v1053": ["den Rundfunkbeitrag zahlen","der Rundfunkbeitrag finanziert"],
"v1054": ["die Medienlandschaft verändert sich","eine vielfältige Medienlandschaft"],
"v1055": ["die Zuspitzung vermeiden","eine bewusste Zuspitzung"],
"v1056": ["die Polarisierung verstärken","zunehmende Polarisierung"],
"v1057": ["Empörung auslösen","große Empörung"],
"v1058": ["soziale Ächtung","die Ächtung im Netz"],
"v1059": ["die öffentliche Meinung beeinflussen","die öffentliche Meinung kippt"],
"v1060": ["Selbstzensur üben","aus Selbstzensur schweigen"],
"v1061": ["Quellenkritik üben","Quellenkritik lernen"],
"v1062": ["einen Leitartikel schreiben","der Leitartikel vertritt"],
"v1063": ["die Bildsprache der Kampagne","eine klare Bildsprache"],
"v1064": ["eine bewusste Untertreibung","zur Untertreibung neigen"],
"v1065": ["das Framing erkennen","ein negatives Framing"],
"v1066": ["die Deutungshoheit beanspruchen","um die Deutungshoheit streiten"],
"v1067": ["eine Gegenöffentlichkeit schaffen","als Gegenöffentlichkeit dienen"],
"v1068": ["die Werbewirtschaft finanziert","Interessen der Werbewirtschaft"],
"v1069": ["Schleichwerbung betreiben","verbotene Schleichwerbung"],
"v1070": ["der Transparenzpflicht unterliegen","die Transparenzpflicht erfüllen"],
"v1072": ["der Presserat rügt","Beschwerde beim Presserat"],
"v1073": ["eine Gegendarstellung verlangen","die Gegendarstellung abdrucken"],
"v1074": ["mit der Informationsflut umgehen","in der Informationsflut untergehen"],
"v1075": ["unter Nachrichtenmüdigkeit leiden","Nachrichtenmüdigkeit nimmt zu"],
"v1076": ["der Nachrichtenticker meldet","den Nachrichtenticker verfolgen"],
"v1078": ["eine These widerlegen","eine Behauptung widerlegen"],
"v1079": ["die Wahrheit verschweigen","wichtige Fakten verschweigen"],
"v1081": ["eine Zahl einordnen","historisch einordnen"],
"v1083": ["eine reißerische Überschrift","reißerisch berichten"],
"v1084": ["ein tendenziöser Bericht","tendenziös berichten"],
"v1087": ["meinungsstark auftreten","ein meinungsstarker Kommentar"],
"v1088": ["Chancengerechtigkeit herstellen","mehr Chancengerechtigkeit fordern"],
"v1089": ["die Kulturhoheit der Länder","an der Kulturhoheit festhalten"],
"v1090": ["eine Grundschulempfehlung erhalten","die Grundschulempfehlung ist verbindlich"],
"v1091": ["auf die Gesamtschule gehen","eine Gesamtschule gründen"],
"v1092": ["der Ganztagsanspruch gilt","den Ganztagsanspruch umsetzen"],
"v1093": ["Inklusion umsetzen","Inklusion an Schulen"],
"v1094": ["die frühe Aussonderung","die Aussonderung kritisieren"],
"v1095": ["die Abbrecherquote senken","eine hohe Abbrecherquote"],
"v1096": ["das klassische Bildungsbürgertum","zum Bildungsbürgertum gehören"],
"v1097": ["Bildungssprache beherrschen","Bildungssprache fördern"],
"v1098": ["den Zweiten Bildungsweg gehen","den Zweiten Bildungsweg nutzen"],
"v1099": ["eine Vergleichsstudie durchführen","die Vergleichsstudie zeigt"],
"v1100": ["als Wiederholer starten","die Zahl der Wiederholer"],
"v1101": ["als Sitzenbleiber gelten","das Wort Sitzenbleiber vermeiden"],
"v1102": ["zum Elternabend gehen","der Elternabend findet statt"],
"v1103": ["die Klassenkonferenz entscheidet","die Klassenkonferenz einberufen"],
"v1104": ["die Versetzung ist gefährdet","die Versetzung erreichen"],
"v1107": ["einen Leistungskurs wählen","der Leistungskurs Mathematik"],
"v1108": ["im Grundkurs sitzen","der Grundkurs zählt weniger"],
"v1109": ["die Vergabe der Studienplätze","die zentrale Vergabe"],
"v1111": ["als Exzellenzuniversität gelten","der Titel Exzellenzuniversität"],
"v1112": ["Drittmittel einwerben","auf Drittmittel angewiesen"],
"v1113": ["Geisteswissenschaften studieren","die Zukunft der Geisteswissenschaften"],
"v1114": ["unter Unterfinanzierung leiden","die chronische Unterfinanzierung"],
"v1115": ["den Personalschlüssel verbessern","der Personalschlüssel in der Kita"],
"v1116": ["den Förderbedarf feststellen","einen besonderen Förderbedarf haben"],
"v1117": ["einen Schulverweis erteilen","mit dem Schulverweis drohen"],
"v1118": ["die Schulsozialarbeit stärken","Schulsozialarbeit anbieten"],
"v1119": ["eine Patenschaft übernehmen","durch eine Patenschaft unterstützen"],
"v1120": ["die Einschulung feiern","der Tag der Einschulung"],
"v1121": ["die Promotionsordnung verlangt","die Promotionsordnung ändern"],
"v1122": ["die Habilitation abschließen","nach der Habilitation lehren"],
"v1123": ["einen Bildungskredit aufnehmen","den Bildungskredit zurückzahlen"],
"v1125": ["die Bildungsrendite messen","eine hohe Bildungsrendite"],
"v1126": ["in Frühförderung investieren","Frühförderung anbieten"],
"v1127": ["Sprachförderung anbieten","zusätzliche Sprachförderung"],
"v1128": ["die frühe Selektion","die Selektion nach der Grundschule"],
"v1129": ["unter Notendruck stehen","den Notendruck verringern"],
"v1130": ["die Hausaufgabenbetreuung besuchen","Hausaufgabenbetreuung anbieten"],
"v1132": ["kompetenzorientiert unterrichten","ein kompetenzorientierter Lehrplan"],
"v1133": ["bildungsferne Familien","aus bildungsfernen Schichten"],
"v1134": ["eine inklusive Schule","inklusiv unterrichten"],
"v1136": ["ein chancengleiches System","chancengleich gestalten"],
"v1413": ["Macht ausüben","die Macht kontrollieren"],
"v1424": ["die Freiheit einschränken","für die Freiheit kämpfen"],
}
