# -*- coding: utf-8 -*-
"""Kollokationen Batch 2 (B2, allgemeine Verben/Nomen): je 3 feste Verbindungen."""
K = {
"v137": ["die Verantwortung übernehmen","die Kosten übernehmen","eine Aufgabe übernehmen"],
"v139": ["Kenntnisse voraussetzen","als bekannt voraussetzen","Erfahrung voraussetzen"],
"v142": ["den Namen angeben","den Grund angeben","Gründe angeben"],
"v143": ["Bezug nehmen auf","mit Bezug auf den Vertrag","den Bezug herstellen"],
"v144": ["das Studium abschließen","einen Vertrag abschließen","eine Versicherung abschließen"],
"v178": ["grundsätzlich umdenken","beim Konsum umdenken","radikal umdenken"],
"v179": ["zu einem Mittel greifen","nach dem Handy greifen","zum Telefon greifen"],
"v216": ["jemandem den Erfolg gönnen","sich eine Pause gönnen","niemandem etwas gönnen"],
"v257": ["Kollegen mobben","im Netz mobben","systematisch mobben"],
"v274": ["Obdachlose unterbringen","als Obdachloser leben","Hilfe für Obdachlose"],
"v275": ["einen Migrationshintergrund haben","Kinder mit Migrationshintergrund","der Migrationshintergrund spielt keine Rolle"],
"v276": ["als Migrant ankommen","die Rechte der Migranten","ein Migrant der zweiten Generation"],
"v292": ["an einer Kundgebung teilnehmen","eine Kundgebung anmelden","die Kundgebung vor dem Rathaus"],
"v301": ["im Rechtsstaat leben","den Rechtsstaat verteidigen","ein Merkmal des Rechtsstaats"],
"v309": ["die Meinungsfreiheit schützen","die Meinungsfreiheit einschränken","das Recht auf Meinungsfreiheit"],
"v328": ["eine gute Nachbarschaft","in der Nachbarschaft wohnen","die Nachbarschaft pflegen"],
"v330": ["in eine andere Stadt umziehen","nächsten Monat umziehen","wegen der Arbeit umziehen"],
"v334": ["ein ruhiger Stadtteil","in einem anderen Stadtteil wohnen","der Stadtteil im Norden"],
"v337": ["in die Innenstadt fahren","die Innenstadt beleben","mitten in der Innenstadt"],
"v339": ["ein Eigenheim bauen","vom Eigenheim träumen","ein Eigenheim finanzieren"],
"v344": ["die Heizung modernisieren","das Gebäude modernisieren","energetisch modernisieren"],
"v347": ["eine Wohnung besichtigen","das Haus besichtigen","die Stadt besichtigen"],
"v357": ["mit Freunden zusammenleben","friedlich zusammenleben","mit der Familie zusammenleben"],
"v361": ["mit Technik ausstatten","die Küche ausstatten","gut ausgestattet sein"],
"v363": ["den Grundriss zeichnen","ein offener Grundriss","einen Grundriss anfordern"],
"v370": ["eine Plattform betreiben","über eine Plattform buchen","auf der Plattform anmelden"],
"v376": ["die Bildschirmzeit begrenzen","zu viel Bildschirmzeit","die Bildschirmzeit der Kinder"],
"v380": ["ein Nutzerkonto anlegen","das Nutzerkonto löschen","sich im Nutzerkonto anmelden"],
"v390": ["die Kluft überwinden","eine tiefe Kluft","die Kluft zwischen Arm und Reich"],
"v399": ["die Datenspeicherung begrenzen","die Datenspeicherung in der Cloud","Regeln zur Datenspeicherung"],
"v404": ["der Speicher reicht nicht","Speicher freigeben","mehr Speicher brauchen"],
"v406": ["die Nutzungsbedingungen akzeptieren","die Nutzungsbedingungen lesen","gegen die Nutzungsbedingungen verstoßen"],
"v413": ["ein Update installieren","das Update herunterladen","ein Update verpassen"],
"v425": ["im Labor arbeiten","Proben im Labor untersuchen","ein modernes Labor"],
"v427": ["einen Datensatz auswerten","der Datensatz umfasst","einen großen Datensatz"],
"v430": ["die Auswertung der Daten","die Auswertung dauert","eine statistische Auswertung"],
"v443": ["eine Vorlesung halten","die Vorlesung besuchen","die Vorlesung fällt aus"],
"v449": ["ein Forschungsprojekt leiten","ein Forschungsprojekt finanzieren","an einem Forschungsprojekt arbeiten"],
"v450": ["auf Nachhaltigkeit achten","Nachhaltigkeit fördern","das Prinzip der Nachhaltigkeit"],
"v451": ["in Physik promovieren","nach dem Master promovieren","im Ausland promovieren"],
"v452": ["die Promotion abschließen","mit der Promotion beginnen","während der Promotion"],
"v454": ["die Veröffentlichung verzögern","eine wissenschaftliche Veröffentlichung","die Veröffentlichung planen"],
"v1430": ["Wissen vermitteln","Wissen erwerben","fundiertes Wissen"],
"v462": ["dem Schönheitsideal entsprechen","das Schönheitsideal hinterfragen","ein unerreichbares Schönheitsideal"],
"v480": ["eine bekannte Marke","auf die Marke achten","eine Marke aufbauen"],
"v491": ["ohne Retusche zeigen","starke Retusche","die Retusche kennzeichnen"],
"v493": ["der erste Eindruck zählt","der erste Eindruck täuscht","den ersten Eindruck korrigieren"],
"v501": ["aus Eitelkeit handeln","die Eitelkeit der Menschen","ein Zeichen von Eitelkeit"],
"v507": ["ein Gemälde betrachten","ein Gemälde restaurieren","das Gemälde hängt im Museum"],
"v510": ["eine Skulptur aus Stahl","eine Skulptur aufstellen","die Skulptur vor dem Bahnhof"],
"v511": ["ein Denkmal errichten","ein Denkmal setzen","das Denkmal erinnert an"],
"v522": ["der Regisseur dreht","unter einem bekannten Regisseur","der Regisseur des Films"],
"v524": ["der Darsteller spielt","ein bekannter Darsteller","die Darsteller proben"],
"v531": ["ein Buch rezensieren","einen Film rezensieren","kritisch rezensieren"],
"v538": ["ein bekannter Schriftsteller","der Schriftsteller liest vor","Schriftsteller und Verleger"],
"v542": ["ein zentrales Motiv","das Motiv der Reise","aus welchem Motiv"],
"v548": ["eine Sehenswürdigkeit besuchen","die wichtigste Sehenswürdigkeit","Sehenswürdigkeiten der Stadt"],
"v558": ["Schichtarbeit leisten","die Schichtarbeit belastet","Schichtarbeit im Krankenhaus"],
"v560": ["in Vollzeit arbeiten","eine Stelle in Vollzeit","auf Vollzeit wechseln"],
"v569": ["in der Firma aufsteigen","zum Teamleiter aufsteigen","schnell aufsteigen"],
"v575": ["ein Burnout erleiden","vor dem Burnout schützen","Anzeichen für ein Burnout"],
"v576": ["die Vereinbarkeit von Familie und Beruf","die Vereinbarkeit verbessern","Vereinbarkeit ermöglichen"],
"v590": ["als Quereinsteiger anfangen","Quereinsteiger einstellen","ein Quereinsteiger aus der Gastronomie"],
"v595": ["in den Ruhestand treten","den Ruhestand genießen","im Ruhestand sein"],
"v598": ["die Luftqualität messen","schlechte Luftqualität","die Luftqualität verbessern"],
"v599": ["die Umwelt verschmutzen","das Wasser verschmutzen","die Luft verschmutzen"],
"v603": ["die Wiederverwendung fördern","zur Wiederverwendung geeignet","Wiederverwendung statt Recycling"],
"v605": ["Plastikmüll vermeiden","Plastikmüll im Meer","der Plastikmüll wächst"],
"v612": ["ein Kraftwerk bauen","das Kraftwerk abschalten","ein Kraftwerk betreiben"],
"v614": ["Solarenergie nutzen","auf Solarenergie umsteigen","Strom aus Solarenergie"],
"v621": ["den Ausstoß senken","der Ausstoß von CO2","den Ausstoß messen"],
"v622": ["Schadstoffe ausstoßen","CO2 ausstoßen","weniger Abgase ausstoßen"],
"v624": ["Feinstaub messen","die Belastung durch Feinstaub","Feinstaub in der Luft"],
"v625": ["das Umweltbewusstsein stärken","wachsendes Umweltbewusstsein","aus Umweltbewusstsein handeln"],
"v630": ["sich für den Naturschutz einsetzen","Maßnahmen zum Naturschutz","Naturschutz und Landwirtschaft"],
"v631": ["ein Schutzgebiet ausweisen","im Schutzgebiet leben","das Schutzgebiet erweitern"],
"v637": ["das Grundwasser schützen","das Grundwasser sinkt","Grundwasser fördern"],
"v638": ["Hochwasser droht","vom Hochwasser betroffen","das Hochwasser steigt"],
"v641": ["eine Hitzewelle überstehen","während der Hitzewelle","die Hitzewelle hält an"],
"v642": ["der Meeresspiegel steigt","den Anstieg des Meeresspiegels bremsen","der Meeresspiegel sinkt"],
"v643": ["der Gletscher schmilzt","der Gletscher zieht sich zurück","auf dem Gletscher wandern"],
"v646": ["den Wald abholzen","illegal abholzen","große Flächen abholzen"],
"v647": ["die Abholzung stoppen","die Abholzung des Regenwaldes","gegen die Abholzung protestieren"],
"v648": ["Treibhausgase ausstoßen","ein starkes Treibhausgas","Treibhausgase reduzieren"],
"v650": ["das Klimaziel erreichen","das Klimaziel verfehlen","ein ehrgeiziges Klimaziel"],
"v654": ["die Mülltrennung erklären","bei der Mülltrennung helfen","Regeln zur Mülltrennung"],
"v658": ["die Zahlung leisten","die Zahlung erfolgt","eine Zahlung erhalten"],
"v665": ["Einkommen versteuern","den Gewinn versteuern","Einnahmen versteuern"],
"v666": ["die Mehrwertsteuer senken","inklusive Mehrwertsteuer","die Mehrwertsteuer beträgt"],
"v672": ["ein Guthaben aufladen","das Guthaben reicht","Guthaben auf der Karte"],
"v673": ["den Kontostand prüfen","der Kontostand ist negativ","den Kontostand abfragen"],
"v677": ["die Verschuldung steigt","hohe Verschuldung","die Verschuldung abbauen"],
"v681": ["die Kundschaft bedienen","treue Kundschaft","neue Kundschaft gewinnen"],
"v684": ["ein Schnäppchen machen","ein echtes Schnäppchen","auf Schnäppchen achten"],
"v691": ["ein Plakat aufhängen","ein Plakat entwerfen","das Plakat wirbt für"],
"v695": ["einen Haushaltsplan aufstellen","der Haushaltsplan der Stadt","sich an den Haushaltsplan halten"],
"v696": ["den Kassenbon aufheben","den Kassenbon vorlegen","den Kassenbon verlieren"],
"v697": ["eine Quittung ausstellen","eine Quittung verlangen","die Quittung aufbewahren"],
"v699": ["den Pullover umtauschen","gegen eine andere Größe umtauschen","die Ware umtauschen"],
"v701": ["die Gewährleistung gilt","Anspruch auf Gewährleistung","die gesetzliche Gewährleistung"],
"v702": ["die Ware reklamieren","einen Mangel reklamieren","sofort reklamieren"],
"v704": ["vom Rückgaberecht Gebrauch machen","das Rückgaberecht gilt","ein Rückgaberecht von vierzehn Tagen"],
"v710": ["am Geldautomaten abheben","der Geldautomat ist außer Betrieb","der nächste Geldautomat"],
"v715": ["Insolvenz anmelden","in die Insolvenz gehen","die Insolvenz abwenden"],
"v720": ["ein Elektroauto laden","auf ein Elektroauto umsteigen","die Reichweite des Elektroautos"],
"v722": ["eine Ladestation suchen","an der Ladestation laden","Ladestationen ausbauen"],
"v724": ["den Fahrgast informieren","der Fahrgast steigt ein","ein Fahrgast ohne Ticket"],
"v726": ["die Fahrkarte entwerten","das Ticket entwerten","vor der Fahrt entwerten"],
"v730": ["auf Gleis fünf","das Gleis wechseln","der Zug fährt von Gleis drei"],
"v743": ["zur Arbeit pendeln","täglich pendeln","zwischen zwei Städten pendeln"],
"v757": ["einen Strafzettel bekommen","der Strafzettel liegt unter dem Scheibenwischer","einen Strafzettel bezahlen"],
"v759": ["ein Fahrverbot verhängen","ein Fahrverbot von einem Monat","gegen das Fahrverbot verstoßen"],
"v767": ["nur Handgepäck mitnehmen","das Handgepäck kontrollieren","ins Handgepäck passen"],
"v768": ["die Anreise planen","die Anreise erfolgt","am Tag der Anreise"],
"v769": ["die Abreise vorbereiten","am Tag der Abreise","die Abreise verschieben"],
"v770": ["die Rückkehr feiern","die Rückkehr planen","die Rückkehr in die Heimat"],
"v773": ["die Rechtslage prüfen","die Rechtslage ist eindeutig","nach aktueller Rechtslage"],
"v774": ["die Verfassung ändern","gegen die Verfassung verstoßen","in der Verfassung stehen"],
"v775": ["das Grundgesetz schützt","im Grundgesetz verankert","das Grundgesetz ändern"],
"v777": ["der Paragraph regelt","laut Paragraph drei","einen Paragraphen streichen"],
"v778": ["eine Vorschrift befolgen","gegen die Vorschrift verstoßen","strenge Vorschriften"],
"v779": ["das Gesetz schreibt vor","Maßnahmen vorschreiben","jemandem nichts vorschreiben"],
"v782": ["in der Verwaltung arbeiten","die Verwaltung modernisieren","die öffentliche Verwaltung"],
"v785": ["den Antrag bewilligen","Mittel bewilligen","den Kredit bewilligen"],
"v786": ["die Bewilligung abwarten","ohne Bewilligung starten","die Bewilligung erhalten"],
"v788": ["den Umbau genehmigen","einen Antrag genehmigen","offiziell genehmigen"],
"v790": ["ein Verbot aussprechen","gegen das Verbot verstoßen","das Verbot aufheben"],
"v791": ["um Erlaubnis bitten","die Erlaubnis erteilen","ohne Erlaubnis betreten"],
"v793": ["die Ablehnung begründen","eine Ablehnung erhalten","gegen die Ablehnung vorgehen"],
"v796": ["dem Bescheid widersprechen","einer Aussage widersprechen","sich selbst widersprechen"],
"v798": ["vor Gericht klagen","gegen den Vermieter klagen","auf Schadensersatz klagen"],
"v803": ["ein Verfahren einleiten","das Verfahren einstellen","das Verfahren dauert"],
"v806": ["eine Rechtsberatung in Anspruch nehmen","kostenlose Rechtsberatung","zur Rechtsberatung gehen"],
"v810": ["die Pressefreiheit garantieren","die Pressefreiheit einschränken","Angriffe auf die Pressefreiheit"],
"v811": ["das Wahlrecht ausüben","das Wahlrecht ab sechzehn","das Wahlrecht erhalten"],
"v815": ["die Staatsbürgerschaft beantragen","die deutsche Staatsbürgerschaft erhalten","die Staatsbürgerschaft verlieren"],
"v816": ["die Einbürgerung beantragen","die Einbürgerung dauert","Voraussetzungen für die Einbürgerung"],
"v817": ["jemanden einbürgern","eingebürgert werden","achthundert Menschen einbürgern"],
"v818": ["den Aufenthalt verlängern","einen legalen Aufenthalt","während des Aufenthalts"],
"v820": ["die Abschiebung stoppen","eine Abschiebung anordnen","von Abschiebung bedroht"],
"v821": ["Asyl beantragen","Asyl gewähren","um Asyl bitten"],
"v823": ["in Haft sitzen","aus der Haft entlassen","zu zwei Jahren Haft verurteilen"],
"v825": ["eine Straftat begehen","eine Straftat anzeigen","eine schwere Straftat"],
"v826": ["ein Verbrechen aufklären","ein Verbrechen begehen","ein schweres Verbrechen"],
"v829": ["eine Geldstrafe zahlen","eine Geldstrafe verhängen","zu einer Geldstrafe verurteilen"],
"v830": ["Korruption bekämpfen","Korruption aufdecken","der Verdacht auf Korruption"],
"v831": ["einen Beamten bestechen","mit Geld bestechen","sich nicht bestechen lassen"],
"v833": ["eine Fälschung erkennen","eine Fälschung aufdecken","eine plumpe Fälschung"],
"v834": ["Dokumente fälschen","eine Unterschrift fälschen","Zeugnisse fälschen"],
"v835": ["eine Bescheinigung ausstellen","eine Bescheinigung vorlegen","die Bescheinigung der Universität"],
"v836": ["die Arbeitsunfähigkeit bescheinigen","schriftlich bescheinigen","den Empfang bescheinigen"],
"v839": ["Kopien beglaubigen","beglaubigen lassen","amtlich beglaubigen"],
"v842": ["einen Studiengang wählen","der Studiengang kombiniert","den Studiengang wechseln"],
"v843": ["einen Studienplatz bekommen","um einen Studienplatz bewerben","der Studienplatz ist begehrt"],
"v845": ["zum Studium zulassen","Bewerber zulassen","zur Prüfung zulassen"],
"v852": ["einen Schein machen","den Schein bekommen","der Schein aus dem Seminar"],
"v853": ["einen Leistungsnachweis erbringen","der Leistungsnachweis besteht aus","den Leistungsnachweis vorlegen"],
"v854": ["eine Arbeit benoten","streng benoten","nach Kriterien benoten"],
"v856": ["durch die Prüfung fallen","zweimal durchfallen","knapp durchfallen"],
"v857": ["von der Prüfung zurücktreten","vom Vertrag zurücktreten","rechtzeitig zurücktreten"],
"v858": ["die Rückmeldung läuft","eine Rückmeldung geben","auf Rückmeldung warten"],
"v859": ["die Einschreibung beantragen","die Einschreibung erfolgt","die Frist für die Einschreibung"],
"v860": ["sich an der Uni einschreiben","sich für Informatik einschreiben","sich fristgerecht einschreiben"],
"v861": ["die Studienberatung aufsuchen","zur Studienberatung gehen","die Studienberatung empfiehlt"],
"v864": ["Bücher ausleihen","in der Bibliothek ausleihen","ein Fahrrad ausleihen"],
"v865": ["die Leihfrist verlängern","die Leihfrist überschreiten","die Leihfrist beträgt"],
"v867": ["gutes Zeitmanagement","Zeitmanagement lernen","Tipps zum Zeitmanagement"],
"v868": ["einen Lernplan erstellen","sich an den Lernplan halten","der Lernplan sieht vor"],
"v869": ["eine Lernmethode ausprobieren","die passende Lernmethode","eine effektive Lernmethode"],
"v870": ["regelmäßige Wiederholung","eine Wiederholung einplanen","die Wiederholung des Stoffes"],
"v871": ["eine Eselsbrücke bauen","sich eine Eselsbrücke merken","eine gute Eselsbrücke"],
"v876": ["eine Ablenkung vermeiden","ohne Ablenkung lernen","die größte Ablenkung"],
"v877": ["eine kurze Unterbrechung","ohne Unterbrechung arbeiten","eine Unterbrechung vermeiden"],
"v879": ["eine technische Störung","die Störung beheben","eine Störung melden"],
"v881": ["die Effizienz steigern","hohe Effizienz","die Effizienz messen"],
"v882": ["den Lernerfolg messen","der Lernerfolg zeigt sich","ein sichtbarer Lernerfolg"],
"v888": ["die Betonung liegt auf","die richtige Betonung","mit Betonung sprechen"],
"v889": ["eine Silbe betonen","richtig betonen","die erste Silbe betonen"],
"v890": ["die Rechtschreibung üben","Fehler in der Rechtschreibung","die neue Rechtschreibung"],
"v892": ["einen Tippfehler machen","einen Tippfehler übersehen","ein Tippfehler in der Adresse"],
"v894": ["der Dozent erklärt","ein erfahrener Dozent","den Dozenten fragen"],
"v897": ["an der Fakultät studieren","die Fakultät für Informatik","der Dekan der Fakultät"],
"v899": ["eine Exkursion machen","an der Exkursion teilnehmen","die Exkursion führt nach"],
"v902": ["einen Betreuer finden","der Betreuer der Arbeit","mit dem Betreuer sprechen"],
"v1428": ["eine Prüfung bestehen","eine Prüfung ablegen","sich auf die Prüfung vorbereiten"],
"v1429": ["Kenntnisse erwerben","gute Kenntnisse in Deutsch","Kenntnisse vertiefen"],
"v904": ["Stolz empfinden","mit Stolz erfüllen","aus Stolz schweigen"],
"v907": ["Eifersucht empfinden","vor Eifersucht rasen","aus Eifersucht handeln"],
"v912": ["der Frust wächst","seinen Frust abbauen","Frust über die Bürokratie"],
"v916": ["die Anspannung fällt ab","unter Anspannung stehen","die Anspannung lösen"],
"v918": ["Gelassenheit zeigen","mit Gelassenheit reagieren","innere Gelassenheit"],
"v921": ["Selbstvertrauen gewinnen","Selbstvertrauen aufbauen","mangelndes Selbstvertrauen"],
"v924": ["die Belastung reduzieren","eine hohe Belastung","unter der Belastung leiden"],
"v925": ["die Umwelt belasten","das Budget belasten","jemanden mit Sorgen belasten"],
"v935": ["das Leben riskieren","viel riskieren","einen Streit riskieren"],
"v941": ["Mitgefühl zeigen","Mitgefühl empfinden","aus Mitgefühl handeln"],
"v943": ["Mitleid haben mit","Mitleid empfinden","kein Mitleid zeigen"],
"v946": ["eine Warnung ignorieren","die Regeln ignorieren","jemanden bewusst ignorieren"],
"v950": ["eine Kränkung erleben","eine tiefe Kränkung","die Kränkung verzeihen"],
"v953": ["die Neugier wecken","aus Neugier fragen","voller Neugier"],
"v955": ["Sehnsucht haben nach","die Sehnsucht nach dem Meer","voller Sehnsucht"],
"v958": ["unter Einsamkeit leiden","die Einsamkeit im Alter","Einsamkeit überwinden"],
"v961": ["ein Bedürfnis haben","das Bedürfnis nach Ruhe","Bedürfnisse erfüllen"],
"v963": ["einen Abschluss anerkennen","die Leistung anerkennen","offiziell anerkennen"],
"v964": ["Anerkennung finden","Anerkennung bekommen","die Anerkennung des Diploms"],
"v966": ["ein Lob aussprechen","Lob bekommen","ein ehrliches Lob"],
"v970": ["einen Vorwurf machen","den Vorwurf zurückweisen","ein berechtigter Vorwurf"],
"v972": ["Heimweh haben","unter Heimweh leiden","das Heimweh überwinden"],
"v980": ["die Kondition verbessern","eine gute Kondition","an der Kondition arbeiten"],
"v986": ["eine große Anstrengung","mit letzter Anstrengung","die Anstrengung lohnt sich"],
"v988": ["Erholung brauchen","zur Erholung fahren","Erholung finden"],
"v989": ["sich vom Stress erholen","sich im Urlaub erholen","sich schnell erholen"],
"v995": ["die Dosis erhöhen","eine niedrige Dosis","die richtige Dosis"],
"v1000": ["einen Wettkampf gewinnen","am Wettkampf teilnehmen","sich auf den Wettkampf vorbereiten"],
"v1001": ["einen Wettbewerb ausschreiben","am Wettbewerb teilnehmen","den Wettbewerb gewinnen"],
"v1002": ["ein Turnier veranstalten","das Turnier gewinnen","beim Turnier antreten"],
"v1006": ["eine Niederlage einstecken","eine bittere Niederlage","die Niederlage verkraften"],
"v1011": ["der Schiedsrichter pfeift","den Schiedsrichter kritisieren","die Entscheidung des Schiedsrichters"],
"v1015": ["die Übertragung beginnt","die Übertragung verfolgen","die Übertragung des Spiels"],
"v1019": ["den Beitritt erklären","der Beitritt zum Verein","den Beitritt beantragen"],
"v1020": ["einem Verein beitreten","der Gewerkschaft beitreten","einer Gruppe beitreten"],
"v1021": ["den Austritt erklären","der Austritt aus dem Verein","den Austritt schriftlich mitteilen"],
"v1027": ["eine Wanderung machen","eine Wanderung planen","eine mehrstündige Wanderung"],
"v1030": ["einen Marathon laufen","für den Marathon trainieren","den Marathon beenden"],
"v1032": ["in die Verlängerung gehen","die Verlängerung des Vertrags","eine Verlängerung beantragen"],
"v1035": ["eine Bestleistung aufstellen","seine Bestleistung verbessern","die persönliche Bestleistung"],
}
