# -*- coding: utf-8 -*-
"""Kollokationen Batch 6 (B1 Rest, Teil 1): je 2 Verbindungen. Konnektoren/Präpositionen → AUSNAHMEN (Wortart)."""
AUSNAHMEN = {
"vg-argumen-009": "Konnektor (dennoch) — keine Nomen-Verb-Verbindung",
"vg-argumen-010": "Konnektor (allerdings)",
"vg-argumen-015": "Konnektor (folglich)",
"vg-argumen-016": "Konnektor (daher)",
"vg-argumen-018": "Präposition (hinsichtlich)",
"vh-projekt-041": "Satzadverb (erfreulicherweise)",
"vh-projekt-042": "Satzadverb (bedauerlicherweise)",
"vk-b1x-034": "Satzadverb (vermutlich)",
}
K = {
"v1043": ["Manipulation erkennen","gezielte Manipulation"],
"v1071": ["eine Recherche durchführen","gründliche Recherche"],
"v1077": ["das Gegenteil behaupten","etwas ohne Beweis behaupten"],
"v1080": ["eine Aussage zuspitzen","die Lage spitzt sich zu"],
"v1082": ["eine Entscheidung nachvollziehen","die Gründe nachvollziehen"],
"v1085": ["eine seriöse Quelle","seriös wirken"],
"v1086": ["anonym bleiben","ein anonymer Kommentar"],
"v1105": ["eine Doppelstunde Mathematik","die Doppelstunde dauert neunzig Minuten"],
"v1106": ["in die Oberstufe kommen","in der Oberstufe wählen"],
"v1110": ["auf der Warteliste stehen","auf die Warteliste setzen"],
"v1124": ["Nachhilfe geben","Nachhilfe nehmen"],
"v1135": ["leistungsstarke Schüler","leistungsstark sein"],
"v1142": ["eine Sanktion verhängen","mit Sanktionen drohen"],
"v1152": ["bei der Tafel helfen","die Tafel verteilt Lebensmittel"],
"v1160": ["eine Stiftung gründen","die Stiftung finanziert"],
"v1172": ["zum Jobcenter gehen","das Jobcenter zahlt"],
"v1175": ["Geld spenden","für die Tafel spenden"],
"v1176": ["benachteiligte Kinder","benachteiligt werden"],
"v1207": ["die Umsiedlung ablehnen","von der Umsiedlung betroffen"],
"v1208": ["eine Entschädigung zahlen","Entschädigung fordern"],
"v1214": ["das Gerät abschalten","den Strom abschalten"],
"v1236": ["die Haltung der Tiere","eine artgerechte Haltung"],
"v1238": ["einen Auslauf haben","der Auslauf hinter dem Stall"],
"v1245": ["eine Klausel im Vertrag","die Klausel streichen"],
"v1257": ["einen Gutschein einlösen","einen Gutschein verschenken"],
"v1264": ["Werbung kennzeichnen","deutlich kennzeichnen"],
"v1294": ["der Zuzug in die Stadt","den Zuzug begrenzen"],
"v1308": ["eine Sozialwohnung beantragen","in einer Sozialwohnung leben"],
"v1312": ["Büros in Wohnungen umwandeln","die Nutzung umwandeln"],
"v1328": ["ein Visum beantragen","das Visum läuft ab"],
"v1351": ["sich in der neuen Stadt einleben","sich schnell einleben"],
"v1396": ["ein Problem verdrängen","Gefühle verdrängen"],
"vg-gesells-001": ["die Bevölkerung wächst","die Bevölkerung informieren"],
"vg-gesells-002": ["die Mehrheit entscheidet","die Mehrheit der Befragten"],
"vg-gesells-003": ["eine Minderheit schützen","zur Minderheit gehören"],
"vg-gesells-004": ["die Gleichberechtigung fördern","für Gleichberechtigung kämpfen"],
"vg-gesells-005": ["Chancengleichheit schaffen","mehr Chancengleichheit fordern"],
"vg-gesells-006": ["eine Benachteiligung erfahren","gegen Benachteiligung vorgehen"],
"vg-gesells-008": ["die Herkunft spielt keine Rolle","nach der Herkunft fragen"],
"vg-gesells-010": ["Toleranz zeigen","zur Toleranz erziehen"],
"vg-gesells-011": ["Respekt zeigen","mit Respekt behandeln"],
"vg-gesells-021": ["die Steuererklärung abgeben","die Steuererklärung machen"],
"vg-gesells-024": ["im Wohlstand leben","der Wohlstand wächst"],
"vg-gesells-031": ["die Beteiligung der Bürger","eine hohe Beteiligung"],
"vg-gesells-032": ["an die Öffentlichkeit gehen","in der Öffentlichkeit sprechen"],
"vg-argumen-000": ["eine Behauptung aufstellen","die Behauptung prüfen"],
"vg-argumen-004": ["einen Beleg liefern","ohne Beleg bleiben"],
"vg-argumen-008": ["einen Fehler einräumen","ehrlich einräumen"],
"vg-argumen-020": ["die Lage einschätzen","richtig einschätzen"],
"vg-argumen-021": ["eine realistische Einschätzung","die Einschätzung teilen"],
"vg-argumen-023": ["Vor- und Nachteile abwägen","sorgfältig abwägen"],
"vg-staatx-700": ["die Zivilgesellschaft stärken","Teil der Zivilgesellschaft"],
"vg-arbeit--000": ["Karriere machen","die Karriere planen"],
"vg-arbeit--001": ["den Werdegang beschreiben","ein beruflicher Werdegang"],
"vg-arbeit--002": ["eine Qualifikation erwerben","die nötige Qualifikation"],
"vg-arbeit--005": ["sich beruflich weiterentwickeln","sich ständig weiterentwickeln"],
"vg-arbeit--006": ["eine Beförderung bekommen","die Beförderung feiern"],
"vg-arbeit--008": ["ein Arbeitszeugnis ausstellen","das Arbeitszeugnis lesen"],
"vg-arbeit--010": ["den Schritt in die Selbstständigkeit wagen","die Selbstständigkeit planen"],
"vg-arbeit--011": ["eine Firma gründen","einen Verein gründen"],
"vg-arbeit--013": ["an der Aufgabe scheitern","das Projekt scheitert"],
"vg-arbeit--014": ["einen Misserfolg erleben","aus dem Misserfolg lernen"],
"vg-arbeit--015": ["Erfolg haben","zum Erfolg führen"],
"vg-arbeit--017": ["Elternzeit nehmen","in Elternzeit gehen"],
"vg-arbeit--018": ["eine Teilzeitstelle suchen","auf eine Teilzeitstelle wechseln"],
"vg-arbeit--019": ["im Homeoffice arbeiten","Homeoffice erlauben"],
"vg-arbeit--021": ["über das Gehalt verhandeln","hart verhandeln"],
"vg-arbeit--025": ["der Fachkräftemangel wächst","unter Fachkräftemangel leiden"],
"vg-arbeit--026": ["in welcher Branche arbeiten","die Branche wechseln"],
"vg-arbeit--028": ["eine Zielvereinbarung treffen","die Zielvereinbarung erfüllen"],
"vg-psyche--000": ["die Psyche belasten","die Psyche stärken"],
"vg-psyche--002": ["unter Druck stehen","Druck ausüben"],
"vg-psyche--006": ["Achtsamkeit üben","mit Achtsamkeit essen"],
"vg-psyche--009": ["die Hoffnung verlieren","Hoffnung geben"],
"vg-psyche--012": ["sich zu Hause wohlfühlen","sich im Team wohlfühlen"],
"vg-psyche--013": ["Unsicherheit spüren","die Unsicherheit nehmen"],
"vg-psyche--014": ["Zweifel haben","der Zweifel bleibt"],
"vg-psyche--016": ["eine Entscheidung bereuen","nichts bereuen"],
"vg-psyche--017": ["einen Fehler verzeihen","jemandem verzeihen"],
"vg-psyche--018": ["eine Auseinandersetzung haben","eine heftige Auseinandersetzung"],
"vg-psyche--020": ["jemandem Faulheit vorwerfen","einen Fehler vorwerfen"],
"vg-psyche--021": ["jemanden beleidigen","sich beleidigt fühlen"],
"vg-psyche--022": ["sich im Team durchsetzen","sich mit Argumenten durchsetzen"],
"vg-psyche--024": ["zwischen zwei Seiten vermitteln","im Streit vermitteln"],
"vg-psyche--025": ["die Vermittlung übernehmen","eine Vermittlung anbieten"],
"vg-psyche--026": ["im Streit einlenken","am Ende einlenken"],
"vg-psyche--029": ["die Versöhnung feiern","eine Versöhnung anbieten"],
"vh-projekt-000": ["ein Projekt leiten","das Projekt abschließen"],
"vh-projekt-001": ["den Tag planen","genau planen"],
"vh-projekt-002": ["einen Zeitplan erstellen","den Zeitplan einhalten"],
"vh-projekt-004": ["die Zusammenarbeit verbessern","eine gute Zusammenarbeit"],
"vh-projekt-006": ["die Umsetzung des Plans","mit der Umsetzung beginnen"],
"vh-projekt-007": ["eine Idee umsetzen","den Plan umsetzen"],
"vh-projekt-009": ["eine Präsentation halten","die Präsentation vorbereiten"],
"vh-projekt-010": ["eine Folie zeigen","die Folien vorbereiten"],
"vh-projekt-017": ["den Text verbessern","die Qualität verbessern"],
"vh-projekt-018": ["einen Entwurf schreiben","den Entwurf überarbeiten"],
"vh-projekt-019": ["die endgültige Fassung","eine neue Fassung"],
"vh-projekt-021": ["ein Fazit ziehen","zum Fazit kommen"],
"vh-projekt-022": ["eine Gliederung erstellen","die Gliederung der Arbeit"],
"vh-projekt-023": ["sich mit dem Team abstimmen","sich vorher abstimmen"],
"vh-gesundh-000": ["eine gesunde Lebensweise","die Lebensweise ändern"],
"vh-gesundh-001": ["zur Vorsorgeuntersuchung gehen","eine Vorsorgeuntersuchung machen"],
"vh-gesundh-003": ["eine Therapie beginnen","die Therapie hilft"],
"vh-gesundh-004": ["Nebenwirkungen haben","starke Nebenwirkungen"],
"vh-gesundh-005": ["eine chronische Krankheit","chronisch krank sein"],
"vh-gesundh-007": ["das Immunsystem stärken","ein schwaches Immunsystem"],
"vh-gesundh-008": ["die Belastbarkeit erhöhen","an die Grenze der Belastbarkeit"],
"vh-gesundh-009": ["das Gleichgewicht halten","das Gleichgewicht verlieren"],
"vh-gesundh-011": ["der Verzicht auf Zucker","der Verzicht fällt schwer"],
"vh-gesundh-013": ["Ausdauer trainieren","viel Ausdauer brauchen"],
"vh-gesundh-015": ["eine Ernährungsberatung machen","zur Ernährungsberatung gehen"],
"vh-gesundh-018": ["eine Rehabilitation beantragen","nach der Rehabilitation arbeiten"],
"vh-gesundh-019": ["zum Pflegefall werden","einen Pflegefall betreuen"],
"vh-technik-000": ["die Anwendung erklären","eine praktische Anwendung"],
"vh-technik-001": ["eine Funktion haben","die Funktion prüfen"],
"vh-technik-002": ["die Einstellung ändern","die richtige Einstellung"],
"vh-technik-003": ["eine Aktualisierung installieren","die Aktualisierung dauert"],
"vh-technik-005": ["Zugang haben zu","den Zugang sperren"],
"vh-technik-007": ["eine sichere Verschlüsselung","die Verschlüsselung aktivieren"],
"vh-technik-008": ["Missbrauch verhindern","den Missbrauch melden"],
"vh-technik-009": ["in Abhängigkeit geraten","die Abhängigkeit vom Handy"],
"vh-technik-013": ["eine Falschmeldung verbreiten","eine Falschmeldung erkennen"],
"vh-technik-014": ["Nachrichten verbreiten","sich schnell verbreiten"],
"vh-technik-015": ["eine Stellungnahme abgeben","um Stellungnahme bitten"],
"vh-technik-016": ["als Journalist arbeiten","der Journalist recherchiert"],
"vh-technik-017": ["eine Tatsache sein","Tatsachen prüfen"],
"vh-technik-019": ["ein deutlicher Rückgang","der Rückgang der Zahlen"],
"vh-technik-020": ["ein starker Anstieg","der Anstieg der Preise"],
"vh-technik-021": ["die Miete beträgt","die Gebühr beträgt sechs Euro"],
"vi-stadt-u-000": ["die Infrastruktur ausbauen","eine gute Infrastruktur"],
"vi-stadt-u-001": ["den Nahverkehr nutzen","der Nahverkehr fährt"],
"vi-stadt-u-002": ["eine gute Anbindung","die Anbindung an die Innenstadt"],
"vi-stadt-u-003": ["der Ausbau der Radwege","den Ausbau beschleunigen"],
"vi-stadt-u-004": ["die Sanierung des Hauses","eine Sanierung planen"],
"vi-stadt-u-005": ["eine Baugenehmigung beantragen","ohne Baugenehmigung bauen"],
"vi-stadt-u-009": ["die Lebensqualität verbessern","eine hohe Lebensqualität"],
"vi-stadt-u-010": ["eine Grünfläche anlegen","die Grünfläche erhalten"],
"vi-stadt-u-011": ["unter Verkehrslärm leiden","den Verkehrslärm reduzieren"],
"vi-stadt-u-012": ["die Feinstaubbelastung messen","eine hohe Feinstaubbelastung"],
"vi-stadt-u-014": ["durch die Fußgängerzone gehen","die Fußgängerzone erweitern"],
"vi-stadt-u-015": ["eine Bürgerinitiative gründen","die Bürgerinitiative protestiert"],
"vi-stadt-u-017": ["den Abriss verhindern","der Abriss des Gebäudes"],
"vi-stadt-u-019": ["die Zuständigkeit klären","in die Zuständigkeit fallen"],
"vi-stadt-u-020": ["den Wasserverbrauch senken","der Wasserverbrauch steigt"],
"vi-stadt-u-023": ["im Kreislauf halten","der natürliche Kreislauf"],
"vi-geld-re-000": ["der Verbraucherschutz warnt","Regeln zum Verbraucherschutz"],
"vi-geld-re-001": ["das Widerrufsrecht nutzen","ein Widerrufsrecht von vierzehn Tagen"],
"vi-geld-re-004": ["Ersatz verlangen","als Ersatz bekommen"],
"vi-geld-re-010": ["eine Vereinbarung treffen","sich an die Vereinbarung halten"],
"vi-geld-re-011": ["eine verbindliche Zusage","verbindlich buchen"],
"vi-geld-re-012": ["ein unverbindliches Angebot","unverbindlich anfragen"],
"vi-geld-re-013": ["ein kostenpflichtiger Dienst","kostenpflichtig werden"],
"vi-geld-re-014": ["eine Stornierung ist möglich","die Stornierung kostet"],
"vi-geld-re-015": ["eine Rücklage bilden","auf die Rücklage zurückgreifen"],
"vi-geld-re-017": ["die Ersparnisse aufbrauchen","von den Ersparnissen leben"],
"vi-geld-re-018": ["eine Investition tätigen","die Investition lohnt sich"],
"vi-geld-re-019": ["sich beim Autokauf verschulden","sich für das Haus verschulden"],
"vi-geld-re-020": ["Zinsen zahlen","die Zinsen steigen"],
"vi-geld-re-021": ["die Gebührenordnung lesen","die Gebührenordnung regelt"],
"vi-geld-re-024": ["das Konto pfänden","den Lohn pfänden"],
"vi-funktio-001": ["die Wünsche berücksichtigen","bei der Planung berücksichtigen"],
"vj-bildung-000": ["die Berufsorientierung in der Schule","zur Berufsorientierung beitragen"],
"vj-bildung-001": ["einen Bildungsweg wählen","der zweite Bildungsweg"],
"vj-bildung-011": ["eine Fachrichtung wählen","die Fachrichtung wechseln"],
"vj-bildung-012": ["der Lehrplan sieht vor","den Lehrplan ändern"],
"vj-bildung-013": ["das eigene Lerntempo","das Lerntempo anpassen"],
"vj-bildung-014": ["Nachhilfeunterricht bekommen","Nachhilfeunterricht anbieten"],
"vj-bildung-015": ["die Schulpflicht gilt","gegen die Schulpflicht verstoßen"],
"vj-bildung-016": ["einen Schulabbruch verhindern","der Schulabbruch hat Folgen"],
"vj-migrati-001": ["einen Aufenthaltstitel beantragen","der Aufenthaltstitel läuft ab"],
"vj-migrati-007": ["die Teilnahmepflicht gilt","der Teilnahmepflicht nachkommen"],
"vj-migrati-008": ["sich in der Stadt zurechtfinden","sich schnell zurechtfinden"],
"vj-migrati-010": ["Mehrsprachigkeit fördern","Mehrsprachigkeit als Vorteil"],
"vj-migrati-013": ["einen Neuanfang wagen","der Neuanfang fällt schwer"],
"vj-migrati-015": ["die Wurzeln nicht vergessen","zu den Wurzeln zurückkehren"],
"vj-migrati-016": ["die Anpassung fällt schwer","Anpassung verlangen"],
"vj-migrati-017": ["die Erziehung der Kinder","eine strenge Erziehung"],
"vj-migrati-018": ["Kinder erziehen","zur Selbstständigkeit erziehen"],
"vj-migrati-023": ["die Aufgabenteilung im Haushalt","eine faire Aufgabenteilung"],
"vj-migrati-026": ["Taschengeld bekommen","das Taschengeld erhöhen"],
"vj-migrati-027": ["in der Pubertät sein","in die Pubertät kommen"],
"vj-migrati-030": ["das Familienleben genießen","das Familienleben organisieren"],
"vj-migrati-033": ["als Alleinerziehende arbeiten","Hilfe für Alleinerziehende"],
"vk-b1x-000": ["eine Dienstleistung anbieten","die Dienstleistung bezahlen"],
"vk-b1x-001": ["einen Auftrag erteilen","den Auftrag annehmen"],
"vk-b1x-002": ["den Kundendienst anrufen","der Kundendienst hilft"],
"vk-b1x-004": ["die Bearbeitung dauert","in Bearbeitung sein"],
"vk-b1x-005": ["den Ablauf erklären","ein reibungsloser Ablauf"],
"vk-b1x-007": ["die Vertretung übernehmen","eine Vertretung organisieren"],
"vk-b1x-008": ["die Abwesenheit melden","während der Abwesenheit"],
"vk-b1x-009": ["auf Dienstreise sein","eine Dienstreise planen"],
"vk-b1x-010": ["Spesen abrechnen","die Spesen erstatten"],
"vk-b1x-011": ["die Kosten erstatten","den Betrag erstatten"],
"vk-b1x-016": ["den Gipfel erreichen","auf den Gipfel steigen"],
"vk-b1x-017": ["ins Tal wandern","im Tal liegen"],
"vk-b1x-018": ["an der Küste leben","an die Küste fahren"],
"vk-b1x-019": ["auf einer Insel wohnen","die Insel besuchen"],
"vk-b1x-020": ["mit der Fähre fahren","die Fähre legt ab"],
"vk-b1x-021": ["die Ausrüstung packen","eine gute Ausrüstung"],
"vk-b1x-022": ["einen Anfängerkurs besuchen","den Anfängerkurs abschließen"],
"vk-b1x-023": ["die Mitgliedschaft kündigen","eine Mitgliedschaft beantragen"],
"vk-b1x-027": ["sich vor dem Sport aufwärmen","sich zehn Minuten aufwärmen"],
"vk-b1x-038": ["einen Anteil haben an","der Anteil steigt"],
}
