# -*- coding: utf-8 -*-
"""Kollokationen Batch 4 (B2 Fachwortschatz, Teil 2 — Rest B2): je 2 Verbindungen."""
AUSNAHMEN = {
"v1268": "Partizip-Wendung (gentechnisch verändert) — ist selbst die feste Verbindung",
"v1314": "Partizip-Wendung (dicht bebaut) — ist selbst die feste Verbindung",
"v1399": "Adjektiv nur attributiv in Fachtexten (erinnerungspolitisch) — keine feste Verbindung außerhalb",
}
K = {
"v1137": ["der Sozialstaat fängt auf","den Sozialstaat finanzieren"],
"v1138": ["Umverteilung über Steuern","die Umverteilung von oben nach unten"],
"v1139": ["den Solidaritätszuschlag zahlen","den Solidaritätszuschlag abschaffen"],
"v1140": ["Grundsicherung beziehen","Anspruch auf Grundsicherung"],
"v1141": ["Bürgergeld beantragen","Bürgergeld beziehen"],
"v1143": ["den Regelsatz anpassen","der Regelsatz für Alleinstehende"],
"v1144": ["zur Bedarfsgemeinschaft zählen","eine Bedarfsgemeinschaft bilden"],
"v1145": ["eine Riester-Rente abschließen","die Riester-Rente lohnt sich"],
"v1146": ["Altersarmut bekämpfen","von Altersarmut bedroht"],
"v1147": ["die Mütterrente anrechnen","Anspruch auf Mütterrente"],
"v1148": ["Erwerbsminderungsrente beantragen","die Erwerbsminderungsrente erhalten"],
"v1149": ["Wohngeld beantragen","Anspruch auf Wohngeld"],
"v1150": ["die Armutsgefährdungsquote steigt","die Armutsgefährdungsquote berechnen"],
"v1151": ["Teilhabe ermöglichen","gesellschaftliche Teilhabe"],
"v1153": ["als Ehrenamtlicher helfen","Ehrenamtliche gewinnen"],
"v1154": ["einen Freiwilligendienst leisten","ein Jahr Freiwilligendienst"],
"v1155": ["eine Aufwandsentschädigung zahlen","eine Aufwandsentschädigung erhalten"],
"v1156": ["die Übungsleiterpauschale nutzen","die Übungsleiterpauschale ist steuerfrei"],
"v1157": ["den Freibetrag ausschöpfen","unter dem Freibetrag bleiben"],
"v1158": ["eine Spendenquittung ausstellen","eine Spendenquittung verlangen"],
"v1159": ["eine Sachspende abgeben","Sachspenden sammeln"],
"v1161": ["die Gemeinnützigkeit anerkennen","die Gemeinnützigkeit verlieren"],
"v1162": ["der Wohlfahrtsverband betreibt","Mitglied im Wohlfahrtsverband"],
"v1163": ["die Ehrenamtsagentur vermittelt","sich bei der Ehrenamtsagentur melden"],
"v1164": ["eine Einsatzstelle finden","die Einsatzstelle wechseln"],
"v1165": ["die Solidargemeinschaft trägt","Teil der Solidargemeinschaft"],
"v1166": ["Pflegezeit nehmen","Anspruch auf Pflegezeit"],
"v1167": ["Kindergeld beantragen","Kindergeld beziehen"],
"v1168": ["den Kinderzuschlag beantragen","Anspruch auf Kinderzuschlag"],
"v1169": ["Mitbestimmung ausüben","das Recht auf Mitbestimmung"],
"v1170": ["die Versicherungspflicht gilt","der Versicherungspflicht unterliegen"],
"v1171": ["die Beitragsbemessungsgrenze überschreiten","oberhalb der Beitragsbemessungsgrenze"],
"v1173": ["die Fürsorgepflicht verletzen","der Fürsorgepflicht nachkommen"],
"v1174": ["eine Sozialleistung beantragen","Sozialleistungen kürzen"],
"v1177": ["vom Angebot ausgeschlossen","ausgeschlossen werden"],
"v1178": ["eine Laufzeitverlängerung beschließen","gegen die Laufzeitverlängerung protestieren"],
"v1179": ["ein Endlager suchen","das Endlager muss sicher sein"],
"v1180": ["Atommüll lagern","Atommüll entsorgen"],
"v1181": ["einen Bürgerwindpark gründen","sich am Bürgerwindpark beteiligen"],
"v1182": ["den Mindestabstand einhalten","der Mindestabstand beträgt"],
"v1183": ["der Schattenwurf stört","den Schattenwurf berechnen"],
"v1184": ["Infraschall messen","Infraschall wahrnehmen"],
"v1185": ["das Netzentgelt zahlen","das Netzentgelt steigt"],
"v1186": ["den Netzausbau beschleunigen","der Netzausbau stockt"],
"v1187": ["eine Stromtrasse bauen","gegen die Stromtrasse klagen"],
"v1188": ["eine Gleichstromleitung verlegen","die Gleichstromleitung verliert weniger"],
"v1189": ["der Grundversorger springt ein","zum Grundversorger wechseln"],
"v1190": ["einen Anbieterwechsel durchführen","der Anbieterwechsel dauert"],
"v1191": ["die Stromkennzeichnung lesen","die Stromkennzeichnung zeigt"],
"v1192": ["Ökostrom beziehen","auf Ökostrom umsteigen"],
"v1193": ["das Erneuerbare-Energien-Gesetz ändern","das Erneuerbare-Energien-Gesetz garantiert"],
"v1194": ["eine Einspeisevergütung erhalten","die Einspeisevergütung sinkt"],
"v1195": ["den Eigenverbrauch erhöhen","Eigenverbrauch lohnt sich"],
"v1196": ["einen Stromspeicher installieren","der Stromspeicher im Keller"],
"v1197": ["ein Pumpspeicherkraftwerk betreiben","das Pumpspeicherkraftwerk speichert"],
"v1198": ["Sektorenkopplung umsetzen","das Prinzip der Sektorenkopplung"],
"v1199": ["die Wärmewende gelingt","die Wärmewende finanzieren"],
"v1200": ["an die Fernwärme anschließen","mit Fernwärme heizen"],
"v1201": ["eine Umlage erheben","die Umlage verteilen"],
"v1202": ["der CO2-Preis steigt","den CO2-Preis erhöhen"],
"v1203": ["am Emissionshandel teilnehmen","der Emissionshandel funktioniert"],
"v1204": ["die Wasserstoffstrategie umsetzen","auf die Wasserstoffstrategie setzen"],
"v1205": ["Wasserstoff durch Elektrolyse gewinnen","die Elektrolyse braucht Strom"],
"v1206": ["den Braunkohletagebau schließen","Dörfer für den Braunkohletagebau umsiedeln"],
"v1209": ["die Akzeptanz steigt","Akzeptanz schaffen"],
"v1210": ["einen Blackout verhindern","beim Blackout ausfallen"],
"v1211": ["die Netzreserve aktivieren","Kraftwerke in der Netzreserve"],
"v1212": ["den Flächenverbrauch senken","der Flächenverbrauch wächst"],
"v1213": ["Strom ins Netz einspeisen","Solarstrom einspeisen"],
"v1215": ["das Kraftwerk hochfahren","langsam hochfahren"],
"v1216": ["Windräder abregeln","bei Überschuss abregeln"],
"v1217": ["energieintensive Industrie","energieintensiv produzieren"],
"v1218": ["volatile Erzeugung","volatil bleiben"],
"v1219": ["grundlastfähige Kraftwerke","als grundlastfähig gelten"],
"v1220": ["das Netz netzstabil halten","netzstabil bleiben"],
"v1221": ["Stromknappheit droht","vor Stromknappheit warnen"],
"v1222": ["Energiesouveränität erreichen","nach Energiesouveränität streben"],
"v1223": ["den Gasspeicher füllen","den Gasspeicher leeren"],
"v1224": ["fossile Subventionen abbauen","die fossile Subvention verzögert"],
"v1225": ["das Mindesthaltbarkeitsdatum überschreiten","das Mindesthaltbarkeitsdatum prüfen"],
"v1226": ["Lebensmittelverschwendung vermeiden","die Lebensmittelverschwendung reduzieren"],
"v1227": ["sich in der Lebensmittelrettung engagieren","Lebensmittelrettung organisieren"],
"v1228": ["die Nährwerttabelle lesen","die Nährwerttabelle auf der Packung"],
"v1229": ["den Nutri-Score angeben","der Nutri-Score zeigt"],
"v1230": ["einen Geschmacksverstärker zusetzen","auf Geschmacksverstärker verzichten"],
"v1231": ["einen Zusatzstoff zulassen","Zusatzstoffe kennzeichnen"],
"v1232": ["eine E-Nummer entschlüsseln","hinter der E-Nummer steckt"],
"v1233": ["Süßstoff verwenden","mit Süßstoff süßen"],
"v1234": ["Palmöl enthalten","auf Palmöl verzichten"],
"v1235": ["eine Tierwohlabgabe einführen","die Tierwohlabgabe verteuert Fleisch"],
"v1237": ["Käfighaltung verbieten","Eier aus Käfighaltung"],
"v1239": ["das Biosiegel tragen","auf das Biosiegel achten"],
"v1240": ["die Herkunftsangabe fehlt","eine klare Herkunftsangabe"],
"v1241": ["die Siegelflut verwirrt","sich in der Siegelflut zurechtfinden"],
"v1242": ["Irreführung der Verbraucher","wegen Irreführung abmahnen"],
"v1243": ["eine Abmahnung erhalten","eine Abmahnung aussprechen"],
"v1244": ["aus Kulanz zurücknehmen","Kulanz zeigen"],
"v1246": ["das Kleingedruckte lesen","im Kleingedruckten stehen"],
"v1247": ["in die Abo-Falle tappen","vor der Abo-Falle warnen"],
"v1248": ["als Lockvogel dienen","mit einem Lockvogel werben"],
"v1249": ["Preistreiberei betreiben","gegen Preistreiberei vorgehen"],
"v1250": ["das Bundeskartellamt prüft","beim Bundeskartellamt anmelden"],
"v1251": ["die Lebensmittelinflation trifft Familien","die Lebensmittelinflation bremsen"],
"v1252": ["der Kennzeichnungspflicht unterliegen","die Kennzeichnungspflicht gilt"],
"v1253": ["eine Rückrufaktion starten","von der Rückrufaktion betroffen"],
"v1254": ["einen Rückruf veranlassen","der Rückruf betrifft"],
"v1255": ["eine Musterfeststellungsklage einreichen","sich der Musterfeststellungsklage anschließen"],
"v1256": ["einen Testkauf durchführen","beim Testkauf auffallen"],
"v1258": ["die Haltbarkeit verlängern","die Haltbarkeit prüfen"],
"v1259": ["die Eigenmarke des Supermarkts","zur Eigenmarke greifen"],
"v1260": ["die Portionsgröße angeben","die Portionsgröße anpassen"],
"v1261": ["den Zuckergehalt senken","ein hoher Zuckergehalt"],
"v1262": ["der Verlockung widerstehen","eine große Verlockung"],
"v1263": ["eine Mogelpackung erkennen","als Mogelpackung entlarven"],
"v1265": ["eine Firma abmahnen","wegen falscher Werbung abmahnen"],
"v1266": ["ein Produkt zurückrufen","eine Charge zurückrufen"],
"v1267": ["verderbliche Ware","leicht verderblich"],
"v1269": ["nährstoffreiche Lebensmittel","nährstoffreich essen"],
"v1270": ["geschönte Zahlen","ein geschöntes Bild"],
"v1271": ["verbraucherfeindliche Klauseln","als verbraucherfeindlich einstufen"],
"v1411": ["Gift enthalten","tödliches Gift"],
"v1272": ["die Stadtplanung verbessern","in der Stadtplanung arbeiten"],
"v1273": ["einen Bebauungsplan aufstellen","der Bebauungsplan erlaubt"],
"v1274": ["den Flächennutzungsplan ändern","im Flächennutzungsplan eintragen"],
"v1275": ["die Gentrifizierung stoppen","von Gentrifizierung betroffen"],
"v1276": ["die Aufwertung des Viertels","eine Aufwertung erfahren"],
"v1277": ["eine Milieuschutzsatzung erlassen","die Milieuschutzsatzung gilt"],
"v1278": ["die Zweckentfremdung verbieten","eine Zweckentfremdung genehmigen"],
"v1279": ["den Mietspiegel heranziehen","laut Mietspiegel üblich"],
"v1280": ["die Kappungsgrenze einhalten","die Kappungsgrenze liegt bei"],
"v1281": ["Wohnraumförderung beantragen","Mittel der Wohnraumförderung"],
"v1282": ["Geschosswohnungsbau fördern","der Geschosswohnungsbau spart Fläche"],
"v1283": ["Nachverdichtung planen","gegen die Nachverdichtung protestieren"],
"v1284": ["die Skyline prägen","die Skyline der Stadt"],
"v1285": ["unter Denkmalschutz stehen","der Denkmalschutz verbietet"],
"v1286": ["einen Bürgerentscheid durchführen","beim Bürgerentscheid abstimmen"],
"v1287": ["die Planfeststellung abschließen","das Verfahren der Planfeststellung"],
"v1288": ["Bürgerbeteiligung ermöglichen","echte Bürgerbeteiligung"],
"v1289": ["die Versiegelung des Bodens","Versiegelung vermeiden"],
"v1290": ["eine Frischluftschneise freihalten","die Frischluftschneise bebauen"],
"v1291": ["einen Hitzeaktionsplan erstellen","der Hitzeaktionsplan sieht vor"],
"v1292": ["Stadtbegrünung fördern","in Stadtbegrünung investieren"],
"v1293": ["das Konzept der Schwammstadt","zur Schwammstadt umbauen"],
"v1295": ["die Abwanderung stoppen","Abwanderung junger Leute"],
"v1296": ["in einer Kleinstadt leben","die Kleinstadt beleben"],
"v1297": ["das Stadt-Land-Gefälle verringern","das Stadt-Land-Gefälle wächst"],
"v1298": ["Verkehrsberuhigung einführen","Maßnahmen zur Verkehrsberuhigung"],
"v1299": ["Parkraumbewirtschaftung einführen","die Parkraumbewirtschaftung ausweiten"],
"v1300": ["eine autofreie Zone einrichten","in der autofreien Zone liefern"],
"v1301": ["das Quartiersmanagement organisiert","beim Quartiersmanagement melden"],
"v1302": ["den Leerstand bekämpfen","Leerstand im Zentrum"],
"v1303": ["eine Hausbesetzung beenden","die Hausbesetzung dauert"],
"v1304": ["das Vorkaufsrecht ausüben","das Vorkaufsrecht nutzen"],
"v1305": ["die Verdrängung der Mieter","Verdrängung verhindern"],
"v1306": ["die Mietpreisbremse gilt","die Mietpreisbremse verlängern"],
"v1307": ["die Modernisierungsumlage begrenzen","über die Modernisierungsumlage zahlen"],
"v1309": ["die Belegungsbindung endet","eine Belegungsbindung vereinbaren"],
"v1310": ["das Viertel verdichten","behutsam verdichten"],
"v1311": ["das Haus sanieren","energetisch sanieren"],
"v1313": ["ein Viertel aufwerten","den Platz aufwerten"],
"v1315": ["flächensparend bauen","eine flächensparende Bauweise"],
"v1316": ["in die Neubausiedlung ziehen","die Neubausiedlung am Stadtrand"],
"v1317": ["das Fachkräfteeinwanderungsgesetz erleichtert","das Fachkräfteeinwanderungsgesetz anwenden"],
"v1318": ["die Blaue Karte beantragen","mit der Blauen Karte arbeiten"],
"v1319": ["ein Punktesystem einführen","im Punktesystem zählen"],
"v1320": ["die Gleichwertigkeitsprüfung bestehen","die Gleichwertigkeitsprüfung dauert"],
"v1321": ["eine Nachqualifizierung absolvieren","die Nachqualifizierung dauert"],
"v1322": ["einen Integrationskurs besuchen","der Integrationskurs umfasst"],
"v1323": ["den Wertekurs besuchen","im Wertekurs lernen"],
"v1324": ["die Optionspflicht abschaffen","unter die Optionspflicht fallen"],
"v1325": ["eine Duldung erhalten","mit einer Duldung leben"],
"v1326": ["die Niederlassungserlaubnis beantragen","die Niederlassungserlaubnis erhalten"],
"v1327": ["den Familiennachzug beantragen","der Familiennachzug setzt voraus"],
"v1329": ["Fluchtursachen bekämpfen","die häufigste Fluchtursache"],
"v1330": ["in der Asylunterkunft wohnen","eine Asylunterkunft einrichten"],
"v1331": ["die dezentrale Unterbringung bevorzugen","die dezentrale Unterbringung erleichtert"],
"v1332": ["der Residenzpflicht unterliegen","die Residenzpflicht aufheben"],
"v1333": ["eine Arbeitserlaubnis beantragen","ohne Arbeitserlaubnis arbeiten"],
"v1334": ["den Zweitspracherwerb fördern","der Zweitspracherwerb gelingt"],
"v1335": ["Sprachmittlung anbieten","auf Sprachmittlung angewiesen"],
"v1336": ["die Sensibilisierung der Lehrkräfte","zur Sensibilisierung beitragen"],
"v1337": ["Willkommenskultur leben","eine echte Willkommenskultur"],
"v1338": ["über die Leitkultur streiten","der Begriff Leitkultur"],
"v1339": ["von Parallelgesellschaft sprechen","eine Parallelgesellschaft entsteht"],
"v1340": ["eine Quotelung einführen","die Quotelung verhindert"],
"v1341": ["der Migrationsbeirat berät","im Migrationsbeirat sitzen"],
"v1342": ["das Herkunftsland angeben","ins Herkunftsland zurückkehren"],
"v1343": ["eine Migrationsgeschichte haben","die eigene Migrationsgeschichte erzählen"],
"v1344": ["eine gute Bleibeperspektive","die Bleibeperspektive prüfen"],
"v1345": ["eine Ausbildungsduldung erhalten","die Ausbildungsduldung schützt"],
"v1346": ["die Vorrangprüfung abschaffen","der Vorrangprüfung unterliegen"],
"v1347": ["an der Einbürgerungsfeier teilnehmen","bei der Einbürgerungsfeier sprechen"],
"v1348": ["Assimilation verlangen","Assimilation statt Integration"],
"v1349": ["die Mehrheitsgesellschaft merkt","Teil der Mehrheitsgesellschaft"],
"v1350": ["die Zuwanderungsstatistik zählt","die Zuwanderungsstatistik veröffentlichen"],
"v1352": ["sich ins Team einfügen","sich schnell einfügen"],
"v1353": ["Neuankömmlinge integrieren","in den Arbeitsmarkt integrieren"],
"v1354": ["zugewanderte Fachkräfte","vor Jahren zugewandert"],
"v1355": ["heimatlos werden","sich heimatlos fühlen"],
"v1356": ["eine Bildungskarriere beginnen","die Bildungskarriere fördern"],
"v1357": ["Zweitsprachigkeit nutzen","die Zweitsprachigkeit der Kinder"],
"v1358": ["eine Begegnungszone schaffen","die Begegnungszone im Viertel"],
"v1359": ["die Erinnerungskultur pflegen","eine lebendige Erinnerungskultur"],
"v1360": ["das Gedenken an die Opfer","zum Gedenken versammeln"],
"v1361": ["am Volkstrauertag schweigen","der Volkstrauertag im November"],
"v1362": ["einen Stolperstein verlegen","der Stolperstein vor dem Haus"],
"v1363": ["ein Mahnmal errichten","das Mahnmal erinnert"],
"v1364": ["eine Gedenkstätte besuchen","die Gedenkstätte bietet Führungen"],
"v1365": ["Wiedergutmachung leisten","Anspruch auf Wiedergutmachung"],
"v1366": ["Reparationen zahlen","Reparationen fordern"],
"v1367": ["die Entnazifizierung durchführen","das Verfahren der Entnazifizierung"],
"v1368": ["als Mitläufer gelten","als Mitläufer eingestuft"],
"v1369": ["die Täterschaft nachweisen","die Frage der Täterschaft"],
"v1370": ["die Schuldfrage stellen","die Schuldfrage klären"],
"v1371": ["das Konzept der Kollektivschuld","Kollektivschuld ablehnen"],
"v1372": ["einen Zeitzeugen befragen","der Zeitzeuge berichtet"],
"v1373": ["ein Zeitzeugeninterview führen","das Zeitzeugeninterview aufzeichnen"],
"v1374": ["eine Gedenkminute einlegen","nach der Gedenkminute sprechen"],
"v1375": ["die Verharmlosung der Verbrechen","Verharmlosung beginnt bei der Wortwahl"],
"v1376": ["die Relativierung zurückweisen","eine Relativierung vornehmen"],
"v1377": ["einen Schlussstrich ziehen","den Schlussstrich fordern"],
"v1378": ["Erinnerungsarbeit leisten","Erinnerungsarbeit an Schulen"],
"v1379": ["ein Gedenkritual abhalten","das Gedenkritual wirkt fern"],
"v1380": ["die Friedliche Revolution begann","an die Friedliche Revolution erinnern"],
"v1381": ["an der Montagsdemonstration teilnehmen","die Montagsdemonstration wächst"],
"v1382": ["die Stasi-Unterlagen einsehen","Akten der Stasi-Unterlagen"],
"v1383": ["Vergangenheitsbewältigung leisten","der Prozess der Vergangenheitsbewältigung"],
"v1384": ["Geschichtspolitik betreiben","die Geschichtspolitik entscheidet"],
"v1385": ["die Restitution fordern","die Restitution des Gemäldes"],
"v1386": ["Raubkunst zurückgeben","Raubkunst identifizieren"],
"v1387": ["Provenienzforschung betreiben","die Provenienzforschung prüft"],
"v1388": ["die Umbenennung beschließen","die Umbenennung der Straße"],
"v1389": ["eine Namensdebatte führen","die Namensdebatte dauert"],
"v1390": ["die Kolonialgeschichte aufarbeiten","Kolonialgeschichte im Unterricht"],
"v1391": ["die Opferperspektive einnehmen","die Opferperspektive fehlt"],
"v1392": ["Täterforschung betreiben","die Täterforschung fragt"],
"v1393": ["als Vertriebener ankommen","die Vertriebenen aufnehmen"],
"v1394": ["die Nachwirkungsdebatte zeigt","eine Nachwirkungsdebatte führen"],
"v1395": ["der Opfer gedenken","gemeinsam gedenken"],
"v1397": ["die Geschichte aufarbeiten","die Vergangenheit aufarbeiten"],
"v1398": ["Verbrechen relativieren","eine Aussage relativieren"],
}
