# -*- coding: utf-8 -*-
"""Kollokationen Batch 5 (B1 Kernwortschatz, Teil 1): je 2 Verbindungen mit B1-Wortschatz."""
K = {
"v097": ["in der Gesellschaft leben","die Gesellschaft verändert sich"],
"v098": ["eine Diskussion führen","an der Diskussion teilnehmen"],
"v099": ["eine Meinung begründen","die Entscheidung begründen"],
"v100": ["ein großer Vorteil","Vorteile haben"],
"v101": ["ein Nachteil sein","Nachteile haben"],
"v102": ["Verantwortung tragen","die Verantwortung abgeben"],
"v103": ["eine Ausbildung machen","die Ausbildung abschließen"],
"v104": ["eine Bewerbung schreiben","die Bewerbung abschicken"],
"v105": ["eine Stelle suchen","die Stelle ist frei"],
"v106": ["den Lebenslauf schreiben","ein tabellarischer Lebenslauf"],
"v107": ["der Arbeitgeber zahlt","mit dem Arbeitgeber sprechen"],
"v108": ["die Umweltverschmutzung nimmt zu","gegen Umweltverschmutzung kämpfen"],
"v109": ["eine Maßnahme ergreifen","Maßnahmen planen"],
"v110": ["den Klimawandel stoppen","die Folgen des Klimawandels"],
"v111": ["die Regierung entscheidet","eine neue Regierung wählen"],
"v112": ["die Wirtschaft wächst","die Wirtschaft stärken"],
"v113": ["die Krankenkasse zahlt","bei der Krankenkasse anrufen"],
"v114": ["eine Behandlung beginnen","die Behandlung dauert"],
"v115": ["jemanden überzeugen","mit Argumenten überzeugen"],
"v116": ["eine Lösung suchen","die beste Lösung"],
"v117": ["einen Rat geben","um Rat fragen"],
"v118": ["eine neue Regelung","die Regelung gilt ab"],
"v119": ["junge Leute ausbilden","zum Techniker ausbilden"],
"v120": ["eine These aufstellen","die These vertreten"],
"v169": ["einen Vertrag unterschreiben","den Vertrag verlängern"],
"v170": ["an die Hochschule gehen","an der Hochschule studieren"],
"v171": ["ein überzeugendes Argument","überzeugend sprechen"],
"v172": ["vor Publikum auftreten","ruhig auftreten"],
"v173": ["eine Bilanz ziehen","eine positive Bilanz"],
"v174": ["das Prüfungsergebnis abwarten","das Prüfungsergebnis kommt per Post"],
"v1406": ["die Polizei rufen","bei der Polizei anzeigen"],
"v1407": ["eine Geschichte erzählen","die Geschichte der Stadt"],
"v131": ["Konsequenzen haben","die Konsequenzen tragen"],
"v181": ["eine Beziehung haben","eine feste Beziehung"],
"v182": ["Kontakt haben zu","den Kontakt verlieren"],
"v183": ["eine Freundschaft schließen","eine lange Freundschaft"],
"v184": ["einen Partner suchen","mit dem Partner sprechen"],
"v188": ["sich mit dem Nachbarn streiten","sich um Geld streiten"],
"v190": ["Vertrauen haben","das Vertrauen verlieren"],
"v192": ["ehrlich sein","eine ehrliche Antwort"],
"v193": ["sich vom Partner trennen","sich nach fünf Jahren trennen"],
"v196": ["verliebt sein","frisch verliebt"],
"v197": ["ein Date haben","zum Date gehen"],
"v198": ["sich zum Essen verabreden","sich für Samstag verabreden"],
"v199": ["eine Verabredung haben","die Verabredung absagen"],
"v201": ["per E-Mail kommunizieren","offen kommunizieren"],
"v203": ["Distanz halten","auf Distanz gehen"],
"v204": ["sich um die Kinder kümmern","sich um den Vater kümmern"],
"v206": ["einen Konflikt lösen","ein Konflikt entsteht"],
"v207": ["ein Gespräch führen","ins Gespräch kommen"],
"v208": ["sich über den Film unterhalten","sich lange unterhalten"],
"v211": ["ein Geheimnis haben","das Geheimnis verraten"],
"v214": ["sich auf den Urlaub freuen","sich auf das Wochenende freuen"],
"v218": ["eine Gewohnheit haben","eine Gewohnheit ändern"],
"v219": ["einen Kompromiss finden","einen Kompromiss schließen"],
"v223": ["auf die Gesundheit achten","die Gesundheit geht vor"],
"v224": ["krank werden","krank im Bett liegen"],
"v225": ["eine Krankheit haben","eine ansteckende Krankheit"],
"v227": ["zur Ärztin gehen","die Ärztin untersucht"],
"v228": ["in die Praxis gehen","die Praxis öffnet um acht"],
"v229": ["ins Krankenhaus kommen","im Krankenhaus liegen"],
"v230": ["in die Apotheke gehen","in der Apotheke kaufen"],
"v231": ["ein Rezept bekommen","das Rezept einlösen"],
"v232": ["eine Tablette nehmen","Tabletten gegen Kopfschmerzen"],
"v233": ["starke Schmerzen haben","der Schmerz lässt nach"],
"v234": ["Fieber haben","das Fieber senken"],
"v235": ["sich wohl fühlen","sich müde fühlen"],
"v239": ["einen Patienten behandeln","mit Tabletten behandeln"],
"v242": ["eine Operation haben","die Operation dauert"],
"v246": ["sich beim Chef krankmelden","sich telefonisch krankmelden"],
"v248": ["eine Versicherung haben","die Versicherung zahlt"],
"v251": ["Stress haben","unter Stress stehen"],
"v252": ["gestresst sein","völlig gestresst"],
"v260": ["die Arbeitszeit verkürzen","flexible Arbeitszeit"],
"v261": ["eine Pause machen","die Mittagspause dauert"],
"v265": ["sich mit Sport fit halten","sich im Alter fit halten"],
"v266": ["sich gesund ernähren","sich vegetarisch ernähren"],
"v267": ["Bewegung an der frischen Luft","mehr Bewegung brauchen"],
"v273": ["in Armut leben","Armut bekämpfen"],
"v279": ["die Integration fördern","der Schlüssel zur Integration"],
"v283": ["ein Vorurteil haben","Vorurteile abbauen"],
"v284": ["tolerant sein","tolerante Nachbarn"],
"v285": ["eine Entscheidung akzeptieren","die Regeln akzeptieren"],
"v286": ["ein Ehrenamt übernehmen","ein Ehrenamt im Verein"],
"v288": ["in einen Verein eintreten","Mitglied im Verein"],
"v291": ["gegen das Gesetz demonstrieren","friedlich demonstrieren"],
"v295": ["die Wahl gewinnen","zur Wahl gehen"],
"v296": ["eine Partei wählen","wählen gehen"],
"v297": ["jeder Wähler bekommt","die Wähler entscheiden"],
"v298": ["ins Parlament einziehen","das Parlament diskutiert"],
"v300": ["in einer Demokratie leben","die Demokratie stärken"],
"v303": ["eine Pflicht haben","seine Pflicht erfüllen"],
"v304": ["freiwillig helfen","freiwillig teilnehmen"],
"v306": ["Essen wegwerfen","alte Sachen wegwerfen"],
"v311": ["ein starkes Argument","ein Argument nennen"],
"v312": ["eine positive Entwicklung","die Entwicklung der Preise"],
"v316": ["ein schneller Wandel","der Wandel der Arbeitswelt"],
"v317": ["Einfluss haben auf","großen Einfluss haben"],
"v321": ["die Miete zahlen","die Miete steigt"],
"v327": ["ein netter Nachbar","der neue Nachbar"],
"v331": ["aus der Wohnung ausziehen","im März ausziehen"],
"v332": ["in die neue Wohnung einziehen","am Ersten einziehen"],
"v333": ["eine ruhige Gegend","in der Gegend wohnen"],
"v336": ["in einem Dorf wohnen","ein kleines Dorf"],
"v342": ["einen Kredit aufnehmen","den Kredit zurückzahlen"],
"v356": ["in einer WG wohnen","eine WG gründen"],
"v359": ["auf dem Balkon sitzen","eine Wohnung mit Balkon"],
"v368": ["Ruhe brauchen","in Ruhe lassen"],
"v372": ["mit Freunden chatten","jeden Abend chatten"],
"v373": ["eine App herunterladen","mit der App lernen"],
"v374": ["das Gerät ausschalten","ein neues Gerät"],
"v375": ["vor dem Bildschirm sitzen","auf den Bildschirm schauen"],
"v377": ["eine Suchmaschine benutzen","in die Suchmaschine eingeben"],
"v378": ["eine Serie streamen","Musik streamen"],
"v381": ["sich online anmelden","sich für den Kurs anmelden"],
"v382": ["die Anmeldung ist Pflicht","zur Anmeldung gehen"],
"v383": ["die Datei speichern","den Text speichern"],
"v388": ["ein Roboter arbeitet","einen Roboter bauen"],
"v392": ["in den sozialen Medien posten","die sozialen Medien nutzen"],
"v393": ["ein Netzwerk aufbauen","ein gutes Netzwerk haben"],
"v394": ["Werbung machen","Werbung im Fernsehen"],
"v396": ["die Lieferung kommt","auf die Lieferung warten"],
"v403": ["das Handy aufladen","über Nacht aufladen"],
"v405": ["jeder Nutzer braucht","die Nutzer der App"],
"v411": ["digital einreichen","die digitale Welt"],
"v412": ["auf der Tastatur tippen","die deutsche Tastatur"],
"v416": ["eine Studie zeigt","eine Studie durchführen"],
"v417": ["den Patienten untersuchen","ein Problem untersuchen"],
"v418": ["eine Untersuchung machen","die Untersuchung zeigt"],
"v419": ["ein gutes Ergebnis","das Ergebnis der Prüfung"],
"v420": ["ein Experiment machen","das Experiment wiederholen"],
"v421": ["die Theorie prüfen","eine Theorie entwickeln"],
"v424": ["ein bekannter Forscher","der Forscher arbeitet an"],
"v426": ["eine Methode anwenden","die beste Methode"],
"v428": ["die Statistik zeigt","eine Statistik lesen"],
"v434": ["ein Zitat aus einem Buch","das Zitat stammt von"],
"v438": ["etwas beweisen können","das Gegenteil beweisen"],
"v439": ["einen Beweis haben","der Beweis fehlt"],
"v440": ["ein Studium beginnen","das Studium wechseln"],
"v441": ["an der Universität studieren","zur Universität gehen"],
"v442": ["ein Seminar besuchen","im Seminar diskutieren"],
"v444": ["die Frist läuft ab","die Frist verlängern"],
"v448": ["Kinder fördern","Sprachkurse fördern"],
"v457": ["das Aussehen ändern","auf das Aussehen achten"],
"v458": ["ein schöner Tag","schön aussehen"],
"v460": ["ein hässliches Gebäude","hässlich finden"],
"v463": ["die Schönheit der Landschaft","Schönheit ist Geschmackssache"],
"v464": ["die Haut pflegen","den Garten pflegen"],
"v465": ["die Pflege der Eltern","Pflege brauchen"],
"v466": ["eine Creme auftragen","eine Creme gegen trockene Haut"],
"v467": ["sich morgens schminken","sich stark schminken"],
"v469": ["eine Falte im Gesicht","Falten bekommen"],
"v470": ["das Alter angeben","das hohe Alter"],
"v471": ["jugendlich aussehen","jugendlich wirken"],
"v473": ["in meiner Jugend","die Jugend von heute"],
"v474": ["die neue Mode","der Mode folgen"],
"v477": ["warme Kleidung","die Kleidung wechseln"],
"v478": ["sich warm anziehen","sich schnell anziehen"],
"v486": ["ein elegantes Kleid","elegant gekleidet"],
"v488": ["natürlich wirken","natürliche Zutaten"],
"v495": ["die Chefin beeindrucken","mit Leistung beeindrucken"],
"v502": ["moderne Kunst","Kunst studieren"],
"v503": ["ein bekannter Künstler","der Künstler malt"],
"v504": ["die Künstlerin stellt aus","eine junge Künstlerin"],
"v505": ["ins Museum gehen","das Museum besuchen"],
"v506": ["eine Ausstellung besuchen","die Ausstellung läuft bis"],
"v508": ["ein Bild malen","gern malen"],
"v509": ["ein Bild aufhängen","das Bild an der Wand"],
"v512": ["ins Theater gehen","Karten fürs Theater"],
"v514": ["ein Konzert besuchen","das Konzert beginnt"],
"v515": ["in die Oper gehen","eine Oper von Mozart"],
"v516": ["im Orchester spielen","das Orchester probt"],
"v517": ["ein Instrument spielen","ein Instrument lernen"],
"v518": ["Musik hören","laute Musik"],
"v519": ["einen Film sehen","der Film läuft im Kino"],
"v520": ["einen Film drehen","in Berlin drehen"],
"v525": ["eine Rolle spielen","die Hauptrolle übernehmen"],
"v529": ["Kritik üben","Kritik annehmen"],
"v530": ["den Plan kritisieren","scharf kritisieren"],
"v533": ["einen Roman lesen","der Roman spielt in"],
"v534": ["ein Gedicht schreiben","ein Gedicht auswendig lernen"],
"v536": ["deutsche Literatur","Literatur lesen"],
"v537": ["ein Buch lesen","ein spannendes Buch"],
"v540": ["das erste Kapitel","ein Kapitel lesen"],
"v541": ["eine spannende Handlung","die Handlung des Films"],
"v543": ["eine andere Kultur","die Kultur kennenlernen"],
"v544": ["auf ein Festival gehen","das Festival findet statt"],
"v545": ["eine alte Tradition","die Tradition pflegen"],
"v550": ["eine Weiterbildung machen","die Weiterbildung bezahlen"],
"v551": ["ein Praktikum machen","das Praktikum dauert"],
"v552": ["als Arbeitnehmer haben","die Rechte der Arbeitnehmer"],
"v553": ["ein gutes Gehalt","das Gehalt verhandeln"],
"v554": ["der Lohn steigt","einen fairen Lohn zahlen"],
"v562": ["in der Probezeit sein","die Probezeit dauert"],
"v563": ["in der Abteilung arbeiten","die Abteilung leiten"],
"v564": ["eine Besprechung haben","die Besprechung beginnt um elf"],
"v570": ["ein sicherer Arbeitsplatz","den Arbeitsplatz wechseln"],
"v572": ["kompetent wirken","eine kompetente Beratung"],
"v578": ["sich um eine Stelle bewerben","sich online bewerben"],
"v579": ["ein guter Verdienst","der Verdienst reicht"],
"v580": ["ein hohes Einkommen","das Einkommen versteuern"],
"v581": ["Steuern zahlen","die Steuer wird abgezogen"],
"v587": ["ein gutes Zeugnis","das Zeugnis bekommen"],
"v593": ["die Arbeitslosigkeit sinkt","hohe Arbeitslosigkeit"],
"v597": ["ein warmes Klima","das Klima schützen"],
"v600": ["ein verschmutzter Fluss","stark verschmutzt"],
"v608": ["den Verbrauch senken","der Verbrauch an Strom"],
"v610": ["sparsam sein","sparsam heizen"],
"v618": ["Kohle verbrennen","Strom aus Kohle"],
"v619": ["Erdöl fördern","der Preis für Erdöl"],
"v620": ["mit Erdgas heizen","Erdgas importieren"],
"v627": ["schädlich für die Gesundheit","schädliche Stoffe"],
"v632": ["die Umwelt schützen","vor der Sonne schützen"],
"v639": ["eine Überschwemmung im Keller","eine Überschwemmung droht"],
"v655": ["eine schöne Landschaft","die Landschaft genießen"],
"v657": ["gegen die Straße protestieren","gegen die Pläne protestieren"],
"v661": ["den Betrag überweisen","ein hoher Betrag"],
"v663": ["einen Rabatt bekommen","zehn Prozent Rabatt"],
"v669": ["bei der Sparkasse arbeiten","ein Konto bei der Sparkasse"],
"v671": ["Geld einzahlen","auf das Konto einzahlen"],
"v678": ["der Käufer zahlt","als Käufer Rechte haben"],
"v680": ["den Kunden beraten","ein zufriedener Kunde"],
"v687": ["ein wertvoller Hinweis","wertvolle Zeit"],
"v690": ["für ein Produkt werben","mit kostenloser Lieferung werben"],
"v694": ["das Budget planen","ein kleines Budget"],
"v705": ["die Ware zurückgeben","das Buch zurückgeben"],
"v706": ["weniger konsumieren","bewusst konsumieren"],
"v708": ["mit Kreditkarte zahlen","die Kreditkarte sperren"],
"v709": ["Bargeld abheben","kein Bargeld dabei"],
"v716": ["öffentliche Verkehrsmittel","das Verkehrsmittel wechseln"],
"v719": ["ein Fahrzeug anmelden","das Fahrzeug parken"],
"v723": ["an der Haltestelle warten","die nächste Haltestelle"],
"v727": ["den Fahrplan lesen","der Fahrplan ändert sich"],
"v733": ["die Straße ist gesperrt","wegen Bauarbeiten gesperrt"],
"v736": ["ein Fußgänger überquert","als Fußgänger unterwegs"],
"v737": ["am Zebrastreifen anhalten","über den Zebrastreifen gehen"],
"v738": ["auf dem Radweg fahren","der Radweg führt zum Park"],
"v745": ["Mobilität ohne Auto","die Mobilität der Zukunft"],
"v766": ["online einchecken","am Schalter einchecken"],
"v780": ["zur Behörde gehen","die Behörde antwortet"],
"v784": ["Elterngeld beantragen","schriftlich beantragen"],
"v789": ["laute Musik verbieten","das Rauchen verbieten"],
"v799": ["vor Gericht gehen","das Gericht entscheidet"],
"v800": ["der Richter entscheidet","vor dem Richter stehen"],
"v804": ["einen Anwalt nehmen","mit dem Anwalt sprechen"],
"v809": ["das Recht haben auf","im Recht sein"],
"v827": ["den Verbrecher fassen","ein gefährlicher Verbrecher"],
"v847": ["im dritten Semester","das Semester beginnt"],
"v862": ["in der Mensa essen","das Essen in der Mensa"],
"v886": ["ein gutes Gedächtnis","das Gedächtnis trainieren"],
"v896": ["der Professor erklärt","beim Professor nachfragen"],
"v898": ["am Institut arbeiten","das Institut sucht"],
"v908": ["sich über den Lärm ärgern","sich über den Chef ärgern"],
"v909": ["Ärger haben mit","Ärger bekommen"],
"v910": ["eine ärgerliche Situation","ärgerlich reagieren"],
"v913": ["enttäuscht sein von","bitter enttäuscht"],
"v919": ["ein ängstliches Kind","ängstlich reagieren"],
"v928": ["das Kind beruhigen","jemanden mit Worten beruhigen"],
"v929": ["sich schnell beruhigen","sich wieder beruhigen"],
"v930": ["gute Stimmung","die Stimmung im Team"],
"v934": ["Mut haben","den Mut verlieren"],
"v938": ["dankbar sein für","dankbar lächeln"],
"v974": ["sich um die Kinder sorgen","sich um die Zukunft sorgen"],
"v975": ["sich Sorgen machen","die größte Sorge"],
"v976": ["besorgt sein","besorgt klingen"],
"v977": ["das Training beginnt","zum Training gehen"],
"v978": ["regelmäßig trainieren","zweimal pro Woche trainieren"],
"v979": ["ins Fitnessstudio gehen","das Fitnessstudio kündigen"],
"v985": ["ein anstrengender Tag","anstrengend sein"],
"v990": ["an die Grenze kommen","die Grenze überschreiten"],
"v996": ["die Muskeln trainieren","der Muskel tut weh"],
"v1008": ["ein großer Fan","Fan von Fußball"],
"v1009": ["in der Sporthalle trainieren","die Sporthalle der Schule"],
"v1017": ["sich im Verein engagieren","sich ehrenamtlich engagieren"],
"v1023": ["einen Ausflug machen","ein Ausflug an den See"],
"v1034": ["einen Rekord aufstellen","den Rekord brechen"],
"v1037": ["Disziplin haben","mit Disziplin lernen"],
}
