# -*- coding: utf-8 -*-
"""18 B1 + 18 B2 Uebungssaetze aus verwaisten Karten (>=3 Waisen je Satz, Level-Wortschatz). Kein Audio (neu)."""

B1_S = [
    ("B1", "Die wirtschaftliche Entwicklung beeinflusst die gesamte Gesellschaft, weil neue Arbeitsplätze den allgemeinen Wohlstand stärken.", "التطور الاقتصادي يؤثر على المجتمع بأكمله، لأن فرص العمل الجديدة تعزز الرخاء العام.", ["die Wirtschaft", "die Entwicklung", "die Gesellschaft"], ["wirtschaft", "gesellschaft"]),
    ("B1", "An der Hochschule verteidigt der Student seine These, bevor das offizielle Prüfungsergebnis bekanntgegeben wird.", "في الجامعة يدافع الطالب عن أطروحته، قبل أن تُعلن نتيجة الامتحان الرسمية.", ["die Hochschule", "die These", "das Prüfungsergebnis"], ["studium", "pruefung"]),
    ("B1", "Wegen einer plötzlichen Krankheit musste er seine Verabredung absagen und sich sofort beim Arbeitgeber krankmelden.", "بسبب مرض مفاجئ اضطر لإلغاء موعده المتفق عليه وإبلاغ صاحب العمل بمرضه فوراً.", ["die Krankheit", "die Verabredung", "sich krankmelden"], ["gesundheit", "beruf"]),
    ("B1", "Viele Bürger demonstrieren friedlich auf den Straßen, um die Demokratie zu schützen und ihren Einfluss zu zeigen.", "يتظاهر العديد من المواطنين سلمياً في الشوارع لحماية الديمقراطية وإظهار تأثيرهم.", ["demonstrieren", "die Demokratie", "der Einfluss"], ["politik", "gesellschaft"]),
    ("B1", "In den sozialen Medien und über eine moderne Suchmaschine kann man gezielt recherchieren und nützliche Inhalte sofort speichern.", "في وسائل التواصل الاجتماعي وعبر محرك بحث حديث يمكن للمرء البحث بدقة وحفظ المحتويات المفيدة فوراً.", ["die sozialen Medien", "die Suchmaschine", "speichern"], ["digital", "internet"]),
    ("B1", "In dieser Fabrik hilft ein Roboter bei der schnellen Lieferung, und man muss den Akku regelmäßig aufladen.", "في هذا المصنع يساعد روبوت في التوصيل السريع، ويجب على المرء شحن البطارية بانتظام.", ["der Roboter", "die Lieferung", "aufladen"], ["technik", "arbeit"]),
    ("B1", "Durch ein sorgfältiges Experiment und eine genaue Statistik konnte das Forscherteam seine Entdeckung eindeutig beweisen.", "من خلال تجربة دقيقة وإحصائية مضبوطة استطاع فريق البحث إثبات اكتشافه بوضوح.", ["das Experiment", "die Statistik", "beweisen"], ["forschung", "wissenschaft"]),
    ("B1", "In diesem wissenschaftlichen Seminar diskutiert der Professor ein bekanntes Zitat aus der klassischen Literatur.", "في هذه الحلقة الدراسية العلمية يناقش الأستاذ اقتباساً معروفاً من الأدب الكلاسيكي.", ["das Seminar", "der Professor", "das Zitat"], ["universitaet", "literatur"]),
    ("B1", "Mit einer pflegenden Creme kann man kleine Falten im Gesicht mildern, bevor man beginnt, sich für das Fest zu schminken.", "باستخدام كريم مغذٍّ يمكن للمرء تخفيف التجاعيد الصغيرة في الوجه، قبل أن يبدأ في التزيّن للاحتفال.", ["die Creme", "die Falte", "sich schminken"], ["pflege", "gesundheit"]),
    ("B1", "Die moderne Mode verändert unsere Vorstellung von Schönheit, denn was gestern noch hässlich war, ist heute im Trend.", "الموضة الحديثة تغيّر تصورنا عن الجمال، فما كان بالأمس قبيحاً صار اليوم دارجاً.", ["die Mode", "die Schönheit", "hässlich"], ["kultur", "mode"]),
    ("B1", "Umweltfreundliche Mobilität erfordert, dass jedes Fahrzeug rechtzeitig vor dem Zebrastreifen anhält.", "التنقل الصديق للبيئة يتطلب أن تتوقف كل مركبة في الوقت المناسب قبل ممر المشاة.", ["die Mobilität", "das Fahrzeug", "der Zebrastreifen"], ["verkehr", "umwelt"]),
    ("B1", "Wenn bei Glatteis gefährliche Probleme auftreten, sollte man das Fahren verbieten, um einen schweren Unfall zu verhindern.", "إذا ظهرت مشاكل خطيرة عند الانزلاق على الجليد، فينبغي منع القيادة لتفادي وقوع حادث خطير.", ["auftreten", "verbieten", "der Unfall"], ["sicherheit", "verkehr"]),
    ("B1", "In der Oberstufe haben die Schüler oft eine Doppelstunde Unterricht, und für beliebte Fächer gibt es eine Warteliste.", "في المرحلة الثانوية العليا يحصل الطلاب غالباً على حصة مضاعفة من الدرس، وتوجد قائمة انتظار للمواد المرغوبة.", ["die Oberstufe", "die Doppelstunde", "die Warteliste"], ["schule", "bildung"]),
    ("B1", "Eine gezielte Nachhilfe unterstützt auch leistungsstarke Kinder und trainiert das Gedächtnis auf spielerische Weise.", "الدروس الخصوصية الموجهة تدعم أيضاً الأطفال ذوي الأداء القوي وتدرّب الذاكرة بطريقة مرحة.", ["die Nachhilfe", "leistungsstark", "das Gedächtnis"], ["bildung", "foerderung"]),
    ("B1", "Wer regelmäßig ins Fitnessstudio oder in die Sporthalle geht, kann seine Ausdauer verbessern und einen persönlichen Rekord aufstellen.", "من يذهب بانتظام إلى النادي الرياضي أو الصالة الرياضية يمكنه تحسين قدرته على التحمل وتسجيل رقم قياسي شخصي.", ["das Fitnessstudio", "die Sporthalle", "der Rekord"], ["sport", "gesundheit"]),
    ("B1", "Um die hohe Arbeitslosigkeit zu senken, zahlt das Jobcenter Unterstützung, verhängt bei Verstößen jedoch eine spürbare Sanktion.", "لخفض معدل البطالة المرتفع يدفع مركز التوظيف دعماً، لكنه يفرض عند المخالفات عقوبة ملموسة.", ["die Arbeitslosigkeit", "das Jobcenter", "die Sanktion"], ["arbeit", "soziales"]),
    ("B1", "Eine gemeinnützige Stiftung möchte benachteiligten Familien helfen, indem engagierte Bürger Kleidung und Schulmaterial spenden.", "ترغب مؤسسة خيرية في مساعدة العائلات المحرومة، من خلال تبرع المواطنين الملتزمين بالملابس والأدوات المدرسية.", ["die Stiftung", "benachteiligt", "spenden"], ["soziales", "spenden"]),
    ("B1", "Man sollte alte Möbel nicht voreilig wegwerfen, denn beim Einziehen in die neue Wohnung hilft oft ein praktischer Gutschein.", "لا ينبغي للمرء رمي الأثاث القديم بتسرّع، لأن قسيمة شراء عملية تفيد كثيراً عند الانتقال إلى شقة جديدة.", ["wegwerfen", "einziehen", "der Gutschein"], ["haushalt", "umwelt"])
]

B2_S = [
    ("B2", "Soziale Ungleichheit führt oft dazu, dass ein Obdachloser unter gesellschaftlicher Ausgrenzung und mangelnder Unterstützung leidet.", "اللاتكافؤ الاجتماعي يؤدي غالباً إلى معاناة الشخص بلا مأوى من الإقصاء المجتمعي ونقص الدعم.", ["die Ungleichheit", "der Obdachlose", "die Ausgrenzung"], ["gesellschaft", "soziales"]),
    ("B2", "Viele Migranten mit Migrationshintergrund möchten sich erfolgreich integrieren und einen aktiven Beitrag zum Zusammenleben leisten.", "يرغب العديد من المهاجرين من ذوي الأصول المهاجرة في الاندماج بنجاح وتقديم مساهمة فاعلة في العيش المشترك.", ["der Migrant", "der Migrationshintergrund", "sich integrieren"], ["migration", "integration"]),
    ("B2", "Durch ehrenamtliches Engagement und eine offizielle Petition können aktive Bürger wichtige Verbesserungen in ihrer Kommune erreichen.", "من خلال الالتزام التطوعي وعريضة رسمية يستطيع المواطنون النشطون تحقيق تحسينات هامة في بلديتهم.", ["ehrenamtlich", "das Engagement", "die Petition"], ["buerger", "engagement"]),
    ("B2", "In einem echten Rechtsstaat ist jede friedliche Demonstration oder öffentliche Kundgebung ein geschütztes demokratisches Grundrecht.", "في دولة قانون حقيقية تعد كل مظاهرة سلمية أو تجمع احتجاجي علني حقاً أساسياً ديمقراطياً محمياً.", ["der Rechtsstaat", "die Demonstration", "die Kundgebung"], ["recht", "politik"]),
    ("B2", "In einer modernen Konsumgesellschaft garantiert die Meinungsfreiheit, dass niemand wegen seiner kritischen Haltung diskriminiert wird.", "في مجتمع استهلاكي حديث تضمن حرية الرأي ألا يتعرض أحد للتمييز بسبب موقفه النقدي.", ["die Konsumgesellschaft", "die Meinungsfreiheit", "diskriminieren"], ["demokratie", "freiheit"]),
    ("B2", "Aufgrund der akuten Wohnungsnot suchen viele Mieter eine bezahlbare Wohnung, die man unbefristet mieten und sorgfältig renovieren kann.", "نظراً لأزمة السكن الحادة يبحث العديد من المستأجرين عن شقة معقولة السعر يمكن استئجارها لأجل غير مسمى وتجديدها بعناية.", ["die Wohnungsnot", "unbefristet", "renovieren"], ["wohnen", "miete"]),
    ("B2", "Für ein harmonisches Zusammenleben in der Hausgemeinschaft regelt die Hausordnung auch die angemessene Möblierung gemeinsamer Räume.", "من أجل عيش مشترك متناغم في مجتمع العمارة ينظم نظام المبنى أيضاً التأثيث المناسب للمساحات المشتركة.", ["zusammenleben", "die Hausordnung", "die Möblierung"], ["wohngemeinschaft", "hausordnung"]),
    ("B2", "Man muss die Folgen der Automatisierung differenziert beurteilen, damit technische Kontrollen nicht zu einer ständigen Belästigung führen.", "يجب على المرء تقييم عواقب الأتمتة بشكل متمايز، حتى لا تؤدي الرقابة التقنية إلى إزعاج مستمر.", ["die Automatisierung", "beurteilen", "die Belästigung"], ["technik", "arbeit"]),
    ("B2", "Ein geschärftes Umweltbewusstsein fordert, dass wirtschaftliche Aktivitäten die Natur nicht schädigen und mit der Vereinbarkeit sozialer Ziele harmonieren.", "يتطلب الوعي البيئي اليقظ ألا تلحق الأنشطة الاقتصادية الضرر بالطبيعة وأن تتناغم مع التوفيق بين الأهداف الاجتماعية.", ["das Umweltbewusstsein", "schädigen", "die Vereinbarkeit"], ["umwelt", "wirtschaft"]),
    ("B2", "Auf der Bühne inszeniert der Regisseur das preisgekrönte Drehbuch mit großer Leidenschaft und beeindruckenden Schauspielern.", "على خشبة المسرح يخرج المخرج السيناريو الحائز على جوائز بشغف كبير وممثلين مثيرين للإعجاب.", ["die Bühne", "der Regisseur", "das Drehbuch"], ["theater", "kultur"]),
    ("B2", "Das Theaterensemble will ein klassisches Stück aufführen, das bekannte Kritiker in einer ausführlichen Rezension rezensieren.", "يريد الفريق المسرحي عرض مسرحية كلاسيكية يراجعها نقاد معروفون في مراجعة نقدية مفصلة.", ["aufführen", "die Rezension", "rezensieren"], ["theater", "kritik"]),
    ("B2", "Ein talentierter Schriftsteller verfasst anspruchsvolle Lyrik und lässt sich dabei von einem historischen Gemälde inspirieren.", "يؤلف كاتب موهوب شعراً غنائياً رفيع المستوى ويستلهم في ذلك من لوحة تاريخية.", ["der Schriftsteller", "die Lyrik", "das Gemälde"], ["literatur", "kunst"]),
    ("B2", "Die berühmte Skulptur gilt als einzigartiges Weltkulturerbe und zieht als Sehenswürdigkeit zahlreiche kulturinteressierte Gäste an.", "يُعد التمثال الشهير تراثاً ثقافياً عالمياً فريداً ويجذب بوصفه معلماً بارزاً عدداً كبيراً من الضيوف المهتمين بالثقافة.", ["die Skulptur", "das Weltkulturerbe", "die Sehenswürdigkeit"], ["kultur", "tourismus"]),
    ("B2", "Viele qualifizierte Fachkräfte in Vollzeit fühlen sich überqualifiziert und zugleich für ihre anspruchsvolle Verantwortung unterbezahlt.", "يشعر العديد من المتخصصين المؤهلين بدوام كامل بأنهم مؤهلون أكثر من اللازم وفي الوقت نفسه لا يتقاضون أجراً كافياً لقاء مسؤوليتهم العالية.", ["die Vollzeit", "überqualifiziert", "unterbezahlt"], ["arbeit", "gehalt"]),
    ("B2", "Wer im Beruf erfolgreich aufsteigen möchte, nutzt jede Konferenz zum Netzwerken oder entscheidet sich für eine fundierte Umschulung.", "من يرغب في الترقي بنجاح في مهنته يستغل كل مؤتمر للتواصل أو يقرر الالتحاق بإعادة تأهيل مهني متين.", ["aufsteigen", "die Konferenz", "die Umschulung"], ["karriere", "weiterbildung"]),
    ("B2", "Die Wiederverwendung von Rohstoffen ist umweltschonend und reduziert den massenhaften Verbrauch von überflüssigen Einwegprodukten.", "إعادة استخدام المواد الخام صديقة للبيئة وتقلل من الاستهلاك الهائل للمنتجات ذات الاستخدام الواحد الزائدة عن الحاجة.", ["die Wiederverwendung", "umweltschonend", "das Einwegprodukt"], ["umwelt", "nachhaltigkeit"]),
    ("B2", "Im Bereich Naturschutz schützt ein ausgewiesenes Schutzgebiet die gefährdete Biodiversität vor schädlichen menschlichen Eingriffen.", "في مجال حماية الطبيعة تحمي محمية معتمدة التنوع البيولوجي المهدد من التدخلات البشرية الضارة.", ["der Naturschutz", "das Schutzgebiet", "die Biodiversität"], ["umwelt", "artenschutz"]),
    ("B2", "Nach dem verheerenden Hochwasser einigten sich die Politiker auf verbindliche Treibhausgase und ein klares nationales Klimaziel.", "بعد الفيضان المدمر اتفق السياسيون على خفض ملزم لغازات الاحتباس الحراري وهدف مناخي وطني واضح.", ["das Hochwasser", "das Treibhausgas", "das Klimaziel"], ["klima", "umwelt"])
]

S = B1_S + B2_S
