# -*- coding: utf-8 -*-
"""22 A1 + 13 A2 Uebungssaetze aus verwaisten Karten (>=3 Waisen je Satz, Level-Wortschatz). Kein Audio (neu)."""
S = [
# A1 (22)
("A1","Im Januar und im Februar ist es kalt, im Juni und im Juli ist es warm.","في يناير وفبراير يكون الجو بارداً، وفي يونيو ويوليو دافئاً.",["der Januar","der Februar","der Juni","der Juli"],["monate","jahreszeit"]),
("A1","Wir mögen grün und gelb, aber unsere Mutter mag nur blau.","نحب الأخضر والأصفر، لكن أمنا تحب الأزرق فقط.",["grün","gelb","mögen"],["farben","moegen"]),
("A1","Jeder Schüler hat einen Stuhl, der Unterricht soll um acht Uhr anfangen.","لكل تلميذ كرسي، والدرس يجب أن يبدأ في الثامنة.",["der Schüler","anfangen","der Stuhl"],["modalverb","trennbar"]),
("A1","Der Stuhl steht zwischen dem Tisch und dem Fenster, die Lampe hängt oben.","الكرسي بين الطاولة والنافذة، والمصباح معلّق في الأعلى.",["der Stuhl","zwischen","oben"],["praeposition","dativ"]),
("A1","Das Buch liegt oben auf dem Regal, die Brille liegt unten auf dem Stuhl.","الكتاب في الأعلى على الرف، والنظارة في الأسفل على الكرسي.",["oben","die Brille","der Stuhl"],["praeposition"]),
("A1","Woher kommst du, warum lernst du Deutsch, und wann willst du anfangen?","من أين أنت، ولماذا تتعلّم الألمانية، ومتى تريد أن تبدأ؟",["woher","warum","anfangen"],["w-fragen"]),
("A1","Die Krankenschwester sagt, ich soll mich ausruhen, weil das Auge rot ist.","الممرضة تقول إن عليّ أن أستريح لأن العين حمراء.",["die Krankenschwester","sich ausruhen","das Auge"],["modalverb","weil"]),
("A1","Mein Auge tut weh und mein Finger auch, aber mein Gesicht ist gesund.","عيني تؤلمني وإصبعي أيضاً، لكن وجهي بخير.",["das Auge","der Finger","das Gesicht"],["koerper"]),
("A1","Ich kaufe fünfhundert Gramm Fleisch, einen Liter Milch und eine Packung Reis.","أشتري خمسمائة غرام لحم، وليتر حليب، وعلبة أرز.",["das Gramm","der Liter","die Packung","das Fleisch"],["mengen"]),
("A1","Eine Dose Tomaten kostet einen Euro, die Trauben drei Euro und die Zwiebeln zwei Euro.","علبة طماطم بيورو، والعنب بثلاثة، والبصل بيورهين.",["die Dose","die Traube","die Zwiebel"],["preise"]),
("A1","Ich schneide die Zwiebel und das Fleisch, dann muss ich den Herd anmachen.","أقطّع البصل واللحم، ثم يجب أن أشغّل الموقد.",["die Zwiebel","das Fleisch","anmachen"],["modalverb","trennbar"]),
("A1","Du musst das Licht ausmachen, wenn du weggehen willst, und es anmachen, wenn du zurückkommen willst.","يجب أن تطفئ الضوء عندما تريد الخروج، وتشغّله عندما تريد العودة.",["ausmachen","weggehen","zurückkommen"],["modalverb","trennbar"]),
("A1","Willst du mitkommen? Wir gehen zur Kirche und dann zur Moschee, beide sind in der Stadtmitte.","هل تريد أن تأتي معنا؟ نذهب إلى الكنيسة ثم إلى المسجد، كلاهما في وسط المدينة.",["mitkommen","die Kirche","die Moschee"],["modalverb","orte"]),
("A1","An der Kreuzung gehst du links; überall gibt es Schilder, und zurückfahren kannst du mit dem Bus.","عند التقاطع تذهب يساراً؛ في كل مكان لافتات، وتستطيع العودة بالحافلة.",["die Kreuzung","überall","zurückfahren"],["wegbeschreibung"]),
("A1","Hier ist Parken verboten, das Geschäft ist geschlossen, und Kinder dürfen nicht allein hinein.","هنا الوقوف ممنوع، والمتجر مغلق، والأطفال لا يجوز لهم الدخول وحدهم.",["verboten","geschlossen","dürfen"],["schilder","modalverb"]),
("A1","Was ist die Bedeutung von diesem Schild? Hier dürfen Autos nicht fahren, das ist verboten.","ما معنى هذه اللافتة؟ هنا لا يجوز للسيارات أن تسير، هذا ممنوع.",["dürfen","verboten","die Bedeutung"],["modalverb"]),
("A1","Am Anfang der Reise packe ich das Handtuch und die Zahnbürste in die Tasche.","في بداية الرحلة أضع المنشفة وفرشاة الأسنان في الحقيبة.",["das Handtuch","die Zahnbürste","der Anfang"],["bad"]),
("A1","Alte Geräte können kaputtgehen; das Kind ist dann traurig, aber der Vater ist nicht böse.","الأجهزة القديمة قد تتعطّل؛ الطفل يحزن حينها، لكن الأب ليس غاضباً.",["kaputtgehen","traurig","böse"],["gefuehle","modalverb"]),
("A1","Herzlichen Glückwunsch! Du bist heute dreizehn oder fünfzehn?","مبارك! عمرك اليوم ثلاث عشرة أم خمس عشرة سنة؟",["Herzlichen Glückwunsch","dreizehn","fünfzehn"],["zahlen"]),
("A1","Die Ehefrau von Herrn Weber verkauft Blumen, ihr Traum ist ein eigener Laden.","زوجة السيد فيبر تبيع الزهور، وحلمها متجر خاص بها.",["die Ehefrau","verkaufen","der Traum"],["beruf"]),
("A1","Im Notruf sagst du am Anfang deinen Namen und die Adresse und darfst nicht aufhören zu sprechen.","في اتصال الطوارئ تقول في البداية اسمك والعنوان ولا يجوز أن تتوقف عن الكلام.",["der Notruf","der Anfang","aufhören"],["notfall","modalverb"]),
("A1","Wir gehen wöchentlich durch den Park, die Maus im Gras sehen wir selten.","نمشي أسبوعياً عبر الحديقة، والفأر في العشب نراه نادراً.",["wöchentlich","durch","die Maus","das Gras"],["praeposition","haeufigkeit"]),
# A2 (13)
("A2","Ehrlich gesagt, meiner Meinung nach ist der Vorschlag gut, aber ich erwarte eine klare Entscheidung.","بصراحة، في رأيي الاقتراح جيد، لكنني أنتظر قراراً واضحاً.",["die Meinung","der Vorschlag","erwarten","die Entscheidung"],["meinung"]),
("A2","Können Sie den Weg beschreiben? Die Strecke bis zur Baustelle ist lang.","هل تستطيع وصف الطريق؟ المسافة حتى الورشة طويلة.",["beschreiben","die Strecke","die Baustelle"],["frage","weg"]),
("A2","Brutto verdiene ich mehr, aber netto bleibt weniger, weil ich lange arbeitslos war.","إجمالياً أكسب أكثر، لكن الصافي أقل، لأنني كنت عاطلاً طويلاً.",["brutto","netto","arbeitslos","verdienen"],["weil","geld"]),
("A2","Wir recyceln das Papier, verpacken das Glas und trennen den Müll für die Umwelt.","نعيد تدوير الورق، ونغلّف الزجاج، ونفصل النفايات من أجل البيئة.",["recyceln","verpacken","die Umwelt","trennen"],["umwelt"]),
("A2","Ich muss den Termin absagen und auf nächste Woche verschieben; das sollten wir kurz absprechen.","يجب أن ألغي الموعد وأؤجّله إلى الأسبوع القادم؛ ينبغي أن نتفق على ذلك باختصار.",["absagen","verschieben","absprechen"],["trennbar","modalverb"]),
("A2","Du musst die Übung jeden Tag üben, dann kannst du die Prüfung bestehen, und die Lehrerin wird dich loben.","يجب أن تتدرّب على التمرين كل يوم، عندها تستطيع النجاح في الامتحان، وستمدحك المعلّمة.",["die Übung","üben","bestehen","loben"],["modalverb","futur"]),
("A2","Am Anfang der E-Mail stehen der Betreff und die Anrede, am Ende die Grußformel.","في بداية الإيميل الموضوع والتحية، وفي النهاية صيغة الختام.",["der Betreff","die Anrede","die Grußformel"],["brief"]),
("A2","Ich bin unsicher und ein bisschen unruhig, aber auch neugierig auf die neue Stadt.","أنا غير واثق وقلق قليلاً، لكنني فضولي أيضاً تجاه المدينة الجديدة.",["unsicher","unruhig","neugierig"],["gefuehle","adjektiv"]),
("A2","Am Feiertag haben wir frei; wir wandern, und danach eröffnet mein Onkel sein neues Geschäft.","في العطلة الرسمية لدينا إجازة؛ نتنزّه مشياً، وبعدها يفتتح عمّي متجره الجديد.",["der Feiertag","wandern","eröffnen","das Geschäft"],["zeit"]),
("A2","Der Sprachnachweis ist eine Bedingung für den Zuschuss, sagt die Beratungsstelle.","إثبات اللغة شرط للمنحة، يقول مركز الاستشارة.",["der Sprachnachweis","die Bedingung","der Zuschuss","die Beratungsstelle"],["amt"]),
("A2","Mein Bruder ist schüchtern, meine Schwester ist großzügig, und ich bin manchmal ungeduldig.","أخي خجول، وأختي كريمة، وأنا أحياناً غير صبور.",["schüchtern","großzügig","ungeduldig","der Charakter"],["adjektiv","charakter"]),
("A2","Zum Frühstück eine Semmel, zum Mittagessen eine fettarme Mahlzeit: So habe ich in drei Monaten fünf Kilo abgenommen.","على الفطور خبزة صغيرة، وعلى الغداء وجبة قليلة الدهون: هكذا خسرت خمسة كيلو في ثلاثة أشهر.",["die Semmel","fettarm","die Mahlzeit","abnehmen"],["ernaehrung","perfekt"]),
("A2","Zuerst musst du dich im Onlineportal einloggen, dann den Scan hochladen und zum Schluss die Benachrichtigung ausdrucken.","أولاً يجب أن تسجّل الدخول في البوابة الإلكترونية، ثم ترفع المسح الضوئي، وأخيراً تطبع الإشعار.",["sich einloggen","hochladen","der Scan","ausdrucken","die Benachrichtigung"],["modalverb","reihenfolge"]),
]
