# -*- coding: utf-8 -*-
"""12 B1 + 13 B2 Uebungssaetze aus verwaisten Karten (>=3 Waisen je Satz). Kein Audio (neu=True)."""
S = [
# B1 (s-b1-49..60)
("B1","Die Krankenkasse übernimmt die Behandlung, aber die Tablette muss ich in der Apotheke selbst bezahlen.","صندوق التأمين يتحمّل العلاج، لكن القرص عليّ دفعه بنفسي في الصيدلية.",["die Krankenkasse","die Behandlung","die Tablette","die Apotheke"],["nebensatz","kontrast"]),
("B1","Meine Freundschaft mit Karim basiert auf Vertrauen, obwohl wir uns nur selten verabreden.","صداقتي مع كريم مبنية على الثقة رغم أننا نادراً ما نحدّد مواعيد.",["die Freundschaft","das Vertrauen","sich verabreden"],["obwohl","nebensatz"]),
("B1","Die Ärztin hat mich beruhigt: Die Operation im Krankenhaus dauert nur eine Stunde.","الطبيبة طمأنتني: العملية في المستشفى تستغرق ساعة واحدة فقط.",["die Ärztin","beruhigen","die Operation","das Krankenhaus"],["perfekt"]),
("B1","Wer sich gesund ernährt und genug Bewegung hat, ist seltener gestresst.","من يتغذّى بشكل صحي ويتحرّك كفاية يكون أقل توتراً.",["sich ernähren","die Bewegung","gestresst"],["relativsatz","wer"]),
("B1","Die Integration gelingt leichter, wenn die Mehrheit tolerant ist und Vorurteile abbaut.","الاندماج ينجح بسهولة أكبر حين تكون الأغلبية متسامحة وتزيل الأحكام المسبقة.",["die Integration","die Mehrheit","tolerant","das Vorurteil"],["wenn","konditional"]),
("B1","Nach der Wahl diskutiert das Parlament über den Klimawandel und die Umweltverschmutzung in den Städten.","بعد الانتخابات يناقش البرلمان التغيّر المناخي وتلوّث البيئة في المدن.",["die Wahl","das Parlament","der Klimawandel","die Umweltverschmutzung"],["praeposition","genitiv"]),
("B1","Für die Weiterbildung hat mein Arbeitgeber die Arbeitszeit um zwei Stunden pro Woche gekürzt.","من أجل التكوين المستمر خفّض صاحب عملي ساعات العمل ساعتين أسبوعياً.",["die Weiterbildung","der Arbeitgeber","die Arbeitszeit"],["perfekt","praeposition"]),
("B1","Bevor du einen Kredit bei der Sparkasse beantragst, solltest du dein Budget genau prüfen.","قبل أن تطلب قرضاً من مصرف التوفير، ينبغي أن تفحص ميزانيتك بدقة.",["der Kredit","die Sparkasse","beantragen","das Budget"],["bevor","konjunktiv2"]),
("B1","Die Behörde hat den Antrag abgelehnt, weil ein Beleg für die Herkunft des Geldes fehlte.","الإدارة رفضت الطلب لأن إثبات مصدر المال كان ناقصاً.",["die Behörde","der Antrag","der Beleg","die Herkunft"],["weil","praeteritum"]),
("B1","In der Ausstellung im Museum zeigt die Künstlerin Gemälde aus ihrer Zeit in Tunis.","في المعرض بالمتحف تعرض الفنانة لوحات من فترتها في تونس.",["die Ausstellung","das Museum","die Künstlerin"],["praeposition","dativ"]),
("B1","Ich kann nachvollziehen, dass du enttäuscht bist, aber wir sollten sachlich bleiben und die Zusammenarbeit verbessern.","أستطيع أن أفهم أنك محبط، لكن ينبغي أن نبقى موضوعيين ونحسّن التعاون.",["enttäuscht","sachlich bleiben","die Zusammenarbeit","verbessern"],["dass","modalverb"]),
("B1","Der Fahrplan hat sich geändert, daher nehmen viele Fußgänger jetzt das Fahrrad statt des Busses.","تغيّر جدول المواعيد، ولذلك يأخذ كثير من المشاة الدراجة الآن بدل الحافلة.",["der Fahrplan","daher","der Fußgänger","das Fahrzeug"],["daher","genitiv"]),
# B2 (s-b2-48..60)
("B2","Die Umfrage wurde von einem unabhängigen Institut durchgeführt; dennoch bezweifeln viele ihre Glaubwürdigkeit und halten die Auswertung für wenig glaubwürdig.","أُجري الاستطلاع من معهد مستقل؛ ومع ذلك يشكّك كثيرون في مصداقيته ويرون التحليل قليل الموثوقية.",["die Umfrage","die Glaubwürdigkeit","die Auswertung","glaubwürdig"],["passiv","konnektor"]),
("B2","Wer Mobbing am Arbeitsplatz erlebt, sollte den Vorgesetzten informieren, statt die Erschöpfung allein zu bewältigen.","من يتعرّض للتنمّر في مكان العمل ينبغي أن يُبلغ رئيسه بدل أن يجابه الإنهاك وحده.",["das Mobbing","der Vorgesetzte","die Erschöpfung","bewältigen"],["statt-zu","relativsatz"]),
("B2","Obwohl die Kaution bereits überwiesen war, verlangte der Makler eine zusätzliche Provision für den Mietvertrag.","رغم أن الضمانة كانت محوَّلة بالفعل، طلب الوسيط عمولة إضافية على عقد الإيجار.",["die Kaution","der Makler","die Provision","der Mietvertrag"],["obwohl","plusquamperfekt"]),
("B2","Der Algorithmus bevorzugt Beiträge von Influencern, die Empörung auslösen, weshalb die Bildschirmzeit vieler Nutzer steigt.","الخوارزمية تفضّل منشورات المؤثّرين التي تثير الاستنكار، ولذلك يرتفع زمن الشاشة لدى كثير من المستخدمين.",["der Algorithmus","der Influencer","die Bildschirmzeit"],["relativsatz","weshalb"]),
("B2","Bevor die Hypothese publiziert wird, muss der Datensatz erneut ausgewertet werden.","قبل نشر الفرضية يجب إعادة تحليل مجموعة البيانات.",["die Hypothese","publizieren","der Datensatz","auswerten"],["passiv","modalverb"]),
("B2","Die Gewerkschaft droht zu streiken, falls der Arbeitsvertrag weiterhin Schichtarbeit ohne Zuschlag vorsieht.","النقابة تهدّد بالإضراب إذا استمر عقد العمل في النصّ على مناوبات بلا علاوة.",["die Gewerkschaft","streiken","der Arbeitsvertrag","die Schichtarbeit"],["falls","infinitiv"]),
("B2","Je stärker die Dürre den Grundwasserspiegel senkt, desto lauter fordert die Klimabewegung ein verbindliches Abkommen.","كلما خفّض الجفاف منسوب المياه الجوفية أكثر، ارتفع صوت الحركة المناخية مطالبةً باتفاق ملزم.",["die Dürre","das Grundwasser","die Klimabewegung","das Abkommen"],["je-desto"]),
("B2","Wäre der Kassenbon nicht verloren gegangen, hätte die Reklamation innerhalb der Gewährleistung problemlos funktioniert.","لو لم يضِع وصل الصندوق، لكانت الشكوى ضمن الضمان القانوني قد نجحت بلا مشاكل.",["der Kassenbon","die Reklamation","die Gewährleistung"],["konjunktiv2","irreal"]),
("B2","Seit der Einführung der Umweltzone hat sich die Luftqualität verbessert, während die Fahrgemeinschaften weiter zunehmen.","منذ إدخال منطقة الانبعاث المقيّدة تحسّن نقاء الهواء، بينما تستمر مجموعات تقاسم السيارة في الازدياد.",["die Umweltzone","die Luftqualität","die Fahrgemeinschaft"],["waehrend","perfekt"]),
("B2","Das Verfassungsgericht prüft, ob die Abschiebung mit den Grundrechten und der Rechtslage vereinbar ist.","المحكمة الدستورية تفحص ما إذا كان الإبعاد متوافقاً مع الحقوق الأساسية والوضع القانوني.",["das Verfassungsgericht","die Abschiebung","die Grundrechte","die Rechtslage"],["ob","indirekte-frage"]),
("B2","Weil sie nicht noch einmal durchfallen wollte, half ihr die Studienberatung, eine passende Lernmethode zu finden.","لأنها لم تُرد الرسوب مرة أخرى، ساعدها الإرشاد الأكاديمي في إيجاد أسلوب تعلّم مناسب.",["durchfallen","die Studienberatung","die Lernmethode"],["weil","infinitiv"]),
("B2","Der Quereinsteiger wurde trotz fehlender Berufserfahrung eingestellt, weil er im Gespräch selbstbewusst und glaubwürdig auftrat.","الداخل من تخصص آخر وُظّف رغم غياب الخبرة المهنية لأنه ظهر في المقابلة واثقاً وموثوقاً.",["der Quereinsteiger","die Berufserfahrung","selbstbewusst","glaubwürdig"],["passiv","trotz","weil"]),
("B2","Ohne verbindliche Mülltrennung bleibt jedes Mehrwegsystem nur ein Symbol gegen den wachsenden Plastikmüll.","بلا فرز إلزامي للنفايات يبقى كل نظام إعادة استعمال مجرد رمز ضد النفايات البلاستيكية المتزايدة.",["die Mülltrennung","das Mehrwegsystem","der Plastikmüll"],["praeposition","ohne"]),
]
