# -*- coding: utf-8 -*-
"""Batch 10: 2 A1 + 16 A2 + 18 B1 + 16 B2 = 52 Saetze (182 Waisen aufgeloest -> A1 100%, A2 100%)."""

S = [
    # === A1 (2 Saetze -> 6 Waisen -> 100% A1) ===
    ("A1",
     "Im warmen August schneidet der Friseur lange Haare kurz, damit keine losen Haare auf den Boden fallen.",
     "في شهر أغسطس الحار، يقص الحلاق الشعر الطويل قصيراً، حتى لا يتساقط شعر سائب على الأرض.",
     ["der August", "das Haar", "fallen"],
     ["alltag", "koerper"]),

    ("A1",
     "Vor der Abreise sagen die Gäste freundlich tschüss, während Lehrer hundertzwanzig Schülern ein gutes Beispiel geben.",
     "قبل المغادرة، يقول الضيوف بوداع لطيف مع السلامة، بينما يقدم المعلمون لمائة وعشرين طالباً قدوة ومثالاً حسناً.",
     ["tschüss", "hundertzwanzig", "das Beispiel geben"],
     ["alltag", "schule"]),

    # === A2 (16 Saetze -> 54 Waisen -> 100% A2) ===
    ("A2",
     "Kunden können frische Waren online bestellen und abholen, wichtige Information erhalten und jeden Text sorgfältig Korrektur lesen.",
     "يمكن للعملاء طلب بضائع طازجة واستلامها عبر الإنترنت، وتلقي معلومات مهمة وقراءة كل نص تدقيقياً بعناية.",
     ["bestellen und abholen", "Korrektur lesen", "die Information"],
     ["einkauf", "medien"]),

    ("A2",
     "Niemand sollte auf andere eifersüchtig sein, sondern mit kleinen Erfolgen zufrieden sein, da gute Ergebnisse vom Fleiß abhängen.",
     "لا ينبغي لأحد أن يكون حسوداً تجاه الآخرين، بل أن يكون راضياً بالنجاحات الصغيرة، لأن النتائج الجيدة تعتمد على الاجتهاد.",
     ["eifersüchtig", "zufrieden sein mit", "abhängen von"],
     ["gefuehle", "alltag"]),

    ("A2",
     "Wer eine große Menge an Schlüsseln besitzt, sollte sie nicht verlieren, da moderne Türen automatisch verriegeln.",
     "من يمتلك كمية كبيرة من المفاتيح، ينبغي له ألا يفقدها، لأن الأبواب الحديثة تقفل تلقائياً.",
     ["die Menge", "automatisch", "verlieren"],
     ["alltag", "sicherheit"]),

    ("A2",
     "Vor der Behandlung zahlten Patienten eine Praxisgebühr, erhielten eine schützende Impfung und vermieden bei richtiger Kalorienzufuhr das Krankenhaus.",
     "قبل العلاج دفع المرضى رسوم العيادة وتلقوا تطعيماً واقياً وتجنبوا دخول المستشفى مع التناول الصحيح للسعرات الحرارية.",
     ["die Kalorie", "die Impfung", "das Krankenhaus einliefern", "die Praxisgebühr"],
     ["gesundheit", "medizin"]),

    ("A2",
     "In der Küche muss die Suppe langsam abkühlen, während der Koch Zutaten auf der Küchenwaage wiegt und die Küchenrolle nimmt.",
     "في المطبخ يجب أن تبرد الشوربة ببطء، بينما يزن الطباخ المكونات على ميزان المطبخ ويأخذ لفة ورق المطبخ.",
     ["abkühlen", "die Küchenwaage", "die Küchenrolle"],
     ["kueche", "haushalt"]),

    ("A2",
     "Sobald der Kurs beginnt, lernen Erwachsene täglich, nachdem sie gearbeitet haben, und erzielen schließlich beachtliche Sprachfortschritte.",
     "بمجرد أن تبدأ الدورة، يتعلم البالغون يومياً بعد أن ينتهوا من العمل، ويحققون في النهاية تقدماً لغوياً ملحوظاً.",
     ["sobald", "nachdem", "schließlich"],
     ["lernen", "zeit"]),

    ("A2",
     "Kinder können sich prächtig entwickeln und jede schulische Schwierigkeit gemeinsam überwinden, wenn Eltern sie liebevoll unterstützen.",
     "يمكن للأطفال أن ينموا بشكل رائع ويتغلبوا على كل صعوبة مدرسية معاً، إذا دعمهم آباؤهم بحب.",
     ["sich entwickeln", "die Schwierigkeit", "überwinden"],
     ["familie", "bildung"]),

    ("A2",
     "Bei dem großen Ereignis prüfte die Leitung jede Haftung, während der engagierte Betriebsrat einen fairen Mindestlohn verlangte.",
     "خلال الحدث الكبير فحصت الإدارة كل مسؤولية قانونية، بينما طالب مجلس الإدارة الملتزم بحد أدنى عادل للأجور.",
     ["das Ereignis", "die Haftung", "der Betriebsrat", "der Mindestlohn"],
     ["arbeit", "betrieb"]),

    ("A2",
     "Durch moderne Dämmung und saubere Sonnenenergie spart das Haus Heizkosten, während Bewohner den Müll in jede Tonne trennen und Plastik wiederverwenden.",
     "من خلال العزل الحديث والطاقة الشمسية النظيفة يوفر المنزل تكاليف التدفئة، بينما يفصل السكان القمامة في كل حاوية ويعيدون استخدام البلاستيك.",
     ["die Sonnenenergie", "die Dämmung", "die Tonne", "wiederverwenden"],
     ["umwelt", "wohnen"]),

    ("A2",
     "An der lauten Hauptstraße schützt ein neuer Lärmschutz das Wohngebiet, wo sauberes Trinkwasser fließt und der Bauer frisches Gemüse anbietet.",
     "على الشارع الرئيسي الصاخب يحمي عازل ضوضاء جديد المنطقة السكنية، حيث تتدفق مياه شرب نظيفة ويعرض المزارع خضروات طازجة.",
     ["der Lärmschutz", "das Trinkwasser", "der Bauer"],
     ["stadt", "umwelt"]),

    ("A2",
     "Wer regional und saisonal einkauft, kann aktiv zum Klimaschutz beitragen und heimische Betriebe stärken.",
     "من يتسوق محلياً وبحسب الموسم، يمكنه المساهمة بفعالية في حماية المناخ ودعم المنشآت المحلية.",
     ["regional", "saisonal", "der Klimaschutz", "beitragen zu"],
     ["einkauf", "umwelt"]),

    ("A2",
     "Zusammengefasst war die Wanderung anstrengend, aber glücklicherweise blieb das Wetter trocken und die Luft angenehm kräftig.",
     "خلاصة القول، كانت جولة السير شاقة، ولكن لحسن الحظ ظل الطقس جافاً والهواء منعشاً وقوياً بشكل لطيف.",
     ["Zusammengefasst", "Glücklicherweise", "kräftig"],
     ["natur", "reisen"]),

    ("A2",
     "Vor dem Spiegel will die Schwester lockige Haare glatt kämmen und das festliche Kleid mit großer Freude anprobieren.",
     "أمام المرآة تريد الأخت تمشيط الشعر المجعد حتى يستوي أملس وتجربة الفستان الاحتفالي بفرحة كبيرة.",
     ["glatt", "lockig", "anprobieren"],
     ["kleidung", "alltag"]),

    ("A2",
     "Im Museum bewunderten Besucher ein wertvolles Kunstwerk, kauften eine Eintrittskarte und studierten den Anhang im Informationsheft.",
     "في المتحف أعجب الزوار بعمل فني قيم، واشتروا تذكرة دخول ودرسوا الملحق في كتيب المعلومات.",
     ["das Kunstwerk", "die Eintrittskarte", "der Anhang"],
     ["kultur", "freizeit"]),

    ("A2",
     "Auf dem Weg zur Sprachschule musste der Student tanken, schaltete das Navigationsgerät ein und durfte trotz Stau niemals aufgeben.",
     "في الطريق إلى مدرسة اللغات اضطر الطالب للتزود بالوقود، وشغل جهاز الملاحة ولم يجز له الاستسلام أبداً رغم الازدحام.",
     ["die Sprachschule", "aufgeben", "das Navigationsgerät", "tanken"],
     ["lernen", "unterwegs"]),

    ("A2",
     "Nach dem gemeldeten Schadensfall zahlte die Versicherung ohne Selbstbeteiligung, sodass Versicherte keinen Widerspruch einlegen und jeden Anspruch genau prüfen konnten.",
     "بعد حالة الضرر المبلغ عنها دفعت شركة التأمين دون نسبة تحمل، حتى لم يضطر المؤمن عليهم لتقديم اعتراض وتمكنوا من فحص كل استحقاق بدقة.",
     ["der Schadensfall", "die Selbstbeteiligung", "Widerspruch einlegen", "der Anspruch prüfen"],
     ["versicherung", "recht"]),

    # === B1 (18 Saetze) ===
    ("B1",
     "Wer trotz Rückschlag dranbleiben kann, darf bei einer Eröffnung entgegen den Erwartungen hoffen, dass der Eintritt frei bleibt.",
     "من يستطيع مواصلة المحاولة رغم الانتكاسة، يمكنه أن يأمل في الافتتاح، على عكس التوقعات، أن يظل الدخول مجانياً.",
     ["dranbleiben trotz Rückschlag", "der Eintritt frei", "entgegen"],
     ["alltag", "kultur"]),

    ("B1",
     "Die fortschreitende Digitalisierung im Alltag erfordert moderne Online-Banking-Apps und eine verlässliche Zwei-Faktor-Authentifizierung für sichere Überweisungen.",
     "يتطلب التحول الرقمي المتزايد في الحياة اليومية تطبيقات بنكية حديثة عبر الإنترنت ومصادقة ثنائية موثوقة للتحويلات الآمنة.",
     ["die Digitalisierung im Alltag", "die Online-Banking-App", "die Zwei-Faktor-Authentifizierung"],
     ["digital", "finanzen"]),

    ("B1",
     "Um sich vor Phishing-Mails zu schützen, sollten Computernutzer unseriöse Cookies ablehnen und sich bei Unklarheiten bei Fachleuten erkundigen.",
     "لحماية النفس من رسائل التصيد الاحتيالي، يجب على مستخدمي الحاسوب رفض ملفات تعريف الارتباط غير الموثوقة والاستفسار لدى المتخصصين عند وجود غموض.",
     ["die Phishing-Mail", "die Cookies ablehnen", "sich erkundigen nach"],
     ["digital", "sicherheit"]),

    ("B1",
     "Im Rahmen der Klimaanpassung beobachten Forscher den fallenden Wasserstand der Flüsse, die extreme Trockenheit und die bedrohte Artenvielfalt.",
     "في سياق التكيف مع المناخ، يراقب الباحثون انخفاض منسوب مياه الأنهار والجفاف الشديد والتنوع البيولوجي المهدد.",
     ["die Klimaanpassung", "die Trockenheit", "der Wasserstand", "die Artenvielfalt"],
     ["klima", "umwelt"]),

    ("B1",
     "Ein starker Umweltschutzverband fordert die gezielte Aufforstung heimischer Wälder, um den natürlichen Lebensraum seltener Tierarten dauerhaft zu bewahren.",
     "تطالب جمعية قوية لحماية البيئة بإعادة تشجير موجهة للغابات المحلية للحفاظ الدائم على الموطن الطبيعي لأنواع الحيوانات النادرة.",
     ["der Lebensraum", "die Aufforstung", "der Umweltschutzverband"],
     ["umwelt", "tierschutz"]),

    ("B1",
     "In der Selbsthilfegruppe lernen die Mitglieder eine beruhigende Achtsamkeitsübung sowie eine wirksame Dehnübung zur Linderung von Rückenschmerzen.",
     "في مجموعة المساعدة الذاتية يتعلم الأعضاء تمريناً مهدئاً لليقظة الذهنية بالإضافة إلى تمرين إطالة فعال لتخفيف آلام الظهر.",
     ["die Dehnübung", "die Selbsthilfegruppe", "die Achtsamkeitsübung"],
     ["gesundheit", "sport"]),

    ("B1",
     "Eine benutzerfreundliche Software sollte zugleich pflegeleicht und zeitaufwendig beim Entwickeln sein, damit kostenbewusste Kunden zufrieden sind.",
     "يجب أن يكون البرنامج سهل الاستخدام وسهل الصيانة ومكثفاً في الوقت أثناء التطوير، حتى يرضى العملاء الواعون بالتكاليف.",
     ["kostenbewusst", "zeitaufwendig", "pflegeleicht", "benutzerfreundlich"],
     ["technik", "wirtschaft"]),

    ("B1",
     "Die verkehrsgünstige Wohnsiedlung ist besonders kinderfreundlich gestaltet, sodass auch eine einkommensschwache Familie dort ohne arbeitsintensive Renovierung leben kann.",
     "تم تصميم المجمع السكني المتميز بموقع مناسب للمرور ليكون ملائماً للأطفال بشكل خاص، حتى تتمكن عائلة منخفضة الدخل من العيش هناك دون تجديد مكثف للعمل.",
     ["kinderfreundlich", "verkehrsgünstig", "einkommensschwach", "arbeitsintensiv"],
     ["wohnen", "familie"]),

    ("B1",
     "Für die krisenfeste Firmenleitung sind teamfähige und lernbereite Mitarbeiter besonders wertvoll, die auch unter Zeitdruck stressresistent bleiben.",
     "بالنسبة لإدارة الشركة المقاومة للأزمات، فإن الموظفين القادرين على العمل الجماعي والمستعدين للتعلم ذوو قيمة خاصة، والذين يظلون مقاومين للتوتر تحت ضغط الوقت.",
     ["krisenfest", "lernbereit", "teamfähig", "stressresistent"],
     ["arbeit", "charakter"]),

    ("B1",
     "Eine lange Dürreperiode erfordert sparsamen Wasserverbrauch, während stabiler Hochwasserschutz verhindert, dass einseitige Berichte über Unwetter Panik schüren.",
     "تتطلب فترة الجفاف الطويلة استهلاكاً مقتصداً للمياه، بينما يمنع نظام الحماية المستقر من الفيضانات أن تثير التقارير أحادية الجانب حول العواصف حالة من الهلع.",
     ["die Dürreperiode", "der Hochwasserschutz", "einseitig"],
     ["klima", "medien"]),

    ("B1",
     "Journalisten müssen jede reißerische Schlagzeile prüfen, jede Leserzuschrift ernst nehmen und eine unfaire Verallgemeinerung beim Einzelfall vermeiden.",
     "يجب على الصحفيين فحص كل عنوان رئيسي مثير، وأخذ كل رسالة من القراء على محمل الجد وتجنب التعميم غير العادل عند تناول حالة فردية.",
     ["die Schlagzeile prüfen", "die Leserzuschrift", "die Verallgemeinerung", "der Einzelfall"],
     ["medien", "gesellschaft"]),

    ("B1",
     "Wenn Koffer und Gepäck verloren gehen, hilft die Reiserücktrittsversicherung, sodass Reisende ihren Notfallkontakt anrufen oder die Botschaft kontaktieren.",
     "عندما تفقد الحقائب والأمتعة، تساعد تأمينات إلغاء السفر، بحيث يتصل المسافرون بجهة الاتصال للطوارئ أو يتواصلون مع السفارة.",
     ["die Reiserücktrittsversicherung", "das Gepäck verloren gehen", "die Botschaft kontaktieren", "der Notfallkontakt"],
     ["reise", "sicherheit"]),

    ("B1",
     "Wer sich mit Verträgen gut auskennen kann, muss nicht für fremde Schäden aufkommen, wenn sie sich als ungerechtfertigt herausstellen.",
     "من يستطيع الإلمام بالعقود جيداً، لا يضطر لتحمل الأضرار عن الآخرين إذا تبين أنها غير مبررة.",
     ["sich auskennen mit", "aufkommen für", "sich herausstellen als"],
     ["recht", "alltag"]),

    ("B1",
     "Die Kanzlei musste auf externe Gutachten zurückgreifen, durfte die Richtigstellung nicht länger hinauszögern und verzeichnete einen plötzlichen Reiseabbruch.",
     "اضطر مكتب المحاماة إلى الاستعانة بتقارير خبراء خارجيين، ولم يعد بإمكانه تأخير التصحيح وسجل إلغاءً مفاجئاً لرحلة عمل.",
     ["zurückgreifen auf", "hinauszögern", "die Richtigstellung", "der Reiseabbruch"],
     ["recht", "arbeit"]),

    ("B1",
     "Der Anwalt verlangte sofortige Akteneinsicht, begründete den gesetzlichen Rechtsanspruch und las die ausführliche Rechtsmittelbelehrung des Gerichtsbescheids.",
     "طلب المحامي الاطلاع الفوري على الملفات، وعلل الحق القانوني وقرأ التوجيهات المفصلة حول الطعون القانونية في قرار المحكمة.",
     ["die Akteneinsicht", "der Rechtsanspruch", "die Rechtsmittelbelehrung"],
     ["recht", "behoerde"]),

    ("B1",
     "Die Behörde wollte keine Ausnahme genehmigen, weshalb der Nachbar eine offizielle Einsprache einlegte, bevor Richter das Verfahren einstellen konnten.",
     "لم ترغب الهيئة في الموافقة على أي استثناء، ولهذا السبب قدم الجار اعتراضاً رسمياً قبل أن يتمكن القضاة من حفظ الدعوى.",
     ["die Ausnahme genehmigen", "die Einsprache", "das Verfahren einstellen"],
     ["behoerde", "recht"]),

    ("B1",
     "In einem traditionsreichen Handwerksbetrieb erlernt jeder motivierte Lehrling das Handwerk von Grund auf, bis er die schwere Meisterprüfung besteht.",
     "في ورشة حرفية عريقة يتعلم كل متدرب متحمس الحرفة من الصفر، حتى يجتاز امتحان الأستاذية الحرفية الصعب.",
     ["der Handwerksbetrieb", "der Lehrling", "die Meisterprüfung"],
     ["handwerk", "ausbildung"]),

    ("B1",
     "Mit der lauten Bohrmaschine reparierte der Handwerker die Wand, weil der Wasserhahn tropft und er jede alte Dichtung wechseln musste.",
     "بالمثقاب الكهربائي الصاخب أصلح الحرفي الجدار، لأن صنبور الماء يقطر واضطر لتغيير كل سدادة قديمة.",
     ["die Bohrmaschine", "der Wasserhahn tropft", "die Dichtung wechseln"],
     ["haushalt", "handwerk"]),

    # === B2 (16 Saetze) ===
    ("B2",
     "Im modernen Online-Handel entlastet flexible Arbeitszeit die Work-Life-Balance der Mitarbeiter, ohne dass Händler ihre Gutscheine entwerten.",
     "في التجارة الإلكترونية الحديثة تخفف ساعات العمل المرنة التوازن بين العمل والحياة للموظفين، دون أن يقوم التجار بإلغاء صلاحية قسائمهم.",
     ["der Online-Handel", "die Work-Life-Balance", "entwerten"],
     ["digital", "arbeit"]),

    ("B2",
     "Das novellierte Erneuerbare-Energien-Gesetz legt einen wirksamen CO2-Preis fest, sodass Stadtwerke emissionsarme Kraftwerke zügig hochfahren.",
     "يحدد قانون مصادر الطاقة المتجددة المعدل سعراً فعالاً لثاني أكسيد الكربون، حتى تقوم مرافق المدينة بتشغيل محطات توليد منخفضة الانبعاثات بسرعة.",
     ["das Erneuerbare-Energien-Gesetz", "der CO2-Preis", "hochfahren"],
     ["energie", "politik"]),

    ("B2",
     "Ein übersichtlicher Nutri-Score sowie eine transparente Herkunftsangabe schützen Konsumenten vor der verwirrenden Siegelflut und versteckten E-Nummern.",
     "يحمي نظام تصنيف القيمة الغذائية الواضح والبيان الشفاف لبلد المنشأ المستهلكين من فيضان أختام الجودة المربك وأرقام المضافات المشفرة المخفية.",
     ["der Nutri-Score", "die E-Nummer", "die Herkunftsangabe", "die Siegelflut"],
     ["ernaehrung", "verbraucher"]),

    ("B2",
     "Gegen dreiste Preistreiberei und anhaltende Lebensmittelinflation schreitet das Bundeskartellamt ein und setzt eine strikte Kennzeichnungspflicht durch.",
     "ضد المغالاة الوقحة في الأسعار وتضخم أسعار الأغذية المستمر يتدخل المكتب الاتحادي لمكافحة الاحتكار ويفرض إلزامية وضع العلامات الصارمة.",
     ["die Preistreiberei", "das Bundeskartellamt", "die Lebensmittelinflation", "die Kennzeichnungspflicht"],
     ["wirtschaft", "verbraucher"]),

    ("B2",
     "Nach einer behördlichen Rückrufaktion veranlasste der Hersteller einen sofortigen Rückruf, während Verbraucherschützer eine Musterfeststellungsklage vorbereiteten und Testkäufe durchführten.",
     "عقب حملة سحب رسمية للمنتجات أمرت الشركة المصنعة بسحب فوري، بينما أعد حماة المستهلك دعوى إثبات جماعية وأجروا عمليات شراء تجريبية.",
     ["die Rückrufaktion", "der Rückruf", "die Musterfeststellungsklage", "der Testkauf"],
     ["verbraucher", "recht"]),

    ("B2",
     "Die beliebte Eigenmarke reduzierte jede Portionsgröße und senkte den Zuckergehalt, um der süßen Verlockung bei Kindern entgegenzuwirken.",
     "قللت العلامة التجارية الخاصة المحبوبة حجم كل حصة وخفضت محتوى السكر للحد من الإغراء الحلو لدى الأطفال.",
     ["die Eigenmarke", "die Portionsgröße", "der Zuckergehalt", "die Verlockung"],
     ["ernaehrung", "gesundheit"]),

    ("B2",
     "Supermärkte müssen gefährliche Waren zurückrufen, wenn leicht verderbliche Lebensmittel mit Gift belastet sind oder verbraucherfeindlich deklariert wurden.",
     "يجب على المتاجر استدعاء البضائع الخطرة عندما تكون الأغذية سريعة التلف ملوثة بالسموم أو معلنة بطريقة معادية للمستهلك.",
     ["zurückrufen", "verderblich", "verbraucherfeindlich", "das Gift"],
     ["verbraucher", "wirtschaft"]),

    ("B2",
     "In der nachhaltigen Stadtplanung weist der Flächennutzungsplan neue Zonen aus, während eine Milieuschutzsatzung die kommunale Wohnraumförderung absichert.",
     "في التخطيط الحضري المستدام يحدد مخطط استخدام الأراضي مناطق جديدة، بينما يؤمن قانون حماية النسيج الاجتماعي تعزيز الإسكان البلدي.",
     ["die Stadtplanung", "der Flächennutzungsplan", "die Milieuschutzsatzung", "die Wohnraumförderung"],
     ["stadt", "wohnen"]),

    ("B2",
     "Um die historische Skyline vor Denkmalschutz zu bewahren, erfordert der Geschosswohnungsbau eine behördliche Planfeststellung mit Bürgerbeteiligung.",
     "للحفاظ على الأفق التاريخي للمدينة وفق حماية المعالم التراثية، يتطلب بناء المساكن متعددة الطوابق تحديد خطة رسمياً بمشاركة المواطنين.",
     ["der Geschosswohnungsbau", "die Skyline", "der Denkmalschutz", "die Planfeststellung"],
     ["stadt", "kultur"]),

    ("B2",
     "Ein kommunaler Hitzeaktionsplan verwandelt die Metropole in eine kühlende Schwammstadt, um die Abwanderung junger Familien in die Kleinstadt zu stoppen.",
     "تحول خطة العمل البلدية لمواجهة موجات الحر المدينة الكبرى إلى مدينة إسفنجية ملطفة للحرارة، لوقف هجرة العائلات الشابة إلى البلدة الصغيرة.",
     ["der Hitzeaktionsplan", "die Schwammstadt", "die Abwanderung", "die Kleinstadt"],
     ["stadt", "klima"]),

    ("B2",
     "Gegen das wachsende Stadt-Land-Gefälle helfen eine durchdachte Verkehrsberuhigung, gerechte Parkraumbewirtschaftung und eine weitläufige autofreie Zone.",
     "ضد الفجوة المتزايدة بين المدينة والريف تساعد تهدئة مدروسة لحركة المرور، وإدارة عادلة لمواقف السيارات ومنطقة فسيحة خالية من السيارات.",
     ["das Stadt-Land-Gefälle", "die Verkehrsberuhigung", "die Parkraumbewirtschaftung", "die autofreie Zone"],
     ["verkehr", "stadt"]),

    ("B2",
     "Erfolgreiches Quartiersmanagement verhinderte die illegale Hausbesetzung, während Eigentümer die Modernisierungsumlage einhielten und eine Belegungsbindung garantierten.",
     "منعت الإدارة الناجحة للأحياء السكنية الاستيلاء غير القانوني على المنازل، بينما التزم المالكون بضريبة التحديث وضمنوا التزاماً بشغل المساكن لفئات مستحقة.",
     ["das Quartiersmanagement", "die Hausbesetzung", "die Modernisierungsumlage", "die Belegungsbindung"],
     ["wohnen", "stadt"]),

    ("B2",
     "Für eine flächensparende Neubausiedlung schafft das Fachkräfteeinwanderungsgesetz die Grundlage, um qualifizierte Bauarbeiter ins Land zu holen.",
     "من أجل مجمع سكني جديد موفر للمساحات يضع قانون هجرة الكفاءات الأساس لجلب عمال بناء مؤهلين إلى البلاد.",
     ["flächensparend", "die Neubausiedlung", "das Fachkräfteeinwanderungsgesetz"],
     ["bauen", "migration"]),

    ("B2",
     "Ein transparentes Punktesystem regelt die Zuwanderung, während ein obligatorischer Wertekurs die Optionspflicht und die Fluchtursache behandelt.",
     "ينظم نظام النقاط الشفاف الهجرة، بينما يتناول مسار تدريب القيم الإلزامي واجب الاختيار وأسباب اللجوء والفرار.",
     ["das Punktesystem", "der Wertekurs", "die Optionspflicht", "die Fluchtursache"],
     ["migration", "gesellschaft"]),

    ("B2",
     "In der Asylunterkunft erleichtert dezentrale Unterbringung die Integration, während die Residenzpflicht gilt und professionelle Sprachmittlung hilft.",
     "في دار إيواء طالبي اللجوء يسهل السكن اللامركزي الاندماج، بينما يسري واجب الإقامة وتساعد الترجمة اللغوية المتخصصة.",
     ["die Asylunterkunft", "die dezentrale Unterbringung", "die Residenzpflicht", "die Sprachmittlung"],
     ["migration", "verwaltung"]),

    ("B2",
     "Eine breite Sensibilisierung der Bürger verhindert die Entstehung einer Parallelgesellschaft und überwindet starre Leitkulturdebatten durch faire Quotelung.",
     "يمنع التوعية الواسعة للمواطنين نشوء مجتمع موازٍ ويتجاوز نقاشات الثقافة المهيمنة الجامدة عبر نظام حصص عادل.",
     ["die Sensibilisierung", "die Leitkultur", "die Parallelgesellschaft", "die Quotelung"],
     ["gesellschaft", "politik"])
]
