# -*- coding: utf-8 -*-
"""Batch 8: 15 A2-Uebungssaetze zur Waisen-Aufloesung (>=3 Waisen je Satz, K76c/K81f)."""

S = [
    ("A2", "Vor dem Abflug zum fernen Reiseziel passierte die Familie die Grenzkontrolle und buchte im Hotel die volle Verpflegung.", "قبل الإقلاع إلى وجهة السفر البعيدة، مرت الأسرة بنقطة مراقبة الحدود وحجزت في الفندق الإعاشة الكاملة.", ["der Abflug", "das Reiseziel", "die Grenzkontrolle", "die Verpflegung"], ["reisen", "urlaub"]),
    ("A2", "An der Rezeption erkundigten sich Touristen nach einer Stadtrundfahrt und kauften eine günstige Reiseversicherung für das Ausflugsziel.", "عند الاستقبال، استفسر السياح عن جولة في المدينة واشتروا تأمين سفر مناسباً لوجهة النزهة.", ["die Rezeption", "die Rundfahrt", "die Reiseversicherung", "das Ausflugsziel"], ["reisen", "urlaub"]),
    ("A2", "Im sozialen Netzwerk teilen Jugendliche interessante Beiträge, kommentieren Fotos und warnen vor jedem falschen Gerücht.", "في الشبكة الاجتماعية يشارك الشباب منشورات ممتعة، ويعلقون على الصور ويحذرون من كل شائعة كاذبة.", ["das soziale Netzwerk", "der Beitrag", "kommentieren", "das Gerücht"], ["medien", "digital"]),
    ("A2", "Die bekannte Zeitschrift will neue Berichte veröffentlichen und stellt eine wöchentliche Sendung im Radio vor.", "تريد المجلة المعروفة نشر تقارير جديدة وتقدم برنامجاً أسبوعياً في الإذاعة.", ["die Zeitschrift", "veröffentlichen", "die Sendung"], ["medien", "kultur"]),
    ("A2", "In der Grundschule beginnt der tägliche Unterricht pünktlich, wobei die Lehrerin großen Wert auf Zuverlässigkeit legt.", "في المدرسة الابتدائية تبدأ الحصة اليومية في الموعد المحدد، حيث تولي المعلمة أهمية كبيرة للموثوقية.", ["die Grundschule", "der Unterricht", "die Zuverlässigkeit"], ["schule", "bildung"]),
    ("A2", "Gute Freunde müssen gegenseitige Rücksichtnahme zeigen, die Verantwortung teilen und können sich aufeinander verlassen.", "يجب على الأصدقاء الجيدين إظهار مراعاة متبادلة، وتقاسم المسؤولية وأن يعتمدوا على بعضهم البعض.", ["die Rücksichtnahme", "die Verantwortung teilen", "sich verlassen auf"], ["beziehung", "freunde"]),
    ("A2", "Bei der schwierigen Wohnungssuche auf dem Wohnungsmarkt half der Familie eine hilfsbereite Genossenschaft.", "في البحث الشاق عن سكن في سوق السكن، ساعدت الأسرة تعاونية سكنية متعاونة.", ["die Wohnungssuche", "der Wohnungsmarkt", "die Genossenschaft"], ["wohnen", "alltag"]),
    ("A2", "Bevor Mieter ausziehen, müssen sie jedes Zimmer streichen und die Bedingungen für ihre Hausratversicherung prüfen.", "قبل أن يخلي المستأجرون السكن، يجب عليهم دهان الغرف وفحص شروط تأمين محتويات المنزل.", ["ausziehen aus", "streichen", "die Hausratversicherung"], ["wohnen", "umzug"]),
    ("A2", "Im gepflegten Treppenhaus treffen Nachbarn einander im Hausflur und regeln gemeinsam die wöchentliche Treppenreinigung.", "في بيت الدرج المرتب، يلتقي الجيران في بهو العمارة وينظمون معاً تنظيف الدرج الأسبوعي.", ["das Treppenhaus", "der Hausflur", "die Treppenreinigung"], ["wohnen", "nachbarschaft"]),
    ("A2", "Ein regelmäßiges Sparen schützt das Sparbuch, sodass man kein Geld verschwenden und das Konto nicht überziehen muss.", "يحمي التوفير المنتظم دفتر التوفير، حتى لا يبذر المرء مالاً ولا يضطر لتجاوز الرصيد في الحساب.", ["das Sparbuch", "verschwenden", "überziehen"], ["finanzen", "alltag"]),
    ("A2", "Gegen chronischen Schlafmangel helfen ruhige Atemübungen, um sich abends im Bett vollkommen zu entspannen.", "ضد قلة النوم المزمنة تساعد تمارين التنفس الهادئة للاسترخاء التام في الفراش مساءً.", ["der Schlafmangel", "die Atemübung", "entspannen"], ["gesundheit", "alltag"]),
    ("A2", "Vor der Mahlzeit muss man Geschirr abwaschen, das Essen in der Mikrowelle erwärmen und auf guten Geschmack achten.", "قبل الوجبة، يجب غسل الصحون وتسخين الطعام في الميكروويف والحرص على مذاق طيب.", ["abwaschen", "die Mikrowelle", "der Geschmack"], ["kueche", "alltag"]),
    ("A2", "Um einen gesunden Vorrat haltbar zu lagern und nicht zu verderben, sollte man frische Lebensmittel zügig einfrieren.", "لتخزين مؤونة صحية صالحة للحفظ وتجنب فسادها، ينبغي تجميد الأغذية الطازجة بسرعة.", ["der Vorrat", "haltbar", "verderben", "einfrieren"], ["kueche", "ernaehrung"]),
    ("A2", "Nach dem Einkauf nach Einkaufszettel muss man gefrorenes Fleisch auftauen und auf dem Blech gut abtropfen lassen.", "بعد التسوق وفق قائمة المشتريات، يجب إذابة اللحم المجمد وتركه يتصفى جيداً على الصينية.", ["der Einkaufszettel", "auftauen", "das Blech", "abtropfen lassen"], ["kueche", "kochen"]),
    ("A2", "Zu Weihnachten backte die Großmutter ein schmackhaftes Gebäck, sodass alle Gäste am Festtisch schnell satt wurden.", "في عيد الميلاد المجيد خبزت الجدة معجنات شهية، حتى شبع جميع الضوف عند مائدة العيد بسرعة.", ["das Weihnachten", "schmackhaft", "satt werden"], ["feste", "familie"])
]
