# -*- coding: utf-8 -*-
"""19 A2 Uebungssaetze aus verwaisten Karten (>=3 Waisen je Satz, Level-Wortschatz A2). Kein Audio (neu)."""
S = [
("A2", "Wenn du Schmerzen im Bauch hast, empfehle ich einen Arztbesuch, damit du ein besseres Gefühl hast.", "إذا كنت تشعر بألم في البطن، فإنني أوصي بزيارة الطبيب لكي تشعر بتحسن.", ["der Bauch", "empfehlen", "das Gefühl"], ["gesundheit", "ratschlag"]),
("A2", "Nach unserer Anfrage haben wir die Reservierung bestätigt, um die lange Warteschlange am Eingang zu vermeiden.", "بعد استفسارنا أكدنا الحجز لتجنب طابور الانتظار الطويل عند المدخل.", ["die Anfrage", "die Reservierung", "die Warteschlange"], ["reisen", "termin"]),
("A2", "Ich schreibe eine Einkaufsliste auf Papier aus der Zeitung und achte immer auf gute Qualität beim Einkaufen.", "أكتب قائمة تسوق على ورقة من الجريدة وأحرص دائماً على الجودة الجيدة عند التسوق.", ["die Einkaufsliste", "die Zeitung", "die Qualität"], ["einkaufen"]),
("A2", "Ich muss heute mein Zimmer aufräumen, denn ich habe die feste Absicht, diese wichtige Aufgabe zu erledigen.", "يجب أن أرتب غرفتي اليوم، لأن لدي النية المؤكدة لإنجاز هذه المهمة الهامة.", ["aufräumen", "die Absicht", "die Aufgabe"], ["haushalt", "plan"]),
("A2", "Die Polizei muss gut aufpassen, denn wer absichtlich ein Feuer legt, kommt für viele Jahre ins Gefängnis.", "يجب على الشرطة أن تحترس جيداً، لأن من يشعل ناراً عمداً يدخل السجن لسنوات عديدة.", ["aufpassen", "das Feuer", "das Gefängnis"], ["sicherheit", "recht"]),
("A2", "Wir sitzen unter der dunklen Wolke, führen eine lange Unterhaltung und bedanken uns für den schönen Nachmittag.", "نجلس تحت السحابة المظلمة، ونجري محادثة طويلة ونشكر على فترة بعد الظهر الجميلة.", ["die Wolke", "die Unterhaltung", "sich bedanken"], ["wetter", "soziales"]),
("A2", "Deine Worte bedeuten mir viel, und ich verspreche dir, jede gute Gelegenheit zum Lernen zu nutzen.", "كلماتك تعني لي الكثير، وأنا أعدك باستغلال كل فرصة جيدة للتعلم.", ["bedeuten", "versprechen", "die Gelegenheit"], ["beziehung", 'lernen']),
("A2", "Der Zweck dieser neuen Erfindung ist einfach, aber ihre positive Wirkung auf den Alltag ist wirklich groß.", "الغرض من هذا الاختراع الجديد بسيط، لكن أثره الإيجابي على الحياة اليومية كبير حقاً.", ["der Zweck", "die Erfindung", "die Wirkung"], ["technik", "alltag"]),
("A2", "Sie können die Datei sicher herunterladen, aber nach der Nutzung sollten Sie das Dokument sofort löschen.", "يمكنك تنزيل الملف بأمان، لكن بعد الاستعمال ينبغي أن تحذف الوثيقة فوراً.", ["herunterladen", "die Nutzung", "löschen"], ["medien", "computer"]),
("A2", "Mit einer gesunden Ernährung kann man leicht abnehmen, ohne später wieder schnell an Gewicht zuzunehmen.", "من خلال التغذية الصحية يمكن للمرء أن ينقص وزنه بسهولة دون أن يزيد وزنه بسرعة لاحقاً.", ["die Ernährung", "abnehmen", "zunehmen"], ["gesundheit", "ernaehrung"]),
("A2", "Im Notfall fährt der Krankenwagen mit hoher Geschwindigkeit, und der Notarzt ist für schnelle Hilfe zuständig.", "في حالة الطوارئ تسير سيارة الإسعاف بسرعة عالية، وطبيب الطوارئ مختص بتقديم المساعدة السريعة.", ["der Notfall", "die Geschwindigkeit", "zuständig"], ["notfall", "rettung"]),
("A2", "Im Erdgeschoss befindet sich die technische Anlage, die für die Heizung im ganzen Haus sorgt.", "في الطابق الأرضي يوجد المرفق الفني الذي يوفّر التدفئة للبيت بأكمله.", ["das Erdgeschoss", "die Anlage", "die Heizung"], ["wohnen", "technik"]),
("A2", "Aus diesem wichtigen Anlass kann ich deinem Standpunkt gerne zustimmen, weil deine Erklärung logisch ist.", "بهذه المناسبة الهامة يمكنني بكل سرور أن أوافق على وجهة نظرك لأن شرحك منطقي.", ["der Anlass", "der Standpunkt", "zustimmen"], ["diskussion", "meinung"]),
("A2", "Dieses Beispiel zeigt das Problem: Einerseits wollen die Menschen reisen, jedoch fehlt ihnen oft das Geld.", "هذا المثال يوضح المشكلة: من جهة يريد الناس السفر، غير أن المال ينقصهم في كثير من الأحيان.", ["das Beispiel", "einerseits", "jedoch"], ["argumentation"]),
("A2", "Wegen der Kündigungsfrist bei der Arbeit organisieren wir die Kinderbetreuung gemeinsam durch aktive Nachbarschaftshilfe.", "بسبب مهلة إنهاء عقد العمل فإننا ننظم رعاية الأطفال معاً من خلال التعاون النشط بين الجيران.", ["die Kündigungsfrist", "die Kinderbetreuung", "die Nachbarschaftshilfe"], ["arbeit", "familie"]),
("A2", "Vor dem Kurs sollten Sie sich gut informieren, denn die Teilnahme ist mit einer festen Verpflichtung verbunden.", "قبل الدورة ينبغي أن تستعلم جيداً، لأن المشاركة ترتبط بالتزام مؤكد.", ["sich informieren", "die Teilnahme", "die Verpflichtung"], ["kurs", "verpflichtung"]),
("A2", "Im Restaurant war die Bedienung freundlich, die Auswahl an Gerichten groß, und für die Feier reichte eine kleine Anzahlung.", "في المطعم كانت الخدمة ودودة، وتشكيلة الأطباق كبيرة، وبالنسبة للحفل كفى عربون صغير.", ["die Bedienung", "die Auswahl", "die Anzahlung"], ["restaurant", "zahlung"]),
("A2", "Ein ehrlicher Charakter ist eine wertvolle Eigenschaft, weil Menschen einem solchen Freund ohne Zweifel vertrauen können.", "الطبع الصادق صفة ثمينة، لأن الناس يستطيعون أن يثقوا بصديق كهذا دون شك.", ["der Charakter", "die Eigenschaft", "vertrauen"], ["charakter", "freundschaft"]),
("A2", "Zur großen Hochzeit kamen viele Verwandte, und selbst der sture Onkel hat den ganzen Abend fröhlich gefeiert.", "إلى حفل الزفاف الكبير جاء أقارب كثيرون، وحتى العم العنيد احتفل مبتهجاً طوال الأمسية.", ["die Hochzeit", "der Verwandte", "stur"], ["familie", "feier"])
]
