# -*- coding: utf-8 -*-
"""5 neue B1-Kurztexte (t-b1-21..25) aus verwaisten B1-Karten (>=12 je Text). Fiktiv, ohne pruefbare Fakten."""
T = [
{"id":"t-b1-21","titleDe":"Der erste Monat in der Firma","titleAr":"الشهر الأول في الشركة",
 "waisen":["die Probezeit","der Arbeitsplatz","der Arbeitnehmer","die Einarbeitungszeit","die Zielvereinbarung","die Beförderung","die Karriere","die Qualifikation","der Werdegang","das Arbeitszeugnis","verhandeln","die Branche","die Teilzeitstelle","scheitern","das Netzwerk"],
 "de":"Als Hanan die Teilzeitstelle bekam, war sie erleichtert und nervös zugleich. Die Branche war neu für sie, und im Vorstellungsgespräch hatte sie ehrlich gesagt, dass ihre Qualifikation aus einem anderen Bereich kommt. Die Chefin hatte geantwortet, ein ungewöhnlicher Werdegang sei kein Nachteil, wenn man lernen will. Trotzdem: Die Probezeit dauert sechs Monate, und in dieser Zeit kann man scheitern.\n\nDie Einarbeitungszeit war gut organisiert. Ein Kollege zeigte ihr den Arbeitsplatz, die Programme und die Regeln, die nirgends geschrieben stehen: Wer die Kaffeemaschine leer macht, füllt sie wieder auf. Nach vier Wochen gab es ein erstes Gespräch. Statt Kritik bekam Hanan eine Zielvereinbarung: drei kleine Ziele bis zum Ende der Probezeit. Über ihre Arbeitszeit konnte sie sogar verhandeln, weil ihre Tochter nachmittags aus der Schule kommt.\n\nAn Karriere oder Beförderung denkt sie noch nicht. Wichtiger ist ihr, dass sie sich als Arbeitnehmerin ernst genommen fühlt. Ihr altes Arbeitszeugnis liegt im Schrank; das neue, sagt sie lachend, soll besser werden. Und das Netzwerk, das sie hier aufbaut, ist vielleicht wertvoller als jeder Titel.",
 "ar":"حنان حصلت على وظيفة بدوام جزئي في قطاع جديد عليها، وقالت بصراحة إن مؤهلها من مجال آخر؛ المديرة اعتبرت المسار غير المعتاد ميزة لمن يريد التعلّم. فترة التجربة ستة أشهر. التأهيل كان منظّماً، وبعد أربعة أسابيع تلقّت اتفاق أهداف بدل النقد، وتفاوضت على ساعات العمل بسبب ابنتها. لا تفكّر في الترقية الآن؛ الأهم أن تُؤخذ بجدّية كأجيرة، وشبكة العلاقات أثمن من أي لقب.",
 "questions":[
  {"type":"mc","promptDe":"Was sagte die Chefin über Hanans ungewöhnlichen Werdegang?","options":["Er ist kein Nachteil, wenn man lernen will.","Er ist ein Nachteil in dieser Branche.","Er verkürzt die Probezeit."],"answer":"Er ist kein Nachteil, wenn man lernen will.","explanationAr":"الدليل حرفياً: «ein ungewöhnlicher Werdegang sei kein Nachteil, wenn man lernen will». الفخّ 1: قلب المعنى. الفخّ 2: فترة التجربة ستة أشهر بلا تغيير."},
  {"type":"mc","promptDe":"Was bekam Hanan nach vier Wochen?","options":["eine Zielvereinbarung mit drei kleinen Zielen","Kritik an ihrer Arbeit","eine Beförderung"],"answer":"eine Zielvereinbarung mit drei kleinen Zielen","explanationAr":"الدليل حرفياً: «Statt Kritik bekam Hanan eine Zielvereinbarung: drei kleine Ziele». الفخّ 1: «Statt Kritik» ينفي النقد. الفخّ 2: الترقية لا تفكّر فيها بعد."},
  {"type":"truefalse","promptDe":"Hanan konnte über ihre Arbeitszeit verhandeln.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «Über ihre Arbeitszeit konnte sie sogar verhandeln»."},
  {"type":"fill","promptDe":"Die ___ dauert sechs Monate, und in dieser Zeit kann man scheitern.","answer":["Probezeit"],"explanationAr":"الدليل حرفياً: «Die Probezeit dauert sechs Monate»."}]},
{"id":"t-b1-22","titleDe":"Streit um den Balkon","titleAr":"خلاف حول الشرفة",
 "waisen":["der Balkon","einziehen","ausziehen","die Hausgemeinschaft","der Gemeinschaftsraum","die Reinigungspflicht","das Nachbarschaftsfest","die Auseinandersetzung","vermitteln","einlenken","die Versöhnung","verzeihen","vorwerfen","die Vereinbarung","akzeptieren"],
 "de":"Als Familie Kaya im Frühjahr einzog, freute sie sich vor allem auf den Balkon. Im Sommer stand dort jeden Abend der Grill. Der Nachbar unter ihnen, Herr Brandt, wohnt seit zwanzig Jahren im Haus und hatte noch nie einen Grill über seinem Schlafzimmerfenster. Nach drei Wochen kam der erste Zettel im Hausflur, nach fünf Wochen die erste laute Auseinandersetzung im Treppenhaus.\n\nHerr Brandt warf der Familie vor, keine Rücksicht zu nehmen. Frau Kaya warf ihm vor, er habe nie freundlich gefragt. Beide hatten recht, und beide wollten nicht einlenken. Die Hausgemeinschaft war gespalten: Die einen sagten, wer Ruhe will, soll aufs Dorf ziehen; die anderen fanden, neue Mieter müssten sich erst einmal anpassen.\n\nAm Ende vermittelte die älteste Bewohnerin des Hauses. Sie lud beide in den Gemeinschaftsraum ein und schlug eine einfache Vereinbarung vor: Grillen ja, aber nur freitags und samstags bis zehn Uhr, und die Reinigungspflicht für den Hof übernimmt in diesem Monat Familie Kaya. Herr Brandt akzeptierte. Frau Kaya musste zugeben, dass die Regel fair war. Ob man so etwas Versöhnung nennen kann, ist offen. Beim Nachbarschaftsfest im September saßen sie jedenfalls am selben Tisch, und niemand musste jemandem etwas verzeihen, weil niemand mehr davon sprach. Ausziehen will jetzt keiner.",
 "ar":"عائلة كايا انتقلت في الربيع وفرحت بالشرفة، وصار الشواء كل مساء فوق نافذة غرفة نوم الجار القديم السيد برانت؛ بعد أسابيع بدأت الرسائل ثم الخلاف الصاخب. كلٌّ اتّهم الآخر وكلاهما رفض التراجع، وانقسم سكان البناية. توسّطت أكبر ساكنة: اتفاق بسيط — شواء الجمعة والسبت حتى العاشرة، وتنظيف الفناء هذا الشهر على عائلة كايا. قبل الجار، واعترفت السيدة كايا بعدالة القاعدة. في مهرجان الجيران جلسوا على طاولة واحدة ولا أحد يريد الرحيل.",
 "questions":[
  {"type":"mc","promptDe":"Wer vermittelte am Ende zwischen den Nachbarn?","options":["die älteste Bewohnerin des Hauses","Herr Brandt","die neuen Mieter selbst"],"answer":"die älteste Bewohnerin des Hauses","explanationAr":"الدليل حرفياً: «Am Ende vermittelte die älteste Bewohnerin des Hauses». الفخّ 1: برانت طرف في الخلاف. الفخّ 2: المستأجرون الجدد طرف الخلاف."},
  {"type":"mc","promptDe":"Was gehört zur Vereinbarung?","options":["Grillen nur freitags und samstags bis zehn Uhr","Grillen jeden Abend bis zehn Uhr","Familie Kaya zieht aufs Dorf"],"answer":"Grillen nur freitags und samstags bis zehn Uhr","explanationAr":"الدليل حرفياً: «Grillen ja, aber nur freitags und samstags bis zehn Uhr». الفخّ 1: «jeden Abend» كان الوضع القديم. الفخّ 2: القرية كانت رأي بعض السكان."},
  {"type":"truefalse","promptDe":"Herr Brandt wohnt seit zwanzig Jahren im Haus.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «wohnt seit zwanzig Jahren im Haus»."},
  {"type":"fill","promptDe":"Beide hatten recht, und beide wollten nicht ___.","answer":["einlenken"],"explanationAr":"الدليل حرفياً: «beide wollten nicht einlenken» — einlenken = يتراجع/يلين في خلاف."}]},
{"id":"t-b1-23","titleDe":"Eine Nachricht, die nicht stimmte","titleAr":"خبر لم يكن صحيحاً",
 "waisen":["die Falschmeldung","verbreiten","der Journalist","die Tatsache","die Stellungnahme","die Recherche","behaupten","seriös","anonym","die Manipulation","zuspitzen","die Berichterstattung","einseitig","ausgewogen","die Gegenposition","die Quelle angeben"],
 "de":"Am Montagmorgen verbreitete sich in der Stadt eine Nachricht: Das Schwimmbad im Norden solle geschlossen werden. Die Meldung stand in einer Gruppe im Messenger, ohne Namen, ohne Datum, ohne Quelle. Bis zum Mittag hatten sie hunderte Menschen weitergeleitet, und am Nachmittag standen die ersten Eltern mit Plakaten vor dem Rathaus.\n\nEine junge Journalistin der Lokalzeitung wollte die Meldung nicht einfach übernehmen. Ihre Recherche dauerte zwei Stunden: ein Anruf bei der Stadt, ein Blick in die Sitzungsunterlagen, ein Gespräch mit dem Bademeister. Die Tatsache war viel kleiner als das Gerücht. Das Bad wird im Winter drei Wochen renoviert, mehr nicht. Die Stadt gab am Abend eine Stellungnahme ab, aber da war die Falschmeldung schon schneller gewesen als die Wahrheit.\n\nWer die Nachricht zuerst geschrieben hatte, blieb anonym. Vielleicht war es keine Manipulation, sondern nur ein Missverständnis, das jemand zugespitzt hatte. Die Journalistin schrieb einen Artikel, der beide Seiten zeigte: die Sorge der Eltern und die Antwort der Stadt. Ausgewogene Berichterstattung heißt nicht, dass beide recht haben. Sie heißt, dass man die Gegenposition ernst nimmt und jede Behauptung prüft, bevor man sie druckt. Seriös ist, wer die Quelle angibt, auch wenn das langsamer ist.",
 "ar":"انتشر خبر بلا اسم ولا مصدر: مسبح الشمال سيُغلق؛ خلال ساعات تجمّع الأهالي أمام البلدية. صحفية محلية لم تنقل الخبر بل بحثت ساعتين: اتصال بالبلدية، وثائق الجلسة، حديث مع منقذ المسبح. الحقيقة أصغر بكثير: ترميم ثلاثة أسابيع شتاءً. البلدية أصدرت بياناً مساءً لكن الخبر الكاذب كان أسرع. الكاتب بقي مجهولاً؛ ربما سوء فهم بولغ فيه لا تلاعباً. كتبت مقالاً يعرض الطرفين: التغطية المتوازنة لا تعني أن الطرفين على حق، بل أن كل ادّعاء يُفحص ويُذكر مصدره.",
 "questions":[
  {"type":"mc","promptDe":"Was war die Tatsache hinter dem Gerücht?","options":["Das Bad wird im Winter drei Wochen renoviert.","Das Bad im Norden wird geschlossen.","Die Eltern haben das Bad gerettet."],"answer":"Das Bad wird im Winter drei Wochen renoviert.","explanationAr":"الدليل حرفياً: «Das Bad wird im Winter drei Wochen renoviert, mehr nicht». الفخّ 1: الإغلاق هو الشائعة. الفخّ 2: احتجاج الأهالي لم يُنقذ شيئاً لأن الإغلاق لم يكن مقرّراً."},
  {"type":"mc","promptDe":"Was bedeutet laut Text ausgewogene Berichterstattung?","options":["die Gegenposition ernst nehmen und jede Behauptung prüfen","dass beide Seiten recht haben","die Meldung schnell weiterleiten"],"answer":"die Gegenposition ernst nehmen und jede Behauptung prüfen","explanationAr":"الدليل حرفياً: «heißt nicht, dass beide recht haben. Sie heißt, dass man die Gegenposition ernst nimmt und jede Behauptung prüft». الفخّ 1: منفيّ صراحة. الفخّ 2: إعادة الإرسال هي ما فعله الناس بالشائعة."},
  {"type":"truefalse","promptDe":"Die Person, die die Nachricht zuerst schrieb, ist bekannt.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل حرفياً: «Wer die Nachricht zuerst geschrieben hatte, blieb anonym»."},
  {"type":"fill","promptDe":"Die Stadt gab am Abend eine ___ ab.","answer":["Stellungnahme"],"explanationAr":"الدليل حرفياً: «Die Stadt gab am Abend eine Stellungnahme ab»."}]},
{"id":"t-b1-24","titleDe":"Gesund bleiben im Schichtdienst","titleAr":"البقاء بصحة في العمل بالمناوبات",
 "waisen":["die Vorsorgeuntersuchung","die Therapie","die Nebenwirkung","chronisch","das Immunsystem","die Belastbarkeit","das Gleichgewicht","die Ausdauer","die Ernährungsberatung","der Schlafrhythmus","die Regeneration","die Entspannungstechnik","der Muskelkater","vorbeugen","die Lebensweise","die Achtsamkeit"],
 "de":"Karim arbeitet seit vier Jahren im Schichtdienst in einer Bäckerei. Frühschicht ab drei Uhr, dann zwei Wochen Spätschicht, dann wieder früh. Sein Schlafrhythmus war irgendwann so durcheinander, dass er auch an freien Tagen um drei Uhr wach lag. Bei der Vorsorgeuntersuchung sagte der Arzt einen Satz, den Karim nicht vergessen hat: „Ihre Belastbarkeit ist nicht das Problem. Ihre Regeneration ist es.“\n\nEine Therapie mit Tabletten wollte Karim nicht, wegen der Nebenwirkungen und weil er nichts Chronisches hatte, nur eine ungesunde Lebensweise. Also änderte er drei Dinge. Er ging zur Ernährungsberatung, weil er nachts immer süß gegessen hatte. Er begann mit Ausdauer statt Kraft: dreimal pro Woche zwanzig Minuten laufen, langsam, ohne Muskelkater am nächsten Tag. Und er lernte eine Entspannungstechnik, die er im Bett anwendet, wenn der Kopf nicht aufhören will zu arbeiten.\n\nNach drei Monaten ist das Gleichgewicht nicht perfekt, aber besser. Sein Immunsystem scheint stabiler; die dritte Erkältung des Winters ist ausgeblieben. Das Wichtigste, sagt er, ist Achtsamkeit für kleine Signale: müde Augen, kurze Geduld, Hunger auf Zucker. Wer sie früh bemerkt, kann vorbeugen, statt später zu reparieren.",
 "ar":"كريم يعمل بالمناوبات في مخبز منذ أربع سنوات واضطرب إيقاع نومه حتى صار يستيقظ في الثالثة حتى في العطل. في الفحص الوقائي قال الطبيب: المشكلة ليست تحمّلك بل استشفاؤك. رفض العلاج بالأقراص بسبب آثارها الجانبية ولأن حالته ليست مزمنة بل نمط حياة. غيّر ثلاثة أشياء: استشارة تغذية، تمارين تحمل خفيفة ثلاث مرات أسبوعياً، وتقنية استرخاء في السرير. بعد ثلاثة أشهر توازنه أفضل ومناعته أثبت. الأهم: الانتباه للإشارات الصغيرة مبكراً للوقاية بدل الإصلاح.",
 "questions":[
  {"type":"mc","promptDe":"Was ist laut Arzt Karims Problem?","options":["seine Regeneration","seine Belastbarkeit","eine chronische Krankheit"],"answer":"seine Regeneration","explanationAr":"الدليل حرفياً: «Ihre Belastbarkeit ist nicht das Problem. Ihre Regeneration ist es». الفخّ 1: التحمل منفيّ صراحة. الفخّ 2: «nichts Chronisches»."},
  {"type":"mc","promptDe":"Warum wollte Karim keine Therapie mit Tabletten?","options":["wegen der Nebenwirkungen und weil er nichts Chronisches hatte","weil die Ernährungsberatung billiger war","weil der Arzt es verboten hatte"],"answer":"wegen der Nebenwirkungen und weil er nichts Chronisches hatte","explanationAr":"الدليل حرفياً: «wegen der Nebenwirkungen und weil er nichts Chronisches hatte». الفخّ 1: استشارة التغذية خطوة أخرى لا سبب. الفخّ 2: لا منع من الطبيب."},
  {"type":"truefalse","promptDe":"Karim läuft dreimal pro Woche zwanzig Minuten.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «dreimal pro Woche zwanzig Minuten laufen»."},
  {"type":"fill","promptDe":"Wer die Signale früh bemerkt, kann ___, statt später zu reparieren.","answer":["vorbeugen"],"explanationAr":"الدليل حرفياً: «Wer sie früh bemerkt, kann vorbeugen, statt später zu reparieren»."}]},
{"id":"t-b1-25","titleDe":"Mehr Grün, weniger Lärm","titleAr":"خضرة أكثر وضجيج أقل",
 "waisen":["die Bürgerinitiative","die Fußgängerzone","der Verkehrslärm","die Grünfläche","die Lebensqualität","die Infrastruktur","die Anbindung","die Baugenehmigung","die Zuständigkeit","der Gemeinderat","die Bürgersprechstunde","die Beschlussvorlage","die Auflage","abstimmen über","die Feinstaubbelastung","die Sanierung"],
 "de":"Die Bürgerinitiative „Mehr Grün“ entstand an einem Küchentisch. Fünf Nachbarn hatten genug vom Verkehrslärm auf der Hauptstraße und von der Feinstaubbelastung, die man an den grauen Fensterbänken sehen konnte. Ihr Vorschlag: Ein Teil der Straße wird Fußgängerzone, der alte Parkplatz wird Grünfläche mit Bäumen und Bänken.\n\nDer Weg dorthin war länger als gedacht. Zuerst war die Zuständigkeit unklar: Straße oder Grünflächen, zwei verschiedene Ämter. In der Bürgersprechstunde riet der Bürgermeister, eine Beschlussvorlage für den Gemeinderat zu schreiben, mit Zahlen zur Anbindung: Wie kommen die Leute dann zum Supermarkt, wo parken die Lieferwagen? Die Initiative besuchte drei Sitzungen, sammelte Unterschriften und rechnete die Sanierung des Parkplatzes mit einem Architekten durch.\n\nIm Herbst stimmte der Gemeinderat über die Vorlage ab: angenommen, mit zwei Auflagen. Die Lieferwagen dürfen morgens bis zehn Uhr in die Zone, und die Baugenehmigung für die Bänke bekommt die Stadt nur, wenn ein Weg für Rollstühle bleibt. Ob die Lebensqualität wirklich steigt, wird man erst im nächsten Sommer wissen. Dass fünf Leute die Infrastruktur einer ganzen Straße verändern können, wissen die Nachbarn jetzt schon.",
 "ar":"مبادرة أهلية «خضرة أكثر» بدأت على طاولة مطبخ: خمسة جيران سئموا ضجيج المرور والجسيمات الدقيقة، واقترحوا تحويل جزء من الشارع إلى منطقة مشاة والموقف القديم إلى مساحة خضراء. الطريق كان طويلاً: اختصاص غير واضح بين إدارتين، نصيحة في ساعة المواطنين بكتابة مقترح قرار لمجلس البلدية بأرقام عن الربط بالمواصلات، ثلاث جلسات، توقيعات، وحساب الترميم مع مهندس. في الخريف صوّت المجلس بالموافقة بشرطين: دخول سيارات التوصيل حتى العاشرة صباحاً، وممر للكراسي المتحركة.",
 "questions":[
  {"type":"mc","promptDe":"Was war zuerst unklar?","options":["die Zuständigkeit zwischen zwei Ämtern","die Zahl der Unterschriften","die Kosten der Bänke"],"answer":"die Zuständigkeit zwischen zwei Ämtern","explanationAr":"الدليل حرفياً: «Zuerst war die Zuständigkeit unklar: Straße oder Grünflächen, zwei verschiedene Ämter». الفخّ 1: التوقيعات جُمعت لاحقاً. الفخّ 2: الترميم حُسب مع مهندس."},
  {"type":"mc","promptDe":"Welche Auflage gehört zum Beschluss?","options":["Die Lieferwagen dürfen morgens bis zehn Uhr in die Zone.","Der Parkplatz bleibt für Lieferwagen.","Die Bänke brauchen keine Baugenehmigung."],"answer":"Die Lieferwagen dürfen morgens bis zehn Uhr in die Zone.","explanationAr":"الدليل حرفياً: «Die Lieferwagen dürfen morgens bis zehn Uhr in die Zone». الفخّ 1: الموقف يصير مساحة خضراء. الفخّ 2: الترخيص مشروط بممر الكراسي."},
  {"type":"truefalse","promptDe":"Der Gemeinderat hat die Vorlage abgelehnt.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل حرفياً: «angenommen, mit zwei Auflagen»."},
  {"type":"fill","promptDe":"In der ___ riet der Bürgermeister, eine Beschlussvorlage zu schreiben.","answer":["Bürgersprechstunde"],"explanationAr":"الدليل حرفياً: «In der Bürgersprechstunde riet der Bürgermeister»."}]},
]
