# -*- coding: utf-8 -*-
"""5 neue B2-Kurztexte (t-b2-21..25) aus verwaisten B2-Karten (>=12 je Text). Fiktiv, ohne pruefbare Fakten. Kein Audio (neu)."""
T = [
{"id":"t-b2-21","titleDe":"Ein Missverständnis unter Freunden","titleAr":"سوء فهم بين صديقين",
 "waisen":["das Missverständnis","die Zuneigung","der Neid","gönnen","nachgeben","die Enttäuschung","das Verhältnis","die Kränkung","die Gelassenheit","das Selbstwertgefühl","das Mitgefühl","betrügen","enttäuschen"],
 "de":"Als Rami erfuhr, dass sein Freund Tarek die Stelle bekommen hatte, auf die sie sich beide beworben hatten, sagte er zuerst gar nichts. Später schrieb er eine kurze Nachricht: „Glückwunsch.“ Ohne Ausrufezeichen. Tarek las darin eine Kränkung und antwortete drei Tage lang nicht. So begann ein Missverständnis, das ihr Verhältnis fast beendet hätte.\n\nIn Wahrheit war Rami weder neidisch noch wütend. Er gönnte Tarek den Erfolg, aber die eigene Enttäuschung war an diesem Abend größer als seine Zuneigung. Das ist menschlich, und es wäre kein Problem gewesen, hätte er es einfach gesagt. Stattdessen schwieg er, und Schweigen lässt sich in jede Richtung deuten. Tarek dachte an Neid; seine Schwester vermutete sogar, Tarek habe ihn betrügen wollen, weil Tarek ihm nichts von dem Gespräch erzählt hatte.\n\nDass die beiden heute wieder zusammen Fußball spielen, liegt an einer einzigen Frage. Tarek rief an und fragte nicht „Warum bist du so?“, sondern „Wie geht es dir damit?“. Diese Frage zeigt Mitgefühl; man muss dafür weder nachgeben noch sich rechtfertigen. Rami konnte antworten, ohne sein Selbstwertgefühl zu verteidigen. Gelassenheit heißt nicht, nichts zu fühlen; sie heißt, das Gefühl zu benennen, bevor es den anderen enttäuscht.",
 "ar":"رامي وطارق تقدّما للوظيفة نفسها؛ حين فاز طارق أرسل رامي تهنئة جافّة، ففهمها طارق إهانة وصمت ثلاثة أيام. الحقيقة: رامي لم يحسد، لكن خيبته كانت أكبر من مودّته تلك الليلة، وصمته فُسّر حسداً وحتى ظنّاً بأن طارق أراد خداعه. أنقذت الصداقةَ مكالمةٌ بسؤال واحد يُظهر التعاطف: «كيف تشعر حيال ذلك؟» — الرزانة هي تسمية الشعور قبل أن يخيّب الآخر.",
 "questions":[
  {"type":"mc","promptDe":"Warum antwortete Tarek drei Tage lang nicht?","options":["Er las in der kurzen Nachricht eine Kränkung.","Er war neidisch auf Rami.","Er wollte Rami nichts von dem Gespräch erzählen."],"answer":"Er las in der kurzen Nachricht eine Kränkung.","explanationAr":"الدليل حرفياً: «Tarek las darin eine Kränkung und antwortete drei Tage lang nicht». الفخّ 1: الحسد ما ظنّه طارق برامي. الفخّ 2: عدم الإخبار عن المقابلة تفسير الأخت."},
  {"type":"mc","promptDe":"Was war laut Text an dem Abend größer als Ramis Zuneigung?","options":["seine eigene Enttäuschung","sein Neid","seine Wut"],"answer":"seine eigene Enttäuschung","explanationAr":"الدليل حرفياً: «die eigene Enttäuschung war an diesem Abend größer als seine Zuneigung». الفخّ: «weder neidisch noch wütend» منفيّان صراحة."},
  {"type":"truefalse","promptDe":"Tarek fragte am Telefon: „Warum bist du so?“","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل حرفياً: «fragte nicht „Warum bist du so?“, sondern „Wie geht es dir damit?“»."},
  {"type":"fill","promptDe":"Er ___ Tarek den Erfolg, aber die eigene Enttäuschung war größer.","answer":["gönnte"],"explanationAr":"الدليل حرفياً: «Er gönnte Tarek den Erfolg» — gönnen = يتمنّى الخير للآخر دون حسد، هنا في Präteritum."}]},
{"id":"t-b2-22","titleDe":"Zurück nach der Operation","titleAr":"العودة بعد العملية",
 "waisen":["operieren","die Genesung","die Krankschreibung","die Reha","die Vorsorge","die Bildschirmarbeit","das Arbeitsklima","süchtig","die Erkältung","das Umfeld","die Solidarität","dosieren","die Anstrengung"],
 "de":"Nach acht Wochen kehrt Frau Lang ins Büro zurück. Im Frühjahr wurde sie am Knie operiert, danach folgten drei Wochen Reha und eine lange Krankschreibung. Die Genesung verlief gut, sagt sie, aber sie hat etwas gelernt, das mit dem Knie wenig zu tun hat: Wie ein Umfeld auf Krankheit reagiert, sagt mehr über das Arbeitsklima als jede Umfrage.\n\nIhre Kolleginnen hatten in der Zeit ihre Aufgaben still übernommen. Niemand fragte, wann sie „endlich“ zurückkomme. Diese Solidarität war keine Selbstverständlichkeit; in ihrer früheren Firma galt schon eine Erkältung als Schwäche, und wer zur Vorsorge ging, tat das heimlich. Dort war sie, wie sie heute selbst sagt, fast süchtig nach Anerkennung gewesen und hatte jede Pause als verlorene Zeit empfunden.\n\nJetzt dosiert sie die Anstrengung anders. Die Bildschirmarbeit unterbricht sie alle fünfzig Minuten, weil der Physiotherapeut es empfohlen hat, aber auch, weil sie gemerkt hat, dass die Arbeit danach besser wird. Ihr Chef hat das Modell für das ganze Team übernommen. Ob das die Produktivität steigert, weiß niemand genau. Dass es das Klima verbessert hat, merkt man schon an der Kaffeemaschine.",
 "ar":"تعود السيدة لانغ إلى المكتب بعد ثمانية أسابيع: عملية في الركبة، ثلاثة أسابيع تأهيل، وإجازة مرضية طويلة. ما تعلّمته: ردّ فعل المحيط على المرض يكشف المناخ المهني. زميلاتها تولّين مهامها بصمت، بخلاف شركتها السابقة حيث كان الزكام ضعفاً والفحص الوقائي سرّاً، وكانت شبه مدمنة على التقدير. الآن تقسّم الجهد وتقطع عمل الشاشة كل خمسين دقيقة، وتبنّى رئيسها النموذج للفريق كله.",
 "questions":[
  {"type":"mc","promptDe":"Was sagt laut Frau Lang mehr über das Arbeitsklima als jede Umfrage?","options":["wie ein Umfeld auf Krankheit reagiert","wie schnell die Genesung verläuft","wie oft man zur Vorsorge geht"],"answer":"wie ein Umfeld auf Krankheit reagiert","explanationAr":"الدليل حرفياً: «Wie ein Umfeld auf Krankheit reagiert, sagt mehr über das Arbeitsklima als jede Umfrage». الفخّ 1: التعافي سار جيداً لكنه ليس المقياس. الفخّ 2: الوقاية ذُكرت عن الشركة السابقة."},
  {"type":"mc","promptDe":"Wie war es in ihrer früheren Firma?","options":["Schon eine Erkältung galt als Schwäche.","Die Kolleginnen übernahmen still die Aufgaben.","Man unterbrach die Bildschirmarbeit alle fünfzig Minuten."],"answer":"Schon eine Erkältung galt als Schwäche.","explanationAr":"الدليل حرفياً: «in ihrer früheren Firma galt schon eine Erkältung als Schwäche». الفخّ 1: التضامن في الشركة الحالية. الفخّ 2: نموذج الخمسين دقيقة الآن."},
  {"type":"truefalse","promptDe":"Es ist bewiesen, dass das neue Modell die Produktivität steigert.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل حرفياً: «Ob das die Produktivität steigert, weiß niemand genau»."},
  {"type":"fill","promptDe":"Nach der Operation folgten drei Wochen ___ und eine lange Krankschreibung.","answer":["Reha"],"explanationAr":"الدليل حرفياً: «danach folgten drei Wochen Reha und eine lange Krankschreibung»."}]},
{"id":"t-b2-23","titleDe":"Ein Passwort für alles","titleAr":"كلمة مرور واحدة لكل شيء",
 "waisen":["das Passwort","das Nutzerkonto","die Cloud","das Backup","der Akku","der Speicher","das Update","aktualisieren","der Spam","hacken","die Cyberkriminalität","die Nutzungsbedingungen","der Chatbot","die Datenspeicherung","die DSGVO"],
 "de":"Herr Ben Salem benutzte jahrelang ein einziges Passwort: für das Nutzerkonto beim Online-Händler, für die Cloud mit den Familienfotos und für das Spiel seines Sohnes. Er hielt das für praktisch. Dann kam eine E-Mail, die er für Spam hielt, und zwei Tage später war das Konto beim Händler gehackt. Bestellt wurde nichts Teures; die Angreifer wollten offenbar nur prüfen, wo das Passwort noch passt.\n\nDie Beraterin der Bank erklärte ihm, dass Cyberkriminalität selten wie im Film aussieht. Meistens sammelt jemand Zugangsdaten und probiert sie automatisch überall aus. Ein Chatbot der Bank hätte ihm dieselbe Antwort gegeben, sagte sie lachend, aber ohne Kaffee. Ihre Empfehlungen waren einfach: für jedes Konto ein eigenes Passwort, die Software regelmäßig aktualisieren, ein Backup außerhalb der Cloud.\n\nZu Hause stellte er fest, dass das letzte Update auf seinem Handy ein Jahr alt war, weil der Speicher voll war und der Akku bei jeder Installation schwächelte. Die Nutzungsbedingungen der Cloud hatte er nie gelesen; dort stand, wie lange die Datenspeicherung nach einer Kündigung weiterläuft. Nach der DSGVO darf er die Löschung verlangen. Er hat es getan, und die Fotos liegen jetzt zusätzlich auf einer kleinen Festplatte in der Küchenschublade.",
 "ar":"السيد بن سالم استعمل كلمة مرور واحدة لكل حساباته حتى اختُرق حسابه عند المتجر بعد إيميل ظنّه بريداً مزعجاً؛ المهاجمون كانوا يختبرون أين تصلح الكلمة نفسها. مستشارة البنك: الجرائم السيبرانية غالباً تجميع بيانات دخول وتجربتها آلياً؛ توصياتها: كلمة لكل حساب، تحديث دوري، نسخة احتياطية خارج السحابة. اكتشف أن آخر تحديث لهاتفه عمره سنة لامتلاء الذاكرة، وأن شروط الاستخدام تحدّد مدة تخزين البيانات؛ طلب الحذف وفق اللائحة الأوروبية وحفظ الصور على قرص صغير.",
 "questions":[
  {"type":"mc","promptDe":"Was wollten die Angreifer laut Text offenbar?","options":["prüfen, wo das Passwort noch passt","etwas Teures bestellen","die Familienfotos löschen"],"answer":"prüfen, wo das Passwort noch passt","explanationAr":"الدليل حرفياً: «die Angreifer wollten offenbar nur prüfen, wo das Passwort noch passt». الفخّ 1: «Bestellt wurde nichts Teures». الفخّ 2: الصور لم تُمسّ."},
  {"type":"mc","promptDe":"Warum war das letzte Update ein Jahr alt?","options":["weil der Speicher voll war und der Akku schwächelte","weil er die Nutzungsbedingungen nicht gelesen hatte","weil die Bank es nicht empfohlen hatte"],"answer":"weil der Speicher voll war und der Akku schwächelte","explanationAr":"الدليل حرفياً: «weil der Speicher voll war und der Akku bei jeder Installation schwächelte». الفخّ 1: الشروط تخصّ تخزين البيانات. الفخّ 2: البنك أوصى بالتحديث."},
  {"type":"truefalse","promptDe":"Die Beraterin empfahl ein Backup außerhalb der Cloud.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «ein Backup außerhalb der Cloud»."},
  {"type":"fill","promptDe":"Nach der ___ darf er die Löschung verlangen.","answer":["DSGVO"],"explanationAr":"الدليل حرفياً: «Nach der DSGVO darf er die Löschung verlangen»."}]},
{"id":"t-b2-24","titleDe":"Das erste Semester","titleAr":"الفصل الجامعي الأول",
 "waisen":["die Vorlesung","das Hörsaal","die Hausarbeit","der Leistungsnachweis","benoten","die Einschreibung","der Studienplatz","die Zulassung","die Dozentin","die Sprechstunde","das Zeitmanagement","das Lerntagebuch","die Ablenkung","die Karteikarte","die Abschlussarbeit"],
 "de":"Mona hatte den Studienplatz erst im zweiten Anlauf bekommen; die Zulassung kam per Post, die Einschreibung musste sie persönlich erledigen. Dann saß sie in der ersten Vorlesung, in einem Hörsaal mit vierhundert Plätzen, und verstand nach zwanzig Minuten kaum noch ein Wort. Nicht wegen der Sprache. Wegen des Tempos.\n\nIn der Sprechstunde riet ihr die Dozentin zu etwas, das Mona zunächst kindisch fand: einem Lerntagebuch. Jeden Abend drei Zeilen: Was habe ich verstanden, was nicht, was mache ich morgen dagegen. Nach zwei Wochen sah Mona ein Muster. Ihre größte Ablenkung war nicht das Handy, sondern die Sorge, nicht gut genug zu sein. Diese Sorge kostete mehr Zeit als jede Nachricht.\n\nFür den ersten Leistungsnachweis, eine Hausarbeit von zwölf Seiten, plante sie rückwärts: Abgabe, Korrektur, Rohfassung, Gliederung, Lesen. Zeitmanagement heißt für sie seitdem nicht, mehr zu schaffen, sondern früher anzufangen. Die Arbeit wurde mit einer Zwei benotet. Die Dozentin schrieb darunter, die Gliederung sei ungewöhnlich klar. Bis zur Abschlussarbeit sind es noch Jahre, aber die Karteikarten mit den Fachbegriffen liegen schon jetzt in einer Schachtel neben dem Bett.",
 "ar":"منى حصلت على مقعد الدراسة في المحاولة الثانية، وفي أول محاضرة في مدرّج بأربعمائة مقعد لم تفهم بعد عشرين دقيقة بسبب السرعة لا اللغة. في موعد المكتب نصحتها المحاضِرة بدفتر تعلّم: ثلاثة أسطر كل مساء. بعد أسبوعين اكتشفت أن أكبر مشتّت لها ليس الهاتف بل القلق من عدم الكفاءة. خطّطت للبحث المكتوب عكسياً من موعد التسليم؛ إدارة الوقت عندها صارت: البدء مبكراً لا الإنجاز أكثر. نالت درجة اثنين، والبطاقات جاهزة قرب السرير.",
 "questions":[
  {"type":"mc","promptDe":"Warum verstand Mona in der ersten Vorlesung kaum noch ein Wort?","options":["wegen des Tempos","wegen der Sprache","wegen der vierhundert Plätze"],"answer":"wegen des Tempos","explanationAr":"الدليل حرفياً: «Nicht wegen der Sprache. Wegen des Tempos». الفخّ 1: اللغة منفيّة صراحة. الفخّ 2: حجم المدرّج وصف لا سبب."},
  {"type":"mc","promptDe":"Was war laut Lerntagebuch Monas größte Ablenkung?","options":["die Sorge, nicht gut genug zu sein","das Handy","die Nachrichten der Freunde"],"answer":"die Sorge, nicht gut genug zu sein","explanationAr":"الدليل حرفياً: «Ihre größte Ablenkung war nicht das Handy, sondern die Sorge, nicht gut genug zu sein». الفخّ: الهاتف منفيّ بـ«nicht … sondern»."},
  {"type":"truefalse","promptDe":"Die Hausarbeit wurde mit einer Zwei benotet.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «Die Arbeit wurde mit einer Zwei benotet»."},
  {"type":"fill","promptDe":"In der ___ riet ihr die Dozentin zu einem Lerntagebuch.","answer":["Sprechstunde"],"explanationAr":"الدليل حرفياً: «In der Sprechstunde riet ihr die Dozentin zu etwas»."}]},
{"id":"t-b2-25","titleDe":"Die Niederlage im Turnier","titleAr":"الهزيمة في البطولة",
 "waisen":["der Wettkampf","das Turnier","die Niederlage","der Schiedsrichter","der Elfmeter","jubeln","anfeuern","das Ausdauertraining","das Krafttraining","sich dehnen","die Zerrung","die Prellung","die Mitgliederversammlung","der Beitritt","die Bestleistung","diszipliniert"],
 "de":"Das Turnier endete für den kleinen Verein aus dem Stadtteil im Halbfinale, mit einem Elfmeter in der letzten Minute. Der Schiedsrichter hatte ein Foul gesehen, das die Hälfte der Zuschauer nicht gesehen hatte. Die andere Hälfte jubelte. So ist das bei einem Wettkampf: Dieselbe Szene, zwei Wahrheiten.\n\nInteressanter als die Niederlage war, was danach geschah. Auf der Mitgliederversammlung zwei Wochen später sprach niemand über den Schiedsrichter. Man sprach über Training. Die Trainerin legte Zahlen vor: drei Zerrungen und zwei Prellungen in einer Saison, fast alle in der zweiten Halbzeit. Ihre Erklärung war unbequem. Das Ausdauertraining sei gut, das Krafttraining schwach, und vor den Spielen dehne sich kaum jemand länger als zwei Minuten.\n\nDer Verein beschloss, disziplinierter zu werden, ohne strenger zu sein: zwei feste Einheiten pro Woche, ein Aufwärmplan, den jeder kennt, und ein Notizbuch, in dem jede Spielerin ihre Bestleistung selbst einträgt. Seit dem Beschluss gab es sieben Beitritte, die meisten von Eltern, die vorher nur vom Rand aus angefeuert hatten. Ob die Mannschaft nächstes Jahr weiterkommt, ist offen. Dass sie besser vorbereitet verliert oder gewinnt, ist sicher.",
 "ar":"خرج نادي الحي من البطولة في نصف النهائي بركلة جزاء في الدقيقة الأخيرة رأى الحكم فيها خطأً لم يره نصف الجمهور. الأهمّ ما جرى بعدها: في الجمعية العمومية لم يتحدث أحد عن الحكم بل عن التدريب؛ المدربة عرضت أرقام الإصابات (شدّ ورضوض معظمها في الشوط الثاني) وشخّصت ضعف تمارين القوة والإطالة. قرّر النادي الانضباط دون تشدّد: حصّتان ثابتتان، خطة إحماء، ودفتر تسجّل فيه كل لاعبة أفضل نتيجتها. سبعة انتساب جديد، معظمهم آباء كانوا يشجعون من الحافة.",
 "questions":[
  {"type":"mc","promptDe":"Worüber sprach man auf der Mitgliederversammlung?","options":["über Training","über den Schiedsrichter","über den Elfmeter"],"answer":"über Training","explanationAr":"الدليل حرفياً: «sprach niemand über den Schiedsrichter. Man sprach über Training». الفخّ: الحكم وركلة الجزاء منفيّان كموضوع."},
  {"type":"mc","promptDe":"Was war laut Trainerin schwach?","options":["das Krafttraining","das Ausdauertraining","die Disziplin der Zuschauer"],"answer":"das Krafttraining","explanationAr":"الدليل حرفياً: «Das Ausdauertraining sei gut, das Krafttraining schwach». الفخّ 1: التحمل «gut». الفخّ 2: الجمهور لم يُقيَّم."},
  {"type":"truefalse","promptDe":"Die meisten neuen Mitglieder sind Eltern, die vorher vom Rand aus angefeuert hatten.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «die meisten von Eltern, die vorher nur vom Rand aus angefeuert hatten»."},
  {"type":"fill","promptDe":"Drei ___ und zwei Prellungen in einer Saison, fast alle in der zweiten Halbzeit.","answer":["Zerrungen"],"explanationAr":"الدليل حرفياً: «drei Zerrungen und zwei Prellungen in einer Saison»."}]},
]
