# -*- coding: utf-8 -*-
"""5 weitere B2-Kurztexte (t-b2-26..30) aus verwaisten B2-Karten (>=12 je Text)."""
T = [
{"id":"t-b2-26","titleDe":"Der Bürgerwindpark","titleAr":"مزرعة الرياح الأهلية",
 "waisen":["das Windrad","der Windpark","erneuerbar","die Solarenergie","der Schattenwurf","der Infraschall","der Mindestabstand","die Akzeptanz","der Netzausbau","die Stromtrasse","einspeisen","die Einspeisevergütung","der Bürgerwindpark","fossil","das Kraftwerk","der Ökostrom"],
 "de":"Als das erste Windrad hinter dem Dorf geplant wurde, war die Stimmung schlecht. Man sprach über Schattenwurf am Morgen, über Infraschall, den niemand hört und alle fürchten, und über den Mindestabstand zu den letzten Häusern. Ein Windpark, hieß es, gehöre aufs Meer, nicht ins Tal.\n\nDie Wende kam mit einem anderen Modell. Statt eines fremden Betreibers gründete eine Gruppe aus dem Ort einen Bürgerwindpark: Wer will, kauft einen Anteil, und der Gewinn bleibt in der Region. Plötzlich rechneten dieselben Leute, die vorher nur Nachteile gesehen hatten, mit der Einspeisevergütung und fragten, wann die Anlage Strom ins Netz einspeisen könne. Akzeptanz, so lernte der Bürgermeister, entsteht selten durch Broschüren. Sie entsteht, wenn Menschen mitverdienen und mitentscheiden.\n\nGelöst ist damit nicht alles. Ohne Netzausbau kommt der Ökostrom nicht in die Stadt, und gegen die neue Stromtrasse klagt schon das Nachbardorf. Auf den Dächern der Schule liefert Solarenergie inzwischen den Strom für die Küche, das alte Kraftwerk am Fluss läuft nur noch im Winter. Erneuerbar heißt nicht einfach; es heißt, dass die Konflikte näher rücken, weil die Energie nicht mehr aus fossilen Quellen weit weg kommt, sondern vom Hügel hinter dem Haus.",
 "ar":"حين خُطّط لأول عنفة رياح خلف القرية ساد الرفض: ظلّ الشفرات، ما تحت السمع، المسافة الدنيا. تغيّر المزاج مع نموذج آخر: مزرعة رياح أهلية يشتري فيها من يشاء حصة ويبقى الربح في المنطقة؛ صار المعارضون يحسبون تعرفة التغذية ويسألون متى يُضخّ التيار في الشبكة. القبول لا يأتي من الكتيّبات بل من المشاركة في الربح والقرار. لكن بلا توسيع الشبكة لا يصل التيار الأخضر، والقرية المجاورة تقاضي ضد ممرّ الكهرباء الجديد؛ المتجدد ليس سهلاً — الصراعات تقترب لأن الطاقة لم تعد تأتي من بعيد.",
 "questions":[
  {"type":"mc","promptDe":"Wodurch entstand laut Bürgermeister Akzeptanz?","options":["dadurch, dass Menschen mitverdienen und mitentscheiden","durch Broschüren","durch den Mindestabstand zu den Häusern"],"answer":"dadurch, dass Menschen mitverdienen und mitentscheiden","explanationAr":"الدليل حرفياً: «Akzeptanz … entsteht selten durch Broschüren. Sie entsteht, wenn Menschen mitverdienen und mitentscheiden». الفخّ 1: الكتيّبات منفيّة. الفخّ 2: المسافة الدنيا كانت من مخاوف البداية."},
  {"type":"mc","promptDe":"Was ist noch nicht gelöst?","options":["Ohne Netzausbau kommt der Ökostrom nicht in die Stadt.","Die Schule hat keinen Strom für die Küche.","Das alte Kraftwerk läuft das ganze Jahr."],"answer":"Ohne Netzausbau kommt der Ökostrom nicht in die Stadt.","explanationAr":"الدليل حرفياً: «Ohne Netzausbau kommt der Ökostrom nicht in die Stadt». الفخّ 1: الطاقة الشمسية تغذّي المطبخ. الفخّ 2: المحطة «läuft nur noch im Winter»."},
  {"type":"truefalse","promptDe":"Das Nachbardorf klagt gegen die neue Stromtrasse.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «gegen die neue Stromtrasse klagt schon das Nachbardorf»."},
  {"type":"fill","promptDe":"Sie fragten, wann die Anlage Strom ins Netz ___ könne.","answer":["einspeisen"],"explanationAr":"الدليل حرفياً: «wann die Anlage Strom ins Netz einspeisen könne»."}]},
{"id":"t-b2-27","titleDe":"Das Kleingedruckte","titleAr":"الخطّ الصغير",
 "waisen":["das Kleingedruckte","die Abo-Falle","der Lockvogel","die Kulanz","die Abmahnung","die Mogelpackung","der Umtausch","umtauschen","reklamieren","das Rückgaberecht","die Kundschaft","das Schnäppchen","minderwertig","hochwertig","die Irreführung","die Verbraucherzentrale"],
 "de":"Frau Öztürk arbeitet seit zwölf Jahren in einer Verbraucherzentrale und sagt, die Fälle hätten sich kaum verändert, nur die Verpackung. Früher kam die Kundschaft mit einem Katalog, heute mit einem Handy. Das Prinzip bleibt: Ein Lockvogel zieht an, das Kleingedruckte holt zurück.\n\nIhr häufigster Fall ist die Abo-Falle. Ein kostenloser Probemonat, ein hochwertig aussehendes Angebot, ein Schnäppchen mit Countdown. Wer nicht kündigt, zahlt. Der zweithäufigste Fall ist die Mogelpackung: gleiche Größe, weniger Inhalt, gleicher Preis. Das ist keine Irreführung im rechtlichen Sinn, solange das Gewicht irgendwo steht. Frau Öztürk nennt es trotzdem so, und die Kundschaft versteht sie.\n\nWas viele nicht wissen: Beim Kauf im Laden gibt es kein gesetzliches Rückgaberecht. Wer einen Pullover umtauschen will, weil er ihm nicht gefällt, ist auf die Kulanz des Händlers angewiesen. Reklamieren kann man dagegen immer, wenn die Ware minderwertig ist oder kaputt ankommt. Den Unterschied zwischen Umtausch und Reklamation erklärt sie jeden Tag. Und wenn ein Händler mit falschen Versprechen wirbt, schreibt die Zentrale eine Abmahnung. Das wirkt, sagt sie, meistens schneller als jedes Gericht.",
 "ar":"السيدة أوزتورك تعمل في مركز حماية المستهلك منذ اثنتي عشرة سنة: الحالات لم تتغيّر، بل غلافها فقط. المبدأ: طُعم يجذب وخطّ صغير يستردّ. أكثر الحالات فخّ الاشتراك، ثم العبوة المخاتلة (حجم واحد، محتوى أقل، سعر واحد) — ليست تضليلاً قانونياً ما دام الوزن مكتوباً. ما لا يعرفه كثيرون: لا حقّ إرجاع قانونياً للشراء في المتجر؛ الاستبدال تفضّل من البائع، أما الشكوى فحقّ دائم للبضاعة الرديئة أو المعطوبة. وضد الإعلان الكاذب يكتب المركز إنذاراً قانونياً — أسرع من المحكمة.",
 "questions":[
  {"type":"mc","promptDe":"Was ist laut Frau Öztürk der häufigste Fall?","options":["die Abo-Falle","die Mogelpackung","die Abmahnung"],"answer":"die Abo-Falle","explanationAr":"الدليل حرفياً: «Ihr häufigster Fall ist die Abo-Falle». الفخّ 1: العبوة المخاتلة «zweithäufigste». الفخّ 2: الإنذار أداة المركز لا حالة زبون."},
  {"type":"mc","promptDe":"Wann kann man laut Text immer reklamieren?","options":["wenn die Ware minderwertig ist oder kaputt ankommt","wenn der Pullover nicht gefällt","wenn der Probemonat abgelaufen ist"],"answer":"wenn die Ware minderwertig ist oder kaputt ankommt","explanationAr":"الدليل حرفياً: «Reklamieren kann man dagegen immer, wenn die Ware minderwertig ist oder kaputt ankommt». الفخّ 1: عدم الإعجاب يعتمد على تفضّل البائع. الفخّ 2: الشهر التجريبي يخصّ فخّ الاشتراك."},
  {"type":"truefalse","promptDe":"Beim Kauf im Laden ist man beim Umtausch auf die Kulanz des Händlers angewiesen.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «ist auf die Kulanz des Händlers angewiesen»."},
  {"type":"fill","promptDe":"Ein ___ zieht an, das Kleingedruckte holt zurück.","answer":["Lockvogel"],"explanationAr":"الدليل حرفياً: «Ein Lockvogel zieht an, das Kleingedruckte holt zurück»."}]},
{"id":"t-b2-28","titleDe":"Wem gehört die Stadt?","titleAr":"لمن المدينة؟",
 "waisen":["die Gentrifizierung","die Aufwertung","die Verdrängung","der Mietspiegel","die Kappungsgrenze","die Nachverdichtung","der Bebauungsplan","die Bürgerbeteiligung","der Bürgerentscheid","das Vorkaufsrecht","der Leerstand","die Stadtbegrünung","die Versiegelung","die Frischluftschneise","sanieren","aufwerten","die Zweckentfremdung"],
 "de":"Im Viertel am Bahnhof eröffneten innerhalb von zwei Jahren drei Cafés, ein Yogastudio und ein Laden für Fahrräder, die mehr kosten als ein Kleinwagen. Die Zeitung nannte es Aufwertung. Die Familie im dritten Stock, deren Miete nach der Sanierung um ein Drittel stieg, nannte es anders. Gentrifizierung ist das Wort, aber das Gefühl dahinter heißt Verdrängung: Man wird nicht gekündigt, man wird herausgepreist.\n\nDie Stadt hat Instrumente, die sie selten nutzt. Der Mietspiegel zeigt, was ortsüblich ist; die Kappungsgrenze begrenzt, wie schnell die Miete steigen darf; das Vorkaufsrecht erlaubt der Stadt, ein Haus zu kaufen, bevor es ein Investor tut. Gegen die Zweckentfremdung von Wohnungen als Ferienunterkünfte gibt es ein Verbot, aber kaum jemand kontrolliert es. Der Leerstand im alten Postgebäude dauert seit sieben Jahren.\n\nBeim Bürgerentscheid im Frühjahr ging es um den Bebauungsplan für den letzten freien Platz: Nachverdichtung mit sechzig Wohnungen oder Stadtbegrünung mit Bäumen und einem Spielplatz. Die Gegner der Bebauung sprachen von Versiegelung und einer Frischluftschneise, die man nicht zubauen dürfe. Die Befürworter fragten, wo die Familien sonst wohnen sollten. Am Ende gewann die Bebauung knapp, mit der Auflage, das Dach zu begrünen. Bürgerbeteiligung heißt nicht, dass alle zufrieden sind. Sie heißt, dass niemand sagen kann, er sei nicht gefragt worden. Ob man ein Viertel aufwerten kann, ohne seine Bewohner zu verlieren, bleibt die eigentliche Frage.",
 "ar":"حيّ المحطة: ثلاثة مقاهٍ وستوديو يوغا ومتجر دراجات غالية خلال سنتين؛ الجريدة سمّته ارتقاءً، والعائلة التي ارتفع إيجارها ثلثاً بعد الترميم سمّته إزاحة. للمدينة أدوات نادراً ما تستعملها: مرآة الإيجارات، سقف الزيادة، حق الشراء الأول، منع تحوير الشقق لسكن سياحي — ومبنى البريد فارغ منذ سبع سنوات. الاستفتاء المحلي حول آخر ساحة: حشو عمراني بستين شقة أم تخضير؛ فاز البناء بفارق ضئيل بشرط تخضير السطح. إشراك المواطنين لا يعني رضا الجميع بل ألا يقول أحد إنه لم يُسأل.",
 "questions":[
  {"type":"mc","promptDe":"Was bedeutet Verdrängung laut Text?","options":["Man wird nicht gekündigt, man wird herausgepreist.","Man bekommt eine Kündigung wegen der Sanierung.","Man zieht freiwillig ins Yogastudio-Viertel."],"answer":"Man wird nicht gekündigt, man wird herausgepreist.","explanationAr":"الدليل حرفياً: «Man wird nicht gekündigt, man wird herausgepreist». الفخّ 1: الإخلاء منفيّ. الفخّ 2: لا طوعية في الأمر."},
  {"type":"mc","promptDe":"Wie ging der Bürgerentscheid aus?","options":["Die Bebauung gewann knapp, mit der Auflage, das Dach zu begrünen.","Die Stadtbegrünung mit Spielplatz gewann.","Der Platz bleibt eine Frischluftschneise."],"answer":"Die Bebauung gewann knapp, mit der Auflage, das Dach zu begrünen.","explanationAr":"الدليل حرفياً: «Am Ende gewann die Bebauung knapp, mit der Auflage, das Dach zu begrünen». الفخّ 1 و2: موقف المعارضين."},
  {"type":"truefalse","promptDe":"Das Verbot der Zweckentfremdung wird streng kontrolliert.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل حرفياً: «aber kaum jemand kontrolliert es»."},
  {"type":"fill","promptDe":"Das ___ erlaubt der Stadt, ein Haus zu kaufen, bevor es ein Investor tut.","answer":["Vorkaufsrecht"],"explanationAr":"الدليل حرفياً: «das Vorkaufsrecht erlaubt der Stadt, ein Haus zu kaufen, bevor es ein Investor tut»."}]},
{"id":"t-b2-29","titleDe":"Ankommen dauert","titleAr":"الوصول يستغرق وقتاً",
 "waisen":["die Einbürgerung","die Staatsbürgerschaft","der Integrationskurs","die Duldung","die Niederlassungserlaubnis","der Familiennachzug","die Arbeitserlaubnis","die Gleichwertigkeitsprüfung","die Nachqualifizierung","die Bleibeperspektive","die Willkommenskultur","die Mehrheitsgesellschaft","sich einfügen","zugewandert","die Blaue Karte","der Zweitspracherwerb"],
 "de":"Als Dr. Amani vor sechs Jahren zugewandert ist, hatte sie einen Abschluss in Chemie und keine Arbeitserlaubnis. Die Gleichwertigkeitsprüfung ihres Diploms dauerte neun Monate; danach fehlte ein halbes Jahr Nachqualifizierung, weil ein Fach im deutschen Lehrplan anders heißt. In dieser Zeit lebte sie mit einer Duldung, die alle sechs Monate verlängert werden musste. Planen konnte sie nichts, nicht einmal einen Zahnarzttermin.\n\nDer Integrationskurs war für sie sprachlich zu leicht und bürokratisch zu wichtig: Ohne das Zertifikat keine Bleibeperspektive, ohne Bleibeperspektive kein Familiennachzug. Ihr Mann kam erst im dritten Jahr. Dass sie heute eine Blaue Karte hat und nächstes Jahr die Niederlassungserlaubnis beantragen kann, verdankt sie vor allem einer Kollegin im Labor, die ihr jeden Brief vom Amt erklärt hat. Willkommenskultur, sagt Dr. Amani, ist kein Plakat am Bahnhof. Es ist eine Person, die Zeit hat.\n\nOb sie die Staatsbürgerschaft beantragt, weiß sie noch nicht. Die Einbürgerung wäre ein Schritt, den ihre Eltern nicht verstehen würden. Sich einfügen, ohne sich aufzugeben, ist die Übung, die sie täglich macht. Die Mehrheitsgesellschaft merkt selten, wie viel Übersetzung das kostet, nicht nur beim Zweitspracherwerb. Ankommen, sagt sie, ist kein Datum. Es ist eine Richtung.",
 "ar":"الدكتورة أماني هاجرت قبل ست سنوات بشهادة كيمياء وبلا رخصة عمل؛ معادلة الشهادة استغرقت تسعة أشهر ثم نصف سنة تأهيل لاحق، وعاشت بتحمّل مؤقت يُجدَّد كل ستة أشهر بلا قدرة على التخطيط. دورة الاندماج كانت لغوياً سهلة وبيروقراطياً حاسمة: بلا شهادة لا أفق بقاء ولا لحاق أسرة؛ زوجها جاء في السنة الثالثة. اليوم لديها البطاقة الزرقاء وستطلب الإقامة الدائمة — بفضل زميلة شرحت لها كل رسالة رسمية: ثقافة الترحيب شخص لديه وقت لا لافتة. التجنيس قرار لم تحسمه؛ الاندماج دون التخلّي عن الذات تمرين يومي. الوصول ليس تاريخاً بل اتجاه.",
 "questions":[
  {"type":"mc","promptDe":"Warum brauchte Dr. Amani eine Nachqualifizierung?","options":["weil ein Fach im deutschen Lehrplan anders heißt","weil ihr Diplom nicht anerkannt wurde","weil sie den Integrationskurs nicht bestanden hatte"],"answer":"weil ein Fach im deutschen Lehrplan anders heißt","explanationAr":"الدليل حرفياً: «weil ein Fach im deutschen Lehrplan anders heißt». الفخّ 1: المعادلة تمّت بعد تسعة أشهر. الفخّ 2: الدورة كانت «zu leicht»."},
  {"type":"mc","promptDe":"Was ist Willkommenskultur laut Dr. Amani?","options":["eine Person, die Zeit hat","ein Plakat am Bahnhof","das Zertifikat des Integrationskurses"],"answer":"eine Person, die Zeit hat","explanationAr":"الدليل حرفياً: «Willkommenskultur … ist kein Plakat am Bahnhof. Es ist eine Person, die Zeit hat». الفخّ 1: منفيّ صراحة. الفخّ 2: الشهادة شرط بيروقراطي."},
  {"type":"truefalse","promptDe":"Ihr Mann kam erst im dritten Jahr nach Deutschland.","options":["richtig","falsch"],"answer":"richtig","explanationAr":"الدليل حرفياً: «Ihr Mann kam erst im dritten Jahr»."},
  {"type":"fill","promptDe":"In dieser Zeit lebte sie mit einer ___, die alle sechs Monate verlängert werden musste.","answer":["Duldung"],"explanationAr":"الدليل حرفياً: «lebte sie mit einer Duldung, die alle sechs Monate verlängert werden musste»."}]},
{"id":"t-b2-30","titleDe":"Ein Stein vor der Tür","titleAr":"حجر أمام الباب",
 "waisen":["der Stolperstein","die Erinnerungskultur","das Gedenken","die Gedenkstätte","das Mahnmal","der Zeitzeuge","die Gedenkminute","die Verharmlosung","der Schlussstrich","die Erinnerungsarbeit","die Vergangenheitsbewältigung","die Schuldfrage","der Mitläufer","gedenken","aufarbeiten","relativieren"],
 "de":"Vor dem Haus Nummer 14 liegt seit dem Frühjahr ein kleiner Stolperstein aus Messing. Ein Name, ein Geburtsjahr, ein Schicksal in drei Zeilen. Die Schülerinnen der zehnten Klasse haben die Geschichte der Familie recherchiert, die dort einmal wohnte, und bei der Verlegung eine Gedenkminute gehalten. Kein Mahnmal aus Stein, keine Gedenkstätte mit Öffnungszeiten, nur ein Stein, über den man beim Einkaufen stolpert. Das ist Erinnerungskultur im Kleinen.\n\nNicht alle im Haus waren dafür. Ein Bewohner fragte, ob man nicht irgendwann einen Schlussstrich ziehen könne; seine Großeltern seien doch nur Mitläufer gewesen. Die Lehrerin antwortete ruhig, dass Erinnerungsarbeit keine Schuldfrage an die Enkel stellt. Sie fragt, wie normale Menschen mitgemacht haben, damit normale Menschen es heute erkennen. Wer die Vergangenheit relativiert, sagt sie, schützt nicht die Großeltern, sondern die Bequemlichkeit.\n\nDer letzte Zeitzeuge aus der Straße ist vor zwei Jahren gestorben. Sein Interview liegt im Archiv der Schule, dreiundvierzig Minuten. Die Schülerinnen haben es gehört, bevor sie den Stein setzten. Vergangenheitsbewältigung ist ein schweres Wort für etwas Einfaches: hinsehen, aufarbeiten, weitergeben. Verharmlosung beginnt nicht mit einer Lüge, sondern mit einem Wort, das weicher klingt als die Tatsache. Wer der Toten gedenkt, sagt die Lehrerin, tut das nicht für die Toten.",
 "ar":"أمام المنزل رقم 14 حجر عثرة نحاسي: اسم وسنة ميلاد ومصير في ثلاثة أسطر. تلميذات الصف العاشر بحثن قصة العائلة وأقمن دقيقة صمت عند التركيب — لا نصب حجري ولا موقع تذكير بأوقات دوام، بل حجر يعثر به المرء أثناء التسوق. ساكن سأل عن خطّ النهاية، فأجدادُه «مجرد منساقين»؛ المعلّمة: عمل التذكّر لا يطرح سؤال الذنب على الأحفاد بل يسأل كيف شارك أناس عاديون كي يميّز العاديون اليوم. آخر شاهد عصر في الشارع مات قبل سنتين ومقابلته في أرشيف المدرسة. التصغير لا يبدأ بكذبة بل بكلمة ألين من الحقيقة.",
 "questions":[
  {"type":"mc","promptDe":"Was fragt Erinnerungsarbeit laut Lehrerin?","options":["wie normale Menschen mitgemacht haben","wer von den Enkeln schuldig ist","wann man einen Schlussstrich ziehen kann"],"answer":"wie normale Menschen mitgemacht haben","explanationAr":"الدليل حرفياً: «Sie fragt, wie normale Menschen mitgemacht haben». الفخّ 1: «keine Schuldfrage an die Enkel». الفخّ 2: خطّ النهاية سؤال الساكن."},
  {"type":"mc","promptDe":"Womit beginnt Verharmlosung laut Text?","options":["mit einem Wort, das weicher klingt als die Tatsache","mit einer Lüge","mit einem Mahnmal aus Stein"],"answer":"mit einem Wort, das weicher klingt als die Tatsache","explanationAr":"الدليل حرفياً: «Verharmlosung beginnt nicht mit einer Lüge, sondern mit einem Wort, das weicher klingt als die Tatsache». الفخّ 1: منفيّ بـ«nicht … sondern». الفخّ 2: النصب الحجري ما ليس موجوداً هنا."},
  {"type":"truefalse","promptDe":"Der letzte Zeitzeuge aus der Straße lebt noch.","options":["richtig","falsch"],"answer":"falsch","explanationAr":"الدليل حرفياً: «Der letzte Zeitzeuge aus der Straße ist vor zwei Jahren gestorben»."},
  {"type":"fill","promptDe":"Vor dem Haus Nummer 14 liegt ein kleiner ___ aus Messing.","answer":["Stolperstein"],"explanationAr":"الدليل حرفياً: «liegt seit dem Frühjahr ein kleiner Stolperstein aus Messing»."}]},
]
