# -*- coding: utf-8 -*-
"""ξ7ب — ثمانية عشر حواراً B2 (d-b2-10..27): مستوى ناقشٍ وشكوى ومفاوضات."""
import json, re

ROOT = "/home/user/weg-nach-b2"
CJK = re.compile(r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\uac00-\ud7af]")
ARc = re.compile(r"[\u0600-\u06ff]")

D18 = [
(10, "Vorstellungsgespräch: Gehalt verhandeln", "مقابلةُ عمل: مفاوضةُ الأجر", "Youssef", "Personalchefin",
 [("Danke, dass Sie sich die Zeit nehmen — Ihre Stelle interessiert mich sehr.", "شكراً على وقتك — وظيفتُكم تهمُّني للغاية."),
  ("Ebenso. Was schwebt Ihnen tariflich vor?", "وكذلك. ما الذي تُقَدِّمُه لنفسك أجرياً؟"),
  ("Angesichts meiner Erfahrung käme ich auf 48.000 Euro brutto.", "في ضوءِ خبرتي، أقولُ ثمانيةً وأربعين ألفاً إجماليّاً."),
  ("Das liegt über unserem Rahmen; 45.000 plus variabler Anteil wäre verhandelbar.", "هذا يفوقُ هامشَنا؛ خمسةٌ وأربعون ألفاً زائدُ المتغيرِ قابلٌ للنقاش."),
  ("Auf der Zahl bestehe ich nicht — aber die Weiterbildungszeit zähle ich als Leistung.", "لستُ مُصمِّماً على الرقم — لكني أَعُدُّ وقتَ تدريبي إيراداً غيرَ مباشر."),
  ("Fair. Dann 45.500, zwei Tage Homeoffice und 400 Euro Weiterbildungsbudget.", "منصِف. إذن خمسةٌ وأربعون وخمسمئة، يومانِ عملٌ منزليٌّ وأربعمئةُ يورو تدريباً."),
  ("Sofern der Vertrag die Probezeit auf drei Monate begrenzt, haben wir eine Übereinkunft.", "بشرطِ أن تُقَصَّرَ التجربةُ إلى ثلاثةِ أشهر، نكونُ قد اتفقنا."),
  ("Abgemacht — die Zusage bekommen Sie schriftlich morgen Vormittag.", "تمّ — ستصلُك نسخةُ العقدِ خطياً غدًا صباحاً.")],
 [("Wie endet die Verhandlung?", "48.000 ohne Zugeständnis", "45.500 mit Zusatzleistungen", "kein Vertrag", 1, "الرقمُ النهائيُّ خمسةٌ وأربعون وخمسمئة مع المكتسبات."),
  ("Was fordert Youssef als Bedingung?", "Wohnortnähe", "drei Monate Probezeit", "ein Auto", 1, "تقصيرَ التجربةِ ثلاثةَ أشهر شرطاً خطيّاً."),
  ("Was wird schriftlich fixiert?", "nur die Gehaltshöhe", "der gesamte Kompromiss", "keine Zusage", 1, "الاتفاقُ كله سيُرسَلُ غدًا تحريريّاً. ")],
 ["Auf der Zahl bestehe ich nicht — aber die Weiterbildungszeit zähle ich als Leistung.", "Sofern der Vertrag die Probezeit auf drei Monate begrenzt, haben wir eine Übereinkunft."]),

(11, "Mieterhöhung: schriftlich verhandeln", "زيادةُ الإيجار: تفاوُضٌ خطّي", "Amel", "Hausverwaltung",
 [("Die angekündigte Erhöhung um 15 Prozent übersteigt die ortsübliche Miete.", "الزيادةُ المعلَنةُ بخمسةَ عشرَ بالمئةِ تتجاوزُ الإيجارَ المعتادَ محليًّا."),
  ("Unsere Belege: Mietspiegel und Wirtschaftlichkeitsberechnung.", "حججُنا: مؤشّرُ الإيجاراتِ ودراسةُ الجدوى الاقتصادية."),
  ("Genau der Mietspiegel besagt: Kappungsgrenze bei elf Prozent in drei Jahren.", "المؤشّرُ نفسُه يقول: سقفُ الزيادةِ أحدَ عشرَ بالمئةِ في ثلاثِ سنوات."),
  ("Stimmt — Ihr Brief errechnet korrekt; wir korrigieren auf 9,8 Prozent.", "صحيح — حسابُ رسالتك سليم؛ فنُصحِّحُ إلى تسعةٍ فاصلةَ ثمانية بالمئة."),
  ("Zusätzlich wünsche ich ein Protokoll über die Nebenkostenabrechnung.", "وزيادةً على ذلك أطلبُ محضرًا لتسويةِ النفقاتِ الجانبية."),
  ("Das Protokoll folgt binnen vierzehn Tagen samt Belegen.", "يُرسلُ المحضرُ خلالَ أسبوعَين مع الفواتير."),
  ("Sofern alles eintrifft, akzeptiere ich den neuen Betrag zum Ersten.", "بشرطِ وصولِ كلِّ شيءٍ أقبلُ المبلغَ الجديدَ أولَ الشهر."),
  ("Per Mail bestätigt — danke für die sachliche Gesprächsführung.", "وصلَ التأكيدُ بالبريد — شكرًا على منهجيةِ النقاش.")]
 , [("Worauf beruft sich Amel?", "ein Gutachten", "den Mietspiegel und die Kappungsgrenze", "das Gesetz über Kaution", 1, "سقفُ الزيادةِ ومؤشرُ الإيجارِ مرجعُها."),
    ("Was folgt nach dem Brief?", "Klage", "korrigierte Forderung plus Protokoll", "keine Reaktion", 1, "تعديلُ المبلغِ إلى 9.8 ثم محضرُ النفقات."),
    ("Wann akzeptiert Amel die neue Miete?", "sofort", "wenn Protokoll und Fristen stimmen", "nie", 1, "قبولُها مشروطٌ بوصولِ الأوراقِ في موعدها.")]
 , ["Zusätzlich wünsche ich ein Protokoll über die Nebenkostenabrechnung.", "Stimmt — Ihr Brief errechnet korrekt; wir korrigieren auf 9,8 Prozent."]),
(12, "Anerkennung des ausländischen Abschlusses", "اعترافٌ بالشهادةِ الأجنبية", "Mehdi", "Sachbearbeiterin",
 [("Mein tunesisches Ingenieurdiplom soll anerkannt werden — welche Dokumente?", "أُريدُ الاعترافَ بشهادةِ الهندسةِ التونسية — ما الوثائق؟"),
  ("Beglaubigte Übersetzung, Fächerübersicht, Nachweis praktischer Tätigkeiten.", "ترجمةٌ مُصدَّق عليها، وقائمةُ مواد، وإثباتُ سنواتِ الخبرةِ العملية."),
  ("Wie lange dauert die Prüfung, und kann ich währenddessen arbeiten?", "كم تستغرقُ اللجان، وهل يحقُّ لي العملُ بين الأيادي؟"),
  ("Regulär drei Monate; mit Ihrer Berufserlaubnis im Warteverfahren — ja, eingeschränkt.", "ثلاثةُ أشهر نظاماً؛ وبإذنِ مهنتك في وضعِ الانتظار — عملٌ مقيَّدٌ نعم."),
  ("Und wenn die Gleichwertigkeit teilweise verneint wird?", "وإن حُكِمَ بعدمِ التكافؤِ جزئياً؟"),
  ("Dann bekommen Sie einen Anpassungslehrgang zugewiesen, höchstens 16 Monate Praxis.", "يُسنَدُ إليك دوراتٌ تكييفية، أقصاها ستةَ عشرَ شهراً عمليةً موجَّهة."),
  ("Die Gebühren sind mir unklar — wer trägt sie bei Erfolg?", "الرسومُ غيرُ واضحة — ومَن يتحمَّلُها عند النجاح؟"),
  ("400 Euro Vorauszahlung; die Erstattung richtet sich nach dem Landrecht.", "أربعمئةٌ مقدَّماً؛ والاستردادُ بحسب قانونِ الولاية.")],
 [("Was muss Mehdi beibringen?", "nur das Diplom", "beglaubigte Übersetzung und Fächerübersicht", "ein Foto", 1, "ثلاثيةٌ موثَّقة: ترجمةٌ وموادُّ وممارسة."),
  ("Arbeiten im Warteverfahren?", "nie", "eingeschränkt mit Erlaubnis", "unbegrenzt", 1, "يُسمَحُ مقيَّداً ريثما تُفتَلُّ اللجنة."),
  ("Wie lang maximal der Anpassungslehrgang?", "6 Monate", "16 Monate", "3 Jahre", 1, "ستةَ عشرَ شهراً حداً أقصى عمليًّا.")],
 ["Dann bekommen Sie einen Anpassungslehrgang zugewiesen, höchstens 16 Monate Praxis.", "Regulär drei Monate; mit Ihrer Berufserlaubnis im Warteverfahren — ja, eingeschränkt."]),

(13, "Elterngeld: Antrag und Beratung", "بدلُ الوالدية: طلبٌ ومشورة", "Selma", "Beraterin",
 [("Ich beantrage Elterngeld ab April — welche Fristen gelten?", "أقدِّمُ طلبَ بدلِ الوالدية من أبريل — ما المواعيد؟"),
  ("spätestens drei Monate nach der Geburt; rückwirkend nur für drei.", "أقصاها ثلاثةُ أشهرٍ بعدَ الولادة، بأثرٍ رجعيٍّ لثلاثةِ أشهرٍ فحسب."),
  ("Mein Mann und ich teilen die Monate — wie wirkt sich Partnerschaftsbonus aus?", "نتقاسمُ الأشهر، فكيف يعملُ مكافأةُ الشراكةِ الزوجية؟"),
  ("Vier Monate gleichzeitig plus Bonus: je zwei Monate obendrauf für beide.", "أربعةُ أشهرٍ متزامنةٌ زائدَ مكافأة: شهرانِ لكلٍّ منكما."),
  ("Die Berechnung basiert auf dem Netto der letzten zwölf Monate?", "تحسبان على صافي الاثني عشرَ شهراً الماضية؟"),
  ("Ja — unteres Einkommen wird prozentual stärker ersetzt, bis 67 Prozent.", "نعم — الدخلُ الأدنى يُعوَّضُ نسبةً أعلى، إلى سبعةٍ وستين بالمئة."),
  ("Wo lade ich die Lohnbelege hoch, und in welchem Format?", "أين أرفعُ كشوفَ الرواتبِ وبأي صيغة؟"),
  ("Im Portal als PDF, je Monat ein Dokument — Scans ohne Stempel akzeptieren wir nicht.", "في البوابةِ PDF صفحةً لكلِّ شهر — وأما المسحُ بلا ختمٍ فلن يُقبَل.")],
 [("Wie lange rückwirkend?", "12 Monate", "3 Monate", "nie", 1, "أثرٌ رجعيٌّ لثلاثةِ أشهرٍ وحدَه."),
  ("Wie hoch maximal die Ersatzquote?", "67 Prozent", "100 Prozent", "50 Prozent", 0, "سبعةٌ وستون للمداخيل الدنيا تنزلقُ مع الغِنى."),
  ("Welche Form für Belege?", "Papier", "PDF je Monat, gestempelt", "Foto vom Handy", 1, "ملفٌ لكلِّ شهر — والختمُ شرط.")],
 ["Ja — unteres Einkommen wird prozentual stärker ersetzt, bis 67 Prozent.", "Im Portal als PDF, je Monat ein Dokument — Scans ohne Stempel akzeptieren wir nicht."]),

(14, "Steuererklärung: Frist und Fristverlängerung", "الإقرارُ الضريبي: الميعادُ وتأجيلُه", "Tarek", "Finanzamt-Hotline",
 [("Die Abgabefrist läuft — ich schaffe sie ohne Steuerberater nicht mehr.", "على وشك الانتهاء — ولن أُتمَّها دونَ مُستشارٍ ضريبيّ."),
  ("Mit Beratung verlängert sich die Frist automatisch bis April nächsten Jahres.", "بالاستعانةِ بمستشارٍ يمدَّدُ الأجلُ تلقائياً إلى أبريل العامِ القادم."),
  ("Welche Nachweise für die Homeoffice-Pauschale sind nötig?", "ما إثباتُ بدلِ العملِ المنزلي؟"),
  ("Arbeitszimmer-Grundriss, Verträge, Nebenkostenanteil — pauschal genügt der Nachweis der Nutzung.", "مخططُ الغرفة، العقود، ونسبةُ النفقات — وإثباتُ الاستعمالِ يكفي بدلَها."),
  ("Die Vorauszahlung wurde erhöht — Widerspruch möglich?", "زادت الدفعةُ المقدمة — أيعترضُ عليَّ؟"),
  ("Innerhalb eines Monats, aber nur mit geänderter Einkommensprognose.", "خلالَ شهرٍ واحد، وبشرطِ توقُّعِ دخلٍ معدَّل."),
  ("Reicht die Übermittlung über ELSTER als Nachweis des Eingangs?", "هل تكفي منصة ELSTER لإثباتِ الوصل؟"),
  ("Ja, die Sendebestätigung aufheben — sie ist das einzige Quittungsdokument.", "نعم — واحتفظْ بإشعارِ الإرسال، فهو الوصلُ الوحيد.")],
 [("Wie wird die Frist verlängert?", "formlos telefonisch", "automatisch mit Steuerberater", "nie", 1, "بمجردِ توكيلِ مستشارِ الضرائب."),
  ("Frist für den Widerspruch?", "ein Monat", "ein Jahr", "14 Tage", 0, "ثلاثون يوماً لا تزيد."),
  ("Welches Dokument beweist den Eingang?", "eine Mail des Amts", "die Sendebestätigung von ELSTER", "nichts", 1, "وصلُ المنصّةِ هو الدليلُ المُعتمَدُ الوحيد.")],
 ["Innerhalb eines Monats, aber nur mit geänderter Einkommensprognose.", "Mit Beratung verlängert sich die Frist automatisch bis April nächsten Jahres."]),

(15, "Wasserschaden: mit der Versicherung", "تلفُ الماء: مع شركةِ التأمين", "Rim", "Sachbearbeiter",
 [("Seit gestern quillt Wasser aus der Decke — Schaden gemeldet, Nummer 7714.", "منذ الأمسِ يتسرَّبُ الماءُ من السقف — أُعلِنَ الخطبُ برقم 7714."),
  ("Protokoll: Fotos, Uhrzeit, Handwerker-Notdienst bereits beauftragt?", "المحضر: صور، وقت، وهل استُقدمَ السبّاكُ الطارئ؟"),
  ("Ja — die Rechnung über die Sofortmaßnahme reicht ein, nicht die Endrechnung.", "نعم — تكفي فاتورةُ الإجراءِ الفوريّ لا الحسابُ النهائي."),
  ("Wir regulieren nach dem Gutachtertermin, binnen zwei Wochen.", "نُسَوِّي بعدَ زيارةِ الخبير، في موعدينِ كحدٍّ أقصى."),
  ("Und wenn der Vermieter den Mangel an der Hauptleitung trägt?", "وإن كان الخللُ في الأنبوبِ الرئيسي على المؤجِّر؟"),
  ("Dann halten wir uns den Rückgriff vor; Sie bekommen Vorschuss.", "نُبقي حقَّ الرجوع؛ وأنت تأخذين عربوناً الآن."),
  ("Mietausfall für die Trocknungszeit — zahlt die Versicherung?", "بدلُ انتفاعٍ أثناءَ التجفيف — على مَن؟"),
  ("Hausrat zahlt Trocknung und Hotel bis zur Wiederbewohnbarkeit; Mietminderung beim Vermieter.", "منقولاتُك تدفعُ التجفيفَ والفندقَ إلى السكنية؛ وتخفيضُ الإيجارِ على صاحبِ الملك.")],
 [("Wer zahlt das Hotel zuerst?", "die Versicherung", "das Amt", "der Nachbar", 0, "التأمينُ إلى أن تُصبِحَ الوحدةُ صالحة."),
  ("Was genügt für die Soforthilfe?", "Endrechnung", "Rechnung der Sofortmaßnahme", "mündliche Zusage", 1, "فاتورةُ الطوارئِ تُقبَلُ بلا إبطاء."),
  ("Wann Regulierung?", "sofort", "binnen zwei Wochen nach Gutachtertermin", "nie", 1, "أسبوعان بعدَ الخبيرِ لا أكثر.")],
 ["Wir regulieren nach dem Gutachtertermin, binnen zwei Wochen.", "Dann halten wir uns den Rückgriff vor; Sie bekommen Vorschuss."]),

(16, "Volkshochschule: Seminartermin tauschen", "جامعةُ الشعب: تبديلُ موعدِ Seminar", "Nadia", "Kursverwaltung",
 [("Der Samstagstermin kollidiert mit meiner Schicht — gegen einen Tausch wäre offen?", "موعدُ السبتِ يتصادمُ مع مناوبتي — أيجوزُ تبديلٌ؟"),
  ("Plätze frei im Donnerstagsblock ab 18; Umbuchung kostet 15 Euro.", "مقاعدُ الخميسِ بعدَ السادسةِ متاحة؛ والتحويلُ خمسةَ عشرَ يورو."),
  ("Wenn ich beim Füllen der Warteliste helfe — erlassen Sie die Gebühr?", "إن أعنتُ في استكمالِ قائمةِ الانتظار — فتتنازلون عنِ الرسم؟"),
  ("Fair — dann Tausch ohne Gebühr, aber die Anwesenheitspflicht bleibt heilig.", "منصف — بلا رسوم، لكنَّ إلزامَ الحضورِ يبقى مقدَّسًا."),
  ("Und wie viel Anwesenheit verlangt das Zertifikat?", "وكم حضورًا يشترطُ الختامُ بالشهادة؟"),
  ("Das Zertifikat setzt 80 Prozent Teilnahme voraus, nicht weniger.", "يشترطُ الختامُ ثمانينَ بالمئةِ حضورًا لا أقلّ."),
  ("Bei Krankheit in der Prüfungswoche: Nachschreibtermin?", "وإن مرضتُ في أسبوع الاختبار — أفُرصةُ تعويض؟"),
  ("Ärztliches Attest bis Montag, dann Nachtermin am Monatsersten.", "شهادةٌ طبيةٌ إلى الاثنين، ثم موعدٌ لاحقٌ أولَ الشهر.")]
 , [("Was kostet die Umbuchung am Ende?", "15 Euro", "nichts", "ein halbes Semester", 1, "تمَّ التحويلُ مجانًا مقابلَ مساعدةِ القائمة."),
    ("Teilnahmepflicht fürs Zertifikat?", "80 Prozent", "jede zweite Sitzung", "60 Prozent", 0, "ثمانونَ بالمئة نصٌّ لا يُنقص."),
    ("Attest wann nötig?", "binnen Montag", "nie", "nach einem Monat", 0, "شهادةُ الطبيبِ إلى الاثنينِ تفتحُ الموعدَ البديل.")]
 , ["Das Zertifikat setzt 80 Prozent Teilnahme voraus, nicht weniger.", "Bei Krankheit in der Prüfungswoche: Nachschreibtermin?"]),
(17, "Arbeitgeber und Weiterbildungskosten", "المُشغِّلُ وتكاليفُ التدريب", "Karim", "Personalleitung",
 [("Die Zertifikatskurse kosten 2.400 Euro — trägt die Firma einen Teil?", "دوراتُ الاعتمادِ بألفَينِ وأربعمئة — أيتحمَّلُ المصنعُ جزءاً؟"),
  ("Bei Branchennähe ja; Rückzahlungsklausel bei Wechsel unter 24 Monaten.", "لصلتها بمجالنا — بنُدَّ عنك إن انتقلتَ قبلَ أربعةَ وعشرين شهراً."),
  ("Die Klausel wäre zu akzeptieren, sofern bezahlte Freistellung mitzählt.", "سأقبلُ البندَ إن حُسِبَتِ الساعةُ المدفوعةُ ضمنَ التدريب."),
  ("Zwei Tage pro Monat frei gegen Bindung an ein Jahr Weiterbildung.", "يومانِ شهريّاً بإجازةٍ مدفوعةٍ مقابلَ ارتباطِ سنةٍ كاملة."),
  ("Und wenn ich während des Kurses Elterngeld nehme — Aussetzen?", "وإن أخذتُ بدلَ الوالدية أثناءَ الدورة — نُبقيها مجمَّدة؟"),
  ("Der Anspruch ruht; wir verlängern die Bindung um die Pause, nicht die Kosten.", "يتوقفُ الاستحقاق؛ نُطيلُ الارتباطَ بمقدارِ الغيابِ لا المال."),
  ("Schriftliche Vereinbarung über beides — dann melde ich mich an.", "اتفاقٌ خطيٌّ للاثنين، وحينئذٍ أسجِّلُ اسمي."),
  ("Morgen im Personalbüro, mit Ihren Zusatzstunden im Vertrag.", "غداً في قسمِ الأفراد، وستُدرَجُ الساعاتُ الإضافيةُ في عقدك.")],
 [("Was folgt aus einem Wechsel vor Ablauf?", "Prämie", " anteilige Rückzahlung", "nichts", 1, "ردٌّ نسبيٌّ للأموالِ حسبِ المدةِ المتبقية."),
  ("Wie wird die Elternzeit behandelt?", "Kurzer", "Anspruch ruht; Bindung wird verlängert", "Annullierung", 1, "التدريبُ يُجمَّدُ لا يُلغى، ويرتبطُ بغيابِه."),
  ("Wie viele freie Tage sind zugesagt?", "zwei pro Monat", "pro Jahr", "keine", 0, "يومانِ لكلِّ شهرٍ برتبةِ يومٍ مدفوع.")],
 ["Der Anspruch ruht; wir verlängern die Bindung um die Pause, nicht die Kosten.", "Bei Branchennähe ja; Rückzahlungsklausel bei Wechsel unter 24 Monaten."]),

(18, "Kündigung der Krankenkasse", "إنهاءُ عقدِ صندوقِ المرض", "Sami", "Kassenberatung",
 [("Ich möchte meine Versicherung zum Quartalsende kündigen.", "أودُّ فسخَ تأميني بنهايةِ الربع."),
  ("Frist läuft; die neue Kasse reicht die Kündigung digital ein.", "الميعادُ جارٍ؛ وصندوقُك الجديدُ يتولّى الإبلاغَ رقمياً."),
  ("Was geschieht mit dem Bonusheft und den Dauermedikamenten?", "ماذا يحدثُ لدفترِ المكافآتِ والأدويةِ المزمنة؟"),
  ("Das Heft bleibt gültig, die Medikamente laufen nahtlos über die elektronische Verordnung.", "يبقى الدفترُ سارياً، والأدويةُ تنتقلُ دونَ انقطاعٍ عبرَ الوصفةِ الإلكترونية."),
  ("Lückenlos versichert — darf ich im Übergangsmonat zum Arzt?", "تغطيةٌ متواصلة — أأذهبُ للطبيبِ في شهرِ العبور؟"),
  ("Ja, der Versicherungsschutz bleibt bis zum letzten Tag bestehen.", "نعم — تظلُّ الحمايةُ ساريةً إلى آخرِ يومٍ من العقد."),
  ("Die Beitragsanteile des Arbeitgebers — wer rechnet ab?", "وحصةُ صاحبِ العملِ من الاشتراكات — مَن يُسَوِّيها؟"),
  ("Die Buchhaltung beider Kassen tut das unter sich; Sie erhalten eine Sammelbescheinigung.", "يتصالحُ محاسبو الصندوقَين بينهما، وتصلُك شهادةٌ إجماليةٌ موحَّدة.")],
 [("Wie kündigt man korrekt?", "per Fax", "die neue Kasse digital", "mündlich", 1, "الصندوقُ الجديدُ يرفعُ الحِملَ رقمياً."),
  ("Schutzlücke im Wechselmonat?", "ja", "nein, lückenlos", "nur stationär", 1, "لا فجوة — حتى آخرِ يومٍ تأمين."),
  ("Wer zahlt den Papierkram der Beiträge?", "der Kunde", "die Kassen unter sich", "der Arzt", 1, "الصندوقانِ يُحصيان، والنتيجةُ شهادةٌ واحدة.")],
 ["Ja, der Versicherungsschutz bleibt bis zum letzten Tag bestehen.", "Das Heft bleibt gültig, die Medikamente laufen nahtlos über die elektronische Verordnung."]),

(19, "Konflikt im Team: Moderation", "نزاعٌ في الفريق: تَوسُّط", "Leila", "Teamleitung",
 [("Die Absprache mit der Einkaufsabteilung ist zweimal gekippt — ohne Rückmeldung.", "اتفاقُنا مع قسمِ المشترياتِ انقلبَ مرتين، دونَ إخطار."),
  ("Was haben Sie selbst unternommen?", "وما الذي فعلتِه أنتِ؟"),
  ("Ich habe die Protokolle datiert und die Kritik sachlich formuliert — per Mail, nicht im Chat.", "وثَّقتُ المحاضرَ بالتواريخ وكتبتُ الاعتراضَ بموضوعيةٍ بالبريدِ لا بالمحادثة."),
  ("Gut so. Dann setzen wir einen runden Tisch: jede Seite nennt drei Bedürfnisse.", "أحسنتِ — نجعلُ طاولةً مستديرة: كلُّ جهةٍ تُسمِّي ثلاثَ حاجات."),
  ("Meine Priorität: verbindliche Lieferfristen statt Zurufen im Flur.", "أولويتي: مواعيدُ تسليمٍ مُلزِمةٌ لا نداءاتٌ في الممرّ."),
  ("Vereinbart wird ein Protokoll mit Fristen, das beide gegenzeichnen.", "نُثبِتُ في المحضرِ المواعيدَ ويوقِّعُها الطرفانِ جميعاً."),
  ("Verstanden — und ich bringe die Zahlen für den Vergleich bis Mittwoch mit.", "فهمتُ — وأُحضِرُ أرقامَ المقارنةِ إلى الأربعاءِ لا أكثر."),
  ("Konstruktiv. Wiedervorlage nach sechs Wochen — damit es nicht verpufft.", "بنّاءٌ الأمر. نُعيدُ العرضَ بعدَ ستةِ أسابيع لئلا يخبوَ الأثر.")],
 [("Wie dokumentierte Leila zunächst?", "mündlich", "per Mail mit Daten", "über den Chat", 1, "بريدٌ موثَّقٌ بالتواريخ — لا ثرثرةُ ردهة."),
  ("Was wird am runden Tisch gemacht?", "Schimpfen", "jede Seite nennt drei Bedürfnisse", "abstimmen", 1, "ثلاثُ حاجاتٍ من كلِّ طرفٍ لا أكثر."),
  ("Wie wird Druck erzeugt?", "durch Gerüchte", "unterzeichnete Fristen und Wiedervorlage", "gar nicht", 1, "التواقيعُ والمواعيدُ المتبادَلةُ هي الضابطُ الوحيد.")],
 ["Gut so. Dann setzen wir einen runden Tisch: jede Seite nennt drei Bedürfnisse.", "Konstruktiv. Wiedervorlage nach sechs Wochen — damit es nicht verpufft."]),

(20, "Pflegeversicherung: Begutachtung", "تأمينُ الرعاية: تقديرُ اللجنة", "Hedi", "Gutachter",
 [("Mein Vater hatte vor vier Wochen einen Schlaganfall — wie hoch wird der Pflegegrad sein?", "أصابَ أبي جلطةٌ قبلَ أربعةِ أسابيع — فما درجةُ رعايتِه المتوقعة؟"),
  ("Wir bewerten Selbstständigkeit, nicht die Diagnose allein.", "نقيّمُ الاستقلاليةَ لا التشخيصَ وحدَه."),
  ("Morgens braucht er Hilfe beim Waschen und Anziehen, mittags reicht Aufsicht.", "صباحًا يُعينُ على الغسلِ واللباس، وعندَ الظهرِ يكفي الإشراف."),
  ("Nächtliche Unruhe und Sturzangst — dokumentieren Sie das bitte im Tagebuch.", "قلقٌ ليليٌّ وخوفُ سقوط — دوّنوا ذلك في المذكرةِ من فضلكم."),
  ("Die zweiwöchige Liste ist vorbereitet, mit Uhrzeiten.", "القائمةُ الأسبوعيةُ جاهزةٌ بساعاتِها."),
  ("Dann rechne ich mit Grad zwei bis drei, je nach Wegstrecke innerhalb der Wohnung.", "أتوقعُ الدرجةَ الثانيةَ إلى الثالثة، بحسب المسافةِ التي يقطعُها داخل الشقة."),
  ("Und wie lange dauert der Bescheid — was, wenn die Bewertung zu knapp ausfällt?", "وكم يستغرقُ القرار — وإن جاءَ التقديرُ بخيلًا؟"),
  ("Schriftlich binnen 25 Arbeitstagen; bei zu knapper Bewertung: Widerspruch.", "خطيًّا خلالَ خمسةٍ وعشرين يومَ عمل؛ ومع التقديرِ البخيل: اعتراض.")]
 , [("Was zählt wirklich?", "die Diagnose", "die Selbstständigkeit im Alltag", "das Alter", 1, "لا المرضُ في الورقة، بل الاستقلاليةُ في الصباحِ والمساء."),
    ("Welche Vorbereitung half?", "Arztbrief allein", "das Pflegetagebuch mit Uhrzeiten", "nichts", 1, "مذكرةٌ أسبوعيةٌ بساعاتِ العنايةِ هي التي رجَّحت."),
    ("Wie lange bis zum Bescheid?", "10 Tage", "25 Arbeitstage", "ein halbes Jahr", 1, "خمسةٌ وعشرونَ يومَ عملٍ نصٌّ إداري.")]
 , ["Morgens braucht er Hilfe beim Waschen und Anziehen, mittags reicht Aufsicht.", "Dann rechne ich mit Grad zwei bis drei, je nach Wegstrecke innerhalb der Wohnung."]),
(21, "Bildungskredit verhandeln", "تفاوضٌ على قرضٍ تعليمي", "Maha", "Bankberaterin",
 [("Der Bildungskredit deckt mein letztes Studienjahr nicht — Möglichkeit einer Aufstockung?", "قرضي التعليميُّ لا يغطي السنةَ الأخيرة — أيمكنُ الزيادة؟"),
  ("Höchstbetrag staatlich gedeckelt; bankseitig ein zinsgünstiges Darlehen mit Bürgschaft.", "الحدُّ الأقصى مكفولٌ اتحادياً؛ وقرضٌ مصرفيٌّ ميسَّرُ الربا بضمانٍ شخصيٍّ منا."),
  ("Die Rückzahlung möchte ich nach dem zweiten Berufsjahr beginnen.", "يسرُّني بدءُ السدادِ بعدَ سنتَين من المزاول."),
  ("Karenzzeit bis 18 Monate möglich; die Zinsen laufen weiter, werden gestundet.", "مهلةُ سماحٍ ثمانيةَ عشرَ شهراً؛ والفائدةُ تجري مُؤجَّلةً لا مُلغاة."),
  ("Welche Tilgungsrate ist realistisch beim Einstieggehalt?", "وما قسطُ تسديدٍ واقعيٌّ براتبِ البداية؟"),
  ("Zwischen 120 und 200 Euro, abhängig vom Zinsnachlass bei Gehaltsüberweisung.", "بين مئةٍ وعشرين ومئتين — على حسبِ تخفيضِ الفائدةِ بتحويلِ المرتب."),
  ("Sonderzahlung zweimal jährlich — damit wäre eine jährliche Sondertilgung vereinbart.", "ومكافأتانِ سنويّاً تجعلُ سدادَ دفعةٍ إضافيةٍ كلَّ عامٍ بديلاً."),
  ("So fixieren wir es im Bescheid — Unterschrift online per eID.", "سنثبِّتُه في القرار؛ فالتوقيعُ على المنصّةِ بالهويّةِ الإلكترونية.")],
 [("Worauf gründet der Zinsnachlass?", "Status", "Gehaltsüberweisung über die Bank", "Kaution", 1, "حوالةُ الراتبِ عبرَ المصرفِ تُنقِصُ الفائدة."),
  ("Was geschieht während der Karenz?", "Zinsen laufen und werden gestundet", "alles ruht", "sofort zahlen", 0, "الفائدةُ تجري في الظلِّ وتُجَمَّدُ السدادُ عنها."),
  ("Wodurch wird Sondertilgung gedeckt?", "Ersparnis", "die zwei Sonderzahlungen", "Bürgschaft", 1, "مكافأتا السنةِ تُمَوِّلان الدفعةَ الاستثنائية.")],
 ["Karenzzeit bis 18 Monate möglich; die Zinsen laufen weiter, werden gestundet.", "Zwischen 120 und 200 Euro, abhängig vom Zinsnachlass bei Gehaltsüberweisung."]),

(22, "Überweisung zum Facharzt: Dringlichkeit", "تحويلةٌ إلى الاختصاصي: حالةُ استعجال", "Imen", "Ärztin",
 [("Die Überweisung zum Radiologen dauert Wochen — meine Schmerzen lassen nicht nach.", "التحويلةُ إلى طبيبِ الأشعةِ تمتدُّ أسابيع — وألمي لا يرحم."),
  ("Wir stufen als akut ein: Dringlichkeitscode C auf dem Schein verkürzt die Wartezeit.", "نُدرجُها طارئة: رمزُ C على الوصفةِ يقصُمُ ظهرَ الانتظار."),
  ("Kann eine Zweitüberweisung an ein anderes Krankenhaus helfen?", "أنجدي تحويلَةٌ ثانيةً إلى مستشفى آخر؟"),
  ("Parallel ja, aber die Akten müssen austauschbar sein — mit Ihrem Einverständnis.", "متوازياً نعم، على أن تتبادَلَ الملفاتُ بموافقتكِ الخطيةِ الموقَّعة."),
  ("Welche Befunde braucht der Facharzt zwingend?", "ما النتائجُ التي لا غنى عنها للطبيبِ المختص؟"),
  ("Laborwerte der Woche, Voraufnahmen im DICOM-Format, keine Komprimierung.", "تحاليلَ الأسبوعِ الطازجة، وصورًا صيغة DICOM غيرَ مضغوطة."),
  ("Der Termin bestätigt — wie storniere ich, falls es früher klappt?", "حُجِزَ الموعد — وإن فرَجَ الله قبلَه، فكيف ألغي؟"),
  ("Ein Anruf genügt; der Platz wandert sofort auf die Nachrückliste.", "مكالمةٌ واحدة — فيقفزُ الصفُّ إلى قائمةِ المُستخلفين حالاً.")],
 [("Was verkürzt die Wartezeit?", "Bargeld", "der Dringlichkeitscode C", "zweite Karte", 1, "الرمزُ الطبيُّ C من يدِ الطبيبةِ المختصرة."),
  ("Welche Bedingung für Parallelüberweisung?", "keine", "schriftliches Einverständnis zur Aktenweitergabe", "ein Anwalt", 1, "موافقةٌ خطيةٌ بأن تتبادلَ المستشفياتِ ملفَّكِ."),
  ("Wie werden Bilder angeliefert?", "USB unkomprimiert", "per E-Mail", "gar nicht", 0, "DICOM كما هو، بلا ضغطٍ يُطيَرُ منه التفصيل.")],
 ["Wir stufen als akut ein: Dringlichkeitscode C auf dem Schein verkürzt die Wartezeit.", "Parallel ja, aber die Akten müssen austauschbar sein — mit Ihrem Einverständnis."]),

(23, "Betriebsrat: Überstundenkonflikt", "لجنةُ العاملين: نزيفُ الساعات", "Amir", "Betriebsrätin",
 [("Im Lager sammeln sich Überstunden — der Ausgleich fehlt seit März.", "في المستودعِ تكدَّست ساعاتٌ إضافية، وتعويضُها غائبٌ منذ مارس."),
  ("Das Arbeitszeitkonto muss monatlich ausgeglichen werden — wir haben die Betriebsvereinbarung.", "يجبُ تصفيةُ حسابِ العملِ شهريّاً؛ وقد نصَّت اتفاقُنا التنظيميُّ على ذلك."),
  ("Vorschlagen Sie eine Zeitschiene statt Auszahlung?", "أتقترحون رصيداً زمنيّاً بدلَ النقد؟"),
  ("Frei im Block: zwei Tage plus Zuschlag pro Überstunde laut Tarif.", "عطلةٌ متتابعة: يومانِ وعلاوةٌ لكلِّ ساعةٍ بحكمِ الاتفاقية."),
  ("Der Schichtplan lässt das nicht zu — wir brauchen das Kontingent vor Ostern abgebaut.", "جدولُ المناوباتِ لا يسمح — علينا تفكيكُ الرصيدِ قبلَ الفصح."),
  ("Wir setzen die Liste am Montag mit dem Schichtleiter durch — verbindlich.", "سنُنَفِّذُ القائمةَ الاثنين مع قائدِ المناوبة — بيقينٍ لا مع وعود."),
  ("Was tun, wenn die Firma ignoriert?", "وماذا لو تجاهلتِ الإدارة؟"),
  ("Dann Einigungsstelle; der Spruch ersetzt die Weigerung des Arbeitgebers.", "إذن لجنةُ التوفيق، وحكمُها يحلُّ محلَّ عنادِ صاحبِ العمل.")],
 [("Wozu verpflichtet die Betriebsvereinbarung?", "Quartal", "monatlichen Ausgleich des Zeitkontos", "nichts", 1, "التسويةُ الشهريةُ في نصِّ الاتفاق."),
  ("Welches Druckmittel steht bereit?", "Kündigung", "die Einigungsstelle", "Presse", 1, "لجنةُ التوفيقِ قرارُها بديلُ العناد."),
  ("Was verlangt Amir zeitlich vor Ostern?", "Bonus", "Abbau des Kontingents", "Überstundenabbau nur im Sommer", 1, "تفكيكُ الرصيدِ قبلَ إجازةِ الفصح.")],
 ["Frei im Block: zwei Tage plus Zuschlag pro Überstunde laut Tarif.", "Dann Einigungsstelle; der Spruch ersetzt die Weigerung des Arbeitgebers."]),

(24, "Integrationskurs: Prüfungswiederholung", "دورةُ الاندماج: إعادةُ الامتحان", "Firas", "Kursleitung",
 [("Ich habe die telc-Prüfung B1 knapp bestanden — Zertifikat oder nicht?", "نجحتُ بفارقٍ ضئيلٍ في امتحان telc B1 — أليَّ شهادة؟"),
  ("Bestanden ist bestanden — das Zertifikat kommt nach vier Wochen per Post.", "نجحتَ ولو شعرة: ستصلُك الشهادةُ بالبريدِ خلالَ أربعةِ أسابيع."),
  ("Für meine Aufenthaltserlaubnis fehlt der Nachweis der Wiederholung nicht?", "وليس مطلوباً منّي إثباتُ إعادةٍ لإقامتي؟"),
  ("Bei Bestehen keine — Wiederholungen nur bei Nichtbestehen, maximal zweimal.", "عندَ النجاحِ لا شيء؛ والإعادةُ للحاصلِ فقط على الراسب، مرتينِ كحدٍّ أقصى."),
  ("Falls ich die B2-Prüfung ablegen will: Anmeldung über die Volkshochschule?", "وإن أردتُ B2: التسجيلُ عبرَ جامعةِ الشعب؟"),
  ("Direkt über das Sprachenzentrum, Termin im Frühjahr — Warteliste inklusive.", "من مركزِ اللغاتِ مباشرة؛ موعدُ الربيع، وقائمةُ الانتظارِ مضمَّنةٌ لك."),
  ("Welche Fördermittel greifen bei wiederholtem Versuch?", "وما المنحُ لمن أُعيدَ كرَّةُ الفشل؟"),
  ("Die Kursträger können die Gebühren halbieren — Antrag binnen zwei Wochen.", "قد يُخفِّضُ حاملو الدورةِ نصفَ الرسوم؛ فاطلبْ خلالَ أسبوعَين لا أكثر.")],
 [("Was erhält Firas trotz knappen Bestehens?", "nichts", "das volle Zertifikat", "eine Wiederholungsgebühr", 1, "الشهادةُ كاملة — الفارقُ الضيقُ لا يُنقِصُ حكماً."),
  ("Wie viele Wiederholungen bei Nichtbestehen?", "1", "2", "unbegrenzt", 1, "كرَّتان لا ثالثَ لهما، ثم يُقفَلُ الباب."),
  ("Wer trägt die Anmeldegebühr für B2?", "niemand", "Sprachenzentrum mit Liste", "nur bei Bestehen", 1, "المركزُ يفتحُ التسجيلَ مع قائمةِ انتظار.")],
 ["Bestanden ist bestanden — das Zertifikat kommt nach vier Wochen per Post.", "Die Kursträger können die Gebühren halbieren — Antrag binnen zwei Wochen."]),

(25, "Beschwerde über den Lieferdienst", "شكوى على خدمةِ التوصيل", "Selim", "Servicecenter",
 [("Die Sendung kam drei Tage später an, das Kühlpaket war offen.", "وصلتِ الشحنةُ متأخرةً ثلاثةَ أيام، وكان ثلجُ التبريدِ مفتوحاً."),
  ("Belegfotos, Packzettel und Zeitstempel der Tür — dann öffnen wir das Verfahren.", "صورُ البضاعة، ورقةُ التعبئة، وختمُ الوقتِ عند الباب — فنفتحُ ملفاً."),
  ("Die Ware selbst ist einwandfrei; ich verlange die Versandgebühr zurück.", "السلعةُ سليمة؛ أريدُ فقط ردَّ مصاريفِ الشحن."),
  ("Rückerstattung plus 10 Euro-Gutschein, Gutschrift binnen 72 Stunden.", "سيُعادُ المبلغُ ويُهَدى عشرُ يوروهات خلالَ ثمانٍ وسبعينَ ساعة (72)."),
  ("Wenn der Kurier wiederholt öffnet — hat er Konsequenzen?", "وإن تكرَّرَ فتحُ الحقائبِ — فماذا عليه؟"),
  ("Wir protokollieren die Charge und setzen ihn bis zur Schulung vom Dienst.", "نسجِّلُ الشحنةَ ونُوقِفُه عن الخدمةِ إلى أن يُدرَّب."),
  ("Muss die Beschwerde auf Englisch sein? Ich schreibe sie gern um.", "هل يلزمُ أن تكونَ الشكوى بالإنجليزية؟ أُعيدُ صياغتَها إن شئتُم."),
  ("Reicht auf Deutsch — unser Haus übersetzt für Sie ins Englische.", "بالألمانيةِ تكفي؛ دارُنا تُترجمُها عنك إلى الإنجليزية.")],
 [("Was wird erstattet?", "der gesamte Einkauf", "die Versandgebühr plus Gutschein", "nichts", 1, "مصاريفُ الشحنِ مع قسيمةِ عشرة."),
  ("Wie schnell?", "72 Stunden", "ein Monat", "sofort", 0, "اثنتانِ وسبعونَ ساعةً — لا تأخيرَ بعدها."),
  ("Welche Beweise nötig?", "nur Erinnerung", "Fotos, Packzettel, Zeitstempel", "die Kurierbescheinigung", 1, "ثلاثيةٌ موثَّقةٌ بالصورةِ والورقةِ والوقت.")],
 ["Wir protokollieren die Charge und setzen ihn bis zur Schulung vom Dienst.", "Belegfotos, Packzettel und Zeitstempel der Tür — dann öffnen wir das Verfahren."]),

(26, "Promotion: Betreuungswechsel", "الدكتوراه: تغييرُ المشرف", "Amina", "Dekan",
 [("Meine Betreuerin geht in den Ruhestand — die Betreuung muss neu geordnet werden.", "مشرفتي على التقاعد — فأعيِدوا توزيعَ الإشراف."),
  ("Wir brauchen eine neue Erstprüferin mit gleicher Qualifikation, binnen sechs Wochen.", "نحتاجُ ممتحنةً أولى بكفاءتِها نفسِها — في ستةِ أسابيع."),
  ("Herr Dr. Weiler erklärte sich bereit, sofern die Dissertationsrichtung bleibt.", "الدكتور فايلرُ أبدى الاستعداد، بشرطِ بقاءِ اتجاهِ الرسالة."),
  ("Dann unterschreiben beide den Wechsel; die alten Gutachten werden übertragen.", "إذن يوقِّعُ الاثنانِ الانتقال؛ وتُنقلُ التقييماتُ السابقةُ كما هي."),
  ("Mein Kolloquiumstermin verschiebt sich damit?", "فهَل يتزحزحُ ميعادُ مناقشتي؟"),
  ("Nein — er bleibt, es sei denn, Sie beantragen einen Aufschub.", "لا — يبقى موعده ما لم تتقدَّمي بطلبِ تأجيل."),
  ("Und was verlangt die Promotionsordnung zusätzlich?", "وماذا تفرضُ لائحةُ الدكتوراه زيادةً؟"),
  ("Zwei externe Gutachten — die Verwaltung holt sie bis Monatsende ein.", "تقاريرُ خارجيةٌ اثنان — والإدارةُ تستحصِلُها بنهايةِ الشهر.")]
 , [("Was muss innerhalb von sechs Wochen geschehen?", "Verteidigung", "neue Erstprüferin bestellt werden", "nichts", 1, "تعيينُ ممتحنةٍ أولى بالكفاءةِ نفسِها."),
    ("Was bleibt beim Wechsel erhalten?", "alle Stipendien", "die alten Gutachten", "die Studiengebühren", 1, "التقاريرُ السابقةُ تُنقَلُ بلا إعادة."),
    ("Was verlangt die Ordnung zusätzlich?", "ein drittes Seminar", "zwei externe Gutachten", "Prüfungsgebühr", 1, "خبرانِ من خارجِ الجامعةِ إلزامٌ نظامي.")]
 , ["Dann unterschreiben beide den Wechsel; die alten Gutachten werden übertragen.", "Nein — er bleibt, es sei denn, Sie beantragen einen Aufschub."]),
(27, "Nachbarschaftsstreit: Schlichtung", "خلافُ الجيرة: مصلحةُ الصلح", "Yara", "Schiedsfrau",
 [("Die Hecke meines Nachbarn ragt 40 Zentimeter auf mein Grundstück — die Mahnung half nicht.", "سياجُ جاري يتدخَّلُ أربعينَ سنتيمترًا في أرضي — وما أفادَ الإنذارُ الخطّي."),
  ("Vor der Klage gehört der Schlichtungsversuch zur Pflicht — dazu bin ich da.", "قبلَ أيِّ دعوى تجبُ محاولةُ الصلح — ولأجلِها وُجِدَ مكتبي."),
  ("Wenn er die Grenze akzeptiert — verzichte ich auf Schadensersatz.", "إن قبلَ بالحدّ — فأَتنازلتُ عنِ التعويض."),
  ("Dann schlage ich einen Vergleich mit Frist zum Rückschnitt vor.", "إذن أقترحُ صلحًا بمهلةٍ مُلزِمةٍ للتقليم."),
  ("Und die Frist — kann die gerichtlich bestätigt werden?", "وهَل تُصدَّقُ المهلةُ قضائيًّا؟"),
  ("Ja — bei Verstoß droht ein Zwangsgeld bis 250.000 Euro.", "نعم — وكلُّ إخلالٍ يُعرِّضُ لغرامةٍ جبريةٍ تبلغُ مئتينِ وخمسينَ ألفَ يورو."),
  ("Welche Unterlagen brauche ich für den Termin?", "ما أوراقُ موعدِكِ؟"),
  ("Katasterauszug, Fotos mit Maßstab, die Mahnung von damals, zwei Zeugen genügen.", "كشفٌ عقاري، صورٌ بمعيار، خطابُ الإنذار، وشاهدانِ يكفيان."),
  ("Und wenn er zum Termin nicht erscheint?", "وإن لم يحضرِ الموعد؟"),
  ("Dann wird das Scheitern protokolliert — und die Klage wird zulässig.", "يُحرَّرُ محضرُ الفشلِ — فتُصبِحُ الدعوى مقبولة.")]

 , [("Was ist vor der Klage Pflicht?", "Mediation durch Zeitungen", "ein Schlichtungsversuch", "eine Mahnwache", 1, "محاولةُ الصلحِ شرطُ قبولِ الدعوى."),
    ("Was geschieht nach Verweigerung?", "Freispruch", "Protokoll des Scheiterns", "ein Bußgeld", 1, "محضرُ فشلٍ يفتحُ بابَ القضاء."),
    ("Was wird mit Zwangsgeld gesichert?", "die Heckenfarbe", "die Frist zum Rückschnitt", "die Ruhezeit", 1, "غرامةٌ جبريةٌ خلفَ مهلةِ التقليمِ لا ألوانَ الشجر.")]
 , ["Vor der Klage gehört der Schlichtungsversuch zur Pflicht — dazu bin ich da.", "Katasterauszug, Fotos mit Maßstab, die Mahnung von damals, zwei Zeugen genügen."]),
]
# إصلاحُ شائبةِ رقمٍ في 25 (سبعٌ وسبعون→ثلاثٌ وسبعون لا؛ الفاتورةُ 72 ساعة)
for i, row in enumerate(D18):
    if row[0] == 25:
        l = list(row[5])
        l[3] = ("Rückerstattung plus 10-Euro-Gutschein — gutgeschrieben binnen 72 Stunden.", "يُرَدُّ المبلغُ وتُهْدَى قسيمةُ عشرةِ يوروهاتٍ خلالَ اثنتينِ وسبعينَ ساعة.")
        q = list(row[6]); q[1] = ("Wie schnell?", "binnen 72 Stunden", "ein Monat", "sofort", 0, "اثنتانِ وسبعونَ ساعةً — لا تأخيرَ بعدها.")
        D18[i] = (row[0], row[1], row[2], row[3], row[4], l, q, row[7])
        break
for (n, td, ta, A, B, lines, qs, dic) in D18:
    assert len(lines) >= 7, n
    for de, ar in lines:
        assert ARc.search(ar) and not CJK.search(ar) and de.strip() and not ARc.search(de) and not CJK.search(de), (n, de[:36])
    assert len(qs) == 3, n
    for (p, o1, o2, o3, ai, ex) in qs:
        assert len({o1, o2, o3}) == 3 and ai in (0, 1, 2) and ARc.search(ex), (n, p)
    all_de = [x[0] for x in lines]
    for d in dic:
        assert d in all_de, (n, d[:36])
print("بنيةُ B2 نظيفةٌ — 18 حواراً")
json.dump(D18, open("/tmp/d28.json", "w", encoding="utf8"), ensure_ascii=False)
