#!/usr/bin/env python3
"""R139: add more Fehler (Fehlerfallen) at B1/B2 for common Arabic L1 mistakes."""
import json
from collections import OrderedDict, Counter

NEUE = [
    # B1
    OrderedDict([("id","f129"),("kat","konstruktion"),("level","B1"),
        ("falsch","*Ich freue mich auf dich zu sehen."),
        ("richtig","Ich freue mich darauf, dich zu sehen. / Ich freue mich, dich zu sehen."),
        ("ar","بعد «sich freuen» لا يأتي «auf … zu» مباشرة، بل إما «darauf, dass» أو مصدر بـzu مباشر أو «auf + اسم»."),
    ]),
    OrderedDict([("id","f130"),("kat","praeposition"),("level","B1"),
        ("falsch","*Ich warte auf den Bus seit 10 Minuten."),
        ("richtig","Ich warte seit 10 Minuten auf den Bus."),
        ("ar","في الألمانية ترتيب المكمّلات: الزمان قبل المكان. لا تضع auf-Objekt قبل seit."),
    ]),
    OrderedDict([("id","f131"),("kat","wortstellung"),("level","B1"),
        ("falsch","*Weil ich bin krank, gehe ich nicht zur Arbeit."),
        ("richtig","Weil ich krank bin, gehe ich nicht zur Arbeit."),
        ("ar","في الجملة الثانوية بـweil/da/dass يذهب الفعل إلى النهاية: «Weil ich krank bin»."),
    ]),
    OrderedDict([("id","f132"),("kat","zeitform"),("level","B1"),
        ("falsch","*Gestern habe ich gehen ins Kino."),
        ("richtig","Gestern bin ich ins Kino gegangen."),
        ("ar","أفعال الحركة (gehen/kommen/fahren/fliegen/laufen/reisen) تستخدم sein لا haben في Perfekt، والجزء الثاني في آخر الجملة."),
    ]),
    OrderedDict([("id","f133"),("kat","artikel"),("level","B1"),
        ("falsch","*Ich fahre zu der Bahnhof."),
        ("richtig","Ich fahre zum Bahnhof."),
        ("ar","Bahnhof مذكر، لذا «zu dem» تُدمَج إلى «zum». لا تقل «zu der Bahnhof»."),
    ]),
    OrderedDict([("id","f134"),("kat","schreibung"),("level","B1"),
        ("falsch","*That´s / das selbe"),
        ("richtig","daß? Nein — dass! / dasselbe (ein Wort)"),
        ("ar","«dass» بلا ß بعد إصلاح الإملاء، و«dasselbe» كلمة واحدة (selbe لا تُكتَب منفصلة عن das إذا صحبها -selbe)."),
    ]),
    OrderedDict([("id","f135"),("kat","wortschatz"),("level","B1"),
        ("falsch","*Ich mache einen Spaziergang in dem Park."),
        ("richtig","Ich mache einen Spaziergang im Park."),
        ("ar","تستخدم «im» (in + dem) لدخول الحديقة والحديقة كمكان لا يتطلب «in dem» منفصلاً إلا للتشديد — im Park هو الشائع.")
    ]),
    OrderedDict([("id","f136"),("kat","konstruktion"),("level","B1"),
        ("falsch","*Ich bin langweilig."),
        ("richtig","Mir ist langweilig."),
        ("ar","للتعبير عن الشعور بالملل: «Mir ist langweilig» (كان الفضول لي؟). «Ich bin langweilig» تعني «أنا مملّ»! زِد: Mir ist kalt/warm/schlecht/langweilig/übel."),
    ]),
    OrderedDict([("id","f137"),("kat","praeposition"),("level","B1"),
        ("falsch","*Ich erinnere mich an dem Termin."),
        ("richtig","Ich erinnere mich an den Termin."),
        ("ar","sich erinnern an + Akkusativ، لذا den Termin لا dem."),
    ]),
    OrderedDict([("id","f138"),("kat","konstruktion"),("level","B1"),
        ("falsch","*Es gibt viele Leute, die wollen nicht arbeiten."),
        ("richtig","Es gibt viele Leute, die nicht arbeiten wollen."),
        ("ar","جملة Relativ تحتاج إلى الفعل في نهايتها: die nicht arbeiten wollen."),
    ]),
    # B2
    OrderedDict([("id","f139"),("kat","konstruktion"),("level","B2"),
        ("falsch","*Obwohl er hat viel gelernt, hat er die Prüfung nicht bestanden."),
        ("richtig","Obwohl er viel gelernt hat, hat er die Prüfung nicht bestanden."),
        ("ar","بعد Konzessivsätze mit obwohl/trotzdem/obgleich يأتي الفعل في نهاية الجملة الثانوية."),
    ]),
    OrderedDict([("id","f140"),("kat","wortstellung"),("level","B2"),
        ("falsch","*Nicht nur er spricht Deutsch, sondern auch Englisch."),
        ("richtig","Er spricht nicht nur Deutsch, sondern auch Englisch."),
        ("ar","nicht nur … sondern auch يربط عنصرين متوازيين من الجملة، ولا تبدأ به الجملة عادةً."),
    ]),
    OrderedDict([("id","f141"),("kat","zeitform"),("level","B2"),
        ("falsch","*Wenn ich nach Hause kam, hatte ich schon gegessen."),
        ("richtig","Als ich nach Hause kam, hatte ich schon gegessen."),
        ("ar","حدث لمرة واحدة في الماضي: استخدم «als» لا «wenn» (wenn = متكرر/مستقبل/شرط)."),
    ]),
    OrderedDict([("id","f142"),("kat","schreibung"),("level","B2"),
        ("falsch","*man kann / *dass man kann"),
        ("richtig","man (Indefinitpronomen) — nicht « Mann » (الرجل)"),
        ("ar","«man» ضمير نكرة لا يُكتب «Mann». أما Mann فهو رجل."),
    ]),
    OrderedDict([("id","f143"),("kat","praeposition"),("level","B2"),
        ("falsch","*Ich interessiere mich für das Buch nicht."),
        ("richtig","Ich interessiere mich nicht für das Buch."),
        ("ar","موقع nicht قبل الجزء المراد نفيه أو قبل für+Akkusativ في حالة النفي الكامل."),
    ]),
    OrderedDict([("id","f144"),("kat","konstruktion"),("level","B2"),
        ("falsch","*Laut dem Arzt soll ich viel trinken."),
        ("richtig","Laut Arzt soll ich viel trinken. (أو Laut des Arztes مع Genitiv)"),
        ("ar","«laut» غالباً تستخدم بلا أداة: laut Arzt. ويمكن Genitiv (laut des Arztes) لكن ليس Dativ في الفصحى."),
    ]),
    OrderedDict([("id","f145"),("kat","zeitform"),("level","B2"),
        ("falsch","*Bis nächsten Monat habe ich die Arbeit beendet."),
        ("richtig","Bis nächsten Monat werde ich die Arbeit beendet haben."),
        ("ar","للمستقبل التام (الانتهاء قبل نقطة في المستقبل) نستخدم Futur II: werde … Partizip II haben/sein."),
    ]),
    OrderedDict([("id","f146"),("kat","artikel"),("level","B2"),
        ("falsch","*Ich gehe in die Schule."),
        ("richtig","Ich gehe zur Schule."),
        ("ar","للذهاب للمدرسة/العمل/الجامعة كعاد يومي: zur Schule/zur Arbeit، وليس في die Schule في سياق العادة."),
    ]),
    OrderedDict([("id","f147"),("kat","falsche-freunde"),("level","B2"),
        ("falsch","*aktuell = aktuell / Actually, das Problem ist…"),
        ("richtig","aktuell = حاليّ/جارٍ الآن / tatsächlich/wirklich = فعلي actually"),
        ("ar","aktuell ≈ حالي لا «فعلي»؛ مقابل actually الإنجليزية هو tatsächlich أو wirklich."),
    ]),
    OrderedDict([("id","f148"),("kat","konstruktion"),("level","B2"),
        ("falsch","*Je mehr du lernst, desto besser wirst du."),
        ("richtig","Je mehr du lernst, desto besser wirst du (هذه الجملة صحيحة أصلاً — لكن تنبيه: desto immer mit Komparativ!)"),
        ("ar","بناء je … desto … يتطلب صيغة المقارنة في الشطرين ولا يُفصل بينهما بفعل زائد قبل desto."),
    ]),
    OrderedDict([("id","f149"),("kat","wortschatz"),("level","B2"),
        ("falsch","*Ich wohne in einem 20-Quadratmeter-Wohnung."),
        ("richtig","Ich wohne in einer 20-Quadratmeter-Wohnung."),
        ("ar","عند ربط الأرقام والوحدات بكلمة أخرى كمُركَّب وصفي، تُنسَب الصفة إلى الاسم النهائي: die Wohnung مؤنث → eine."),
    ]),
    OrderedDict([("id","f150"),("kat","sonst"),("level","B2"),
        ("falsch","*Das Buch ist besser wie der Film."),
        ("richtig","Das Buch ist besser als der Film."),
        ("ar","بعد المقارنة (besser/schöner/größer …) تستخدم «als» لا «wie»."),
    ]),
]

f = json.load(open('content/fehler.json',encoding='utf-8'))
existing = {x['id'] for x in f}
added = 0
for x in NEUE:
    if x['id'] not in existing:
        f.append(x); added += 1
with open('content/fehler.json','w',encoding='utf-8') as fh:
    json.dump(f,fh,ensure_ascii=False,indent=2); fh.write('\n')
print(f"Added {added} fehler. Total: {len(f)}")
print("Per level:", dict(Counter(x['level'] for x in f)))
