#!/usr/bin/env python3
"""R139: add 5 more B1 texts + 5 more B2 texts for depth."""
import json
from collections import OrderedDict, Counter

TEXTS = [
    # B1
    OrderedDict([("id","t-b1-31"),("level","B1"),
        ("titleDe","Ein Umzug in eine neue Stadt"),("titleAr","انتقال إلى مدينة جديدة"),
        ("de","Vor drei Monaten bin ich von Hamburg nach Leipzig gezogen. Der Grund war ein neues Jobangebot als Softwareentwicklerin. Am Anfang fiel es mir schwer, weil ich meine Freunde und meine Familie vermisst habe. Außerdem kannte ich die Stadt überhaupt nicht. Ich habe mir vorgenommen, jede Woche etwas Neues auszuprobieren: ein Café, einen Park oder ein Museum. Inzwischen habe ich zwei Kolleginnen kennengelernt, mit denen ich mich gut verstehe. Wir gehen manchmal zusammen essen oder ins Kino. Was ich an Leipzig besonders mag, sind die vielen Grünflächen und die günstigen Mieten im Vergleich zu Hamburg. Natürlich gibt es auch Dinge, die ich vermisse, zum Beispiel die Hafenatmosphäre und das Meer. Aber ich bereue den Umzug nicht — er hat mir geholfen, selbstständiger zu werden und neue Perspektiven zu gewinnen."),
        ("ar","قبل ثلاثة أشهر انتقلت من هامبورغ إلى لايبزيغ. السبب كان عرض عمل جديدة كمطورة برمجيات. في البداية كان الأمر صعباً لأنني كنت أفتقد أصدقائي وعائلتي، كما أنني لم أكن أعرف المدينة على الإطلاق. قرّرتُ أن أجرّب شيئاً جديداً كل أسبوع: مقهى أو حديقة أو متحفاً. وفي هذه الأثناء تعرّفت على زميلتين أتآلف معهما، نأكل معاً أحياناً ونذهب للسينما. ما يعجبني في لايبزيغ المساحات الخضراء الكثيرة والإيجارات الرخيصة مقارنة بهامبورغ. طبعاً هناك أشياء أفتقدها، مثل أجواء الميناء والبحر، لكنني لا أندم على الانتقال — لقد ساعدني لأصبح أكثر استقلالية ولأكسب منظورات جديدة."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Warum ist sie nach Leipzig gezogen?"),("promptAr","لماذا انتقلت إلى لايبزيغ؟"),("options",["Wegen der Liebe","Wegen eines neuen Jobs","Wegen des Studiums","Wegen der Familie"]),("answer",1),("explanationAr","السبب عرض عمل جديد.")]),
            OrderedDict([("type","mc"),("promptDe","Was gefällt ihr an Leipzig besonders?"),("promptAr","ما يعجبها في لايبزيغ تحديداً؟"),("options",["Das Meer und der Hafen","Die vielen Grünflächen und günstige Mieten","Die vielen Hochhäuser","Das Nachtleben"]),("answer",1),("explanationAr","المساحات الخضراء والإيجارات الرخيصة.")]),
        ])]),
    OrderedDict([("id","t-b1-32"),("level","B1"),
        ("titleDe","Vegetarisch leben — meine Erfahrung"),("titleAr","العيش نباتياً — تجربتي"),
        ("de","Seit einem Jahr esse ich kein Fleisch mehr. Anfangs war es schwierig, weil meine Familie traditionell viel Fleisch kocht und ich in Restaurants oft nur wenige Optionen hatte. Inzwischen habe ich viele neue Rezepte ausprobiert, vor allem aus der orientalischen und indischen Küche, die ohnehin viele vegetarische Gerichte haben. Was mich überrascht hat: Ich fühle mich nicht schwächer, im Gegenteil — ich habe mehr Energie und mein Cholesterinwert ist gesunken. Natürlich muss ich darauf achten, genügend Eisen und Eiweiß zu essen, zum Beispiel durch Hülsenfrüchte, Nüsse und Spinat. Meine Freunde reagieren unterschiedlich: einige finden es gut, andere machen Witze darüber. Ich versuche, niemanden zu missionieren, sondern einfach mit gutem Beispiel voranzugehen."),
        ("ar","منذ سنة لم آكل اللحم. في البداية كان صعباً لأن عائلتي تطبخ كثيراً من اللحم تقليدياً، وفي المطاعم كنت لا أجد سوى خيارات قليلة. مع الوقت جربت وصفات جديدة، خصوصاً من المطبخ الشرقي والهندي الذي يحتوي على أطباق نباتية كثيرة. ما فاجأني أنني لم أشعر بضعف، بل على العكس — لدي طاقة أكثر وانخفضت نسبة الكوليسترول. طبعاً يجب أن أنتبه لأخذ ما يكفي من الحديد والبروتين، عبر البقوليات والمكسرات والسبانخ مثلاً. رد فعل الأصدقاء مختلف: بعضهم يؤيد وبعضهم يمزح. أحاول ألا أعظ أحداً بل أكتفي بأن أكون قدوة."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Wie lange lebt sie schon vegetarisch?"),("promptAr","منذ متى وهي نباتية؟"),("options",["Ein halbes Jahr","Ein Jahr","Zwei Jahre","Drei Jahre"]),("answer",1),("explanationAr","منذ سنة.")]),
            OrderedDict([("type","mc"),("promptDe","Worauf muss sie achten?"),("promptAr","علام يجب أن تنتبه؟"),("options",["Auf viel Fleisch","Auf genügend Eisen und Eiweiß","Auf viel Zucker","Auf wenig Wasser"]),("answer",1),("explanationAr","الانتباه للحديد والبروتين.")]),
        ])]),
    OrderedDict([("id","t-b1-33"),("level","B1"),
        ("titleDe","Ein Bewerbungsgespräch"),("titleAr","مقابلة عمل"),
        ("de","Letzte Woche hatte ich ein Bewerbungsgespräch bei einer Marketingfirma in Köln. Schon Tage vorher war ich ziemlich nervös. Ich habe meinen Lebenslauf mehrmals durchgelesen, mich über die Firma informiert und typische Fragen geübt: nach meinen Stärken und Schwächen, meiner Berufserfahrung und meinen Gehaltsvorstellungen. Pünktlich um 10 Uhr war ich da. Die Gesprächspartnerin war freundlich und hat mir zuerst das Unternehmen vorgestellt. Sie fragte nach meinem Studium, meinen Praktika und warum ich gerade in dieser Firma arbeiten möchte. Am Ende hatte ich auch selbst die Gelegenheit, Fragen zu stellen. Ich fragte nach dem Team, den Arbeitszeiten und der Möglichkeit, teilweise im Homeoffice zu arbeiten. Drei Tage später bekam ich eine E-Mail: Ich wurde zu einem zweiten Gespräch eingeladen."),
        ("ar","الأسبوع الماضي كانت لدي مقابلة عمل في شركة تسويق في كولونيا. قبلها بأيام كنت متوترة جداً. قرأت سيرتي الذاتية عدة مرات، واطلعت على الشركة، ودرّبت على الأسئلة الشائعة: نقاط القوة والضعف، الخبرة، توقعات الراتب. وصلت في العاشرة تماماً. كانت المُحاوِرة لطيفة وبدأت بعرض الشركة. سألت عن دراستي وتدريباتي ولماذا أريد العمل هنا تحديداً. في النهاية أتيحت لي الفرصة لطرح أسئلتي: سألت عن الفريق وأوقات العمل وإمكانية العمل من المنزل جزئياً. بعد ثلاثة أيام وصلتني رسالة: تمت دعوتي لمقابلة ثانية."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Bei welcher Firma hat sie sich beworben?"),("promptAr","في أي شركة تقدّمت؟"),("options",["Einer IT-Firma","Einer Marketingfirma","Einer Schule","Einem Krankenhaus"]),("answer",1),("explanationAr","شركة تسويق في كولونيا.")]),
        ])]),
    OrderedDict([("id","t-b1-34"),("level","B1"),
        ("titleDe","Ein Unfall im Straßenverkehr"),("titleAr","حادث في الطريق"),
        ("de","Gestern habe ich auf dem Weg zur Arbeit einen kleinen Unfall gesehen. Ein Fahrradfahrer wollte an einer roten Ampel die Straße überqueren, und ein Autofahrer hat ihn übersehen. Zum Glück ist nichts Schlimmes passiert: Der Radfahrer ist nur leicht gestürzt und hat sich am Knie verletzt. Passanten haben sofort geholfen, den Krankenwagen gerufen und die Polizei informiert. Der Autofahrer war sehr aufgeregt und hat sich mehrmals entschuldigt. Diese Situation hat mir wieder gezeigt, wie wichtig es ist, im Verkehr aufmerksam zu sein — sowohl als Fußgänger als auch als Fahrer. Viele Unfälle passieren nicht, weil jemand zu schnell fährt, sondern weil man einen Moment lang nicht aufpasst."),
        ("ar","رأيت أمس في طريقي إلى العمل حادثاً بسيطاً. كان درّاج يريد عبور الشارع والإشارة حمراء، ولم يره سائق سيارة. لحسن الحظ لم يحدث شيء خطير: سقط الدراج بجروح خفيفة في الركبة. سارع المارون للمساعدة واستدعوا الإسعاف وأبلغوا الشرطة. كان السائق منفعلاً جداً واعتذر مراراً. ذكرني الموقف بأهمية الانتباه في الطريق — كمشاة وكسائقين. كثير من الحوادث لا تحدث بسبب السرعة بل لانشغال للحظة واحدة."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Wie hat sich der Radfahrer verletzt?"),("promptAr","كيف أُصيب الدراج؟"),("options",["Am Arm","Am Knie","Am Kopf","Am Rücken"]),("answer",1),("explanationAr","أُصيب في ركبته.")]),
        ])]),
    OrderedDict([("id","t-b1-35"),("level","B1"),
        ("titleDe","Ein Brief an die Zeitung: Müll im Park"),("titleAr","رسالة إلى الجريدة: النفايات في الحديقة"),
        ("de","Sehr geehrte Redaktion, ich schreibe Ihnen, weil ich mich über den Zustand des Stadtparks in meinem Viertel ärgere. Immer wieder sehe ich dort Müll auf den Wiesen und auf den Spielplätzen: leere Flaschen, Plastiktüten, Zigarettenkippen und Essensverpackungen. Obwohl es genug Mülleimer gibt, werfen viele Leute ihren Abfall einfach auf den Boden. Das ist nicht nur hässlich, sondern auch gefährlich für Kinder und Tiere. Ich schlage vor, dass die Stadt mehr Kontrollen durchführt und höhere Geldstrafen verhängt. Außerdem könnte man Schüler und Freiwillige zu regelmäßigen Säuberungsaktionen einladen. Nur wenn alle Verantwortung übernehmen, bleibt der Park ein schöner Ort für alle."),
        ("ar","السادة التحرير، أكتب إليكم لأنني مستاء من وضع الحديقة العامة في حيّي. مراراً أرى نفايات على المروج وفي ملاعب الأطفال: زجاجات فارغة وأكياس بلاستيكية وأعقاب سجائر وعبوات طعام. ورغم وجود سلال مهملات كافية، يرمي كثير من الناس النفايات على الأرض. هذا ليس قبيحاً فحسب بل خطير على الأطفال والحيوانات. أقترح أن تُجري المدينة مزيداً من الرقابة وتفرض غرامات أعلى. كما يمكن دعوة التلاميذ والمتطوعين لحملات تنظيف دورية. فقط بتَحمُّل الجميع المسؤولية تبقى الحديقة مكاناً جميلاً للجميع."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Was schlägt der Autor vor?"),("promptAr","ماذا يقترح الكاتب؟"),("options",["Den Park schließen","Mehr Kontrollen und höhere Strafen","Mehr Partys im Park","Weniger Mülleimer"]),("answer",1),("explanationAr","مزيد من الرقابة وغرامات أعلى.")]),
        ])]),
    # B2
    OrderedDict([("id","t-b2-36"),("level","B2"),
        ("titleDe","Sollte das Schulsystem später beginnen?"),("titleAr","هل يجب أن يبدأ اليوم المدرسي متأخراً؟"),
        ("de","Immer mehr Experten fordern, den Schulbeginn von 8 auf 9 Uhr zu verlegen. Ihre Begründung: Jugendliche haben einen anderen Biorhythmus als Erwachsene und Kinder. Studien zeigen, dass die innere Uhr in der Pubertät um bis zu zwei Stunden nach hinten verschoben ist. Wer um 8 Uhr in der Schule sitzt, tut dies oft gegen seine biologische Uhr — mit Folgen für Konzentration, Gedächtnis und nicht zuletzt die psychische Gesundheit. Kritiker wenden ein, dass späterer Unterricht die Eltern vor organisatorische Probleme stellt und die Nachmittagstermine der Schüler kollidieren. Außerdem sei nicht erwiesen, dass späterer Beginn die Leistungen tatsächlich verbessere. Dennoch halte ich einen Modellversuch an einigen Schulen für sinnvoll. Wenn sich zeigt, dass Schüler ausgeruhter und aufmerksamer sind, sollte man die Regelung überdenken — statt am Prinzip «früh übt sich» um jeden Preis festzuhalten."),
        ("ar","يطالب المزيد من الخبراء بتأجيل بدء الدراسة من الثامنة إلى التاسعة صباحاً. حجتهم: لدى المراهقين إيقاع بيولوجي مختلف عن البالغين والأطفال. تظهر الدراسات أن الساعة البيولوجية في سن البلوغ تتأخر حتى ساعتين. من يجلس في الدرس الثامنة غالباً يفعل ذلك ضد ساعته البيولوجية — مع ما يتبع ذلك من أثر على التركيز والذاكرة وعلى الصحة النفسية. يردّ النقاد أن التأجيل يضع الوالدين أمام صعوبات تنظيمية ويتعارض مع مواعيد بعد الظهر، كما أنه لم يثبت أنه يحسن الأداء. مع ذلك أرى أن تجربة نموذجية في مدارس قليلة أمر معقول: إن تبيّن أن التلاميذ أكثر استيقاظاً وانتباهاً، وجب إعادة النظر في النظام بدل التمسّك بمبدأ «بكّروا بالدراسة» مهما كان الثمن."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Welches Argument sprechen die Kritiker an?"),("promptAr","ما حجة النقاد؟"),("options",["Jugendliche sind zu müde","Eltern haben organisatorische Probleme","Lehrer wollen nicht früher aufstehen","Die Busse fahren nicht später"]),("answer",1),("explanationAr","النقاد يذكرون مشاكل تنظيمية لدى الوالدين.")]),
        ])]),
    OrderedDict([("id","t-b2-37"),("level","B2"),
        ("titleDe","Kulturelle Unterschiede in der Kommunikation"),("titleAr","الاختلافات الثقافية في التواصل"),
        ("de","Als ich vor vier Jahren zum ersten Mal nach Deutschland kam, war ich überrascht, wie direkt Kollegen und Nachbarn ihre Meinung sagten. In meiner Heimat gilt es als höflich, Kritik indirekt zu formulieren und zuerst längere Smalltalk-Phasen einzulegen. Hier hingegen hörte ich Sätze wie «Das funktioniert so nicht» oder «Da bin ich anderer Meinung», ohne dass sie als unfreundlich gemeint waren. Anfangs habe ich das als Ablehnung empfunden, bis mir klar wurde, dass direkte Kommunikation kein Zeichen von Respektlosigkeit ist, sondern oft auf Transparenz und Effizienz abzielt. Umgekehrt fanden manche meiner deutschen Kollegen meinerseits meine vorsichtige Formulierung unklar oder sogar unentschlossen. Diese Erfahrung hat mir gezeigt, dass Kommunikation immer auch kulturell geprägt ist. Missverständnisse lassen sich nicht immer vermeiden, aber sie werden seltener, wenn man die eigenen Erwartungen reflektiert und die der anderen ernst nimmt."),
        ("ar","عندما جئت إلى ألمانيا أول مرة قبل أربع سنوات، فوجئت بمباشرة الزملاء والجيران في إبداء الرأي. في بلدي يُعتبر من الأدب صياغة النقد بشكل غير مباشر وبدء الحديث بدرجة أطول من الدردشة. أما هنا فسمعت جملاً مثل «هكذا لا ينجح» أو «أنا على رأي آخر» دون أن يكون المقصود منها الإساءة. في البداية فهمتُها رفضاً، حتى اتضح لي أن المباشرة ليست قلة احترام بل تسعى للشفافية والكفاءة. بالمقابل، رأى بعض زملائي الألمان أن صياغتي الحذرة غامضة أو حتى غير حاسمة. بيّنت لي هذه التجربة أن التواصل مُشكَّل ثقافياً. لا يمكن تجنب سوء الفهم دائماً، لكنه يقل حين يُراجع المرء توقّعاته ويأخذ توقعات الآخرين على محمل الجد."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Was hat der Autor am deutschen Kommunikationsstil überrascht?"),("promptAr","ما الذي فاجأ الكاتب في أسلوب التواصل الألماني؟"),("options",["Übermäßige Höflichkeit","Direktheit","Langes Schweigen","Viel Smalltalk"]),("answer",1),("explanationAr","المباشرة.")]),
        ])]),
    OrderedDict([("id","t-b2-38"),("level","B2"),
        ("titleDe","Teilzeit oder Vollzeit? Die 4-Tage-Woche"),("titleAr","دوام كامل أم جزئي؟ أسبوع الأربعة أيام"),
        ("de","Die Debatte um die Vier-Tage-Woche hat in den letzten Jahren an Fahrt aufgenommen. Pilotprojekte in Island, Großbritannien und Deutschland berichten von höherer Produktivität, weniger Krankmeldungen und zufriedeneren Mitarbeitern. Dennoch bleibt das Modell umstritten. Arbeitgeberverbände warnen davor, dass in produzierenden Branchen Maschinen stillstehen könnten und die Dienstleistungsqualität sinkt. Außerdem sei fraglich, ob alle Aufgaben in vier Tagen bei gleicher Bezahlung zu schaffen seien. Befürworter argumentieren dagegen, dass weniger Arbeitszeit zu konzentrierterem Arbeiten anrege und Menschen motivierter mache, weil sie mehr Zeit für Familie, Hobbys und Erholung hätten. Meiner Ansicht nach ist die Vier-Tage-Woche keine Einheitslösung, aber sie sollte dort, wo es betrieblich möglich ist, ernsthaft erprobt werden. Es wäre naiv anzunehmen, dass weniger Stunden automatisch weniger Leistung bedeuten — entscheidend ist vielmehr, wie die Arbeit organisiert ist."),
        ("ar","اكتسب النقاش حول أسبوع الأربعة أيام زخماً في السنوات الأخيرة. تُفيد تجارب رائدة في آيسلندا وبريطانيا وألمانيا بإنتاجية أعلى وإجازات مرضية أقل وموظفين أكثر رضا. لكن النموذج يظل مثيراً للجدل. تحذّر اتحادات أرباب العمل من توقف الآلات في القطاعات الإنتاجية ومن تراجع جودة الخدمات، كما يشكّون في إمكانية إنجاز كل المهام في أربعة أيام بنفس الراتب. يردّ المؤيدون أن ساعات عمل أقل تحفّز على تركيز أعلى وتزيد الحافز، بتوفر وقت أكبر للعائلة والهوايات والراحة. برأيي، أسبوع الأربعة أيام ليس حلاً واحداً للجميع، لكن تجربته بجدية حيث يكون ممكناً إدارياً أمر حكيم. من السذاجة افتراض أن ساعات أقل تعني إنتاجاً أقل — العامل الحاسم هو كيفية تنظيم العمل."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Was fürchten Arbeitgeberverbände?"),("promptAr","ما الذي يخشاه أرباب العمل؟"),("options",["Zu hohe Löhne","Stillstand von Maschinen und sinkende Dienstleistungsqualität","Zu viele Urlaubstage","Zu geringe Nachfrage"]),("answer",1),("explanationAr","خشية توقف الآلات وتراجع جودة الخدمات.")]),
        ])]),
    OrderedDict([("id","t-b2-39"),("level","B2"),
        ("titleDe","Stadtflucht und Landleben"),("titleAr","الهروب من المدن والحياة الريفية"),
        ("de","Seit der Corona-Pandemie beobachten Stadtforscher einen Trend: Immer mehr Menschen, vor allem junge Familien, ziehen aus teuren Großstädten ins Umland oder gleich in ländliche Regionen. Gründe sind hohe Mieten, beengte Wohnverhältnisse und der Wunsch nach mehr Natur und Ruhe. Gleichzeitig ist das Landleben nicht für alle attraktiv. Öffentliche Verkehrsmittel sind selten, Ärzte und Schulen teilweise weit entfernt, und kulturelle Angebote wie Theater oder Kinos sind rar. Die Digitalisierung — Homeoffice und Videokonferenzen — hat diesen Trend zwar möglich gemacht, doch er funktioniert nur, wenn der ländliche Raum endlich ausreichend mit schnellem Internet ausgestattet wird. Ein Staat, der will, dass Menschen frei entscheiden können, wo sie wohnen, muss die Infrastruktur dort ausbauen, wo sie heute noch fehlt. Sonst bleibt die «Stadtflucht» ein Privileg weniger Menschen mit hohem Einkommen."),
        ("ar","يرصد باحثو المدن منذ جائحة كورونا توجّهاً: مزيد من الناس، خصوصاً العائلات الشابة، ينتقلون من المدن الكبرى المكلفة إلى الضواحي أو إلى المناطق الريفية. الأسباب: الإيجارات المرتفعة، المساكن الضيقة، والرغبة في مزيد من الطبيعة والهدوء. في المقابل، ليست الحياة الريفية جذابة للجميع: المواصلات العامة نادرة، والأطباء والمدارس أحياناً بعيدة، والعروض الثقافية مثل المسارح والسينما قليلة. الرقمنة والعمل من المنزل أسهمت في إتاحة هذا التوجه، لكنه لا ينجح إلا بإنترنت سريع كافٍ في الريف. الدولة التي تريد أن يختار الناس مكان سكنهم بحرية عليها أن تطوّر البنية التحتية حيثما تفتقر اليوم. وإلا ظل «الهروب من المدينة» امتيازاً لذوي الدخل المرتفع فقط."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Weswegen ziehen Familien aufs Land?"),("promptAr","لماذا تنتقل العائلات إلى الريف؟"),("options",["Wegen besserer Schulen","Wegen niedriger Mieten und mehr Natur","Wegen mehr Kulturangeboten","Wegen kürzerer Arbeitswege"]),("answer",1),("explanationAr","إيجارات أقل ومزيد من الطبيعة.")]),
        ])]),
    OrderedDict([("id","t-b2-40"),("level","B2"),
        ("titleDe","Warum lügen Menschen?"),("titleAr","لماذا يكذب الناس؟"),
        ("de","Lügen gilt als moralisch verwerflich — dennoch lügen Menschen nach psychologischen Studien durchschnittlich ein- bis zweimal pro Tag. Die Motive sind sehr unterschiedlich: Manche Lügen dienen dem Selbstschutz, um Strafe oder Blamage zu vermeiden. Andere sollen andere Menschen schonen, zum Beispiel wenn man aus Höflichkeit sagt, dass einem das Essen geschmeckt habe, obwohl es das nicht tat. Wieder andere Lügen dienen der Selbstdarstellung, um in sozialen Medien erfolgreicher oder interessanter zu wirken. Problematisch wird es, wenn Lügen Vertrauen zerstören oder andere bewusst manipulieren. Interessant ist, dass Menschen kleine Höflichkeitslügen oft als weniger schlimm empfinden, obwohl auch sie das Vertrauen untergraben können. Eine offene Kommunikationskultur, in der Fehler zugegeben werden dürfen, ist vermutlich der beste Weg, um unnötige Lügen zu reduzieren."),
        ("ar","يُعدّ الكذب فِعلاً أخلاقياً مذموماً، ورغم ذلك يكذب الناس، وفق دراسات نفسية، بمعدل مرة إلى مرتين يومياً. الدوافع متنوعة: بعض الأكاذيب لحماية الذات وتجنب العقاب أو الإحراج، وبعضها لحماية مشاعر الآخرين كالقول إن الطعام لطيف بدافع الأدب، وغيرها لعرض الذات كأكثر نجاحاً أو تشويقاً على مواقع التواصل. يصبح الكذب خطيراً عندما يدمّر الثقة أو يتلاعب بالآخرين عن قصد. ومن المثير أن الناس غالباً يعتبرون «كذبات الأدب» أقل خطورة رغم أنها تقوّض الثقة أيضاً. ثقافة تواصل مفتوحة يُسمح فيها بالاعتراف بالخطأ هي ربما أفضل وسيلة لتقليل الكذب غير الضروري."),
        ("questions",[
            OrderedDict([("type","mc"),("promptDe","Wie oft lügen Menschen laut Studien durchschnittlich?"),("promptAr","كم يكذب الناس في المعدل وفق الدراسات؟"),("options",["Nie","Einmal pro Woche","Ein- bis zweimal pro Tag","Zehnmal pro Tag"]),("answer",2),("explanationAr","مرة إلى مرتين يومياً.")]),
        ])]),
]

t = json.load(open('content/texts.json',encoding='utf-8'), object_pairs_hook=OrderedDict)
existing = {x['id'] for x in t}
added = 0
for x in TEXTS:
    if x['id'] not in existing:
        t.append(x); added += 1
with open('content/texts.json','w',encoding='utf-8') as f:
    json.dump(t,f,ensure_ascii=False,indent=2); f.write('\n')
print(f"Added {added} texts. Total: {len(t)}")
print("Per level:", dict(Counter(x['level'] for x in t)))
