#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""موجةُ تسمينِ معجمِ A1/A2 — تُضافُ الحزمُ إلى content/vocab.json بلا مساسٍ بالقديم."""
import json, re, sys, os

P = "content/vocab.json"
BILDER = set(os.listdir("public/cards"))

# (de, ar, article|"", plural|"", exampleDe, exampleAr, tag)
A1_ESSEN = [
 ("das Brot","الخبز","das","die Brote","Ich kaufe jeden Morgen frisches Brot.","أشتري خبزاً طازجاً كلَّ صباح","essen"),
 ("das Wasser","الماء","das","","Trinkst du Wasser oder Tee?","أتشربُ ماءً أم شاياً؟","essen"),
 ("der Tee","الشاي","der","die Tees","Ich trinke Tee mit Minze.","أشربُ شاياً بالنعناع","essen"),
 ("der Kaffee","القهوة","der","","Der Kaffee ist heiß.","القهوةُ ساخنة","essen"),
 ("die Milch","الحليب","die","","Die Milch steht im Kühlschrank.","الحليبُ في الثلاجة","essen"),
 ("der Zucker","السكّر","der","","Nimmst du Zucker in den Kaffee?","أتضعُ سكّراً في القهوة؟","essen"),
 ("das Salz","الملح","das","","Das Salz ist auf dem Tisch.","الملحُ على الطاولة","essen"),
 ("das Öl","الزيت","das","die Öle","Ich koche mit Olivenöl.","أطبخُ بزيتِ الزيتون","essen"),
 ("der Reis","الأرزّ","der","","Reis mit Gemüse schmeckt gut.","الأرزُّ بالخضار لذيذ","essen"),
 ("die Nudeln","المعكرونة","die","","Die Kinder essen gern Nudeln.","الأطفالُ يحبّونَ المعكرونة","essen"),
 ("das Fleisch","اللحم","das","","Ich esse kein Fleisch.","لا آكلُ اللحم","essen"),
 ("das Hähnchen","الدجاج","das","die Hähnchen","Das Hähnchen ist im Ofen.","الدجاجُ في الفرن","essen"),
 ("der Fisch","السمك","der","die Fische","Freitags essen wir Fisch.","يومَ الجمعةِ نأكلُ سمكاً","essen"),
 ("das Ei","البيضة","das","die Eier","Ich möchte zwei Eier zum Frühstück.","أريدُ بيضتَينِ للفطور","essen"),
 ("der Käse","الجبن","der","","Der Käse riecht stark.","الجبنُ قويُّ الرائحة","essen"),
 ("die Butter","الزبدة","die","","Butter aufs Brot, bitte.","زبدةً على الخبزِ من فضلك","essen"),
 ("der Apfel","التفاحة","der","die Äpfel","Ein Apfel am Tag ist gesund.","تفاحةٌ في اليومِ صحّة","essen"),
 ("die Banane","الموزة","die","die Bananen","Die Banane ist noch grün.","الموزةُ ما زالت خضراء","essen"),
 ("die Orange","البرتقالة","die","die Orangen","Ich presse zwei Orangen.","أعصرُ برتقالتَين","essen"),
 ("die Traube","حبّةُ العنب","die","die Trauben","Trauben sind im Sommer billig.","العنبُ رخيصٌ في الصيف","essen"),
 ("die Tomate","الطماطم","die","die Tomaten","Der Salat braucht Tomaten.","السلطةُ تحتاجُ طماطم","essen"),
 ("die Kartoffel","البطاطا","die","die Kartoffeln","Kartoffeln sind in Deutschland beliebt.","البطاطا محبوبةٌ في ألمانيا","essen"),
 ("die Zwiebel","البصلة","die","die Zwiebeln","Die Zwiebel macht mich weinen.","البصلةُ تُبكيني","essen"),
 ("das Gemüse","الخضار","das","","Iss mehr Gemüse!","كُلْ خضاراً أكثر!","essen"),
 ("das Obst","الفاكهة","das","","Obst ist gesünder als Kuchen.","الفاكهةُ أصحُّ من الكعك","essen"),
 ("der Salat","السلطة","der","die Salate","Ich nehme einen kleinen Salat.","آخذُ سلطةً صغيرة","essen"),
 ("die Suppe","الشوربة","die","die Suppen","Die Suppe ist zu salzig.","الشوربةُ مالحةٌ جداً","essen"),
 ("der Kuchen","الكعكة","der","die Kuchen","Meine Mutter backt einen Kuchen.","أمّي تخبزُ كعكة","essen"),
 ("die Schokolade","الشوكولاتة","die","","Schokolade macht glücklich.","الشوكولاتةُ تُسعِد","essen"),
 ("das Frühstück","الفطور","das","","Das Frühstück ist um acht.","الفطورُ في الثامنة","essen"),
 ("das Mittagessen","الغداء","das","","Zum Mittagessen gibt es Reis.","على الغداءِ أرزّ","essen"),
 ("das Abendessen","العشاء","das","","Wir essen um sieben Abendessen.","نتعشّى في السابعة","essen"),
 ("der Hunger","الجوع","der","","Ich habe großen Hunger.","أنا جائعٌ جداً","essen"),
 ("der Durst","العطش","der","","Nach dem Sport habe ich Durst.","بعدَ الرياضةِ أعطش","essen"),
 ("essen","يأكل","","","Was isst du gern?","ماذا تحبُّ أن تأكل؟","essen"),
 ("trinken","يشرب","","","Ich trinke viel Wasser.","أشربُ ماءً كثيراً","essen"),
 ("kochen","يطبخ","","","Mein Vater kocht am Wochenende.","أبي يطبخُ في عطلةِ الأسبوع","essen"),
 ("backen","يخبز","","","Sie backt Brot selbst.","هي تخبزُ الخبزَ بنفسِها","essen"),
 ("schmecken","يكونُ طعمُه","","","Das Essen schmeckt sehr gut.","الطعامُ لذيذٌ جداً","essen"),
 ("bestellen","يطلب (في المطعم)","","","Wir bestellen zwei Kaffee.","نطلبُ قهوتَين","essen"),
 ("bezahlen","يدفع","","","Ich möchte bitte bezahlen.","أودُّ أن أدفعَ من فضلك","essen"),
 ("die Rechnung","الفاتورة","die","die Rechnungen","Die Rechnung, bitte!","الفاتورةَ من فضلك!","essen"),
 ("das Restaurant","المطعم","das","die Restaurants","Das Restaurant öffnet um zwölf.","المطعمُ يفتحُ في الثانيةَ عشرة","essen"),
 ("die Speisekarte","قائمةُ الطعام","die","die Speisekarten","Kann ich die Speisekarte haben?","أيمكنني الحصولُ على قائمةِ الطعام؟","essen"),
 ("der Kellner","النادل","der","die Kellner","Der Kellner bringt das Wasser.","النادلُ يُحضِرُ الماء","essen"),
 ("der Teller","الطبق","der","die Teller","Stell den Teller auf den Tisch.","ضعِ الطبقَ على الطاولة","essen"),
 ("das Glas","الكأس","das","die Gläser","Ein Glas Wasser, bitte.","كأسَ ماءٍ من فضلك","essen"),
 ("die Tasse","الفنجان","die","die Tassen","Eine Tasse Tee wärmt.","فنجانُ شايٍ يُدفئ","essen"),
 ("die Gabel","الشوكة","die","die Gabeln","Mir fehlt eine Gabel.","تنقصُني شوكة","essen"),
 ("das Messer","السكين","das","die Messer","Das Messer ist scharf.","السكينُ حادّة","essen"),
 ("der Löffel","الملعقة","der","die Löffel","Nimm einen Löffel Zucker.","خذْ ملعقةَ سكّر","essen"),
 ("die Flasche","القارورة","die","die Flaschen","Eine Flasche Wasser kostet einen Euro.","قارورةُ ماءٍ بيورو","essen"),
 ("der Supermarkt","السوبرماركت","der","die Supermärkte","Der Supermarkt schließt um zwanzig Uhr.","السوبرماركت يُغلقُ الثامنةَ مساءً","essen"),
 ("die Bäckerei","المخبزة","die","die Bäckereien","Die Bäckerei öffnet früh.","المخبزةُ تفتحُ باكراً","essen"),
 ("frisch","طازج","","","Das Brot ist ganz frisch.","الخبزُ طازجٌ تماماً","essen"),
 ("lecker","لذيذ","","","Das war wirklich lecker!","كانَ لذيذاً حقاً!","essen"),
 ("süß","حلو","","","Der Tee ist mir zu süß.","الشايُ حلوٌ أكثرَ ممّا أحب","essen"),
 ("satt","شبعان","","","Danke, ich bin satt.","شكراً، أنا شبعان","essen"),
 ("hungrig","جائع","","","Die Kinder sind hungrig.","الأطفالُ جائعون","essen"),
 ("das Kilo","الكيلو","das","die Kilos","Ich nehme ein Kilo Tomaten.","آخذُ كيلو طماطم","essen"),
]

A1_KOERPER = [
 ("der Körper","الجسد","der","die Körper","Sport hält den Körper fit.","الرياضةُ تُبقي الجسدَ لائقاً","koerper"),
 ("das Gesicht","الوجه","das","die Gesichter","Sein Gesicht ist mir bekannt.","وجهُهُ مألوفٌ لي","koerper"),
 ("das Auge","العين","das","die Augen","Sie hat grüne Augen.","لها عينانِ خضراوان","koerper"),
 ("das Ohr","الأذن","das","die Ohren","Mein Ohr tut weh.","أذني تؤلمني","koerper"),
 ("die Nase","الأنف","die","die Nasen","Meine Nase läuft.","أنفي يسيل","koerper"),
 ("der Mund","الفم","der","die Münder","Mach den Mund auf.","افتحِ الفم","koerper"),
 ("der Zahn","السنّ","der","die Zähne","Der Zahn tut seit gestern weh.","السنُّ يؤلمُ منذُ أمس","koerper"),
 ("das Haar","الشَّعر","das","die Haare","Meine Haare sind zu lang.","شَعري طويلٌ جداً","koerper"),
 ("die Hand","اليد","die","die Hände","Wasch dir die Hände!","اغسلْ يدَيك!","koerper"),
 ("der Arm","الذراع","der","die Arme","Mein linker Arm ist gebrochen.","ذراعي اليسرى مكسورة","koerper"),
 ("das Bein","الساق","das","die Beine","Nach dem Lauf tun die Beine weh.","بعدَ الجريِ تؤلمُ الساقان","koerper"),
 ("der Fuß","القدم","der","die Füße","Mein Fuß ist geschwollen.","قدمي متورّمة","koerper"),
 ("der Finger","الإصبع","der","die Finger","Ich habe mir den Finger geschnitten.","جرحتُ إصبعي","koerper"),
 ("der Rücken","الظهر","der","die Rücken","Mein Rücken tut vom Sitzen weh.","ظهري يؤلمُ من الجلوس","koerper"),
 ("das Herz","القلب","das","die Herzen","Mein Herz schlägt schnell.","قلبي يخفقُ سريعاً","koerper"),
 ("gesund","صحيح البدن","","","Obst hält dich gesund.","الفاكهةُ تُبقيكَ صحيحاً","koerper"),
 ("krank","مريض","","","Ich bin heute krank.","أنا مريضٌ اليوم","koerper"),
 ("müde","متعب","","","Ich bin sehr müde.","أنا متعبٌ جداً","koerper"),
 ("schlafen","ينام","","","Ich schlafe acht Stunden.","أنامُ ثماني ساعات","koerper"),
 ("aufstehen","ينهض","","","Ich stehe um sechs auf.","أنهضُ في السادسة","koerper"),
 ("die Kleidung","الملابس","die","","Die Kleidung liegt im Schrank.","الملابسُ في الخزانة","kleidung"),
 ("das Hemd","القميص","das","die Hemden","Das weiße Hemd ist sauber.","القميصُ الأبيضُ نظيف","kleidung"),
 ("die Hose","البنطال","die","die Hosen","Die Hose ist zu eng.","البنطالُ ضيّقٌ جداً","kleidung"),
 ("der Rock","التنّورة","der","die Röcke","Sie trägt einen langen Rock.","ترتدي تنّورةً طويلة","kleidung"),
 ("das Kleid","الفستان","das","die Kleider","Das Kleid gefällt mir.","الفستانُ يعجبُني","kleidung"),
 ("die Jacke","السترة","die","die Jacken","Nimm eine Jacke mit, es ist kalt.","خذْ سترةً معك، الجوُّ بارد","kleidung"),
 ("der Mantel","المعطف","der","die Mäntel","Im Winter trage ich einen Mantel.","في الشتاءِ ألبسُ معطفاً","kleidung"),
 ("der Schuh","الحذاء","der","die Schuhe","Diese Schuhe sind bequem.","هذا الحذاءُ مريح","kleidung"),
 ("die Socke","الجورب","die","die Socken","Wo sind meine Socken?","أينَ جواربي؟","kleidung"),
 ("die Mütze","القبّعة الصوفية","die","die Mützen","Setz die Mütze auf!","ضعِ القبّعة!","kleidung"),
 ("die Brille","النظّارة","die","die Brillen","Ohne Brille sehe ich nichts.","بلا نظّارةٍ لا أرى شيئاً","kleidung"),
 ("die Tasche","الحقيبة","die","die Taschen","Meine Tasche ist schwer.","حقيبتي ثقيلة","kleidung"),
 ("tragen","يرتدي / يحمل","","","Er trägt heute einen Anzug.","يرتدي اليومَ بدلة","kleidung"),
 ("anziehen","يلبس","","","Zieh dir die Jacke an!","البسِ السترة!","kleidung"),
 ("ausziehen","يخلع","","","Zieh die Schuhe aus, bitte.","اخلعِ الحذاءَ من فضلك","kleidung"),
 ("passen","يناسب (مقاساً)","","","Die Hose passt mir nicht.","البنطالُ لا يناسبُ مقاسي","kleidung"),
 ("kosten","يكلّف","","","Was kostet die Jacke?","كم تكلّفُ السترة؟","kleidung"),
 ("billig","رخيص","","","Das T-Shirt ist billig.","القميصُ رخيص","kleidung"),
 ("teuer","غالٍ","","","Der Mantel ist zu teuer.","المعطفُ غالٍ جداً","kleidung"),
 ("die Größe","المقاس","die","die Größen","Welche Größe brauchen Sie?","أيَّ مقاسٍ تحتاج؟","kleidung"),
 ("die Farbe","اللون","die","die Farben","Welche Farbe magst du?","أيَّ لونٍ تحب؟","kleidung"),
 ("rot","أحمر","","","Das Auto ist rot.","السيارةُ حمراء","farbe"),
 ("blau","أزرق","","","Der Himmel ist blau.","السماءُ زرقاء","farbe"),
 ("grün","أخضر","","","Die Ampel ist grün.","الإشارةُ خضراء","farbe"),
 ("gelb","أصفر","","","Die Sonne ist gelb.","الشمسُ صفراء","farbe"),
 ("schwarz","أسود","","","Ich trinke Kaffee schwarz.","أشربُ القهوةَ سادة","farbe"),
 ("weiß","أبيض","","","Das Papier ist weiß.","الورقُ أبيض","farbe"),
 ("grau","رمادي","","","Der Himmel ist heute grau.","السماءُ اليومَ رمادية","farbe"),
 ("braun","بنّي","","","Sie hat braune Augen.","لها عيونٌ بنّية","farbe"),
 ("waschen","يغسل","","","Ich wasche die Kleidung am Samstag.","أغسلُ الملابسَ يومَ السبت","kleidung"),
 ("sauber","نظيف","","","Das Zimmer ist jetzt sauber.","الغرفةُ نظيفةٌ الآن","kleidung"),
 ("schmutzig","متّسخ","","","Meine Schuhe sind schmutzig.","حذائي متّسخ","kleidung"),
 ("neu","جديد","","","Ich brauche eine neue Hose.","أحتاجُ بنطالاً جديداً","kleidung"),
 ("alt","قديم / كبيرُ السن","","","Der Mantel ist alt, aber warm.","المعطفُ قديمٌ لكنَّهُ دافئ","kleidung"),
 ("kurz","قصير","","","Die Hose ist zu kurz.","البنطالُ قصيرٌ جداً","kleidung"),
 ("lang","طويل","","","Der Rock ist lang.","التنّورةُ طويلة","kleidung"),
 ("warm","دافئ","","","Die Jacke ist schön warm.","السترةُ دافئةٌ جميلة","kleidung"),
 ("kalt","بارد","","","Heute ist es sehr kalt.","الجوُّ اليومَ باردٌ جداً","kleidung"),
 ("die Apotheke","الصيدلية","die","die Apotheken","Die Apotheke ist neben dem Arzt.","الصيدليةُ بجانبِ الطبيب","koerper"),
 ("die Medizin","الدواء","die","","Nimm die Medizin nach dem Essen.","خذِ الدواءَ بعدَ الأكل","koerper"),
]

A1_STADT = [
 ("die Stadt","المدينة","die","die Städte","Tunis ist eine große Stadt.","تونسُ مدينةٌ كبيرة","stadt"),
 ("das Dorf","القرية","das","die Dörfer","Meine Familie lebt in einem Dorf.","عائلتي تعيشُ في قرية","stadt"),
 ("die Straße","الشارع","die","die Straßen","Die Straße ist heute gesperrt.","الشارعُ مغلقٌ اليوم","stadt"),
 ("der Platz","الساحة / المكان","der","die Plätze","Wir treffen uns auf dem Platz.","نلتقي في الساحة","stadt"),
 ("das Haus","البيت","das","die Häuser","Das Haus hat einen Garten.","للبيتِ حديقة","stadt"),
 ("die Wohnung","الشقّة","die","die Wohnungen","Die Wohnung hat drei Zimmer.","الشقةُ فيها ثلاثُ غرف","stadt"),
 ("die Schule","المدرسة","die","die Schulen","Die Schule beginnt um acht.","المدرسةُ تبدأُ الثامنة","stadt"),
 ("die Universität","الجامعة","die","die Universitäten","Er studiert an der Universität.","يدرسُ في الجامعة","stadt"),
 ("das Krankenhaus","المستشفى","das","die Krankenhäuser","Das Krankenhaus ist weit.","المستشفى بعيد","stadt"),
 ("die Post","مكتبُ البريد","die","","Ich bringe den Brief zur Post.","آخذُ الرسالةَ إلى البريد","stadt"),
 ("die Bank","البنك","die","die Banken","Die Bank öffnet um neun.","البنكُ يفتحُ التاسعة","stadt"),
 ("der Bahnhof","محطةُ القطار","der","die Bahnhöfe","Wir treffen uns am Bahnhof.","نلتقي في المحطة","stadt"),
 ("der Flughafen","المطار","der","die Flughäfen","Der Flughafen liegt außerhalb.","المطارُ خارجَ المدينة","stadt"),
 ("die Haltestelle","الموقف","die","die Haltestellen","Die Haltestelle ist um die Ecke.","الموقفُ عندَ الزاوية","stadt"),
 ("der Bus","الحافلة","der","die Busse","Der Bus kommt in fünf Minuten.","الحافلةُ تصلُ بعدَ خمسِ دقائق","verkehr"),
 ("der Zug","القطار","der","die Züge","Der Zug hat Verspätung.","القطارُ متأخِّر","verkehr"),
 ("das Auto","السيارة","das","die Autos","Mein Auto ist kaputt.","سيارتي معطّلة","verkehr"),
 ("das Fahrrad","الدرّاجة","das","die Fahrräder","Ich fahre mit dem Fahrrad.","أذهبُ بالدرّاجة","verkehr"),
 ("das Taxi","سيارةُ الأجرة","das","die Taxis","Nehmen wir ein Taxi?","أنأخذُ تاكسي؟","verkehr"),
 ("fahren","يقود / يسافر بمركبة","","","Ich fahre nach Berlin.","أسافرُ إلى برلين","verkehr"),
 ("laufen","يمشي / يجري","","","Ich laufe zur Arbeit.","أمشي إلى العمل","verkehr"),
 ("fliegen","يطير","","","Wir fliegen im Juli.","نطيرُ في يوليو","verkehr"),
 ("ankommen","يصل","","","Der Zug kommt um acht an.","القطارُ يصلُ الثامنة","verkehr"),
 ("abfahren","ينطلق","","","Der Bus fährt gleich ab.","الحافلةُ تنطلقُ حالاً","verkehr"),
 ("umsteigen","يغيّرُ وسيلة","","","In Köln müssen wir umsteigen.","في كولونيا علينا التغيير","verkehr"),
 ("die Fahrkarte","تذكرةُ السفر","die","die Fahrkarten","Eine Fahrkarte nach Hamburg, bitte.","تذكرةً إلى هامبورغ من فضلك","verkehr"),
 ("links","يسار","","","Gehen Sie links.","اذهبْ يساراً","weg"),
 ("rechts","يمين","","","Die Apotheke ist rechts.","الصيدليةُ على اليمين","weg"),
 ("geradeaus","إلى الأمام مباشرة","","","Gehen Sie immer geradeaus.","امشِ دائماً إلى الأمام","weg"),
 ("die Ecke","الزاوية","die","die Ecken","An der Ecke ist ein Café.","عندَ الزاويةِ مقهى","weg"),
 ("die Kreuzung","التقاطع","die","die Kreuzungen","An der Kreuzung rechts.","عندَ التقاطعِ يميناً","weg"),
 ("die Ampel","إشارةُ المرور","die","die Ampeln","Warte an der Ampel!","انتظرْ عندَ الإشارة!","weg"),
 ("nah","قريب","","","Der Markt ist ganz nah.","السوقُ قريبٌ جداً","weg"),
 ("weit","بعيد","","","Ist es weit von hier?","أهوَ بعيدٌ من هنا؟","weg"),
 ("der Weg","الطريق","der","die Wege","Ich kenne den Weg nicht.","لا أعرفُ الطريق","weg"),
 ("fragen","يسأل","","","Ich frage den Mann.","أسألُ الرجل","weg"),
 ("zeigen","يُري / يدلّ","","","Können Sie mir den Weg zeigen?","أيمكنكَ أن تدلَّني على الطريق؟","weg"),
 ("suchen","يبحث","","","Ich suche den Bahnhof.","أبحثُ عن المحطة","weg"),
 ("finden","يجد","","","Ich finde die Adresse nicht.","لا أجدُ العنوان","weg"),
 ("das Geschäft","المتجر","das","die Geschäfte","Das Geschäft hat bis acht offen.","المتجرُ مفتوحٌ حتى الثامنة","einkauf"),
 ("der Markt","السوق","der","die Märkte","Samstags gehe ich auf den Markt.","أذهبُ إلى السوقِ يومَ السبت","einkauf"),
 ("kaufen","يشتري","","","Ich kaufe Brot und Milch.","أشتري خبزاً وحليباً","einkauf"),
 ("verkaufen","يبيع","","","Er verkauft Obst.","يبيعُ فاكهة","einkauf"),
 ("das Geld","المال","das","","Ich habe kein Geld dabei.","لا أحملُ مالاً","einkauf"),
 ("der Euro","اليورو","der","die Euro","Das kostet zehn Euro.","هذا بعشرةِ يورو","einkauf"),
 ("die Kasse","الصندوق (الدفع)","die","die Kassen","Bitte zahlen Sie an der Kasse.","ادفعْ عندَ الصندوق","einkauf"),
 ("das Kino","السينما","das","die Kinos","Gehen wir ins Kino?","أنذهبُ إلى السينما؟","freizeit"),
 ("das Café","المقهى","das","die Cafés","Das Café hat WLAN.","المقهى فيهِ واي فاي","freizeit"),
 ("der Park","المنتزه","der","die Parks","Im Park spielen Kinder.","في المنتزهِ يلعبُ أطفال","freizeit"),
 ("das Museum","المتحف","das","die Museen","Das Museum ist montags zu.","المتحفُ مغلقٌ الإثنين","freizeit"),
 ("die Kirche","الكنيسة","die","die Kirchen","Die Kirche ist sehr alt.","الكنيسةُ قديمةٌ جداً","stadt"),
 ("die Moschee","المسجد","die","die Moscheen","Die Moschee liegt im Zentrum.","المسجدُ في المركز","stadt"),
 ("das Zentrum","المركز","das","die Zentren","Ich wohne im Zentrum.","أسكنُ في المركز","stadt"),
 ("die Adresse","العنوان","die","die Adressen","Wie ist deine Adresse?","ما عنوانُك؟","stadt"),
 ("die Nummer","الرقم","die","die Nummern","Meine Nummer ist neu.","رقمي جديد","stadt"),
 ("hier","هنا","","","Hier ist es ruhig.","هنا هادئ","weg"),
 ("dort","هناك","","","Dort ist die Haltestelle.","هناكَ الموقف","weg"),
 ("oben","في الأعلى","","","Das Büro ist oben.","المكتبُ في الأعلى","weg"),
 ("unten","في الأسفل","","","Der Keller ist unten.","القبوُ في الأسفل","weg"),
 ("zwischen","بين","","","Die Bank ist zwischen Post und Café.","البنكُ بينَ البريدِ والمقهى","weg"),
]

A2_ARBEIT = [
 ("der Beruf","المهنة","der","die Berufe","Was sind Sie von Beruf?","ما مهنتُك؟","arbeit"),
 ("die Stelle","الوظيفة (الشاغرة)","die","die Stellen","Ich suche eine Stelle als Techniker.","أبحثُ عن وظيفةِ فنّي","arbeit"),
 ("die Bewerbung","طلبُ التوظيف","die","die Bewerbungen","Meine Bewerbung ist schon unterwegs.","طلبي في الطريق","arbeit"),
 ("der Lebenslauf","السيرةُ الذاتية","der","die Lebensläufe","Der Lebenslauf muss aktuell sein.","يجبُ أن تكونَ السيرةُ محدَّثة","arbeit"),
 ("das Vorstellungsgespräch","مقابلةُ العمل","das","die Vorstellungsgespräche","Morgen habe ich ein Vorstellungsgespräch.","غداً لديَّ مقابلةُ عمل","arbeit"),
 ("der Arbeitgeber","صاحبُ العمل","der","die Arbeitgeber","Mein Arbeitgeber zahlt pünktlich.","صاحبُ عملي يدفعُ في موعدِه","arbeit"),
 ("der Kollege","الزميل","der","die Kollegen","Mein Kollege hilft mir oft.","زميلي يساعدُني كثيراً","arbeit"),
 ("die Abteilung","القسم","die","die Abteilungen","Ich arbeite in der Abteilung Technik.","أعملُ في القسمِ التقني","arbeit"),
 ("der Vertrag","العقد","der","die Verträge","Der Vertrag gilt ein Jahr.","العقدُ ساري سنةً","arbeit"),
 ("das Gehalt","الراتب","das","die Gehälter","Das Gehalt kommt am Monatsende.","الراتبُ يصلُ آخرَ الشهر","arbeit"),
 ("die Erfahrung","الخبرة","die","die Erfahrungen","Ich habe drei Jahre Erfahrung.","لديَّ ثلاثُ سنواتِ خبرة","arbeit"),
 ("die Ausbildung","التدريبُ المهني","die","die Ausbildungen","Sie macht eine Ausbildung als Pflegerin.","تتدرَّبُ لتكونَ ممرّضة","arbeit"),
 ("das Praktikum","التربّص","das","die Praktika","Das Praktikum dauert sechs Wochen.","التربّصُ ستةُ أسابيع","arbeit"),
 ("die Schicht","الوردية","die","die Schichten","Diese Woche habe ich Nachtschicht.","هذا الأسبوعَ لديَّ ورديةٌ ليلية","arbeit"),
 ("die Überstunde","ساعةُ عملٍ إضافية","die","die Überstunden","Überstunden werden bezahlt.","الساعاتُ الإضافيةُ مدفوعة","arbeit"),
 ("der Urlaub","الإجازة","der","die Urlaube","Ich nehme im August Urlaub.","آخذُ إجازةً في أغسطس","arbeit"),
 ("die Kündigung","الاستقالة / الفصل","die","die Kündigungen","Die Kündigung muss schriftlich sein.","يجبُ أن تكونَ الاستقالةُ مكتوبة","arbeit"),
 ("arbeitslos","عاطلٌ عن العمل","","","Er ist seit einem Monat arbeitslos.","هو عاطلٌ منذُ شهر","arbeit"),
 ("sich bewerben","يتقدَّمُ بطلب","","","Ich bewerbe mich bei einer Firma.","أتقدَّمُ بطلبٍ لشركة","arbeit"),
 ("verdienen","يكسب","","","Sie verdient gut.","تكسبُ جيداً","arbeit"),
 ("kündigen","يستقيل / يفصل","","","Er hat letzte Woche gekündigt.","استقالَ الأسبوعَ الماضي","arbeit"),
 ("die Besprechung","الاجتماع","die","die Besprechungen","Die Besprechung dauert eine Stunde.","الاجتماعُ ساعة","arbeit"),
 ("der Termin","الموعد","der","die Termine","Ich habe einen Termin um drei.","لديَّ موعدٌ الثالثة","buero"),
 ("absagen","يُلغي","","","Ich muss den Termin absagen.","عليَّ إلغاءُ الموعد","buero"),
 ("verschieben","يؤجّل","","","Können wir den Termin verschieben?","أيمكننا تأجيلُ الموعد؟","buero"),
 ("die Unterlagen","الوثائق","die","","Bringen Sie bitte alle Unterlagen mit.","أحضرْ كلَّ الوثائق","buero"),
 ("unterschreiben","يوقّع","","","Bitte hier unterschreiben.","وقّعْ هنا من فضلك","buero"),
 ("das Formular","الاستمارة","das","die Formulare","Füllen Sie das Formular aus.","املأِ الاستمارة","buero"),
 ("ausfüllen","يملأ","","","Ich fülle den Antrag aus.","أملأُ الطلب","buero"),
 ("der Antrag","الطلبُ الرسمي","der","die Anträge","Der Antrag ist genehmigt.","الطلبُ مقبول","buero"),
 ("die Behörde","الإدارةُ الرسمية","die","die Behörden","Die Behörde antwortet langsam.","الإدارةُ تردُّ ببطء","buero"),
 ("die Versicherung","التأمين","die","die Versicherungen","Die Versicherung zahlt den Schaden.","التأمينُ يدفعُ الضرر","buero"),
 ("die Steuer","الضريبة","die","die Steuern","Die Steuer wird automatisch abgezogen.","الضريبةُ تُخصَمُ تلقائياً","buero"),
 ("das Konto","الحساب البنكي","das","die Konten","Ich eröffne ein Konto.","أفتحُ حساباً","buero"),
 ("überweisen","يحوّلُ مالاً","","","Ich überweise die Miete monatlich.","أحوّلُ الإيجارَ شهرياً","buero"),
 ("die Rechnung prüfen","يراجعُ الفاتورة","","","Prüfen Sie die Rechnung genau.","راجعِ الفاتورةَ بدقة","buero"),
 ("das Zeugnis","الشهادة","das","die Zeugnisse","Mein Zeugnis ist übersetzt.","شهادتي مترجَمة","bildung"),
 ("die Prüfung","الامتحان","die","die Prüfungen","Die Prüfung ist im Juni.","الامتحانُ في يونيو","bildung"),
 ("bestehen","ينجح (في امتحان)","","","Ich habe die Prüfung bestanden.","نجحتُ في الامتحان","bildung"),
 ("durchfallen","يرسب","","","Er ist leider durchgefallen.","رسبَ للأسف","bildung"),
 ("wiederholen","يعيد","","","Ich wiederhole die Vokabeln täglich.","أراجعُ المفرداتِ يومياً","bildung"),
 ("der Kurs","الدورة","der","die Kurse","Der Kurs beginnt nächste Woche.","الدورةُ تبدأُ الأسبوعَ القادم","bildung"),
 ("die Note","الدرجة","die","die Noten","Meine Note ist gut.","درجتي جيدة","bildung"),
 ("die Aufgabe","الواجب / المهمّة","die","die Aufgaben","Die Aufgabe ist schwer.","المهمّةُ صعبة","bildung"),
 ("erklären","يشرح","","","Die Lehrerin erklärt die Regel.","المعلّمةُ تشرحُ القاعدة","bildung"),
 ("verstehen","يفهم","","","Ich verstehe die Frage nicht.","لا أفهمُ السؤال","bildung"),
 ("üben","يتمرَّن","","","Ich übe jeden Tag zwanzig Minuten.","أتمرَّنُ عشرينَ دقيقةً يومياً","bildung"),
 ("die Fähigkeit","القدرة","die","die Fähigkeiten","Teamarbeit ist eine wichtige Fähigkeit.","العملُ الجماعيُّ قدرةٌ مهمّة","arbeit"),
 ("zuverlässig","موثوق","","","Er ist sehr zuverlässig.","هو موثوقٌ جداً","arbeit"),
 ("pünktlich","منضبطٌ بالوقت","","","Bitte sei pünktlich!","كنْ في الموعد!","arbeit"),
 ("selbstständig","مستقلٌّ في العمل","","","Sie arbeitet sehr selbstständig.","تعملُ باستقلاليةٍ عالية","arbeit"),
 ("die Verantwortung","المسؤولية","die","","Ich übernehme gern Verantwortung.","أتحمَّلُ المسؤوليةَ بسرور","arbeit"),
 ("der Stress","الضغطُ النفسي","der","","Im Job habe ich viel Stress.","في العملِ ضغطٌ كثير","arbeit"),
 ("die Pause","الاستراحة","die","die Pausen","Wir machen eine kurze Pause.","نأخذُ استراحةً قصيرة","arbeit"),
 ("der Chef","المدير","der","die Chefs","Der Chef ist heute nicht da.","المديرُ غيرُ موجودٍ اليوم","arbeit"),
 ("die Firma","الشركة","die","die Firmen","Die Firma hat zwanzig Mitarbeiter.","الشركةُ فيها عشرونَ موظفاً","arbeit"),
 ("der Mitarbeiter","الموظف","der","die Mitarbeiter","Jeder Mitarbeiter bekommt einen Schlüssel.","كلُّ موظفٍ يأخذُ مفتاحاً","arbeit"),
 ("die Sicherheit","السلامة / الأمان","die","","Sicherheit geht vor.","السلامةُ أولاً","arbeit"),
 ("der Fehler","الخطأ","der","die Fehler","Aus Fehlern lernt man.","من الأخطاءِ نتعلَّم","arbeit"),
 ("die Lösung","الحل","die","die Lösungen","Wir suchen eine Lösung.","نبحثُ عن حل","arbeit"),
]

A2_ALLTAG = [
 ("die Nachbarschaft","الجوار","die","","In unserer Nachbarschaft ist es ruhig.","حيُّنا هادئ","wohnen"),
 ("der Nachbar","الجار","der","die Nachbarn","Mein Nachbar ist sehr freundlich.","جاري لطيفٌ جداً","wohnen"),
 ("die Miete","الإيجار","die","die Mieten","Die Miete steigt jedes Jahr.","الإيجارُ يرتفعُ كلَّ عام","wohnen"),
 ("der Vermieter","المؤجِّر","der","die Vermieter","Der Vermieter repariert die Heizung.","المؤجِّرُ يصلحُ التدفئة","wohnen"),
 ("die Heizung","التدفئة","die","die Heizungen","Die Heizung funktioniert nicht.","التدفئةُ لا تعمل","wohnen"),
 ("der Strom","الكهرباء","der","","Der Strom ist heute ausgefallen.","انقطعتِ الكهرباءُ اليوم","wohnen"),
 ("die Reparatur","التصليح","die","die Reparaturen","Die Reparatur dauert zwei Tage.","التصليحُ يستغرقُ يومَين","wohnen"),
 ("kaputt","معطَّل","","","Der Aufzug ist kaputt.","المصعدُ معطَّل","wohnen"),
 ("reparieren","يصلح","","","Können Sie das reparieren?","أيمكنكَ تصليحُ هذا؟","wohnen"),
 ("umziehen","ينتقلُ سكناً","","","Wir ziehen im Mai um.","ننتقلُ في مايو","wohnen"),
 ("der Umzug","الانتقال","der","die Umzüge","Der Umzug war anstrengend.","كانَ الانتقالُ مُتعِباً","wohnen"),
 ("der Müll","القمامة","der","","Der Müll wird dienstags abgeholt.","القمامةُ تُرفَعُ الثلاثاء","wohnen"),
 ("trennen","يفرز / يفصل","","","Wir trennen den Müll.","نفرزُ القمامة","wohnen"),
 ("aufräumen","يرتّب","","","Ich räume mein Zimmer auf.","أرتّبُ غرفتي","wohnen"),
 ("die Ordnung","النظام / الترتيب","die","","Ordnung ist wichtig.","الترتيبُ مهم","wohnen"),
 ("das Handy","الهاتف المحمول","das","die Handys","Mein Handy ist leer.","بطاريةُ هاتفي فارغة","kommunikation"),
 ("anrufen","يتّصلُ هاتفياً","","","Ich rufe dich später an.","سأتّصلُ بكَ لاحقاً","kommunikation"),
 ("zurückrufen","يعاودُ الاتصال","","","Ich rufe Sie morgen zurück.","سأعاودُ الاتصالَ غداً","kommunikation"),
 ("die Nachricht","الرسالة / الخبر","die","die Nachrichten","Ich schicke dir eine Nachricht.","سأرسلُ لكَ رسالة","kommunikation"),
 ("schicken","يرسل","","","Schick mir bitte die Adresse.","أرسلْ لي العنوان","kommunikation"),
 ("erreichen","يبلغ / يتمكّنُ من الوصول","","","Ich konnte dich nicht erreichen.","لم أتمكّنْ من الوصولِ إليك","kommunikation"),
 ("Bescheid sagen","يُخبِر","","","Sag mir bitte Bescheid.","أخبرْني من فضلك","kommunikation"),
 ("sich verabreden","يتواعد","","","Wir verabreden uns um sechs.","نتواعدُ على السادسة","kommunikation"),
 ("absprechen","يتّفقُ مسبقاً","","","Das müssen wir vorher absprechen.","علينا الاتفاقُ على ذلك مسبقاً","kommunikation"),
 ("die Einladung","الدعوة","die","die Einladungen","Danke für die Einladung!","شكراً على الدعوة!","sozial"),
 ("einladen","يدعو","","","Ich lade dich zum Essen ein.","أدعوكَ إلى الطعام","sozial"),
 ("absagen müssen","يضطرُّ للاعتذار","","","Ich muss leider absagen.","للأسف عليَّ الاعتذار","sozial"),
 ("sich freuen","يفرح","","","Ich freue mich auf den Besuch.","أتطلَّعُ إلى الزيارة","sozial"),
 ("sich entschuldigen","يعتذر","","","Ich entschuldige mich für die Verspätung.","أعتذرُ عن التأخير","sozial"),
 ("die Verspätung","التأخير","die","die Verspätungen","Die Verspätung war nicht meine Schuld.","التأخيرُ ليسَ ذنبي","sozial"),
 ("das Geschenk","الهدية","das","die Geschenke","Ich bringe ein kleines Geschenk mit.","أُحضِرُ هديةً صغيرة","sozial"),
 ("gratulieren","يهنّئ","","","Ich gratuliere dir zum Erfolg!","أهنّئكَ على النجاح!","sozial"),
 ("der Geburtstag","عيدُ الميلاد","der","die Geburtstage","Mein Geburtstag ist im März.","عيدُ ميلادي في مارس","sozial"),
 ("das Fest","الاحتفال","das","die Feste","Das Fest dauert bis Mitternacht.","الاحتفالُ حتى منتصفِ الليل","sozial"),
 ("feiern","يحتفل","","","Wir feiern zu Hause.","نحتفلُ في البيت","sozial"),
 ("der Gast","الضيف","der","die Gäste","Wir haben heute Gäste.","لدينا ضيوفٌ اليوم","sozial"),
 ("das Wetter","الطقس","das","","Wie ist das Wetter morgen?","كيفَ الطقسُ غداً؟","wetter"),
 ("der Regen","المطر","der","","Der Regen hört nicht auf.","المطرُ لا يتوقّف","wetter"),
 ("der Schnee","الثلج","der","","Im Januar liegt viel Schnee.","في يناير ثلجٌ كثير","wetter"),
 ("der Wind","الريح","der","die Winde","Heute weht ein starker Wind.","اليومَ ريحٌ قوية","wetter"),
 ("die Wolke","السحابة","die","die Wolken","Am Himmel sind dunkle Wolken.","في السماءِ غيومٌ داكنة","wetter"),
 ("die Sonne","الشمس","die","","Die Sonne scheint den ganzen Tag.","الشمسُ تُشرقُ طوالَ اليوم","wetter"),
 ("das Gewitter","العاصفةُ الرعدية","das","die Gewitter","Am Abend gibt es ein Gewitter.","مساءً ستكونُ عاصفةٌ رعدية","wetter"),
 ("die Temperatur","درجةُ الحرارة","die","die Temperaturen","Die Temperatur sinkt nachts.","الحرارةُ تنخفضُ ليلاً","wetter"),
 ("sonnig","مشمس","","","Morgen wird es sonnig.","غداً سيكونُ مشمساً","wetter"),
 ("bewölkt","غائم","","","Der Himmel ist bewölkt.","السماءُ غائمة","wetter"),
 ("neblig","ضبابي","","","Am Morgen war es neblig.","صباحاً كانَ ضبابياً","wetter"),
 ("der Ausflug","النزهة","der","die Ausflüge","Wir machen einen Ausflug ans Meer.","نقومُ بنزهةٍ إلى البحر","freizeit"),
 ("die Reise","الرحلة","die","die Reisen","Die Reise dauert acht Stunden.","الرحلةُ ثماني ساعات","freizeit"),
 ("buchen","يحجز","","","Ich buche das Hotel online.","أحجزُ الفندقَ عبرَ الإنترنت","freizeit"),
 ("das Hotel","الفندق","das","die Hotels","Das Hotel liegt am Strand.","الفندقُ على الشاطئ","freizeit"),
 ("der Koffer","الحقيبة الكبيرة","der","die Koffer","Mein Koffer ist zu schwer.","حقيبتي ثقيلةٌ جداً","freizeit"),
 ("packen","يحزم","","","Ich packe heute Abend.","أحزمُ هذا المساء","freizeit"),
 ("der Ausweis","بطاقةُ الهوية","der","die Ausweise","Zeigen Sie bitte Ihren Ausweis.","أظهرْ هويتَكَ من فضلك","behoerde"),
 ("der Pass","جوازُ السفر","der","die Pässe","Mein Pass läuft bald ab.","جوازي ينتهي قريباً","behoerde"),
 ("die Anmeldung","التسجيل","die","die Anmeldungen","Die Anmeldung ist kostenlos.","التسجيلُ مجاني","behoerde"),
 ("sich anmelden","يسجّل نفسَه","","","Ich melde mich beim Kurs an.","أسجّلُ في الدورة","behoerde"),
 ("die Erlaubnis","الإذن","die","","Dafür brauchst du eine Erlaubnis.","لهذا تحتاجُ إذناً","behoerde"),
 ("gültig","ساري المفعول","","","Die Karte ist bis Mai gültig.","البطاقةُ ساريةٌ حتى مايو","behoerde"),
]

A2_ARBEIT += [
 ("die Arbeitszeit","وقتُ العمل","die","die Arbeitszeiten","Meine Arbeitszeit endet um siebzehn Uhr.","وقتُ عملي ينتهي الخامسةَ مساءً","arbeit"),
 ("der Arbeitsplatz","مكانُ العمل","der","die Arbeitsplätze","Mein Arbeitsplatz ist sehr ruhig.","مكانُ عملي هادئٌ جداً","arbeit"),
 ("die Teilzeit","الدوامُ الجزئي","die","","Sie arbeitet in Teilzeit.","تعملُ بدوامٍ جزئي","arbeit"),
 ("die Vollzeit","الدوامُ الكامل","die","","Ich suche eine Stelle in Vollzeit.","أبحثُ عن دوامٍ كامل","arbeit"),
 ("die Anfrage","الاستفسار","die","die Anfragen","Ich habe eine kurze Anfrage.","لديَّ استفسارٌ قصير","buero"),
 ("die Bestätigung","التأكيد","die","die Bestätigungen","Bitte schicken Sie mir eine Bestätigung.","أرسلْ لي تأكيداً من فضلك","buero"),
 ("die Frist","المهلة","die","die Fristen","Die Frist endet am Freitag.","المهلةُ تنتهي الجمعة","buero"),
 ("die Bescheinigung","الإفادة الرسمية","die","die Bescheinigungen","Ich brauche eine Bescheinigung vom Arzt.","أحتاجُ إفادةً من الطبيب","buero"),
 ("der Schalter","الشبّاك (في إدارة)","der","die Schalter","Gehen Sie bitte zu Schalter drei.","اذهبْ إلى الشبّاكِ الثالث","buero"),
 ("die Warteschlange","طابورُ الانتظار","die","die Warteschlangen","Die Warteschlange ist lang.","طابورُ الانتظارِ طويل","buero"),
 ("beantragen","يقدّمُ طلباً رسمياً","","","Ich beantrage einen neuen Ausweis.","أقدّمُ طلباً لبطاقةٍ جديدة","buero"),
 ("genehmigen","يوافقُ رسمياً","","","Der Chef hat den Urlaub genehmigt.","وافقَ المديرُ على الإجازة","buero"),
 ("ablehnen","يرفض","","","Die Bank hat den Antrag abgelehnt.","رفضَ البنكُ الطلب","buero"),
 ("die Gebühr","الرسم المالي","die","die Gebühren","Die Gebühr beträgt zehn Euro.","الرسمُ عشرةُ يورو","buero"),
 ("die Quittung","الوصل","die","die Quittungen","Heben Sie die Quittung auf.","احتفظْ بالوصل","buero"),
 ("der Vorgesetzte","الرئيسُ المباشر","der","die Vorgesetzten","Mein Vorgesetzter ist fair.","رئيسي منصف","arbeit"),
 ("die Einarbeitung","التأهيلُ الأوّل","die","","Die Einarbeitung dauert zwei Wochen.","التأهيلُ أسبوعان","arbeit"),
 ("die Fortbildung","التكوينُ المستمر","die","die Fortbildungen","Die Firma zahlt die Fortbildung.","الشركةُ تدفعُ التكوين","arbeit"),
 ("belastbar","قادرٌ على تحمُّلِ الضغط","","","Ich bin belastbar und ruhig.","أتحمَّلُ الضغطَ وأبقى هادئاً","arbeit"),
 ("die Teamarbeit","العملُ الجماعي","die","","Teamarbeit ist mir wichtig.","العملُ الجماعيُّ مهمٌّ لي","arbeit"),
 ("die Kenntnisse","المعارف / المهارات","die","","Ich habe gute Deutschkenntnisse.","لديَّ معرفةٌ جيدةٌ بالألمانية","arbeit"),
 ("sich vorstellen","يعرّفُ بنفسِه","","","Darf ich mich kurz vorstellen?","أيمكنني أن أعرّفَ بنفسي؟","arbeit"),
 ("nachfragen","يستفسر","","","Ich frage lieber nach, bevor ich anfange.","أفضّلُ أن أستفسرَ قبلَ أن أبدأ","arbeit"),
 ("sich melden","يتواصل / يبلّغ","","","Melden Sie sich bitte bis Montag.","تواصلْ معنا حتى الإثنين","arbeit"),
 ("die Rückmeldung","التغذيةُ الراجعة","die","die Rückmeldungen","Danke für Ihre schnelle Rückmeldung.","شكراً على ردِّكَ السريع","arbeit"),
 ("die Unterstützung","الدعم","die","","Ich brauche etwas Unterstützung.","أحتاجُ بعضَ الدعم","arbeit"),
 ("die Aufgabe übernehmen","يتولّى مهمّة","","","Ich übernehme diese Aufgabe gern.","أتولّى هذه المهمّةَ بسرور","arbeit"),
 ("der Zeitdruck","ضغطُ الوقت","der","","Unter Zeitdruck mache ich Fehler.","تحتَ ضغطِ الوقتِ أُخطئ","arbeit"),
 ("die Bewerbungsunterlagen","ملفُّ الترشّح","die","","Die Bewerbungsunterlagen sind vollständig.","ملفُّ الترشّحِ مكتمل","arbeit"),
 ("befristet","محدَّدُ المدّة","","","Der Job ist auf ein Jahr befristet.","العملُ محدَّدٌ بسنة","arbeit"),
]
A2_ALLTAG += [
 ("die Hausordnung","نظامُ العمارة","die","","Die Hausordnung hängt im Flur.","نظامُ العمارةِ معلَّقٌ في الرواق","wohnen"),
 ("die Kaution","الضمانُ المالي","die","die Kautionen","Die Kaution sind zwei Monatsmieten.","الضمانُ إيجارُ شهرَين","wohnen"),
 ("die Nebenkosten","التكاليفُ الجانبية","die","","Die Nebenkosten sind nicht enthalten.","التكاليفُ الجانبيةُ غيرُ مشمولة","wohnen"),
 ("der Hausmeister","حارسُ العمارة","der","die Hausmeister","Der Hausmeister hat den Schlüssel.","حارسُ العمارةِ معهُ المفتاح","wohnen"),
 ("der Aufzug","المصعد","der","die Aufzüge","Der Aufzug ist seit gestern kaputt.","المصعدُ معطَّلٌ منذُ أمس","wohnen"),
 ("der Keller","القبو","der","die Keller","Die Fahrräder stehen im Keller.","الدرّاجاتُ في القبو","wohnen"),
 ("der Balkon","الشرفة","der","die Balkone","Wir frühstücken auf dem Balkon.","نفطرُ في الشرفة","wohnen"),
 ("lüften","يهوّي","","","Bitte einmal am Tag lüften.","هوِّ الغرفةَ مرّةً يومياً","wohnen"),
 ("der Lärm","الضجيج","der","","Der Lärm stört mich nachts.","الضجيجُ يزعجُني ليلاً","wohnen"),
 ("sich beschweren","يشتكي","","","Ich habe mich beim Vermieter beschwert.","اشتكيتُ إلى المؤجِّر","wohnen"),
 ("die Sprachnachricht","الرسالةُ الصوتية","die","die Sprachnachrichten","Schick mir lieber eine Sprachnachricht.","أرسلْ لي رسالةً صوتيةً أفضل","kommunikation"),
 ("der Anruf","المكالمة","der","die Anrufe","Ich habe deinen Anruf verpasst.","فاتتني مكالمتُك","kommunikation"),
 ("besetzt","مشغول (الخط)","","","Die Leitung war besetzt.","كانَ الخطُّ مشغولاً","kommunikation"),
 ("die Ansage","الرسالةُ المسجَّلة","die","die Ansagen","Hören Sie die Ansage am Bahnhof.","استمعْ إلى الإعلانِ في المحطة","kommunikation"),
 ("weiterleiten","يحوّلُ رسالة","","","Ich leite die Mail weiter.","أحوّلُ البريد","kommunikation"),
 ("die Unterhaltung","المحادثة","die","die Unterhaltungen","Es war eine nette Unterhaltung.","كانت محادثةً لطيفة","kommunikation"),
 ("das Missverständnis","سوءُ الفهم","das","die Missverständnisse","Das war nur ein Missverständnis.","كانَ مجرَّدَ سوءِ فهم","kommunikation"),
 ("höflich","مهذّب","","","Bleib bitte höflich.","ابقَ مهذّباً","sozial"),
 ("der Vorschlag","الاقتراح","der","die Vorschläge","Das ist ein guter Vorschlag.","هذا اقتراحٌ جيد","sozial"),
 ("vorschlagen","يقترح","","","Ich schlage Samstag vor.","أقترحُ السبت","sozial"),
 ("zusagen","يقبلُ دعوة","","","Ich habe schon zugesagt.","قبلتُ الدعوةَ سلفاً","sozial"),
 ("sich bedanken","يشكر","","","Ich möchte mich herzlich bedanken.","أودُّ أن أشكرَكَ جزيلاً","sozial"),
 ("die Rücksicht","المراعاة","die","","Bitte etwas Rücksicht auf die Nachbarn!","راعِ الجيرانَ قليلاً!","sozial"),
 ("das Hochwasser","الفيضان","das","","Nach dem Regen kam Hochwasser.","بعدَ المطرِ جاءَ الفيضان","wetter"),
 ("der Frost","الصقيع","der","","Nachts gibt es Frost.","ليلاً يكونُ صقيع","wetter"),
 ("die Hitze","الحرّ الشديد","die","","Die Hitze ist kaum auszuhalten.","الحرُّ لا يُحتمَل","wetter"),
 ("die Vorhersage","التوقُّعاتُ الجوية","die","die Vorhersagen","Die Vorhersage verspricht Sonne.","التوقُّعاتُ تَعِدُ بشمس","wetter"),
 ("die Unterkunft","مكانُ الإقامة","die","die Unterkünfte","Die Unterkunft war sauber und günstig.","كانَ مكانُ الإقامةِ نظيفاً ورخيصاً","freizeit"),
 ("die Ermäßigung","التخفيض","die","die Ermäßigungen","Studenten bekommen eine Ermäßigung.","الطلبةُ يحصلونَ على تخفيض","freizeit"),
 ("die Sehenswürdigkeit","المعلَمُ السياحي","die","die Sehenswürdigkeiten","Wir besuchen die Sehenswürdigkeiten der Stadt.","نزورُ معالمَ المدينة","freizeit"),
]

NEUE_DECKS = [
 ("a1-essen-trinken", "A1", "الطعام والشراب والمطعم", A1_ESSEN),
 ("a1-koerper-kleidung", "A1", "الجسد والصحة والملابس والألوان", A1_KOERPER),
 ("a1-stadt-wege", "A1", "المدينة والتنقّل والاتجاهات والتسوّق", A1_STADT),
 ("a2-arbeit-buero", "A2", "العمل والإدارة والتعلّم", A2_ARBEIT),
 ("a2-alltag-dienste", "A2", "السكن والتواصل والمناسبات والطقس", A2_ALLTAG),
]

def main():
    v = json.load(open(P, encoding="utf8"))
    vorhanden = {c["de"] for d in v.values() for c in d["cards"]}
    alleIds = {c["id"] for d in v.values() for c in d["cards"]}
    n = 0
    doppelt = []
    for deckId, level, titel, zeilen in NEUE_DECKS:
        karten = []
        for j, (de, ar, art, plural, exDe, exAr, tag) in enumerate(zeilen):
            if de in vorhanden:
                doppelt.append(de); continue
            vorhanden.add(de)
            kid = f"vw-{deckId[:2]}{deckId[3:6]}-{j:03d}"
            assert kid not in alleIds, kid
            alleIds.add(kid)
            k = {"id": kid, "de": de, "ar": ar}
            if art: k["article"] = art
            if plural: k["plural"] = plural
            k["exampleDe"] = exDe
            k["exampleAr"] = exAr
            k["level"] = level
            k["tags"] = [tag]
            bild = re.sub(r"[^a-z]", "", de.split()[-1].lower().replace("ä","a").replace("ö","o").replace("ü","u").replace("ß","ss")) + ".png"
            if bild in BILDER: k["img"] = "/cards/" + bild
            karten.append(k); n += 1
        v[deckId] = {"id": deckId, "titleAr": titel, "level": level, "cards": karten}
        print(f"  {deckId}: {len(karten)} بطاقة")
    json.dump(v, open(P, "w", encoding="utf8"), ensure_ascii=False, indent=1)
    import collections
    c = collections.Counter(x["level"] for d in v.values() for x in d["cards"])
    print("أُضيفَ:", n, "| مكرَّرٌ تُجُنِّب:", len(doppelt), doppelt[:8])
    print("التوزيعُ الآن:", dict(c), "| المجموع:", sum(c.values()))

if __name__ == "__main__":
    main()
